### ISSUE TITLE
[Feature Request] More Quality of Life Advancements

### ISSUE THREAD

**Issue by judicius** [DarkPacks/SevTech-Ages#1025]
Either as a new Tab or as non-consequential Advancements in the stages things unlock.

An example would be backpacks and the upgrades. Or fishing traps and worm bait.

## Your Environment

* Modpack Version: 3.0.3
* Java Version: 1.80.161
* Launcher Used: Twitch
* Resourcepack Enabled?: Soartex
* Optifine Installed?: Yes / Sildurs shaders

**Comment by justinrusso** [comment]
The concept is to allow players to explore the mods rather than us telling you what to do. A less hand-holding approach.
