### ISSUE TITLE
Stripped Logs, Totem Spider and Bat

### ISSUE THREAD

**Issue by Scotsguy** [DarkPacks/SevTech-Ages#1064]
When sneaking along the edge of a stripped log (in my case oak) with a Totem with Spider and Bat on it, you get propelled very quickly, but only in Survival mode, and on specific sides.

This is probably something between the Step Assist, Totemic and weird Hitboxes on logs
## Steps to Reproduce
https://gfycat.com/gifs/detail/UnnaturalEarnestDartfrog

1. Make a line of stripped logs north to south
2. Place a totem with Spider and Bat
3. Sneak
4. Walk into the line
5. Possibly retry from different sides

Note: You have to be in Survival mode, Creative does not work.

## Your Environment

* Modpack Version: 3.0.3
* Java Version: 1.8.0_161, 64-bit
* Launcher Used: MultiMC
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by cheesealmighty** [comment]
Bug? _I think you mean feature._ :P

**Comment by justinrusso** [comment]
Going to mark this as stale. If this is still a thing in 3.0.7+ please let us know by submitting a new issue. Thanks!
