### ISSUE TITLE
Pickletweaks Dye doesn't work on Dog Collars

### ISSUE THREAD

**Issue by Targren** [DarkPacks/SevTech-Ages#1079]
## Issue / Bug

Tamed myself a couple of wolves, ground up a few flowers, and went to change their collars. But it doesn't work with the Pickle Tweaks dye powders. 

## Current Behavior

Right-clicking the tamed wolf with the dye just toggles the "sit" command.  I don't know if this is something that can be fixed in CraftTweaker or if it's a problem with the PT mod itself. 

## Steps to Reproduce (for bugs)
1. Tame a Wolf
2. Obtain a PickleTweaks dye powder (I used purple) 
3. Right-click wolf with dye powder. 

## Your Environment
* Modpack Version: 3.0.3
* Java Version: 1.8.0_161 (x64)
* Launcher Used: MultiMC 5 - 0.6.1
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Darkosto** [comment]
Hey @BlakeBr0 can we take a look at making this work with Pickle Tweaks?

**Comment by BlakeBr0** [comment]
![pepodance](https://user-images.githubusercontent.com/12994882/38116395-79acf8a8-3375-11e8-885f-8edce2eba279.gif)
