### ISSUE TITLE
Empty Bucket recipes not showing up in JEI, even when available

### ISSUE THREAD

**Issue by Targren** [DarkPacks/SevTech-Ages#1131]
## Issue / Bug

The recipes for empty buckets available at the current stage (at least up to stage 2) are hidden in JEI. 

## Current Behavior

Typing in "clay bucket" (stage 1), "Syrmorite bucket" (stage 2), etc..  or even just "bucket" into JEI displays bucket fill of liquids, but no recipes for several of the buckets themselves.  (This is hinted at in #1088) 

* Clay Bucket
* Weedwood Bucket

"Unfired Clay Bucket" does show up, curiously enough, as do vanilla buckets in Stage 2. 

## Possible Solution

Display empty bucket recipes when available. 

## Steps to Reproduce (for bugs)
0. Be at least in Stage 2
1. Open JEI
2. Type "Weedwood Bucket" 
3. Observe lack of recipe

## Context

This has led to some confusion and doing things the hard way, like thinking I had to explore the Betweenlands without rubber boots because the buckets weren't enabled. 

* Modpack Version: 3.0.3
* Java Version: 1.8.0._161
* Launcher Used: MultiMC 5 0.6.1
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by daddy77gaming** [comment]
@Targren I think those recipe come available once you unlock prereq.. as in my stage 2 i can see all 3 recipe, last to unlock was regular bucket once i got controlling advancement

**Comment by Targren** [comment]
I'm in stage two, none of them show up: only the various filled versions.

**Comment by daddy77gaming** [comment]
have you entered the betweenlands? chopped down some hardwood.. made some rope from swamp reed.. tried crafting the bucket. (top center the rope, then left and right center and bottom center the planks)
Can you see the stone bucket ( needed to make the bucket cast? )
type:  /gamestage info @p
what does it report back?

**Comment by Targren** [comment]
Yeah, I was in the betweenlands. I was able to make the bucket after I looked up the recipe on the BL wiki, but it doesn't show up in JEI. "Stone Bucket" does show up.

**Comment by Skullywag** [comment]
Just to add to this, im currently trying to do everything to get to the beneath to get black quartz to get axles to power my saw to get a turntable so I can finally get a bucket, so far this back has been BucketQuest. Is this right? or is there a way simpler way?

**Comment by WhisperFire26** [comment]
I have this same issue as well. I'm in Stage 2, in The Betweenlands and the buckets from the mod are viewable in JEI. There appears to be no crafting recipe. I am using version 3.0.7. Please advise.

**Comment by justinrusso** [comment]
This is fixed in 3.0.8. Specifically with 3effc5b67e9a57387ea28e75996274e67954d1db
