### ISSUE TITLE
Twilight portal generated under water

### ISSUE THREAD

**Issue by daddy77gaming** [DarkPacks/SevTech-Ages#1173]
Forge version: 14.23.2.2635
Twilight Forest version: 1.12.2-3.6.345-universal
Pack: SevTech Ages including optifine and SEUS shaders

Upon Entering the portal for the first time, i got teleported back to the overworld almost instantly again, took me a bit to realize i was pushed into the portal straight away on the other end.. then took me a while to not be ported back instantly.
Played quite a few packs with twilight in it, first time seeing this happen.

Also reported to twilight github; https://github.com/TeamTwilight/twilightforest/issues/465

![2018-03-31_13 25 26](https://user-images.githubusercontent.com/31905330/38163207-4b694be6-34f0-11e8-8c0e-e478e038feec.png)

**Comment by justinrusso** [comment]
Going to just close this issue. If its fixed it will be added. Please see the referenced issue for any further information.
