### ISSUE TITLE
[3.0.4] New Liquid slime doesn't have a crafting recipe

### ISSUE THREAD

**Issue by Gremilcar** [DarkPacks/SevTech-Ages#1212]
## Issue / Bug

New liquid slime has no recipe at age 4

## Current Behavior

Only recipe mentioning new liquid is the mixer ones that use it to craft different colors. Slimes in smelter generate blood.

## Possible Solution

Add a way to graft the liquid.

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 161
* Launcher Used: Native
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by justinrusso** [comment]
Ugh.. I only verified that slime liquid casted to slime...

**Comment by justinrusso** [comment]
@Darkosto I've created the slime recipe that Immersive Tech added. Should there be anything added that uses the slime balls to turn into it? Seems logical..

**Comment by justinrusso** [comment]
Just going to leave it as is.
