### ISSUE TITLE
Breaking Soul sand with nether wart ontop drops beetroot seeds.

### ISSUE THREAD

**Issue by ComaCanadian** [DarkPacks/SevTech-Ages#1274]
## Issue / Bug
When breaking soul sand with nether wart planted on top it breaks into beetroot seeds (and the soul sand). 
It should drop the nether wart as well. considering just breaking the nether wart itself yields the wart.

## Steps to Reproduce (for bugs)
1. place soul sand,
2. plant nether wart,
3. break soul sand

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8.0.161 64bit
* Launcher Used: jar
* Resourcepack Enabled?: no
* Optifine Installed?: yes
* Current Stage: 3

**Comment by timmit99** [comment]
Still exists! Rather annoying as breaking the soul sand with excavate was my plan for making a nether wart farm but now i just have a ton a beetroot seeds.

**Comment by Kelmey** [comment]
Can confirm this happens in 3.0.7

**Comment by justinrusso** [comment]
Will try to have this looked at before 3.0.8. This may have to be considered a known limitation.
