### ISSUE TITLE
Stacked buckets wont pull water from barrels

### ISSUE THREAD

**Issue by varadinn** [DarkPacks/SevTech-Ages#1281]
If you have stacked buckets in inventory and you try to get water from a barrel it wont pull the water till you unstack the bucket. I was using Iron buckets and trying to get water from the barrels and it wouldn't pull it until I unstacked buckets. 

## Your Environment

* Modpack Version:3.0.4
* Java Version:1.8.0
* Launcher Used:Twitch/Curse
* Resourcepack Enabled?:no
* Optifine Installed?:yes

**Comment by An-Sar** [comment]
Copy of my reply from the Primal issue tracker: this has something to do with detecting the bucket's fluid capability while it's stacked, i will need to do some testing to see what the best solution is.

**Comment by An-Sar** [comment]
this has now been fixed in dev and will be part of the next primal release (0.6.57)
