### ISSUE TITLE
Ocean Monument and the Aquisition of Prismarine Shards before Age 3

### ISSUE THREAD

**Issue by Mrrebelthefirst** [DarkPacks/SevTech-Ages#1290]
While exploring the world, in Deep Ocean Biomes there is supposed to be an Ocean Monument that spawns, not every one but if the world gen allows it should be there.

Currently in Age 2 there is a quest that needs you to craft a Stop Watch (Speed Run: The stopwatch will display information on the player's motion.)  The current recipe is gated behind having to acquire a Darkstone Button which is from Darkstone which from my knowledge is only found in Abyssal Craft's first explorable dimension.

To access that dimension you need to build a Gateway Key, in that recipe there is an Oblivion Catalyst, crafted in from a Necronomicon Ritual needing 4 Prismarine Shards.

Those Prismarine Shards are either found by killing the Guardians of the Ocean Monument or by crafting them using a Crystallization machine in Abyssalcraft (not craftable until more knowledge is gained and in Age 3) or lastly by a Hydrator (requires you to be Age 3 quite a distance up the tech tree.

Solution: Reinstitute the ability for Ocean Monuments to spawn and removing the 4 Gold Blocks inside of the Ocean Monument OR just leaving them in there since if you are down there you will have to be in armor and food wise ability to be there.  You cant get there on accident and survive with the Gold Blocks without being at such a armor and gear level of Age 2 armor.
 

* Modpack Version: 3.0.3
* Java Version: 1.8.0_25
* Launcher Used: Twitch Launcher?
* Resourcepack Enabled?: No.
* Optifine Installed?: No?

**Comment by ComaCanadian** [comment]
The ocean monuments do spawn. Keep looking.

**Comment by ChipmunkCraft** [comment]
Darkstone cobble can be obtained from the Darklands in the overworld. Put it in a furnace or grill to make Darkstone and craft into a button like a normal stone button.

As ComaCanadian stated, Ocean Monuments do spawn.

**Comment by shane3silbaugh** [comment]
The Hydrator from Cyclic allows you to craft a prismarine shard in version 3.0.6. Though JEI doesn't show recipes using the Hydrator when you hit 'U' on the machine, if you hit 'R' on prismarine shards it'll show a hydrator recipe.

JEI should probably be fixed so you can get to the prismarine shard from the hydrator recipe and the opposite, get to the hydrator from the prismarine shard. Because it's Very un-obvious how to craft it.

**Comment by justinrusso** [comment]
Ocean monuments do spawn
