### ISSUE TITLE
Astral sorcery resources

### ISSUE THREAD

**Issue by Waisse** [DarkPacks/SevTech-Ages#1292]
I'm currently in the Age 3. I understand that the pack is supposed to be difficult but so far there is a constant pattern of resources being easier to get/craft at some point, sadly this doesn't seem to be the case for most AS resources.

Glass pane can't be crafted any other way than a casting table, this is really annoying because they are used for some AS crafting.

Aquamarine : can only be gathered in The Beneath. Thankfully it's renewable with endgame AS, a minor annoyance since liquid starlight/lava interaction was disabled.

Starmetal dust : the quartz dust recipe is nice, thanks.

Starmetal ore : the most problematic resource. It really need an easier way to get at some point. Extremely annoying since the iron ore transmutation was disabled.

Modpack Version: 3.0.4

**Comment by SephirothWS** [comment]
I have to agree with the whole Starmetal Ore thing. Unless there's something I am missing, converting two starmetal dusts into a single ore for a single ingot and thus a single dust is rather lossy...

**Comment by Dutchs** [comment]
Starmetal Ore will be added back to Starlight Transmutation in 3.0.7, see #1792
