### ISSUE TITLE
Making Chowder dupes the bucket

### ISSUE THREAD

**Issue by iffonox** [DarkPacks/SevTech-Ages#1303]
As I was trying to get milk out of a bucket in stage two, I noticed a second bucket in the output when making chowder,

## Steps to Reproduce (for bugs)
1. Put a cooked fish, a milk bucket and two bowls in a BWM cauldron
2. wait
3. Get two buckets and two bowls of chowder

![2018-04-02_17 36 54](https://user-images.githubusercontent.com/4130675/38202663-c8472d92-369c-11e8-80a4-9a724b4df17b.png)
![2018-04-02_17 37 36](https://user-images.githubusercontent.com/4130675/38202664-c8649706-369c-11e8-8aca-97dcfef2eeae.png)

## Context
Free buckets! Yay?

Also there might be a staging issue here as you can make chowder in stage two, but milk buckets should only be available in stage three. On the other hand is this a way to get milk out of the bucket if you accidentally milked a cow before stage three.

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8.0_101
* Launcher Used: Twitch
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
Yup can confirm the bug will look into it.

**Comment by artdude543** [comment]
@primetoxinz as this is a recipe added by BWM is this something you could poke at? Not sure if I can fix this via the recipe scripts.

**Comment by KatharineRosewood** [comment]
I wish i searched for this bug in here first before making a video to show. :S

**Comment by justinrusso** [comment]
@artdude543 do you know if this was ever fixed?

**Comment by Jandakast** [comment]
This was fixed in 3.0.7 with the mod update.
