### ISSUE TITLE
Unable to Navigate "L" Gui

### ISSUE THREAD

**Issue by TurbaDux** [DarkPacks/SevTech-Ages#1309]
## Issue / Bug
When you launch the modpack, join a world/server, and open up the L quest menu type thing, you're supposed to be able to click around so that you can view the quests and such.

## Current Behavior
When I launch the modpack, go into a singleplayer world OR multiplayer server, and hit L, i'm not allowed to navigate the gui. I can't click to move the screen, at all.

## Possible Solution
Well, I changed my gui settings to small (I regularly play on auto which makes the gui very large - I have a 1080p wide monitor) and that allows me to be able to see all of the age 0 quests vertically. Since I know the pack evolves horizontally though, I don't know if I'm going to able to get very far.

## Context
Well uh, I'm trying to play the game. This is before I do anything in the game. Haven't even broken a block or moved and I still can't move around the gui, although I have also tried 

## Your Environment

* Modpack Version: 3.0.3
* Java Version: Version 8 Update 161
* Launcher Used: Twitch
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by daddy77gaming** [comment]
Just being that guy.. are you holding down left click and then move the mouse?

sidenote you can only move if there is more then the eye can see

**Comment by TurbaDux** [comment]
Yes - and when im using the auto gui-size setting, even just stage 0 has more than the eye can see. When I change the gui setting to small then I can see all of the stage 0 quests.

**Comment by Darkosto** [comment]
Are you aware that quests unlock as you go? You cannot move the GUI if the quests are not currently showing because you have not reached them yet.

**Comment by justinrusso** [comment]
Closing this issue as it has been quite a while. If this is still an issue please create a new one referencing this issue. Thanks!
