### ISSUE TITLE
Extra astral sorcery recipes not showing after update

### ISSUE THREAD

**Issue by Archaon-Zero** [DarkPacks/SevTech-Ages#1323]
Currently in stage 2. After updating from 3.0.3 to 3.0.4, the Starlight Crafting Altar+ recipes (starmetal ore, coal engine, etc) vanished from JEI. The interactions still work, but finding them in-game is impossible.

Other astral sorcery recipes, such as the necronomicon rituals, still show up.

* Modpack Version: 3.0.4 
* Java Version: 1.8.0_25
* Launcher Used: Twitch launcher, up to date
* Resourcepack Enabled?: Unity 1.12_plus (sometimes)
* Optifine Installed?: Yes ( SEUS v11.0, but not always on, because of graphic bugs)

**Comment by bumgrowth** [comment]
Same issue for me. No resource pack, using optifine but no shaders. Using Jar launcher.

This is currently keeping me from progressing. Can someone post the recipes here to begin with?

**Comment by Archaon-Zero** [comment]
Update:  The recipes appeared randomly after PC restart. Note that this wasn't the first restart since the problem occured. The PC had been turned off and on at least twice and minecraft itself at least 4 times. 

Maybe related to Minecraft's April Fools texture tomfoolery? Farfetched, but I can't think of anything else...

**Comment by Wipperwill** [comment]
According to JEI the only way to make an ingot of starmetal is with Ore. You can only make dust is with Ore or an Ingot. Also can get the dust on the surface of a Rock crystal deposit but that's very limiting.  Is there a way to make dust I havent mentioned?  Or where is Starmetal ore? I have  never seen it.

**Comment by PsyberMind** [comment]
As of 3.0.6, this is still present - Cannot progress out of Age 2 at this point, because there is no way to open the Twilight Forrest Portal without a Starmetal Ingot, which requires ore, and JEI has no recipe for it.

**Comment by bumgrowth** [comment]
@PsyberMind I fixed it by downgrading to 3.0.3 and then updating the mod again. Try that. If it doesn't work I will post the recipe for the ore for you instead.

**Comment by PsyberMind** [comment]
Still didn't work.. I went back to 3.0.6 after, recipe still not in JEI.. I got the recipe though.. I was able to make the ore.. Ok.. so that's one popular mod I've never played with started.. Twilight Forrest and Mod #2 here I come! (I've been so sheltered in Minecraft in the past LOL)

**Comment by justinrusso** [comment]
@PsyberMind Are you using optifine as well?

**Comment by MigukNamja** [comment]
The recipe *was* showing up for me in 3.0.6, then I changed Shaders back and forth, logged out and back into the server, and after all that, it disappeared. I couldn't figure out how to get it back. Maybe a restart of the client or a PC reboot would have fixed it. But, here's a screenshot of the recipe :+1: 

[https://i.imgur.com/4x90HCw.png](url)

- 4 Nocturnal Powder,
- 4 Illumination Powder
- 2 StarDust
- 2 Stone
- 1 Iron Cluster

**Comment by justinrusso** [comment]
I'd like to know if a restart of the pack would fix it

**Comment by PsyberMind** [comment]
Yea, that seemed to fix it
