### ISSUE TITLE
Tinkers Bolt cores are in stage 3 but the crossbow is in stage 2

### ISSUE THREAD

**Issue by Skullywag** [DarkPacks/SevTech-Ages#1324]
As per title, dont know which one is wrong but it makes no sense for them to be separate really.

**Comment by justinrusso** [comment]
Can you provide a screenshot? Everything I have is set for 2.

**Comment by daddy77gaming** [comment]
not really related but sort of :) 

my Kama cast is stage disabled.. tho does NOT say which stage.. which doesnt correspond with all the other items showing their stage #1312 

![2018-04-02_22 07 26](https://user-images.githubusercontent.com/31905330/38216343-d16a7d1a-36ca-11e8-9857-372d13f72a85.png)

**Comment by justinrusso** [comment]
Because its disabled :P

**Comment by daddy77gaming** [comment]
I know but other items say for instance cant use need stage four unlocked.. that kama cast doesnt state which stage i need

**Comment by justinrusso** [comment]
"disabled" because it is disabled. You cannot get it. That stage is used for disabling items.

**Comment by daddy77gaming** [comment]
almost cheesed it :) cant blaim me for trying

![2018-04-02_22 17 57](https://user-images.githubusercontent.com/31905330/38216758-24fb184e-36cc-11e8-85f5-f38c27f793ee.png)

**Comment by Darkosto** [comment]
Please do not jump in on an issue and add a completely different issue onto it. Kama issues are for another issue, not one about bolts.
