### ISSUE TITLE
Creative Fluid Tank takes 2M Slates

### ISSUE THREAD

**Issue by davqvist** [DarkPacks/SevTech-Ages#1336]
## Issue / Bug
The Creative Fluid Tank needs 4 Blood Tanks Tier 16. Each Blood Tank takes 327680 Blank Runes. As you need 4 and each Rune needs 2 Slates that is over 2M Slates for you. I get that this is a creative item, but even with autocrafting this will take an unreasonable amount of time to craft, IMHO.

## Context
This has affected me that I can't sleep because I will never complete the pack. PLZ FIX KAPPA

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 8 144
* Launcher Used: Jar
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by vadis365** [comment]
Get crafting then.

**Comment by 3jlowes** [comment]
Without testing how much time it will actually take, I would agree with vadis. I will take some time and do some calculations later and share my setup if that helps :D (by the way you can have many altars doing crafting, not only one)

**Comment by davqvist** [comment]
lol I don't need testing if I can do basic math. Even if each slate takes only 1 second to craft, making 2.6 M takes 30 days running non stop.

**Comment by SplitJugular** [comment]
bump this thread. recipe is unreasonable

**Comment by lawl281** [comment]
this is automatable.  well of suffering with like 12 witchs under each altar.  set up 5 altars and you are done in 6 days.

**Comment by Jandakast** [comment]
This was already reduced to using the Tier 10 tank.
