### ISSUE TITLE
[3.0.4] IE core sample rendering issue

### ISSUE THREAD

**Issue by Gremilcar** [DarkPacks/SevTech-Ages#1345]
## Issue / Bug
I am holding a core sample that has quartz vein 
![](https://i.gyazo.com/7d70d76fadd851ec5aa0aa7166b43ad1.png)

This is the same sample placed in OW. notice the top part (quartz isn't rendered)
![](https://i.gyazo.com/738051ec47f0107a3985df5a00e1b057.png)

## Current Behavior

At least quartz ore doesn't render well in core samples from Immersive engineering mod. Liquids and Teallite render properly.

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 161
* Launcher Used: native
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Gremilcar** [comment]
Bauxite core looks like there are no ores present. I am at age 4 Bauxite is unlocked

**Comment by daddy77gaming** [comment]
coal also has no texture

![2018-04-03_14 07 57](https://user-images.githubusercontent.com/31905330/38251191-0a3b42c4-3751-11e8-95b1-47e4558e2653.png)
