### ISSUE TITLE
Equipped Lurker Skin Bag from Betweenlands drops on ground upon death

### ISSUE THREAD

**Issue by ragehugs** [DarkPacks/SevTech-Ages#1357]
## Issue / Bug

Equipped Lurker Skin bags fall to the ground upon death.

## Current Behavior

When the player dies with an equipped Lurker Skin bag (any tier/size), the bag will drop to the ground. If the bag is in inventory, it becomes part of the grave.

## Possible Solution

Make bags not despawn, disable equip functionality, or add equipped bag to itemlist for graves if possible?

## Steps to Reproduce (for bugs)

1. Get Lurker Skin bag
2. Equip it via the Betweenlands keybinds (circle menu default C)
3. Die
4. Bag will drop next to grave

## Context

Equipped bag on ground will despawn. It seems that the Iron Backpacks equip functionality is disabled... perhaps for this very reason?

## Your Environment

* Modpack Version: 3.0.4 - Age 2
* Java Version: 1.8.0_161-b12
* Launcher Used: Twitch
* Resourcepack Enabled?: F32 Fanver
* Optifine Installed?: Yes

**Comment by 3jlowes** [comment]
Sounds like an issue with the Betweenlands. That mods rings also drop on the ground on death.

**Comment by daddy77gaming** [comment]
graves dont see them items.. same as for aether mod.. where your greaves etc dont, 

added nasty thing to that is if you have multiples amulets equiped and die.. the slots created are no longer there so you have to use the charm again to re-equip

**Comment by GoryMoon** [comment]
This is an issue with TombManyGraves as discussed here https://github.com/Angry-Pixel/The-Betweenlands/issues/557

**Comment by 3jlowes** [comment]
Thank you for referencing the post :D

**Comment by thephoenixlodge** [comment]
It's closed on the BL side because it's not an issue for them to solve, it's on the TMG side of things.
