### ISSUE TITLE
Astral Sorcery personal progression not updating after picking up Luminous Crafting Table

### ISSUE THREAD

**Issue by FlorisXll** [DarkPacks/SevTech-Ages#1362]
## Issue / Bug

What ideally would have to happen is that the personal achievements of a player in Astral Sorcery gets updated when picking up the crafting tables created by someone else. This way anyone can use the crafting tables.

## Current Behavior

It seems as though Astral Sorcery personal achievements are not affected when doing multiplayer: at this moment I am not able to upgrade any of the Astral Crafting Tables. However, I do have the advancements necessary, because someone else had crafted the crafting table which I picked up.

Because of this issue I cannot use the wand and upgrade the crafting table to the next stage whereas the other player is.

## Possible Solution

* We are not using Together Forever and only share items by holding it to get advancements. This way we can individually do most of the advancements of our one. However, I would be unsure if Together Forever would work as I have the necessary advancements.
* Without having knowledge of the codebase, one could make sure Astral Sorcery progress triggers when picking up the Luminous Crafting Table and upgrades of it (if this is the issue).
* Finally, performing the ritual for the Luminous Crafting Table may do the trick, but this is somewhat devious to do all over again.

## Steps to Reproduce (for bugs)

1. Let someone else craft the Starlight Crafting Table.
2. Pick up the Starlight Crafting Table (and make sure you get the advancement)
3. Try to upgrade to the Celestial Altar with the Resonating Wand (and make sure you have the right ingredients at the right position with the right altar setup!)

## Context

I would like to be able to craft items myself instead of having to call my budy and right click the altar with the Resonating Wand.

## Your Environment

* Modpack Version: 3.0.4 (issue also present in 3.0.3)
* Java Version: 1.8.0_25
* Launcher Used: Twitch Native Launcher
* Resourcepack Enabled?: -
* Optifine Installed?: -

**Comment by Jandakast** [comment]
This is more so an issue with how Astral Sorcery manages a per-player progression. It doesn't use advancements/achievements that can be synced easily and it saves a .astral file in the world\playerdata folder for each player. There are some Astral Sorcery commands that could potentially be linked as rewards for each of the steps. This would require someone going through each Astral Sorcery advancement one at a time and determining the Research/Constellation/Attunement state of the player after each step. Which will be rather time consuming and I'm not 100% sure Astral Sorcery commands are fine grained enough to do this.

**Comment by FlorisXll** [comment]
@ComaCanadian Thank you very much for the suggestion on the Scroll of written Expertise.
