### ISSUE TITLE
Blood Magic Living Armor

### ISSUE THREAD

**Issue by unclekakarot** [DarkPacks/SevTech-Ages#1383]
Seems to be a big bug with living armor

- Upgrades don't show up when you get them (Will only show when taking the chest piece off and putting in inventory or if you completely restart the pack they will show up while wearing the armor but won't update if given more upgrades)

- Most if not all upgrades do not work unless you completely restart the pack

Was going to just comment on https://github.com/Darkosto/SevTech-Ages/issues/1220#issue-310303446 and say what the exact problems were and ways to fix it but he closed it.

**Comment by justinrusso** [comment]
Not sure why it was closed...

So once the pack is restarted, the armor works fine?

**Comment by 3jlowes** [comment]
https://github.com/WayofTime/BloodMagic/issues/1142

**Comment by justinrusso** [comment]
@unclekakarot is this in single player or multiplayer?

**Comment by 3jlowes** [comment]
Oh and I closed #1220 because it is a blood magic issue. Not a pack issue. As long as blood magic is updated in 3.0.5 everything should be great.

**Comment by justinrusso** [comment]
Yeah... and thus its a pack issue.

**Comment by 3jlowes** [comment]
Well... not sure if the armor flashing was fixed in the latest version of blood magic as I saw no other issue reports on the blood magic issue tracker of this happening. I installed same version of BM that sevtech is using and JEI in a new instance and managed to reproduce. I was just saying its good to keep blood magic updated.

**Comment by unclekakarot** [comment]
Just tested in single player and everything seems to work just fine, so it seems like it's just a multiplayer bug

**Comment by Arphahat** [comment]
Just to confirm: I am seeing this in 3.0.7 in multiplayer.
