### ISSUE TITLE
Bundle of Arrows makes lost arrows

### ISSUE THREAD

**Issue by Serolar** [DarkPacks/SevTech-Ages#1391]
## Issue / Bug
Bundle of Arrows, usually, allows for the compression of countless arrows. and turning them back helps manage arrow stocks

## Current Behavior
turning a Bundle of Arrows back into arrows isn't possible right now. no result comes by putting the bundle in the crafting table

## Possible Solution
Making a shapeless recipe where the Bundle of arrows, transforming into hemp fibers, crafts 8 arrows

## Steps to Reproduce (for bugs)
1. Make a Bundle of Arrows, Hemp fiber in middle, arrows in the rest of the 3x3 crafting grid
2. Take Bundle of Arrows into a 2x2 grid's slot
3. Sob at no result

## Context
Being able to compress arrows can help in storage inside general chests, or when out and about.

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8.0_161
* Launcher Used: AT Launcher
* Single Player
* Resourcepack: Updated Minecraft Textures V2(Not April 1st resources)
* Optifine: No

Thank you for your time.

**Comment by justinrusso** [comment]
It would have to be a bundle -> 8 arrows. You'd lose the fiber.

Note for dev: Bundle of Arrows: `<betterwithaddons:bundle:1>`
