### ISSUE TITLE
RebornStorage Invalid Recipes

### ISSUE THREAD

**Issue by KAfable** [DarkPacks/SevTech-Ages#1401]
## Issue / Bug
- RebornStorage adds a multiblock crafter that stores CPU's and Crafting Storages similar to AE1's automated crafting process, however most of these recipes are invalid due to the removal of Refined Storage's microcraft process

## Current Behavior
- All of the autocrafting supplements added by RebornStorage have invalid recipes, specifically the
Crafting Frame
![image](https://user-images.githubusercontent.com/26587049/38310056-98b4593a-37e9-11e8-98b6-198c8d40b522.png)

Heat Conductor
![image](https://user-images.githubusercontent.com/26587049/38310065-a010ca74-37e9-11e8-9b59-7165cff2a2fe.png)

Crafting Storage
![image](https://user-images.githubusercontent.com/26587049/38310074-a688b66e-37e9-11e8-812f-12ab3bfc047d.png)

Crafting CPU
![image](https://user-images.githubusercontent.com/26587049/38310087-ab6b7f0e-37e9-11e8-82f1-1851b3f8c0c3.png)

## Possible Solution
- Similar to how you handled the other Refined Storage recipes, by replacing them with the AE2 equivalent microcrafting components

## Your Environment

* Modpack Version: 3.0.4

**Comment by artdude543** [comment]
I have this fixed in dev will be in 3.0.5 :)
