### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by vanko2oo1** [DarkPacks/SevTech-Ages#1405]
## Issue / Bug
Hi! My problem is that I can't get into the world. The game starts properly and there are no issues until I try to Enter a world. When I click it and it starts loading it just stays there between 10 seconds and a minute and then it crashes and all that is shown to you is "The game crashed. Sorry for your inconvenience". I would like help since I haven't played much modded MC and I couldn't find a solution on the net. Here are my logs tough I'm not sure if this is enough of them. https://pastebin.com/sx0fLmK9

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
No idea.

## Context
I can't load the world, meaning I can't play.

## Your Environment
* Modpack Version:3.0.4
* Java Version:
* Launcher Used:ATL
* Server/LAN/Single Player:Single Player
* Resourcepack Enabled?:If this asks if I have one then no, but if it's about me enabling something ingame then it's a no again
* Optifine Installed?:No

**Comment by vanko2oo1** [comment]
I forgot. My java is Version 8 Update 161.

**Comment by justinrusso** [comment]
```
[04/4/2018 18:31:13 PM] # An error report file with more information is saved as:
[04/4/2018 18:31:13 PM] # **USERSDIR**\Instances\SevTechAges\hs_err_pid17008.log
``` 
Please provide this log as well

**Comment by vadis365** [comment]
See #1385

**Comment by TheCyberBrick** [comment]
This is not the same as #1385. It is an Intel driver crash (oh who'd have thought), but this time not because of the BL rift.

**Comment by TheCyberBrick** [comment]
See https://bugs.mojang.com/browse/MC-32606 for potential solutions
