### ISSUE TITLE
Tier 2 - sack of storage 

### ISSUE THREAD

**Issue by kragnoth** [DarkPacks/SevTech-Ages#1412]
The sack of storage can be crafted at age 2 (thanks to redstone in twilight forest), but the recipe doesn't show up in JEI.

Steps to reproduce:
Attain redstone from a mound in TF
click U (default up-craft for jei recipes) and cycle through until you see the sack of storage recipe.

Note: It isn't terribly out of line with the golden iron backpacks bag (9x6 for golden bag, 11x6 for sack of holding) but it doesn't require much for crafting it.

**Comment by daddy77gaming** [comment]
sack of holding (not in JEI) recipe

![2018-04-04_22 12 06](https://user-images.githubusercontent.com/31905330/38335142-ae232a52-385d-11e8-86af-37217a487adc.png)

this are the stage 3 recipe's for the sack of holding.. (basicly a chest transporter)

![2018-04-04_22 08 37](https://user-images.githubusercontent.com/31905330/38334963-2554c046-385d-11e8-9f0f-fb49f14fcf09.png)
![2018-04-04_22 08 38](https://user-images.githubusercontent.com/31905330/38334969-277552aa-385d-11e8-9bbc-b7667f7025ce.png)

**Comment by artdude543** [comment]
This is not an issue in 3.0.6/7/8
