### ISSUE TITLE
Fibre Torches to Normal Torches

### ISSUE THREAD

**Issue by SonOfDiablo** [DarkPacks/SevTech-Ages#1425]
Placing a Lit Fibre Torch in The Betweenlands changes it to a Damp Torch, which you can put in a furnace/stone grill to make a vanilla torch.
It's probably not a big bug, but it does make it so that you can get vanilla torches without using coal.

* Modpack Version: 3.0.4

**Comment by TheCyberBrick** [comment]
Hm I forgot they could be turned back into lit torches. We'll probably do the same thing as with rotten food where it turns back into its original item. Not sure that's possible with furnace recipes though.

**Comment by WildFTW** [comment]
To be honest it seems like a very complex way of getting a vanilla torch cause you still have to use fuel to cook the torch in which you would waste fuel

**Comment by SonOfDiablo** [comment]
@WildFTW not if you use the Stone Grill.

It's not a fast process, but, it's a quite easy process

**Comment by vadis365** [comment]
There is an unlit version of the fibre torch in primal tech, I should be able to add some code to check the dimension and use the same event we use in BL to turn PT torches in to unlit ones. This seems like the most logical fix and will prevent the issue.

**Comment by flapee** [comment]
Ehhh guys, the whole discussion gets sidetracked by totem torch :D 
firesticks -> fire -> lit fibre torch -> totem torch -> no need for sulfur

**Comment by monodemono** [comment]
This has been implemented.
