### ISSUE TITLE
Crashed while exploring - can't load world

### ISSUE THREAD

**Issue by Zenith-One** [DarkPacks/SevTech-Ages#1436]
## Issue / Bug
Game crashed during terrain generation. Now loading that world immediately crashes to desktop.

## Current Behavior
- Expected behavior: The game doesn't crash due to a chunk generation/loading issue.
- Actual behavior: It does :(

## Possible Cause
According to the [crash log](https://pastebin.com/raw/fa3cLthP), it would seem that the game wants to load a chunk or entity for which the index is out of bounds. Beyond that, I'd have to look at the offending code for more of a specific idea.

## Steps to Reproduce (for bugs)
I have no idea. Generate a lot of new terrain quickly?

## Context
I was out exploring and died. No big deal! Except when I was following the death compass (on a more direct route), my game suddenly crashed. Upon trying to reload that world, the game immediately crashes.

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8.0_51
* Launcher Used: native
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Faithful 32
* Optifine Installed?: When the initial crash happened and first attempt to load the world again, yes. However, I removed Optifine to no effect.

## Other remarks
There are several other posts about the game crashing on load, but none of them that I saw seemed to mention an exception related to chunk management. If this ends up being a duplicate, I offer my sincerest apologies.

**Comment by Jandakast** [comment]
Try updating Java to 1.8.0_161, restarting your computer, and removing the resource pack.  It sounds ridiculous but I've had a couple issues recently with Minecraft crashes where I've needed to reboot my computer before I could reload a world after a crash.

**Comment by artdude543** [comment]
Hello!

This appears to be an older issue on an old version of the modpack. This issue may have been fixed in later versions of the modpack, so we recommend that you update! If however, you are still having the same issue.

Please re-file an issue following the template and provide as much detail as you can. 

Thanks in advance and thank you for playing SevTech Ages!
