### ISSUE TITLE
Tiny Pile of Iron Dust / Ironberries

### ISSUE THREAD

**Issue by Buldr1504** [DarkPacks/SevTech-Ages#1462]
## Issue / Bug
Hey Darkosto, first of all, thanks again for your amazing mod pack. 
I'm currently in Stage 2 and found a potential issue or a bit of a weird recipe: "Tiny Pile of Iron Dust"! Is it intended that there is no further recipe (in this stage) for this item? You can plant and harvest the Rustic Ironwood trees and put the Ironberries in a Crushing Tub and Drying Basin to get the Tiny Pile of Iron Dust, but you can't melt it in a Smeltery or put it in a Horse Press. The player needs to find iron in the world to even get the Crushing Tub, so it would be available anyways. Issue #706 could be the same, but I'm not sure. 

## Possible Solution
If you don't want the player to have access to iron through Ironberries in stage 2, wouldn't it be better to hide the Crushing Tub and Drying Basin recipe till the stage the player is actually able to obtain iron this way? It's really not a big deal, just a bit weird and confusing. 

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8.0_161
* Launcher Used: curse / twitch app
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Yes, Soartex Fanver Modded.
* Optifine Installed?: No.

**Comment by artdude543** [comment]
This is fixed in dev and will be removed completely. So you only will have the berry to eat! 😄
