### ISSUE TITLE
Iron Backpacks AND Improved Backpacks share the same role

### ISSUE THREAD

**Issue by silentstormpt** [DarkPacks/SevTech-Ages#1474]
Not a bug but rather a suggestion. The mods "Iron Backpacks" and "Improved Backpacks" work towards the same role, this makes one of them redundant. Here's a few suggestions:

- Share upgrade/crafting recipes with one another;
- Remove one of them;

**Comment by Jandakast** [comment]
I personally love the progression difference between them and think they are setup appropriately 

- Improved Backpacks have a higher storage capacity in the early game, takes less resources to get max tier, and is available starting in stage 0 
- Iron Backpacks have a higher storage capacity in the late game, takes more resources to get max tier, and is started in stage 2.
