### ISSUE TITLE
[Suggestion] Add Shelf Recipe using sidings

### ISSUE THREAD

**Issue by iffonox** [DarkPacks/SevTech-Ages#1476]
Currently the BiblioCraft shelves are only craftable using regular slabs. It would be nice to have a recipe that uses sidings from Age one onwards.

Adding a second recipe for each shelf or changing the current recipes to use slabWood would do that.

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8.0_101
* Launcher Used: Twitch
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No
* Optifine Installed?:

**Comment by WildFTW** [comment]
This could be added. Thanks for the suggestion
