### ISSUE TITLE
Shift Clicking "Iron Backpacks" Backpacks Allows for Nesting

### ISSUE THREAD

**Issue by erez22** [DarkPacks/SevTech-Ages#1488]
## Issue / Bug

If you try to place a backpack (with or without contents) inside another backpack from "Iron Backpacks" by dragging it, it doesn't let you (which suggests me that nesting them like that is not intended). But if you SHIFT click the backpack into the other backpack you are able to nest them.

## Possible Solution
Prevent the player from shift clicking one backpack into another.

## Steps to Reproduce (for bugs)

1. Open one of the backpacks.
2. Shift click the other backpack.

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 8 (update 25)
* Launcher Used: Twitch Launcher
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Yes, Faithful 32
* Optifine Installed?: No

**Comment by justinrusso** [comment]
Fixed in @7bf5fe5a8ea36410cbdccf3f10c712912abda3ee
