### ISSUE TITLE
[Suggestion] Change Stage 5 Desh Ore Advancement to Detecting Unrefined Desh

### ISSUE THREAD

**Issue by Vyraal1** [DarkPacks/SevTech-Ages#1516]
## Issue / Bug
Change the Desh Ore advancement in GalacticCraft to look for Unrefined Desh or `galacticraftplanets:item_basic_mars`, since it only looks for the silk touched variant of the ore (to keep it consistent with how the pack treats Silk Touch).

![image](https://user-images.githubusercontent.com/26587049/38431531-8a99e004-3992-11e8-95ef-80a95f7e3b59.png)

* Modpack Version: 3.0.4

**Comment by Stifling-Bossness** [comment]
I'll second this, as when I mined Desh ore, I did not get the advancement since I didn't use silk touch.
