### ISSUE TITLE
rustic brewing barrel issue

### ISSUE THREAD

**Issue by dublee68** [DarkPacks/SevTech-Ages#1521]
## Issue / Bug

 when placing water into the rustic brewing barrel using a syrmorite bucket, in the bucket output tab instead of an empty syrmorite bucket it returns an empty weedwood bucket. No problems if using an iron bucket.

## Expected Behavior

I'd expect to get an empty syrmorite bucket back
## Steps to Reproduce (for bugs)

1.
2.

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by MrHrulgin** [comment]
The same thing happened to me in 3.0.6.

**Comment by justinrusso** [comment]
Please submit a new issue if this still persists in 3.0.7. Thanks!
