### ISSUE TITLE
Immersive Petroleum Distillation Tower Miscount for Steel Scaffolding Slab

### ISSUE THREAD

**Issue by Fireztonez** [DarkPacks/SevTech-Ages#1526]
Hello Darkosto,
On the Immersive Manual, the Immersive Petroleum Distillation Tower have miscount for Steel Scaffolding Slab. The manual said needed 33 Steel Scaffolding Slab, but only 30 is needed for the construction.

Fireztonez

**Comment by Fireztonez** [comment]
https://github.com/Flaxbeard/ImmersivePetroleum/issues/108

**Comment by justinrusso** [comment]
Going to take this one off the tracker. Will get added when the mod updates, but low enough of a priority that this doesn't really need to be on our tracker.
