### ISSUE TITLE
Blood Magic - First rune of any given type not working

### ISSUE THREAD

**Issue by ArtOfCombat** [DarkPacks/SevTech-Ages#1529]
## Issue / Bug

The first rune of any type added to a blood magic altar does not affect the altar. I have 12 runes of self-sacrifice and one rune of capacity; I only get credit for 11 runes of self-sacrifice.

## Expected Behavior

All runes on a blood altar should affect the altar's behavior.

## Possible Solution

Not honestly sure if this one's intentional or not... If so, ignore?

## Steps to Reproduce (for bugs)

1. Make a tier-2 blood altar.
2. Compare with one rune of self-sacrifice v. none with a divination sigil.

## Context

I'm trying to make a 26000 capacity tier-3 altar, but this is going to take more iron than I allocated. Fixing this will make it easier to make powerful (and beautifully symmetrical) altars.

## Client Information

* Modpack Version: 3.0.4
* Java Version: 8.161
* Launcher Used: Twitch, .jar loader

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: Unknown, probably 8.161
* Operating System: Unknown
* Hoster/Hosting Solution: Unknown
* Sponge (Non-Vanilla Forge) Server?: No

* Additional Content Installed?: N/A

**Comment by predakanga** [comment]
Came to report this as well - turns out it's https://github.com/WayofTime/BloodMagic/issues/1260, fixed by Blood Magic 1.12.2-2.2.8-91

**Comment by predakanga** [comment]
@orville94Bailey Yep - I've been using BloodMagic-1.12.2-2.2.10-93 for a week or so with no problems

**Comment by artdude543** [comment]
This was fixed in an update to BM which was included in 3.0.7 of the pack 😄
