### ISSUE TITLE
[Question] Any way to change a biome to another biome?

### ISSUE THREAD

**Issue by unclekakarot** [DarkPacks/SevTech-Ages#1535]
## Issue / Bug
Been going through all of abyssalcraft to be able to get rid of darklands that has spread but while doing so have spread the dreadlands all over my main base in the overworld and have no way of getting rid of it. Talked to the dev of abyssalcraft and he has said he plans on adding a way to get rid of it but as of right now there is no way. Wondering if there is any mod that is in the pack that can change one biome to another?

Edit: Happened over night while the server was running: https://imgur.com/a/8QEUx
Kinda getting ridiculous

## Possible Solution
Maybe there is a way to make a ritual to get rid of it. Not sure if possible though

## Steps to Reproduce (for bugs)
If you wanna test for yourself, go to the dreadlands, get the dread plaque from the mobs hitting you, got to the overworld and the land will start turning to dreadlands.

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0_161-b12
* Launcher Used: ATLauncher
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Lyrad8791** [comment]
Would love to know a way to fix this myself as using worldedit and such to fix this isn't right. there is a ritual of cleansing that was removed in this pack, if that does as i have read it MIGHT be able to fix this.
