### ISSUE TITLE
Stage 5 wont unlock

### ISSUE THREAD

**Issue by steinjorn** [DarkPacks/SevTech-Ages#1539]
I completed the to the moon advancement, it gave all the fanfare and said i unlocked stage 5, but the advancmencts dont show up and when i do gamestage check 5 command, it says i dont have stage five.  i used gamestage add 5, says i unlocked 5, but still not there. and yes, i have already updated to 3.0.5

* Java Version:1.8
* Operating System:win 10
* Hoster/Hosting Soultion:single player
* Sponge (Non-Vanilla Forge) Server?:no

**Comment by dariumz** [comment]
Same problem, hoping its fixed in next version :)

**Comment by dariumz** [comment]
Same problem sadly.

**Comment by Darkosto** [comment]
Just an FYI, the stages are written out "five". When adding it back yourself you need to use that to get into the stage. Stage "5" does not exist.

**Comment by steinjorn** [comment]
ya i figured that out, but it still doesnt work

**Comment by Darkosto** [comment]
Can you be more specific? What does not work? Unlocking stage five? The advancement?

**Comment by steinjorn** [comment]
the advancements tab for stage 5 does not show up. but, i just went in and deleted the moon advanement out of the advancement save file, rocketed back to the moon, and it showed up. so it seems that the issue only affects games that completed the moon advancement before 3.0.5 like i had initially

**Comment by Darkosto** [comment]
After testing I was able to both gain Stage Five through advancements and also through the command "/gamestage add @p five"

Not sure what's happening in your worlds but I cannot reproduce.

**Comment by dariumz** [comment]
Yea manually fixed it by rewoking the moon achievement and then regranted it.

Tried flying back to the moon after rewoking didnt trigger, so had to manually grant.

**Comment by daddy77gaming** [comment]
How do you revoke the moon achievement and regrant it? only with edit of the file? not with a command? cause when pre update in 3.0.4 i went to the moon it stated stage 5 unlocked and i could see the items, but didnt get a new tab in achievement.. I'll go search for it and redo cause i guess i still need to do the dungeon anyways

**Comment by daddy77gaming** [comment]
stage5 advancements show up in my advancements JSON file.. but the tab doesnt show up in game. After /gamestage add @(me) five as well as messing with the json file

**Comment by dariumz** [comment]
you need the name of the moon achievement which is "triumph:stage4/moon".

Then use the /advancement rewoke command and after that the grant command.
