### ISSUE TITLE
Garden cloche for cotton

### ISSUE THREAD

**Issue by Waisse** [DarkPacks/SevTech-Ages#1562]
Cotton can't be farmed using IE garden cloche, I can only put the cotton seed in the soil slot but nothing in the seed slot. Cotton and sugar cane are used for making wool.

Sevtech 3.0.5

**Comment by Darkosto** [comment]
Will look to see if I can add this.

**Comment by kragnoth** [comment]
The helper functions are written into IE itself.  

This being an example:  https://github.com/BluSunrize/ImmersiveEngineering/blob/495e2c5365235881285909cff65e087f945fdc1d/src/main/java/blusunrize/immersiveengineering/common/util/compat/ActuallyAdditionsHelper.java

I think you would need to PR this into an update for natura compatibility.

**Comment by artdude543** [comment]
Going to tag this onto this issue now https://github.com/DarkPacks/SevTech-Ages/issues/2400
