### ISSUE TITLE
Immersivecraft has duplicate info

### ISSUE THREAD

**Issue by darkhax** [DarkPacks/SevTech-Ages#1587]
## Issue / Bug
ImmersiveCraft has double info for inventories in Hwyla/Waila

## Expected Behavior
Only one entry, not two.

## Possible Solution
Not sure what mod is doing this.

## Steps to Reproduce (for bugs)
Look at an immersivecraft thing with an inventory, like a shelf or a pile of sticks.

## Context
![image](https://user-images.githubusercontent.com/2250798/38460335-04ad6cac-3a75-11e8-9084-5f17a4112194.png)

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8_161
* Launcher Used: MultiMC
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
This is fixed in the mod update. But we can't update just yet due to block Id changes. So will have to hang fire on this on.
