### ISSUE TITLE
Astral sorcery saturation potions not working

### ISSUE THREAD

**Issue by steinjorn** [DarkPacks/SevTech-Ages#1597]
they do nothing at all.

* Modpack Version:3.0.5
* Java Version:1.8
* Launcher Used:twitch

**Comment by hellrage** [comment]
Neither do vanilla saturation potions in 3.0.4 and 3.0.6. Haven't checked in other versions.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
