### ISSUE TITLE
[Server 3.0.6] Can't change seed

### ISSUE THREAD

**Issue by lordammon** [DarkPacks/SevTech-Ages#1600]
## Issue / Bug

I have put the new 3.0.6 files over the 3.0.5 on my server and when I go to create a new world it is not using the seed -20608858170141219328 in the server.properties. Instead, it is using a different one. Each time I try to make a new wold is keeps using the following seed. -1048832949

## Expected Behavior

To use the seed I enter in the server.properties and not the same one each time I start the server.

## Steps to Reproduce (for bugs)

1. 
2.

## Context

Can't use a world that I have craeted in single player on our multiplayer server.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.6
* Java Version: jre1.8.0_162
* Launcher Used: Jar Launcher

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: no
* Optifine Installed?: no

## Server Information
* Java Version: java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
* Operating System: Debian
* Hoster/Hosting Soultion: 
* Sponge (Non-Vanilla Forge) Server?: yes
Just the basic SevTech Ages pack

* Additional Content Installed?: None

**Comment by artdude543** [comment]
When you run the `/seed` command in game. It will not display the full string/seed. As long as the seed is correct on the server.properties the world _should_ be generated with that seed. Example my server seed is a long string or mess same with my single player test world. And both the values are given from the command are not the ones in the config.

The other thing I could ask; are you trying to generate a new world or copy over an existing Single Player world? As both your OP and Context contradict each other. If your using a single player world you can't change the seed of that generated world once it's set in the level files that's generally it. You can specify the server config but I'm not too sure if it will take the value as the value is then set in the world files themselves.

In regards to a new server world; make sure you delete the world folder before booting the server and that the config is set correctly to the property: `level-seed=`. Then it will work fine. Otherwise if your still having issues this is a user error and not a pack error.

**Comment by daraku** [comment]
I don't know if he described it right, but it is not user error.  
We found a world in single player we wanted to use for the server, used the /seed command. copied the seed into the server properties file. started the server.  when the server starts it is not the same world from the single player. and the /seed does not match what we put into the server properties. 
We have tried deleting the world folder on the server, and even regenerating the server properties and re-adding the seed then. 

This worked fine in 3.0.4.

**Comment by lordammon** [comment]
What Daraku said is right, we would go into a world in singleplayer and spawn near a lake and mountain and then when we use that seed and generate a new wold on the server with it. When we enter that we are in the middle of a giant plains biome no lake or mountains and the seed is completely different.

**Comment by fuelhauler** [comment]
Sponge?

**Comment by lordammon** [comment]
fuelhauler what do you mean by that?

**Comment by iDarper** [comment]
easy fix: copy the single player world folder. copy it over to the server, rename it as "world" and problem solved.

**Comment by fuelhauler** [comment]
Would need to pregen chunks in SP before copying over world folder or any new chunks would still be messed with by Sponge, if that is the problem.

**Comment by daraku** [comment]
that would work, but only for the pre-generated area. as soon as some one left that area the chunkgen would be different. We are trying again with the official server pack that came out today to see if the problem persists. 
We were having to manually update the server from 2.0.5 to 2.0.6 from the client files before.

**Comment by lordammon** [comment]
Not using a Sponge server, just Forge running off of Debian Linux.

**Comment by lordammon** [comment]
Just did a fresh 3.0.6 server build off of my Windows PC. I changed the server.properties to have the level-seed=-20608858170141219328. Then I ran the Install.bat and then the ServerStart.bat and it is still using the same seed as on my Linux Server, Seed: -1048832949. Can we please get an answer on this.

**Comment by iDarper** [comment]
If the world gen option client side is set to realistic,  try seeing the
server side generator to quark_realistic  in the server properties.  (Same
thing)

**Comment by lordammon** [comment]
That is what we have done, those are both the default settings. It's very strange.

**Comment by lordammon** [comment]
Maybe someone out there could try to reproduce this?

**Comment by lordammon** [comment]
Server properties file:

#Minecraft server properties
#Mon Apr 09 15:52:56 MDT 2018
spawn-protection=16
max-tick-time=60000
query.port=25565
generator-settings=
force-gamemode=true
allow-nether=true
gamemode=0
dc_preset=Default
broadcast-console-to-ops=true
enable-query=true
player-idle-timeout=0
difficulty=1
spawn-monsters=true
op-permission-level=4
pvp=true
snooper-enabled=false
level-type=quark_realistic
hardcore=false
enable-command-block=true
max-players=20
network-compression-threshold=256
resource-pack-sha1=
max-world-size=29999984
server-port=25565
server-ip=
spawn-npcs=true
allow-flight=true
level-name=world
view-distance=10
resource-pack=
spawn-animals=true
white-list=false
generate-structures=true
online-mode=true
max-build-height=256
level-seed=-20608858170141219328
use-native-transport=true
prevent-proxy-connections=false
enable-rcon=false
motd=\u00A7d\u00A7oSevTech\: Ages Server\u00A7r - \u00A74v3.0.6
