### ISSUE TITLE
Vanilla Skeleton Horse trap moved into Age 2 instead of Age 0 or whatever it's in?

### ISSUE THREAD

**Issue by JackRuby1** [DarkPacks/SevTech-Ages#1611]
https://clips.twitch.tv/CourageousArborealBulgogiDerp
Maybe move back the skeleton horse trap to Age 2, as the skeletons spawn with bows, which can overpower a just starting out player.
FirstNecron even suggested that it might be a good idea, so blame him if it's not Kappa
Version: 3.0.6

**Comment by Targren** [comment]
Spider Jockeys may also still be spawning in Age 0, bows and all.

**Comment by justinrusso** [comment]
@Targren this is not related to the issue. As well, what you mentioned is already fixed in the latest update. (https://github.com/Darkosto/SevTech-Ages/issues/1087)

**Comment by Targren** [comment]
@justinrusso  Okay, thanks. 

Funniest thing I ever saw was when the jockey shot his spider (Guessing Mo'bends changed its hitbox or something) and the two of them were fighting it out while I just watched. I think that's when I fell in love with the pack. :)
