### ISSUE TITLE
Ghast Trap advancement not triggered after multiple traps.

### ISSUE THREAD

**Issue by Posivated** [DarkPacks/SevTech-Ages#1619]
Fought the Ur-Ghast, trapped him multiple times but advancement didn't trigger. I'm assuming it's because I had to replace the redstone and pressure plate since they were destroyed? Also I don't believe Ur-Ghast dropped a trophy or it was destroyed by fire?

**Comment by xZonTex** [comment]
The Ur-Ghost did not drop anything for me too, but in the middle of the tower a chest spawned with the items in it.

**Comment by Posivated** [comment]
I understand how it works and is why I said I trapped him multiple times, the achievement didn't trigger. I also just fought another one and trapped him again and still no trigger.

**Comment by SummitSummit** [comment]
Yeah, I didn't get the advancement either.  I used the climbing gloves and slime sling to skip most of the tower though, so perhaps there is a hidden progression unlock I skipped?

**Comment by Posivated** [comment]
The first time I did it I did everything in the tower, the other times I skipped the entire thing and just fought the Ghast.

**Comment by justinrusso** [comment]
I've seen the advancement work fine. If you happen to still have an issue please re-submit a bug report. Thank you!
