### ISSUE TITLE
Death from Sacrificial Dagger - No Grave, Death Compass points to area I didn't die at. 

### ISSUE THREAD

**Issue by Dystilled** [DarkPacks/SevTech-Ages#1620]
## Issue / Bug
Accidentally scrolled to sacrificial dagger instead of food and killed myself, on respawn had no grave at the point I died, and death compass points to a random area in my base about 50 blocks away. 

## Expected Behavior
No grave on respawn, random area marked by death compass

## Possible Solution
???
Possibly look into a command to recover last inventory? Number of bugs reported with missing/random location graves. 

## Steps to Reproduce (for bugs)
Die from Sacrificial Dagger next to tier 2 altar. 
![death bug](https://user-images.githubusercontent.com/36810196/38469455-67a04a7c-3b98-11e8-9c7c-33fd505f0e71.jpg)

## Context
Lost hours worth of gear. 
5
## Client Information

* Modpack Version: 0.5
* Java Version: Latest
* Launcher Used: Twitch
* Server/LAN/Single Player: SP 
* Resourcepack Enabled?: Soartex 
* Optifine Installed?: Yes

**Comment by LycanBlackpaw** [comment]
There is a command to restore death inventories. /tmg_restore (player name) (timestamp). You can tab to see the timestamps

**Comment by Dystilled** [comment]
Had no idea that command existed. 

Unfortunately doesn't seem to work for me. 

Tabbing doesn't show any time stamps and using 'latest' says Either the owning player is misspelled or the timestamp is invalid

I assume that means that a grave wasn't created which is the bug.

**Comment by Vyraal1** [comment]
Can confirm this just happened to someone else on my team. She died, the compass was pointing to her last death in the Abyssal Wasteland dimension, and not anywhere near the altar. We don't know how to reproduce this yet as trying it again properly registered the death.

The tmg restore command apprently doesn't work either, and I'm assuming if it did, it might not have had the death registered, as when she died, there wasn't a chat death message output to ther server about "soul becoming too weak". JourneyMap also did not have the death point marked down.

**Comment by Dystilled** [comment]
Yep, what Vyraal said is basically identical to what happened to me.

**Comment by nullKomplex** [comment]
Did you all have a charm of keeping on the initial death?

**Comment by popps73x** [comment]
version 3.0.6 singleplayer.  just had this happen to me.  at tier 3 blood altar died to the self sacrifice.  death compass pointed to a previous death (several sessions and days before) in the twilight.  tmg_restore gave me items from my latest death which was in the twilight since it did not log the death at my altar.  not sure if it is related but I had a "false" death message previously using the sigil of the blood lamp when I ran out of LP.  I got the death screen but when I pressed respawn I still had my inventory at the same spot in world.  I also had the red tilted body "Schrodinger's cat" as some call it.  reloging fixed the player render.

**Comment by thedoo** [comment]
Just had this happen this morning. No grave or death message. Didn't even spawn at my spawn point, respawned right where I died. Was wearing the Aevitas Mantle of the Stars, and not paying attention while holding down the sacrifice dagger, until it killed me. No Charm of Keeping that someone else mentioned.

### Client Information
    Modpack Version: 3.0.6
    Java Version: 1.8.0_171
    Launcher Used: MultiMC
    Memory Allocated: 8GB
    Server/LAN/Single Player: Server
    Resourcepack Enabled?: No
    Optifine Installed?: No

### Server Information

    Java Version: 1.8.0_162
    Operating System: Linux
    Hoster/Hosting Soultion: Nodecraft
    Sponge (Non-Vanilla Forge) Server?: No
    Additional Content Installed?: None

**Comment by justinrusso** [comment]
I have tried this multiple times and cannot get this to happen to me. I tried running around a bit to see if maybe that was the case, as well as trying different locations to stand at. No luck...
