### ISSUE TITLE
Shift key is "stuck" after changing dimensions while the key is held

### ISSUE THREAD

**Issue by justinrusso** [DarkPacks/SevTech-Ages#1634]
## Issue / Bug

When the player changes dimensions while holding down the shift key (as required for some portals) the players shift key is stuck being held.
## Temporary Solution
Pressing the shift key should resolve the issue when it is happening.

## Possible Solution

This is looking like it may be a bug with minecraft itself. I'm not sure what can be done to resolve this.

## Steps to Reproduce (for bugs)

1. Travel to a dimension while holding down the shift key while "triggering" the dimension change
2. Key should now be stuck. You can check by attempting to open a chest for example.

## Context
This is quite confusing to the player as they then think something is broken with misc. mods, though it is really just their shift key being held unintentionally.

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8u161
* Launcher Used: ANY

* Server/LAN/Single Player: ANY
* Resourcepack Enabled?: N/A
* Optifine Installed?: N/A

**Comment by Scodigy** [comment]
Not sure if this will help but I disabled my shader's (Sildur's) and optifine, then only right clicked into the portal and so far so good.

**Comment by bs2609** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/4974

**Comment by monodemono** [comment]
Fixed in https://github.com/DarkPacks/SevTech-Ages/blob/master/src/config/mputils/changelog.txt#L141
