### ISSUE TITLE
Stage 0 Tweaks

### ISSUE THREAD

**Issue by OriginalSuperGumby** [DarkPacks/SevTech-Ages#1643]
The advanced crafting table should be added shortly after the initial craft table.
The fishing strainers should be added just before the third hopper recipe that requires a shark tooth.
Awesome mod pack with a great staggered implementation.

**Comment by SteseDav** [comment]
If I was the pack developer, I'd be curious why you'd like your suggestions implemented... maybe it will help if you added that information?

**Comment by OriginalSuperGumby** [comment]
Well for the advanced crafting table, it's extremely useful. People new to the mod(s) may not go looking for it in JEI as the number of JEI pages grows quite quickly. Having made an extreme number of torches one at a time, it would have been useful to have known about this upgrade.
For the strainers, I think I'm just a doofus cause they are right there in the tree. Were they there in 3.0.4? Probably I'm just blind.

**Comment by justinrusso** [comment]
I think a bit of the idea behind the pack is that theres intended to be some "secrets" that reward you for looking closer. I appreciate the feedback 👍
