### ISSUE TITLE
Quantum Compressors Voiding 10k Items

### ISSUE THREAD

**Issue by Vyraal1** [DarkPacks/SevTech-Ages#1649]
## Issue / Bug
https://streamable.com/k7jj0
- Quantum Compressors cannot recognize items at the rate that a glowstone translocator inputs into, and voids items but doesn't acknowledge progress towards a singualrity

## Expected Behavior
- proper progress towards a singularity

## Steps to Reproduce (for bugs)
https://streamable.com/k7jj0

## Context
- This is needed to make singularities, and since these items usually require around 10k items, and due to how cheap Translocators are, it seemed like the most natural option to transfer large amounts of items into a compressor

## Client Information
* Modpack Version: 3.0.6

**Comment by artdude543** [comment]
Will be resolved in 3.1.0 😄
