### ISSUE TITLE
TogetherForever not syncing

### ISSUE THREAD

**Issue by ericrboidi** [DarkPacks/SevTech-Ages#1661]
## Issue / Bug
Together Forever not syncing advancements. Currently not working on the Gold & Iron advancements.

## Expected Behavior
Together Forever giving you all advancements made by team members.

## Steps to Reproduce (for bugs)

1. Make a server, and a team with two players.
2. Player 1 logs on, achieves Gold Standard
3. Player 2 logs on, tries force-syncing Gold Standard.

## Logs

* Client/Server Log: https://gist.github.com/ericrboidi/349a789813c728158aea76a4b9350bc3

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0_161
* Launcher Used: Twitch

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: 1.8.0_262
* Operating System: Win10 Pro
* Hoster/Hosting Soultion: Self-hosted
* Sponge (Non-Vanilla Forge) Server?: No

* Additional Content Installed?: No

**Comment by Skullywag** [comment]
I had to invite my friend to a team, sync, disband team, have him invite me to his team, sync, form then on syncing somewhat works when the other logs in and if it doesnt a /tf forcesync gets it to work.
