### ISSUE TITLE
Primalcore cosmetic stone variants uncraftable?

### ISSUE THREAD

**Issue by lemonbarking** [DarkPacks/SevTech-Ages#1672]
## Issue/Question?
All of the Primalcore stone types can't be crafted into their cosmetic variant ex. smooth/brick/pillar

I can't find anything in the configs about these being specifically disabled. Was there a kiln from this mod that was disabled that could exclusively cook its own stone or are these just gated beyond age 3?

Sorry and thanks for the great pack!

**Comment by artdude543** [comment]
I believe the recipe stage was an oversight. We'll look into this as soon as we can 😄

**Comment by Toksyuryel** [comment]
These blocks are all actually craftable, the recipes simply don't appear in JEI for some reason.

**Comment by lemonbarking** [comment]
That was my first thought and I checked that first thing b4 posting to no avail. I then saw a recent To Asgaard LP and he was able to craft them for his BM build. I don't know what version he was running when he recorded that though. I triple checked after I saw that using 3.0.6 but was unable to craft them. As artdude tagged though low priority. I'll be concerned if I bosd from not having them.

**Comment by ToAsgaard** [comment]
Your playing on single player correct?  In 3.0.6 the crafts still work for us on the server.  They dont show in jei, but they are still craftable.  However, it was discovered on our discord that those crafts do not work in singleplayer.  The recipes are basically missing but are included in the server files.
