### ISSUE TITLE
Disappearing Redwood saplings

### ISSUE THREAD

**Issue by djnifos** [DarkPacks/SevTech-Ages#1676]
## Issue / Bug

Growing them with a watering can causes them to disappear when they update.  

## Expected Behavior
Tree Growth

## Steps to Reproduce (for bugs)

1.  https://clips.twitch.tv/BenevolentPerfectMushroomWOOP

Maybe intentional??

## Server Information
CaptainQ & Darkphan's server

**Comment by justinrusso** [comment]
https://github.com/progwml6/Natura/issues/413

**Comment by justinrusso** [comment]
As a temporary solution, ensure that the center sapling is the one that "triggers" the growth and it will work. Youll have to bonemeal it and be ready to chop wood before you suffocate.
