### ISSUE TITLE
Cyclic Automated User Cannot Automate Starlight Infuser

### ISSUE THREAD

**Issue by Vyraal1** [DarkPacks/SevTech-Ages#1692]
## Issue / Bug
Cyclic automated user cannot place items into Astral Sorcery's infusion altar as shown here https://github.com/PrinceOfAmber/Cyclic/issues/766

I originally thought it was an issue with the mod but the dev cannot replicate in a smaller environment with just Cyclic and Astral Sorcery + some other mods, so I guess it might be a mod interaction.

## Expected Behavior
Working as shown in the video.

## Possible Solution
Don't know of a solution atm, I'll let you know if i come up with anything.

## Steps to Reproduce (for bugs)
See video in the issue linked.

## Context
Starlight Infuser recipes are pretty tedious and manual. And you need a fair amount of resonating gems for some recipes. The same also applies with Stardust.

**Comment by artdude543** [comment]
We don't have it disabled in the pack, and it's not blacklisted either. So this could a mod conflict or other issue. Will need to debug this further, however.

**Comment by Waisse** [comment]
This is really important because stardust is a crafting component for AE2 and other stuff. having a way to automate it would be great.

**Comment by PrinceOfAmber** [comment]
I will investigate again once next version of pack comes out - this was reported in 3.0.6

**Comment by Sorbe** [comment]
Similar problem using Cyclic's _Automated User_ to place _Netherrack_ into the AS _Lightwell_ in 3.0.7 SMP.

**Comment by Sorbe** [comment]
![2018-05-25_01 08 17](https://user-images.githubusercontent.com/7958470/40533628-39c00f68-5fb8-11e8-8444-ade0abc05e84.png)
![2018-05-25_01 08 20](https://user-images.githubusercontent.com/7958470/40533629-39dc56fa-5fb8-11e8-83af-9c387aa18159.png)

**Comment by Sorbe** [comment]
Maybe the "hidden user" for the _Automated User_ is not appropriately age advanced?

**Comment by Wigalot** [comment]
Just wanted to add this here. (similar issue with same machine but it is performing a different action(throwing)) The Automated User also has issues throwing eggs. They will only be thrown if the user is set to -1 in the height department, but visually they still appear to be flung out as if the machine is set to +1. If set to 0 or +1 eggs remain in the machines internal inventory and aren't thrown.

**Comment by NanoSlack** [comment]
From what I can see, the Automated User technically works with Lightwells, but it has some issues.

1. It does not appear to like Aquamarine's or Resonating Gem's (Think Liqued Magma to, as I previously tried that to generate lava - same for the Starlight Infuser, so rather sure it's the AU itself), if you use Rock Crystals(or Celestial's) it does insert them into/onto the Lightwell.

2. The power indicator on the right hand side has issues updating, (I recognize this should probably be a seperate issue, new Githubber here - forgive me) tried various cables including the Cycle ones.
It does get power properly as I had a Powercell connected and it shows drain when always on, stops the drain when turned to red-stone mode (Or use a Daylight sensor set to night).
The AU continues to operate when the bar is empty, but does not update the power indicator in the GUI.
I don't think this is a client-side issue either, as I'm not using any resource packs - just SevTech itself and I could get it to update the bar now and again, but that required replacing the blocks and wasn't always consistant.


Using SevTech 3.0.8.

**Comment by artdude543** [comment]
This is fixed for 3.1.0 😄
