### ISSUE TITLE
Magic Map no longer working after going back to the overworld

### ISSUE THREAD

**Issue by Kuperus** [DarkPacks/SevTech-Ages#1694]
## Issue / Bug

The magic map gets broken when taken to the overworld, it no longer updates for me in the Twilight Forest once a magic map has been taken topside.

I would expect it to keep on mapping and showing your location in the Twilight upon returning there

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:
[latest.log](https://github.com/Darkosto/SevTech-Ages/files/1895173/latest.log)

**Comment by daddy77gaming** [comment]
thats a very well known Twilight thing.. just leave it in a chest at the portal :)

**Comment by Hebbu** [comment]
Map fixes itself once you go back to Twilight forest and relog

**Comment by Skullywag** [comment]
chest doesnt work either, you have to relog.

**Comment by bs2609** [comment]
https://github.com/TeamTwilight/twilightforest/issues/427

**Comment by justinrusso** [comment]
This was fixed in a mod update. 3.0.7 should fix this. Please submit a new issue if the problem persists.
