### ISSUE TITLE
Crash on hitting "ESC"

### ISSUE THREAD

**Issue by lawl281** [DarkPacks/SevTech-Ages#1700]
## Issue / Bug
Sometimes randomly when hitting "ESC" the pack will give a java crash.  No minecraft crash log but does provide java crash log. Is a bug like this fixable? It never happened before latest version.

## Expected Behavior
Existing open GUI.

## Steps to Reproduce (for bugs)
This bug is very hard to force.  I can't determine if it is because I alt tab or what.  Sometimes it happens immediately after tabbing back into game and hitting "ESC" to return to playing.  Sometimes I will be playing for 30 mins+ press "ESC" to exit an inventory and it crashes.

## Logs
https://pastebin.com/M2Y8NR11
https://pastebin.com/97thfWQP
https://pastebin.com/aE4daiRp
https://pastebin.com/0CAYYUy4

## Client Information

* Modpack Version: 3.0.6
* Java Version: JRE version: Java(TM) SE Runtime Environment (8.0_25-b18) (build 1.8.0_25-b18)
* Launcher Used: Twitch
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: 1.12.2_HD_U_C9

## Server Information
* Java Version:  Will provide as soon as I get from server admin
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?: FTB Utils,

**Comment by MJRLegends** [comment]
This isn't a mod pack crash, its a java thing that can happen with any java application 

See https://www.google.co.uk/search?q=Failed+to+write+core+dump.+Minidumps+are+not+enabled+by+default+on+client+versions+of+Windows+%23&gws_rd=cr&dcr=0&ei=CHXPWqC1EoyEgAbuoo24Cg

**Comment by lawl281** [comment]
I am aware that it is a Java crash but I am not the only one on my server to have it happen and it has only started and 3.0.6

**Comment by justinrusso** [comment]
It also seems like you are running a very old Java version. Try giving that an update.

If you are still having issues and you believe its related to the pack, please submit a new issue. You could also speak with the community (https://discord.gg/darkosto) for any possible assistance with a general Java issue.
