### ISSUE TITLE
Environmental Tech Lonsdaleite

### ISSUE THREAD

**Issue by pennyvise1** [DarkPacks/SevTech-Ages#1708]
There is no apparent way to get Lonsdaleite (Unless it is generated from one of the void mining structures and not listed in JEI) which is required for every one of the modifiers for the resource miners and the nano beacon.

**Comment by bblay** [comment]
Can we confirm [this workaround](https://www.reddit.com/r/feedthebeast/comments/891mvn/ftb_revelations_180_environmental_tech_cant_find/) is safe?

**Comment by pennyvise1** [comment]
You can't regenerate the configs because they have been modified for sevtech, if you do that that miners will not be outputting the proper ores, they will be outputting the vanilla/modded that env tech would normally be outputting.... it might work but the weights and outputs will be wrong, to solve this until it is updated I just added lonsdaelite to the tier 3+ ore miner jsons at a weight of 2 which is fairly rare

**Comment by JustHeyo** [comment]
Just making sure this is known - normally, Lonsdaleite is generated only by the Void Ore Miners and isn't found in-world.  In my Revelations playthrough in a single-player world, I ran a tier 1 void ore miner for quite a long time (long enough to take IC2 from basic machines to 2 reactors and all-the-things) and got some of it, but not quite enough to upgrade to tier 2 as returns are slow and it is fairly rare.
