### ISSUE TITLE
Reset my advancements 

### ISSUE THREAD

**Issue by TomKing1** [DarkPacks/SevTech-Ages#1723]
![bingo](https://user-images.githubusercontent.com/38212845/38603742-59eb4c4a-3d66-11e8-93be-7177701ca829.PNG)

**Comment by TomKing1** [comment]
Gonna Just start from the beginning i was nearly at age 4 as well

**Comment by TomKing1** [comment]
@Darkosto Would it be possible to get a mod that backs up your world. ik its a big ask but JW

**Comment by TWJedi** [comment]
Did your game crash or you have to prematurely close your client? I ran into the same problem. I had to manually re-add all of my advancements to where I was.

Darkosto has said he won't add a backup mod to the pack. Pick your favorite and add it yourself. I added Aroma backup, and it has worked great.

**Comment by Jandakast** [comment]
Need more information. What were you doing? Did the game crash? Did you login in a different spot with different items in your inventory than when you logged out? Just posting a screenshot with no logs and no information is about as helpful as saying cheeseburger.

**Comment by edenprojectde** [comment]
Had the same happen to me after my Monitor lost it's life. I had to Shutdown the PC via physically disconnecting to the power source. 🤷‍♂️
