### ISSUE TITLE
Assorted Quartz showing on Ore Prospector but isn't visible in age 3. (3.0.6)

### ISSUE THREAD

**Issue by Posivated** [DarkPacks/SevTech-Ages#1738]
It's in a Limonite chunk on the surface, dug down, and nothing. This a bug or am I missing something?

**Comment by oISketcHIo** [comment]
Came across this issue as well. Found it while searching for coal in Age 3. Blocks ended up still just being stone, but when I went to ore excavate, it registered it as a vein of quartz, but didnt give the items. (Clearly cause we dont have access to them in age 3)

**Comment by artdude543** [comment]
This is fixed in either 3.0.7 or 3.0.8 but either way it's not happening anymore! :)
