### ISSUE TITLE
[3.0.6] Holding Right Click on Prospector Causes some checks to not occur

### ISSUE THREAD

**Issue by Marioluigi7896** [DarkPacks/SevTech-Ages#1742]
## Issue / Bug

While holding right click on my Tough dowsing rod, the checks worked most of the time but sometimes the check goes through without any message going to the chat.
[Clip](https://streamable.com/70b1u)
## Expected Behavior

The checks should all occur no matter how the right click button is held (So spam clicking isn't necessary)
## Steps to Reproduce (for bugs)

1. Get a dowsing rod and look at an ore
2. Hold Right click and move the mouse
3. See that some checks don't occur which requires spam clicking for accurate readings

## Context

I was looking for rock crystal ore in a chunk, excavated the whole layer and scanned every block, during that I found this

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0_161
* Launcher Used: MultiMC

* Memory Allocated: 8 GB

**Comment by Marioluigi7896** [comment]
Same occurs when you spam click with the prospector not being fully recharged

**Comment by Darkosto** [comment]
Interesting, I'll see if @PrinceOfAmber can check it out :)
