### ISSUE TITLE
Chisels and Bits Chiseled blocks rendering issues

### ISSUE THREAD

**Issue by Mario90900** [DarkPacks/SevTech-Ages#1749]
## Issue / Bug

Chisels and Bits Chiseled blocks seem to have a few issues on a server I am running for a few friends and I. It first started with some strangeness between the staged blocks mod and this one, as after logging back in and around chiseled stone bricks, they would look like they are masked to be Cobblestone again. This seems to be an extension of the greater issue of any blocks that can be masked (with the example of Vanilla Torches) will look like the masked block (in the example case, Fiber Torches) if you log in around them. This seems to be fixed in an area as soon as you just update a block around them and it renders everything as you should see it. But unfortunately this does not update Chisels and Bits Chiseled Stone Brick, which can only be fixed if you flip the rendering style from Fancy to Fast or the other way around. There is an example of my chiseled stone brick looking like cobble below, but as you can see, HWAILA or whatever its named points out that it is indeed Stone Brick that is chiseled.

The second issue is that sometimes, seemingly after a place is redrawn (the easiest way being to flip Fancy and Fast graphics again and the only one I have reliably tested causing this), sometimes it will just not render a specific chiseled block type in a line. In my examples below you can see the effects of this as it is probably easier to see it for yourself then to try and explain it. So far I have seen it happen with Rustic's Ironwood Planks, and my friend has had it happen to Chisel's Chiseled Dark Oak. When it does occur though, it seems specific to the shape of the chiseled block, if you add or remove a single bit the whole thing will render again - but as soon as you revert those changes, it will go invisible. It also may prefer like-shaped chiseled blocks for the line it follows? Though I am unsure about this, but it has happened to my wall and my friend's floor. It also appears that you need to be close by any of the chiseled blocks in question for any of the holes to appear in rendering, if you are further away (about 2-3 chunks maybe) from the blocks and flip the graphics around, it seems to not cause any holes. You seem to need to be in close proximity to them for any holes in rendering to appear.

Chiseled Stone Brick looking like Cobble: https://i.imgur.com/IFCYls0.png

Invisible Blocks: https://i.imgur.com/ZGPA8yA.png
It appears to only effect one block type at a time: https://i.imgur.com/60D1H5Z.png
## Expected Behavior

The expected behavior would be that everything renders as it normally should upon returning to a place or logging in.

## Steps to Reproduce (for bugs)

1. Setup a whole bunch of similarly chiseled blocks and stone brick.
2. Log out of the world or server.
3. Log back in and your stone brick should look like cobblestone.
4. Flick the graphics settings from Fancy to Fast and back again.
5. There may be a line of missing blocks in the array of chiseled blocks.

## Context

Trying to build walls/flooring for houses out of chiseled blocks, and server reboots causing us to log out and back in to witness everything happening.

## Logs

There are no logs associated with either issue unfortunately.

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0_45 64bit
* Launcher Used: Twitch

* Memory Allocated: 8 gigs, but the game seems to only register that 7 are allocated.

* Server/LAN/Single Player: Multiplayer Server
* Resourcepack Enabled?: Not on the client.
* Optifine Installed?: No.

**Comment by justinrusso** [comment]
If this is still an issue you have, please create a new issue referencing this one. I have not heard of this otherwise - possibly the Java version?

**Comment by Mario90900** [comment]
Ever since the 3.0.7 update, it seems to happen much less frequently, but it does happen rarely still - though not frequent enough to really worry about anymore. Plus both issues can simply be fixed if you just flip the graphics settings around when you are not nearby the chiseled stuff if it does happen again.  I probably won't open a new ticket unless it starts happening on each connection again. I figure an update to the staging mods or chisels and bits in 3.0.7 may have helped to fix it.

**Comment by justinrusso** [comment]
Odd.. maybe it's a weird graphics setting? No one else has mentioned this, seems like something fishy is going on.

**Comment by Mario90900** [comment]
No idea, but I do remember now that it seemed to also be related to the other issue of slimeboots not showing up when you first connect. Except that this issue extends to all fully-repaired armor, just is most visible on the slimeboots as they never get damaged. Whenever the chisels and bits blocks looked masked as cobblestone, the armor disappearing glitch was also occurring. This issue is probably related to that old kicking on first connect issue, in this case?

**Comment by justinrusso** [comment]
Hmm.. but the blocks are different if they are chiseled, so it shouldn't be caught by the block hiding mod.

**Comment by Mario90900** [comment]
I thought so as well, but when a friend came to visit in Age 1 before Stone Brick, both the solid blocks as well as the chiseled ones looked like Cobblestone to him. I figured it wasn't intended interaction with CnB, but maybe its somehow related to how CnB acquires the textures for the bits, and its able to pull the masked block before the game has a chance to load in your current age?

**Comment by justinrusso** [comment]
That would be pretty interesting if its somehow catching those blocks. If it is, then that would explain the issue. Performance did improve which helped ease those issues. Theres still some more to go on that though. Hopefully 3.0.9!

**Comment by Mario90900** [comment]
When I first was told about it, I did think it was super cool interaction even if it wasn't intended, and it really is kinda cool how it fits the theme of the pack. But yeah, hopefully future updates can be rid of it rarely popping up!
