### ISSUE TITLE
PrimalCore terracotta brick not usable to craft blocks

### ISSUE THREAD

**Issue by Ozzymud** [DarkPacks/SevTech-Ages#1755]
I have tried due diligence to the best of my ability here. My home area is littered with the Terra Clay. Digging it up produces Terra Clay Clumps. Smelting those gives Terracotta brick.

I have tried crafting these in a 2x2 grid, and tried placing 4 of them in the 4 quadrants of a 3x3 crafting grid (thinking maybe shaped recipe). Also tried 8 and 9 in a 3x3 grid. JEI shows nothing craftable with them, but does show several Terracotta blocks.

Tried getting some help from google. I see mention on GitHub that there was a bug with recipes. This was said to be fixed in 0.6.10 (https://github.com/An-Sar/PrimalCore/issues/115). SevTech 3.0.6 has PrimalCore-1.12.2-0.6.45 in it.

Am I just missing something? Pretty much copy/pasted from a reddit thread I started: https://www.reddit.com/r/feedthebeast/comments/8bpb6l/sevtech_terracotta_bricksblocks/  

Seems like these would be a perfect stage 0 building item just after getting the grill which the clumps can be smelted in to make brick ingots.

**Comment by Mario90900** [comment]
Yeah, there are a whole bunch of PrimalCore blocks that look pretty nifty to build with. Are they available later on atleast? I'm currently in Age 2 and they are still uncraftable, which seems odd considering they do look to be an early building material and have been visible for a long time. It appears the only one we can craft is the dried mud, while everything else seems uncraftable. I hope that this is something that can be added in sometime soon - It always confused me why we couldn't do anything with the Terracotta Bricks, and I have so much Terra Clay sitting around.

**Comment by Ozzymud** [comment]
From the reddit replies, everyone is saying scrap them as they never become available. So I'm hoping to see some minetweaker script type thing to add recipes for them. The blocks are already in the game so should be as simple as adding some recipes.

**Comment by ParadoxBomb** [comment]
Thinking along these lines, I'd love to see the rest of the decorative blocks enabled.

**Comment by egeis** [comment]
I tried the configuration @Dragonchampion, could not get it to work.  Seems to break the SevTech scripts and primal core defaults back to vanilla crafting recipies.  I tried inserting it to the addshapeless recipies script but that caused many of the recipies to break.

**Comment by artdude543** [comment]
The Primal Stones was fixed in this commit: https://github.com/DarkPacks/SevTech-Ages/commit/abcff6254e3eb4606e8d672953fa117bba8cde99 (for 3.1.0)
