### ISSUE TITLE
Get the advancement but did not unlock Age 2.

### ISSUE THREAD

**Issue by RealLith** [DarkPacks/SevTech-Ages#1767]
## Issue / Bug
 Got the advancement for Luminuos crafting table But did not unlock age 2

 https://imgur.com/a/fgpY0

## Expected Behavior
 As expected I get the advancement, But i do not unlock age 2

## Possible Solution
 N/A

## Steps to Reproduce (for bugs)

1. Craft a luminuos crafting table
2. Not get the age :D https://imgur.com/a/fgpY0

## Logs
Its not a crash

## Client Information

* Modpack Version: 3.0.6
* Java Version: latest
* Launcher Used: twitch

* Memory Allocated: 10gb

* Server/LAN/Single Player: server
* Resourcepack Enabled?: NO
* Optifine Installed?: NO

## Server Information
* Java Version: N/A (im not the owner)
* Operating System:  N/A (im not the owner)
* Hoster/Hosting Soultion:  N/A (im not the owner)
* Sponge (Non-Vanilla Forge) Server?: sponge

* Additional Content Installed?: N/A

**Comment by RealLith** [comment]
I am not in a team, I did try to relog, No i did not get the notification for age 2 (nor on the screen and not in the chat).
after i ran /gamestage info @p it said zero one one_mob tutorial

Not sure if this is intentional but in singleplayer after i have myself the advancement to foce myself into stage 3 it completed even the "I can't find a jungle" advancement even tho its blue (not a part of age quests) and after you use the command (to grant your self advancements) it only completes the advancements that are required previosly. So my guess would be that "i can't find a jungle" advancement is somehow connected to the  final luminuos crafting table advancement (since on the ser ver i did not complete "I can't find the jungle quest")

**Comment by RealLith** [comment]
NOTE: completed the "I can't find the jungle' on the server and it did nothing. so i guess i was wrong in my last message.

**Comment by RealLith** [comment]
completed every single quest in the age 1 advancement tab. Still nothing https://imgur.com/a/noTPs

**Comment by 2013emi** [comment]
a temporary fix that I've found and use on a server I play on is to have a member of staff run the commands /advancement revoke playername stage1/astable and then /advancement grant playername stage1/astable. we've had to do this a lot for many of the advancements

**Comment by Sharkske** [comment]
the commands are like this, that is if anyone wants to copy paste :)
/advancement revoke @p only triumph:stage1/astable
/advancement grant @p only triumph:stage1/astable
