### ISSUE TITLE
Vanilla Nether Quartz Ore has higher mining level than NetherEx Quartz Ores

### ISSUE THREAD

**Issue by SephirothWS** [DarkPacks/SevTech-Ages#1782]
## Issue / Bug
Currently in Age 3, Vanilla Nether Quartz Ore is unmineable with my current equipment.
![Image](https://i.imgur.com/sVq6SDg.png)
However, All of the NetherEx quartz ores are.
![Image](https://i.imgur.com/bZWFP4T.png)

## Expected Behavior
Vanilla Nether Quartz Ore should be mineable as NetherEx quartz ores are.

## Possible Solution
Drop the block hardness to the same as NetherEx Quartz Ores.

## Steps to Reproduce (for bugs)

1. Iron tools, Age 3.
2. Go to the Nether.
3. Find Vanilla Nether Quartz Ore
4. Become a sad panda to inability to mine it.
5. ¯\\\_(ツ)_/¯

## Context
As NetherEx Quartz Ores are mineable, this doesn't really pose a problem for me, but it is an inconsistency.

## Logs

* Client/Server Log: ¯\\\_(ツ)_/¯
* Crash Log: ¯\\\_(ツ)_/¯

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8, Update 161, 64-bit
* Launcher Used: Twitch

* Memory Allocated: 8GB

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Nope
* Optifine Installed?: Nope

**Comment by 3jlowes** [comment]
You just dont have high enough mining level. This is intended.

**Comment by SephirothWS** [comment]
@3jlowes So its intended that NetherEx Quartz is a lower mining level?

**Comment by SephirothWS** [comment]
If so, how does one raise their mining level then? #1711 prevents me from getting anything higher, unless I'm overlooking something...

**Comment by 3jlowes** [comment]
Soulforged steel is not Immersive engineering steel.
