### ISSUE TITLE
Mushroom stew / musroom stew duplicated bucket

### ISSUE THREAD

**Issue by TheLemein** [DarkPacks/SevTech-Ages#1785]
Just killed Lich, while in Age 2. Looking at next advancement "Mighty Stroganoff". Went to make Mushroom Stew which is 3 mushrooms a bowl, and Unfamiliar Item (which I guessed was milk) Milked a cow, and of course it drops the bucket, but with a full quick bar, it goes to inventory. I put that, the bowl, and mushrooms in cauldron for it only to return with Mushroom Stew, and 2 buckets in cauldron. I was then able to repeat this a second time

**Comment by justinrusso** [comment]
I believe this should be fixed. If the problem persists please submit a new issue.
