### ISSUE TITLE
Low FPS While playing SevTech on shaders, on normal minecraft its like ~200

### ISSUE THREAD

**Issue by Aquuil** [DarkPacks/SevTech-Ages#1786]
Hello,

I have problem with fps. I have good computer but fps sits on 50-60 but when I destroy grass for example it drops to ~20-30 :/

![screenshot_3](https://user-images.githubusercontent.com/38355248/38743704-0ec5b33c-3f40-11e8-952c-df282a582c23.png)
![screenshot_4](https://user-images.githubusercontent.com/38355248/38743705-0ef2a086-3f40-11e8-90a3-eb2b8a0e346b.png)

**Comment by 3jlowes** [comment]
Pc specs? Not a lot of info given

**Comment by Aquuil** [comment]
Well i thought the info on F3 screen will be enought info about my pc specs (on right) :P 
[DxDiag.txt](https://github.com/Darkosto/SevTech-Ages/files/1908029/DxDiag.txt)

**Comment by Aquuil** [comment]
Also look at this guys, the graphics processor take almost 100% on minecraft O.o
![screenshot_5](https://user-images.githubusercontent.com/38355248/38749297-698443fe-3f51-11e8-86ba-c153221a4a83.png)

**Comment by 3jlowes** [comment]
The solution is to disable shaders. Im not entirely sure why it was "popularized" with this pack. I just dont see the appeal with shaders.

**Comment by Aquuil** [comment]
Turned off shaders and the fps drops are even more often :D

**Comment by Shock2k** [comment]
Did you ever try turning motion blur off?  There are other settings that can be tweaked further.  Also turn "mipmap level to 0".  That fixed a lot of issues for me.

**Comment by Aquuil** [comment]
Yeah, motion blur is turned off, also mipmap level is on 0, I turned off extra leaves, grass and falling leaves aswell, the problem is that when im destroying something fast (like grass to get string) im getting big fps drops.

**Comment by justinrusso** [comment]
As @3jlowes stated, the suggestion would be to play without them. We cannot help you with shaders and is considered unsupported for the pack. If you still need help, you can try talking with the community in our discord: https://discord.gg/darkosto
