### ISSUE TITLE
A bunch of items in Age 2, that require items from Age 3. Plus 1 item recipe problem

### ISSUE THREAD

**Issue by JackRuby1** [DarkPacks/SevTech-Ages#1790]
**Better With Mods in age 2:**
anchor - 2 different recipes, ingot (age 1) and plate (age 2)
pulley - (says in age 1) item from age 3
bloody sapling - (says in age 1) items from age 3
filament - (says in age 1) items from age 3
dynamite - item from different age

**Better with Addons Age 2:**
Gold Matchpick - items from age 3

**Iron Chests in Age 2:**
Iron Chests - has silver chest and silver chest upgrage in age 2, no silver available until 3

**Cyclic age 2:**
Merchant Almanac - requires emerald
Water, Antidote, Speed charms - diamonds/emeralds/nether wart.
Spawn Detector - items from Age 3 in recipe.
Garden Scythe - items from age 3 in recipe
Spawner Seeker - items from age 3 in recipe
Engraved thunder - items from age 3 in recipe

**Dark Utilities Age 2:**
Portal charm -  both recipes require items from different ages.
Sneaky block/lever/torch/false block/obsidian/pressure plate - all  needs item from age 3
Lore tag - 35835/11 diamond
null charm - showing in age 2 - https://gyazo.com/1e2f534ec5f0041f2c1dd88c8def0dec
Focus Sash - showing in Age 2 - https://gyazo.com/cf3f2c422a2d4dfd93525b1d20346954

**Astral Sorcery Age 2:**
Mantle of the Stars - Horologium, Armara, Lucerna, Pelotrio items from different ages.

**Bibliocraft Age 2:**
Fancy Lantern, and Fancy Lamp -  both varieties of Iron and Gold both require glowstone, which is age 3

**Blood Magic Age 2:**
Demon will aura gauge - item from age 3 in it

**Chisel Age 2:**
Antiblock - requires glowstone from age 3

**Mekanism Age 2:**
Tin dust
Copper/Tin/Iron/Gold clumps
Dirty Clusters Copper/Tin/Iron/Gold
Copper/Tin/Iron/Gold shards
Copper/Tin/Iron/Gold Crystals

**Rustis Age 2:**
Advanced Alchemic Condenser + Retort - item from Age 3 in it.

**Storage Drawers Age 2:**
Concealment Key - item from age 3

**Tinkers' Construct Age 2:**
Fancy and normal Golden item frame - requires obsidian

Version 3.0.6
Server: No

**Comment by JRiebling** [comment]
For a couple of these, it's relevant to consider that Glowstone can be acquired from the Twilight Forest in Age 2.

**Comment by Arphahat** [comment]
The glowstone, however, isn't displayed in JEI in Age 2. I've not really explored TF much, but will it let it remain in inventory in Age 2, or kick it?

**Comment by JackRuby1** [comment]
You can craft the antiblock in stage 2 it seems, but how can you craft with something if you don't know what it is?

**Comment by JRiebling** [comment]
So long as you, the player, know what the item is and can keep that item in your inventory using a method like the one I stated above, you can then place the item in a crafting table where it belongs in recipes. This is particularly easy with things that are readily identified visually, such as glowstone or diamonds (the latter of which are obtainable as soon as you can go to the first Abyssalcraft dimension).

Of course, it's up to you whether you consider that cheating or breaking progression. And I fully support the recipes being made consistent with the materials used to make them.
