### ISSUE TITLE
Some coal veins have no below grade coal AT ALL

### ISSUE THREAD

**Issue by Sorbe** [DarkPacks/SevTech-Ages#1791]
I've noticed a possible problem with the surface coal markers. Some of them have no ore at all. Only happens with coal. One had 7 markers and exactly 1 ore block at the surface.   I've seen this now on 3 separate "bogus" coal veins that actually had nothing below grade.  Even the dousing rod confirms no coal ore in the entire chunk with a full scan vertical from the surface (48 deep from low plains surface and coal does not spawn below that; plus I mined them to bedrock and scan laterally too).

Only happens with coal ore veins so far.

**Comment by sarcastic6** [comment]
Hmm, maybe this is another person experiencing https://github.com/Darkosto/SevTech-Ages/issues/1707?

**Comment by ShaneCourtrille** [comment]
I'm also finding this.  Running a server and I think the person in #1707 who thinks it has to do with Y levels is correct as the area my coal markers were at was only at Y level 73.

**Comment by LadyRyl** [comment]
I am playing on a server and have had this happen as well. 2 coal chunks with no coal below grade and 1 gold chunk with no gold.

**Comment by justinrusso** [comment]
The speculation in https://github.com/Darkosto/SevTech-Ages/issues/1707#issuecomment-381320216 sounds somewhat plausible. It wouldn't surprise me if Geolosys does something weird and chooses to generate in an extremely non-ideal area. If this is the same, possible a report can be made to fix such situations or we adjust the max Y level to ideally mitigate the issue.

**Comment by justinrusso** [comment]
Have not been hearing much on this issue lately, and we have had updates to Geolosys since. Maybe this has helped it. If you are still having problems, please submit a new issue and reference this one.
