### ISSUE TITLE
Can't creating/loading world when additonal mouse button was assign

### ISSUE THREAD

**Issue by leosia** [DarkPacks/SevTech-Ages#1797]
## Issue / Bug
When I'm assigning additional buttons from mouse (button 4, button 5) world is not creating or loading, I can assign buttons during the game but I need to reset buttons before I quit it. One solution for this was to disable ImprovedBackpacks mod, but then recipes was messed up, like for example planks can be created with vanilla way.
Another issue with this was that when I change assigning a buttons during the game and then I want to quit it, minecraft "normaly" quit but Java process is still running and taking the same amount of RAM (for me was 8GB) but processor using was aroung 1%.
Game not crashed only stop loading.

## Possible Solution
None

## Steps to Reproduce (for bugs)
1. Start a game
2. Assign a buttons for Sneaking to Mouse button 4 and Sprint to Shift button
3. Load or create a world

## Context
Can't create/load world

## Logs
https://pastebin.com/index/Rb35nsTZ
It's the end of log, pastebin have a limit, if more is needed I will place it here.

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0.161 and version from Twitch 1.8.0.025
* Launcher Used: Twitch and ATLauncher
* Memory Allocated: 4GB. 8GB. 12GB, 14GB
* Server/LAN/Single Player: None
* Resourcepack Enabled?: None and Soartex_Fanver_Modded_Universal
* Optifine Installed?: yes and no (logs are with optifine)

**Comment by leosia** [comment]
#1044 was closed but not fixed

**Comment by justinrusso** [comment]
#1180
