### ISSUE TITLE
Dire Wolves spawn in bases

### ISSUE THREAD

**Issue by Xavfire** [DarkPacks/SevTech-Ages#1801]
## Issue / Bug
Behavior: Dire Wolfs from the Mod EnderRoot Zoo spawn inside of bases. In my case, they spawned on Concrete(Chisel), Birch Wood(Minecraft), Marble Bricks(Chisel) inside of 50x70 Rooms with the height between 2 and 4. The Rooms had the light level at every point above 7. The biome where i build the base in is Extreme Hills.

Suggestion: Change the block where they spawn on to Dirt, Grass, Gravel or Stone, so that they don't spawn on player build structures. 

## Expected Behavior
It was expected that Dire Wolfs can't spawn everywhere at anytime.

## Possible Solution
Workaround for me was the deactivation of Dire Wolf spawns until it gets fixed.

## Steps to Reproduce (for bugs)

1. Create a Room 50x4x70 in a Extreme Hills Biome, light it fully up
2. You will notice that Dire Wolfs spawn

## Context
I tried to build a base and had Dire Wolfs spawning inside of my base wich was fully light up. I was unable to go AFK inside of my base because Dire Wolfs could spawn, roam around and kill me.

## Client Information

* Modpack Version:3.0.6
* Java Version:1.8.0_161
* Launcher Used:Twitch (Jar)

* Memory Allocated:6 GB

* Server/LAN/Single Player:Server
* Resourcepack Enabled?:No
* Optifine Installed?:No

## Server Information
* Java Version:8
* Operating System:Win 10
* Hoster/Hosting Soultion:Hosting
* Sponge (Non-Vanilla Forge) Server?:No

* Additional Content Installed?:No

**Comment by DerpityDoo** [comment]
Now that I have a void ore miner to AFK I am starting to see this problem more. I left the game on for about 10 hours and came back to aver 30 direwolves in my 3x3 chunk base.  
![2018-04-14_17 26 00](https://user-images.githubusercontent.com/37868135/38774027-7e3390a8-4009-11e8-975b-aab3fd67ea9f.png)

**Comment by mitchej123** [comment]
Culprit: https://github.com/PrinceOfAmber/ERZ/blob/master/src/main/java/teamroots/emberroot/entity/wolfdire/EntityDireWolf.java#L100-L102

This would need to be changed to a config option, or removed and allow the super class's behavior which I believe would default to standard hostile spawning light rules.

**Comment by artdude543** [comment]
@PrinceOfAmber could you chime in on the comment above for me? ^_^

**Comment by Wigalot** [comment]
Additional info: I also have bears and rats spawn in my base, as well as the wolves so not isolated to just wolves.
