### ISSUE TITLE
Assembler Auto Crafting Stage-Gate Barrier 

### ISSUE THREAD

**Issue by Soaryn** [DarkPacks/SevTech-Ages#1803]
## Issue / Bug
https://clips.twitch.tv/WonderfulGentleWormDoritosChip
Similar to the issue of #1733 but poses more of a automation barrier for some setups.

## Expected Behavior
Assembler from Immersive Engineering is an auto crafting table for 3 different items at a time. Should be able to craft things the player knows about (POSSIBLY more)

## Possible Solution
If there is a way to link a specific assembler to a player. Be careful merely whitelisting the fake player as it is a crafting bench and COULD craft things gated farther than the player.
If it is not a unique fake player per Assembler, then I would recommend syncing it to the farthest player on the server.

## Steps to Reproduce (for bugs)

1. Build Assembler from Immersive Engineering
2. Use a recipe that is gated behind anything in Age 1 or beyond

## Context
When using the assembler from Immersive Engineering to auto craft items, it would seem that the recipes that are gated behind stages are not craftable: IE, Iron Sheet Metal slabs to blocks where as sheet metal slabs are craftable at any stage..

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0_91
* Launcher Used: Twitch App
* Memory Allocated: 6GB

**Comment by artdude543** [comment]
@BluSunrize or @malte0811 is there anything that could be done in regards to this? Like, take the player name of who built the structure? I don't think there could be a way to use a custom player name for highest progression as then we'd need a way to change an internal name in the mod.

But the player name taking sounds like a more objective way of solving this solution maybe?

**Comment by BluSunrize** [comment]
We don't really account for that, no. The assembler just goes through available recipes, factoring in a player has never been necessary...

**Comment by artdude543** [comment]
Yeah; I never thought about this issue could be a thing as other crafters in the pack are going to have the same issue in regards to the fake player being stuck at Age 0. I'm not too sure on what could be done in regards to this as this is out of my knowledge range for modding.

**Comment by DerpityDoo** [comment]
If no better solution can be found then you could just gate a different crafter to each age, assuming they don's all use the same "fake player".

**Comment by BluSunrize** [comment]
Oh so your problem is being stuck in Age 0. I thought you had the issue of people craftign stuff too advanced :'D (I didn't read this well this morning)

If you've got a decent idea how to handle this, I'd want to look into it. But I'm not sure a player's name is enough? I don't know how SevTech's gating system works, and I can't store the whole player data...

**Comment by darkhax** [comment]
This would be the area of RecipeStages which is done by @jaredlll08. That said, for this to work, the TileEntity would need to pass a player instance which has the stages unlocked with our API. In GameStages itself there are some areas of the code which will also fail on fake players, which was partially intended but doesn't need to be. 

I've been discussing a refactor of the GameStages API for a while now that will potentially break compat with some addons. Perhaps Blu and some others could help me work out a way to add stage support to tile entities and fake players.

**Comment by M3wM3w** [comment]
Please.. want to make an assembler cake factory so bad >.>

**Comment by Jandakast** [comment]
No, the Assembler isn't even a fake player, it's a container and attempting to stage the container hasn't worked. We are still looking into it and will fix it once we can.

**Comment by sk2048** [comment]
This issue is fortuitously resolved by BluSunrize/ImmersiveEngineering@1ba6025 so long as the container is given the relevant stages.

**Comment by Dominic1DL** [comment]
IE is at 0.12-92 please update to finaly fixe this Issue

**Comment by Squ-Cog** [comment]
updating the mod to my server gives a crash (3.1.2 hotfix 1)
[crash-2020-01-24_22.58.44-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/4110943/crash-2020-01-24_22.58.44-server.txt)
