### ISSUE TITLE
Astikoor carts just vanish

### ISSUE THREAD

**Issue by Nightcaste** [DarkPacks/SevTech-Ages#1812]
## Issue / Bug
I was building a road, so I had a horse and cart full of materials.  I would build a section of road, then go ride the horse forward, build another section.  I never hit the hotkey to disconnect the cart, but the cart did become disconnected from the horse.  got back on the horse to go reconnect to the cart, and the cart had simply disappeared.

## Expected Behavior
I would expect the cart to not disappear

## Steps to Reproduce (for bugs)
1. I don't know, but this is the second time I've had a cart evaporate today.

## Context
It has affected me in that I have lost a significant amount of time and building materials because something just ceased to exist

## Logs

* Client/Server Log:  Pastebin will not accept the log due to size, not sure what to cut to bring the size down
* Crash Log:  This did not cause a crash, so I do not have a relevant log.

## Client Information

* Modpack Version:  3.0.6
* Java Version: 161
* Launcher Used:  Jar launcher via twitch

* Memory Allocated:  6GB

* Server/LAN/Single Player:  Server
* Resourcepack Enabled?:  No
* Optifine Installed?:  No

## Server Information
I am neither the server owner, nor server administrator, I don't know how to get access to this information.

* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:  none that I am aware of.

**Comment by XepherX** [comment]
+1

had a cart come loose without hitting the action key, due to getting stuck. trying to reattach made the cart disappear.

**Comment by Omniwrath** [comment]
I had a similar experience. I was moving to a new base, the terrain between bases was kind of bumpy. I put my valuables in a cart and started towards the new base. Once I got there, I disconnected the cart and checked inside. There was nothing in the cart. I figured it was a graphical glitch, so I logged out and back in. Upon logging back in, the cart had vanished entirely. Presumably the cart got stuck somewhere along the way and disconnected from the horse, but after hours of searching, I am unable to find it.

**Comment by lesteenman** [comment]
This happened to me too, but I was lucky enough to find it. Lucky, because apparently the cart does not just get disconnected, but the whole cart just drops as an item, along with everything in it. By pure coincidence, I saw the items in the high grass.

This likely happened because the cart/horse got damaged by a venus flytrap. I'm playing sevtech ages.

**Comment by Nightcaste** [comment]
It's not a matter of finding it.  Read the title.  The cart *ceased* *to*
*exist*.

**Comment by lesteenman** [comment]
And you're 100% positive it's not just the same; The cart dropping down as an item, and likely disappearing after a certain time because of item despawns?

**Comment by Nightcaste** [comment]
If it had dropped as an item it would have barfed all of my building
materials all over the place
