### ISSUE TITLE
World Biomes Not Generating in 3.0.6

### ISSUE THREAD

**Issue by oxlBEASTlxo** [DarkPacks/SevTech-Ages#1836]
## Issue / Bug
 When updating to 3.0.6, a lot of objects in the world changed to other blocks (ex. random RS controllers in the forests, iron chests changed to something that looks like a export bus type thing, Betweenlands portal turned into some brown liquid). After making a new world in 3.0.6, there are only 4 different biomes that generate, a very green field (flower field maybe), a normal forest, a menril tree forest, and a seasonal forest.  This has occurred in 5+ different worlds on single player and server.  Reverting to 3.0.4 to make a new world shows correct world generation.

## Expected Behavior
 The world should generate all the biomes, like swamps, dark oak forest, etc.

## Steps to Reproduce (for bugs)

1.Create a new world in 3.0.6

## Context
 It makes progressing not possible in the pack and also corrupted my age 3 world.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:3.0.6
* Java Version: 1.8.0_161
* Launcher Used: twitch
 
* Memory Allocated:8gb

* Server/LAN/Single Player: single and server affected
* Resourcepack Enabled?: no
* Optifine Installed?: no

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by Aquuil** [comment]
Yup have same, created today like 20 worlds on creative mode and couldnt find any biomes from mods (like darklands etc)

**Comment by justinrusso** [comment]
Sounds like either a world corruption issue or your pack install is bad

**Comment by 0xb00b** [comment]
Ive started a new world in 3.0.6 specifically for the new biome generation, at first i thought darklands wasnt generating either but its just a lot harder to find now, i can def confirm it does generate, you just have to get into the right temperature band.

**Comment by justinrusso** [comment]
The biome is now in general easier to find. Its in a guaranteed band. You just need to go north or south, then east or west. Its more predictable than prior.

**Comment by Aquuil** [comment]
But how to check that im heading noth or south ? :P im minecraft newbie.

**Comment by justinrusso** [comment]
Sorry I deleted your comment - as I stated I dont want this going further off topic.

I believe a map would be obtainable by that point, as well as just the direction of the sun. Theres likely other methods, as well as new items that appear later on in the game as well that will assist you in finding dimensions.
