### ISSUE TITLE
Endless Fatal Loop (Log Spam)

### ISSUE THREAD

**Issue by PsyberMind** [DarkPacks/SevTech-Ages#1837]
Issue: Endless Error Loop

Context: After leaving the Twilight Forrest (Age2), Simply returning to base, and I noticed I was getting slight frame stutter. I checked the console log, and it was reporting an error that seemed to be in an endless loop, I had to close the world, otherwise the log would just fill my hard drive eventually, and after a short time, MultiMC ignored the log all together in the console, it was writing so fast

Not sure what's causing this. I went into TF, started the Labrynth, and Died Running with the Bulls... recovered my gear, left and ported out, that's when the issue started. I do notice that I had a little tick lag, but I attributed that to the TF itself, I always lag in there..

A Client Restart fixes it, but I'm curious as to what caused it in the first place

Latest Log (Snipped, as the Fatal Error just repeats itself into infinity)
https://pastebin.com/txSHEAwD

Somehow I doubt this will be repeatable

## Client Information

* Modpack Version: 3.0.6
* Java Version: jre1.8.0_151
* Launcher Used: Ported from Twitch to MultiMC
* Memory Allocated: 9GB
* Server/LAN/Single Player: SSP
* Resourcepack Enabled?: Inviticus Modded Universal
* Optifine Installed?: Yes, No Shaders (They lag TF something aweful)

Added ClientSide Mods: Twitch Integration for Chat Tweaks

**Comment by PsyberMind** [comment]
Happened again. It looks like, from what I can tell, the only way to stop it is a complete pack restart with a force quit. Trying to go back to the menu screen locks up the client all together

**Comment by SteseDav** [comment]
Hi, couple of bits to try - 

1. Remove optifine
2. Remove the resource pack
3. update your version of Java and force the launcher to use the latest (https://docs.google.com/document/d/e/2PACX-1vR5muyi1m7Zy_qSwrzeb9e3tbbRlksguNUb_Pvm3pn9eDpsIkUj5qQUq6WFPPdEoVWZq91WvvH57KzC/pub)
4. Check your allocated RAM is not more than Half of your available RAM in the machine. 

Regards,
