### ISSUE TITLE
[Recipe Error] Blood magic - Wrong meta for Bound Blade - Broken sword

### ISSUE THREAD

**Issue by tjsd** [DarkPacks/SevTech-Ages#1844]
## Issue / Bug
Age 3 creating a bound blade with blood magic returns it as broken. 
Seems to be meta tag error in the recipe.

Also even when I cheated in an unbroken one and used it to slay mobs, I do not get blood shards. The sword is supposed to apply a weakness debuff to mobs, but that does not seem to happen and I get no blood shard drops.

## Expected Behavior
When you recieve the bound blade its supposed to be unbreakable. 
When slaying mobs with the bound blade I expect to get blood shards.

## Possible Solution
Change recipe for bound blade to be the correct version to get a blade that works. Blood shards, unsure, is "potion" effect disabled on mobs in age3?

## Steps to Reproduce (for bugs)
1. Use binding reagent on arcane ash crafting circle.
2. Use Gold Sword on circle
3. Get broken sword

1. Get a proper sword from JEI Cheat mode
2. Bind it to you and activate it
3. slay mobs
4. get no shards
5. get sad :(

## Context
To get to Tier 4 blood altar you need blood bricks, they are created with blood shards.

## Client Information
* Modpack Version: 3.0.6
* Java Version: 8.0 64bit 161
* Launcher Used: MultiMC
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: 1.8.0_161
* Operating System: Ubuntu
* Hoster/Hosting Soultion: My own server'
* Forge Version: 2651
* Additional Content Installed?:
DiscordIntegration-mc1.12.2-3.0.5.jar
TickProfiler-1.12-0.0.2.jar 
qutilities-1.12-0.6.26.jar

**Comment by tjsd** [comment]
Update, I did manage to get some blood shards! Drop rates seems very low, but that could just be me. Worth testing. I got no shards in Beneath or Hunting Dim. But got a couple in darklands.

**Comment by JRiebling** [comment]
I'm getting a decent amount of shards with mine, though I did have to give it Looting 3. Mainly farmed in the Beneath and Overworld, and it works in both of those places. That's with the proper version, which I too cheated in from NEI after crafting the "Broken" one. That said, I never tried using the "Broken" one, and the sword isn't supposed to take damage, so I don't know if the "Broken" one gets shards.

**Comment by lemonbarking** [comment]
The "broken" one created using the gold sword work exactly like the one created with the diamond sword/cheated in. It's only a tooltip error and has no effect on the item or it's functions. I'm using the gold sword version in 3.0.6 just fine, enchants and blood shards included.

**Comment by justinrusso** [comment]
Increasing the offsset of "broken" in pickletweaks for these swords should be enough to stop these tooltips from appearing.

**Comment by Jandakast** [comment]
Pretty sure this is fixed. Please open a new issue if it still happens after 3.0.8 is released.
