### ISSUE TITLE
BloodMagic Tanks (Bucket Mode) Not working

### ISSUE THREAD

**Issue by Phantum** [DarkPacks/SevTech-Ages#1856]
## Issue / Bug
The Tier 2 Bloodmagic Tank  (Blood Tank Tier 2) deletes liquids if you try to use it as a bucket.  (at least with starlight,) I'm off to work so I can try other fluids when I get home.

## Expected Behavior
Contents of tank should increase as liquids are added to the tank (by right clicking while holding tank

## Possible Solution
Unknown at this point.

## Steps to Reproduce (for bugs)
Pickup Blood Tank Tier 2, walk to lightwell, and right-click when the lightwell has liquid starlight in it!
1.
2.

## Context
Was running around grabbing liquid starlight from about 15 lightwells and then realized that I didn't get any of the liquid starlight, felt bad man!

## Client Information

* Modpack Version: 3.0.5
* Java Version: 8u161
* Launcher Used: TwitchApp
* Memory Allocated: 10GB
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Soartex Fanver
* Optifine Installed?: No

## Server Information
* Java Version: 8
* Operating System: Linux
* Hoster/Hosting Soultion: Nodecraft
* Sponge (Non-Vanilla Forge) Server?: No
* Additional Content Installed?: MCLink for Subscriber Whitelisting

**Comment by IChris2698I** [comment]
I also experienced this. I used a Blood Magic tank (tier 4 or 5 I think), on another of the same tier tank. I was hoping they'd swap, but it deleted the liquid starlight in the placed one without adding it to the one in my hand. Not a big loss, and it's probably a Blood Magic bug.

**Comment by TehNut** [comment]
Solved via https://github.com/WayofTime/BloodMagic/commit/da8e43a8b494df393687af91415a69f8b10db227. Should be built in the next few days. I have a few more things I want to get into the next version.

**Comment by Phantum** [comment]
Thanks :)

**Comment by artdude543** [comment]
This is resolved in 3.0.7 _(how this issue was missed not sure xD)_
