### ISSUE TITLE
Backpacks Item dupe

### ISSUE THREAD

**Issue by ihop2100** [DarkPacks/SevTech-Ages#1865]
## Issue / Bug

Duping items

https://clips.twitch.tv/PluckyPlayfulPanFUNgineer

## Expected Behavior

Backpack interface to close when put into offhand or when dropped

## Steps to Reproduce (for bugs)

1.open a backpack
2.put backpack into off hand with keyboard shortcut
3.put backpack into inventory with keyboard shortcut in a different spot
4.drop backpack
5.take items from interface

## Client Information

* Modpack Version:3.0.6
* Java Version:8
* Launcher Used:ATLauncher
* Memory Allocated: 4GB

**Comment by justinrusso** [comment]
Hey @gr8pefish was this fixed?

**Comment by gr8pefish** [comment]
No sorry, I forgot about it. I'll copy this issue over to my bug tracker so that doesn't happen again 😅

**Comment by PrinceOfAmber** [comment]
I dont think the item is in the modpack, but `cyclicmagic:storage_bag` can cause the same dupe. 

Only with using quarks F feature and throwing the bag, same steps to replicate.

**Comment by justinrusso** [comment]
This issue also exists in Iron Backpacks https://minecraft.curseforge.com/projects/improvedbackpacks/issues/9

**Comment by justinrusso** [comment]
@gr8pefish @PrinceOfAmber Just tested this with Betweenlands' Lurker Pouch and the pouch prevents even a Player Interface from causing the dupe. Might be worth checking out how they handle it?

**Comment by DreenDex** [comment]
@justinrusso There is no known dupes in the latest Impreved Backpacks. Most possible problems was fixed.
I am informing you here because you can't see issue status as we moved our issues to GitHub.

**Comment by artdude543** [comment]
This seems to be resolved with my testing. If this is still an issue please re-make the issue when 3.1.0 comes to the public. Thanks!
