### ISSUE TITLE
Storage Drawer Key in Offhand causing Crash

### ISSUE THREAD

**Issue by Lomare** [DarkPacks/SevTech-Ages#1868]
## Issue / Bug

Storage Drawer Key in the offhand causes crash when planting sapling in Bonsai Pot

Note: The drawer key in the offhand is normally used to pre-lock storage drawers while placing them,
Which for a large bonsai farm seemed appropriate at the time.

## Possible Solution
  Removing the key from the offhand resolves the issue

## Steps to Reproduce (for bugs)

Equip a storage drawer key in offhand.
Place a Bonsai tree hopper pot down (chest or ground makes no difference)
Place a Sapling (Oak in my case) into the planter pot.
Crash Occurs.

Simply remove the storage drawer key from your offhand and this crash will no longer occur.

## Logs
* Server Log: [debug.zip](https://github.com/Darkosto/SevTech-Ages/files/1913307/debug.zip)
* Crash Log: https://pastebin.com/7q17mJdm

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0.161
* Launcher Used: Twitch

* Memory Allocated: 6G

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?:Soartex Fanver
* Optifine Installed?: No

**Comment by Craken761** [comment]
Just confirming I experience the same behaviour
