### ISSUE TITLE
Suggestion: Reduce grass grind for torches in stages 2+

### ISSUE THREAD

**Issue by ShadowTheAge** [DarkPacks/SevTech-Ages#1869]
## Suggestion
Reduce grass grind for torches.
Tocrches require sticks, coal/charcoal and grass. While charcoal and sticks can be auto-produced in bulk, grass can only be grinded. You need 3 plant fiber for 1 plant twine for 2 torches.

## Possible Solution
* Reduce grass cost of torches (maybe plant fiber instead of plant twine?)
or
* Add additional way to produce torches via early-game automation (leaves maybe?)
or
* There is an AOE scythe "Brush Scythe" from "Cyclic" mod availible in stage 2. It can cut flowers and grass. Flowers are dropping but plant fiber is not. This may be a bug, if so - fixing it will help with the issue.

## Context
Stage 2 unleashes exploration into the twilight forest. The least enjoyable part is grinding for torches.

**Comment by Arcanatias** [comment]
you can make a blood lamp sigil in stage 2. as for the mazes in twilight forest you really only need torches until you can make a maze map.

**Comment by ChunkierDrew** [comment]
Or you can make a torch launcher from cyclic, 256 torches at the cost of 2 coal blocks, 2 gold and a few other cheap things.

**Comment by Targren** [comment]
The torch seems to use the "cordage" oredict, so you don't need grass.  You can use Twine (though I can't remember how to make it and the recipe isn't coming up on JEI now)

**Comment by justinrusso** [comment]
I think this eases as you progress. You begin to obtain other options for lighting up areas as well.
