### ISSUE TITLE
Chaos Reaper from Cyclic not craftable

### ISSUE THREAD

**Issue by JackRuby1** [DarkPacks/SevTech-Ages#1882]
What I'm seeing: https://gyazo.com/8567991b0380286164a9e0bec3f4229e
What the recipe is: https://gyazo.com/f5bc7a33a6c092d591931103b2d2158c
I cannot craft the Chaos Reaper from Cyclic, even though the recipe is correct, and I am in age 3. I even took it out of the crafting table and did it via the + button, which put the items in place, but no item. This happens on a server & single player world
Recipe needs fixing maybe?

**Comment by artdude543** [comment]
Reported to dev: https://github.com/PrinceOfAmber/Cyclic/issues/780

**Comment by Minecraftbegin2snow** [comment]
@JackRuby1 Cyclic has been updated to 1.15.0
CurseForge link:[https://minecraft.curseforge.com/projects/cyclic/files/2560070](url)

**Comment by artdude543** [comment]
We're going to update the mod in 3.0.8 and/or a patch version. As we need to launch 3.0.7 now.

**Comment by JackRuby1** [comment]
Cool beans, thank you @Minecraftbegin2snow
