### ISSUE TITLE
[3.0.6] Blood Magic - Well of Suffering telling me it should be disabled but works?

### ISSUE THREAD

**Issue by RyanP1991** [DarkPacks/SevTech-Ages#1902]
Issue / Bug:

Currently set up a Well of Suffering to collect LP for my altar but Waila tells me it should be disabled in the config but the ritual works correctly.

Expected Behavior:

The Well of Suffering either to work or not depending on if you guys wanted to disable it or not.

Possible Solution:

Confirmation on if the Well of Suffering should be disabled or not, Waila tells me it should be, but the config says : B:ritualWellOfSuffering=true

Steps to Reproduce (for bugs):

Set up a Well of Suffering and look at the master ritual stone.

Client Information

    Modpack Version: 3.0.6
    Java Version: 1.8.1_161
    Launcher Used: Twitch App
    Memory Allocated: 6GB

    Server/LAN/Single Player: Server and Single Player
    Resourcepack Enabled?: Nope
    Optifine Installed?: Nope

**Comment by 3jlowes** [comment]
https://github.com/WayofTime/BloodMagic/issues/1265

**Comment by RyanP1991** [comment]
No worries, thank you for finding clarification.
