### ISSUE TITLE
Nether imp's causing lagg on server.

### ISSUE THREAD

**Issue by Narzil** [DarkPacks/SevTech-Ages#1910]
Hi, 

Currently having this issue on our server, huge spawns of Imp's and it's creating heavy lag. 
![2018-04-17_05 34 51](https://user-images.githubusercontent.com/38449630/38847475-15737d94-4202-11e8-9469-0758e4e575d0.png)

Not the only spawn, but you can understand the problem..

Any suggestion on what to do here? Currently running sevtech 3.0.6 everything is up to date. I don't see any uses for the Imps (yet) in recipes etc, so removing them would not do any harm? Reduce spawnrate? Remove natura mod? Same issue on #1558

The server runs on own computer should not be any problem on that end.

**Comment by pure-fire** [comment]
I am playing 3.0.06 in single player and have hundreds of Nether Imps bobbing around in the lava all the time. Please advise how I can get rid of them or reduce the spawn rate. They are a big problem.

**Comment by Sorbe** [comment]
I also see this problem in SevTech 3.0.7 with Java 8u172 x64 [8GB VM] in SMP client/server mode.

There are way too many imps and some serious item lag (up to 10 seconds for some blocks (Fiery Nether Quartz for example) to break and drop items after mining).   Here is a panorama of one "imp cave" near my portal and another screenshot with current visible and total entity counts in F3.  There are 210 visible entities and 602 total entities.  It's a total imp party in hell....

![2018-05-18_02 55 26](https://user-images.githubusercontent.com/7958470/40229121-33031050-5a48-11e8-8986-4a4db7a940ed.png)
![2018-05-18_02 55 33](https://user-images.githubusercontent.com/7958470/40229123-33c6f2f4-5a48-11e8-83ef-cc995d03c181.png)

P.S.> Unlike the overworld and any other dimension, the first time entering the Nether, the game froze up (<<1 fps) for over 10 minutes.   I had to kill the game and restart to even get control.

**Comment by Sorbe** [comment]
Because of the severe near-lockup problems on first zone-in to the Nether dimension, I would recommend elevating the priority of this bug.
