### ISSUE TITLE
Enhancement: Add Galacticraft/Extraplanets Structures to Scanner

### ISSUE THREAD

**Issue by DerpityDoo** [DarkPacks/SevTech-Ages#1920]
Currently struggling to find a moon dungeon, would be nice to be able to find one a little easier with the scanner

**Comment by Dystilled** [comment]
Theres an item that scans in 128 block distance for mob spawners. Use that.

**Comment by MJRLegends** [comment]
yeah depending on how the scanner works you might not be able to do it

**Comment by justinrusso** [comment]
This seems to be the way to go - use the mob spawner to find a dungeon.
