### ISSUE TITLE
Beacon does not work as expected

### ISSUE THREAD

**Issue by GreatBanoose** [DarkPacks/SevTech-Ages#1922]
## Issue / Bug

Beacon effect only on top of beacon.
## Expected Behavior

To get the effects when in range of the beacon.
## Steps to Reproduce (for bugs)

1. Place Beacon
2. Put desired number of blocks underneath
3. Make sure it has line of sight to the sky
4. Make sure the beam is visible
5. Choose effects
6. Don't receive effects unless you stand directly on top of it.

## Context

I decided to have one of the beacons on my blood magic altar be functional.  I went with a full size beacon, and chose jump and regen.   Everything is setup correctly, but the only time I ever get the effects is when I'm standing directly on top of the beacon.
## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.5
* Java Version: 1.8.0_161
* Launcher Used: MultiMC

* Memory Allocated: 6 GB

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by SteseDav** [comment]
Could you backup your world, update to 3.0.6 and try again?

**Comment by GreatBanoose** [comment]
I wasn't able to successfully update my singleplayer world to 3.0.6, ran into some issues but those might not be pack related.

I did some testing in a superflat world on 3.0.6 and its still not working at all.
Standing 1 block away from beacon.  Look in top right, no effect.
![2018-04-18_04 35 38](https://user-images.githubusercontent.com/23392259/38929806-69f2759e-42c2-11e8-9d46-90e5a8aa28cf.png)
Standing on top of beacon, getting strength
![2018-04-18_04 35 49](https://user-images.githubusercontent.com/23392259/38929832-84af3836-42c2-11e8-96a5-95b6bd1702c9.png)
Standing well within beacon range, no effect
![2018-04-18_04 36 12](https://user-images.githubusercontent.com/23392259/38929848-934fb0dc-42c2-11e8-8db4-ea53e15f5687.png)

I'll try to get a video if that would help explain it better.

**Comment by GreatBanoose** [comment]
In the following video I showcase the issue happening on a 3.0.6 server.  I already have several effects due to Abyssalcraft armor and the nutrition mod, but you can clearly see that I don't get the beacon effects unless im standing on top of the beacon.

https://www.youtube.com/watch?v=eB4knP9ZUT4&feature=youtu.be

**Comment by Azrazal** [comment]
i am having this same issue

with some testing, it appears to work in a straight line east or south, but not north or west. and only 
when exactly in line with the beacon

also, only works when head height is in line with beacon or higher

i am running 3.0.8 and the only change to the pack i have made is disabling better foliage from in game menu

please let me know if i should make a new bug report for this

**Comment by lrwerewolf** [comment]
Also experiencing this issue on 3.0.8 Server, with a world begun in 3.0.7.  Standing on top gives the expected statuses (though it's clearly fighting with my Ritual of Regeneration).  Tried building a beacon some distance away and saw the same outcome.
