### ISSUE TITLE
BWM Candles disappear but leave smoke effects

### ISSUE THREAD

**Issue by Sorbe** [DarkPacks/SevTech-Ages#1925]
## Issue / Bug
BWM Candles disappear but leave smoke effects.
(See attached screenshots showing the "red smoke" animation, but no candle visible

## Expected Behavior
I would either expect both the candle and the smoke animation to be visible -OR-
If the candle is supposed to be temporary, the smoke animation should also be removed.

## Possible Solution
(Use other lighting methods as a workaround)

## Steps to Reproduce (for bugs)
Place a "White Candle" on the ground and come back sometime later.
I've logged in/out a large number of times before I spotted this artifact.

## Context
Used the candles as cosmetic lighting for Astral Sorcery altar.

## Logs
Not a crashing bug.

## Client Information
Sevtech Ages 3.0.6
Java 8 Update 162 (64-bit)
Jar Launcher selected
6GB Max VM Heap Size
Recommend Java VM help options
Client + SMP Server (also 3.0.6)
SoarTex Fan Version
No Optifine installed

SMP Server
No Resource Pack Download Option
No Optifine.

**Comment by Sorbe** [comment]
![2018-04-18_03 33 06](https://user-images.githubusercontent.com/7958470/38927664-5dcf73f4-42bb-11e8-881c-e8d42f68dc00.png)
![2018-04-18_03 33 14](https://user-images.githubusercontent.com/7958470/38927665-5dfca43c-42bb-11e8-9a91-e6211fe34ad4.png)

**Comment by Sorbe** [comment]
Note the subtle "red specs" above the inner White Marble Bricks that are the "smoke animation" from the candles that used to be there.

**Comment by Sorbe** [comment]
Here is another different, but more obvious "missing candle" smoke animation.
![2018-04-18_03 51 11](https://user-images.githubusercontent.com/7958470/38927994-50b5c91a-42bc-11e8-9f48-dcbfb869f80d.png)

**Comment by primetoxinz** [comment]
This is very bizarre. Candles are not different than torches in practice, they don't dispear after a while or anything. So I honestly have no idea why they are doing that, nor why the particles hang around after they do. - BWM Dev

**Comment by artdude543** [comment]
This can't be re-done in testing worlds. Just tried spam placing and removing them over and over for about 5 mins. And each one is removed fine. So this is an issue on your side. Restarting the client/world will help if anything.
