### ISSUE TITLE
Dreadium Bolt not craftable

### ISSUE THREAD

**Issue by Lewisking50** [DarkPacks/SevTech-Ages#1926]
## Issue / Bug

Can not create Tinkers' Construct bolts if the bolt core is tipped with AbyssalCraft Dreadium.
## Expected Behavior

A bolt is created.
## Steps to Reproduce

1. Craft an arrow shaft and pour Dreadium on it to create, for example, a Bone-Dreadium Bolt Core.
2. Attempt to craft a bolt in the tool forge using said bolt core and any fletching.

## Context

Can't create super awesome crossbow bolts of doom and destruction.
Feels bad man.

## Client Information

* Modpack Version: 3.0.6
* Java Version: jre1.8.0_161
* Launcher Used: Twitch Native Launcher

* Memory Allocated: 8,192 MB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes, Faithful 32x
* Optifine Installed?: Yes

## Server Information
* Java Version: jre1.8.0_161
* Operating System: Windows 10
* Hoster/Hosting Solution: Local Server
* Sponge (Non-Vanilla Forge) Server?: No

* Additional Content Installed?: No

**Comment by Mikte** [comment]
I would like to add to this, it seems any AbyssalCraft tipped bolts will not work.

Modpack Version: 3.0.8

Materials:
=Tips: Abyssalnite, Refined Coralium, Dreadium
=Core: Reeds
=Fletching: Steeleaf

**Comment by monodemono** [comment]
Reported to mod, awaiting fix.

https://github.com/Shinoow/AbyssalCraft-Integration/issues/21
