### ISSUE TITLE
Security Station can't add users

### ISSUE THREAD

**Issue by DrunkOctopus** [DarkPacks/SevTech-Ages#1931]
## Issue / Bug
The button for actually adding a user to the whitelist on a security station doesn't work. Pressing enter, right clicking, left clicking: no input works
This means only the owner can be on the whitelist

http://prntscr.com/j6wnqk

## Steps to Reproduce (for bugs)

1. Get a pneumatic craft security station and try to add someone who is online or offline

## Context
I was trying to make a base with a friend

## Client Information

* Modpack Version: 3.0.6
* Java Version: Latest Java 8
* Launcher Used: Native
* Memory Allocated: 8.5gb

**Comment by desht** [comment]
Both @MineMaarten and I have tried to reproduce this bug (in dev, and also in a dedicated server instance), and have not been able to reproduce the problem.  Left or right-clicking the "+" button adds the name in the text field to the security station as expected (pressing Enter doesn't do anything).

Is anything logged when you press the "+" button?  Any errors, execptions etc.?

**Comment by DrunkOctopus** [comment]
http://prntscr.com/j7jp3u
Here you are, a picture works too

**Comment by justinrusso** [comment]
PneumaticCraft devs were not able to reproduce this

**Comment by artdude543** [comment]
Closing this issue as it's not reproducible from various testing. If this is still an issue when 3.0.8 lands. Re-post on this issue with video footage that time around.
