### ISSUE TITLE
Suggestion to add Morph-o-Tool

### ISSUE THREAD

**Issue by SeanLatimer** [DarkPacks/SevTech-Ages#1936]
## Issue / Bug

I would like to suggest adding [Morph-o-Tool](https://minecraft.curseforge.com/projects/morph-o-tool). With the amount of wrench type items, being able to combine them into a single item would be a huge quality of life enhancement.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by artdude543** [comment]
I've looked into the mod and where it could fit into the pack. While yes it would _help_ save on some tools with mods. It removes the need for people to have a bag of tools like you would IRL and what not.

Also been some discussions with users of the mod with issues and some compat issues. Along with people mentioning in Discord that they would dislike the mod being added. So based on my findings and talking to some community members (who are heavy pack users) the mod won't be added to the pack.

But thanks for your suggestion!
