### ISSUE TITLE
Wither produced Low Grade Charcoal from Netherrack.

### ISSUE THREAD

**Issue by reklatsmasters** [DarkPacks/SevTech-Ages#1941]
## Issue / Bug

Wither produced Low Grade Charcoal from Netherrack.

https://clips.twitch.tv/ClearCloudyLapwingWoofer ( don’t forget off sounds )
## Steps to Reproduce (for bugs)

1. Call wither.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.5 probably 

It was on melharucos’s server.

**Comment by redparry** [comment]
This happens with any explosion, e.g. TNT.

**Comment by justinrusso** [comment]
This might have to be considered a known limitation. We will take note of it though and consider the options.
