### ISSUE TITLE
Game crashed while breaking dirt slab in hunting dimension

### ISSUE THREAD

**Issue by LordHellscream** [DarkPacks/SevTech-Ages#1943]
This happened when I attempted to break a dirt slab in hunting dimension
Modpack version 3.0.6

this permanently ruined my save, not able to recover (fortunately I have backup)

https://pastebin.com/UqVnY2gC

**Comment by SteseDav** [comment]
You seem to be using the packaged Java rather than the latest. 

Please can you update your Java and force your launcher to use it.

https://docs.google.com/document/d/e/2PACX-1vR5muyi1m7Zy_qSwrzeb9e3tbbRlksguNUb_Pvm3pn9eDpsIkUj5qQUq6WFPPdEoVWZq91WvvH57KzC/pub

**Comment by bigfooteUK** [comment]
Also occurring when placing dirt slab in Hunting Dimension. 3.0.6, Java 1.8.0.161 64bit on the JAR launcher.

https://pastebin.com/jgjiHBUf

**Comment by bigfooteUK** [comment]
Java 171 fixes the issue.

**Comment by LordHellscream** [comment]
I updated to 171, not sure if the issue is fixed or not haven't used the dirt slab since.

**Comment by SteseDav** [comment]
ok, may need futher investigation then.

**Comment by demosthien** [comment]
I think I also have this issue.

Was placing/breaking dirt half slabs in the Hunting Dimension when MC crashed. Now when I start the saved game it commences loading terrain shows my inventory and I get some graphic appearing then it crashes.

Most recent crash report.

https://pastebin.com/ChTuXpV2
