### ISSUE TITLE
Syncing Issues

### ISSUE THREAD

**Issue by deer-god** [DarkPacks/SevTech-Ages#1950]
## Issue / Bug

Player (on the same team) who wasn't online during the advancement from age 0 to 1 didn't have waila auto-enabled.
Server has a team of 3. Two players weren't online while the advancement from age 0 to 1 was completed. 
Upon rejoin, one player didn't have waila enabled, even after running `/tf forcesync`.
forcesync worked for the other player, and their waila was enabled. 
We were able to fix this by manually enabling waila (I'm unsure if this will lead to us seeing things we shouldn't have).

A second minor bug is that another player is unable to read the names of the shadow gems (they're just the mystery gibberish), even though he's synced fine and all other non shadow-gem-related items have visible names.
## Expected Behavior

All players on a team should have waila enabled after logging back on after an age change.
All players should be able to read the names of unlocked items. 
## Possible Solution

Sometimes, when a player rejoins after an age change the script to enable waila isn't run.
## Steps to Reproduce (for bugs)

Unfortunately since this only happened with one player and not both, I'm unsure how to replicate the bug. The player who did have it happen already has a single player game past age 1, and so perhaps its something to do with the way the script to enable waila is run. 

## Context

Not all players know to enable waila by hand if this issue arises,  one player can't read the names of some items (although they can still be used in crafting, so this is a minor issue). 
## Logs
N/A
## Client Information

* Modpack Version: 3.06
* Java Version: 1.8.0.161
* Launcher Used: Jar launcher through twitch

* Memory Allocated: 8-10G

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: 1.8.0.161
* Operating System: Windows
* Hoster/Hosting Solution: Self hosted, 10G memory
* Sponge (Non-Vanilla Forge) Server?: Nope

* Additional Content Installed?: No

**Comment by justinrusso** [comment]
The abyssalcraft "blurryness" on item names is not something that is synced.

Was the player that still had issues up to date on the advancements, or was everything still having issues syncing?

**Comment by Borlaq** [comment]
Same issue for me on my server when transitioning from stage 1 to stage 2. Force sync didnt work, so player had to pick up the altar himself to be able to advance to next age.

I also seem to remember there being some issues with other minor achievements not getting updated for others untill i get a new achievement done. Even after using force sync. Not 100% on this, since its been a while since this was a problem.
