### ISSUE TITLE
Tinker's Tool + Soulbound + Gravestones = No worky

### ISSUE THREAD

**Issue by Mr-B-l-a-c-k** [DarkPacks/SevTech-Ages#1953]
## Issue / Bug

I added a nether star to a tinker's shuriken in a tool forge, it added the "soulbound" portion to the star. I died, but respawned with just the death marker in my inventory. Shuriken was left in my gravestone.

## Expected Behavior

Shuriken should have stayed in my inventory I think- it would make getting back to my grave a lot easier..

## Steps to Reproduce (for bugs)

1. Add Soulbound to tinker's tool
2. Die

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.06
* Java Version: 
* Launcher Used: MultiMC

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by justinrusso** [comment]
3.1.0 will be transitioning to a new gravestone mod. As such, please be sure to get any remaining graves before updating. This should hopefully resolve this issue.
