### ISSUE TITLE
Tinker Tool dupe

### ISSUE THREAD

**Issue by randomlypickedname** [DarkPacks/SevTech-Ages#1962]
## Issue / Bug
If one player in age 3+ accesses a tool forge while another age 2 player has a tool with modifier ingredients in the forge, the age 2 player can add the modifier and receives both the modified tool, with a default name, and their original tool without modifiers.

## Steps to Reproduce (for bugs)
1. Have age 2 player add tool + e.g. lapis to forge
2. Age 3 player r-clicks tool forge
3. Age 2 player can click (I imagine shift-click too) their tool out of the output side and gets two tools as mentioned above

## Client Information

* Modpack Version: 3.0.6
* Java Version: latest
* Launcher Used: AT
* Memory Allocated: 6G
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: N 
* Optifine Installed?: Y

**Comment by justinrusso** [comment]
This needs to be reported to https://github.com/SlimeKnights/TinkersConstruct/issues and reference this issue
