### ISSUE TITLE
Gold and Quartz Spawn below bedrock in Twilight Forest

### ISSUE THREAD

**Issue by Shock2k** [DarkPacks/SevTech-Ages#1969]
## Issue / Bug
Gold and Quartz are not spawning correctly in Twilight Forest.

## Expected Behavior
Gold fever, instead get Gold cold.

## Possible Solution
They might just spawn to low, maybe remove them from the ore list, or readjust where they spawn.

## Steps to Reproduce (for bugs)

1. Prospect for the ore, you will see 1's and 2's but no more.
2. Mine down, and you will hit bedrock before hitting the ore.

## Context

Can't actually mine this ore in the Twilight Forest.

## Client Information

Modpack Version: 3.0.6
Java Version: u161
Launcher Used: Twitch
Memory Allocated: 12G

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Yes
* Optifine Installed?: Yes

**Comment by 3jlowes** [comment]
This happens with a lot of ores, and it is not specific to just twilight. If the Y level the ores spawn at is low, there is a good chance it can be under bedrock.

**Comment by Jemsuper** [comment]
Adding redstone (cinnebar) ore to this list

**Comment by justinrusso** [comment]
This should have been improved in 3.0.7. Let is know if you still have difficulties.
