### ISSUE TITLE
Immersive Engineering Feedthrough Insulator HWYLA Interaction Causing Ghost Item Drops

### ISSUE THREAD

**Issue by TrueKuehli** [DarkPacks/SevTech-Ages#1972]
## Issue / Bug
Looking at a Feedthrough Insulator from the Immersive Engineering Mod formed from a double slab causes a large quantity of visual Item Entities to be created. These cannot be picked up by the player and seem to only exist on the client side. They do however start to cause framerate lag fairly quickly. Slabs from Natura and Tinkers' Construct seem to be unaffected, most other slabs are. 
From my testing it appears to be an interaction issue between Immersive Engineering and HWYLA (Tested with just these two mods installed, IE on it's own doesn't produce this bug).

## Steps to Reproduce
[Video of the Bug](https://youtu.be/-eSGbAmr5w4)
1. Place two slabs on top of each other to create a full block.
2. Place two LV / MV  / HV Connectors on two oppsite sides of the double slab.
3. Right click on one of the connectors with the Engineer's Hammer.
4. Look at the block, so that the HWYLA HUD shows on the screen.

## Logs
This issue unfortunately does not produce any logged information.

## Client Information
* Modpack Version: 3.0.6
* Java Version: Java 8 Update 171 (Build 1.8.0_171-b11)
* Launcher Used: Twitch Launcher (7.5.6683.1384) using the Jar Launcher Option
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by malte0811** [comment]
Fixed in IE, for build 82. If this had been reported to IE rather than here (where it was ignored) or passed on to us the fix could have been in the last build (which broke things in a new way).
