### ISSUE TITLE
Assorted Quartz only gives Nether Quartz ore when mined with a silk touch pickaxe

### ISSUE THREAD

**Issue by marjak93** [DarkPacks/SevTech-Ages#1978]
## Issue / Bug
When mining assorted quartz, using a silk touch pickaxe will yield only nether quartz ore. Nether quartz ore can not be refined into black quartz or certus quartz, so it doesn't make sense to be a result from assorted quartz.

## Expected Behavior
Mining assorted quartz should give an assortment of different types of quartz.

## Possible Solution
Add a recipe to refine nether quartz into certus/black quartz in age 4 and onwards. Alternatively (not sure if possible), drop a random type of quartz ore when mining assorted quartz with silk touch pickaxe.

## Steps to Reproduce (for bugs)

1. Add 'squaky' modifier to a TC pickaxe
2. Mine assorted quartz (geolosys)

## Context
Mined an entire assorted quartz vein with my squaky ore excavated TC pickaxe, looking for certus quartz. Only got nether quartz.

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0_161
* Launcher Used: Twitch

* Memory Allocated: 5120MB

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by gnuffiehot** [comment]
I am finding this problem now as well.

**Comment by TheFlie01** [comment]
Yes, the problem still exists in 3.0.8  and they can meanwhile fix the IE excavator with it.
