### ISSUE TITLE
Hostile mobs are barely spawning

### ISSUE THREAD

**Issue by Wafflesrbae** [DarkPacks/SevTech-Ages#2001]
## Issue / Bug
 Hostile mobs will barely spawn in any of the worlds I create. Render distance is 8-12 

## Possible Solution
 My guess for reason is some where along the lines mobs don't or can't spawn for reasons in age 1.

## More Info
I looked to see if others were having this on later posts and I do see people who have this problem. I have no clue if they found a answer to why this is happening.

## Context
  I can't progress into age 2 as no mobs spawn in the dark lands and I can't get the dark gem to progress. 

## Client Information

* Modpack Version: 3.0.6
* Java Version: 
* Launcher Used: Twitch
 
* Memory Allocated: 10 mb
No server just single player.

**Comment by SphynxLoL** [comment]
Mobs not spawning "At All" in any world you create sounds like you might be on peaceful. Title to your report says "barely spawning" then in your report you say they don't spawn at all. It's hard to tell or give any diagnosis if you can't provide exact information. Also, have you added any mods to the pack that may influence mobs spawning, biomes, or mob drops?

**Comment by Phantum** [comment]
I've actually run into something similar.   tried setting up a mobfarm above our blood magic alter, and even with lighting up the entire island, and using a cave illuminator, almost nothing comes out of the spawner on my server.  Maybe 2-3 mobs once in a blue moon.  Not the 300+ I'm normally used to o.0

**Comment by Linkinexe** [comment]
I've run into the same issue as Wafflesrbae. I've spent several days and nights in the Dark lands in order to farm for the Dark gem but even on "hard" there are no hostile mobs spawning, no vanilla mobs, no mod mobs. Neutral mobs are still there however.

**Comment by Wafflesrbae** [comment]
@SphynxLoL Randomly generated for all of them

**Comment by SphynxLoL** [comment]
I've had an issue with samples that didn't update after unlocking a new age. I had to restart my entire client for the update to go through. Have you restarted your client since you made it to the new age? I'm only throwing ideas out, as this cannot be reproduced. It seems to be only a handful of people being affected.

**Comment by Phantum** [comment]
server restarts twice a day, and client has been restarted quite a bit for my end.

**Comment by MrHrulgin** [comment]
@Phantum You're probably having a different issue than the OP. On servers the hostile mob spawn cap is shared between all active players. It's an expected consequence of an active server that each player will encounter many fewer mobs unless the mob cap is adjusted to be higher than it is in single player.

**Comment by Phantum** [comment]
how does one adjust that mobcap?  My server atm can definitely handle far higher.

**Comment by Ozzymud** [comment]
@Wafflesrbae How much memory are you allocating? I was having an issue where it kinda felt like peaceful, upping the memory to 6gb made a world of difference.

**Comment by Ozzymud** [comment]
@Wafflesrbae possibly related to #2158 with a temp fix set of commands if so in the issue?

**Comment by justinrusso** [comment]
I agree with @Ozzymud, this sounds like the same issue. If this issue persists after 3.0.8 please let us know.
