### ISSUE TITLE
Weirding Gadget does not load Galacticraft/Extra Planets on Server Restart

### ISSUE THREAD

**Issue by Fatthunder** [DarkPacks/SevTech-Ages#2004]
## Issue / Bug

When I place Weirding Gadget down on a planet (Moon, Mars, Venus, Mercury) and then restart my server.  Weirding Gadget does not load/keep these dimensions loaded. I have to go to each in order for the initial load to occur.

## Expected Behavior

Weirding gadget should load the dimensions it is placed in, whether an actual player has been there since a server restart or not.

## Possible Solution

There might be a conflict between how weirding gadget tries to load a dimension and how Galacticraft wants one loaded?

## Steps to Reproduce (for bugs)

1. Place Weirding Gadget on planet.
2. Restart server
3. Check loaded worlds.
4. No worlds are loaded.

## Context

Trying to set up some automation on the worlds, but everytime my server restarts I need to go the those worlds to get the automation started again.

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.172
* Launcher Used: Twitch

* Memory Allocated: 8GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes (Soartex modded)
* Optifine Installed?: Yes

## Server Information
* Java Version: 1.8.161
* Operating System: Windows Server 2016
* Hoster/Hosting Soultion: N/A
* Sponge (Non-Vanilla Forge) Server?: N/A

* Additional Content Installed?:

**Comment by Targren** [comment]
We used to have a similar problem with the portals on our old  Attack of the B-Team server. If the mod hasn't changed how it works, it doesn't actually load the dimension until a player visits it, so it's not loading the chunk loaders.

**Comment by Fatthunder** [comment]
> We used to have a similar problem with the portals on our old Attack of the B-Team server. If the mod hasn't changed how it works, it doesn't actually load the dimension until a player visits it, so it's not loading the chunk loaders.

I think this is an issue then.  If this is going to be the only chunk loading method provided, I would think that it should properly load dimensions on restart without having to go to said dimension, otherwise the point of chunk loading other dimensions on an actively restarting server doesn't really matter.

**Comment by Targren** [comment]
It's been awhile since I had to look into it, but I seem to remember that it was intentional. Back then when GC only had 2 planets + one space station/player, it was a lot of potentially unused dimensions to be loading. Now that it's up to what, almost a dozen, it's gonna be a tradeoff.

**Comment by Fatthunder** [comment]
Hmm. Looking at GC config (chunkloading); It should be loading on server login (which with Weirding they do not).

`chunkloading {
    # If you don't want each player's chunks to load when they log in, set to false.
    B:LoadOnLogin=true
}`

Though it may only be referring to GC launch controller chunk loading in planets.conf

`general {
    # Whether or not the launch controller acts as a chunk loader. Will cause issues if disabled!
    B:launchControllerChunkLoad=true`

**Comment by AtomicBlom** [comment]
I'm the mod dev for The Weirding Gadget.

I recently had this reported to me as well with the gadget not working with the nether, so I suspect that it might be an issue on my side.

I've been doing a lot of feature work on Weirding Gadget lately and hope to have a new release soon. I intend to test and fix this if it is an issue on my side.
