### ISSUE TITLE
Crash multiplayer server in BetweenLands

### ISSUE THREAD

**Issue by gamingouchs** [DarkPacks/SevTech-Ages#2006]
## Issue / Bug
Server client loads and stays idle as soon as someone connects it does the initial disconnect once 
then when they reconnect it will crash the server 
players are inside the betweenlands when they try to log in

## Expected Behavior
log into the server and play while in betweenlands?

## Steps to Reproduce (for bugs)

1.load multiplayer server
2.login while in betweenlands

## Context
just opened AGE 2 trying to progress in betweenlands and it crashed

## Logs

* Client/Server Log: https://pastebin.com/JhKHXGa0
* Crash Log: https://pastebin.com/zhzxpHNz 

## Client Information

* Modpack Version:3.0.6
* Java Version: latest version
* Launcher Used: jar launcher always use latest version

* Memory Allocated:8192M

* Server/LAN/Single Player:Server
* Resourcepack Enabled?:yes
* Optifine Installed?:yes

## Server Information
* Java Version: version 8 161
* Operating System: win 10 home
* Hoster/Hosting Solution: home computer
* Sponge (Non-Vanilla Forge) Server?:no

* Additional Content Installed?:no

**Comment by SteseDav** [comment]
Try without Optifine enabled/installed.

Are you running the server on the same machine as the client? how much available ram in the server machine?

**Comment by gamingouchs** [comment]
Server isnt playing minecraft its just hosting it
it has 16gb

**Comment by gamingouchs** [comment]
https://mega.nz/#F!78lVWQaZ!SFHKN4QjSWOMAPfmJofYzA

Upload of the world I can't get it to load no matter what
tried to get a screenshot of invent right before it crashes, but to no avail.

Both of us are stuck in the betweenlands we have the starter gear of weed wood tools ect.
standing in the tree portal next to empty chest.

**Comment by artdude543** [comment]
Looking at the crash log this is something with the flowers updating from @BlakeBr0 mod.

**Comment by gamingouchs** [comment]
Is there anything I could do to delete the betweenlands instance and have it regenerate/restart so I could get back into the world super curious if thats a possibility.

**Comment by TheCyberBrick** [comment]
@gamingouchs you can delete the Betweenlands world by deleting the DIM20 folder in your world folder.
