### ISSUE TITLE
Crash within an hour of gametime (and occasionally on startup)

### ISSUE THREAD

**Issue by RiSsS** [DarkPacks/SevTech-Ages#2028]
I haven't been able to find any related issues with a solution provided.
 
## Issue / Bug
Game crashing on startup, and also at seemingly random times within the game after anywhere between 5 minutes and an hour. This happens in the Overworld, the Twilight Forest, Hunting Dimension, etc. I can usually completely reinstall the pack, but the issue will occur again within an hour of game time. 

## Steps to Reproduce (for bugs)
1. Seems to be random. Sometimes the launcher works, sometimes it crashes. 

## Logs
There doesn't seem to be a crash-logs folder in my instance, but this is the log from the launcher. 
https://gist.github.com/RiSsS/a4fbd52eda2abdbcb67c6625091c9a18

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0.161 x64
* Launcher Used: Jar Launcher

* Memory Allocated: 6144 (16 GB total on machine)

**Comment by SphynxLoL** [comment]
After some google reasearch, I found this seems to be a Graphics Card Driver issue. Try updating your driver.

**Comment by RiSsS** [comment]
I updated graphics drivers, and it launched without crashing on the first attempt, it continued to run for over an hour without crashing. I'll try to update if anything changes.

**Comment by 3jlowes** [comment]
Its not gfx related. Try reinstalling java. Mignt have a corrupted install. And try disabling UAC.

**Comment by RiSsS** [comment]
Uninstalled Java, and reinstalled with most recent version. Disabled UAC. Still crashing on launch.

Crash Log: https://gist.github.com/RiSsS/4c56167755159ad52931ebf6d67beb84

**Comment by 3jlowes** [comment]
An error report file with more information is saved as:
# C:\Users\josh\Documents\Curse\Minecraft\Instances\SevTech Ages\hs_err_pid836.log

Attach that

**Comment by mindcloud69** [comment]
post a gist of the log mentioned in your crash report.

C:\Users\josh\Documents\Curse\Minecraft\Instances\SevTech Ages\hs_err_pid836.log
