### ISSUE TITLE
Mob Masher not mashing Galacticraft Evolved Creepers

### ISSUE THREAD

**Issue by DerpityDoo** [DarkPacks/SevTech-Ages#2035]
![2018-04-23_01 27 05](https://user-images.githubusercontent.com/37868135/39118310-996da786-4695-11e8-8e0c-0ecbcb94244d.png)

## Issue / Bug
Mob Masher isn't mashing Galacticraft Evolved Creepers

## Expected Behavior
Masher should damage any mob that touches it

## Steps to Reproduce (for bugs)
Push an Evolved Creeper into a Mob Masher and see it takes no damage

## Context
Just boxed up some spawners from the moon and wanted to grind em up for some blaze rods

## Client Information

* Modpack Version: 3.0.6
* Java Version: jdk1.8.0_144
* Launcher Used: Twitch

* Memory Allocated: 12G

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Default
* Optifine Installed?: Yes

**Comment by justinrusso** [comment]
Reference https://github.com/vadis365/Mob-Grinding-Utils/issues/81 for any more on this issue.
