### ISSUE TITLE
Cooking For Blockheads issues

### ISSUE THREAD

**Issue by Murazriel** [DarkPacks/SevTech-Ages#2051]
## Issue / Bug

1) Using a cooking for blockheads cooking table + setup, along with Actually Additions "Knife" only works for one recipe, then the knife becomes damaged and wont work in any recipes. (Trying to make bacon for example). 
2) Using a cooking for blockheads cooking table + setup, I have sugar, flour, raw egg, and apples all in either fridges or kitchen counters, however, an oven-ready apple pie does not show up within the cooking table as a recipe that's completable. As well as Pizza from Actually Additions does not show up with all the ingredients.
3) No way to attach a tank to the cooking table to supply milk directly to it
## Expected Behavior

1) Knife should work until broken to do recipes as it does in just your normal crafting grids.
2) Oven ready pies and Pizza should show up in the cooking for blockheads cooking table if all ingredients are within the multiblock storage.
3) A connected tank full of milk should be usable for the multiblock structure
## Possible Solution

1) Make a knife that has a higher cost but infinite durability so the recipe always works, or make the recipes work with a damaged knife.
2) Add in the "oven ready" pie and Pizza recipes since they're missing from the cooking table.
3) Have a way to use a tank full of milk in recipes if its connected to the multiblock structure, or implement an item that is a fluid storage specifically for the multiblock structure.

## Steps to Reproduce (for bugs)

1.
2.

## Context

Making a nice kitchen setup feel with cooking for blockheads, but unable to if the recipes arent working.
## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.6.1
* Launcher Used: Native

* Memory Allocated: 5gigs

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by csg1995** [comment]
if you empty the water from a sink, you can add milk use fluid pipes to get it from your tank to the sink for easy transport

**Comment by artdude543** [comment]
- You can also use a cow in a jar for milk. I don't believe the mod supports other "mod tanks" apart from its own blocks/tiles.
- The knife seems like it could be a bug with how the recipes works and/or CFB not understanding durability on tools. Would need further testing to work out who is to blame on that one.
- Oven ready pies and Pizza would need adding manually as the mod does not auto-generate recipes for its self; so we can look into that one.

**Comment by artdude543** [comment]
- Milk jar is fixed we're re-adding the jar back to the game and enabling a new recipe for it. But the cow in a jar will be kept disabled.
- We need to manually add the other food items which _will/may_ take a while to do so.
- The knife is a bug with the mod. If you wanted to help out if you could report to the mod dev that tools that take durability seem to not work once they have taken "damage" this would help a tonne 🙂

**Comment by AndrewR73** [comment]
Not sure if this was covered already, but in my game (Twitch/3.0.8 - single player) the sink does not appear to be supplying water to recipes. If I have a water bucket in hand I will get recipes like Dough in the Cooking Table, but if I remove the water bucket from my inventory the recipe goes away... and this is with a sink connected directly to the Cooking Table (see attached image)
![2018-06-15_15 26 36](https://user-images.githubusercontent.com/8558973/41491890-9dee23f4-70b0-11e8-91d5-25d02115b19c.png)
.

Additionally, if we now have the Cooking Table, Oven, and other kitchen elements opened up to us in Age 4.... where are the tools?
![image](https://user-images.githubusercontent.com/8558973/41491973-08ff3cb4-70b1-11e8-8528-bbc0a8e944f3.png)

-- Andrew
