### ISSUE TITLE
Lava Sigil dupe.

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [DarkPacks/SevTech-Ages#2059]
## Issue / Bug
When Lava Sigil is used on any tank, which can store fluids (Smeltery, Clay Barrel and etc...) it's duping lava. You have got a lava IN your tank and OUTSIDE of your tank and lost 1000 LP, instead of 2000 LP.

## Expected Behavior
Lava Sigil must give 1 bucket of lava in your tank or outside, but not IN your tank and OUTSIDE of your tank.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)

1. Get a Lava Sigil.
2. Get some LP in your altar, atleast 1000 LP.
3. Get any tank and place into the world.
4. Use the Lava Sigil on the tank.
5. You got 2 buckets of lava, instead of one bucket.
EDIT: Did some tests, with tanks and Lava Sigil and tried to reproduce it and got the some thing. If you only Righ-Click to a tank, it will consume 2000 LP and you get 2 buckets, but if you Shift + Right-Click to a tank with a sigil, it'll consume 1000 LP, and you also get 2 buckets.

## Context
It's make getting lava more cheaper. I trying to make it more balanced. *My bad english got stucked here.*

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0_151 / 1.8.0_171
* Launcher Used: Twitch

* Memory Allocated: 7200MB / 6192MB

* Server/LAN/Single Player: Single Player, also works on a server.
* Resourcepack Enabled?: Faithful / None.
* Optifine Installed?: No.

**Comment by Jandakast** [comment]
I believe this is related to this NullPointerException issue and the fix will be available in a future Blood Magic release.

https://github.com/WayofTime/BloodMagic/issues/1236

**Comment by artdude543** [comment]
As far as I'm aware that's already in the version we have in dev. So it would be fixed in 3.0.7

**Comment by 3jlowes** [comment]
Just thought id add this. Only happens on some tanks. Ender tanks work fine. (Sevtech 3.0.6)

**Comment by justinrusso** [comment]
Does not dupe:
- IE Tank
- Ender Tank

Dupes:
- BC Tank
- Tinkers Seared Tank
- Cyclic Fluid Storage Tank

**Comment by justinrusso** [comment]
The dupe part seems to be fixed. It now at times double right-clicks when clicking on some tanks. See 1781 for that issue.
