### ISSUE TITLE
Slimeling wants Wooden Hoe

### ISSUE THREAD

**Issue by Ritsuna** [DarkPacks/SevTech-Ages#2066]
## Issue / Bug
After collecting a few slimelings I have run into a problem where several of my slimelings want wooden hoes, however, I cant make any, so they are now stuck.

## Expected Behavior
Either not have uncraftable items on their food list, or be able to in age 5 make their food.

## Possible Solution
hard to say, as I know a lot of things were done for balance, but this is breaking a feature of the mod.

## Context
I was trying to breed up the slimelings to act as bodyguards while I work on alien worlds.

## Client Information

* Modpack Version: 3.0.6
* Java Version: version 10 build 10-46
* Launcher Used: Twitch launcher Forge 14.23.2.2651
* Memory Allocated: 6 GB

* Server/LAN/Single Player: both single and server
* Resourcepack Enabled?: yes, persistence
* Optifine Installed?: no

**Comment by artdude543** [comment]
@MJRLegends any chance we should save them?! 😀

**Comment by MJRLegends** [comment]
@artdude543 This would need to come from the GC side of things as its hard coded https://gyazo.com/2175dcdef46c073b3884f33807938532

Maybe a pull request for a config based list instead? let me know if you want me to help with that

**Comment by artdude543** [comment]
tbh this won't be fixed. We don't want to enable the hoe for this one _(kinda pointless)_ addition. Along with getting a PR made/accepted will take time which we don't have as of current.

**Comment by chucktheviking** [comment]
I am saddened by the fact that Slimeling kind will always die to a lack of wooden hoe. Too bad we can't just get a useless wooden hoe just to feed them, but either way, I was just conveying the opinions of some of the dwellers on the server I play on.
