### ISSUE TITLE
Chisel does not work on Gold Blocks (block shown in JEI)

### ISSUE THREAD

**Issue by Sorbe** [DarkPacks/SevTech-Ages#2092]
## Issue / Bug
A variety of chiseled Gold Blocks are shown in JEI, but none of them are actually craftable.

## Expected Behavior
Chisel offers up the decorative gold blocks in JEI, but cannot be made with chisel currently(Age 2).

## Possible Solution
Fix the chisel recipes or remove the uncraftable blocks.

## Steps to Reproduce (for bugs)
1. Find Gold Vein from surface samples
2. Mine out all of the Gold Ore
3. Smelt Gold Ore into Liquid Gold
4. Cast the Liquid Gold into Gold Blocks
5. Search JEI for Gold Block (from Chisel)
6. Open Chisel and insert a Gold Block
7. Nothing besides the Gold Block can be made.

## Context
Making decorative blocks for an altar.

## Logs
Not a crashing bug.

## Client Information
SevTech 3.0.6
Java 8u162 x64
Jar Launcher
6 GB of Memory Allocated
SMP Client => Local Server
Soartex FanVer Modded Universal 4.1.2
Optifine is NOT installed.

**Comment by Sorbe** [comment]
![2018-04-26_15 30 23](https://user-images.githubusercontent.com/7958470/39335520-39a32468-4968-11e8-9453-52189e503a75.png)
![2018-04-26_15 31 31](https://user-images.githubusercontent.com/7958470/39335521-39c4391e-4968-11e8-9b05-e6a56f931550.png)

**Comment by kragnoth** [comment]
Tinker's construct added a gold block = iron block ore dict, did you do something to fix that, that would have broken chisel?

**Comment by Voxelse** [comment]
Since the issue isn't resolved yet, I had to specify that the problem isn't only for gold but for most of the basic ore blocks (Aluminum, Bronze, Cobalt, Copper, Electrum, Gold, Iron, Lead, Nickel, Platinum, Silver, Steel, Tin).
