### ISSUE TITLE
AE2 Paintball missing recipe

### ISSUE THREAD

**Issue by Rixxaw** [DarkPacks/SevTech-Ages#2096]
## Issue / Bug
AE2 Paintballs are used by the Color Applicator to "Paint" AE2 cables so you can efficiently segment and manage your network without having to make stacks of cables of each color.  I see they are removed from JEI and there is no recipe for them.  

![image](https://user-images.githubusercontent.com/17864718/39342216-9674e65c-499c-11e8-9656-2ab2e434d4cb.png)
****
## Expected Behavior
That I should be able to craft Paintballs to use to color my AE2 cables.

## Possible Solution
Add the Recipes for Paintballs back to the modpack.

## Context
I have crafted a Matter Condenser and a Color Applicator.  I am mining Mars Stone and feeding it in to my matter condenser to make Matter balls and the the final step of loading my color applicator with paintballs is impossible because I can't craft Paintballs.  

I will now have to craft 8 at a time Smart Cables in various colors and thus waste the limited supply of AE2 crystals I have from mining them.  I can't think of any reason why Paintballs were removed, except that they clutter up JEI?  As a possible alternative fix you could create a 1 smartcable + 1 dye recipe produces 1 colored cable as a way to allow for more careful use of the resources required to make smart cable.

## Client Information

* Modpack Version:  3.06
* Java Version: Not applicable
* Launcher Used: Twitch
* Memory Allocated: 12 gig

**Comment by artdude543** [comment]
You can use standard dyes for the color applicator. As of current, we're going to hold off on fixing this for 3.0.8 due to Id issues. But Dyes do work as well as the paintballs! :)
