### ISSUE TITLE
Spawner Agitator making spawners last longer then 400 spawns

### ISSUE THREAD

**Issue by SystemCollapse** [DarkPacks/SevTech-Ages#2105]
## Issue / Bug
Spawner Agitator making spawners last longer then 400 spawns both in Single player and my Patreon Sever.

## Expected Behavior
Not lasting forever.

## Possible Solution
Darkosto stated it was working at one point so something broke it?

## Steps to Reproduce (for bugs)
Move a Vanilla spawner, stick a Agitator on it. Wait.

## Context
It has broken my heart and wounded me deeply.

## Logs
Are made of wood.

## Client Information
N/A

**Comment by SystemCollapse** [comment]
The Agitator as per Darkosto is not intended to extend the life of the Spawner.

**Comment by Ozzymud** [comment]
@milcondoin at least in 3.0.6 (I haven't updated to 3.0.7 as issues), I don't see it in tips.txt: https://pastebin.com/K58740iR located in Instances\SevTech Ages\resources\justthetips\texts

**Comment by justinrusso** [comment]
Same as #2190
