### ISSUE TITLE
Mantle of the stars should be moved to later age

### ISSUE THREAD

**Issue by lawl281** [DarkPacks/SevTech-Ages#2113]
Mantle of the stars with Aevitas from astral sorcery should be unobtainable till a later age.  This one item gives ridiculous regen and keeps you full saturation locking your nutrition levels at what they were when equipped.  If you can't stage lock it then maybe require at least a diamond if not something from later game.  Aevitas cape + Armara player attunment = unkillable.

## Possible Solution
Require Diamond or even a ore from a planet to craft

## Steps to Reproduce (for bugs)
1. Craft Aevitas Mantle of the stars.
2. Get all nutrition to 100%
3. Equip Mantle, Never worry about food again.
4 Attune player to Armara, Max out the skill tree.
5 Unkillable GODDDD

## Context
I like the struggle to and fine balance of gearing and leveling as I go.  This is an instant endgame jump.
The void can't kill you.  lava can't kill you.  Haven't tried using this on planets yet.  Will probably out heal the suffocation damage.

## Client Information

* Modpack Version: 3.0.6
* Java Version:
* Launcher Used: Twitch
* Memory Allocated: 12gb
* Resourcepack Enabled?: Soartex
* Optifine Installed?: yes

**Comment by Rixxaw** [comment]
Out Heal suffocation damage you say?  No need for space suits?  Sign me up :+1:

**Comment by Targren** [comment]
Seems silly to stage it after all the combat progression is done; other than a quick jaunt to the End at the beginning of Age 4, all the real fighting is in Ages 2 and 3.

**Comment by LordHellscream** [comment]
AS takes a lot of efforts to get with all the grind for crystal and such, I think a tweak is needed but do not blindly gate things into late ages. The reason some more powerful stuff are available in Age2 because that encourage you to explore (especially to complete the Iron apple quest), once you progress to later age those "power" cease to be meaningful anymore.

**Comment by justinrusso** [comment]
The mantle was tweaked in 3.0.7 (brokenly) and again will be tweaked in 3.0.8. Please let us know if you still feel this needs to be adjusted. Thanks!
