### ISSUE TITLE
Server & SinglePlayer Generation Don't Match

### ISSUE THREAD

**Issue by ShetiPhian** [DarkPacks/SevTech-Ages#2120]
## Issue / Bug
Dispite same seed and level-type server and single player generate different worlds

## Expected Behavior
Same world should be generated reguardless if done by a server or client

## Possible Solution
No idea, something is messing with the generator

## Steps to Reproduce (for bugs)
seed:-5728716666143060273
level-type:quark_realistic

Create a new single player world with the provided seed
Edit server.properties to contain the same seed, and create the world

In single player you start in a wooded area with a river to the west
On the server you start on an island 

## Context
Started playing in single player, then opened it to LAN so my brother could play too.
Today I tried to move our world to a local server, so he can play even when I'm unable to.

## Logs
https://gist.github.com/ShetiPhian/e5d248c32a6b7217fadc349327e3e9ea

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0.162 (64-bit)
* Launcher Used: Curse/Twitch
* Memory Allocated: 4096
* Server/LAN/Single Player: All three, but Server is the one having issues
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: 1.8.0.162 (64-bit)
* Operating System: Windows 10
* Hoster/Hosting Soultion: Same PC as client (will move to another PC once working)
* Sponge (Non-Vanilla Forge) Server?: No

**Comment by justinrusso** [comment]
Did you transfer your world or just start fresh but keeping the same seed?

**Comment by ShetiPhian** [comment]
I tested using fresh worlds with the same seed.
After work I can see what happens when a client world is moved to the server.

**Comment by justinrusso** [comment]
With the information provided the information I've obtained seems true then.

```
dc_preset=Default
```

Needs to be removed. Omitting it or setting `dc_preset=notSet` results in the proper world gen type.

**Comment by ShetiPhian** [comment]
For a bit there I thought village locations where still off, but that was a 3.0.6 vs 3.0.7 difference.

With that change client and server seem to be generating the same.

**Comment by artdude543** [comment]
This is fixed for server files which will ship with 3.0.8
