### ISSUE TITLE
Galacticraft - When placing launch pad inventory inaccessable

### ISSUE THREAD

**Issue by Bill0305** [DarkPacks/SevTech-Ages#2124]
## Issue / Bug

When placing Galacticraft launch pad (either from landing pod or parachute chest) it places the first launch pad then freezes your invenotry. Cannot scroll, use inventory hot keys. No items visible in slot where lanch pad was. 
This happened in System Collapse Lets play. [Sevtech Ages EP28 To the Moon! + Age 5](https://youtu.be/LXiyzg2u2UI?t=804) at around 13:22
## Expected Behavior

Pick up launch pad from landing pod or parachute chest. Place it on your hotbar. Place launchpad in the world. It places the launch pad, however your inventory is frozen now. I cannot access my invenotry by pressing E, cannot select inventory slot by pressing 1-9 and cannot scroll to change selected inventory slot. You have to click on an open area to place a second launch pad. No your inventory is clear of item and you can open inventory. 

It should place the launch pad and it no longer is in your inventory. 
## Steps to Reproduce (for bugs)

1. Land on another planet or return to earth.
2. Retrieve launch pad from entry vehicle or parachute cheat
3. Try to place launch pad.

## Context

To try and fix I reset Controls to default, logged out / in, restarted launcher. I then realized I had to place the item again after watching video from system collapse who had the same issue in his video 

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by PsyberMind** [comment]
Additional Information to this - I had the same thing happen, and when I attempted to access a chest to check functionality, It placed down a landing pad.. So it also Dupes the pad

**Comment by justinrusso** [comment]
This seems to be fixed now (blacklisted from carry-on). As an extra precaution, I blacklisted all of the landing pads.
