### ISSUE TITLE
RFTools Spawner doesn't work with Wild Dog syringe

### ISSUE THREAD

**Issue by Brettflan** [DarkPacks/SevTech-Ages#2150]
## Issue / Bug
The RFTools Spawner doesn't list any required items for a syringe of Wild Dog essence, instead listing "nullRF". As a result, it cannot spawn them.

## Expected Behavior
For it to list some ingredients and be able to spawn them.

## Possible Solution
I'm guessing this problem also affects most if not all other mobs with available essence syringes that aren't currently listed in the rftools.cfg in the "mobspawnamounts" and "mobspawnrf" sections. They could all have ingredients and power requirements added there.

## Steps to Reproduce (for bugs)
1. Place an RFTools Spawner. Maybe connect it to power along with a Matter Beamer which is linked to it, though those shouldn't be needed to confirm the issue.
2. Place a syringe of Wild Dog essence (at 100%) in the Spawner. Observe that no ingredients are listed, and it only lists "nullRF".

## Context
I have no place near my base where Wild Dogs spawn, so I don't find many. I'm in Age 5 and still only have found 2 wild dog pelts, and I still want a pair of those boots. I decided to go the RFTools Spawner route to get more Wild Dogs, so I spent probably an hour wandering around a Plains biome with a Scanner looking for Wild Dogs to fill up a syringe with. Not a single pelt dropped from the ones I killed to fill that syringe. My hope had been that I'd just get the pelt drops while filling the syringe and not have to actually set up a Spawner, but no luck. Now I'm sad.

However, since I'm playing singleplayer, I just went ahead and added entries for the wild dog in the rftools.cfg for myself (settings copied from the vanilla skeleton entry), which works as expected.

**Comment by vadis365** [comment]
The drop rate coded in to the Animalium mod for wild dog pelts is 1:4.
No matter what anyone says, it's hardcoded to be that. Any non-drop dogs you experience are purely RNG and just bad luck. There is no issue with the drop rates or spawning of the mob for that matter, it's just that the people with bad RNG shout the loudest and the silent majority have super sanic awesome boots. :)

**Comment by Brettflan** [comment]
Well, the main issue (and focus of this) is that the RFTools Spawner isn't properly configured in this mod pack to actually work with any of the syringes that were added for mobs beyond the default vanilla mobs.

**Comment by vadis365** [comment]
Hello,
@TomeWyrm - the issue is 100% to do with spawn and drop rates. If a player has to edit in their own configs to circumvent RNG due to not being able to acquire an RNG based item then; it plainly is. Finding the RF Tools mechanic is not accounted for is a direct result of the root cause. I can assure you that the Dogs, Bears and Rats in Animalium are configured to use the Biome Dictionary in forge and as such will spawn in all non-water biomes (and not end or nether). The drop rates are also fine as have been tested live on Darkosto's stream. As for the RFTools spawner compat, @justinrusso or one of the other scripters may add support for such things if it's required and a problem in the pack.
Cheers,
Me.

**Comment by Brettflan** [comment]
> I can assure you that the Dogs, Bears and Rats in Animalium are configured to use the Biome Dictionary in forge and as such will spawn in all non-water biomes (and not end or nether).

I realize you are the author of Animalium, and therefore have direct knowledge of how it works.

However: my main base is in a Lush Swamp biome, which is where I've spent dozens of hours, and I have never had any spawn there. I've also never seen any spawn in my neighboring Darklands Plains biome either.
Actually, I've only seen them spawn in 2 specific biomes: vanilla Plains and vanilla Forest. They're actually only mildly uncommon when I go there to hunt for them.
This is all anecdotal evidence, but perhaps something is not right there. Could other mods be overwriting the spawn rates or something, getting rid of the chance for Animalium mobs from spawning in some biomes? For example, the Lush Swamp biome does occasionally spawn various Abyssalcraft mobs, much like the Darklands biomes. But never any Animalium mods.

Or, is Lush Swamp considered a water biome? It definitely isn't, despite "swamp" being in the title maybe implying otherwise.


All that said, again, the actual main issue here is that the RFTools spawner needs to be configured to work with the syringes that were added for non-vanilla mobs. The syringes are unlocked in Stage 5, but non-vanilla ones do not work due to the lack of extra config needed to support them.

**Comment by vadis365** [comment]
Hello,
Yeah, the spawn rates may be affected by, as you say, another mod. ;)
I'm sure something will be sorted for this issue - as the reason you discovered the RFTools spawner thing as a direct result of your gameplay and have a way around the spawning (which I still maintain is the reason why we are actually discussing this) it seems a good reason to add mobs to the list of things that RFTools can spawn. :+1: 
Cheers,
Me.

**Comment by Brettflan** [comment]
Just for reference, this was closed due to them adding support specifically for Wild Dogs in the RFTools Spawner in the SevTech 3.0.7 release.

Though... might I suggest removing/hiding all of the other various still unsupported full RFTools syringes still listed in JEI, or possibly even adding support for some of those mobs in the Spawner as well? Having them show up in JEI is misleading and implies (to me, anyway) that they should work. Just for reference, only the empty RFTools syringe is listed by default in JEI.
I guess this might warrant just opening another issue, but...

**Comment by artdude543** [comment]
If you could make another issue that would be awesome. Then I'll tag it for next release. Don't worry about filling the template in. Just pretty much say what you said with additional data if you wish.

**Comment by Brettflan** [comment]
OK, done. I did go ahead and roughly follow the template anyway just for tidiness.
https://github.com/DarkPacks/SevTech-Ages/issues/2289
