### ISSUE TITLE
Recipe to convert wines/juices into empty bottles is missing [Rustic]

### ISSUE THREAD

**Issue by EhGneissGuy** [DarkPacks/SevTech-Ages#2157]
## Issue / Bug

Rustic recipe to convert beverages to empty bottles is missing.

![2018-04-30_00 00 13](https://user-images.githubusercontent.com/17113297/39414816-f1221966-4c09-11e8-8c43-9d354015195f.png)

![2018-04-29_23 59 58](https://user-images.githubusercontent.com/17113297/39414818-f4e3acc2-4c09-11e8-970c-40a462d9160d.png)

## Expected Behavior

Place filled bottles into crafting grid to remove contents and return empty bottle.

## Possible Solution

Possible that recipe is gated beyond Age 2 or that the issue is native to the mod itself. If it turns out to be not-related to the custom recipes/progression, I'll pass this on to the Rustic team.

## Steps to Reproduce (for bugs)

1. Fill glass bottle with Rustic drink.
2. Try to craft an empty bottle using the drink.

## Context

Stuck with a bunch of filled bottles that, if drank, result in several minutes of negative effects. For instance, intense nausea, slowness, blindness, etc.

![2018-04-29_23 53 16](https://user-images.githubusercontent.com/17113297/39414852-43d6ae6a-4c0a-11e8-9e2c-08124875335a.png)

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8.171
* Launcher Used: ATLauncher

* Memory Allocated: 4GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: Yes

## Server Information
* Java Version: N/A
* Operating System: N/A
* Hoster/Hosting Soultion: CubedHost, 4GB, Premium
* Sponge (Non-Vanilla Forge) Server?: N/A

* Additional Content Installed?: No

**Comment by LycanBlackpaw** [comment]
A way around this is to place the alcohols into a primal wooden barrel, then break it. This voids the fluid. There're likely a variety of other methods for fluid voids, but this one is probably the easiest.

**Comment by EhGneissGuy** [comment]
@LycanBlackpaw You cannot fill primal barrels with the booze bottles.

**Comment by timmit99** [comment]
You can right click the bottle onto the "Drying Basin" which will hold the liquid for a little bit before it "Evaporates" Thats how i've been emptying bottles.
