### ISSUE TITLE
Sevtech Ages Crashes when loading world

### ISSUE THREAD

**Issue by Asstastic34** [DarkPacks/SevTech-Ages#2162]
## Issue / Bug
Game crashes whenever I try to load the world.

## Steps to Reproduce (for bugs)

1. Load World
2. Wait

## Context
I had just found the location for the Stronghold to the End, started digging for it, and after breaking a few blocks the game crashed. Immediately after that it would freeze up and crash whenever I tried to load the world.

Update: I removed Cooking for Blockheads from the pack as the crash log was saying that the crash had something to do with the oven. As a result I was able to actually get into my game. However moments after it would crash with a new crash log. It doesn't seem that anything in particular is re-creating the crash. At least nothing that is apparent to me.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/LCj7jMXU
Updated Crash Log: (I cropped all but the first 10 "Blocks being updated" because otherwise it was literally so big that it exceeded the pastebin post size limit. Hopefully it's not important because I don't know what else to do.) https://pastebin.com/sDHtiDvz

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0.161
* Launcher Used: Twitch, Jar Launcher

* Memory Allocated: 12MB

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Yes. Soartex Fanver Modded
* Optifine Installed?: No

**Comment by Asstastic34** [comment]
So is there anything I can do to fix or work around this issue while it gets addressed? I have been playing an unhealthy amount of Sevtech Ages recently and if my options are to either start from scratch or not play at all it'll be some sad times.

**Comment by xZonTex** [comment]
Don't know if this will help. First make a backup of your world and then open it with MCEdit.  Then look for the blocks from the crash logs and remove them. Then save the world and see if you still have the problem.

**Comment by SteseDav** [comment]
allocating 12GB of RAM seems excessive, and seems to cause issues. How much RAM is available on the machine? if you are allocating more than half, then you need to reconsider this... There seems to be a bug within Java/Minecraft that causes odd issues. Try 6GB and see if the problem re-occurs.
