### ISSUE TITLE
Crash with RFTools Filter - Sevtech v3.0.7.6

### ISSUE THREAD

**Issue by Muddr** [DarkPacks/SevTech-Ages#2166]
## Issue / Bug
Attempting to put an item into a RFTools Filter causes the game to crash. Fine in 3.0.6 without issue.

## Steps to Reproduce (for bugs)
1. Grab a filter from RFTools.
2. Place item in filter.

Video: http://muddrdev.com/mp4/77bbcf04.mp4

## Logs
* Client/Server Log: https://gist.github.com/Muddr/7a2a5f3870304bb74ef85ac49420ea11
* Crash Log: https://gist.github.com/Muddr/24117f05473d3ad92cee458ac32ccccd

## Client Information
* Modpack Version: 3.0.7.6 Test
* Java Version: 1.8.0 171 64bit
* Launcher Used: MultiMC
* Memory Allocated: 8gb

**Comment by artdude543** [comment]
This looks like an issue with MouseTweaks. Neither mod updated so far so their the same versions as in 3.0.6.

As looking at the report looks like MouseTweaks derped while handling the mouse event internally which then cascaded to a crash with the item you were holding. Can you reproduce this over and over or was this a one-off? If so when disabling MouseTweaks can you still make the crash happen?

**Comment by Muddr** [comment]
It does it every time I try.  Either my main save (stage 5) or a flat test world (all stages).  Does it with shift-clicking an item into the filter also.

Logs with MouseTweaks disabled:

* Client/Server Log: https://gist.github.com/Muddr/9fb84d307995aa2be70ac8504c7c1012
* Crash Log: https://gist.github.com/Muddr/5d7fbaaca10eb6d48c28a590d25c39ce
* Debug Log: http://muddrdev.com/txt/12749aed.txt (too big for a Gist)

**Comment by artdude543** [comment]
Awesome thanks! It's easier to report this with nothing of MouseTweaks in the report so this confirms it's the mod 🙂
