### ISSUE TITLE
Fluid filter crash in Blood Magic input node.

### ISSUE THREAD

**Issue by talonos2** [DarkPacks/SevTech-Ages#2174]
## Issue / Bug
Fluid filter crashes the server quite often. See below for repro steps.

## Expected Behavior
I expect the server not to crash when using fluid filters.

## Possible Solution
Update Blood magic as soon as a new build comes out. This commit fixes all the issues: https://github.com/WayofTime/BloodMagic/commit/d29b91a1068fa007bb2604f17b717aa2852d48c7

## Steps to Reproduce (for bugs) 
Example:

1: Put an Input Node above a TiC casting table with an ingot cast in it.
2: Put a fluid filter into it.
3: Put a bucket of TiC Molten Bronze into the Fluid Filter.
4: Put a master routing node nearby.
5: Use a node linker to link the input node to the master routing node.
6: Crash. World is not corrupted; loading the world will revert to directly before you linked the nodes.

## Context
Trying to get an automated smeltery setup using blood magic.

## Logs
No need to post logs; the crash is already fixed on Way's end. I'm just notifying you that you'll need to update Blood Magic soon to avoid fluid-filter related crashes in the near future. (After all, fluid filters have a recipe now, right? #2003 ;) )

**Comment by artdude543** [comment]
Fixed in 3.0.7
