### ISSUE TITLE
Baykok bow and arrows are restricted for one of the two players that play with "Together Forever"

### ISSUE THREAD

**Issue by dmitry-diolan** [DarkPacks/SevTech-Ages#2179]
## Issue / Bug
I play with my son, configuring "Together Forever". When we killed the Baykok at the end of stage 0, we get bow and arrow. My son can use them, but for me these items are still restricted. We tried to kill Baykok several more times (once I killed it myself from the beginning till the end). But these items are still restricted for me.
## Expected Behavior
I think the items should become available for all "Together Forever" players after killing Baykok.

 I think this is some kind of bug that you can fix in the future version. 

May be you also have some workaround for me for now (e.g. edit some config files or using some command)?

**Comment by dmitry-diolan** [comment]
Hello,

I play with my son, configuring "Together Forever". When we killed the Baykok at the end of stage 0, we get bow and arrow. My son can use them, but for me these items are still restricted. We tried to kill Baykok several more times (once I killed it myself from the beginning till the end). But these items are still restricted for me. I think this is some kind of bug that you can fix in the future version. May be you also have some workaround for me for now (e.g. edit some config files or using some command)?

**Comment by justinrusso** [comment]
Do they have the advancement?

**Comment by dmitry-diolan** [comment]
Yes.

**Comment by justinrusso** [comment]
Every player has the baykok advancement? Just not all can see the items?

**Comment by flamingram** [comment]
yeah im having same issue differnt server

**Comment by justinrusso** [comment]
@flamingram do both players have the advancement?

**Comment by flamingram** [comment]
yes
