### ISSUE TITLE
Mekanism Logistical Pipes Bugging Out

### ISSUE THREAD

**Issue by kpress15** [DarkPacks/SevTech-Ages#2183]
# Issue / Bug
I have an issue where items traveling through my mekanism logistical pipes get stuck. 

# Expected Behavior
Items to travel through the pipe and not get bugged and stuck in the pipe.

# Possible Solution
Not sure.

# Steps to Reproduce (for bugs)
Sometimes it happens and sometimes it works fine, so I'm not positive how to reproduce. I think that maybe traveling to a different dimension may be the cause to mess them up. I am not positive, though. Still should not happen.

# Context
Sometimes items in mekanism logistical pipes get stuck or even refuse to pull items at all. I have everything connected properly. The only way to fix this is to sometimes to restart the server, however, this only works part of the time. The other way to fix this is to completely go through and disconnect all the pipes and re-lay them down. This is very tedious and very obnoxious to do, though.

# Client Information
Modpack Version: 3.0.6
Java Version: Latest
Launcher Used: Jar Launcher
Memory Allocated: 8GB
Server/LAN/Single Player: Single PLayer
Resourcepack Enabled?: None
Optifine Installed?: Yes

**Comment by kpress15** [comment]
Also, just now I think when trying to remove the pipes and re-place them, I am pretty sure I lost all the items in the pipe.

**Comment by Jandakast** [comment]
Is it all pipes or only when connected to certain machines/inventories. Please post a screenshot of your setup.

**Comment by Jandakast** [comment]
Are any/all/some of your pipes/machines chunkloaded?

**Comment by Jandakast** [comment]
Ok so this looks like it is an ongoing Mekanizm issue that they are trying to work out. I'm trying to setup my dev version of the pack machines and setups from your screenshots so I can continue to test this as Mekanizm updates are released. 

https://github.com/aidancbrady/Mekanism/issues/4676

**Comment by kpress15** [comment]
@Jandakast Thanks, I appreciate it the help! Glad it wasn't just me.
