### ISSUE TITLE
Cyclic power cables not pulling power from Immersive Multiblocks or inputting to Capacitors

### ISSUE THREAD

**Issue by thatguyfrai** [DarkPacks/SevTech-Ages#2185]
## Issue / Bug
When attempting to switch to a less potentially deadly form of power transmission in Age 4, I attempted to switch to Cyclic's cables only to find that my capacitors would not accept energy from them, nor would they pull power from my Immersive Petroleum Alternator setup. Further testing in a new creative world yielded the same results.
In creative, I tested IE Thermo gen and Kinetic gen with the cables inputting into Mekanism's energy cubes and they properly transferred power and was able to pull energy from IE Capacitors (LV, MV, and HV) using the Cyclic cables into an excavator.

## Expected Behavior
Cyclic cables should transmit RF between Immersive Engineering and Immersive Petroleum generators multiblocks and be able to input RF into capacitors.

## Possible Solution
Wait for @PrinceOfAmber to address the [issue](https://github.com/PrinceOfAmber/Cyclic/issues/788) and update Cyclic

## Steps to Reproduce (for bugs)
1. Setup an IE Multiblock Power Gen or a creative capacitor
2. Place Cyclic power cables between the power source (power extraction cable optional) and an empty capacitor
3. Correctly configure capacitor input/output
4. Check power level of the receiving capacitor.
5. Attach Mekanism Energy Cell or other non IE power storage option to cable
6. Check power level.

## Context
Energy Cables are a safer alternative to HV wires from IE and have a transfer limit of 8000 RF, whereas HV wires are limited to 4096.

## Client Information
* Modpack Version: 3.0.6
* Java Version:1.8.0.101
* Launcher Used: Twitch
* Memory Allocated:8gb

## Workaround
The Power Adapter unlocked in Age 4 can attach directly to the face of a power output and allow Cyclic to pull energy indirectly from IE Diesel Generators and Capacitors, however this method will not work with Immersive Petroleum's Alternator.

I know this issue has already been reported on the Cyclic github, however I thought it'd be useful to have a record of it on the Sevtech github, since it didn't occur to me until I was already writing this to check the github for a specific mod, though the issue referred to above only specifies the capacitors and the charging station from IE, and not Immersive Petroleum. I apologize if this is considered an issue that has already been reported for SevTech Ages.

**Comment by NerevarDZN** [comment]
It' works - all you need to do is specify I/O on IE capacitors

**Comment by PrinceOfAmber** [comment]
Fixed in dev but i didnt make it in time for 308. pinging so bot doesnt auto close
