### ISSUE TITLE
Crash on Load World in Betweenlands dimension

### ISSUE THREAD

**Issue by Relsaye** [DarkPacks/SevTech-Ages#2186]
## Issue / Bug
On attempt to load my world, game does one of two things:
1. Loads to the loading screen for the betweenlands (where I was last located), and then freezes. Its not just taking a while; I've left this shit trying to load for hours. Went and picked up daughter from school. Got some groceries. Still at the loading screen.
2. Straight up crashes. ONCE I actually got to a point where I saw my inventory load in, got all excited, and then it just closed, leaving a sevtech shaped hole inside of my heart.

## Expected Behavior
Well, it should be loading my world, with me in a betweenlands boat suffering from the monsters there. Instead it doesn't load and is stuck or crashes.

## Possible Solution
Not really sure, I am having trouble determining what the problem actually IS looking at this bug report. I tried at one point using an NBT editor style thing to change my dimension, but I think it was for an older version, doesn't seem to work/actually save my changes, so I'm still stuck with the same problem. I could theoretically delete my player data, but then I'd have to figure out what I had on me, spawn that stuff in, potentially redo my progress through the ages, and dont want to do all that.

Edit: Alright, so. Figured out how to use the NBT editor to change dimension and location and such, and am STILL experiencing crashes. Attempted to reinstall the pack, copy the world to the new instance of the modpack, and change my location to the overworld at spawn and it once again got to the point of showing my inventory very briefly before crashing... again. I would normally assume it was just something wrong in my inventory, but I was able to (at one point in testing), delete the world file for The Betweenlands, and everything worked. The problem being that the Betweenlands doesn't by default contain a portal BACK to the overworld. Realized I still have the betweenlands dimension folder on that run, so am going to delete it and try to load it once more.

Edit 2: That didn't work. I've been troubleshooting/trying to get this to work for about 6 hours now. Gonna get around to starting my day, take daughter to school, do some household chores, and come back and see if anyone has any ideas. Crash log for this test is added below.

Edit 3: Okay so probably final test until someone posts/tells me something new to try, but looking back on older issues with crash on load for the pack had a few people with outdated graphics card drivers. My version was ahead of what was usually recommended as the minumim update, but updated mine just in case that was the problem. It wasn't. Same issue, but have added the new crash log just in case its helpful.

## Steps to Reproduce (for bugs)
1. Launch game from twitch.
2. Attempt to load world
3. Crash or get stuck loading

## Context
I want to play the modpack.
I am unable to play the modpack.
I'm sad because this is a baller modpack and have been having a blast with it.

## Logs
https://pastebin.com/JCZB0YPx - Here is a crash log from when it actually crashed/closed the client.
https://pastebin.com/7tZvAY7j - Here is a crash log from when the loading just stalls out and I have to close it using task manager; it doesn't respond to normally trying to close it.

EDIT: https://pastebin.com/NRJnn3GX - Here is the crash log for after installing second instance of modpack, moving world over, and editing location using NBTExplorer to move me to the overworld and spawn coords.

EDIT 2: https://pastebin.com/6gPRVcuV

EDIT 3: https://pastebin.com/niueUy22

## Client Information
* Modpack Version: 3.0.6
* Java Version: Java 8 Update 162 (64 Bit)
* Launcher Used: Twitch
* Memory Allocated: 4G
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by DenisMasterHerobrine** [comment]
I think, that's the memory you allocated is creating this issue. Try to allocate 6GB+ in the Twitch/MC launcher and go to the betweenlands.

**Comment by Relsaye** [comment]
Upped ram to 6gb and ran it, same issue (in this instance stuck on loading. Again, gave it way more than ample time to load, it wasn't just slow. Can also usually tell because in task manager the memory will still be used but the disk usage will drop down to 0% when its crashing in this manner.)

https://pastebin.com/UpjgemA4

**Comment by Relsaye** [comment]
Upped ram to 6gb and ran it, same issue (in this instance stuck on loading. Again, gave it way more than ample time to load, it wasn't just slow. Can also usually tell because in task manager the memory will still be used but the disk usage will drop down to 0% when its crashing in this manner.)

https://pastebin.com/UpjgemA4

Then realized I was trying on the new instance of the pack with moved location; tried with original instance backup with original location, with the Ram upped to over 6 gigs; also crashed, same type as usual, with the one 'caveat' being that when I'm IN the betweenlands, it gets to the loading screen of the betweenlands itself before crashing. https://pastebin.com/V0dp4xFU

**Comment by Relsaye** [comment]
Based on this (https://github.com/Darkosto/SevTech-Ages/issues/1739) post, I updated my drivers.

**Comment by TheCyberBrick** [comment]
This is most likely a duplicate of #2006.
I have no idea what's going on here except that there seem to be a ton of blocks dropping/breaking in a chain reaction and then causing this crash. No clue how or why this would happen, the only thing that I can think or right now is world corruption. Did you ever add/remove mods from the pack?
Maybe somehow the internal block ID table broke and blocks got replaced with other blocks, but that's just a very wild guess.

**Comment by Relsaye** [comment]
No, I've disabled the betterfoliage but I did that from its ingame gui, it's still installed. At this point unless anyone has a better solution, I'm going to try to remove the dimension, as that let's me log in, and try to work towards a swamp talisman I guess? My only worry is that using an nbt editor to move me to the overworld still resulted in crashes; I wasnt in the betweenlands long enough to mind losing that world, but losing my overworld progress would be pretty devastating and I'd probably just drop the pack

**Comment by TheCyberBrick** [comment]
Do you mind uploading the world? I'd like to have a look at it

**Comment by Relsaye** [comment]
Sure thing, wasn't sure if there was a preferred host so just used mega, let me know if I should be using something else. This is the original backup I did, so with no changes and with me in the betweenlands (which is dim20 in case unawares.)
https://mega.nz/#!LFdnTQZZ!gLbgxFHMbBcqIF6oV4UF1V621GzMluqq6oTDEknwktc

As a side note, got my swamp talisman (fuck wights btw), made the portal back, and while it worked for a MOMENT (IE could move, checked my map book to see where it put me), it then crashed after a few seconds and the crashlog looks unfortunately familiar.
https://pastebin.com/c1S9g9rT
Worth pointing out this actually has a good chunk of the 'block being updated' segments cut out; the entire error log went over the limit.

**Comment by TheCyberBrick** [comment]
Thanks.
The corruption isn't in the Betweenlands world (maybe there too, but haven't found any so far), but the overworld seems to be partially corrupted. I opened the world in MCEdit and found that a lot of blocks near bedrock in the overworld were replaced with "traverse:fir_door", so either the world or the block IDs got corrupted somehow.
Maybe related to https://github.com/MinecraftForge/MinecraftForge/issues/4904?

**Comment by Relsaye** [comment]
Any way to fix it? Or is it just corrupted and nothing to be done?

**Comment by TheCyberBrick** [comment]
It doesn't look too good unfortunately because the world file is corrupted. Do you have a backup from before the crash occurred? It *might* be possible to restore the block IDs (if that's the part that is broken) and fix the world like that.

**Comment by Relsaye** [comment]
No, I don't; was playing just fine (had gotten to the betweenlands, was just exploring around/recovering corpse run stuff), and then crashed and couldn't get it to reload. Really sucks, I was having a great time with the pack but its a LOT to lose unfortunately :(

**Comment by TheCyberBrick** [comment]
Which version of the mod pack did you initially create the world with?

**Comment by Relsaye** [comment]
One of the earlier ones; started playing right around release.

**Comment by TheCyberBrick** [comment]
I'd need to know the exact version

**Comment by Relsaye** [comment]
I'm not certain; is there a way to check?
It may well have been 3.0.0/initial release, if not it was 3.0.1; there was a fix in 3.0.2 I needed to move on at one point, so I know it was one of those two at the very least.

**Comment by TheCyberBrick** [comment]
I tried copying over the block IDs but it was still corrupted in some places. This probably isn't fixable anymore unfortunately

**Comment by TheCyberBrick** [comment]
You can try doing that with MCEdit, though it looked like most important blocks were missing from the base
