### ISSUE TITLE
AE2 Duplication bug

### ISSUE THREAD

**Issue by 3jlowes** [DarkPacks/SevTech-Ages#2188]
## Issue / Bug

AE2 Formation planes set to drop items as entities (not place block mode) will duplicate the stack (ie if there is 2 items in a stack it will drop 4. if 64 it will drop 128) without removing the item stack that was supposed to be dropped.
## Expected Behavior

Formation Planes from AE2 should not duplicate items.

## Possible Solution

There is a mod in the pack that cancels the way AE2 handles drops. I havent tried to find it myself, but if the mod that is causing it can change how they handle adding custom entities for existing items that allow for in world crafting.

Another note: Forge could implement something different for AE2 to use, so it may not be worth investigating this issue, but just thought I would point it out. But as stated by yueh they probably wont implement a fix until 1.13

## Steps to Reproduce (for bugs)

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3458

That link goes to the issue I created on AE2 issue tracker when I first thought it might have been an AE2 bug. My setup is a gif there. But all that is need is an AE2 formation plane hooked up however you would like. They mod authors also provide reasoning as to why they implement item dropping the way they do.
## Context

This affected me because I was trying to use a AE2 only setup for automation of fluxed quartz and all of the pure seed growth. I would consider this issue to be a LOW priority, but it is still an issue

The context is that If a player wanted to only use AE2 for automation then it would not be possible. Currently I am using a precise item dropper which works fine, but is not from AE2

## Client Information

* Modpack Version: 3.0.6
* Java Version: 182
* Launcher Used: Twitch
 
* Memory Allocated: 7 GB

* Server/LAN/Single Player: Multiplayer
* Resourcepack Enabled?: No
* Optifine Installed?: Yes
* Shaders Installed? No

## Server Information
* Java Version: 182
* Operating System: Windows 10
* Hoster/Hosting Soultion: Dedicated Linux Server
* Sponge (Non-Vanilla Forge) Server?: Vanilla Forge

* Additional Content Installed?: None

**Comment by Jandakast** [comment]
This looks like it is caused by Realistic Item Drops. Reported to mod dev.

https://github.com/Funwayguy/RealisticItemDrops/issues/12

**Comment by justinrusso** [comment]
This cant be left in for 3.0.7. We have a few options:

1. Remove the recipe for the formation plane
2. Remove Realistic Item Drops
3. Wait for Realistic Item Drops to fix the issue

**Comment by 3jlowes** [comment]
Try Item physics mod. https://minecraft.curseforge.com/projects/itemphysic I cant test if for myself right now, but please dont remove formation plane.

**Comment by artdude543** [comment]
So after discussing the issue and after a few attempts at fixing. Item Dropping from AE will be kept disabled until a better solution is found for the problem.

There are other blocks in the pack which can be used for ejecting items into the world, which are not affected by the bug. So this will the route we force people down.
