### ISSUE TITLE
Different Astral Sorcery Gateway Crash

### ISSUE THREAD

**Issue by Lewdicolo** [DarkPacks/SevTech-Ages#2211]
Tried to teleport from Overworld to Jupiter with an Astral Sorcery Gateway (which I've done successfully multiple times), and it crashed the server and the client. Restarted the server, and crashed upon login with the same crash. 

I tried searching this github for this problem, but couldn't find another post with this specific crash. Apologies if it's a duplicate.

Crash Report: https://pastebin.com/GAEzgatU

SevTech Ages: v3.0.6
Astral Sorcery: v1.8.5

**Comment by artdude543** [comment]
Relates to https://github.com/HellFirePvP/AstralSorcery/issues/678

**Comment by justinrusso** [comment]
This was added in 3.0.7
