### ISSUE TITLE
Fake players can't mine non geolysis, fortune affected ores

### ISSUE THREAD

**Issue by Rakede** [DarkPacks/SevTech-Ages#2212]
## Issue / Bug
Fake players (RF Tools builder, AA Block breaker, etc) turn any non geolysis redstone/lapis/emerald/certus quartz into cobblestone upon mining. Ores created are from the Astral Sorcery mineralis ritual. Also if a builder is set in the nether, All Ardite and Cobalt it mines turn into low grade charcoal.

## Expected Behavior
Fake player to mine the ore and give the appropriate drop.

## Possible Solution
Replace vanilla ore in the mineralis ritual with geolysis versions, see https://hastebin.com/uhexiviwoq.coffeescript

## Steps to Reproduce (for bugs)

1. Set up the mineralis ritual from astral sorcery and roll until it creates an item dropping ore/Set up builder in Nether
2. Mine with a fake player and receive cobblestone instead.

## Context

Was to be used as an alternative to the void ore miner as anything made this way on the large scale requires stage 5 anyway.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:3.0.6
* Java Version:Latest
* Launcher Used: Jar

* Memory Allocated: 11GB

**Comment by Rakede** [comment]
Could possible be due to "fake players" being age 1 maybe?

**Comment by artdude543** [comment]
We are aware of this issue. It's being worked on but will take time as it needs more extensive testing than normal player staging.

**Comment by artdude543** [comment]
Will be resolved in 3.1.0 :)
