### ISSUE TITLE
Client crash Galacticraft

### ISSUE THREAD

**Issue by mori912** [DarkPacks/SevTech-Ages#2214]
## Issue / Bug
Client crash when trying to break a lighting panel(Dark) that looks like a marble block from chisel

## Expected Behavior
Block gets broken and drops on the ground

## Steps to Reproduce (for bugs)

1.Shift right click a lighting panel onto a marble block from chisel
2.Try to break it

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/gwCC20rV

## Client Information

* Modpack Version:3.0.6
* Java Version:1.8.0.161 64bit
* Launcher Used:Twitch app

* Memory Allocated:8192

* Server/LAN/Single Player:Multiplayer
* Resourcepack Enabled?:No
* Optifine Installed?:Yes

**Comment by artdude543** [comment]
What was the marble block/type you had being the block to show as?

**Comment by mori912** [comment]
Raw marble from chisel

**Comment by artdude543** [comment]
This was not able to be reproduced. If this issue still happens when 3.0.8 lands please make a new issue with more data. I.E. Video is you can make it happen over and over.
