### ISSUE TITLE
Totemic Endermen Totem flashing is both annoying and dangerous

### ISSUE THREAD

**Issue by Sorbe** [DarkPacks/SevTech-Ages#2237]
## Issue / Bug
The Night Vision buff you get from the Endermen totem is great, except that it starts at ~15 secs duration and refreshes at about ~6 seconds,  Below 10 "seconds" it strobes constantly making the buff visually annoying and a real danger for Epileptics.  Also, if actually check the countdown, it's ticking about 2 seconds off for every 1 second of real time.

## Expected Behavior
If the buff is constantly up, I would expect no flashing warning at all.
Please consider the health danger and liability of inducing seizures in anyone.

## Possible Solution
I would suggest starting at 20 seconds and refreshing before 10 seconds left.
I would also suggest investigating why the time countdown runs at double speed.

## Steps to Reproduce (for bugs)
1. Make a 2 high totem, totem base, enderman.
2. Stand near the totem and watch the screen strobe half the time.

## Context
I was trying to use this totem buff to help defend a fort in SMP - stopped because it was aggravating everyone.

## Client Information
SevTech Ages 3.0.6
Java 8u172
Jar Launcher
Java VM Space 8GB
Client/Server
Soartex FanVer
No Optifine.

**Comment by ljfa-ag** [comment]
>  I would also suggest investigating why the time countdown runs at double speed.

Were you in the Hunting Dimension? Potion effects tick down twice as fast there, which also applies to Totem effects. However this is fixed in the newest version of Hunting Dimension.

I'll see what I can do in the general case.

**Comment by artdude543** [comment]
3.0.7 has the latest build of Hunting Dimension so part of the issue would be resolved. But this is an issue we'd want to find some kind of resolution/patch. As we're aware of users playing the pack who are affected by some effects and strobing.

An alternative could be to install the mod which removes the flashing effect which could be something if Totemic can't resolve "cleanly" w/o touching the base MC. (Which in turn could make the code messy xD)

**Comment by PsyberMind** [comment]
I don't believe it can be fixed without digging into MCs base.. It's a visual representation of potion effects wearing off. Until 3.0.7 comes out you can edit the HuntingDim config to:

` # While true, beneficial potion effects on players will wear off twice as fast. [default: true]
    B:quickPotionWearOff=false`

Which will fix that, as for the overworld issue, the only time I've run into it is when I'm out of range of the totem. However I can see where lag may cause the tickrate to mess up. This issue is also present in Astral Sorcery, since Liquid Starlight also gives a Night Vision effect (for like 2 seconds once you get out of a pool of it)

Other than either adding 
https://minecraft.curseforge.com/projects/no-night-vision-flashing 

or installing it as a client-side mod, I don't see a way around this

**Comment by Jemsuper** [comment]
Maybe add the "no nightvision flashing"mod

**Comment by PsyberMind** [comment]
That's what @ljfa-ag is saying. He looked at how the mod was implemented, and he may be able to add the same concept to Totemic to prevent having to install another mod

**Comment by artdude543** [comment]
The `no-night-vision-flashing` mod will not be added by default to the pack. You are more than welcome to install it yourself.

Otherwise hold your prayers and send cookies to the Totemic devs and you may get it on the next update to SevTech ;)

**Comment by Sorbe** [comment]
As of 3.0.7, the Night Vision flashing from the Enderman Totem in the Hunting Dimension is not semi-continuous.  It only flashes when the Night Vision buff is actually lapsing, just like it does in the Overworld.  I also confirmed that Liquid Starlight also causes the same flashing effect when it lapses.

**Comment by ljfa-ag** [comment]
Yeah it has been added to Totemic 0.11.2. Hopefully it won't cause problems with all of the other mods.
