### ISSUE TITLE
Frequency of Recurrent Structures - Review

### ISSUE THREAD

**Issue by Sorbe** [DarkPacks/SevTech-Ages#2242]
## Issue / Bug
Recurrent Structures in some Biomes is potentially excessive

## Expected Behavior
Some biomes like Jungles and Deserts seem to have quite a few of the same recurrent structures.
(see the screenshot of Jungle attached, Desert screenshot forthcoming)

## Possible Solution
Decrease the density of those structures in said biomes
(actually, I would recommend a field survey of this topic in general)

## Steps to Reproduce (for bugs)
Fly around and observe how often each of the recurrent structure is appearing in general.
For biomes which are wide open with a lot of visibility, like deserts, reduce occurrence chance more

## Context
I've been walking around the world and like it when I'm surprised by the recurrent structures... but when I can see 10 other ones nearby it's far less wonderous and special.

**Comment by LycanBlackpaw** [comment]
I don't see any Recurrent Complex structures in that picture. Those stone rings are from Betweenlands; underneath the altars in the middle is a spawner that is needed to make the talisman to get to the dimension.

**Comment by Sorbe** [comment]
Regardless of what produces the small temples in the desert with the Firefly Jars and the Druid Circles, the density of them on the landscape could use a review.  Probably post 3.0.7.

**Comment by tahg** [comment]
Despite the fact you had capitalized it, I had assumed you were just using recurrent to mean something appearing multiple times, and not in reference to any particular mod? I had noticed this too, with multiple nether portals no more than a couple chunks away from each other.
