### ISSUE TITLE
Request to limit Dread Lands chain reaction spawning

### ISSUE THREAD

**Issue by Calgor** [DarkPacks/SevTech-Ages#2255]
I'd like to put in a request for some form of limitation on the Abyssalcraft integration within this mod pack. Due to some rather terrible decisions, a few of us on a server have pretty much messed the entire thing up completely and it doesn't look like there are easy ways to tidy this up.
 
## Issue / Bug
The issue seems to arise during the Dread Lands progression of Abyssalcraft whereby the goal is to defeat Cha'garoth in their lair and obtain the next key needed to progress this mod further. Unfortunately the sheer number of dreadlings which spawn in that section and the nature of Dread Plague itself being impossible or unpredictable to remove means that death is highly likely.

Enemies seem to grow and split off one another, with lesser spawn becoming dread spawn and becoming greater spawn if left long enough. If then a player decides to remove them using a poison like Corallium Plague (this was not the brightest idea in retrospect), the plague splashes out on death to the nearby lower tier minions that spawn when the creature dies of it and triggers another Corallium plague on them. However the spawnlings dont die quick enough to not become larger ones and so on but remain affected by it...it's an infinite loop. If only I had a blood altar under it I could be able to fill a Tier 6 altar entire pool within a few ticks. 

We're now stuck at the point where the server is hitting memory limits and exceeding it with no way to rectify this. The vanilla kill command will kill the mobs but that will force them to split into lessers which will grow up and add more to it and by the time we got some of them down there were too many on there for the game to remain stable to repeat and finish them. It's a never ending cycle.

We're up to the point where that world and that server is almost unplayable and have had to ask the admin to remove the world itself.

## Expected Behaviour
That the *ahem* things would die and be done with it or to not be stuck in endless cycles of splitting and slowly multiplying ad-infinitum

## Possible Solution
Some method of limiting the spawns of these creatures or limit to the number of enemies within this region would be ideal as I imagine I'm not the only one that was dumb enough to try that...that or a command to remove (not kill) mobs and thus break the cycle.

## Steps to Reproduce (for bugs)
1. Enter Dreadlands from Abyssal craft as per progression
2. Attempt to kill the boss Cha'garoth without just resorting to lava'ing the whole room and losing the thing we came for.
3. If the mobs are not killed quickly enough they will grow and spread. The player deaths add to the count of enemies as well.
4. Player tries to come up with a good idea and throw a Splash Potion of Corallium Plague into the mix
5. Dreadlings die. Slowly. But not before splitting and growing.
6. Enjoy watching the chain reaction of endless and impossible to stop spawns.

## Client Information

* Modpack Version: 3.0.6
* Java Version: Version 8, Update 161
* Launcher Used: Twitch Launcher

* Memory Allocated: 7GB

**Comment by Calgor** [comment]
To further clarify, it's not even the client side that's running out of memory (I can throw more at it if required), it's the server that seems to be giving up and cannot keep up with the repeated spawns.

**Comment by Arkene** [comment]
I'd just like to add that the dread plague made it way into the overworld, (not me), turning the area around a well of suffering into dreadlands, At some point (there is a chunk loader) some mobs have spawned in that chamber that when they died have become lesser dreadbeasts. I can only assume that the well of suffering killing them has caused a death cycle as the room, large enough for a fully upgraded blood alter, but only at tier 4 at the moment, was so full with them i was unable to see the blocks beneath. As they are killed, more spawn. Switching to creative mode and using the kill command to kill them all, only exasperated the situation. I suspect that at least one lesser dread beast is being spawned every time a cloud of dread plague is ending or being killed.

**Comment by drakkensong21** [comment]
Could you not turn it to peaceful and back to normal or whatever

**Comment by Arkene** [comment]
what do you mean?

**Comment by MissPotato** [comment]
"/difficulty peaceful" then "/difficulty normal"
that would instantly kill all hostile mobs that are currently loaded. As for biome issues, you can either cheat and use, make a fence/box around it, to contain the bad stuff.

**Comment by Degonsky** [comment]
There is ritual to cleanse influence of the abyss, but it is used to clear spreaded darklands, not sure about dreadlands.

Ritual accessable with abyssalnomicon.

Also, did't had any problems with dreadbeast, used "Armara" attunement on me from astral sorcery with all perks, 2 pieces of enchanted armor and tinkers tools (shield with handle from cacti - blocks melee dmg with thorns effect)

Good luck :)

**Comment by Calgor** [comment]
Thanks @MissPotato , muppet moment to forget about that one. I could probably have used Blood Magic Ward of Sacrosanctity which I think does the same in a 60x60x60 radius or something huge. I have blood to burn...

@Degonsky , issue was more the plague itself which seems to bypass the armour and shielding. It was a long lasting potion effect which seemed to just randomly affect without even is being directly hit by anything but actually further reading suggests that was a bug where it would chain randomly from mob to mob even already infected ones and that our continued deaths were making it difficult to break the cycle.

I saw 3.0.7 contains change for plague, making the recipe easier to obtain for the antidote and I seem to recall something changing the mechanics of the plague spawning but I can also use the difficulty change as well. I withdraw my issue.

**Comment by Degonsky** [comment]
@Calgor, dread plague in earlier version of abyssalcraft sometimes refreshed itself, but eventualy it stopped. That was a bug, now fixed. All other aspects of plague remains the same

**Comment by Calgor** [comment]
@Degonsky, yep that explained it. I think the initial version in use was an older release.

**Comment by Arkene** [comment]
they have 300 health...and the ones they spawned seemed to grow up to the bigger ones quicker then i could kill them, even in ops mode and having spawned a high end weapon. I would suggest limiting the amount of them that can exist on a server at any one time, and limit the amount of children each one could spawn at any one time. Make the fights against them more tactical. Otherwise you just end up killing them by flooding the chamber with lava and thats just kinda lame.

**Comment by Degonsky** [comment]
@Arkene
These bosses mostly late-game stuff, they don't open much and there's not that much of a reason to fight them early, he called "dreadbeast" for a reason :D

I had no truble with them, were using tinker's yoyo, had full ench armor and saturation buff.Unbreackable shield with cacti handle (battlesighn) helps aswell. I guess any kind of aoe dmg will work well, also - explosives (like "Angry Pebble")

Also - good idea to do that with friend, but I killed dreadbeast alone.

About breackout - they spawn like any other hostile mob, except when they were " born" from other spawns.

Good luck :)
