### ISSUE TITLE
Creeping Moss (Coralium Swamp Biome) in the Hunting Dimension creating Ocean Biomes.

### ISSUE THREAD

**Issue by demosthien** [DarkPacks/SevTech-Ages#2287]
## Issue / Bug

Used Coralium Swamp Creeping Moss in the Hunting Dimension creates an Ocean Biome.

See this previously closed issue.

https://github.com/DarkPacks/SevTech-Ages/issues/1883

**Comment by artdude543** [comment]
Don't report an issue which was already closed. Read the comment posted by the modpack developer.

**Comment by demosthien** [comment]
Sorry for being a PITA, but the closure prevented me commenting in that location so I was forced to open a new issue.

The comment by the person who closed the issue indicates they misunderstood what was being described.

Their comment indicates they think the problem is with creating the creeping moss… The issue is not with creating the moss. 

The issue is with actually using it in the Hunting Dimension (as noted in my new issue).

Seriously, I’ve tested this a dozen times or more and it is occurring as stated.

Yours,

Matthew

**Comment by demosthien** [comment]
I just installed the latest update for the mudpack and have not been able to replicate the issue again. So, I guess the glitch has been fixed by something in that.
