### ISSUE TITLE
[Suggestion] Better With Mods sidings should be in the Ore Dictionary as slabs

### ISSUE THREAD

**Issue by griseouslight** [DarkPacks/SevTech-Ages#2290]
## Issue / Bug
Better With Mod's siding blocks should be listed as a slab in ore dictionary so it works in the respective crafting recipes.

## Expected Behavior
in SevTech 3.0.7, wooden sidings do not work in any slab recipes other than the ones that better with mods already implements.

(I accidentally submitted this before completing/formatting it the first time, my bad)

**Comment by justinrusso** [comment]
With the way the siding blocks work, this is not possible
