### ISSUE TITLE
Once-visible Abyssalcraft item names reobfuscating after defeating the Ender Dragon.

### ISSUE THREAD

**Issue by dalsio** [DarkPacks/SevTech-Ages#2294]
## Issue / Bug
After defeating the Ender Dragon and using the portal to get back to the overworld, I went to put all the Coralium Plagued Flesh that I had collected from the Abyssal Zombies that spawned and noticed that the name was obfuscated as if I had not "learned" about it, as were the various shadow gem pieces (I of course had to have known about and used them in the course of getting to that stage) including the ones I had already collected and stored in a chest in the overworld. I don't know for sure if it was defeating the Ender Dragon itself, dying a few times, or running the end-credits but I know for a fact that shortly after starting the encounter I had some plagued flesh that appeared as normal. I also converted to creative mode once or twice so I could fly and get my stuff (I got flung off into the void by the dragon and didn't realize my stuff was floating above rather than in the dead zone). Also as a result, I gained the ability to teleport using JourneyMap which I used several times (didn't realize it was only available because I started a LAN session) however I'm pretty sure I saw that everything was fine by the time I went out of cheat mode (I was still in the LAN session but I didn't want to use any cheats for the fight itself) and started the encounter proper. Strangely, nothing else was affected, Coralium Gems, my Yog statues, the Beneath Teleporter and the Energy Pedestal all appear to be fine. My theory is that whatever I had with me when I went through the final portal, died, went creative, teleported, or a combination thereof became this way.

## Expected Behavior
No matter what I do, Abyssalcraft items I have knowledge of I continue to have knowledge of for the rest of that map.

## Possible Solution
Heck if I know. May not be solvable, depending on whether teleporting using JourneyMap or creative mode had an effect on it. Also may be hard or impossible to reproduce.

## Steps to Reproduce (for bugs)

I don't know for sure how to reproduce it, but I'll list here all the things I did in order. Some (or most) may be unnecessary to reproduce the problem.
1. Progress through Abyssalcraft and the rest of the pack as normal, unlocking the names of the coralium plagued flesh and the shadow gem items
2. Acquire the ability to use Journey Map
3. Find a Stronghold
4. Open the Portal
5. Place a waypoint on top of the portal so that if you teleport there using Journey Map it instantly spawns you into the End.
6. Use the portal as normal.
7. Kill a few abyssal zombies to get some coralium flesh and maybe a shadow gem fragment or two
8. Make a new waypoint in the End on a safe platform
9. Get knocked into the void by the dragon and die (the jerk)
10. Run all the way back and use the portal like normal again
11. Try to find your "grave" and fail
12. Die again
13. Start a LAN session with cheating enabled
14. Teleport to the waypoint of the ender portal using JM
15. Once in the End, enable creative mode
16. Fly to the death waypoint and continue to fly downward into the void, taking damage
17. Die from being in the death plane
18. Teleport to the ender portal waypoint
19. Run into the void again trying to find your corpse
20. Accidentally stop flying and die again
21. Teleport to the ender portal
22. Panic, thinking your items are gone forever
22. Finally find and grab your grave items
23. Fly to a safe space and disable creative mode
24. Get knocked 100ft by the dragon and die from falling
25. Teleport to the safe spot waypoint inside the end directly
26. Dig yourself into walls and a hole to keep from getting flung
27. Make a new end waypoint in your hole
28. Die to the dragon's magic breath because you sat in a hole
29. Finally give in and build a Railgun
30. Teleport to the hole waypoint and immediately die to the magic cloud that's still there
31. Teleport to the safe spot waypoint, wait for the magic to go away, grab your stuff, and finally start fighting the dragon
32. Kill many many zombies to get their flesh and shadow gems
33. Finally kill the dragon after taking way too long
34. Grab the dragon egg
35. Use the portal home
36. Teleport to the safe spot waypoint again to try and find some choral fruit
37. Fail to find any (didn't know about the whole outer islands thing yet) and use the portal home one last time
38. Notice that the plagued flesh and shadow gems are in gibberish again

## Context
Not sure yet, haven't tried to use the items. Hopefully I can still progress through Abyssalcraft or at least that I can fix it somehow.

## Logs

* Client/Server Log: https://gist.github.com/dalsio/4afd41c3d1440254168aa70ffff5f923

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0.171
* Launcher Used: Twitch Launcher, modified to use the latest Java

* Memory Allocated: 4gb

* Server/LAN/Single Player: Single Player/LAN
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by justinrusso** [comment]
This is fixed in 3.0.7. https://minecraft.curseforge.com/projects/sevtech-ages/files/2560173

**Comment by dalsio** [comment]
Sorry, second time I did that, checked github but realize to check the 0.7 patch notes as well. Will check them in the future before posting.
