### ISSUE TITLE
String recipe not working in 3.0.7? (Learned this is a server specific issue, close pls)

### ISSUE THREAD

**Issue by kungfunick123** [DarkPacks/SevTech-Ages#2297]
## Issue / Bug
Creating string using fleece next to a workblade (specifically flint in my case) isn't working even when having JEI move the items into place. I have tested this in my own inventory grid, a bench, and had another person test it.

## Expected Behavior
JEI moves the items into place and the string doesn't show up in the completed area of the crafting bench.

## Steps to Reproduce (for bugs)

1. Put fleece and a workblade next to each other in any crafting area

## Context
Trying to create string to progress through the ages but I can't because I dont have cotton, so I use fleece to get it.
## Context
Trying to create string to progress through the ages but I can't because I dont have cotton, so I use fleece to get it.

## Client Information
* Modpack Version: 3.0.7
* Java Version: 1.8.0_25
* Launcher Used: Twitch
* Memory Allocated: 5.8GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Tahakk** [comment]
You know that you can close your own issues?

**Comment by kungfunick123** [comment]
Oh I didnt see it lol

**Comment by kungfunick123** [comment]
Oh I didnt see it lol
