### ISSUE TITLE
Ironberry Juice Remains unobtainable (3.0.7)

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [DarkPacks/SevTech-Ages#2298]
## Issue / Bug
Ironberry juice is created from crushing ironberries from rustic in the crushing tub. After loading a new world in creative and giving myself the necessary advancements to hold them/use them, I placed down a crushing tub with a stack of ironberries. Nothing happens when you jump on them. Referencing https://github.com/DarkPacks/SevTech-Ages/issues/1618 issue 1618 this was supposedly fixed. There are no recipes for ironberry juice, and as such, ironberry wine. 

## Expected Behavior
Ironberries should be crushed when the player or another entity jumps on the crushing tub. 

## Possible Solution
Reenable ironberry juice/ironberry wine, and disable the tiny pile of iron dust, the reason this juice was disabled in the first place. 

## Steps to Reproduce (for bugs)
Place crushing tub.
Add ironberries.
Jump on tub.
Berries remain, no juice.

## Context
Frustration and disappointment is how its effecting me. 

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0.171
* Launcher Used: Multimc

* Memory Allocated: 5.5GB?
* Server/LAN/Single Player: Single player
* Resourcepack Enabled?: no 
* Optifine Installed?: no

I was looking forward to this update. I am **disappointed** at present. Please fix. 
Please and thank you.

**Comment by artdude543** [comment]
This one is my bad; removed the wrong script line. (Was done at 3am in the morning >.>) will be fixed in 3.0.8 whenever that lands.

Also being _disappointed_ is kinda silly considering it's a minor issue.

**Comment by ZephyrWindSpirit** [comment]
True, I did overreact a bit for that. 
For curiosity's sake, what script line is it so I can fix my own client for single player until 3.0.8 lands?
