### ISSUE TITLE
bit defender anti virus flagging server files

### ISSUE THREAD

**Issue by Yawb120** [DarkPacks/SevTech-Ages#2303]
Bit defender and a few other AV's are now flagging the forge installer jar file for the server files 3.0.6 + 3.0.7 from https://minecraft.curseforge.com/projects/sevtech-ages/files

The file it doesn't seem to like this file specifically.
"GameData$RecipeCallbacks$DummyRecipe.class". 

The file is present in a few of the server .jar's and gets flagged as "Java.Trojan.GenericGB.24424"

https://www.virustotal.com/#/file/cb8cb52de9afefc67df7c2b3d63301cea7774464c8dc718f3a491f045f5100c2/detection

I downloaded the latest server zip and its also flagging it too with the same "Java.Trojan.GenericGB.24424".  I have posted it to Bit Defender's false positives so hopefully its resolved eventually, just thought i should let you know.
 

Thanks,  

 Greg

**Comment by artdude543** [comment]
This is fine and can be safely ignored. Curse check all files being uploaded to the platform, and I did tests with the upload beforehand. This seems to be a false positive. But nothing to worry about.
