### ISSUE TITLE
Gravel in a filtered hopper no longer produces sand (3.0.7)

### ISSUE THREAD

**Issue by DigitalDiatom** [DarkPacks/SevTech-Ages#2305]
Testing on a clean install of 3.0.7
 
## Issue / Bug
Gravel in a filtered hopper no longer provides sand.  Only flint is produced.  The recipe is still listed in JEI as producing sand.  Nothing listed in change log as to this being a desired change.

## Expected Behavior
Dropped a stack of gravel into a powered filtered hopper, expected to get some sand produced.

## Possible Solution
Unsure of a solution

## Steps to Reproduce (for bugs)
1.  Power a filtered hopper (with correct filter)
2.  Drop gravel into it.

## Context
Issue appear immediately upon upgrading to 3.0.7.  I performed a clean install as well to verify it still did not work there.  Bug is present in a clean install.

## Logs
* Client/Server Log:  https://pastebin.com/Hj28Tr01
* Crash Log:  No crash

## Client Information
* Modpack Version: 3.0.7
* Java Version: version 8 update 171
* Launcher Used: Twitch
* Memory Allocated: 6 gigs
* Resourcepack Enabled?:  Yes sortex
* Optifine Installed?:  No

**Comment by MrDj200** [comment]
we have the same problem. Any solutions already?

**Comment by artdude543** [comment]
Fixed in 3.0.8 

![image](https://user-images.githubusercontent.com/1885466/40873884-46123526-6660-11e8-93f8-2d173005589a.png)
