### ISSUE TITLE
I am hosting a sevtech atlauncher more errors than words in english dictionary. 65k

### ISSUE THREAD

**Issue by antoniobradiano** [DarkPacks/SevTech-Ages#2306]
I use biscuithost they looking into it. since its a new beast. any ideas why it crashes on start up. with no plugin?  If I post log then I have to post in quarterly. cause too damn much.  Yea think twice on this pacj\k

**Comment by kragnoth** [comment]
Atlauncher has issues with the newest version of forge.  They are currently working on a fix as of 8pm est yesterday last I heard from Darkosto.  maybe the source of part of your issues?

**Comment by artdude543** [comment]
ATLauncher was updated which fixes the crashing. Re-install the entire pack.
