### ISSUE TITLE
8 Wool + Dye powder recipe = 1 dyed wool

### ISSUE THREAD

**Issue by Stifling-Bossness** [DarkPacks/SevTech-Ages#2307]
## Issue / Bug
The 8 wool + 1 dye powder only gives 1 wool.
https://imgur.com/a/fho7fI3

## Expected Behavior
To give 8 dyed wool, or to give 7 undyed wool back.

## Possible Solution
Give 7 more wool in the recipe, or maybe have one of the modular machines provide a higher efficiency, the loom maybe?

## Steps to Reproduce (for bugs)
1. Get 8 wool and 1 dye powder.
2. Craft them with 8 wool in a hollow square and fill the hole with a dye powder.
3. Get 1 wool from the recipe.

## Context
I'm making some oxygen tanks from Galacticraft, and I wanted to have a colored oxygen tank, so I dyed the 8 wool thinking it would be enough, but it only gave me 1 wool so I'm sad now :(

## Logs
* Client/Server Log: https://gist.github.com/Stifling-Bossness/fc8741176811636cbade3933b1e412ab

## Client Information
* Modpack Version: 3.0.7
* Java Version: 1.8.172
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Yes, 32x Faithful Modded Edition
* Optifine Installed?: No

**Comment by justinrusso** [comment]
Ahh.. woops! 👎
