### ISSUE TITLE
3.0.7 Removing Chalice from Age2 (likely unintentionally) make astral sorcery a lot more tedious 

### ISSUE THREAD

**Issue by LordHellscream** [DarkPacks/SevTech-Ages#2309]
My understanding is that the chalice was removed because it create obsidian (which i still don't understand why it matters since there isn't anything you can do with it in Age2)

However with the latest change this have other impacts, none of this change the actually make things impossible to do just a hell lot more tedious, so I suspect this is not intented?
1. Can't get aquamarine shale anymore, this make acquiring aquamarine entirely rely on mining in the beneath, which, as much as i love this modpack, was the single most tedious thing to do. Especially consider the chalic is available late in astral progression.

2. Making infusion altar a PAIN to operate, I do not really care much about the starlight liquid it saves, but having to manually check every spot for missing liquid and refill it with barrel for every single piece of resonating gem is such a pain.

3. The cobble gen really encourage more building in Age2 in my opinion. Cobbles are nothing rare but having to mine them just for building (no game power impact) is like pouring cold water on my artistic fever, is that a good choice?

**Comment by JRiebling** [comment]
Just so you know, aquamarine shale has been disabled for a while now. So yes, annoying as it is in Age 2, the only way to get aquamarine is the beneath, which is intended in the pack.

The rest I rather agree with, though since there's no easy option in the config to disable obsidian generation (as there is with the aquamarine shale), I wouldn't expect it to change.

**Comment by artdude543** [comment]
This was intended for a few reasons. And won't change unless a config is made to help disabling recipes.
