### ISSUE TITLE
Mod installation 3.0.7

### ISSUE THREAD

**Issue by jj16240** [DarkPacks/SevTech-Ages#2310]
So i just updated and it seemed to have bugged and it now it only has 9 mods and i tried to reupdate many times and it wont fix idk how to fix it

**Comment by oLeXGamingTV** [comment]
I uninstalled SevTech and that seemed to fix the issue for me (make sure to backup everything).

**Comment by artdude543** [comment]
This is a twitch wide issue. A new install seems to get around the broken updater. Otherwise wait for twitch to fix the system.
