### ISSUE TITLE
Space suits need rediculous resources to craft

### ISSUE THREAD

**Issue by poxun1** [DarkPacks/SevTech-Ages#2313]
## Issue / Bug
Contrary to closed issue #680 "Extra Planets Space Suits Need New Recipes" space suit recipes are still 'nested' and require a lot of steps and resources to craft.  This is a significant problem when they last almost no time on Venus making it very expensive and near impossible to get to a boss and obtain a shield controller.

## Expected Behavior
Simplify and reduce the resource load needed to craft (tier 2 at least) space suits.

## Context
Having successfully  completed Mars dungeons and figured out I need to go to the asteroid belt to get Titanium it took me ages to figure out why i kept dieing almost as soon as I landed on Venus.    About half an hour later on google I realised I needed the shield controller but can see no way to get one without burning through a large number of tier 2 space suits that are complex to make and require significant resources.

The complete lack of Youtube videos of the pack beyond the Moon or Mars would suggest this is causing major issues but content makers are switching instead of working through it.

* Modpack Version: 3.0.7
* Java Version: 8.131`
* Launcher Used: Twitch

**Comment by MJRLegends** [comment]
Do note you can do the whole Tier 1 - 10 planets with just Tier 1 Space Suit your not required to upgrade the suit unless you want more protection(Gain Radiation slower) which i believe it turned off so theres really no need for you to be upgrading in that case

**Comment by artdude543** [comment]
Recipes are intended as we changed them in the pack. And as stated above you _don't have_ to upgrade it.
