### ISSUE TITLE
Excavate Modifier not craftable

### ISSUE THREAD

**Issue by xSkyJay** [DarkPacks/SevTech-Ages#2314]
## Issue / Bug
The Excavate Modifier does not seem to be craftable

## Possible Solution
Tried relogging, using different mazestone types and using vanilla/modded crafting tables. None solved the problem.

## Steps to Reproduce (for bugs)
![c3e486a7acecbc6255e2887df45c67b4](https://user-images.githubusercontent.com/15221980/39854297-233caa22-53f5-11e8-87d3-781fad960a9b.png)
![eb2246268a632e4dc4d13e82ea2f7322](https://user-images.githubusercontent.com/15221980/39854323-3e55db94-53f5-11e8-965d-ac41f731e7e4.gif)
![207823ead7ea9a190b0bb90e460df197](https://user-images.githubusercontent.com/15221980/39854326-3fa2965e-53f5-11e8-9e61-6cf1057d2368.gif)

## Client Information
* Modpack Version: 3.0.7
* Java Version: Java 8 - 171
* Launcher Used: MultiMC
* Memory Allocated: 12,288

**Comment by PsyberMind** [comment]
Check the Mazestone.. I seem to remember having a problem with this until I got the correct type of Mazestone..

**Comment by xSkyJay** [comment]
Initially tried all the mazestone, didn't seem to be the problem. The recipe uses oredict for the crystals and the mazestone so that shouldn't be an issue.

**Comment by ScaCoyote** [comment]
I tried with several types of mazestone and on both a crafting stations and vanilla table. JEI has no problem moving the items but there is no output for the recipe like shown in the gifs above. Also I used both rock crystals and celestial crystals. My game has nothing added or disabled and I launch the the pack with the twitch app using the Jar launcher. I run Java 8 version 171.
