### ISSUE TITLE
Digital Miner Mekanism no recipe 

### ISSUE THREAD

**Issue by ferrium42** [DarkPacks/SevTech-Ages#2316]
issue

 
## Issue / Bug
Age 5 i just wan´t to build a digital miner for the planet mining and i can´t find the recipe , i try another save to be sure he isn´t disabled and no and in the config he is enabled 

## Expected Behavior
in the version 3.0.6 the miner was craftable , i look in the changes and find nothing

## Possible Solution
Add the recipe 

## Steps to Reproduce (for bugs)
age 5 try to craft an digital miner from mekanism
1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version:
* Launcher Used: twitch

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by kragnoth** [comment]
They disabled it to make the extra planet stuff... more ... something.

**Comment by artdude543** [comment]
The machine is disabled for making as it's broken and it's not worth the hassle. It won't be making a return either.

**Comment by thiakil** [comment]
"broken" how?

**Comment by artdude543** [comment]
Broken as in not understanding the geolysis ore generation and another issue dark found. It was never meant to be enabled in the first place. So was mistaken left in.

**Comment by thiakil** [comment]
Pretty sure it works with geolosis ores...
