### ISSUE TITLE
60 Missing Entries in Save after upgrade from 3.0.6 to 3.0.7

### ISSUE THREAD

**Issue by dyingdemon** [DarkPacks/SevTech-Ages#2317]
## Issue

Upon booting up the server after updating to 3.0.6 (after following all instructions in the update text) i am greeted to the following:

```
[05:02:30] [Server thread/WARN] [FML]: Forge Mod Loader detected missing registry entries.

There are 60 missing entries in this save.
If you continue the missing entries will get removed.
A world backup will be automatically created in your saves directory.

Missing primal:recipes_hibachi:
    primal:hibachi_meat_wolf
Missing minecraft:blocks:
    extraplanets:basic_purifier
    extraplanets:basic_solar_evaporation_chamber
    extraplanets:potash
    extraplanets:basic_chemical_injector
    extraplanets:basic_smasher
    extraplanets:basic_decontamination_unit_fake_block
    extraplanets:basic_decontamination_unit
    industrialforegoing:water_resources_collector
    cyclicmagic:block_shears
    extraplanets:basic_decrystallizer
    extraplanets:basic_crystallizer
Missing minecraft:items:
    extraplanets:anti_radiation
    extraplanets:potash
    extraplanets:iodide_salt
    industrialforegoing:water_resources_collector
    extraplanets:potassium
    extraplanets:potash_shards
    extraplanets:basic_purifier
    buildcraftcore:fragile_fluid_shard
    tombmanygraves:grave_block
    cyclicmagic:block_shears
    extraplanets:basic_decrystallizer
    extraplanets:basic_crystallizer
    extraplanets:basic_solar_evaporation_chamber
    extraplanets:basic_chemical_injector
    extraplanets:potassium_iodide
    extraplanets:basic_smasher
    extraplanets:basic_decontamination_unit_fake_block
    extraplanets:basic_decontamination_unit
Missing minecraft:soundevents:
    cyclicmagic:warp
    cyclicmagic:byeaa
    primal:block_wood_full
    cyclicmagic:bass_echo
    primal:block_wood_lid
    primal:block_metal_gong_full
    cyclicmagic:bip
    cyclicmagic:spikes_in
    cyclicmagic:crackle
    cyclicmagic:dcoin
    primal:block_metal_gong_dull
    cyclicmagic:powerupscales
    cyclicmagic:firelaunch
    cyclicmagic:pew
    cyclicmagic:buzzp
    cyclicmagic:explosm
    cyclicmagic:laserbeanpew
    primal:block_metal_lid
    cyclicmagic:spikes_out
    primal:block_wood_dull
    cyclicmagic:goodlaunch
    cyclicmagic:magic_missile
Missing primal:recipes_cauldron:
    primal:cauldron_brine_fire
    primal:cauldron_brine_void
    primal:cauldron_tanned_pigman
    primal:cauldron_brine_halite
    primal:cauldron_lacquer_plank_vanilla
    primal:cauldron_muck_magmacream
    primal:cauldron_tanned_hide
    primal:cauldron_brine_netjry


Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.
```
 This was tested on both a upgraded and a fresh install, and only happens on a upgrade

## Expected Behavior
Server to boot straight up without needing manual intervention after update

## Possible Solution
Starting a fresh world (highly unwanted as loss of progress would be immense)

## Steps to Reproduce (for bugs)
1. download 3.0.7 files
2. install server fresh
3. transfer prestige and world folders over to fresh install
4. launch server using ServerStart.bat
5. wait till after everything is loaded and will appear at end before dimension loading

## Context
Trying to upgrade to 3.0.6 to 3.0.7 without the loss of prestige or progress that has been gained by both myself and the users of my server

## Logs
[Latest Launch Log](https://gist.github.com/dyingdemon/ef3e1d4a96a81debe46ee20ac3d40f57.js
)
## Client Information

* Modpack Version:3.0.7
* Java Version:1.8.0 161
* Launcher Used: Not relevant to issue but Jar launcher, launched through twitch client
* Memory Allocated: 8gigs
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes client side
* Optifine Installed?: Yes client side 

## Server Information
* Java Version: 8
* Operating System: Windows (however unknown for actual host as not listed in server specs)
* Hoster/Hosting Soultion:  Nitrado.net

((Should be noted that i always test the update on my local machine BEFORE i update the actual server. This issue is occurring on the local machine 
OS: Windows 10 64bit
Ram: 16gigs (8 dedicated to Client and 4 Dedicated to server by config/install file)
HDD space: 1tb main 2tb backup
Java version: 1.8.0 161
server launched via the ServerStart.bat command))

**Comment by Tahakk** [comment]
As it says:

> A world backup will be automatically created in your saves directory.

So go for it, and if something goes wrong you just load up backup. Easy

**Comment by justinrusso** [comment]
Just... click OK?
