### ISSUE TITLE
Menu Flashing

### ISSUE THREAD

**Issue by Kessah** [DarkPacks/SevTech-Ages#2321]
Just today, while streaming the pack, I noticed the reason my stream is lagging and what not is the menu keeps popping up while I'm just walking around.  Like Jei/Nei when I'm actually in the menu keeps refreshing/popping up.  Then after I get out of that the screen will flash between the esc menu and the jei menu.  None of this can I see in game, but through my stream it is visible.  It happened with the clean install as well.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
