### ISSUE TITLE
Unable to Cook Crucible in the Kiln.

### ISSUE THREAD

**Issue by power-spike** [DarkPacks/SevTech-Ages#2322]
Greetings, 

Just updated to Sevtech 3.0.7 - I have no additional mods installed at the moment.

I am currently on Age 4 - and attempting to make a crucible in the (stoked) Kiln so I can progress to make soulforge steel. 

However when I place the unfired crucible into the kiln, it does not cook, and just stays there.

I have left it there for several minutes and no change, it doesn't even show the cracking textures like other items do. 

The Kiln is still working - because I made a couple of urns for the filtered hopper using it.

**Comment by Nammor** [comment]
Desactivate the Hibachi under your kiln to cook the crucible, it's made in the normal Kiln, not the stoked one, they are 2 separate techniques.

**Comment by lendrick** [comment]
I was having the same issue, and I wanted to add a note here that it's showing up in JEI as a recipe for both the stoked and un-stoked kiln, but it only worked in an un-stoked kiln.

**Comment by artdude543** [comment]
It's an issue with BWM but it's known to try both types normally. We'll look at trying to sort this out soonish. But it's working for now I guess.
