### ISSUE TITLE
Not all mods are included in download

### ISSUE THREAD

**Issue by mastersantans** [DarkPacks/SevTech-Ages#2323]
As the title suggests, not all mods are included in both Twitch app install and CurseForge .zip download. I've attached pictures of both.
![bug1](https://user-images.githubusercontent.com/39163360/39876439-2c5efea6-5441-11e8-88ab-7b77458995fb.png)
![bug2](https://user-images.githubusercontent.com/39163360/39876440-2ca5ed98-5441-11e8-81d0-4cebc0cd438d.png)

**Comment by Battokage** [comment]
yeah same as me, you need to rollback to version 3.0.4 for now it seems

**Comment by mastersantans** [comment]
Cool. Thanks!
