### ISSUE TITLE
Tier 1 Space Suit cannot be charged (3.0.7)

### ISSUE THREAD

**Issue by Viba** [DarkPacks/SevTech-Ages#2324]
When crafted, the Tier 1 Space Suit has 0/31 250 RF and cannot be charged.
I've tried basically all available chargers from various mods and none can charge the suit.

As a result, if you take an arrow hit from a skeleton the whole suit gets destroyed immediately.

If you cheat in a charged Tier 1 Space Suit and take damage, it seems as if the charge would be depleted (the green bar shows), once you open your inventory and hover over an armor piece with your mouse it shows full charge and the green bar is removed.

In a previous version (watched on youtube) it appears the Space Suit doesn't have any RF charge.

Using version 3.0.7.

**Comment by poxun1** [comment]
Suits can be charged using the Galacticraft Energy Storage Module (and presumably the tier 2 version) only.  Other chargers/energy storage including wireless charging, batteries etc will not work.

Suit crafted in 3.0.6 shows a full RF charge in 3.0.7 after updating

**Comment by Viba** [comment]
Thank you, that seems to be working. Can close this.
