### ISSUE TITLE
Extra Planets "Module Manager" window opens any time you type H

### ISSUE THREAD

**Issue by poxun1** [DarkPacks/SevTech-Ages#2326]
## Issue / Bug
If you are wearing any of the Extra Planets spacesuit pieces and press H the Module Manager window always opens except if you are typing in chat.  If searching in TMI or any of the storage mod search windows for instance it will always close whatever inventory/GUI and open the Module Manager.
This is occurring 3.0.7 but not 3.0.6

## Expected Behavior
Module Manager to only open if there is no active GUI/Inventory already on screen when pressing H

## Possible Solution
Remap to a key/symbol that isn't normally typed in search boxes etc.  Unmapping the key totally won't work as you need to use the Module Manager to add upgrades to the suits.

## Steps to Reproduce (for bugs)
1. Wear any piece (or combination of pieces) of the Extra Planets spacesuit
2. Open any search/GUI such as inventory->TMI seearch
3. type an item name with an H in it such as "fish"

## Context
Very disruptive when using TMI, storage mods, item name filters (eg Pneumaticraft compression chamber interfaces) etc.

## Client Information

* Modpack Version: 3.0.7
* Java Version: jre1.8.0_161
* Launcher Used: Curse/Minecraft
* Memory Allocated: 7MB

**Comment by ChipmunkCraft** [comment]
You can change the keymap under "Options -> Controls -> Open Module Manager"

I set mine to semicolon personally.

**Comment by MJRLegends** [comment]
@justinrusso Updating to latest ExtraPlanets will fix this due to its already fixed a few updates ago
