### ISSUE TITLE
Grave destroyed by Shoggoth acid

### ISSUE THREAD

**Issue by Gameswithjohn** [DarkPacks/SevTech-Ages#2330]
Just had an issue when fighting my first Shoggoth in Age 1. I was killed by its acid and when I went to collect my grave the only thing around was the "mystery meat" floating in the river. I searched around, got the death list to check the Y cord. and nothing. I just found that the Shoggoth acid can destroy blocks so I'm guessing this is the cause of the missing grave.

I used the "/tmg_deathlist" command to see where my grave should be exactly with the particle effects, but there was nothing there other than the floating ball of light because of the list. I also turned on cheats to use the "/tmg_return [player] <timestamp>" command to get my items back (because of the missing grave), but this doesn't seem like the proper way to have to do this.

While I personally feel that the Shoggoth statue quest is a bit difficult for this stage in the advancements, because of how little you have to use yet and their strength/skills, this does seem like something that needs to be addressed. I'm not sure if there is a "block can't be broken" line in the TMG mod so that this cannot happen to others?

**Comment by Pikafrenzy** [comment]
Can confirm this happens in 3.0.7

**Comment by tcush35** [comment]
This just happened to me as well. Bit infuriating.

**Comment by 8bitgamer1972** [comment]
I'm in same boat as the rest of you, it just happened to me.

**Comment by choekstr** [comment]
same :(

**Comment by WorldWarHulk** [comment]
yeah Shoggoth needs a blacklist of what block it can destroy even by walking around, this can happen.

**Comment by N00bSkyw4lk3r** [comment]
Yeah this is definitly annoying. They are immune to any ranged attacks whilst puking out all dissolving acid Balls. Also the ratio is absolutely imba: It would take my darkstone axe (+9 Attack) like 15 hits to get rid of 1. They kill me in 3 wearing the toughest possible bronze armor. And this would be just 1. We need to lure 6 (!) of them out and kite them through all their sticky and damaging ichor. Just running does not work all that great when sticking in tar and getting 6 shots of achid when 3 are enough to kill.

I honestly don´t know how this worx, but would it possible to give the Block of a Gravestone the hardness of Bedrock? Then you do not have to file yet another black- and Whitelist but this one is just impenetrable except for the pickup command?
Kr,
a Noob.

**Comment by Gameswithjohn** [comment]
After my first run in with them and having to cheat in my stuff after the grave was melted I did it the "hard way" and mined out one of the lairs that glitched out not having any of them in it. This doesn't seem like the intended way to complete this mod. It isn't a bad mod, seems to have depth to it, but the combat aspect is far too difficult for that stage. 

I'm all for a challenge, but combat difficulty in Minecraft is not something easily done and in most cases isn't done well. It is either far too easy, is so difficult that you have to cheese it, or you simply rage quit. That simply isn't the way to make these packs. Its also why I don't play things like the "mad pack" ones where the mob difficulty is amped (never a fan of the "lets steal mobs from every other game" lack of creativity of Lycanites) but make the crafting far too simple, just to rush the game artificially?

**Comment by N00bSkyw4lk3r** [comment]
P.s.: I just cheesed it too. I snuck up the lair from behind and dug underneath it. There you can get a few hits on those beasts from below and back off to heal (they cannot grief their own stones :)). I did die a couple of times still but was able to get about 1 1/4 stack of flesh and some of the stone to craft quite a few of these statues. At some point they must have been trying to get me from outside the lair for there was an actual monolith statue tower thingy right in front of it afterwards. (Of course i snaged that too with ONLY 3 death in between).

I never want to go there again...

Kr,
a Noob

**Comment by MikeyIGN** [comment]
Same issue for me.  Unfortunately the command to return your goods back to you (which included 2 upgraded bags of gear) isn't working for me.

**Comment by choekstr** [comment]
You have to be OP in order to use the command if on a server or you have to enable cheats (open to lan) in order for it to work.

And just to review, its:
/tmg_restore <username> latest

**Comment by justinrusso** [comment]
We are moving to a new gravestone mod for 3.1.0. This should resolve issues. Please be sure to gather any graves in the world before updating, as the old gravestones will be deleted!
