### ISSUE TITLE
Improved backpacks able to be put in baubles slot, but not opened from there.

### ISSUE THREAD

**Issue by Gameswithjohn** [DarkPacks/SevTech-Ages#2332]
You are able to place the Improved Backpacks in the baubles chest slot, the tool tip even says "Bauble (body)", but you are not able to open it from there like you can if you are wearing it in the armor slot. Not sure if this is intentional or if it is a feature that is not working properly since there seems to be more than a few issues dealing with backpacks.

**Comment by scollenburg** [comment]
Fixed in IBp 1.2.0.3: https://github.com/DreenDex/ImprovedBackpacks-Issues/issues/3

... which is part of SevTech 3.0.8. This can be closed.
