### ISSUE TITLE
Arc Furnace Recipe for Bronze inconsistent with Smeltery

### ISSUE THREAD

**Issue by Serolar** [DarkPacks/SevTech-Ages#2334]
## Issue / Bug
The Arc Furnace should Yield 4 Bronze from 3 Copper Ingots and 1 Tin Dust

## Expected Behavior
Currently, the Bronze Recipe Yields 3 Bronze from the same ingredients

![2018-05-10_14 54 07](https://user-images.githubusercontent.com/16960400/39890976-0eb0a186-5462-11e8-91bd-db93ee24eeda.png)

## Possible Solution
Making the Bronze Recipe Consistent with the Smeltery makes both viable when they're available. Since the Smeltery requires Lava, and the Arc Furnace can "Kind of" run on renewable energy, the Arc Furnace is an Upgrade, Technically.

## Steps to Reproduce (for bugs)

1. Look up recipe for Bronze Ingot
2. Gather Resources to make Bronze.
3. Place proper resources in Arc Furnace, Tin Dust in Alloy section
4. Become sad at 3 Bronze Ingots

## Context
Seeing that the Bronze Arc Furnace Alloying Provides less than the Smeltery, well, it's counterproductive, I need more Batches to make the same result, so the method I've been doing(Ore-Doubling, then Melting the Ingots in the Smeltery, and casting the Bronze Result), is still the current way I plan to do it, for now.

## Client Information

* Modpack Version: 3.0.7
* Java Version:1.8_161
* Launcher Used:

* Memory Allocated: 6GB

* Server/LAN/Single Player: SinglePlayer
* Resourcepack Enabled?: None
* Optifine Installed?: No

**Comment by pjc21** [comment]
Also found this odd, I am assuming this was not intended (simple typo) and have modified the script so Arc Furnace yields 4 bronze ingots.

Script to modify - scripts\mod_integrations\immersive_engineering.zs
change line 149 
from
`ArcFurnace.addRecipe(metals.bronze.ingot.firstItem * 3, metals.copper.ingot * 3, slag, 100, 512, [metals.tin.dust]);`
to
`ArcFurnace.addRecipe(metals.bronze.ingot.firstItem * 4, metals.copper.ingot * 3, slag, 100, 512, [metals.tin.dust]);`
![2018-05-11_15 52 03](https://user-images.githubusercontent.com/4660190/39909212-266c4b26-5535-11e8-8915-a64a585acd5b.png)
