### ISSUE TITLE
Platinum Clusters have no recipe for the Immersive Engineering Crusher

### ISSUE THREAD

**Issue by dalsio** [DarkPacks/SevTech-Ages#2335]
## Issue / Bug
The Immersive Engineering crusher does not have a recipe accepting platinum clusters nor any form of platinum ore. There is an entry for the Crusher outputting platinum dust, but there is no input item (the space is blank).

## Expected Behavior
Platinum clusters can either be ground in the IE crusher, or the blank crusher recipe is removed.

## Possible Solution
Probably a missed line of config code.

## Steps to Reproduce (for bugs)

1. Look at JEI recipes
OR
1. Get platinum clusters
2. Build an Immersive Engineering Crusher
3. Attempt to put the clusters into the Crusher

## Context
Can't refine platinum using my shiny new crusher/arc furnace setup. Sad.

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0.171
* Launcher Used: Twitch Launcher, modified to use the latest Java

* Memory Allocated: 4gb

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by justinrusso** [comment]
DarkPacks/SevTech-Ages#2315
