### ISSUE TITLE
Not all mods are included in download

### ISSUE THREAD

**Issue by NeverSalty** [DarkPacks/SevTech-Ages#2336]
![unbenannt1](https://user-images.githubusercontent.com/39171025/39891234-4fd46022-549d-11e8-9488-5eeccdad8325.PNG)
same in ATM3 and all other modpacks downgrade to 3.0.6 or 0.4 not worked at all

**Comment by redfoxhint** [comment]
i have the same problem..i really want to play :(((

**Comment by Mad-Zone** [comment]
Same issue. Replicates even when utilizing older versions.

**Comment by justinrusso** [comment]
This is not a pack issue, this is a launcher issue.
