### ISSUE TITLE
Inductive Logistics Fluid Pipes do not extract fluids from Immersive Petroleum distillation towers

### ISSUE THREAD

**Issue by BenB196** [DarkPacks/SevTech-Ages#2340]
## Issue / Bug

I attached a fluid extraction pipe to an Immersive Engineering distillation tower and a Fluid inject pipe (with a filter, taking off the filter did not fix it) to the tank. With an advanced universal pipe connecting them.

<img width="1127" alt="pipe_setup" src="https://user-images.githubusercontent.com/8277432/39894522-1e310ce6-5475-11e8-9666-7a906af4cdb1.png">

The fluids in the tower did not go anywhere, and the pipes would not move any fluid.

## Expected Behavior

The pipes should extract and transport the fluids to the tank.

## Possible Solution

This may be an issue with the mod inductive logistics as it was just recently overhauled.  I have opened a report on their end as well

https://github.com/CD4017BE/InductiveLogistics/issues/23

## Steps to Reproduce (for bugs)

1. Distillation Tower
2. Advanced Universal Pipe w/ Fluid extraction pipe on the end attached to the tower & Fluid insertion pipe on end attached to tank
3. Fluids in tower will stay in tower and not move

## Context

I am trying to find a way to route fluids fast, and am unable to do so as the only real other fluid router is the IE fluid router.

## Logs
N/A

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.171
* Launcher Used: Twitch

* Memory Allocated: 8GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes
* Optifine Installed?: No

## Server Information
* Java Version: 1.8.171
* Operating System: Windows 2012 R2
* Hoster/Hosting Soultion: N/A
* Sponge (Non-Vanilla Forge) Server?: No

**Comment by Fatthunder** [comment]
With the latest changes, it appears that you need to now use a fluid destination pipe, instead of a fluid inject pipe for inserting fluids.
