### ISSUE TITLE
freezes every 5 seconds

### ISSUE THREAD

**Issue by TeKett** [DarkPacks/SevTech-Ages#2343]
the ingame memory count (f3) never reaches over 3000, every time it reaches 2800+mb the game freezes for .5 to 2 second and memory usage drops to 2000-2200mb and then crawls back to 2800+ in about 5 seconds and then repeats. however in taskmanager it does just fine of staying on ~4500 mb

other then trying to mess with the runtime parameters, which i did after i first noticed the freezing, i have not touched any settings, i just downloaded minecraft and the mod via twitch app, logged in and then launched the game, made a world and noticed the freezing.

vanilla runs flawlessly.

Operating System: Windows 10 Home 64-bit (10.0, Build 16299)
Processor: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 CPUs), ~2.6GHz
Memory: 16384MB RAM
Card name: NVIDIA GeForce GTX 970M
Display Memory: 11162 MB
Dedicated Memory: 3032 MB
Shared Memory: 8130 MB
Java version: 10.1 64bit and 8.something 64bit

**Comment by ChipmunkCraft** [comment]
-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

Use these at your own risk but UseG1GC seems to be the best method for garbage collection for me at least.
That freezing is caused by the garbage collector stopping to clear garbage

**Comment by artdude543** [comment]
You need to mess with Java args but the one mentioned above is okay. But you can tweak as needed for your system. But the pack will never fix stuttering as that's the user side of things which we don't control.

**Comment by TeKett** [comment]
turns out the game is using its own version of java, 1.8.0_25 and java 9 or 10 makes it crash. also every time i launch minecraft via twitch app, the launch options keeps resetting. had 1.8.0_144 that dident show up in the java control panel, used that one and its all good now altho im only getting 50-60 fps on 8 chunks and lowest settings, its now playable but still.
