### ISSUE TITLE
Game Crashes When Joining Server or Starting a World

### ISSUE THREAD

**Issue by ABCEasyAs123** [DarkPacks/SevTech-Ages#2344]
## Issue / Bug

Anytime I attempt to join a server or open a world in single player, the game will load in the world for a few seconds and then crash to desktop. 

## Expected Behavior

World should load in/Client should be able to join server

## Possible Solution

N/A
## Steps to Reproduce (for bugs)

1. Load world/ Join server
2. Wait

## Context

I can't log in to a private server while others can using the same launcher and settings.

## Logs

* Client/Server Log: https://gist.github.com/ABCEasyAs123/99d663e1485b0e5d06de74d352b09aae
* Crash Log: 

## Client Information

* Modpack Version: 3.0.7
* Java Version:1.80_171
* Launcher Used: Twitch

* Memory Allocated: 4GB

* Server/LAN/Single Player: Single Player and Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by DarthSpaceLord** [comment]
I have this same issue, I tried to open a world from 3.0.6 in 3.0.7 and all it did was keep crashing. I luckily made a backup before trying 3.0.7.

**Comment by ABCEasyAs123** [comment]
Therein lies part of the problem. It''s not generating a crash report either. However, now that 3.0.7 is uploaded to ATLauncher which is what I was originally using, I no longer crash. So, that would lead me to believe that the problem lies with the Twitch launcher

**Comment by artdude543** [comment]
That leads me to believe your Twitch install was missing files which is a current issue with the launcher. But unless you have the crash files please don't name an issue as "crash" when there is no evidence to back that up. As your client log was normal and had nothing to show that a crash occurred.

But nonetheless glad to hear you have it working now.
