### ISSUE TITLE
IE Crusher and MM Mill less effective at making hemp fiber than the mill stone

### ISSUE THREAD

**Issue by Stifling-Bossness** [DarkPacks/SevTech-Ages#2345]
## Issue / Bug
The IE Crusher and MM Industrial Mill give less hemp fiber per hemp (2) than the BWM Mill Stone (3)
https://imgur.com/a/d29w0Qk

## Expected Behavior
For the Crusher and Industrial Mill to give the same or more hemp fiber per hemp than the old Mill Stone.

## Possible Solution
Raise the hemp fiber per hemp by 1 for the Crusher and Industrial Mill, or reduce by 1 for the Mill Stone.

## Steps to Reproduce (for bugs)
1. Crush Hemp in IE Crusher.
2. Mill Hemp in MM Industrial Mill
3. Mill Hemp in BWM Mill Stone.
4. Compare amounts given.

## Context
It seems very odd that a primitive Mill Stone would be more effective at grinding hemp than other more advanced methods. This also seems to be exclusive to hemp, as other recipes offer the same amounts.

## Logs
* Client/Server Log: https://gist.github.com/Stifling-Bossness/a7832a9b44fed66acf22c12150478403

## Client Information
* Modpack Version: 3.0.7
* Java Version: 1.8.172
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Yes, 32x Faithful Modded Edition
* Optifine Installed?: No

**Comment by artdude543** [comment]
This was intentional due to manual labour being needed at early stages in the game. And automation is a pain as items spit out so more work to collect it. But the recipe values are intentional. To make it feel less grindy at the start.
