### ISSUE TITLE
Refined Storage, Multipart and Chisels & Bits

### ISSUE THREAD

**Issue by UncertifiedDevice** [DarkPacks/SevTech-Ages#2346]
## Issue / Bug
Refined storage doesn't seem to work with mcmultipart. I was trying to use chisels and bits to cover up my RS cables on a server but I couldn't get it to work. I tried placing bits as 1/4 blocks, lines etc. but I simply couldn't place bits around my cables. I tried doing this in singleplayer but I still couldn't place bits on the cable. Multipart seems to be installed and support is enabled in the chisels & bits config so I'm not sure why this isn't working.

## Expected Behavior
I should be able to place bits in the same block as my cables so long as the bits are not in the way of any connections.

## Steps to Reproduce (for bugs)
https://www.dropbox.com/s/148g9ubd1afv04u/2018-05-10%2023-48-46.flv?dl=0

## Context
I can't cover my RS cables :(

## Client Information
* Modpack Version: 3.0.7
* Java Version: jre1.8.0_162
* Launcher Used: MultiMC, imported from twitch
* Memory Allocated: 10G
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes
* Optifine Installed?: Yes

## Server Information
* Java Version: 1.8.0_171-b11
* Operating System: Ubuntu 16.04.4 LTS
* Hoster/Hosting Soultion: OVH
* Sponge (Non-Vanilla Forge) Server?: Forge

**Comment by justinrusso** [comment]
Sounds directly related to Refined Storage... Please submit a request for it https://github.com/raoulvdberge/refinedstorage/issues

**Comment by justinrusso** [comment]
This is no longer possible. The latest update (1.6) of Refined Storage removes the integration for MCMultiPart.
