### ISSUE TITLE
Hello? Extra Planets Wasn't Updated

### ISSUE THREAD

**Issue by FaustyTheRager** [DarkPacks/SevTech-Ages#2347]
## Issue / Bug
Extra Planets had updates that fixed issues

## Expected Behavior
I expected you all to update this.

## Possible Solution
Update

## Steps to Reproduce (for bugs)
1. Ignore updated version
2. Update SevTech

## Context
I can't install certain modules

## Client Information
* Modpack Version: 3.0.7
* Java Version: .18.0_u171
* Launcher Used: Java
* Memory Allocated: 12 GB
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## I am sorry, I understand you guys are working hard :)

**Comment by artdude543** [comment]
The mod can't be updated due to issues with crashing and config issues. This will be looked at again later on the next major.
