### ISSUE TITLE
Player totaly flips out whenever I walk on a new block

### ISSUE THREAD

**Issue by mrpeeps** [DarkPacks/SevTech-Ages#2351]
So. Recently got the modpack with ATlauncher, and it worked fine when I first opened it. On the second time, though, whenever I step onto a new block, the player will completly flip out

I dont really know what the steps to reproduce are, as it happened randomly. 

This bug makes the game completly impossible.

PS sorry if this is formatted wrong, first time posting on github

**Comment by justinrusso** [comment]
Try disabling the mobendz mod.
