### ISSUE TITLE
Mk3 OreMatic Missing Structure When Structure is Correct

### ISSUE THREAD

**Issue by kpress15** [DarkPacks/SevTech-Ages#2352]
# Issue / Bug
I am not able to create an orematic machine of mk 2 or higher. I made all the materials and configured them exactly how the multiblock image says to and nothing. I am 99.99% sure that I have everything in the right position. I checked it over and re-constructed the machine multiple times.

# Expected Behavior
Structure to form when all of the correct blocks are in place.

# Context
I just finished making everything I needed to create the mk3 orematic from modular machinery. When I placed the blocks together it still said missing structure. After a few tries of reconstructing the whole thing, I went to see if the mk2 would work and again it said missing structure. I tried to make a mk1 after that and it worked. I don't know if it has something to do with the abyssalcraft machines in the multiblock since those are only in the 2 and 3. 

# Client Information
Modpack Version: 3.0.7
Java Version: Latest
Launcher Used: Jar Launcher
Memory Allocated: 8GB
Server/LAN/Single Player: Single PLayer
Resourcepack Enabled?: None
Optifine Installed?: Yes

Here's a few screenshots from all angles of the machine https://imgur.com/a/tSbu0J8

**Comment by artdude543** [comment]
The rotation on the middle blocks matter.

When you are using the projector the overlay will be flicking on the ones, not in the correct rotation. However, this will be changed in the next update to allow any rotation. But they do build when the rotation is correct.
