### ISSUE TITLE
Was the ingot to dust/grit recipe in the IE crusher removed?

### ISSUE THREAD

**Issue by dalsio** [DarkPacks/SevTech-Ages#2353]
## Issue / Bug
I'm worried I missed a changelog or issue or milestone somewhere again that states this but I can't find it anywhere. I can no longer put ingots into the crusher to get their dusts as I did in 3.0.6, meaning that if I process all dusts in the arc furnace and suddenly need an alloy, I have to use the Tinker's smeltery instead. Is this an intended effect?

## Expected Behavior
Ingots placed into the IE Crusher grind to their dust forms.

## Possible Solution
Probably a line in a config or script somewhere?

## Steps to Reproduce (for bugs)
1. Check JEI for missing recipes
OR
1. Make an IE Crusher
2. Get metal ingots
3. Put the ingots into the crusher

## Context
I have to keep a backlog of dusts I might need to alloy with which isn't really a big deal I suppose, but it de-incentivises the scenario of shoving a bunch of ores into an input chest and having them all processed into ingots automatically.

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0.171
* Launcher Used: Twitch launcher, modified to use the latest version of Java

* Memory Allocated: 4gb

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by justinrusso** [comment]
Shouldnt have been removed. Will look into it, it may have been removed on accident with a bunch of processing re-working.

**Comment by dalsio** [comment]
I finally did it right! \o/

**Comment by PsyberMind** [comment]
From what I can see/have experienced, all ingot -> dust was taken out - So far I've tested the IE Crusher, AE2 Quartz Grindstone, AS Grindstone, and the Mekanism Crusher.  I can only assume this was to prevent doubling from ingots, but please think of the storage children when I now have to keep a couple stacks of dust as well as the ingots on hand :P 

With my limited amount of programming skills (I am still envious of what you guys do,) I came across a couple script lines that do seem to have disabled Ingot->dust.. I may play around with it (Locally on a separate instance of course) and see if I can fix it on my end, but of course I'll leave the real changes up to the pros.. at the least it's decent practice for me
