### ISSUE TITLE
3.0.7 contains only 6 mods

### ISSUE THREAD

**Issue by maettle** [DarkPacks/SevTech-Ages#2355]
## Issue / Bug
- v3.0.7 contains only this 6 mods (zip or via twitch App):
-a----       06.04.2018     22:48          55622 ChickenASM-1.12-1.0.2.7.jar
-a----       07.05.2018     05:34        3845741 Galacticraft-Planets-1.12.2-4.0.1.176.jar
-a----       07.05.2018     05:34       10356002 GalacticraftCore-1.12.2-4.0.1.176.jar
-a----       07.05.2018     05:35          52597 MicdoodleCore-1.12.2-4.0.1.176.jar
-a----       12.03.2018     22:35          93531 Nutrition-1.12.2-3.0.0.jar
-a----       23.03.2018     22:43         380607 SevTweaksNPC-0.0.3.jar

## Expected Behavior
- like 3.0.6, contains all mods

## Possible Solution
- include all mods?

## Steps to Reproduce (for bugs)
1. download via curseforge (zip) or twitch app
2. start mod

## Logs
none needed

## Client Information
* Modpack Version: 3.0.7
* Java Version: 8-171
* Launcher Used: twitch app
* Memory Allocated: 8GB
* Server/LAN/Single Player: SP
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by nebularazer** [comment]
This is an issue with the twitch app. Darkosto mentioned this in his stream yesterday.
This has to be fixed by twich.

**Comment by Boomflex** [comment]
https://twitter.com/CurseForge/status/994346258163687425

**Comment by Mad-Zone** [comment]
In his stream from last night (10MAY2018) go to 00:42:23 and you can see him talk about it a little bit. Until Twitch fixes this issue, I'll be using MultiMC vs not playing.

**Comment by artdude543** [comment]
See the linked tweet.

**Comment by tapegreen** [comment]
their is a temporary fix. Go to browse all modpacks, then find the sevtech modpack, instead of clicking play, click the arrow next to it, then click install. From their you need to go into the old modpack and grab all the save files and transplant them into the new modpack.

**Comment by Boomflex** [comment]
Not a temporary fix, just luck of the draw.
