### ISSUE TITLE
Optifine/shaders

### ISSUE THREAD

**Issue by Spelhajen** [DarkPacks/SevTech-Ages#2357]
I can't seem to launch the modpack with optifine. i want optifine for shaders and i know its possible just not how to do it, 
heres the problem

11/5/2018 12:46:51 PM] [main/ERROR] [FML]: The minecraft jar 
file:/C:/Users/02asa/Desktop/ATLauncher/Instances/SevTechAges/bin/minecraft.jar!/net/minecraft/client/ClientBrandRetriever.class appears to be corrupt! There has been CRITICAL TAMPERING WITH MINECRAFT, it is highly unlikely minecraft will work! STOP NOW, get a clean copy and try again!
[11/5/2018 12:46:51 PM] [main/ERROR] [FML]: FML has been ordered to ignore the invalid or missing minecraft certificate. This is very likely to cause a problem!
[11/5/2018 12:46:51 PM] [main/ERROR] [FML]: Technical information: ClientBrandRetriever was at jar:file:/C:/Users/02asa/Desktop/ATLauncher/Instances/SevTechAges/bin/minecraft.jar!/net/minecraft/client/ClientBrandRetriever.class, there were 0 certificates for it

**Comment by PsyberMind** [comment]
Does the pack launch without the Optifine jarfile? If so, you may want  to try re-downloading Optifine as the DL may have been corrupted.

**Comment by artdude543** [comment]
Either you installed Optifine the old way (via the Jar) or you have a broken Jar download. As Optifine goes in the mod folder now (and has done for ages) but you have a corrupt vanilla jar file. This needs re-downloading (delete the bin folder and let the launcher re-download it)

**Comment by Spelhajen** [comment]
still doesnt work
reinstalled the pack and tried with all optifineversions for 1.12.2

**Comment by Spelhajen** [comment]
must be something really easy i'm missing but i'm stumped anyway
