### ISSUE TITLE
Galacticraft Map causing game to crash

### ISSUE THREAD

**Issue by Deagon64** [DarkPacks/SevTech-Ages#2359]
## Issue / Bug

On single and multiplayer every time I try to open the Galacticraft map it forces my game closed with the the error 

The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Do not check permissions on client side! Node: galacticraft.station.create

Here is a copy of the Crash Report: 

https://pastebin.com/6tumdWzM

## Client Information

* Modpack Version: 3.0.7
* Java Version: 8 update 161
* Launcher Used: Twitch
* Memory Allocated: 8Gb

**Comment by justinrusso** [comment]
We dont include FTB Utilities in the pack. This is not our issue.

Please report it directly to the mod maker.
