### ISSUE TITLE
Scannables Scanner missing config for Assorted Quartz

### ISSUE THREAD

**Issue by ChylerBH** [DarkPacks/SevTech-Ages#2360]
## Issue / Bug
Scannables Scanner does not recognise Assorted Quartz ores

## Expected Behavior
I would expect the Scanner to be able to detect and highlight Assorted Quartz as it does the other ores

## Possible Solution
Add Assorted Quartz to the Scannables config

## Steps to Reproduce (for bugs)

1.  Find an Assorted Quartz ore block and try to scan for it
2.  

## Context

Quality of Life change.  If the other ores have been added, it would be nice if this was too

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_171
* Launcher Used: Twitch

* Memory Allocated: 8 Gb

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Soartex
* Optifine Installed?: No

## Server Information
* Java Version: 1.8.0_171
* Operating System: Windows 10
* Hoster/Hosting Soultion: Private Server
* Sponge (Non-Vanilla Forge) Server?: 

* Additional Content Installed?: Aroma Core / Backup

**Comment by justinrusso** [comment]
This issue is fixed in an update to Scannable, but we are currently waiting for an important fix to be done before it can be added to the pack. https://github.com/MightyPirates/Scannable/issues/43
