### ISSUE TITLE
Field Manual can't be shift-clicked into Bibliocraft bookcase despite update.

### ISSUE THREAD

**Issue by EhGneissGuy** [DarkPacks/SevTech-Ages#2363]
## Issue / Bug

Geolysis Field Manual cannot be shift-clicked into bibliocraft bookcase.

## Expected Behavior

Minor issue, don't know why this book wouldn't shift-click in while others can.

## Possible Solution

Add to the whitelist for books.
## Steps to Reproduce (for bugs)

1. Try to put field manual into book case.

## Context

Little to no effect, initially thought the bookcase was bugged. Was trying to quickly store the book.

## Logs

* Client/Server Log: https://gist.github.com/EhGneissGuy/a93aaddf29a5f24ed054a710f72f0466
* Crash Log: N/A

## Client Information

* Modpack Version: 3.0.7
* Java Version: 8.171
* Launcher Used: Twitch

* Memory Allocated: 6.4 GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes
* Optifine Installed?: Yes

## Server Information
* Java Version: N/A
* Operating System: N/A
* Hoster/Hosting Soultion: Cubedhost 4GB
* Sponge (Non-Vanilla Forge) Server?: N/A

* Additional Content Installed?: Yes [Akashic Tome, Morph-o-Tool, Test Dummy Mod [MmmMmmMmmMmm])

**Comment by justinrusso** [comment]
Was there an issue on this already?
