### ISSUE TITLE
Uncrafting Table doesn't work.

### ISSUE THREAD

**Issue by EhGneissGuy** [DarkPacks/SevTech-Ages#2364]
## Issue / Bug

Trying to use items in the uncrafting table from Twilight Forest yields nothing. It doesn't ask for XP, it doesn't give ghost images or items you can take.
![image](https://user-images.githubusercontent.com/17113297/39939017-de0b9966-5522-11e8-9a2c-e3f8dd0a01c8.png)
Image is without use of Resource pack, general play uses Faithful modded.

## Expected Behavior

For an XP cost, displayed in the GUI, I'd expect to be able to uncraft items.

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1. Craft uncrafting table.
2. Place any item in.

## Context

Makes gathering certain materials/fixing mistakes in crafting incredibly harder.
## Logs

* Client/Server Log: https://gist.github.com/EhGneissGuy/a93aaddf29a5f24ed054a710f72f0466
* Crash Log: N/A

## Client Information

* Modpack Version: 3.0.7
* Java Version: 8.171
* Launcher Used: Twitch

* Memory Allocated: 6.4 GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes
* Optifine Installed?: Yes

## Server Information
* Java Version: N/A
* Operating System: N/A
* Hoster/Hosting Soultion: CubedHost 4GB
* Sponge (Non-Vanilla Forge) Server?: N/A

* Additional Content Installed?: Yes [Akashic Tome, Morph-o-Tool, Test Dummy Mod [MmmMmmMmmMmm])

**Comment by JRiebling** [comment]
I remember someone saying a while ago that it has problems recognizing staged items. Thus, pretty much anything in the base modpack won't work with it.

As such, perhaps it should simply be disabled, as I remember being quite disappointed myself when I made it and could do nothing with it.

**Comment by artdude543** [comment]
This is intentional due to how staging works. The crafter is not used in the pack for anything really. But the small number of recipes it allows. We are fine with it. By default in none staged packs most recipes don't work either. It's a known issue with the mod/block and has been since 1.7 so could get fixed or axed who knows.

But from our point of view, it will stay enabled _for now_ and will only have limited usages.
