### ISSUE TITLE
Can't craft Flint Pickaxe until after crafting Flint Axe

### ISSUE THREAD

**Issue by Auretus** [DarkPacks/SevTech-Ages#2365]
## Issue / Bug

Flint Pickaxe recipe doesn't work until after Flint Axe is crafted
## Expected Behavior

Flint Pickaxe should be craftable as soon as the listed prerequisites are met (Work stump, sticks, plant twine, flaked flint, crafting rock

## Steps to Reproduce (for bugs)

1. Start new game
2. Craft work stump
3. Craft plant twine
4. Craft flint flakes
5. Place work stump
6. Place sticks, flint flakes, and plant twine on stump according to recipe
7. Use crafting rock. Notice that no amount of right-clicking will make the recipe work
I've completely broken a crafting rock trying to get this recipe to work in the manner described.
8. Rearrange items on crafting table to make Flint Axe
9. Use crafting rock. Flint Axe crafts normally
10. Place items for Flint Pickaxe on stump
9. Use crafting rock. Flint Pickaxe now crafts normally.

## Client Information

* Modpack Version: 3.0.7
* Java Version: 8 update 171
* Launcher Used: Twitch Client
* Memory Allocated: 8192MB
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: tried both ways, doesn't seem to matter
* Optifine Installed?: no

**Comment by Jandakast** [comment]
How are you crafting a work stump before crafting a Flint Axe? Breaking wood without the Axe should just break the wood block and give you nothing.

**Comment by Auretus** [comment]
Flint hatchet does the job nicely. After that, feed the log into the
crafting interface to get the chopping block, then feed that into the
interface again with another log and you get work stump.

**Comment by Auretus** [comment]
Also, stump is a prerequisite for axe anyway, since it needs a 3x3 crafting
grid.
