### ISSUE TITLE
Crafting Pneumaticcraft Speed Upgrade Crashes Game

### ISSUE THREAD

**Issue by JackApples** [DarkPacks/SevTech-Ages#2366]
**# Issue / Bug**
When I craft the speed upgrade from Pneumaticcraft, my game crashes immediately.

**# Expected Behavior**
Should be able to craft the speed upgrade from Pneumaticcraft without the game crashing.

**# Steps to Reproduce (for bugs)**
1 Craft the speed upgrade from Pneumaticcraft.
2 Game crashes

**# Client Information**
Modpack Version: 3.0.7
Java Version: 8 update 171
Launcher Used: Twitch Client
Memory Allocated: 6114MB
Server/LAN/Single Player: Server
Resourcepack Enabled?: No.
Optifine Installed?: Yes.

**# Crash Log:**

https://pastebin.com/Debtvn3M

**Comment by JRiebling** [comment]
For OP, I encountered this same issue when crafting in bulk. Crafting them one at a time seemed to work just fine.

Of course, I quickly got tired of creating a stack of the buggers, so I threw the ingredients in lava and waited for the great lava entity to grant me a stack (in the form of JEI cheating them in).
