### ISSUE TITLE
Can't open ./settings.sh upon first run on linux

### ISSUE THREAD

**Issue by derpinirish** [DarkPacks/SevTech-Ages#2367]
Noe I have been insulted before stating I can't read, you might want to look again.
![screenshot from 2018-05-11 17-23-10](https://user-images.githubusercontent.com/38843687/39947494-1a127f2a-5540-11e8-8cce-da34a3b9e090.png)
Now say I can't read I even did the permissions check with chmod. I ran the install, that didn't work, I even ran the serverstart that didn't work, same error Can't open settings.sh even though its literly there in it's face, now this may have a bad start command.

**Comment by derpinirish** [comment]
definitly a bad start command with something, its not java....I tried hot linking it, no luck...

![screenshot from 2018-05-11 17-53-29](https://user-images.githubusercontent.com/38843687/39948522-596f1418-5544-11e8-96ca-94300af131dc.png)

**Comment by derpinirish** [comment]
it did do install when I did that but when i tried to start it it goes unable to access jar file and i looked at the directory, its not there, so either the forge server file is missing from the download directory or named incorrectly or its got a bad start command... The EULA is there and set to true....

**Comment by tapiralec** [comment]
did you mark settings.sh as executable?
`chmod +x settings.sh`

**Comment by derpinirish** [comment]
hyper linking it works and its reading the file but it not downloading it even though its it is....
I'm on ubuntu 18.04 LTS btw but i know its well compatible with java 8

**Comment by derpinirish** [comment]
this may be an issue within the start install command and the installer.....
![screenshot from 2018-05-11 19-36-06](https://user-images.githubusercontent.com/38843687/39950881-e1650428-5552-11e8-82ee-d6581235e639.png)

**Comment by tapiralec** [comment]
which directory are you in?
`pwd`

**Comment by tapiralec** [comment]
it looks like you don't have a copy of settings.sh in your home/mikeadmin/st directory

**Comment by derpinirish** [comment]
No its there its a matter of hyper linking it with"" marks.   Its weird but it reads the settings file but doesnt download anything it just goes split second done and i know it takes much longer than a second to download, i tried the at launchers server, workx but has an issue eula, its set to true still saying you need to agree it is missing server.properties which usually autogenerates.

**Comment by artdude543** [comment]
Hello! I make all the server files for the pack and test them on all Operating Systems before release to ensure they work. 18.04 LTS is the build I test against which it's working fine for said version.

I know there is an issue with the line endings being wrong on Unix and the download currently. So if you run a converter on them and try again. (Yes this may not fix it but it will rule that factor out).

But I've tested the download myself again (did the conversion) and it's install/booted fine w/o issues.

**Comment by artdude543** [comment]
`dos2unix`? A pretty standard command for conversions... Your EULA issue is your fault tbh and this entire issue sounds like some config issue as the EULA is in the root. If it's unable to read it this would lead to permission issues/line endings again and/or broken file.

It's not funny also ^_^ Just giving the facts!

**Comment by derpinirish** [comment]
You were saying?
![screenshot from 2018-05-12 15-45-49](https://user-images.githubusercontent.com/38843687/39961019-ab461aea-55fb-11e8-83bb-a80ff1505639.png)

Way ahead of ya......the permission issue I might have to do in root, which would be

`sudo launcher.sh`

if that don't work then there is an issue with both because I did root install.sh and it just farted on me...

**Comment by Marcel40625** [comment]
just run the universal.jar and install the server ... and u are fine :)

**Comment by derpinirish** [comment]
did that 20 times yesterday, no luck, it would just go cannot download even though I gave it root I might change out my ubuntu to a different linux which may happen and btw just ran the launcher on root...

results......negative

![screenshot from 2018-05-12 15-49-56](https://user-images.githubusercontent.com/38843687/39961072-9273d8da-55fc-11e8-83d1-8d0b6b2c1b98.png)
![screenshot from 2018-05-12 15-50-07](https://user-images.githubusercontent.com/38843687/39961073-96b2a44e-55fc-11e8-9fa9-0b2eea1b6615.png)
![screenshot from 2018-05-12 15-50-11](https://user-images.githubusercontent.com/38843687/39961076-9addead8-55fc-11e8-8261-da0b70a89e86.png)

now I ran that full root even when the EULA is set to true.  Feed the beast launchers never have this issue and I use to run 1.7.10 Infinityevolved 250 server, I'm wondering if Mojang patched something up with modded servers like these, and I mean any modded....bukkit, and forge are having issues with 1.12 lately....

**Comment by artdude543** [comment]
Okay so how this missed me I don't know but the issue is actually pretty straightforward.

Both the Install and Start script **need** to be in relative to the server directory. Otherwise, when you start the server it uses the `cwd` of where the called the jar, not the `cwd` of where the files are. I only noticed this on your screenshots and how you were calling the script and a lightbulb moment happened.

But yeah that's your issue run the scripts inside the directory and your golden.

**Comment by derpinirish** [comment]
or i can go into my windows partition and run the bat files...

**Comment by artdude543** [comment]
Okay so after double checking _(and wasting more time)_ this is something you're doing out the ordinary for the scripts. The scripts are based on the ones FTB now supply in downloads and they are vetted before upload and are checked multiple times.

As 98% of the user base run the server from the directory it's contained in and it's not a symlink or _"non"_ standard file system the script works 100% of the time.

I won't update the script to allow from other media sources as MC Forge it self won't run when called from another dir to how the directory setting is done in Java. As you disccoved when MC can't find the eula as it's not reading from where the files are but from where you called the jar from.

I'm not going to spend anymore time on this issue. As it's not a normal case and it's your matter and you'll need to either follow how the run the server or make something work for your use case. But other than that I nor anyone else can help/change how MC server starts.

Thanks!

**Comment by derpinirish** [comment]
Then you're fools........

You have failed to recognize your main issue now which is the EULA agreement, I figured out the start command and solved that issue why aint it readin the EULA, I deleted it and restarted still nothing even change the eula=false to eula=true, your telling me thats not an issue.....your client side works but your server side sits there and jerks off...I ran it on windows, same problem its on your end......

**Comment by artdude543** [comment]
No one is a fool here. The EULA works perfectly fine. That is also outside of the support from the modpack team. So feel free to try to find somewhere else on the internet for support. May I suggest the Mojang Tracker or MC Forums.

If there was an issue with the EULA a tonne of people would be having the same issue. Which they are not, the last EULA bug reported to Mojang was back in late 2017 so `¯\_(ツ)_/¯` This has nothing to do with the pack at all. So I hope you can eventually get this sorted but we're not going to assist any further.

**Comment by Jandakast** [comment]
I can run the server files just fine....
