### ISSUE TITLE
IE Tank / IE Silo Dupe Flying Iron Sheetmetal

### ISSUE THREAD

**Issue by Wassaaa** [DarkPacks/SevTech-Ages#2368]
## Issue / Bug

Using Teleposer to move a IE Tank or Silo produces flying iron sheet metal in the past location and a full working tank in the destination.

## Expected Behavior

IE Tank/Silo moves and leaves nothing behind

## Possible Solution

I have no idea, but I tested to telepose some other IE machines and they work normal. (crusher, Trubine, Alternator). Also having the exact same position tank in the other end fixes the flying sheetmetal. it just switches between 2 tanks and nothing drops.

## Steps to Reproduce (for bugs)

[Video Link](https://streamable.com/46gyc)
1. Build an IE Tank and activate the multiblock
2. Put down a Teleposer under the multiblock (middle)
3. Shift click with Reinforced Teleposition Focus on the Teleposer to save the coordinates
4. put down another Teleposer 10 or so blocks away and put in the Teleposition Focus with the coordinates
5. Put a button on the side of the Teleposer.
6. Click the button and enjoy flying Iron Sheetmetal.

## Context

Just wanted to move Tanks of liquid around with Teleposers over long distances.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version: Java 8 (171) 64-bit
* Launcher Used: Twitch (Jar Launcher)

* Memory Allocated: 6gb

* Server/LAN/Single Player: reproduced in Single Player but also happens in server
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by justinrusso** [comment]
Going to make an assumption (along with Jandakast) and say this is a Realistic Drops issue

**Comment by Jandakast** [comment]
Trying to blacklist the Immersive Engineering blocks from the teleposer as multiblocks shouldn't be able to be moved this way... and found that the blacklist in the config isn't working. Reported to mod. https://github.com/WayofTime/BloodMagic/issues/1303
