### ISSUE TITLE
Odd Hotbar and Hand Visual Bugs

### ISSUE THREAD

**Issue by KCtops100** [DarkPacks/SevTech-Ages#2370]
Hello,

I have just updated Sevtech Ages to version 3.0.7 today.  Everything seemed to be going well until i used Immersive Engineering's Engineer's Workbench.  After using it to make some circuit boards, every time after I either use JEI or pause the game, the items on my hotbar block the JEI search function.  Additionally, some of the icons (including a gold backpack from Iron Backpacks) act strange while pausing.

Another issue that has happened after using the Workbench is my hand acting strange with flowers from the Ferdinand's Flowers mod.  Attached are screenshots that show what I am writing about.  This is my first time using this issue page, so please let me know if I need to do anything else or I am doing anything wrong.

Appreciate your time!

![2018-05-11_18 27 09](https://user-images.githubusercontent.com/29132307/39949480-fd89e132-5548-11e8-959e-d882555915f1.png)
![2018-05-11_18 21 28](https://user-images.githubusercontent.com/29132307/39949492-0ee7e140-5549-11e8-8a0c-21da54f74c87.png)
![2018-05-11_18 21 32](https://user-images.githubusercontent.com/29132307/39949499-12e7cdbe-5549-11e8-9937-2d037a5aa238.png)

**Comment by KCtops100** [comment]
One thing that I forgot to add, I am using Optifine.

**Comment by justinrusso** [comment]
Please try without optifine

**Comment by KCtops100** [comment]
Thank you for responding!
