### ISSUE TITLE
Aevitas Attuned Mantle of Stars Not Giving Saturation or Hunger Shanks

### ISSUE THREAD

**Issue by ABCEasyAs123** [DarkPacks/SevTech-Ages#2371]
## Issue / Bug

It would seem the Aevitas mantle of stars no longer gives hunger or saturation to the player. I noticed in the patch notes that it said the values for aevitas was adjusted, but even after waiting 5 or so minutes, my hunger and saturation was the same.
![2018-05-11_15 34 28](https://user-images.githubusercontent.com/18062733/39950025-a4d3f8e4-554c-11e8-8423-052d33becbfc.png)
![2018-05-11_15 34 23](https://user-images.githubusercontent.com/18062733/39950020-a11776ea-554c-11e8-88d4-1b2659e53df9.png)

## Expected Behavior

Upon equipping the mantle, hunger and saturation should be filled

## Steps to Reproduce (for bugs)

1. Lower hunger and saturation
2. Equip Mantle of Stars attuned to Aevitas constellation
3. Wait

## Logs

* Client Log: https://gist.github.com/ABCEasyAs123/a14462d4eb318b9acc6170a3a9f0f151
* Server Log: https://gist.github.com/ABCEasyAs123/ef160b0fb4b76bdfd8b8e686ed6878cd

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.80_171
* Launcher Used: ATLauncher

* Memory Allocated: 4GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by tahg** [comment]
Hunger refilling was intentionally disabled, but I've noticed it not ever giving you saturation either (I've afk'd for hours wearing the cape)

**Comment by Jandakast** [comment]
This should be fixed for 3.0.8
