### ISSUE TITLE
Game seems to crash specifically while browsing the Immersive Engineering Manual

### ISSUE THREAD

**Issue by zemallo** [DarkPacks/SevTech-Ages#2372]
My game seems to crash quite consistantly while browsing the Immersive Engineering Manual, Unsure what is causing this as I cannot really wrap my head around the crash log. 

Things of note, I play this on a server i host, the server is 100% fine and not crashing, only my client is crashing, Just aged up to age 3.

Here is a pastebin of the crash log. 
https://pastebin.com/2ykENfQX

**Comment by Stifling-Bossness** [comment]
This is fixed by updating your Java, it even tells you in chat when you first log in that you're using an outdated version and that it will crash if you open the manual.

**Comment by zemallo** [comment]
owo Huh.. How about that. Thanks!

**Comment by EhGneissGuy** [comment]
@zemallo This is an issue specifically with Twitch launcher as well. It will use an out of date java version. See this Reddit post or this photo for the args to fix it (if you're using that launcher that is).
https://www.reddit.com/r/feedthebeast/comments/8iogvf/how_to_use_the_latest_java_version_while_using/

![image](https://user-images.githubusercontent.com/17113297/39952096-f2df5738-555e-11e8-996f-2ed2af6f5763.png)
