### ISSUE TITLE
Conversion wand treats  ironwood as olive wood - potentially more conflict.

### ISSUE THREAD

**Issue by EhGneissGuy** [DarkPacks/SevTech-Ages#2374]
## Issue / Bug

When selecting ironwood with the conversion wand, it selects olive wood whether or not it's in your inventory. Potentially all rustic woods have this issue, cannot test at this time.

![ezgif-1-04a55f5c20](https://user-images.githubusercontent.com/17113297/39952065-73f19238-555e-11e8-87f9-af841a46dacb.gif)

## Expected Behavior

Block selected should be the block in the top right/block referenced.

## Possible Solution

Worked before 3.0.7, potentially roll back nerf to conversion wand.

## Steps to Reproduce (for bugs)

1. Place ironwood.
2. Select ironwood with wand.

## Context

Cannot use ironwood with conversion wand.

## Logs

* Client/Server Log: https://gist.github.com/EhGneissGuy/a93aaddf29a5f24ed054a710f72f0466
* Crash Log: N/A

## Client Information

* Modpack Version: 3.0.7
* Java Version: 8.171
* Launcher Used: Twitch

* Memory Allocated: 4 GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes
* Optifine Installed?: Yes

## Server Information
* Java Version: N/A
* Operating System: N/A
* Hoster/Hosting Soultion: CubedHost 4GB
* Sponge (Non-Vanilla Forge) Server?: N/A

* Additional Content Installed?: Yes [Akashic Tome, Morph-o-Tool, Test Dummy Mod [MmmMmmMmmMmm])

**Comment by Jandakast** [comment]
This has nothing to do with the crafting recipe change made to the conversion wand. This happens with any block that shares the same ID but has different Meta values. This is an Astral Sorcery bug.

**Comment by Jandakast** [comment]
https://github.com/HellFirePvP/AstralSorcery/issues/692

**Comment by artdude543** [comment]
Will be fixed in 3.1.0 😄
