### ISSUE TITLE
When adding new mods to the pack, sometimes recipes seem hidden/inaccessible for the players.

### ISSUE THREAD

**Issue by EhGneissGuy** [DarkPacks/SevTech-Ages#2375]
## Issue / Bug

I totally get that this is a bit outside the purview of the pack, but it's the best place to ask I reckon. I wanted to add the Akashic Tome and Morph-o-Tool mod to the pack for my server players, but the recipes remain hidden away from general use and, when used, don't work. Now, the mods should work since they use the same library as a few other mods in the pack and the items are clearly there in JEI, although obfuscated. But even using, for instance `/give Player akashictome:tome` doesn't work.

What's odd is these are the only mods added to have done this. For instance, the Test Dummy Mod works right off the bat - the recipe is easily searchable and craftable as long as you understand the components. However, the Akashic Tome and Morph-o-Tool recipes are only accessibly by using the "Uses" hotkey on an ingredient in JEI (ie, cactus green for the morph-o-tool or bookshelf for the Akashic tome), and then using the recipe that way. Even with all ingredients present and able to be JEI-auto crafted the recipe doesn't yield an item.

## Expected Behavior

I'd expect it to work just like any other mod added to the pack without a blacklist on the items for progression. 

## Possible Solution

I'm not entirely sure how the item blacklist/whitelist works for JEI and the ages, but I imagine it's something to do with that.

## Steps to Reproduce (for bugs)

1. Install Akashic Tome/Morph-o-Tool.
2. Try to craft.

## Context

I was hoping to add some new content to the pack for personal use on my server since my players and I were pretty hyped when we learned about the mods. If the pack locks out all customization or adding of new items/mods/recipes, it makes it pretty difficult to tailor a private player experience.

## Logs

* Client/Server Log: https://gist.github.com/EhGneissGuy/a93aaddf29a5f24ed054a710f72f0466 / https://gist.github.com/EhGneissGuy/f7b122dd1dbd4b7ecb871398925a50e2
* Crash Log: N/A

## Client Information

* Modpack Version: 3.0.7
* Java Version: 8.171
* Launcher Used: Twitch

* Memory Allocated: 4 GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes
* Optifine Installed?: Yes

## Server Information
* Java Version: N/A
* Operating System: N/A
* Hoster/Hosting Soultion: CubedHost 4GB
* Sponge (Non-Vanilla Forge) Server?: N/A

* Additional Content Installed?: Yes [Akashic Tome, Morph-o-Tool, Test Dummy Mod [MmmMmmMmmMmm])

**Comment by EhGneissGuy** [comment]
@justinrusso I agree and understand, but there shouldn't be a conflict with a mod with as specific an id as akashictome:tome. If it were another mod or the like, I'd understand a bit more. But I see why this is a risk with adding anything independently.

I don't understand either, which is why I initially thought maybe it worked on a whitelist and just blocked crafting anything not inherently listed.

![ezgif-1-0d5594b9fa](https://user-images.githubusercontent.com/17113297/39952401-07b81e24-5564-11e8-8ad4-7ce7d0d8d69f.gif)

That is currently the situation I'm in. The recipe is there, but nothing else seems to be. If you have time to think it over or if you do end up adding these mods in the future, keep me in mind.

**Comment by tahg** [comment]
I don't believe either of those mods add blocks, so they should be safe in that regard.  As far as the issue is concerned, are you sure they are installed correctly on the server? It doesn't look like you provided a server log, so it's hard to verify if that's the case or not.

**Comment by EhGneissGuy** [comment]
@tahg Sorry, slipped my mind. Yes, installed on a server and correctly I believe. Here's the log. https://gist.github.com/EhGneissGuy/f7b122dd1dbd4b7ecb871398925a50e2

**Comment by justinrusso** [comment]
@tahg I was not stating that that was the issue here - it was just a general statement.

I also agree with that assumption. It seems as though the client knows of the recipe, but the server has to validate it and cannot. Try making it in singleplayer to see?

**Comment by artdude543** [comment]
This is a server issue as the mod is not loaded hence the recipes not working. JEI syncs with the server on the items to list. However, the recipe sync is another thing and it pulls recipes from the client. So the recipe will show on your end but the server won't know about the recipe.

1. Have you actually uploaded your changes/mods to the server and rebooted it?
2. Are you **sure** that the mod is loading up on the server on boot time. I.E. No errors or warnings.

This is **not** a script issue with the pack as the recipes will load up fine _(as you can see from your JEI)_ but I'm leading to believe that the server does not know anything about the mod. _(Which is confirmed by the fact the `give` command does not work)_ So please confirm the questions above and get back to us! Thanks

**Comment by EhGneissGuy** [comment]
@artdude543 @justinrusso @tahg 

It looks like it definitely was server side, but it was just an oversight on my part. At the time that I'm writing this, I'm reuploading the mods and will restart the server shortly. I don't know what caused it, but the mods were missing from the mod folder. However, my transfer history on Filezilla shows I did upload the mods to that folder earlier this week, but when looking at the folder again, the mods aren't there. It's likely a one-off issue. 

After restarting the server, everything seems to be working just great! I won't pretend to know what happened, but I'm thankful for ya'll taking the time to help me with this issue. I'll be sure to check the things that seem certain more often with this kind of stuff.
