### ISSUE TITLE
Abyssalcraft Oblivion Catalyst not able to summon

### ISSUE THREAD

**Issue by Setsua** [DarkPacks/SevTech-Ages#2376]
## Issue / Bug
If you summon the Oblivion Catalyst for Gateway Key from Abyssalcraft the items on the pedestals disappear except for the ender pearl. The animals (sacrifices) are unaffected.
https://streamable.com/cp97b

## Expected Behavior
Animals (sacrifices) die, all items on the pedestals disappear and Oblivion Catalyst appears.

## Logs

* Client Log (partly due to size): https://pastebin.com/w8uYryPx
* Server Log: https://pastebin.com/QUummxsk

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_171
* Launcher Used: Twitch

* Memory Allocated: 3072

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: 1.8.0_171
* Operating System: Debian 4.9.88-1+deb9u1
* Hoster/Hosting Soultion: CubeCoders AMP (https://cubecoders.com/AMP)
* Sponge (Non-Vanilla Forge) Server?: No

* Additional Content Installed?: Yes, DebugServerInfo (https://minecraft.curseforge.com/projects/debugserverinfo)

**Comment by justinrusso** [comment]
Killing the animals yourself should work
