### ISSUE TITLE
[Issue][3.0.7] Rope block cannot be uncrafted back into 9 ropes.

### ISSUE THREAD

**Issue by Rosethorns** [DarkPacks/SevTech-Ages#2379]
## Issue / Bug
Better with Mods Rope Blocks can no longer be uncrafted back into 9 rope. 

## Expected Behavior
Rope blocks are storage blocks for rope. Placing a rope block into any vanilla crafting grid should allow the block to crafted into 9 Better With Mods Rope

## Possible Solution
I could not find the offending script, however I suspect its something which affects betterwithmods:aesthetic:* or some such, Rope blocks are meta 4 (betterwithmods:aesthetic:4)

## Steps to Reproduce (for bugs)
1. Place rope block into vanilla crafting grid
2. No rope output

Or

1. check uses for rope block
2. no uncrafting recipe listed.

## Context
All my rope stored in block form is currently useless without processing it back via cheat trading with JEI

## Client Information
* Modpack Version: 3.0.7
* Java Version: 8 161
* Launcher Used: Jar Launcher
* Memory Allocated: 8gb
* Server/LAN/Single Player: Single Player

**Comment by justinrusso** [comment]
This is caused by the rope's recipes being removed and created custom. Removing all the recipes causes that De-compression recipe to be removed as well.
