### ISSUE TITLE
IE and Buildcraft Causing Server Crash When Going From 3.0.6 to 3.0.7

### ISSUE THREAD

**Issue by ArsFrags** [DarkPacks/SevTech-Ages#2381]
## Issue / Bug
Upgraded the server from 3.0.6 to 3.0.7.  The server was in a crash loop.  It seems to be an incompatibility between IE and Buildcraft

## Expected Behavior
No crash :)  It almost appears as if the IE multiblock structures are not properly completing and a buildcraft pipe attempts to attach to the uncompleted structure.

## Possible Solution
I had to revert back to 3.0.6

## Steps to Reproduce (for bugs)
Upgrade server to 3.0.7

## Context
I had to revert back to 3.0.6.

## Logs
https://pastebin.com/rGu4mKzQ
https://imgur.com/a/L2ixIbl

## Server Information
* Java Version: 1.8.161 x64
* Operating System: Linux (amd64) version 4.9.87-xxxx-std-ipv6-64
* Hoster/Hosting Soultion: Bisecthosting
* Sponge (Non-Vanilla Forge) Server?: no
* Additional Content Installed?: no

**Comment by artdude543** [comment]
Can you downgrade, break the multiblock, upgrade and see if this works/fixes?

This seems like an edge case but this could be a decent test also. (Use a copy of backup for this so you don't have to care for loss of resources)

**Comment by ArsFrags** [comment]
Before I saw your reply, I had accidentally broken the tank and re-built it.  I also removed the buildcraft pipes that were attaching to the tank.  One of these 2 steps has stopped the server crashing and I successfully upgraded to 3.0.7.

**Comment by pip69** [comment]
I might be having the same issue.  
I have the advanced coke oven with a buildcraft fluid pipe on the output, I thinks its crashing when I look at the buildcraft fluid pipe.

https://pastebin.com/SsyPYq0R
