### ISSUE TITLE
Torches are not Craftable with String

### ISSUE THREAD

**Issue by Alyusha** [DarkPacks/SevTech-Ages#2382]
## Issue / Bug

Currently (as of Age 3) you need to use Coal/Charcoal + Sticks + Twine / Plant Fiber / Sinuous Fiber / Sinuous Cordage / Leather Cordage to make 2 Torches.

## Expected Behavior
String should be a part of the recipe for Torches. Logically it is equal to or greater than Twine or Plant Fiber and is used as an alternative in other parts of the pack.

## Possible Solution
Add String to the Recipe manually or if supported (I'm pretty unfamilure with the Dev side) add the alternatives to String to the Ore Dictionary.

## Context
I'm reaching a position where it is easier for me to obtain String than it is for me to obtain other alternatives, which is to be expected in a mod pack like this. It is very tedious for me to have to ignore my String Farm and go dig up dirt / break random grass just to make torches.

There are other alternatives (I'm working on my Blood Lamp atm) but this seems more like an oversight than a feature.

## Client Information

* Modpack Version: 3.0.6
* Java Version:
* Launcher Used:Twitch
* Memory Allocated: 8Mb

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by artdude543** [comment]
This is an intended recipe for the torches and won't change. To add the usage would require adding another recipe (of many) which will increase load time. But yeah this recipe is intended for the pack.
