### ISSUE TITLE
Work Stump broken

### ISSUE THREAD

**Issue by Shadownixx** [DarkPacks/SevTech-Ages#2383]
Whenever I try to place things on the work stump it doesn't place the item where I want it to go! I'll place a stick but it will actually place like 3 slots away. I've tried restarting the game multiple times.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
