### ISSUE TITLE
Udated to new version

### ISSUE THREAD

**Issue by Ticskter** [DarkPacks/SevTech-Ages#2385]
updated from 3.0.6 to 3.0.7 just a few minutes ago and Sevtech now only has 9 mods installed. went to load world anyway and it says like nearly 10 thousand block ids are missing. i hit cancel to investigate. reverted back to 3.0.6 and the same thing happens and the world will not load. i really hope i havent lost all that i have worked for in this mod pack.

mod pack has worked absolutely fine up until 3.0.7 for me.

**Comment by justinrusso** [comment]
https://github.com/DarkPacks/SevTech-Ages/issues/2355
