### ISSUE TITLE
Conflicting mill stone cocoa beans recipes

### ISSUE THREAD

**Issue by Stifling-Bossness** [DarkPacks/SevTech-Ages#2386]
## Issue / Bug
JEI shows putting cocoa beans in the mill stone to have 2 different recipes, one for cocoa powder, and the other for 2 brown dye. When milled, it makes cocoa powder.
https://imgur.com/a/uPff1fs

## Expected Behavior
Have one recipe for cocoa beans in the mill stone.

## Possible Solution
Either remove the brown dye recipe, or have the cocoa powder recipe require something else as well, such as sugar.

## Steps to Reproduce (for bugs)
1. Look up Cocoa Beans in JEI
2. Look at uses for Cocoa Beans in the Mill Stone.

## Context
I was making cocoa powder and I noticed that there were two uses for the beans, luckily I was after the cocoa powder and not the brown dye powder.

## Logs
* Client/Server Log: https://gist.github.com/Stifling-Bossness/74b37554cd67540c6be46f1f8ed3199c

## Client Information
* Modpack Version: 3.0.7
* Java Version: 1.8.172
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Yes, 32x Faithful Modded Edition
* Optifine Installed?: No
* Mods disabled: Better Foliage and Fancy Block Particles.

**Comment by justinrusso** [comment]
Just need this looked over. I was not able to open up the game and check.

The route should be Beans -> cocoa powder -> dye powder.

Check other machines as well.

**Comment by pjc21** [comment]
Mill Stone recipe looks good now
- Cocoa Beans > Cocoa Powder

The Grindstone recipe still 
- Cocoa Beans > 2x Brown Dye Powder

First 2 images are Cocoa Beans recipes, rest are Cocoa Powder > Brown Dye Powder.
https://imgur.com/a/XTXqcFN
