### ISSUE TITLE
Optifine

### ISSUE THREAD

**Issue by Spelhajen** [DarkPacks/SevTech-Ages#2389]
installing optifine by adding it, as a jarfile, through the "edit mods" 
when launching the pack it's a black screen on instead of the normal and then it just crashes after a while
can launh without optifine and tried all 1.12.2 optifineversions.

its really annoying now, been at it for 2 days.

**Comment by artdude543** [comment]
1. Don't make another issue just comment on the closed one.
2. Canned Response 

Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by Spelhajen** [comment]
i did comment on the original one though
