### ISSUE TITLE
Totemic : Wind Chime not working properly

### ISSUE THREAD

**Issue by lacraft1** [DarkPacks/SevTech-Ages#2390]
## Issue / Bug
When I try to select the wind chime for a ceremony in single player (for example the Buffalo Dance), nothing happens. I verified that nothing was in my hands (including the off-hand), verified that the chime was next to the totem and tried to remove my equipment, without success.

## Expected Behavior
The wind chime should be selected and the ceremony which requires this instrument should start.

## Steps to Reproduce (for bugs)

1. Place a totem
2. Place a wind chime in a 1 block radius around the totem
3. Place a totemic drum for the buffalo dance
4. Select with sneak + left click the totemic drum then the wind chime
5. Nothing happens, and if the drum is selected next, the war dance will trigger

## Context
This prevents me from progressing through the game.

## Client Information

* Modpack Version: 3.0.7
* Java Version : 8.0.1610.12
* Launcher Used: ATLauncher

* Memory Allocated: 4 GB

**Comment by Jandakast** [comment]
Are you sneak right clicking the wind chime with an empty hand?

**Comment by lacraft1** [comment]
Thanks for your suggestions, but I finished to find what was the problem . When a totem is built, it can be composed of multiple totem poles (blocks in other words), and when an instrument is played, only the totem pole at the same level than this instrument recognize it for a ceremony. The problem was that my drum was at the same level than the first totem pole, and my wind chime at the level of the second totem pole (the one above the previous one), and so the instruments were not selected together, thus resulting in the War Dance triggered when the drum was selected a second time.
