### ISSUE TITLE
World Not Working Correctly. Not loading correctly even upon entering.

### ISSUE THREAD

**Issue by skye006** [DarkPacks/SevTech-Ages#2391]
## Issue / Bug

Chests/GUI's fail to open. Behavior is similar to block lag except nothing ever happens. When trying to Save World to attempt to get back to main menu, minecraft begins to not respond and does not fix itself and I am forced to forcibly end minecraft.
Video: https://youtu.be/gIwLKw0_V5Q

## Expected Behavior

Chests and GUI's loading correctly as well as broken blocks should be broken when mined.

## Steps to Reproduce (for bugs)

1. Enter World
2. Chests along with any GUI's fail to open.

## Context

I am unable to play SevTech as this prevents me from doing so.

## Logs

* Client/Server Log: https://gist.github.com/skye006/5cc8c9cdbd35b874df60b752890047fc
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version: 8
* Launcher Used: Twitch

* Memory Allocated: 6.4 MB

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Soartex Fanver Modded
* Optifine Installed?: Yes

**Comment by skye006** [comment]
Just tried launching without Optifine, problem still occurs.

**Comment by skye006** [comment]
Removed resource pack, problem still occurs.

**Comment by skye006** [comment]
Opened another world. Not having a problem with that one so it's just the one world.

**Comment by artdude543** [comment]
Sometimes worlds just _die_ it's one of the things when it comes to modded. Sorry about the world! 🙁
