### ISSUE TITLE
Unable to upgrade to version 3.0.7

### ISSUE THREAD

**Issue by kiwipels** [DarkPacks/SevTech-Ages#2392]
Hi,

I love this modpack and I have not encountered any problems with upgrading before, but now I get this message on Twitch saying:

"Error:
Cannot update, files are already in use. Please exit any applications that may be using the files in this profile folder"

I have tried to restart windows, but the same thing happens every time I try to upgrade.

**Comment by Jandakast** [comment]
This is a Twitch App/PC issue not a pack issue. Maybe try the Twitch subreddit.
