### ISSUE TITLE
Random Server Crashes

### ISSUE THREAD

**Issue by Newbtron** [DarkPacks/SevTech-Ages#2395]
## Issue / Bug

Once a few of us log into the server it stops after a few minutes and then restarts abruptly. 

## Expected Behavior

No real issues leading up to the problem. Lag seems about the same as normal and then we get the can't connect kick message as the server restarts. 

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/qAtmhdHK

## Client Information

* Modpack Version: 3.0.6 and 3.0.7
* Java Version:
* Launcher Used: 
 
* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?: 
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion: Shockbyte
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by Jandakast** [comment]
The log attached appears to be an incomplete latest.log not a crash log. If the server is crashing it should generate a crash log. If it is just restarting randomly we will need the latest.log file from the server.

**Comment by artdude543** [comment]
Thank you for reporting an issue!

It appears you are logging an issue for a crash, but you have either not uploaded to PasteBin/Gist etc.. of the actual crash report. This report contains the needed data to help to locate the cause and a possible fix. To find the file needed please review the following for either of the launchers.

## Twitch
1. Select the SevTech Pack to view the modpack page.
2. Click the `...` button on the top right just next to `Get More Content`.
3. Click `Open Folder`.
4. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it. 

## ATLauncher
1. Select the Instances tab, then scroll to the instance of SevTech.
2. Click the bottom right button named `Open Folder`
3. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it.

For any other launcher should be a similar process, if not consult with Google if you are not sure on how to find the folder. The information contained in these reports is critical for getting the crash fixed/looked into.

## Servers
For servers the process if farilt simple. Go the folder cotaining all the sever files/folder and you will see a folder called `crash-reports` follow the same process as above by getting the lastest one and uploading it to a text store.
