### ISSUE TITLE
Arcane scrolls do not drop (3.0.7 / Age2)

### ISSUE THREAD

**Issue by LordHellscream** [DarkPacks/SevTech-Ages#2397]
I've been killing random mobs in hunting dimension for hours and hours, i got 73 levels worth of kill. (killed over 1500 enemies)
I did all the killing by myself, not using grinding or anything. 
One of my sword even have fortune enchantment, and yet still no arcane scroll, am I bugged?

**Comment by LordHellscream** [comment]
I still have no found a single arcane scroll from random drop. I have now progressed to mid Age3, where I was able to build and kill withers, where this is no much an issue anymore. But based on what I've seen. they drop all the time (not common) for other folks, so I still think there is a bug here.

**Comment by LordHellscream** [comment]
Still have not found a single arcane scroll from drops. must have killed gazillions of mobs at this point (mid age3), I can build wither now so it's ok. But still I think I'm bugged somehow

**Comment by artdude543** [comment]
It's a rare drop in default. But it still drops just tested on a farm and got 5 already. RNG issue at the end of the day.

**Comment by LordHellscream** [comment]
I think if the game was designed for player to find it at some point naturally, then it failed spectacularly. I have logged 150 levels worth of xp before I finally reached to point to kill a wither, and i have not got a single drop from the gazillions of mobs I've slaugtered (no mob farm, all normal killing on my own). Is this intended to be this hard??

**Comment by artdude543** [comment]
I did it in 5 seconds with a test spawner as per my comment. It's all RNG. Make a mob farm and you'll get them with less effort. Or deal with the fact you've had bad RNG.
