### ISSUE TITLE
Assorted Quarts Not spawning

### ISSUE THREAD

**Issue by tapegreen** [DarkPacks/SevTech-Ages#2398]
The assorted Quarts just aren't spawning in my world. It is the latest world, recently into age 4, but cant find assorted Quartz. Silicon spawns just normally but I haven't found any assorted quarts.

**Comment by Jandakast** [comment]
The Assorted Quarts spawns it's just rare. I tested this with a new 3.0.7 world and in worlds from 3.0.6 and 3.0.5. Using the Scanner from Scannable in creative I found a sample about every 400 or so blocks from each other.
