### ISSUE TITLE
Unable to plant Rustic tomatos, chili peppers or Betweenland white pear seeds in Garden Cloche.

### ISSUE THREAD

**Issue by neonod** [DarkPacks/SevTech-Ages#2400]
## Issue / Bug
The following items cannot be placed in the Immersive Engineering Garden Cloche to grow crops:
Chili Pepper Seeds (Mod: Rustic - normally planted on wooden stake on tilled soil)
Tomato Seeds (Mod: Rustic - normally planted on wooden stake on tilled soil)
White Pear Seeds (Mod: Betweenlands - normally planted on purified swamp dirt that has been "dug" and covered with "compost")

## Expected Behavior
Use either wooden stake/dirt or purified swamp dirt as soil to allow crops to grow in cloche.

## Possible Solution
Unknown.

## Steps to Reproduce (for bugs)
1. Place expected soils in cloche.
2. Attempt to place seeds into cloche.

## Context
Attempting to use all garden cloches for growing of crops instead of multiple farm setups.

## Logs
* Client/Server Log: no logs.
* Crash Log: no logs.

## Client Information
* Modpack Version: 3.0.7
* Java Version: 1.8.0_171-b11
* Launcher Used: Twitch
* Memory Allocated: 8gb
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: Unavailable (sorry i am not owner of server so server specs unavailable)
* Operating System: Unavailable
* Hoster/Hosting Soultion: Unknown
* Sponge (Non-Vanilla Forge) Server?: No

**Comment by Ozzymud** [comment]
This one would be tough to do and maintain what the mods in question intended as the Rustic ones need the sticks for the vines to grow on and the Betweenlands not only need the dirt, but a special mechanic to prepare the dirt. Both of these require 2 growth mediums where the cloche can only handle one. It would sorta be like saying IC2 or Agricraft crop sticks don't work in the cloche. Both mods mentioned basically use "crop sticks" just they look and sound different.

**Comment by artdude543** [comment]
None of the plants are support and _won't_ be either unless someone makes a mod or PR to IE. But we can't add it ourselves. You'll have to do the good old fashion planting/harvesting.

But one day an integration would be made! You could suggest this to the devs of the mods also.

**Comment by artdude543** [comment]
@neonod @Ozzymud I got a tad bored this morning. So I made a thing xD 

![image](https://user-images.githubusercontent.com/1885466/40121413-6f8c4a1c-5919-11e8-8b22-a6aeaf94ad2e.png)

**Comment by neonod** [comment]
Looks nice.

**Comment by Notaros** [comment]
This mod seems to make the cloche combatible with rustic plants tested it seems to work in sevtech. 
https://minecraft.curseforge.com/projects/cloche-call

I added it to sevtech following these instructions.
https://www.reddit.com/r/feedthebeast/comments/4r1tpz/how_do_i_add_mods_to_the_curse_launcher_mod_pack/

**Comment by artdude543** [comment]
Well, we already have support for rustic plants. They just require farmland instead.
