### ISSUE TITLE
Unable to Load ModPack

### ISSUE THREAD

**Issue by anothrony17** [DarkPacks/SevTech-Ages#2401]
## Issue / Bug

I have tried a few times to load the game and it crashes during initialization. It gets to around the second round of loading and then crashes.

## Expected Behavior

I would expect the Mod Pack to load.

## Possible Solution

I haven't a clue.

## Steps to Reproduce (for bugs)

1. Load the Twitch Launcher
2. Select the SevTech modpack to load
3. Ask it to be played in the launcher
4. Watch the cute alien guy until it eventually crashes
5. Cry

## Context

I just want to try out this awesome pack.

## Logs

* Client/Server Log: https://pastebin.com/TbTqBm08
* Crash Log: https://pastebin.com/1TqzghYU
(not sure if these are correct...kind of a newb)

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.6.89
* Launcher Used: Twitch

* Memory Allocated: 6144mb

* Server/LAN/Single Player: n/a
* Resourcepack Enabled?: n/a
* Optifine Installed?: n/a

**Comment by artdude543** [comment]
Your missing one the needed libs mods for CC. This is installed with the modpack via Twitch/ATL.

1. Is the modpack/launcher install on a cloud drive? Like OneDrive or Dropbox?
2. What the is the file path to the instance? _(You can redact names from the file path)_

**Comment by anothrony17** [comment]
I suppose the file path is indeed on my OneDrive. 

The file path is: C:\Users\[redacted]\OneDrive\Documents\Curse\Minecraft

**Comment by artdude543** [comment]
Yep, that's the issue you can't use OneDrive for this (or MC in general) please move all files outside to the main Documents folder. Modpacks don't work with CloudDrives sadly.
