### ISSUE TITLE
Iron Backpack eating items

### ISSUE THREAD

**Issue by Donav22** [DarkPacks/SevTech-Ages#2402]
## Issue / Bug
(This issue started with 3.0.7)
Bug:
You can shove an iron backpack inside of itself.  If you do that, and then remove the iron backpack, the result is that the backpack is returned to its initial state before you tried to put your inventory in, but your inventory is still clean.  All of the items have been "eaten"

## Expected Behavior
A) You can not put the backpack inside itself
OR
B) You can safely remove it

## Steps to Reproduce (for bugs)
1. Have an iron backpack(gold in my case) in inventory (not hot bar)
2. Hit "I" to open it.
3. Hold shift-left click and swipe over your inventory (not hot bar) to shove everything in.
4. Say "oops" and remove the backpack back to your inventory
5. Hit ESC to close backpack
6. Hit "I" to re-open backpack
Optional
7. Cry a little on the inside and re-name the backpack to "Bag of Devouring"

(now with screenshots)
1) Inventory
![2018-05-13_12 58 43](https://user-images.githubusercontent.com/39231057/39969808-c2347cb0-56af-11e8-8017-00a8fa6d92c4.png)
2) Initial state (after hitting "I")
![2018-05-13_12 58 49](https://user-images.githubusercontent.com/39231057/39969815-db1c3e34-56af-11e8-8acc-5f23a233af19.png)
3) Held Shift-left-click on cobble on left and swiped right
![2018-05-13_12 59 06](https://user-images.githubusercontent.com/39231057/39969816-db2d32ac-56af-11e8-8151-71bd8c66a518.png)
4) Selected and moved backpack back to inventory
![2018-05-13_12 59 15](https://user-images.githubusercontent.com/39231057/39969817-db3bdbb8-56af-11e8-9eb0-ffd079f73fe2.png)
5) Hit "ESC"
![2018-05-13_12 59 19](https://user-images.githubusercontent.com/39231057/39969818-db4bf4a8-56af-11e8-8f71-55f65e423076.png)
6) Hit "I" again to re-open pack
![2018-05-13_12 59 25](https://user-images.githubusercontent.com/39231057/39969819-db58791c-56af-11e8-9aab-d4ee7915afb8.png)

## Context
First time, I had a ton of stuff going on, and lost a backpack full of astral stuff, but was clueless as to what happened.
Second time, I only had that one backpack with me, and was mining.  Cleaned out my inventory, and realized exactly what had happened and posted this report

## Logs
section from "latest.log"
[12:57:50] [Server thread/INFO]: Saving and pausing game...
[12:57:50] [Server thread/INFO]: Saving chunks for level 'SevTech6'/overworld
[12:57:51] [Server thread/INFO]: Saving chunks for level 'SevTech6'/Storage Cell
[12:58:31] [main/INFO]: [CHAT] Saved screenshot as 2018-05-13_12.58.31.png
[12:58:33] [main/INFO]: [CHAT] Saved screenshot as 2018-05-13_12.58.33.png
[12:58:39] [main/INFO]: [CHAT] Saved screenshot as 2018-05-13_12.58.39.png
[12:58:43] [main/INFO]: [CHAT] Saved screenshot as 2018-05-13_12.58.43.png
[12:58:49] [main/INFO]: [CHAT] Saved screenshot as 2018-05-13_12.58.49.png
[12:59:06] [main/INFO]: [CHAT] Saved screenshot as 2018-05-13_12.59.06.png
[12:59:15] [main/INFO]: [CHAT] Saved screenshot as 2018-05-13_12.59.15.png
[12:59:19] [main/INFO]: [CHAT] Saved screenshot as 2018-05-13_12.59.19.png
[12:59:26] [main/INFO]: [CHAT] Saved screenshot as 2018-05-13_12.59.25.png
[12:59:36] [Server thread/INFO]: Saving and pausing game...
[12:59:36] [Server thread/INFO]: Saving chunks for level 'SevTech6'/overworld
[12:59:36] [Server thread/INFO]: Saving chunks for level 'SevTech6'/Storage Cell

## Client Information

* Modpack Version: 3.0.7 (as-is, no additional mods, no config changes)
* Java Version: unknown
* Launcher Used: Twitch (latest)

* Memory Allocated: 6GB

**Comment by justinrusso** [comment]
I'm not able to reproduce this. I've followed your steps as provided...

Backpacks shouldnt be nested anyways (and I thought they should be) but something must be going on with the blacklist.

**Comment by dalsio** [comment]
I've actually noticed the backpack sometimes doing this without nesting them at all. Sometimes I'll put things in and not a minute later the backpack reverts to a previous state, with the most recent items gone but not in my inventory nor are they anywhere else. Might even work the other way around, but I've only really noticed it this way because it's the most... frustrating. It almost behaves similarly to effects seen with lag spikes (which I experience often, my PC is kind of old) and it may be an issue only experienced during low performance. Might also have something to do with shift clicking since I've noticed that if I shift click something into inventories and exit the GUI too quickly during a time of low-framerate, the items will usually spit out onto the floor or do other weird things.

**Comment by Donav22** [comment]
@dalsio Mine does it every time.  Example/Proof:  After @justinrusso was unable to reproduce, I fired up the game again, performed the bug again, and took/added the screenshots above.

**Comment by ginkoopl** [comment]
That issue #236 was posted by me, the iron backpacks works perfectly fine after I downgraded it to the latest full release version, instead of the beta one. I also used gold backpack.

**Comment by gr8pefish** [comment]
Hmm, I will have to investigate.

**Comment by Jandakast** [comment]
I added the backpack to the blacklist and it fixes the ability to put the backpacks inside of themselves or other iron backpacks bags. I will keep an eye on this to make sure it stays fixed as we update further.

**Comment by DarkHeroZark** [comment]
This issue is still in 3.0.8

**Comment by Jandakast** [comment]
This is not possible in 3.0.8 dev. You cannot shift click or place any of the Iron backpack bags into themselves or any other backpack from Iron Backpacks.
