### ISSUE TITLE
Paperclip Factory can NOT be formed due to Conveyor

### ISSUE THREAD

**Issue by SihenZhang** [DarkPacks/SevTech-Ages#2404]
## Issue / Bug

Paperclip Factory can NOT be formed just like this.
![](https://i.imgur.com/zYyZkvt.png)
Because the NBT Tag of the Conveyor is **wrong**. 
![](https://i.imgur.com/xkJlmPT.png)

## Expected Behavior

The NBT tag of the Conveyor in the JSON is just like this. 
> {
>             "x": -2,
>             "y": 0,
>             "z": 1,
>             "nbt": {"conveyorBeltSubtypeNBT":{"dyeColour":"-1","direction":"0"},"facing":"2","conveyorBeltSubtype":"immersiveengineering:conveyor","id":"immersiveengineering:conveyorbelt"},
>             "elements": [
>                 "immersiveengineering:conveyor@0"
>             ]
>         },

But the NBT tag of the Conveyor has changed to **"conveyorSubtype"** so a player can NOT get the Conveyor. 
Besides, if use "setBlock" to place this Conveyor which is with **wrong** NBT tag, the client will crash. 
I also upload the crash report if necessary.

## Possible Solution

Just rewrite the JSON file of Paperclip Facotry. MAYBE it will work. :)

## Steps to Reproduce (for bugs)

1. Just try to build a Paperclip Factory.
2. 

## Logs

* Client/Server Log:
* Crash Log: https://paste.ee/p/qm2CB

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_171
* Launcher Used: MultiMC

* Memory Allocated: 6144 MB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: [Simplified Chinese Localization Resource Package](https://minecraft.curseforge.com/projects/simplified-chinese-localization-resource-package)
* Optifine Installed?: No

## Server Information
* Java Version: 1.8.0_171
* Operating System: Windows Server 2012R2
* Hoster/Hosting Soultion: 
* Sponge (Non-Vanilla Forge) Server?: No

* Additional Content Installed?:

**Comment by Jandakast** [comment]
Currently the conveyors must be facing/moving items north in order for the machine to detect them correctly. We are exploring either adding a tooltip to the blueprint or potentially changing the conveyor blocks out with a different block that doesn't require a facing.

**Comment by Jandakast** [comment]
Actually I figured out how to make it accept conveyors in any orientation. Should be fixed in 3.0.8 :)
