### ISSUE TITLE
range upgrade industrial foregoing machine missing

### ISSUE THREAD

**Issue by ferrium42** [DarkPacks/SevTech-Ages#2406]
found no range upgrade , rancher has working area 1x2x1 , to small

 
## Expected Behavior
normaly this machine has an working area 5x1x5 in front 

## Possible Solution
add recipe, if not for the rancher you will need it in the planter and other machine

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by Jandakast** [comment]
These should already exist and have recipes. They are called "Range Addon". When filling out an issue report please be sure to fill in all of the information on the template. 

Did you enable a texture pack without restarting the game or change any mods? 

![image](https://user-images.githubusercontent.com/19498789/39967944-a03e137c-5692-11e8-93c8-03000412632c.png)
