### ISSUE TITLE
Twilight oak wood not sawing

### ISSUE THREAD

**Issue by Ataloumpak** [DarkPacks/SevTech-Ages#2407]
![2018-05-13_10 33 15](https://user-images.githubusercontent.com/6170190/39965518-e86af676-569a-11e8-9793-7f2c34777a45.png)

 
## Issue / Bug
When placing Twilight oak wood on a saw from better with mods, wood is not cut in planks

## Expected Behavior
Recipe shows that we can cut twilight oak wood into 6 logs and 3 dust.
Oak wood chopping works as intended.

## Possible Solution
NA

## Steps to Reproduce (for bugs)
1. Place a working saw from better with mods
2. Place in front of it a log of Twilight oak wood

## Context

I just tried to use the saw to cut log into planks. The horse chopping block machine works so i will use that instead.

## Logs

* Client/Server Log:No crash
* Crash Log: No crash

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0.25
* Launcher Used: Twitch

* Memory Allocated: 8GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No resourcepack except default one
* Optifine Installed?: No

## Server Information
* Java Version: Not found
* Operating System: Not found
* Hoster/Hosting Soultion: Boxtoplay
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?: no

**Comment by artdude543** [comment]
Dupe and already fixed for next version. Check other issues before opening them.
