### ISSUE TITLE
Issue / Bug - Total crash on loading the Betweenlands - source possibly directional value of mortar

### ISSUE THREAD

**Issue by RyoNara** [DarkPacks/SevTech-Ages#2409]
Hey,
I have suddenly crashed after entering the Betweenlands.
No indication on what might have changed, it did not crash before.

From the crash report (as follows) I would assume my mortar is causing the issue,
but I cannot say why or how.

I have so far tried to:
 - move out of the Betweenlands, but time is to short before the crash happens.
 - google the issue, but couldn't find a thing
 - disabled my ressource packs (faithful 32 and the addon one), but to no change

Any idea how to proceed?

---------------------------------------

https://pastebin.com/Z64BgPZh

**Comment by justinrusso** [comment]
There is so much missing information here that may be relevant. Please re-submit your issue following the issue template provided.

Thanks.
