### ISSUE TITLE
KUDA shaders conflict with Astral Sorcery

### ISSUE THREAD

**Issue by MrKekster** [DarkPacks/SevTech-Ages#2412]
This post most likely doesnt belong here, but figured this was the best place to post my issue (Perhaps im not alone)

 Im having issues with KUDA shaders and the astral sorcery mod specifically. I've tried searching for solutions with no luck, so figured i'd give it a try here.

In the attached picture i am wearing mantle of stars which has particles flying around it. It can be seen that "shadowy squares" will occur for the particles as if it renders it badly. This happens for all astral sorcery related particles.
![2018-05-13_17 39 04](https://user-images.githubusercontent.com/39242033/39968973-c93d584e-56d5-11e8-8612-cf3480f98f75.png)

I've seen streamers without this issue, dont know if they've already fixed it or if its a unique issue for me. Video settings for minecraft is set to "Fast" and shaders is set to "High". Everything else is default.

**Comment by justinrusso** [comment]
There are a few things you can try:

1. Adjust settings with the shaders and the game to see if it helps resolve it
2. See if the mod author would be interested in looking into it
3. See if the shader pack maker can look into it.

Unfortunately this is out of our scope though.
