### ISSUE TITLE
Pack fails to launch after update to 3.07

### ISSUE THREAD

**Issue by Trathien** [DarkPacks/SevTech-Ages#2413]
## Issue / Bug
After updating to v3.07 using Twitch launcher, pack fails to launch

## Expected Behavior
Launch?

## Steps to Reproduce (for bugs)

1. Press Play on launcher
2. wait approximately 20seconds
3. read crash log on launcher...

## Context
Updated to 3.07 with much hope of continuing to advance in anotherwise excellent pack after 100's of invested hours.  Tried delete/reinstall  of java and modpack profile (twitch launcher using updated java version) at least 2 times. spent several hours searching forums and this site for useful suggestions.

## Logs
* Launcher Log: https://pastebin.com/mnQFbfaf
* Client/Server Log: https://pastebin.com/LjA8WcGD
* Crash Log: https://pastebin.com/vNYFcrsb

## Client Information
* Modpack Version: 3.07
* Java Version: 1.8.0_161 64bit
* Launcher Used: 1.6.84

* Memory Allocated: 6912
* Server/LAN/Single Player: Singleplayer
* Resourcepack Enabled?: None (originally soartex fanver but error repeats regardless)
* Optifine Installed?: No

**Comment by artdude543** [comment]
Reboot your PC and update your drivers. This issue was caused by a broken driver released by Nvidia.
