### ISSUE TITLE
Optifine, unable to install

### ISSUE THREAD

**Issue by Spelhajen** [DarkPacks/SevTech-Ages#2415]
## Issue / Bug
 I install optidine in the ATlauncher via the "editmods" and then i launch the pack. The pack begins booting up but when the actual minecraft screen comes up it's just black unlike the normal "sevtechanimation", it goes on like that for around a minute then it crashes and goes back to the ATlauncher.

## Steps to Reproduce (for bugs)

1. install optifine as a inside minecraft jar via edit mods
2. run the game
(probably not helpful since i seem to be the only one thats having this problem)

## Context
 I am trying to launch the game with Optifine to install a Shaders later.

## Logs

* Client/Server Log:
* Crash Log:  http://paste.atlauncher.com/view/3d9bb737

## Client Information

* Modpack Version: 3.0.7
* Java Version: java 8 update 171
* Launcher Used: ATlauncher

* Memory Allocated: 4096

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?: not quite

**Comment by justinrusso** [comment]
I (and others) have been able to open fine with optifine. Optifine is not a supported mod as it causes conflicts. Your step 1 seems a bit confusing - but make sure you are taking the optifine `.jar` file and putting that right into the mods folder of the sevtech instance.

**Comment by artdude543** [comment]
Just going to add this. One more issue from yourself about the same thing. I'm banning you. I've already warned you once.
