### ISSUE TITLE
Dropping "unknown items" when logging in or changing dimensions

### ISSUE THREAD

**Issue by DamienBlack** [DarkPacks/SevTech-Ages#2417]
## Issue / Bug

When we load into the game for the first time, or when when move to a new dimension, we seem to "drop" the item in our hand. 

We'll get the message "you dropped an unfamiliar item". The highlighted slot in our hotbar will be empty and the graphic of our hand will be empty. Often, we can open our inventory, click on the slot that the item was in and it will "reappear" as normal.

If we don't notice and immediately try to "recover" the item, it seems like they sometimes disappear forever. I have not confirmed when this happens. It is possible people are accidentally swapping/dropping the invisible item.

## Possible Solution
It seems like the "unfamiliar item" check is happening before our current age progress is loaded. If the unfamiliar item check could be delayed for a little while, this may solve the issue.

## Steps to Reproduce

1. Progress past age 0
2. Place an advanced item in your hotbar
3. Make sure the item is in you "hand"
4. Use a portal/log in (happens most when you are going to an unloaded area)
5. Look for the "dropped unfamiliar item" message
6. If hand item is missing/invisible, try opening inventory and clicking on the hand slot. It may "reappear"

## Context
We have lost important items logging in and jumping between dimensions. Sometimes the are found again, sometimes they seem to disappear for good. This happens 10-20% of the time we log in or jump to a dimension. I think when the area is being loaded for the first time, it is closer to 60%.

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.6 - 3.0.7
* Java Version: Clients are using 1.9.0.171 (64 bit)
* Launcher Used: Twitch
* Memory Allocated: Server has 8gb, clients have 4gb-6gb
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: Using default?
* Operating System: Windows 10
* Hoster/Hosting Soultion: Self Hosted
* Sponge (Non-Vanilla Forge) Server?: No
* Additional Content Installed?: None

**Comment by artdude543** [comment]
This is intentional from the mod we use for staging. It won't be fixed due to how it works. But it may be better in the next major re-write from the mod. But the issue will still exist.

9/10 if you don't do anything and let it load you won't drop anything. Dark has proved this countless times on his stream when moving back and forth from the Twilight.
