### ISSUE TITLE
Cannot Load a New World

### ISSUE THREAD

**Issue by skateereer** [DarkPacks/SevTech-Ages#2418]
Hello, I submitted a report about a week ago relating to not being able to get past the launcher. I'm now able to get into the menu and start a new world, but the game crashes while trying to load the world. 

 
## Issue / Bug
Game crashes each time I try and load into a new world.

## Expected Behavior
Game should load world.

## Possible Solution
Not sure if my computer is just too weak to even run the modpack or if there is a legitimate fix for my issues. 

## Steps to Reproduce (for bugs)

1.
2.

## Context
Won't let me play the game.
[crash-2018-05-13_19.13.08-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/1999194/crash-2018-05-13_19.13.08-client.txt)

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0.171 (64 bit)
* Launcher Used: Twitch

* Memory Allocated: 5888MB

* Server/LAN/Single Player: Single
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by artdude543** [comment]
You ran out of memory when loading the modpack. (Pretty clear from the crash report) 6gb should be enough anyway. But ensure that the game is loading with the values and not other ones.

Also, try with the args here: https://pastebin.com/hWWUGGHQ

But this is not a pack issue.
