### ISSUE TITLE
3.0.7 missing most Mods in Curse Launcher

### ISSUE THREAD

**Issue by WickedBowie** [DarkPacks/SevTech-Ages#2419]
^^ title

 
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by justinrusso** [comment]
This is a twitch launcher issue, not ours. Keep trying or wait for Twitch to fix it.
