### ISSUE TITLE
SevTech 3.0.7 nutrition and advancements not populating (server)

### ISSUE THREAD

**Issue by TwoFaceFear** [DarkPacks/SevTech-Ages#2421]
## Issue / Bug
 when starting a server and entering advancements don't populate and nutrition is not displayed.

## Context

I am trying to start a playthrough with some friends on a dedicated server and none of the advancements are showing. I have messed around with the advancement command but nothing seems to set it.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version:
* Launcher Used:ATLauncher

* Memory Allocated:4gb

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion: multicraft
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?: none

**Comment by artdude543** [comment]
Looks like the server is missing pretty much all the config/mods needed. Please re-upload all files and ensure that the server takes at least 5/6 mins to boot. This will confirm it's the pack loading up.

But that fact you're not having anything showing up tells me your missing a lot of data needed.

**Comment by TwoFaceFear** [comment]
I did try re-uploading the modpack.. file zilla didn't say it missed any files either time. Are there certain files I should look for to confirm the mods don't exist? If not I can redownload and setup the server files I have then re-uploading them... Don't know if it helps, but when uploading it says there's a little over 1800 files uploaded.

**Comment by TwoFaceFear** [comment]
It correctly blocks items I'm not allowed to see/use... Just doesn't give me the goals. Also structures from mods appear to exist

**Comment by artdude543** [comment]
This an issue on your end then. Am I presuming this is a Vanilla Forge Server? I.E. Not Sponge or any of the other crap out there?

**Comment by redalpha01** [comment]
Out of curiosity, did you run the forge server installer?
I know I forgot one time and was really confused.

**Comment by artdude543** [comment]
Closing this and throwing it to support status for Discord.
