### ISSUE TITLE
I cant place the Strainer base underwater

### ISSUE THREAD

**Issue by Gurkenyoshi** [DarkPacks/SevTech-Ages#2422]
I started playing the Modpack via Twitch Launcher

## Issue / Bug
I can't place the strainer underwater, only above and therefore I can't get shark tooths and so on. 

## Expected Behavior
I just can't place it. Not even in creative mode

## Context
It bothers me because I want to get to the next age but I can't because of this bug.

**Comment by Tahakk** [comment]
At least tell us your version of the pack + if you have any mod added.

**Comment by artdude543** [comment]
See https://github.com/DarkPacks/SevTech-Ages/issues/2130#issuecomment-385255287

**Comment by Gurkenyoshi** [comment]
Thank yoooou !
