### ISSUE TITLE
Jukebox has no recipe in Age 3, but is needed for the Jukebox-Module for Viescraft

### ISSUE THREAD

**Issue by Nivrelin** [DarkPacks/SevTech-Ages#2425]
## Issue / Bug
The  Jukebox-Module for the airship is craftable in age 3, but the jukebox has no recipe.

## Expected Behavior
Being able to craft the jukebox

## Possible Solution
Either give the jukebox a recipe in age 3 or move the jukebox-module to a later age.

## Steps to Reproduce (for bugs)

1. Check Recipe for Jukebox-Module
2. Check Recipe for Jukebox
3. Be sad.

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_171-b11
* Launcher Used: Twitch Launcher

* Memory Allocated: 6144M

* Server/LAN/Single Player:  Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: 1.8.0.171-b11
* Operating System: Debian
* Hoster/Hosting Soultion: hosted Rootserver@Netcup
* Sponge (Non-Vanilla Forge) Server?: Nope

* Additional Content Installed?: Nope

**Comment by KonoTyran** [comment]
This is not just age 3, even in age 5/creative there is still no recipe for making the jukebox.
