### ISSUE TITLE
Better With Mods Manual Broken

### ISSUE THREAD

**Issue by Therandus93** [DarkPacks/SevTech-Ages#2426]
## Issue / Bug
Better With Mods Manual Broken
![2018-05-14](https://user-images.githubusercontent.com/14925108/39993382-91b3eb20-576d-11e8-84e2-a0671ede7262.png)
Happened after last update.

## Expected Behavior
Normal Manual should be present. 

## Possible Solution
file accidentally moved so it cant find it, or misnamed?

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_161
* Launcher Used: Jar launcher

* Memory Allocated: 8192

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: Yes

**Comment by artdude543** [comment]
Not our issue please report to the mod repo. You can use the online docs however as linked in the book.

**Comment by Therandus93** [comment]
would like to point out it is your issue, this version of the mod has the docs in the located folder, however in your version in the modpack the files are missing, i have put them in manually. But it doesnt change the fact, the betterwithmods jar file you are using has its files in the "docs" folder missing.
