### ISSUE TITLE
Immersive Engineering Core Sample Drill does not store Energy

### ISSUE THREAD

**Issue by silverwyrm** [DarkPacks/SevTech-Ages#2430]
## Issue / Bug

Not sure if this is a bug or a feature, but the Immersive Engineering Core Sample Drill has an internal Energy buffer of 8000 flux, but does not store this Energy when broken, leading to wasted power generation resources.

## Expected Behavior

The Immersive Engineering Portable Generator, for instance, stores Energy when broken. I expected the Core Sample Drill to behave similarly.

## Possible Solution

Allow the Core Sample Drill to store Energy

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by artdude543** [comment]
This is an intended for the drill. Has been for ages now.
