### ISSUE TITLE
Suggestion - Cotton > String should yield 3 string instead of 1

### ISSUE THREAD

**Issue by silverwyrm** [DarkPacks/SevTech-Ages#2431]
## Issue / Bug

I'm not sure if this is intended or not, but the Cotton > String recipe yields only 1 string. This makes cotton farming almost worthless due to the extremely low yield.

## Possible Solution

Increasing the recipe yield to 3 string seems like it would put cotton more in line with the cost / yield of other crops / products.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by artdude543** [comment]
We've added support to the IE Garden in 3.0.8 and you can use the Loom to make 2 to 1 so I'm going to close this one. Based on the fix to IE and that the Loom is a MM machine you can make in higher stages to help make it more efficient.
