### ISSUE TITLE
Opening the game just opens vanilla MC

### ISSUE THREAD

**Issue by konkonsoy** [DarkPacks/SevTech-Ages#2438]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by artdude543** [comment]
Not even going to bother helping you with this one. Make a new issue filling in **all** the required information. Like I dunno the client info?
