### ISSUE TITLE
3.0.6 Server Crash after Ore is mined by player and 1000 xp drops

### ISSUE THREAD

**Issue by Maatschunat** [DarkPacks/SevTech-Ages#2439]
## Issue / Bug
https://www.pic-upload.de/view-35325912/2018-05-02.png.html

- Players mines ore (Geolysys most of the time) and 1000 Xp orbs are spawning and killing the server because of too many entities. Server comes back player mines block again. Next server Crash. But after some times the ore isnt spawning the orbs. Or the server can handle the Orbs and i got over 450 levels.
- Only with no silk touch when xp should be dropped

## Expected Behavior
- Spawn the Xp orbs like in the config 
## Possible Solution
- First workaround but no fix is to set xp from ore to 0

## Steps to Reproduce (for bugs)

1. Hard to Reproduce becaus of randome ore block is doing it.
2. after 1000 Ore blocks i thing 1 block must do it

## Logs

* Client/Server Log: Will ask Stuff for it
* Crash Log: Will ask Stuff for it

## Client Information

* Modpack Version: 3.0.6
* Java Version: latest 8
* Launcher Used: Twitch

* Memory Allocated: 8,5 GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: NO
* Optifine Installed?: NO

## Server Information
* Java Version: ask Stuff
* Operating System: ask Stuff
* Hoster/Hosting Soultion: ask Stuff
* Sponge (Non-Vanilla Forge) Server?: ask Stuff

* Additional Content Installed?:

**Comment by artdude543** [comment]
You need to add the server information. As your saying it's a server issue. No data = no support.

**Comment by Maatschunat** [comment]
Will follow...

**Comment by Jandakast** [comment]
Is that a full Bronze hammer?

**Comment by Maatschunat** [comment]
yes it is. 2 Bronze Plates and wood Stick. But happened also with Bronze Pick from Tinkers.
