### ISSUE TITLE
Can't ascend blocks between 0.5 and 0.6 meters.

### ISSUE THREAD

**Issue by ButerBreaGrieneTsiis** [DarkPacks/SevTech-Ages#2440]
## Issue / Bug
After eating the Apple of Lofty Stature the ability to step up a full block has gone, but also has the ability to step up anything between 0.5 and 0.6 meters. This includes walking from a grass path up to a slab, or walking on a stair made with Chisel and Bits.

## Expected Behavior
If all is well, you should be able to walk up to any block that is lower than 0.6 meters.

## Possible Solution
I have no clue. Maybe something with the configs? Haven't found anything.

## Steps to Reproduce (for bugs)
1. Eat the Apple of Lofty Stature if step assist is still on.

2. Right click dirt/grass with a shovel to make a grass path. 
3. On the block adjacent to the grass path, place a slab.
4. Try to walk up.  
OR  
2. Make stairs out of 1/2 chisel and bits blocks.
3. Try to walk up.

## Context
I want to make walkable paths (with wooden slabs) and for design purposes, I made stairs in various buildings with chisel and bits. I could also use 1/4 blocks for stairs, but that's not a reason to not have this fixed.

## Logs
This doesn't require logs.

## Client Information

* Modpack Version: 3.0.7
* Java Version: Java 8 Update 172
* Launcher Used: MultiMC
* Memory Allocated: 8GB
* Resourcepack Enabled?: Yeah
* Optifine Installed?: Yeah

* Additional Content Installed?: 
Extended Days 0.24-20 (+ SilentLib 2.2.18-100)
ClassicCombat 1.0.0
Optifine HD U 12

**Comment by Jandakast** [comment]
https://github.com/PrinceOfAmber/Cyclic/issues/810

**Comment by artdude543** [comment]
Fixed for 3.0.8
