### ISSUE TITLE
Unavailable Forge 

### ISSUE THREAD

**Issue by Tixit363** [DarkPacks/SevTech-Ages#2443]
So, I was really excited to get this mod pack, and play it. Installed it on Twitch App, With a fresh minecraft and everything, and It keeps saying that Forge is unavailable. Prompting "LAUNCH FAILED : This version you are trying to play inherits properties from an unknown version"

Anyone have any idea how to fix this?

**Comment by artdude543** [comment]
This is an issue with Twitch you'll have to wait for them to fix it. Alt would be to use the ATLauncher.
