### ISSUE TITLE
unable to craft and remove rubber from a symorite/weedwood bucket

### ISSUE THREAD

**Issue by greatmonkey** [DarkPacks/SevTech-Ages#2445]
## Issue / Bug

The Symorite and Weedwood bucket is not showing up in JEI and you cannot craft it even if you do know the recipes.  If you do have some buckets, you can have them get rubber and even cook them to turn the rubber hard but unable to remove it from the bucket as there is no crafting recipe for it. 

## Expected Behavior

unable to craft Symorite and Weedwood buckets

be able to craft the buckets
## Steps to Reproduce (for bugs)

1. search JEI for Symorite or Weedwood buckets or try to craft it

## Context

I am trying to complete The betweenlands and am trying to make potions.

I did re-download the pack on a new profile and the same problem is happening

## Logs

no logs for this, but can do an image
https://i.imgur.com/nfIR92h.png

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:3.0.7
* Java Version:1.8.0.161 
* Launcher Used:twichApp

* Memory Allocated:8.5GBs

* Server/LAN/Single Player:Single player
* Resourcepack Enabled?:default
* Optifine Installed?:no
On my main profile/file i did add aromabackup-mod but as I am still having the same issue in a new profile/world without the mod, that is not effecting it.

**Comment by Jandakast** [comment]
This has been fixed in 3.0.8. 

You should still be able to craft the buckets using weedwood planks and reed rope, or syrmorite ingots and reed rope 

![image](https://user-images.githubusercontent.com/19498789/40034273-3ef0183e-57ca-11e8-95bb-12cedc05a76b.png)
