### ISSUE TITLE
[Stage 3] Missing Mixer Recipe Rice Flour to Rice Dough

### ISSUE THREAD

**Issue by iffonox** [DarkPacks/SevTech-Ages#2447]
Unlike similar items (Dough, Wet Tanned Leather, Pulp, ...) Rice Flour doesn't have a Mixer recipe to turn it into Rice Dough in stage three.

## Client Information
* Modpack Version: 3.0.7
* Java Version: Java 8 update 161 64bit
* Launcher Used: jar laucher via Twitch app with cpw's java arguments from reddit
* Memory Allocated: 6 GB
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Jandakast** [comment]
recipe added in 3.0.8 :)
