### ISSUE TITLE
Server stage tutorial needed

### ISSUE THREAD

**Issue by ryncoca** [DarkPacks/SevTech-Ages#2448]
## Issue / Bug
I made a private server to play with my friend, he joined in first, and he can play the game regularly. But when I joined, anything I pick up is an "unfamiliar item". In TMI mod, it says that I need stage tutorial to learn the items.

## Steps to Reproduce (for bugs)

1.
2.

## Context
I can't play the game with my friend at all.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version: newest
* Launcher Used: twitch

* Memory Allocated: 5G

* Server/LAN/Single Player: server
* Resourcepack Enabled?: nope
* Optifine Installed?: nope

## Server Information
* Java Version: newest
* Operating System: windows 10
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?: no

* Additional Content Installed?:

**Comment by artdude543** [comment]
You did not set the server up right then. When you join you'll automatically get given the stage. Make sure you uploaded **all** files, especially the mods/config folders. Then try again.

This is an issue on your side and not the packs.

If your playing as a team using `Together Forever` run `/tf forcesync` to make sure you have all the advancements from the other players.

**Comment by Sir-Will** [comment]
I'm having the same issue, which mod does add the tutorial stage to the player?
