### ISSUE TITLE
Prismarine dupe

### ISSUE THREAD

**Issue by iffonox** [DarkPacks/SevTech-Ages#2450]
Prismarine can be duped by using a Chisel and the Uncrafting Table.

## Steps to Reproduce (for bugs)
1. Get a Block of Prismarine
2. Chisel the block into Prismarine Bricks or Dark Prismarine
3. Uncraft the Prismarine Bricks Block into nine Prismarine Shards
4. Craft two Prismarine Blocks using four Prismarine Shards each
5. goto 2

## Client Information
* Modpack Version: 3.0.7
* Java Version: Java 8 update 161 64bit
* Launcher Used: jar laucher via Twitch app with cpw's java arguments from reddit
* Memory Allocated: 6 GB
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by lawl281** [comment]
That uses a large amount of experience.  It does have a cost
