### ISSUE TITLE
Game closes with unexpected error within 30 mins of playing.

### ISSUE THREAD

**Issue by nixxo84** [DarkPacks/SevTech-Ages#2453]
## Issue / Bug

I recently had issues of the game not starting proper. I did a clean install as recommended. Added my backed up world into the clean save. I was then able to finally get back into the game. Was playing fine for a good 20 minutes and the game just crashed. I don't recall exactly what I was doing but something to do with Immersive Engineering.

I started up the client again, continued playing as normal, within 30 minutes the exact same thing happened. I gave up for a few hours then decided to try again, figured it was just bad luck with random crashes. I threw in optifine before loading the client this time. I was assembling my jackpump from Immersive Engineering, was about 20 minutes into this round of playtime and the game just closes out of no where with the Minecraft launcher saying Unexpected Error. There is no option to view crash log or anything.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log: https://gist.github.com/nixxo84/884913c6ba660002087e23b9009cc0c1
* Crash Log: Not sure where this is. The above is what I found in the "latest" file in the logs folder. I hope that's correct.

## Client Information

* Modpack Version: 3.0.7
* Java Version: Java 8 171/Java 8 171(64-bit): Both versions are 8.0.1710.11
Not sure how to tell which one my Minecraft is using.
* Launcher Used: Twitch Desktop App
 
* Memory Allocated: 8192 Mb

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: Most recently yes, but the problem was happening before I installed Optifine.

If it helps, additional PC info: Windows 7 Home Premium, Intel i5-4590 3.30Ghz, Nvidia GTX 960 (Driver version: 24.21.13.9764

**Comment by artdude543** [comment]
Thank you for reporting an issue!

It appears you are logging an issue for a crash, but you have either not uploaded to PasteBin/Gist etc.. of the actual crash report. This report contains the needed data to help to locate the cause and a possible fix. To find the file needed please review the following for either of the launchers.

## Twitch
1. Select the SevTech Pack to view the modpack page.
2. Click the `...` button on the top right just next to `Get More Content`.
3. Click `Open Folder`.
4. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it. 

## ATLauncher
1. Select the Instances tab, then scroll to the instance of SevTech.
2. Click the bottom right button named `Open Folder`
3. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it.

For any other launcher should be a similar process, if not consult with Google if you are not sure on how to find the folder. The information contained in these reports is critical for getting the crash fixed/looked into.

## Servers
For servers the process if farilt simple. Go the folder cotaining all the sever files/folder and you will see a folder called `crash-reports` follow the same process as above by getting the lastest one and uploading it to a text store.
