### ISSUE TITLE
Suggestion / Enchancement: Aluminium and Platinum in Mekanism

### ISSUE THREAD

**Issue by UncertifiedDevice** [DarkPacks/SevTech-Ages#2455]
## Issue / Bug
Aluminium and Platinum cannot be processed with Mekanism machines.

## Possible Solution
Somehow implementing custom items and custom recepies with mek machines or adding JAOPCA and restricting it with staging. I tried adding JAOPCA and launching my offline test world but adding the mod seems to have broken the level.dat, probably because of conflicting ids. After creating a new world though I could process the geolosys aluminium ore chunks in a chemical injection chamber and in a purification chamber just fine.

## Expected Behavior
Mekanism doesn't feature any recepies for aluminium or platinum natively but many packs before had JAOPCA so that mek could still be used to process modded ores it doesn't support natively.

## Context
I can't process my aluminium with the rest of my ores :(

## Client Information
* Modpack Version: 3.0.7
* Java Version: jre1.8.0_162
* Launcher Used: MultiMC, imported from twitch
* Memory Allocated: 10G
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes
* Optifine Installed?: Yes

## Server Information
* Java Version: 1.8.0_171-b11
* Operating System: Ubuntu 16.04.4 LTS
* Hoster/Hosting Soultion: OVH
* Sponge (Non-Vanilla Forge) Server?: Forge

**Comment by UncertifiedDevice** [comment]
Nickel is also affected by this

**Comment by Jandakast** [comment]
We added the OreMatic 5000 in 3 tiers to allow you to 3x, 4x, and 5x process all of the ores outside of Mekanism. We currently do not have a way to create custom gasses for Mekanism and the mod you mentioned breaks existing worlds. We are hopefully getting the ability to create custom gasses for soon but until then the Orematic 5000 is the solution.

**Comment by UncertifiedDevice** [comment]
If JAOPCA is not an option and there's no way to change ids it may still be worth contacting the developer on how to add custom gases. As well as shards and clumps for all the ores the mod also adds the slurry, clean slurry and the crystals for each of the ores it adds support for.

**Comment by thiakil** [comment]
It is indeed possible to add gasses, but requires Java code at the moment. Though I know Skysom was working on adding it to ContentTweaker recently.

**Comment by artdude543** [comment]
Recipes for both Platinum & Aluminium have had recipes changed and forced in the direction we want with the pack.

There are now enough methods to handle processing of these ores. We are not going to add support for the whole slurry deal. The OreMatic is the machine in replacement for the mods where support lacks. Also gives the player some benefits when using it.
