### ISSUE TITLE
[Crash] Ticking World Exception

### ISSUE THREAD

**Issue by Nagshell** [DarkPacks/SevTech-Ages#2456]
## Issue / Bug
I'm getting ticking world exceptions that crash me to desktop after entering Hunting Dimension.
Looking at crash log it appears it has something to do with dirt slabs.

## Steps to Reproduce (for bugs)
Location: Hunting Dimension
Situation: world gen + several spread out tiki torches and three totemic totems applying buffs
Action:  Even standing still crashed me after some time, but not instantly.

## Context
I wanted to make mob farm in Hunting Dimension, so I lighted up area and started clearing terrain around portal.

## Logs
* Client/Server Log: latest.log is too big for pastebin, what do I do?
* Crash Log: https://pastebin.com/HFfs9FeK

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0.171 (64-bit)
* Launcher Used: Twitch
* Memory Allocated: 6144 MB

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No
* Modpack changes: None, except turning mobGriefing off.

**Comment by artdude543** [comment]
Fixed in next update.
