### ISSUE TITLE
Too many graphical mods

### ISSUE THREAD

**Issue by HaDaShAtWiTh** [DarkPacks/SevTech-Ages#2457]
My frame rate is roughly 5-30fps... are all the graphics mods really necessary? 
If not could pls provide a list of the disposable graphical mods. Thank you.

**Comment by Squ1zzl3** [comment]
https://i.imgur.com/uCwFeV1.png

**Comment by ByteTemplar** [comment]
You can disable at least Better Foliage, Fancy Block Particles and Smooth Font mods, those are pure cosmetic mods.
