### ISSUE TITLE
Can not open my world after first start or reload...it stops at 0%   3.0.7

### ISSUE THREAD

**Issue by Coltphyton** [DarkPacks/SevTech-Ages#2458]
## Steps to Reproduce (for bugs)

1.Start launcher
2.loading screen
3.done!
4.Select world
5.loading
6.freeze...(don`t load longer)

At first time crating a world , it works.But when i create an other one or I try to open the other world again , it will not open it or create it... :(
## Context
Im sad becouse i want to play it with friends and i rlly like this pack....i tryed everything....i searched many reports  with the same topic here.I tryed to toggle mods off and on and change settings....nothing work.

## Logs

* Client/Server Log: /
* Crash Log:https://gist.github.com/Coltphyton/7d8d606219af7b308b381dfc5d13b586

## Client Information

* Modpack Version:3.0.7
* Java Version: 10 1.8.0_171
* Launcher Used:Curse (twitch) AtLauncher too

* Memory Allocated:6GB

* Server/LAN/Single Player:Single Player
* Resourcepack Enabled?:No
* Optifine Installed?:No

**Comment by artdude543** [comment]
Thank you for reporting an issue!

It appears you are logging an issue for a crash, but you have either not uploaded to PasteBin/Gist etc.. of the actual crash report. This report contains the needed data to help to locate the cause and a possible fix. To find the file needed please review the following for either of the launchers.

## Twitch
1. Select the SevTech Pack to view the modpack page.
2. Click the `...` button on the top right just next to `Get More Content`.
3. Click `Open Folder`.
4. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it. 

## ATLauncher
1. Select the Instances tab, then scroll to the instance of SevTech.
2. Click the bottom right button named `Open Folder`
3. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it.

For any other launcher should be a similar process, if not consult with Google if you are not sure on how to find the folder. The information contained in these reports is critical for getting the crash fixed/looked into.

## Servers
For servers the process if farilt simple. Go the folder cotaining all the sever files/folder and you will see a folder called `crash-reports` follow the same process as above by getting the lastest one and uploading it to a text store.
