### ISSUE TITLE
3.0.7 Blood Magic Sigil of Elemental Affinity Java I/O error.

### ISSUE THREAD

**Issue by Codock** [DarkPacks/SevTech-Ages#2462]
## Issue / Bug

Age 4, created a Sigil of Elemental affinity and put it in the Sigil of holding. Right clicked to activate and immediately had an internal Error. This was 5/10/18. All other players on server are able to log in just fine but ever time I attempt to log in I get "Internal Exception: java.io.IOExceptin: An existing connection was forcibly closed by the remote host."
I had the server admin do a pack update to 3,0.7 and was able to log in long enough to pull the Sigil of Elemental Affinity out of the Sigil of holding and took a step to go trashcan it and got the internal Error again and am no back to unable to logon.

No crash log generated on my end

## Possible Solution

Going to attempt to have the admin intercept my login with a /kill to see if that works. All else fails I'll see if we can edit my player save to remove the sigil.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:3.0.6 and 3.0.7 
* Java Version:8.171
* Launcher Used:Twitch

* Memory Allocated:7Gigs

* Server/LAN/Single Player:Server
* Resourcepack Enabled?: None that I know of unless the pack came with one active.
* Optifine Installed?:No

## Server Information
Server Information not available to me at this time.
* Java Version: 
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by artdude543** [comment]
Okay closing this one as it's missing all the needed data. Once you have all the information/logs etc.. then please make a new issue. We can't help without that critical information.

The logs will be server side in this case.
