### ISSUE TITLE
Game locked up, forcing a PC restart - save corrupted, crashes game on save selection

### ISSUE THREAD

**Issue by WebMaka** [DarkPacks/SevTech-Ages#2463]
I was playing happily, minding my own business, when the game stopped. I thought it was lag, but it hung the PC so hard that a hard reset didn't even work and I had to power-cycle the PC. Upon relaunching, Minecraft makes it to the main menu but attempting to start or load a singleplayer session crashes the game. (Click "singleplayer" button, see dirt texture for a moment, boom, drops back to launcher.)

This machine doesn't generally hang, and certainly not so hard that I have to power-cycle it. The modpack, however, I've noticed does lag hard for 5-10 seconds on occasion.

Looking over the crash log, it looks to me like the save was hosed by the unexpected lockup, and when the game tries to load the save there's an array that's misallocating and eating up the heap.

I am rather unhappy to not see any obvious backup mechanisms in place, and hopefully just overlooked something.

Crash log was posted to : https://pastebin.com/icmpwGQ7

Environment details:

* Modpack Version: 3.0.7 (fresh install - only two days old)
* Java Version: Tried with JRE8 u161 and u171 64-bit
* Launcher Used: Stock - Twitch 7.5.6702.487, native Minecraft 2.0.1049
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single
* Resourcepack Enabled?: No/stock
* Optifine Installed?: No. Stock pack, no added mods.

**Comment by artdude543** [comment]
The crash log is fairly easy `java.lang.OutOfMemoryError: Java heap space`

Try adding these args to the game to see if that helps: https://pastebin.com/hWWUGGHQ

In regards to backup we are iffy about adding one by default as some users like it and others don't that and Curse does not allow optional mods. So when that is a thing we shall add one as optional. Otherwise your free to install your own.

**Comment by WebMaka** [comment]
Looks like the command-line switches did the trick. Once it had enough heap space to load everything, it worked. Might I recommend adding that to the readme?

As for the backup issue. For what little it's worth I would recommend forcing the use of one and let people that don't like having a backup mechanism disable it with a config file edit. Opt-out of automaic backups instead of opt-in. My reason for this position is the fact that Minecraft has historically been inherently unstable with large modpacks and the last thing anyone would want with a progression game is to irrecoverably lose all progress because MS decided to crap the bed.
