### ISSUE TITLE
Astral Sorcery Celestial Gateway Yellow Star Icon Not Showing

### ISSUE THREAD

**Issue by KCtops100** [DarkPacks/SevTech-Ages#2466]
## Issue / Bug

Astral Sorcery Celestial Gateway not working between Overworld and Moon.  The yellow star does not appear.

## Expected Behavior

Instead of a yellow star appearing, one does not appear.

## Steps to Reproduce (for bugs)

1.  Simply launch the game and attempt to teleport to the moon via Celestial Gateway.
2.

## Context

I was attempting to teleport via the Celestial Gateway instead of using a rocket.

## Logs

* Client/Server Log:
* Crash Log: No crash

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0.171 64 bit
* Launcher Used:  Native Launcher

* Memory Allocated: 6 GB

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Yes
* Optifine Installed?: Yes

**Comment by Jandakast** [comment]
I can do this just fine, have you tried without Optifine?
If you go to the moon is it still fully formed?
Sometimes after a pack restart/server restart the Planets/Moons/Space Stations chunkloaders don't start to work until you visit the dimension to "wake" them up.

**Comment by KCtops100** [comment]
Thank you for responding!  With the Optifine mod disabled and after reloading the game, there is still no yellow icon.  If it helps, the version of Optifine is HD_U_C9.

**Comment by Darkbq** [comment]
@Jandakast as you locked #1803, I'm leaving it here. I'm not a mod developer, but played somehow with   @BluSunrize IM code and get a way to at least set Assembler recipe stages working globally. Also, I have some idea how to make it take in care owner's stage. Can we get somehow in touch or it was not a good thing to edit mod code?

**Comment by artdude543** [comment]
Hello!

This appears to be an older issue on an old version of the modpack. This issue may have been fixed in later versions of the modpack, so we recommend that you update! If however, you are still having the same issue.

Please re-file an issue following the template and provide as much detail as you can. 

Thanks in advance and thank you for playing SevTech Ages!
