### ISSUE TITLE
Crashing on load up 

### ISSUE THREAD

**Issue by JoltDragon** [DarkPacks/SevTech-Ages#2467]
I just recently saw videos on this mod pack so I wanted to try it out But when I try to load it up on the new launcher its says "the version you are trying to play inherits properties from an unknown version" so i tried it on the java version and while it does start loading it will get to 2/7 done when loading the mods and right when its about to get to 3/7 it crashes here is the crash report.
[crash-2018-05-15_17.43.44-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/2007070/crash-2018-05-15_17.43.44-client.txt)
I used to play skyfactory 3 and tried loading that up and it works fine so I'm not to sure how to fix this.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
