### ISSUE TITLE
crashing when loading mods.

### ISSUE THREAD

**Issue by JoltDragon** [DarkPacks/SevTech-Ages#2468]
## Issue / Bug

I tried launching the game on native and it keeps saying "The version you are trying to play inherits properties from an unknown version" so I tried to java and while it does load it will get to 2/7 mods loaded and right when its about to finish and get to 3/7 it crashes.

## Possible Solution

Not sure have uninstalled reinstalled minecraft and the mod pack but same thing keeps happening.  
## Steps to Reproduce (for bugs)

1.
2.

## Context

I'm just trying to get the game to load all the mods or at least launch the game (native).
## Logs

* Client/Server Log:
* Crash Log:https://pastebin.com/3eZdu3ed

## Client Information

* Modpack Version:3.0.7
* Java Version:1.12.2 or release forge- 14.23.3.2679 not sure if the forge version matters.
* Launcher Used: java and native

* Memory Allocated:5120m

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by artdude543** [comment]
You're missing a key mod from the load up. Specifically CC Lib.

You can download the mod again from [CF yourself](https://minecraft.curseforge.com/projects/codechicken-lib-1-8/files/2558563) to fix this issue. Also if you have your modpack instance on OneDrive or Dropbox just don't. It's not supported and leads to issues like this.
