### ISSUE TITLE
Migrate Content Tweaker Molten Fiery to Twilight Forest Molten Fiery

### ISSUE THREAD

**Issue by Jandakast** [DarkPacks/SevTech-Ages#2472]
- [x] Remove melting recipes for Content Tweaker molten fiery
- [x] Add casting recipe for Content Tweaker Fiery Gear/Plate/Rod from Twilight Forest Molten Fiery
- [ ] Add tooltip to Content Tweaker Molten Fiery stating it's `Depreciated`

**Comment by justinrusso** [comment]
@artdude543 were you able to figure out how to change the name of the liquid?

**Comment by Jandakast** [comment]
Tooltips on fluids don't seem to work so it's been added to the change log and marked important.
