### ISSUE TITLE
Unfired Porcelain Issue is back [3.0.7]

### ISSUE THREAD

**Issue by Thornbrier** [DarkPacks/SevTech-Ages#2473]
The problem where updating the pack breaks the Unfired Porcelain recipe is back. I didn't know about this bug until I updated to 3.0.7 just after getting to Age 1 and suddenly I can't finish my basin without cheating in one more Porcelain brick. The millstone is only seeing the bonemeal and giving me white dye powder. I looked through all the closed Issues but done of them had a solution other than 'update to the latest version' but that's what caused this issue for me and I really don't want to have to start over a whole new world yet again over something like this.

**Comment by artdude543** [comment]
The recipe was changed in the Millstone (3.0.7) please refer to JEI.
