### ISSUE TITLE
Hostile mob spawning issues

### ISSUE THREAD

**Issue by Iorce** [DarkPacks/SevTech-Ages#2475]
## Issue / Bug

In general, hostile mobs seem to quite rare, except for the Hunting Dimension and the Abyssal Wastelands. Usually that would only be a minor problem, however, once you want to progress in AbyssalCraft, specifically the Dreadlands, things get tricky.

Searching far and wide for hours only led me to a couple Dreadguards and Dreadlings/Dread Spawns, the latter supposedly spawning very commonly in Dread Forests.

The currently only "reasonable" method of farming the Dread Fragments required to upgrade the Necronomicon is to make a Potion of Dread Plague and infect yourself to then infect the mobs in the Abyssal Wastelands (which is currently the Dimension with the highest mob density by far (and even there it feels like there should be more mobs) to be getting roughly 1-2 Dread Fragments per minute (with a Looting I sword) while also being constantly affected by the Dread Plague in order to spread it to other mobs. 

## Expected Behavior

Definitly more Dreadlings/Dread Spawns in Dread Forests in the Dreadlands, maybe more Dreadguards, maybe less Abyssalnite Golems.

## Possible Solution

Increasing the values of the spawn settings serverside.

## Steps to Reproduce (for bugs)

1. Get into the Dreadlands (Asorah's Dreaded Gateway Key, use it once in the Overworld to get into the Abyssal Wastelands, once again there to get into the Dreadlands)
2. Search for Dreadlings/Dread Spawns in a Dread Forest
(Search for Dreadguards in the Dreadland Mountains)

## Context

Wanted to progress through Abyssalcraft. Need 72 Dread Fragments for the next Necronomicon level.

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0.161
* Launcher Used: Twitch App

* Memory Allocated: 6400MB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: no
* Optifine Installed?: no

## Server Information
* Java Version: unknown
* Operating System: unkown
* Hoster/Hosting Soultion: unknown
* Sponge (Non-Vanilla Forge) Server?: no

* Additional Content Installed?: no

**Comment by artdude543** [comment]
Update to 3.0.7 this pretty much solves 80% of your issue. It's also an RNG issue. You need to explore/grind to progress in some sections. Or even hanging out in biomes/places for a while.
