### ISSUE TITLE
Graves&Betweenland bug or feature?

### ISSUE THREAD

**Issue by warlock1984** [DarkPacks/SevTech-Ages#2476]
For this experiment you need few things:

1. Lurker pouch and/or amulet from Betweenlands.
![amulet](https://user-images.githubusercontent.com/24734687/40118447-40c2d290-591a-11e8-93ad-fe2f5874c766.png)
2. Equip them from in game equipment menu. (default key is ``C`` )
![menu](https://user-images.githubusercontent.com/24734687/40118884-6cabce06-591b-11e8-96a0-a3e2c5c0f764.png)
2b. Icon of items will appear right of item bar 
![pozicija](https://user-images.githubusercontent.com/24734687/40118981-bd9fed1a-591b-11e8-8a26-32fe726cb59e.png)
3. Now DIE!!!!!!! Muhahahahah                in game of course.
4. Grave will spawn BUT all equip items will be out  not in grave 
![smrt](https://user-images.githubusercontent.com/24734687/40119188-45c0109e-591c-11e8-8a06-fdf4e69c5199.png)

Try to ask Betweenlands dev to add tab like galactic craft to make grave see items or ask Grave dev to try to capture items from Betweenlands.

**Comment by justinrusso** [comment]
Included in https://github.com/M4thG33k/TombManyGraves2/issues/34

**Comment by vadis365** [comment]
This isn't a Betweenlands issue, iirc the items dropped are part of the living drops event.
Tomb Many Graves needs to handle this.

**Comment by Renari** [comment]
It appears support was added for this in Betweenlands 3.3.9?

https://github.com/Angry-Pixel/The-Betweenlands/issues/608

It seems the pack currently includes Betweenlands 3.3.8.

**Comment by justinrusso** [comment]
@Renari As I've stated in my reply to the TombManyGraves2 comment, adding this support requires updating TombManyGraves2 to a newer version which breaks all existing graves. This will not be happening.

**Comment by monodemono** [comment]
TombManyGraves has been replaced with Corail Tombstone, which fixes this issue.
