### ISSUE TITLE
[3.0.7] Getting electrocuted by phantom (broken) IE wires.

### ISSUE THREAD

**Issue by dalsio** [DarkPacks/SevTech-Ages#2484]
## Issue / Bug
Occasionally, and I can't seem to pin down exactly why, I will take wire damage (and often die) from an IE wire I just recently broke. The wire can still exist long after it has been broken (and killed me many times). I'm 100% sure the wires are not there, since they drop into my inventory and no power is transferred through them. I'm also quite some distance from any other wires. I did some testing and it seems to happen consistently when I break the HV connector (and wire) to my Distillation Tower (tried it on a pumpjack and everything behaved normally). The wire drops on the boiler below and where it used to be is an invisible HV-power electrocution zone. The space the connector used to occupy is unaffected. It also happened with LV wires and connectors once, but I don't have any logs from then nor do I know for sure what I did to cause it. Forcing a block update on the empty space where the connector used to be does not fix the issue, but reloading the game does.

## Possible Solution
It may be due to a lack of a block update somewhere, or a latency spike (framerate drop, what have you) causing it to not realize it was broken. Might also be specific to Immersive Tech (the LV wire problem I had was while fiddling with Advanced Coke ovens though I don't know if it was directly caused by them).

## Steps to Reproduce (for bugs)
I don't know for sure how many scenarios this works but I will explain in detail what caused it recently, and then what is consistent for me:

1. Die to a live HV power line dangling quite low and close to both an immersive tech boiler and the distillation tower it is connected to
2. try and grab my stuff from under it, but die in the process
3. die a few more times
4. decide to break the connector of the wire attached to the distillation tower without tools
5. connector breaks and disappears (does not drop), the HV wire drops onto the ground
6. Attempt to grab stuff again, get killed by the wire I just broke
7. Remember that I can grab a block of dirt and use it to block the wire and make it drop
8. Do so for another wire that was kind of (but not really) close thinking that's what killed me
9. Wire breaks and drops onto the ground
10. Try to get stuff and get killed in the same spot by the wire I broke the first time.

or what is consistent for me:

1. Build an IT Distillation tower right next to a tank full of diesel and a boiler and connect them all with pipes
2. Connect the tower with a HV connector and wire and feed HV power into them.
3. Break the connector using either no tool or a pickaxe (I used a TC pickaxe)
4. Attempt to move in the space once occupied by the wire

 
## Context
It's very frustrating because if I died too close to it I can basically never get my items back without either beefing up my health and chancing a brute force, crafting another Faraday suit, or reloading the game.

## Logs
1. https://gist.github.com/dalsio/5046d570720fe01178be1267769bac16
2. https://gist.github.com/dalsio/1751338a03cfab193dbbe720f1f10c63
3. https://gist.github.com/dalsio/db150aa426c864a3449d123345d418d3

## Client Information
* Modpack Version: 3.0.7
* Java Version: 1.8.0.171
* Launcher Used: Twitch, modified to use the latest java
* Memory Allocated: 4gb
* Server/LAN/Single Player: Single
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
Can you report this in the IE tracker and link back to this issue. As it's purely an IE issue.

**Comment by dalsio** [comment]
Done: [Immersive Engineering Issue \#3000](https://github.com/BluSunrize/ImmersiveEngineering/issues/3000)

**Comment by artdude543** [comment]
Has been resolved in the mod being updated. 3.0.8 contains the fix likewise 3.1.0 when it lands. Will tag as 3.1.0 however.
