### ISSUE TITLE
Cyclic Standard Exchange Sceptre Drops Wrong Block

### ISSUE THREAD

**Issue by thatguyfrai** [DarkPacks/SevTech-Ages#2485]
## Issue / Bug
When using the Cyclic Exchange Sceptres on blocks that are hidden until another stage is unlocked, the hidden block is returned. Examples include obsidian (and its chiseled variants) dropping basalt (and its chiseled variants) or fences returning planks.

## Expected Behavior
Exchanging blocks should yield the original block.

## Possible Solution
May be an issue with how Cyclic's Sceptre works. The behavior seems like it could be acting as a fake player when breaking blocks.

## Steps to Reproduce (for bugs)
Obsidian/Basalt Example:
1. Advance gamestage to Age 3
2. Find/ Place obsidian
3. Use Cyclic Exchange Sceptre ( either one) and replace obsidian with any block
4. Basalt (or a chiseled variant) should now be in your inventory

## Context
Had little impact on my game due to discovering it on obsidian and suffering from an overabundance of it. Further testing on other blocks was performed on common/low-cost blocks. Others may try to use it on more important/rare blocks, however.

[Log](https://drive.google.com/file/d/125Rk_BJQ9QjLzLKbfQ_S0US7d78j1yMK/view?usp=sharing)

## Client Information
* Modpack Version: 3.0.7
* Java Version: 1.8.0.101
* Launcher Used: Twitch
* Memory Allocated: 8gb

**Comment by PrinceOfAmber** [comment]
For clarification:
in lower stages, obsidian is hidden using gamestages to instead appear to be basalt.

So a player advances to later stage (three maybe) until obsidian appears as its honest obsidian self.

Then use the exchange scepter on it, but it drops the gamestages replicant (basalt).

Is this correct?  Basically the tool does not "pass the player context" however you want to put it into the breaking of the block?
