### ISSUE TITLE
[3.0.7] Venus corrosive atmosphere + extraplanets pressure damage way overtuned?

### ISSUE THREAD

**Issue by faraday326** [DarkPacks/SevTech-Ages#2487]
## Issue / Bug
I didn't test older versions but this seemed to get much worse in 3.0.7 (maybe related to radiation mechanic being disabled?)

Because of ExtraPlanets pressure damage, you mostly have to wear a space suit on Venus. The corrosive damage tears the space suit to shreds incredibly quickly. The item to stop the corrosive damage is on venus. The same story is true on Saturn and beyond. Jupiter, for example, has low pressure, so you can get away without a space suit and it's relatively easy to tank the pressure damage. 

Space suits last, based on my timing, 100 seconds on Venus (which is a suspiciously round number) without the shield controller. By the time your lander hits the ground on your first trip, you'll be close to 50% durability, already. Related: all tiers of space suit seem to last the same amount of time.

## Expected Behavior
A more reasonable amount of time?

## Possible Solution
Up the durability? Lower the corrosive? Lower the pressure penalty of venus so you don't need a suit? Make the shield controller craftable or put it somewhere else?

## Steps to Reproduce (for bugs)
1. Cheat in a tier 2 spacesuit (and some oxygen)
2. Blast off for Venus.
3. When you land, look at the durability of your space suit. It goes to about 50% durability by the time you hit the ground.

Additionally: you can also cheat in different tiers of space suit and watch them all decay at the same rate, too. 

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by DmitriySalnikov** [comment]
In fact, there is one way to get around this without cheating, but before that you just need to think. With this method, I took my first shield controller. 
Hint: You can repair armor without removing it.

**Comment by technolem** [comment]
Just get the meat feeder from industrial forgoing and use a jetpack + disposable armor. The feeder will out heal pressure damage, the jetpack wont take corrosion damage, and some armor like obsidian armor has a ton of durability/protection for it's price. Or equip a focus sash and grind out Environmental Tech for Resistance V and Regen V to be immortal.

By default Galacticraft doesn't even need armor and it's intended that you use cheap/no armor to find the shield. Extra planets should be well aware of how corrosion works in Galacticraft, so I can only assume this is intentionally difficult to do. The reward is really nice and even seems to prevent baubles like the cyclic ones from taking any durability damage. But it does make things more tedious than they really need to be.

**Comment by MJRLegends** [comment]
SevTech Dev Team: Please make as reported to mod dev as im going to fix this :D Thanks :P

**Comment by faraday326** [comment]
I was able to progress by tanking the damage similar to the suggestions above. I used armara attunement perks, jetpack, crystal obsidian pants, an actually additions adv. regen ring, and a stack of hearty stew.

**Comment by MJRLegends** [comment]
ExtraPlanets Update has been released to fix this @artdude543
