### ISSUE TITLE
Able to place normal torches on the moon by right-clicking with pickaxe/hammer

### ISSUE THREAD

**Issue by Stifling-Bossness** [DarkPacks/SevTech-Ages#2490]
## Issue / Bug
Normal torches are able to be placed on the moon, as long you don't select them on your hotbar.
https://imgur.com/a/L9uID5e

## Expected Behavior
Torches to not work on the moon

## Possible Solution
Have them go out immediately after being placed instead of being marked "unplacable" when selected on the hotbar?

## Steps to Reproduce (for bugs)
1. Get a tinkers' construct tool, such as a hammer or pickaxe (I didn't test it with other tools)
2. Put the torches on your hotbar
3. Go to the moon (other planets will probably work, but I haven't been able to go to anything other than the moon yet)
4. Select the tool in your hotbar (NOT the torches)
5. Right-click to place the torches and see they're acting like normal torches.

## Context
I noticed this when I right clicked the wall of a cave out of habit, and it actually placed a torch. I was kinda surprised, and I'm pretty sure this isn't supposed to work.

## Logs
* Client/Server Log: https://gist.github.com/Stifling-Bossness/2821b58768c571be7c3421e219bcb6e7

## Client Information
* Modpack Version: 3.0.7
* Java Version: 1.8.172
* Launcher Used: Twitch 7.5.6702.487
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Yes, 32x Faithful Modded Edition
* Optifine Installed?: No

**Comment by Stifling-Bossness** [comment]
Still occurring in 3.0.8

**Comment by monodemono** [comment]
Fixed with 237b9cd
