### ISSUE TITLE
Excavate enchantment only obtainable at Age 5 as Moon Dungeon loot

### ISSUE THREAD

**Issue by UncertifiedDevice** [DarkPacks/SevTech-Ages#2491]
## Issue / Bug
The Excavate enchantment seems to be completely unobtainable. In the source code of Ore Excavation Integration it looks like some enchantability parameters are set but right at the end of the same file that sets these parameters the Excavate enchant is registered as a treasure enchantment which means that the only way to obtain it is through villager trades or dungeon loot. I'm not 100% on this but there is a function named isTreasureEnchantment that just returns true.
**EDIT:** (old title: "Excavate enchantment unobtainable?") Turns out you can obtain this enchantment on an enchanted book in Moon Dungeons, inaccessible before Age 5.

## Possible Solution
Villager trades are customized and dungeon loot doesn't spawn anywhere but the Twilight forest. Even so the TF generates loot based on tables hard-coded into the mod so you can't find it on a steeleaf pickaxe. A solution to this would be to add a custom villager trade, amadron trade or a crafting recepie (i.e. 5x5 out of excavate modifiers in advanced crafting table gives Excavate V book)

## Client Information
* Modpack Version: 3.0.7
* Java Version: jre1.8.0_162
* Launcher Used: MultiMC, imported from twitch
* Memory Allocated: 10G
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes
* Optifine Installed?: Yes

## Server Information
* Java Version: 1.8.0_171-b11
* Operating System: Ubuntu 16.04.4 LTS
* Hoster/Hosting Soultion: OVH
* Sponge (Non-Vanilla Forge) Server?: Forge

**Comment by Stifling-Bossness** [comment]
Came in here to say, I've found some excavate books in moon dungeons

**Comment by UncertifiedDevice** [comment]
Just went through a couple moon dungeons and my third dungeon had an Excavate I book. 
I suppose this works for me for the mean time, at this point this issue is more of a suggestion / enchancement given that by the time you go to the moon you're at age 5 and excavate modifiers can be made at early age 3. I'll edit the title and add an edit to the Issue / Bug section to reflect this.

**Comment by VallenFrostweaver** [comment]
I'm in Stage 2 and got Excavate V on a Knightly Axe in the Knight's forest boss chest. Don't lose hope. ;)
