### ISSUE TITLE
Game doesn´t starts anytime

### ISSUE THREAD

**Issue by TheHorro** [DarkPacks/SevTech-Ages#2495]
I play start and it crashes
[SevTech crash-report.txt](https://github.com/DarkPacks/SevTech-Ages/files/2014355/SevTech.crash-report.txt)
Idk what I have to do pls help

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
