### ISSUE TITLE
Server seems to not load mods.

### ISSUE THREAD

**Issue by Tori1157** [DarkPacks/SevTech-Ages#2497]
## Issue / Bug
Server seems to not load the mods, giving errors left and right.

## Expected Behavior
That the server is launched.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)

1. Launching the forge.jar
2. Then immediately launch the start.bat

## Context
I want to play this modpack with my friends.

## Logs

* Client/Server Log:
https://pastebin.com/wQg6UZM9
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_171
* Launcher Used: Twitch App

* Memory Allocated: Default (1gb-4gb(?))

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: 1.8.0_171
* Operating System: Windows 10
* Hoster/Hosting Soultion: Local
* Sponge (Non-Vanilla Forge) Server?: No

* Additional Content Installed?: No

**Comment by Tori1157** [comment]
Aight, thanks.

**Comment by Tori1157** [comment]
I'm using those files, i increased the ram usage, but it's still giving the same errors.

For the record you're supposed to start the forge.jar file then press the start.bat file right after right? 

I also tried doing only the batfile and it only opens a windows the immediately closes.

**Comment by artdude543** [comment]
Then you're doing something wrong. The setting values work out of the box fine. (As it's tested) you must not have enough RAM on the system to run a server. _Note: That RAM has to be clear as Java will allocate all the memory given_ If you don't have it, it will still boot and then freeze out.

**Comment by Tori1157** [comment]
I have 32gb of ram, 8 being used, and i allocated 10gb, so it can't be the RAM.

Again am i supposed to run the forge.jar file then immediately run the bat file?

**Comment by artdude543** [comment]
As stated in the README for the download.

````
To get your server up and running just run the following:

- Windows:
	- Run Install.bat
- Linux:
	- Run Install.sh

To start the server you can perform the following:

- Windows:
	- Double Click the Forge Jar. (Or)
	- Run the Start.bat Script.
- Linux:
	- Run the Start.sh Script.

**Comment by Tori1157** [comment]
```To start the server you can perform the following:

- Windows:
	- Double Click the Forge Jar.
	- Run the Start.bat Script.
- Linux:
	- Run the Start.sh Script.```

The "Or" part was not there.

However i found the issue, i remember MC needing a specific java (Windows Offline (64-bit)) installed that, and boom working.

Thanks for all the help.
