### ISSUE TITLE
Friends cant join server

### ISSUE THREAD

**Issue by Midlo98** [DarkPacks/SevTech-Ages#2499]
Created a private server, i used the executable jar file to launch the server, both my friend and i can join, but we dont have any advancements. So i switched to the .bat file to start the server and everything was there, but my friend can no longer join.

 
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: Sevtech 3.0.7
* Java Version:
* Launcher Used: Twitch app

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion: hamachi
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by artdude543** [comment]
**All the information needs filling in**

_Canned Response_

Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
