### ISSUE TITLE
Chunkloading issue causing game to crash after Age 1

### ISSUE THREAD

**Issue by peacherine** [DarkPacks/SevTech-Ages#2501]
## Issue / Bug
(Singleplayer) World suddenly stops loading chunks and allowing blocks to be broken or commands/hotkeys to be used. Areas that have been loaded previously become inaccessible. 

When I reached Age 1 and went to look for coal, the chunks beyond it stopped loading and any blocks that were broken dropped nothing. I'm unable to load beyond the roughly 8x8 chunk square I'm in when it happens, and it is always in the same area. I re-created the map (as well as a fresh world) with the same seed and it happened both times. While in Creative I could fly around to the chunk and everything loaded normally but the moment I reached the same area it broke again. When I try to save and exit the game crashes. 

## Expected Behavior
I just want to mine things!

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
World seed 3822593286363813618, all other options default with allow cheats on. I'm not sure how to give the exact area that is affected because I didn't reach the coordinates stage.

## Logs
https://gist.github.com/peacherine/7e6c609b7b55ab663aae02d9a9403de1

## Client Information

* Modpack Version: 3.0.7
* Java Version: v8u144
* Launcher Used: Twitch

* Memory Allocated: 4GB

* Server/LAN/Single Player: Single
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Espergium** [comment]
It sounds like the tickrate was shot. No ticks = world pauses until catching up.

I do notice that your log says you're running java v8_25. This means you're using the MC launcher native!
Do this: Add -version:1.8+ to the twitch settings. Arrow on upper right near login > settings > minecraft > Advanced: Additional java settings box.

Try running again with this parameter and it should pick the newer java. See if this happens after the fact.

**Comment by peacherine** [comment]
I tried that and the BuildCraft warning went away but unfortunately the same thing happened.

**Comment by Espergium** [comment]
Not sure if this issue could be used in relation to this, but try moving the minecraft instance out of the documents folder.
I've had a person or two experience erratic behavior of their client until they moved the instance out.
