### ISSUE TITLE
Unable to charge Tier 1 Space Suit in Age 4

### ISSUE THREAD

**Issue by thedoo** [DarkPacks/SevTech-Ages#2503]
## Issue / Bug

There seems to be no way to charge a Tier 1 Space Suit in Age 4. I tried the every charger block/item I could think of. A previous issue: #2324, showed that you can only use a Galacticraft Energy Storage Module to charge the suit. You can't craft that in Age 4.

## Expected Behavior

Be able to charge the suit in Age 4 since you need it to advance.

## Possible Solution

Allow the Galacticraft Energy Storage Module to be crafted in Age 4

## Steps to Reproduce (for bugs)

1. Craft the Tier 1 Space Suit, has no charge
2. Attempt to charge with various blocks, unable to

## Context

I can't advance to Age 5 because I can't get to the Moon. I can't get to the Moon without the Space Suit. I can't use the Space Suit without being able to charge it. I can't charge it with blocks in Age 4.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_171
* Launcher Used: MultiMC

* Memory Allocated: 6GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: 1.8.0_111
* Operating System: Linux
* Hoster/Hosting Soultion: Akliz
* Sponge (Non-Vanilla Forge) Server?: No

* Additional Content Installed?: No

**Comment by Stifling-Bossness** [comment]
As a temporary workaround until this is fixed, you can use the aevitas attunement perk to have your armor get repaired while you're wearing it. It works on the space suit, and should even keep your charged up while you're on the moon. It won't work with the oxygen tanks, though, so make sure to take plenty!

**Comment by pjc21** [comment]
Another option is a few simple script modifications to allow the Energy Storage Module to be crafted in Age 4.
In \scripts\staging\item_and_recipes\05_five\items.zs 
& \scripts\staging\item_and_recipes\05_five\recipe.set.zs
- cut lines 
```
<galacticraftcore:battery:100>,
<galacticraftcore:battery>,
<galacticraftcore:machine_tiered>,
```

and paste into \scripts\staging\item_and_recipes\04_four\items.zs 
& \scripts\staging\item_and_recipes\04_four\recipe.set.zs
