### ISSUE TITLE
Water invisible while in weedwood rowboat

### ISSUE THREAD

**Issue by TheMingo888** [DarkPacks/SevTech-Ages#2506]
## Issue / Bug

While in 3rd person POV in the weedwood rowboat, (swamp) water is invisible and the blocks beneath it render as if they were dry. (NB: this issue does not occur in the 1st person POV.)

Screenshot: https://imgur.com/4H4Qst3

## Expected Behavior

Water remains visible at all times in all points of view.

## Possible Solution

Unknown, but switching to first person allows it to function normally.

## Steps to Reproduce (for bugs)

1. Visit The Betweenlands (for myself, during Age 2)
2. Place a Weedwood Rowboat in swamp water
3. Right click to enter the rowboat
4. Press F5 if not already in the 3rd person point of view

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_161-b12
* Launcher Used: Twitch

* Memory Allocated: 7 GB

* Server/LAN/Single Player: Single
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
Can you report this on the mod own tracker please?

**Comment by TheMingo888** [comment]
Angry-Pixel/The-Betweenlands#568

**Comment by artdude543** [comment]
This will be fixed in the next pack update.
