### ISSUE TITLE
Items showing in NEI but not craftable

### ISSUE THREAD

**Issue by Nefar1on** [DarkPacks/SevTech-Ages#2508]
I noticed that the _**(Immersive Craft)**_ **Chest**, _**(Progression Tweaks)**_ **Fire Pit** and the _**(Progression Tweaks)**_ **Flat Bread** are available in the Tutorial stage, but not craftable until Age 0, you should probably make that invisible until after you make the Work Stump.

**Comment by justinrusso** [comment]
The only one valid here is the Flat bread. The rest of them are able to be crafted in tutorial...
