### ISSUE TITLE
Eagle Dance Wont work

### ISSUE THREAD

**Issue by Lucky119** [DarkPacks/SevTech-Ages#2509]
## Context
 I have 2 rattles and 2 flutes, 4 drums and still cant get the bar high enough for the eagle dance. The rattles stop working and the flutes only make it go up very slowly.
 No matter what I do I cant get it to work. I have 3 chimes with it as well, I don't know why it isn't working, ive looked at plenty of videos and they seem to do fine with it.

**Comment by justinrusso** [comment]
There are a few instruments you are not using, and players are able to do this just fine on 3.0.7.

**Comment by fowlerhk** [comment]
I've also been trying the Eagle Dance ceremony for days without ever finishing it!
I have been using 9 drums, a flute (in off-hand), rattle, jingle dress and 2 wind chimes. What else can I do?
I've also constantly failed to complete the Serenade of Syrinx to upgrade the flute (using the same instruments as above).
