### ISSUE TITLE
Server Crash : Tick Loop @ buildcraft

### ISSUE THREAD

**Issue by JIrgend** [DarkPacks/SevTech-Ages#2511]
We were in the mid age 4 when we tryed to automate immersive engineerings cokeovens with buildcraft. But something went wrong, and the server and the same world in sp crashes. The modpack is in the vanilla version:

https://pastebin.com/wu045Axy

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
