### ISSUE TITLE
Creative Tank (Dupe?) bug

### ISSUE THREAD

**Issue by PasoLeaute** [DarkPacks/SevTech-Ages#2513]
## Issue / Bug
You can craft the lower level Mekanism tanks into a Creative Tank - for free.

So, just got my creative tank today and was playing around with various liquids, using the empty grid crafting recipe to empty it out and swap liquids.  I had the thought to check if that same thing worked on the lower level Mekanism tanks to empty them, and low and behold it does, except it will give you a creative tank instead of the same level tank you used!  I tried it with all levels of tanks (Basic to Ultimate).  Works with all of them, regardless if they have fluid in them or not.

Don't know if it works that way 'before' I crafted my first tank the long way, but if so man that's a hell of a shortcut . . . 

## Expected Behavior
Either you can't empty a lower level Mekanism tank by putting it in a crafting grid, or when you do it gives you back the same level tank as you put in.

## Steps to Reproduce (for bugs)
1. Make Basic Mekanism Tank
2. Put in crafting grid by itself
3. Receive your free creative tank

## Client Information
* Modpack Version: 3.0.7
* Java Version:  1.8.0.161
* Launcher Used: Twitch - Jar Launcher
* Memory Allocated: 6 GB
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information - Don't know any of this but I'll bug Voxel if you need it.
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by Stifling-Bossness** [comment]
Can confirm, placing a basic mekanism tank into crafting table provides a creative tank.
https://imgur.com/a/Olg7MU1
