### ISSUE TITLE
Kepler22b Stone Inferium/Prosperity Ore

### ISSUE THREAD

**Issue by ChipmunkCraft** [DarkPacks/SevTech-Ages#2514]
## Issue / Bug
#525 shows that stone inferium and prosperity ore being created for Kepler22b; however, I have quarried and searched for both of these on Kepler22b in a very large area and have found none.

## Expected Behavior
Are these 2 ores supposed to be generated on Kepler22b? If so, then it appears they are not generating.

## Steps to Reproduce (for bugs)

1. Go to Kepler22b
2. Try to locate Stone Inferium and Prosperity Ore

## Client Information

* Modpack Version: 3.0.7
* Java Version: v8 161
* Launcher Used: Twitch
* Memory Allocated: 8Gb
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Faithful x32
* Optifine Installed?: Yes

**Comment by Jandakast** [comment]
So the issue with this that we currently have no way to actually add the custom ore blocks to the world gen for Kepler 22b. Looking into crating a recipe for these that uses the Kepler 22b stone to still require traveling there for the ores.
