### ISSUE TITLE
Can't saw leaves into sticks despite having a recipe to do so

### ISSUE THREAD

**Issue by monodemono** [DarkPacks/SevTech-Ages#2516]
## Issue / Bug
There's a recipe in JEI to saw leaves into sticks.

<img width="1920" alt="screen shot 2018-05-18 at 17 17 41" src="https://user-images.githubusercontent.com/1161277/40262842-fba37730-5abf-11e8-8718-01a4c43212d7.png">

But it doesn't actually work.

<img width="1920" alt="screen shot 2018-05-18 at 17 18 00" src="https://user-images.githubusercontent.com/1161277/40262851-096fe380-5ac0-11e8-92f8-90d0599943c3.png">

And here's proof that the saw is working (note the particle effects above it).

<img width="1920" alt="screen shot 2018-05-18 at 17 17 54" src="https://user-images.githubusercontent.com/1161277/40262855-1fec892e-5ac0-11e8-99fa-65684ebd5184.png">

Also I've cut a ton of wood on it, it's definitely functional.

## Expected Behavior
According to the recipe, the leaves block should be consumed, and it should drop 2 sticks.

## Steps to Reproduce (for bugs)
1. Shear some leaves.
2. Put leaves against a saw.

## Context
I need a lot of sticks for a tall ladder to lead up to my astral sorcery workshop, and I figured I might as well saw some leaves since it should be a guaranteed 2:1 recipe for sticks.

## Client Information
* Modpack Version: 3.0.7

**Comment by justinrusso** [comment]
#2483
