### ISSUE TITLE
No tabs in advancements

### ISSUE THREAD

**Issue by Darkfable98** [DarkPacks/SevTech-Ages#2517]
I beat baykok but I dont have any advancements for the next stage. is this a bug or am I missing something?

**Comment by justinrusso** [comment]
Baykok is not the final advancement to get to the next stage. That is a "side quest"

**Comment by Darkfable98** [comment]
i have completed every advancement. how do i get to the next stage?

**Comment by timmit99** [comment]
There should be a line of quests that are purple. Complete all of those and then you should unlock the next stage.
