### ISSUE TITLE
Engineer's Hammer duplication

### ISSUE THREAD

**Issue by silverwyrm** [DarkPacks/SevTech-Ages#2519]
## Issue / Bug

When placing two Engineer's Hammer in a crafting grid, yield is 1 undamaged hammer. The original hammers are not consumed, but damaged.

## Expected Behavior

I assume expected behavior is for the original hammers to be consumed.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by Tahakk** [comment]
wow, what a nice filled template you got there

**Comment by silverwyrm** [comment]
@Tahakk I didn't think any further information was necessary. If there's anything that would be helpful to add let me know!

**Comment by Tahakk** [comment]
All of these information in template are inportant, that's why they are in template. 
If you think Mod version is not important for example...

**Comment by malte0811** [comment]
BluSunrize/ImmersiveEngineering#2990

**Comment by artdude543** [comment]
Will be fixed in 3.1.0 😄
