### ISSUE TITLE
Not possible to craft from primal cores stone types walls pillars etc (Age2)

### ISSUE THREAD

**Issue by Deloraze** [DarkPacks/SevTech-Ages#2520]
Age 2. Primal core stone derived (like sarsen stone pillars) are listed in jei but they are impossible to craft 

* Modpack Version: 3.0.7
* Java Version:
* Launcher Used:
* Memory Allocated: 4 Gb
* Server/LAN/Single Player: single player
* Resourcepack Enabled?: No
* Optifine Installed?:yes

**Comment by artdude543** [comment]
Duplicate of #1672
