### ISSUE TITLE
Chiseled colored glass crashes the game.

### ISSUE THREAD

**Issue by ginkoopl** [DarkPacks/SevTech-Ages#2521]
## Issue / Bug
The chiseled, colored glass blocks crash the game.

## Expected Behavior
I expect the game not to crash while chiseling blocks.

## Steps to Reproduce (for bugs)
1. Place light gray glass block on the ground.
2. Keep clicking it with the chisel.
3. ???
4. Profit.

## Context
It crashed my game. I've tried it on light gray and gray glass blocks, the game crashes when I hit the "clear glass" dyed glass block with the chisel. Not sure if normal glass crashes.

## Logs

* Crash Log:  [crash report](https://pastebin.com/Ghdfd6AD)

## Client Information
* Modpack Version: 3.0.7
* Java Version: Latest, idk, probably doesn't matter
* Launcher Used: Titan minecraft launcher 3.7.0
* Memory Allocated: 4 Gb

**Comment by Jandakast** [comment]
I am unable to reproduce this in dev. I have tried chiseling all stained glass variants using the Iron, Diamond, and iChisel in all modes.

**Comment by Jandakast** [comment]
Just got the crash when chiseling rapidly through the variants.

**Comment by ginkoopl** [comment]
I should probably add that I used tinkers chisel.

**Comment by artdude543** [comment]
Fix included in the next update :)
