### ISSUE TITLE
Age2: impossible to craft oblivion catalyst from abyssalcraft

### ISSUE THREAD

**Issue by Deloraze** [DarkPacks/SevTech-Ages#2522]
Age2. Trying to craft an oblivion catalyst. Altar correctly set up (worked for previous ritual) and necronomicon full (5000 PE). Put the items required in the correct location, shift right click with the necronomicon on the altar (central pedestal) but nothing happens

* Modpack Version: 3.0.7
* Java Version:
* Launcher Used: 

* Memory Allocated: 4Gb
* Resourcepack Enabled?: No
* Optifine Installed?: Yes

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by Stifling-Bossness** [comment]
#2376
