### ISSUE TITLE
Darklands Broken

### ISSUE THREAD

**Issue by MrBrettimus** [DarkPacks/SevTech-Ages#2523]
Currently playing v 3.0.7 and cant get any shodow creatures to spawn in Darklands, ive been to about 10 or so different darklands and havent seen a single shadow beast, ended up just spawning in crystals to advance out of age 0

**Comment by Degonsky** [comment]
Check undergrounds of Darklands biome. Spawn rate of all mobs quite low, and sometimes mobs get stuck underground and eat up the whole spawn limit

(Also you can try kill command /kill @e[type=!player,r=X] ; X - radius)

**Comment by artdude543** [comment]
It's intended to be low and forces you to explore world top and bottom.
