### ISSUE TITLE
stuck on age 1

### ISSUE THREAD

**Issue by Lyk89** [DarkPacks/SevTech-Ages#2524]
I have made all achievement in stage 1 also final - LINK TO STARS, but nothing happens, age 2 doesnt unlock
 
## Issue / Bug
stage wont unlock

## Expected Behavior
All achievement done in age 1

## Client Information

    Java Version:1.8
    Operating System:win 10
    Hoster/Hosting Soultion:sever
    Sponge (Non-Vanilla Forge) Server?:no

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by gabeux** [comment]
Had the same issue on 3.0.8. For a quick fix try restarting the server and client, and redoing the ritual. 
There are ways to put the server into a weird braindead state when dealing with some Abyssalcraft blocks - in my case someone put a Bronze Axe in a pedestal, and that crashed me and the person out of the server. 
After a couple minutes we could connect and play, but some stuff was behaving oddly.

Weird glitch, so just better to workaround.

**Comment by zuoanqh** [comment]
I have the same issue. I finished every achievement required in age 1 (including luminous crafting table) but can't enter age 2. Please reopen this issue, the OP's report is quite clear -- what more do you expect?

**Comment by Tahakk** [comment]
They expect him to fill out the template that is provided. At last you can use this command to move you to age 2 if it was not changed
`/advancement grant playerName only stage2`

**Comment by zuoanqh** [comment]
Thanks, I'll ask our admins to try that. I would argue the purpose of a template is to solve problems. it is therefore against the purpose (and make one sounds like an emotionless machine) to ask for someone to follow the template when they already provided the details needed to solve the problem. I mean you could just ask if there's something you need to know.
