### ISSUE TITLE
Ancestral infuser crafting isn't working fully

### ISSUE THREAD

**Issue by Psyvana** [DarkPacks/SevTech-Ages#2525]
## Issue / Bug

Followed instructions from book of single (better with mods & addons guide), also referred to https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/wip-mods/1440917-1-2-5-japanese-weapons-and-architecture-v0-4-3#Infuser

In a test world I have cleared an area around the infuser, spammed a load of ancestral spirits on the soul sand block below and it still will not light up. It was set to night also, so definitely below light level 7 as i had no light sources nearby. I have tried throwing the ancestral spirit bottles until I was in a veritable cluster F of red orbs. Still no joy. 

## Expected Behavior

In the right conditions the infuser is supposed to light up red and be able to craft. Throwing seeds on top does work as expected, it's the the crafting gui that isn't working.

## Possible Solution
Provide alternate crafting recipe for japanese culture items

## Context

As the throwable recipe's worked, I was able to create bamboo, but because of the crafting recipe, I was unable to access the ability to do anything with it, ie use the soaking unit. I just wanted to build pretty things :(

## Client Information

Tested on multiplayer server and singleplayer.
* Modpack Version: 3.0.7
* Java Version: 1.8.0_171-b11
* Launcher Used: Twitch
* Memory Allocated: 6gb
* Resourcepack Enabled?: Faithful 32, though my pack doesn't texture the infuser by the looks.
* Optifine Installed?: No

**Comment by gcaliber** [comment]
I built and used to make drying and soaking units just a couple of days ago. I had to put it inside an unlit building, I think night time light is too bright.

**Comment by Psyvana** [comment]
I have tested below light level 7 under cover and outside.

**Comment by gcaliber** [comment]
What are you trying to craft, are you sure you have the correct recipe?
