### ISSUE TITLE
Vanilla/Cyclic Block dispenser can't place sidings/mouldings/corners and just deletes them instead

### ISSUE THREAD

**Issue by Kiyaku** [DarkPacks/SevTech-Ages#2538]
## Issue / Bug
Putting sidings/mouldings/corners into a cyclic or vanilla block dispenser and powering it does neither place nor spit out the item, it just deletes it. 
Video of example: https://streamable.com/pm746

## Expected Behavior
Sidings/Mouldings/Corners should be placed in the world, or spit out as an item if not possible. 

## Steps to Reproduce (for bugs)
Place any of the above mentioned blocks into a cyclic or vanilla dispenser and give it a redstone signal. 

## Context
Was going to automate the Better With Mods saw, using those dispensers.

## Client Information
* Modpack Version: 3.0.7

## Server Information
* Sponge (Non-Vanilla Forge) Server?: No

**Comment by Jandakast** [comment]
Reported to mod  https://github.com/BetterWithMods/BetterWithMods/issues/938

**Comment by primetoxinz** [comment]
To put the information where it is more relevant.
Quark and Cyclic block placers do not properly attempt to place the itemstack through its ItemBlock, instead trying to get the IBlockState through ways that are incorrect. This causes special implementations such as mini blocks not called the proper code and thus placing wrong.

**Comment by Jandakast** [comment]
Blackliisted the blocks from Quark but still have the issue with Cyclic block placer. Reported to that mods issue tracker as well. https://github.com/PrinceOfAmber/Cyclic/issues/812

**Comment by artdude543** [comment]
The Cyclic side is fixed for 3.0.8 but this won't be fixed for Vanilla. And we've disabled the usage in the Quark ones.

**Comment by primetoxinz** [comment]
Know this is closed but want to clarify, the vanilla dispenser can only place blocks because of Quark, so you fixed the bug by disabling it in Quark
