### ISSUE TITLE
Totem ceremony broken/unresponsive

### ISSUE THREAD

**Issue by Tipperty** [DarkPacks/SevTech-Ages#2540]
## Issue / Bug

The music progress's bar slows or stops completely on eagle or buffalo dance
## Expected Behavior

That it continues to the end and completes the ceremony
## Steps to Reproduce (for bugs)

1. pick ideally eagle or buffalo dance and complete
2. 

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version: 8.0.1610.12 64-bit
* Launcher Used: Twitch app
 5
* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?: no
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by Pokefenn** [comment]
Each instrument can only do a certain amount towards a ceremony. Read the book fully, as it gives a full explanation in detail.

**Comment by Jandakast** [comment]
As @Pokefenn mentioned, if the bar slows or stops increasing then you need to use a mix of unique instruments.

**Comment by Tipperty** [comment]
I used all the instruments. I had 4 wind chimes 5 drums, I had the flute in my shield slot and the rattle in my main hand. I tried clicking them I  a rythum and spamming them, but still the bar gets to about 90% and doesn't move on the Eagle dance. On the buffalo it is hit or miss I can spam the drums over and over some times it completes 1 in 4 times
