### ISSUE TITLE
Singleplayer save not loading, not sure what issues are occurring.

### ISSUE THREAD

**Issue by E-hellman** [DarkPacks/SevTech-Ages#2541]
I'm not sure what the issue is, or what kind of logs can help clarify the issue. 
I have played a single played game for a few hours, but now when I go to load the game, there is no game to load. It appears as if there was no save file created, as there is no backup .zip file anywhere, or any save folders available. 

I'm not sure what the issue is, or how to replicate it.

**Comment by Jandakast** [comment]
When submitting an issue please fill in all information that the Template asks for. It is there to help us help you. However, this particular issue isn't an issue with the pack it is an issue with your computer or your install location.

Check to make sure your Minecraft instance is not saved in a OneDrive, DropBox, or other similar cloud synced location
Make sure you have free space on the drive that your Minecraft instance is saved to
