### ISSUE TITLE
Modpack crashes on load

### ISSUE THREAD

**Issue by GamerPandaBear** [DarkPacks/SevTech-Ages#2542]
## Issue / Bug

The modpack crashes while loading in. (the blue dude loading)

## Expected Behavior
 
The modpack loads and I can play.

## Possible Solution

All I can deduce from this is that there is something wrong with Content Tweeaker. What though?

## Steps to Reproduce (for bugs)

1. Start the modpack
 (that's it. The crash happens somwhere midway through the loading)

## Context

The modpack is not installed on OneDrive. I have tried restarting my pc.

## Logs

This is the few lines Minecraft throws at me when it crashes
* The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ContentTweaker (contenttweaker)

* Crash Log: https://pastebin.com/gZUK2e4T

## Client Information

* Modpack Version: 3.0.7
* Java Version: 8 (build 1.8.0_171-b11)
* Launcher Used: Twitch

* Memory Allocated: 6144mb

* Server/LAN/Single Player: 0
* Resourcepack Enabled?: 0
* Optifine Installed?: 0

**Comment by GamerPandaBear** [comment]
@ByteTemplar Actually, could you help me?
I don't know how to change the java version without also changing the launcher tpye.
It also states that it's using the latest version of java. (Sorry for repeating myself)

**Comment by ByteTemplar** [comment]
I dont use Twitch client, its awful application. I did find this instruction just by googling:
https://www.reddit.com/r/feedthebeast/comments/80nhie/twitch_launcher_forcing_old_java_versions_on_you/

Maybe you can figure it out, there looks like to be quite nice guide.

I use MultiMC, with standalone Java, I will never install that either to my computer, basically big security hole tbh...

**Comment by artdude543** [comment]
Java is out of date you can follow this guide for [Twitch](https://docs.google.com/document/d/e/2PACX-1vR5muyi1m7Zy_qSwrzeb9e3tbbRlksguNUb_Pvm3pn9eDpsIkUj5qQUq6WFPPdEoVWZq91WvvH57KzC/pub) Also re-install the pack as one of the config files has become corrupt causing the crash.

**Comment by GamerPandaBear** [comment]
Both of you sent me a guide to a thing I tried already. I will just transfer to MultiMC, as it appears superior. Thank you for your help.
