### ISSUE TITLE
Together forever mod not allowing others to complete advancements

### ISSUE THREAD

**Issue by Crumpet1** [DarkPacks/SevTech-Ages#2546]
Hello, I have recently joined a sevtech server with a few friends and i invited them to my together forever 'party' this is good but only i can complete the advancements. It will not let anyone else complete them. i was worndering if there is a way to fix this or if it is a bug.
Thanks in advance
-Crumpet

**Comment by artdude543** [comment]
Use the `/tf forcesync` command. This is not a bug if you complete more when others are offline they would normally sync on join. But a force is needed sometimes. Also if you are using LAN it's not supported at all due to various bugs/issues with too many mods.

**Comment by Crumpet1** [comment]
Ah great it works. thanks alot!

**Comment by MokahTGS** [comment]
I don't understand how this was working before in our LAN environment and now it doesn't?  This bug makes it impossible to play in LAN.
