### ISSUE TITLE
SevTech Server Crash

### ISSUE THREAD

**Issue by JWondercats** [DarkPacks/SevTech-Ages#2548]
## Logs

Crash server txt
https://pastebin.com/tpUjRRs3

## Client Information

* Modpack Version:3.0.7
* Java Version:newest
* Launcher Used:Twitch

* Memory Allocated:6GB

* Server/LAN/Single Player:Server
* Resourcepack Enabled?:no
* Optifine Installed?:no

## Server Information
* Java Version:Java 8
* Operating System:Window 10

**Comment by Jandakast** [comment]
Do you really have 675 Fish Traps?

**Comment by JWondercats** [comment]
No i never add any fish traps

**Comment by Jandakast** [comment]
Are you able to zip up the save folder for your server and put it somewhere I can download it so I can look into this further.

**Comment by JWondercats** [comment]
There the link:
http://www.mediafire.com/file/n5lsd2cy9bkg51k/world.rar
