### ISSUE TITLE
Cannot open Single Player

### ISSUE THREAD

**Issue by Razorain56** [DarkPacks/SevTech-Ages#2549]
## Issue / Bug

When the pack loads everything works as intended but when i click on Singleplayer the pack freezes and then crashes.
## Expected Behavior

     The screen to pick a world is displayed when i click the singleplayer button.
## Possible Solution

have no idea
## Steps to Reproduce (for bugs)

1.load pack
2.click singleplayer

## Context

just want to play the pack
## Logs

* Client/Server Log:
* Crash Log:
https://pastebin.com/YssxXGYT
## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0.171
* Launcher Used: JAR Launcher

* Memory Allocated: 8,192

* Server/LAN/Single Player: single Player
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion: 
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by Jandakast** [comment]
Your crashlog states it is crashing because java is out of memory. Try removing Optifine, the shaders,  and/or increasing the amount of ram 
```
java.lang.OutOfMemoryError: Java heap space
    at java.util.ArrayList.<init>(Unknown Source)
    at com.google.common.collect.Lists.newArrayListWithCapacity(Lists.java:190)
```

**Comment by Razorain56** [comment]
Thank you!! i had to remove optifind and up the ram to 10gb
