### ISSUE TITLE
Immersive Engineering Windmill Sail cannot craft windmill

### ISSUE THREAD

**Issue by BonaireDreams** [DarkPacks/SevTech-Ages#2553]
## Issue / Bug
No recipe for Improved Windmill crafted  from Windmill Sail. I've been able to craft the Windmill Sails since Age 3, thought maybe the Improved Windmill was in age 4, but just here and its still not craftable. Can only craft the basic windmill using Windmill Blades.

## Expected Behavior
8 Windmill Sail around an ingot to produce Advanced Windmill

## Possible Solution
Not sure if still gated. If it should be available in Age 3 add recipe. If it should not be available until Age 4, remove Sail recipe from Age 3, and add windmill recipe to Age 4

## Steps to Reproduce (for bugs)

1. Craft 8 Windmill Sails using 6 Tough Fabric
2.Discover no Recipe to create the Improved Windmill that uses the sails

## Context
The Improved
 Windmill using Sails doubles the output of the Windmill using Windmill Blades.

Windmill Sail Recipe
![screenshot 32](https://user-images.githubusercontent.com/5133282/40290727-d910d3f0-5c74-11e8-82a1-a2c289224d05.jpg)

Expected Improved Windmill Recipe
![screenshot 34](https://user-images.githubusercontent.com/5133282/40290807-7cabbb42-5c75-11e8-9f6a-3a8aed30e239.jpg)

Basic Windmill
![screenshot 33](https://user-images.githubusercontent.com/5133282/40290729-db26b768-5c74-11e8-97ee-086498db923b.jpg)

**Comment by Stifling-Bossness** [comment]
You no longer craft the improved windmill, you right click the blades of an existing windmill and it will apply the sail to that blade.

**Comment by BonaireDreams** [comment]
Thanks for that!!
