### ISSUE TITLE
[3.0.7] Cyclic - Wireless Redstone Receiver disappears on break

### ISSUE THREAD

**Issue by dalsio** [DarkPacks/SevTech-Ages#2555]
## Issue / Bug
Just making a note here for anyone encountering the bug where breaking the Wireless Redstone Receiver with Tinkers tools (and maybe other tools) destroys the block instead of drops it: this is fixed in the beta version 1.15 of cyclic, and I assume the SevTech team is waiting on those versions to come out of beta (or become more stable) before updating. [Cyclic Issue \#672](https://github.com/PrinceOfAmber/Cyclic/issues/672)

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0.171
* Launcher Used: Twitch, modified

* Memory Allocated: 4gb

* Server/LAN/Single Player: Single
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Jandakast** [comment]
We are using Cyclic 1.15.3 (newest beta release on Curse) in dev and this is still an issue.

**Comment by dalsio** [comment]
Huh. Must have been a regression or an interaction with the pack (or it was only partially fixed), supposedly it was fixed in the 1.15 release. Oh well, should I expand this issue to a full entry (logs, replication method, etc)?
