### ISSUE TITLE
[3.0.7] Totemic ceremonies timeout to short?

### ISSUE THREAD

**Issue by BiZZKeryear** [DarkPacks/SevTech-Ages#2557]
## Issue
I find it very hard to complete totemic ceremonies, often running out of time while performing the more complicated ones.
(old setup: 1 flute[rarely used if at all], 1 rattle, 1 drum, 1 jingle dress, 1 wind chime
new setup: 1 flute[dual wield], 1 rattle, 1 drum, 1 jingle dress, 6 wind chimes)
While I managed in my old setup to get the spring and buffalo ceremony to work while jumping up and down and beating the drum with the rattle (but only barely), I had not a chance in my old setup to get any other ceremony performed. 
It might work when more player help but I am playing on single player.
In my new setup where I jump (to get the dress working) in front of the drum while hitting it with the rattle (to use both) and occasionally playing the flute ... I only make it barely through the "Serenade for Syrinx" ... but only if the chimes kick in.
Using every trick in the book and making it barely through can't be it.
Edit: Even then I still can't make the rain dance to work. ... even with the upgraded flute

**Comment by JWondercats** [comment]
Have more than one drum like 5

**Comment by Jandakast** [comment]
I don't think this is really an issue. It is doable in single player just might take a couple attempts to get a mix that works for you.  Multiple drums will help, I also feel that you get a lower effectiveness if you dual wield instruments.

This is something you would need to take up with the Author of Totemic, as we couldn't adjust the timeout even if we wanted to.

**Comment by BiZZKeryear** [comment]
@JWondercats How? I don't understand how more than one drum will help. Please explain. (maybe with pictures ... so that I get it)

**Comment by Jandakast** [comment]
There is no config that you or I can adjust. This is hard coded into the Mod. This also isn't a place for how to play questions. That's what the discord is for.
