### ISSUE TITLE
[3.0.6] Cooked Puffer fish from Better with Addons have no Nutritional Stats.

### ISSUE THREAD

**Issue by swestrup** [DarkPacks/SevTech-Ages#2561]
## Issue / Bug
Although Raw Puffer Fish, and Fugu Jerky both have listed Nutritional Stats, Cooked Puffer Fish does not.

## Expected Behavior
I expect Cooked Puffer Fish to show a Nutritional bonus.

## Steps to Reproduce (for bugs)
Put raw Puffer Fish in a Cauldron, to cook.

## Client Information
Still using version 3.0.6 since the Betweenlands portals broke for me in 3.0.7

**Comment by Stifling-Bossness** [comment]
This is already fixed in 3.0.7
