### ISSUE TITLE
Wopper's Can't Pull from Casting Basins.

### ISSUE THREAD

**Issue by swestrup** [DarkPacks/SevTech-Ages#2562]
## Issue / Bug
I put a wopper under a Tinker's casting basin, to semi-automate smelting metals, and found that the wopper won't pull either iron blocks or blocks of glass from the basin. I also discovered that a wopper won't accept iron blocks from a normal hopper.

Note: It may be related, or not, but a solid block of glass in a casting basin shows as an empty basin in Waila.

## Expected Behavior
I have a chain of woppers under the various casting basins and casting tables on my Tinker's smeltery, all leading to a chest. The expectation is that when an item has cooled in a casting basin, it will be pulled out, passed along, and deposited in the chest.

## Possible Solution
You may want to simply say this is normal behaviour (although some sort of documentation of that would be appreciated) since I can use normal hoppers in stage 2, and they do work as expected.

**Comment by timmit99** [comment]
Whoppers CANNOT push into another hopper they have to go directly into a chest
From the mod page [HERE](https://minecraft.curseforge.com/projects/wopper):
"It acts like a normal Hopper, the only difference being that it doesn't have an internal buffer, meaning it has no slots. This means that it can pull items from inventories above it and pick them up from the world and push those items into containers that it is pointing at. **However, it cannot be inserted into by other Hoppers meaning you cannot chain them.**"

**Comment by artdude543** [comment]
This is intentional from the mod.
