### ISSUE TITLE
[3.0.6] Age 2 - Redstone Blocks turn to Granit when Placed

### ISSUE THREAD

**Issue by swestrup** [DarkPacks/SevTech-Ages#2563]
## Issue / Bug
In Age 2, after having finally gotten some redstone in the Twilight Forest, I decided to semi-automate my smeltery using a turntable, and a redstone block, to cyclically trigger output. However, I discovered that placed Redstone turns to Granite. This was a very unpleasant surprise!

## Expected Behavior
If Redstone blocks are not yet legal/available in Age 2, I would expect them to not be creatable, or not be placeable. At least that way one hasn't lost the investment in gathering the redstone ore.

## Possible Solution
It certainly not necessary to have Redstone blocks in the world at this stage as I was able to do what I wanted with a block of granite and a lever placed on the turntable, but I would like the behaviour to be changed on placement.

## Steps to Reproduce (for bugs)
Be in Age 2. Craft a Redstone Block. Place it in the World. Be dismayed.

**Comment by Jandakast** [comment]
This is intentional to prevent access to redstone blocks that generate in some structures before doing the advancements in the Twilight Forest. It's intended to be used in crafting only until age 3.
