### ISSUE TITLE
Typo in New Issue template

### ISSUE THREAD

**Issue by mtjohnson47** [DarkPacks/SevTech-Ages#2565]
## Issue / Bug
There is a typo ("Hoster/Hosting Soultion:") in the new issue template for this github.

## Possible Solution
Fix the typo.  Soultion should be Solution.

## Steps to Reproduce (for bugs)
1. Click The Issues tab above.
2. Click New Issue

## Context
I was submitting a Bug Report when I noticed it.  I did not fix in that report as it's part of the template.

## Client Information
* Chrome Version: 66.0.3359.181

**Comment by artdude543** [comment]
You could submit a PR to fix this. Just saying ;) #welovetypos
