### ISSUE TITLE
[3.0.7] [PneumaticCraft: Repressurized] [Cosmetic] new (unexposed) Empty PCB's item count overlapped by durability bar.

### ISSUE THREAD

**Issue by dalsio** [DarkPacks/SevTech-Ages#2570]
## Issue / Bug
I don't know if this is a fixable issue and it may affect plenty of other items (I don't remember even seeing anything with a durability bar stack) but if you stack multiple 0% Empty PCBs the stack number is overlapped by the durability bar. Super insignificant and cosmetic (you still can't shove more than one in the UV light box), but I figure that on the off-chance that they aren't supposed to stack like that, I figured I'd report it anyway.

![2018-05-16_23 19 27](https://user-images.githubusercontent.com/1721589/40340333-0ce611ca-5d44-11e8-8a8d-6b840d9bb336.png)

## Expected Behavior
Either Empty PCBs can't stack or the durability bar doesn't overlap the item count.

## Possible Solution
Either make them not stack, or probably some retooling that's more trouble than it's worth. Probably a PnC issue.

## Steps to Reproduce (for bugs)
1. Get several 0% Empty PCBs
2. Stack them

## Context
Makes OCD people go nuts.

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0.171
* Launcher Used: Twitch, modified

* Memory Allocated: 4gb

* Server/LAN/Single Player: Single
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by justinrusso** [comment]
Please report this directly to the mod author https://github.com/TeamPneumatic/pnc-repressurized/issues
