### ISSUE TITLE
[3.0.7] [Better With Mods] [Recipe] Two BWM Candles have the wrong dying recipes

### ISSUE THREAD

**Issue by dalsio** [DarkPacks/SevTech-Ages#2572]
## Issue / Bug
White and orange candle dying recipes (the ones that use dye powders) use Magenta Dye Powder and White Dye Powder respectively instead of White Dye Powder and Orange Dye Powder respectively.

![2018-05-22_00 01 36](https://user-images.githubusercontent.com/1721589/40343150-1a4cfdd2-5d54-11e8-8468-7570e314e013.png)

![2018-05-22_00 01 40](https://user-images.githubusercontent.com/1721589/40343152-1c7d13e4-5d54-11e8-8445-04c755ad3c72.png)

## Expected Behavior
White candle is made using white dye and orange candle is made using orange dye.

## Possible Solution
Probably a mismatched recipe script.

## Steps to Reproduce (for bugs)
1. Check JEI candle recipes

## Context
Can't bleach my candles.

## Client Information
* Modpack Version: 3.0.7
* Java Version: 1.8.0.171
* Launcher Used: Twitch, modified

* Memory Allocated: 4gb

* Server/LAN/Single Player: Single
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
This will be fixed in the next update :)
