### ISSUE TITLE
[Suggestion] Consider adding Construct's Armory & Cosmetic Armor to the Pack

### ISSUE THREAD

**Issue by EhGneissGuy** [DarkPacks/SevTech-Ages#2595]
## Issue / Bug

Not really an issue. Just a suggestion that since the pack encourages use of Tinker's tools it would be nice to add the complimentary mod with appropriate gating.

## Expected Behavior

If added, it could reinforce the use of early-game materials (wood, flint, stone, bone, etc) available in Tinker's tools in armor. Also, it would give the player an armor source that they could modify/build on throughout the ages. It would ultimately be a very rewarding and hard-earned reasonable set of armor until later ages when jetpacks, etc become available.
Cosmetic armor would just be a nice feature which also compliments the wide variety of armor styles. For instance, the appearance of wolf armor when wearing bone armor! Or vice versa.

## Possible Solution

[Add in construct's armory! ](https://minecraft.curseforge.com/projects/constructs-armory)
[Add in cosmetic armor reworked!](https://minecraft.curseforge.com/projects/cosmetic-armor-reworked)

## Context

I find that as the ages progress I really don't take advantage of any of the armors since they wane in use so quickly. I don't use any armor other than pants and a helmet since I'm always wearing the backpacks and slime boots. Since Construct's Armory adds in useful slime boots as armor and chestplates that can use backpacks, it feels like the next logical step. It would promote engagement in the armor advancement system (as players are going to upgrade their armor as they progress through the ages). I feel like it compliments the shifting focus of materials in the pack - just as it does for Tinkers - and is a well made mod.

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: 3.0.7
* Java Version: 8.171
* Launcher Used: Twitch

* Memory Allocated: 4GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes
* Optifine Installed?: Yes

## Server Information
* Java Version: N/A
* Operating System: N/A
* Hoster/Hosting Solution: CubedHost 4Gb
* Sponge (Non-Vanilla Forge) Server?: N/A

* Additional Content Installed?: Yes (Test Dummy Mod, Akashic Tome, Morph-o-Tool)

**Comment by LordHellscream** [comment]
I was just about to say this. This will add great flavors to the already fantastic modpack.

**Comment by BlackBeltPanda** [comment]
I would love to see this added. I've never been a fan of being locked to whatever armor happens to be the best at that point, rather than the armor I want to wear. =)

**Comment by PrimeEi8ht** [comment]
I approve

**Comment by Jandakast** [comment]
Construct's Armory is being added. 

We will not be adding cosmetic armor reworked because it adds blocks and we are very low on availible blockIDs.

**Comment by LordHellscream** [comment]
is this going to be in 3.0.8?
