### ISSUE TITLE
Weedwood crafting table and Integrated dynamics crash the game.

### ISSUE THREAD

**Issue by ginkoopl** [DarkPacks/SevTech-Ages#2596]
## Issue / Bug
I crash every time I look in the direction of a weedwood crafting table.

## Expected Behavior
Every time I look at weedwood crafting table from betweenlands my game crashes. BUT it always worked fine until I tried to craft [Output Variable Transformer](https://ftb.gamepedia.com/Output_Variable_Transformer) from Integrated Dynamics mod in said table. The moment I clicked on JEI "plus" sign in order to put crafting materials in the table my game has crashed.

## Possible Solution
Fixed it by breaking the table with /setblock.
Don't use weedwood crafting table.

## Steps to Reproduce (for bugs)
1. Put down weedwood crafting table.
2. Have all materials required to craft Output Variable Transformer.
3. Look it up in JEI and try to insert the required items.

I've managed to recreate it in a new world.

## Context
It crashed my game, I tried to craft Output Variable Transformer through JEI while in Weedwood Crafting Table's interface. I've checked the recipe in other crafting tables and it works as intended.

## Logs
* Crash Log: [Crash report](https://pastebin.com/kH3zYAvN)

## Client Information
* Modpack Version: 3.0.7
* Java Version: Latest, idk, probably doesn't matter
* Launcher Used: Titan minecraft launcher 3.7.0 (with Twitch app)
* Memory Allocated: 4Gb

**Comment by Jandakast** [comment]
Reported to mod https://github.com/Angry-Pixel/The-Betweenlands/issues/618
