### ISSUE TITLE
I have a lag problem

### ISSUE THREAD

**Issue by jeffeyinc** [DarkPacks/SevTech-Ages#2597]
so i load up into the map, i,m doing just fine for a while but then at some point the game will stop for a second then continue on for about 5 seconds with no problem then it will repeat. i feel like it might just be doing that when i load in more chunks, because if i stay in generally the same spot for a while it will work fine. i have all of my visual settings on fast, and i,ve disabled better foliage and that one where you drop items flat on the ground, but that didn't help.

**Comment by ginkoopl** [comment]
You could try updating java 8 if you haven't done that yet, I'm only saying this because my friend had similiar issue and that fixed it.

**Comment by ByteTemplar** [comment]
This is not for support!
Post to Reddit or go to Discord (https://discord.gg/darkosto) for these kinds of problems...
