### ISSUE TITLE
Scanner not detecting many Galacticraft ores

### ISSUE THREAD

**Issue by Brettflan** [DarkPacks/SevTech-Ages#2598]
## Issue / Bug
The Scanner from Scannable is not detecting many Galacticraft ores. Specifically I have observed it not working on Ilmenite Ore, Solid Meteoric, Carbon Ore, Ceres Uraniuim Ore, Jupiter Palladium Ore, and Jupiter Red Gem Ore. I'm guessing most Galacticraft ores which aren't just variations on standard iron/tin/copper/etc. are affected.

## Expected Behavior
For those ores to be detected.

## Possible Solution
Not sure. I see you do have config added for the various Galacticraft ores in scannable.cfg using oreDict (other than solid Meteoric Iron), but they don't appear to be working for some reason.

## Steps to Reproduce (for bugs)
1. Give yourself some of the various blocks mentioned above in creative mode, and place them in the world.
2. Try scanning them using a charged Scanner with Common Ores and Rare Ores modules in it.
3. Observe that they aren't detected by the scanner, unlike vanilla and Geolosys ores.

## Context
I also tried using the Block module for the scanner to detect Ilmenite, which it lists properly on the card, but it appears to ignore block data when actually scanning since that just lights up entire asteroids. Ilmenite has been rather hard for me to find, and I was unable to get the RFTools Builder's Quarry module to work for detecting and mining it. Quite possibly a problem with my attempt at using a Filter module to blacklist the basic asteroid blocks, now that I consider it; I may have messed that up. As it turned out, however, I ended up just re-enabling the Digital Miner recipe and using oreDict with one of those to successfully collect nearby Ilmenite.

## Client Information
* Modpack Version: 3.0.7
* Java Version: 1.8.0_161
* Launcher Used: Native Launcher, from Twitch
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Singleplayer
* Resourcepack Enabled?: Faithful [32x]
* Optifine Installed?: yes, 1.12.2_HD_U_D3

I saw this issue, which covers Scanner support for the Galacticraft ores being added in 3.0.7:
https://github.com/DarkPacks/SevTech-Ages/issues/908
It indicated to submit a new issue for any outliers, so here it is.

**Comment by justinrusso** [comment]
I thought this was related to another issue but was not. We then investigated if the time oredict for those ores were registered in init phases, but it does not appear to be the case either... 🤔
