### ISSUE TITLE
[3.0.7][Recipe] Cannot craft tinkers' excavator modifier.

### ISSUE THREAD

**Issue by HellishINC** [DarkPacks/SevTech-Ages#2600]
When attempting to craft the tinkers' excavator modifier, nothing is shown as an output. This occurs in vanilla crafting table, tinkers' as well as TBL's crafting table.

Please note, I only tried basic white (ie not the blue crafted crystrals) crystals.

## Logs
*Cannot run pack + memory hungry browser due to ram limitation, will update with logs in future*

* Modpack Version: 3.0.7
* Java Version: jdk8-8u172-1
* Launcher Used: MultiMC 0.6.2-1
* Memory Allocated: 5gB
* Server/LAN/Single Player: SSP
* Optifine Installed: Yes, also occurs without
* Shaders Enabled: No

Please note I have removed client side bloatware: Better laggy foilage, just the useless tips, Fugly block particles, Mo' ugly spider bends, not really Neat, Lag Font. Function > Form.

**Comment by justinrusso** [comment]
#2314

**Comment by HellishINC** [comment]
Hmm, I searched and that didn't come up. Apologies.
