### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by Orrin82** [DarkPacks/SevTech-Ages#2601]
## Bug Report

Crashes during Smooth Font load (2/7), if i remove that mod it crashes later on during Immersive Craft (4/7).
Have tried allocating different amounts of memory (8GB, 10GB, 12GB and less), my computer has 16 GB of memory so that should probably not be a problem.
Have tried both the Native and Jar launcher.
Have also tried reinstalling both Minecraft, Java and probably downloading Sevtech about 10 times now.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log: 
* Crash Log: https://pastebin.com/xjtxFwip
https://gist.github.com/Orrin82/74adb02d74ddde1eedd77d80bf3cafe6

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0.171(64 Bit)
* Launcher Used: Twitch, Jar launcher
* Memory Allocated: 8 448 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Orrin82** [comment]
Sorry probably the wrong log then, thought it was the latest.log, here's the debug.log
https://gist.github.com/Orrin82/74adb02d74ddde1eedd77d80bf3cafe6

**Comment by artdude543** [comment]
Thank you for reporting an issue!

It appears you are logging an issue for a crash, but you have either not uploaded to PasteBin/Gist etc.. of the actual crash report. This report contains the needed data to help to locate the cause and a possible fix. To find the file needed please review the following for either of the launchers.

## Twitch
1. Select the SevTech Pack to view the modpack page.
2. Click the `...` button on the top right just next to `Get More Content`.
3. Click `Open Folder`.
4. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it. 

## ATLauncher
1. Select the Instances tab, then scroll to the instance of SevTech.
2. Click the bottom right button named `Open Folder`
3. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it.

For any other launcher should be a similar process, if not consult with Google if you are not sure on how to find the folder. The information contained in these reports is critical for getting the crash fixed/looked into.

## Servers
For servers the process if farilt simple. Go the folder cotaining all the sever files/folder and you will see a folder called `crash-reports` follow the same process as above by getting the lastest one and uploading it to a text store.

**Comment by Orrin82** [comment]
Sorry I don't seem to have a Crash-reports folder, it doesn't exist where it should (...\Minecraft\Instances\SevTech Ages\) and I have tried searching my discs for it without results.
