### ISSUE TITLE
[Overlooked?] Some arcane scrolls (better with mods) are unobtainable, infernal enchanter is useles

### ISSUE THREAD

**Issue by Degonsky** [DarkPacks/SevTech-Ages#2602]
As you know, better with mods (or one of the addons, wich adds functionality of old version) adds it's enchanting system with arcane scrolls. These scrolls can be used in infernal enchanter and get used up by enchanting something.

So, to enchant a things, you will need them, quite a lot of them. Some of them drops from mobs, but it's rare, cost of expirience is way higher then normal enchanting (if compare same low lvl enchants) and you can't obtain a big part of them, because the most intresting enchantments (like unbrackable) supposed to be obtained through villager-trades, but villagers don't have such trades (I tested a lot of them. I mean... A LOT).

And because of that infernal enchanter becames completely useles and not worth the cost (theres vanila with random enchants, in which you have better chances get what you want by just grinding). I want to suggest to add in to villager trades these arcane scrolls, but make them cost something worthwile. That will encourage building of villages and use of infernal enchanter, as well will reduce enchant-grinding.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
