### ISSUE TITLE
NEI not showing items

### ISSUE THREAD

**Issue by Nefar1on** [DarkPacks/SevTech-Ages#2606]
I noticed that some items disappear from NEI, even though I'm able to make them, if you disable JEI Integration, this may be a bug, but I recommend adding a tool-tip when hovering over the option that says some items may disappear from NEI if this option is changed.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
