### ISSUE TITLE
Fluid Pump

### ISSUE THREAD

**Issue by SmileMore79** [DarkPacks/SevTech-Ages#2607]
hi my name is Smilemore79 I play sevtech ages on a server I'm very into it and love the way the mod is set up. not sure if I'm in the right place here for my issue I'm having. I'm in age three now and I'm wanting to make the bottler machine, it calls for the fluid pump, however I cant find any information or crafting recipe for it.

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by SmileMore79** [comment]
this forum sucks ass
