### ISSUE TITLE
Cant form dreadlands ritual altar without the dreadlands necronomicon

### ISSUE THREAD

**Issue by robzombie91** [DarkPacks/SevTech-Ages#2608]
## Bug Report
Trying to form a dreadlands ritual altar in the dreadlands with an abyssal wasteland necronomicon does nothing, even with the correct altar setup and nothing in the middle or sides of the ritual altar (used dreadlands cobblestone). Only way to form an altar was to make it with the dreadlands necronomicon which requires dreaded flesh which requires a dreaded rending staff which requires a dreaded altar. 

## Expected Behaviour
Be able to form the altar with an abyssal wasteland necronomicon with the correct ritual altar setup and dreadlands cobblestone.

## Steps to Reproduce (for bugs)

1. Get dreadlands cobblestone
2. Form ritual altar
3. Shift right click with abyssal wastelands necronomicon
4. Ritual altar does not form which breaks progression

## Client Information
* Modpack Version: 3.0.7
* Java Version: Java 1.8.0
* Launcher Used: Multimc
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: None
* Shaders Enabled: None

**Comment by Jandakast** [comment]
You can use any of the Staff's of Rending. It doesn't have to be the Dreadlands level one.

**Comment by robzombie91** [comment]
Except my abyssal staff of rending wouldnt damage any dreaded mobs or give any energy for the dreaded esscence
