### ISSUE TITLE
Rite of Spring Totemic Ceremony Not Working on 3.0.7?

### ISSUE THREAD

**Issue by ajbowler** [DarkPacks/SevTech-Ages#2610]
## Bug Report
Trying to perform the Rite of Spring ceremony, and it completes as far as I can tell. I am able to run through the ceremony to the end and it shows the green sparkles that you'd typically get with bone mealing stuff in vanilla Minecraft.

I have placed an oak sapling 2 blocks away from my 2-totem-high totem pole (3 tall including the base), but after completing the ceremony, the sapling is still oak-flavored and not red cedar. I noticed that the two dogs and two horses I have nearby aren't breeding either.

## Expected Behaviour
After completing the ceremony, I expect the oak sapling next to my totem pole to convert to a red cedar, and I expect the dogs and horses to get real friendly with each other. They do not.

## Steps to Reproduce (for bugs)
1. Build totem pole with two totems on top of the base.
2. Put oak sapling two blocks away from it.
3. Start rite of spring (sneak, flute, drum). All instruments had been made and used for previous ceremonies prior to this, and I doublechecked that the water breathing ceremony works correctly.
4. Play the instruments till ceremony is complete.
5. Watch green sparkles fly all over the place like you just bonemealed your farm in vanilla, but notice nothing changes.

## Logs
No relevant logs from ATLauncher as far as I can tell, just typical logs around saving chunks.

## Client Information

Default ATLauncher settings, Java version is shown:

![image](https://user-images.githubusercontent.com/6600392/40457555-cbcadcfa-5ebc-11e8-8eab-92d2db41815b.png)

The only change I've made to the mods since starting is disabling the Better Foliage mod since it's a massive performance hog.

**Comment by ajbowler** [comment]
I've tried a couple other methods just now, placing both an oak sapling and an olive sapling directly next to a new totem pole, then crafting new instruments. Still the same issue.

**Comment by Jandakast** [comment]
I just downloaded ATLauncher, the pack, started a new world and was able to do this just fine. Not sure what is going on in your world.

**Comment by ajbowler** [comment]
I don't think disabling Better Foliage would have caused this, would it? They're separate mods but they both touch the trees, though I admittedly don't know how deep into the tree code they intersect

**Comment by Jandakast** [comment]
Disabling Better Foliage shouldn't cause this.

**Comment by ajbowler** [comment]
I did try a couple different y levels as well as a different biome (Plains and Forest) to no avail.

I can close this issue if having it open is getting in the way since it doesn't seem reproducible for anyone else. I've since cheated around the advancement through adding some cedar to my inventory after verifying through other users that I was doing everything correctly in-game.
