### ISSUE TITLE
Low Performance

### ISSUE THREAD

**Issue by Megaskizzen** [DarkPacks/SevTech-Ages#2612]
When playing SevTech, FPS lingers around 0-1, with a very rare high of around 4. I've already done a few things to attempt to improve performance and I have seen some improvement so far. Visually, the FPS is almost high enough to be playable, at least by my standards, however it's not quite there.

**Specs:**

- Processor : Intel Core i5-2450M 2.5 GHz
- RAM : 8.00 GB (7.84 usable)
- OS : Windows 7 Home Premium 64-Bit
- Java : Version 8 Update 151 (build 1.8.0_151-b12)

**Things I have done so far in an attempt to increase performance:**

- Removed 4 aesthetic mods: Better Foliage, Mo'Bends, Smooth Font, and FancyBlockParticles
- Installed Optifine and adjusted settings
- Set algorithm to "Taylor's Algorithm" and turned on "Preallocate Memory" in BetterFps Options
- Allocated 4096 MB of RAM in the launcher
- Pasted [this code](https://pastebin.com/nV8aHRLE) in Java Parameters

Any ways I could further increase performance would be appreciated, and if any further information is needed I'd be happy to provide. Thanks.

**Comment by Jandakast** [comment]
This is designed for Higher end PCs. Unfortunately, this may not be the right pack for a nearly 5 year old laptop. You've done everything we would suggest to try.
