### ISSUE TITLE
Better with Mods Saw not processing Leaves into Sticks

### ISSUE THREAD

**Issue by Kayin318** [DarkPacks/SevTech-Ages#2613]
## Bug Report
The Better with Mods Saw will not process any leaves into sticks.  The recipe is displaying properly.  The recipe is also clearly added in the script file.

## Expected Behaviour
Leaves process into sticks when placed on the active side of a Better with Mods Saw.

## Possible Solution
I saw no conflicts in the scripts supplied with the pack.

## Steps to Reproduce (for bugs)
1.Place leaves on active side of Better with Mods saw.

## Logs
This bug produces no log entries.

## Client Information

* Modpack Version: 3.0.7
* Java Version: Java 8 U 161
* Launcher Used: Twitch
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Server
* Optifine Installed: none
* Shaders Enabled: none

**Comment by Stifling-Bossness** [comment]
#2483
