### ISSUE TITLE
Crash when crafting speed upgrade for pneumatic craft if you have more than 1 item in a slot in the crafting table.

### ISSUE THREAD

**Issue by Oarcinae** [DarkPacks/SevTech-Ages#2621]
## Bug Report
Put more than 1 item into the crafting table when trying to craft the speed upgrade for pneumatic craft.
Client crashes.

## Expected Behaviour
Not crash.

## Possible Solution (workaround)
Make sure each slot in the crafting table only has 1 item and don't shift-click.

## Steps to Reproduce (for bugs)
Put more than 1 item into the crafting table when trying to craft the speed upgrade for pneumatic craft.

## Logs
Sorry :(

## Client Information
* Modpack Version: 3.0.7
* Launcher Used: twitch
* Memory Allocated: 8gb
* Server/LAN/Single Player:
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Stifling-Bossness** [comment]
#2366
