### ISSUE TITLE
Random Knockback w/o Damage

### ISSUE THREAD

**Issue by zkoehler** [DarkPacks/SevTech-Ages#2623]
## Bug Report
I was standing around in my base crafting and I was getting random knockback that didnt damage me. It happens about every 10 seconds but in seemingly random directions

## Expected Behaviour
There is random knockback and there shouldnt be

## Steps to Reproduce (for bugs)
Its like my character is getting hit by a mob but there is nothing around 

## Logs
* Client/Server Log:
[0f94e6c1c7799b0f9044607933fbc7f0-c1d82ce8e8d1df99d23c2c0631fb0228ee10e652.zip](https://github.com/DarkPacks/SevTech-Ages/files/2038288/0f94e6c1c7799b0f9044607933fbc7f0-c1d82ce8e8d1df99d23c2c0631fb0228ee10e652.zip)

* Crash Log:

## Client Information
* Modpack Version:3.0.7
* Java Version: build 1.8.0_144-b01
* Launcher Used: Twitch
* Memory Allocated: 9G
* Server/LAN/Single Player: Single Player
* Optifine Installed:Not Unless it comes with the modpack
* Shaders Enabled:Nothing unless they come with the modpack

**Comment by justinrusso** [comment]
Trumpet Skeleton?

**Comment by KonoTyran** [comment]
Or possibly blood magic related if they have run out of LP with an ongoing effect.

**Comment by freitagdavid** [comment]
I'm running into the same issue. No skeleton and I haven't gotten into blood magic yet.

**Comment by freitagdavid** [comment]
Take it back there was a trumpet skeleton hiding in a hole under my base.
