### ISSUE TITLE
Models not Rendering

### ISSUE THREAD

**Issue by MrDj200** [DarkPacks/SevTech-Ages#2625]
## Bug Report

Some Models are not shown after changing dimensions/starting the game.
It seems to be pretty random. 
Things we tried:
1. Fresh Modpack Install => Worked at first. On the second start of the pack, things were bugged again.
2. Driver Check with other people where it works => All drivers are the same version. No dice.
3. Other ModPacks/Vanilla => The bug did NOT show up there
4. Setting the Video Settings and BetterFPS options to the same as other people => Bug is still present
5. Using the MC Default Java Version (1.8.0_25 64Bit) => Nope

## Expected Behaviour

Models should be rendered normally

## Possible Solution

No Idea for Reason or Solution

## Steps to Reproduce (for bugs)

1. Seems to be local to a machine. Other people on our Server could not reproduce

## Logs

* Client/~Server~ Log: https://gist.github.com/Cavadeca/d4c2ba3dcdb2ebf348a6123a01748d97
* Crash Log: N/A

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_171 64bit
* Launcher Used: New
* Memory Allocated: 12GB
* Server/LAN/Single Player: All
* Optifine Installed: false
* Shaders Enabled: false

**Comment by Stifling-Bossness** [comment]
Care to elaborate on which models don't show up? Like, are they multiblock structures, solid blocks, slabs, etc.

Also, you're allocating _way_ too much memory, performance starts to degrade after 8GB, and this pack doesn't seem to need more than 6-7GB.

**Comment by MrDj200** [comment]
Chests, Vanilla Creatures, Players, Totemic Creatures, Twilight Forest Creatures. Sometimes they are not Completely Invisible but weird. 
Like this: 
![Example 1](https://i.imgur.com/Hjj8BkQ.png)
Or this:
![Example 2](https://i.imgur.com/BDTJ9yl.png)

**Comment by justinrusso** [comment]
Rather than messing with Better FPS options, try disabling it completely and seeing if that helps. Settings for one person doesn't necessarily work for another.

**Comment by MrDj200** [comment]
We'll try this once the Person having this issue is back. Thanks for the tips!

P.S.: Setting the RAM to 8Gigs seems to make it atleast playable.

**Comment by artdude543** [comment]
I'm going to close this issue. We know this is an issue per say. But it's normally been down to the user side with the PC not being able to handle all the rendering going on.

9/10 disabling the MoBendz mod will _fix_ the issue and/or be disabling the _Foliage_ mod. At the end of the day, it's a limitation issue on the client side which we can't control nor the mod, if it comes to the engine not being to handle what's going on.

Most of these mods are having re-dos for 1.13 so we may see less of these cases of issues. But thanks for the report tho!
