### ISSUE TITLE
Has there been a solution to Ore Excavation Modifier not being craftable?

### ISSUE THREAD

**Issue by Gameswithjohn** [DarkPacks/SevTech-Ages#2627]
Attempting to craft the Ore Excavation Modifier, the mats all auto place, yet there is no output when they are in the table (both vanilla and TiC crafting tables). Saw other posts but no solution posted. Tried the various forms of maze stone and the different Astral Sorcery crystals with no results. 

I have no additional mods added or subtracted any, using the Twitch launcher, using version 3.0.7

Thanks for the assistance.

**Comment by Stifling-Bossness** [comment]
#2314 , it's set to be fixed 3.0.8. Only way to get the modifiers is to cheat them in, currently.

**Comment by Gameswithjohn** [comment]
Ahh, ok. Hate cheating in things if I don't need to, but will do for now since I am not wanting to wait for 3.0.8 I'll just throw out the mats to be fair I guess.

Thanks for the responses and sorry to bother with the duplicate post, wasn't since there wasn't much of an outright update. 

And Stifling-Bossness & Justinrusso, thanks for the quick checking, its a good pack (maybe a bit tough at times, but well...). Glad to see there is still so much going for such a simple older game that has always had crazy potential.

**Comment by Gameswithjohn** [comment]
Done know why, but I logged in today and was able to create the Ore Excavator modifier. Didn't change anything from yesterday.
