### ISSUE TITLE
Suggestion: Natures Compass, more Biomes to search for

### ISSUE THREAD

**Issue by Tozoz** [DarkPacks/SevTech-Ages#2631]
## Context

It would be nice, if less biomes were blacklisted in the NaturesCompass Config, only the darklands are shown, which makes sense in the progression, but looking for coralium swamps and other biomes is hard without it. Maybe somehow integrate it into the progression, so more biomes open up, depending on the age.

## Config/Script Details
* Link:

**Comment by artdude543** [comment]
Nope, not gonna happen this pack is designed for you to explore. It was only added to help the _few_ with issues finding the DarkLands.
