### ISSUE TITLE
Error Between BetterWithAddons and BetterWithMods

### ISSUE THREAD

**Issue by MrDietPeppsi** [DarkPacks/SevTech-Ages#2633]
We have been working on making a server for a couple hours now, using a purchased host and once we fully installed the modpack we continued to get the error
"Skipping event fmlServerStopped and marking errored mod betterwithaddons since required dependency betterwithmods has errored" We are using the 3.07 version of sevtech and as far as we know should be working and this is the only error that we are receiving

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
