### ISSUE TITLE
Crash during server load - Better With Mods

### ISSUE THREAD

**Issue by MegaKyle1250** [DarkPacks/SevTech-Ages#2634]
## Bug Report
The server seems to be loading fine then I get an error regarding Better With Mods.

## Expected Behaviour
I was expecting the server to load properly for the first time.

## Steps to Reproduce (for bugs)

1. Start Server
2. ???

## Logs

* Client/Server Log: https://pastebin.com/SgkH6YA0
* Crash Log: https://pastebin.com/KrDeYGgc

## Server Information
* Java Version: 1.8.0_162
* Operating System: Linux (amd64) version 2.6.32-696.18.7.el6.x86_64
* Hoster/Hosting Solution: Beastnode?
* Sponge (Non-Vanilla Forge) Server: ?

**Comment by artdude543** [comment]
This was already fixed. Seems your config was reset. Please re-install and try again. As the module which caused this is disabled in the pack.
