### ISSUE TITLE
[3.0.7][Totemic] Red Cedar tree leafs swallow wind chimes.

### ISSUE THREAD

**Issue by NaturalHate** [DarkPacks/SevTech-Ages#2638]
## Bug Report
Growing red cedar trees near placed down wind chimes makes the leafs swallow them up.

## Expected Behaviour
Instead of just leaving the chimes alone they create a leaf block in their place, deleting the wind chimes.

## Steps to Reproduce (for bugs)
1. Place wind chimes down.
2. Place red cedar tree nearby.
3. Let it grow.

Might work with other trees as well?

## Client Information
* Modpack Version: 3.0.7
* Java Version: 1.8.0_161
* Launcher Used: MultiMC
* Memory Allocated: 5GB
* Server/LAN/Single Player: SP
* Optifine Installed: Not unless it was pre installed.
* Shaders Enabled: No.

**Comment by AquaXV** [comment]
I noticed the same happen with acacia trees.
Might be happening with all leaves.
