### ISSUE TITLE
Your Betterwithmods jar file has its docs missing

### ISSUE THREAD

**Issue by Therandus93** [DarkPacks/SevTech-Ages#2640]
I made a post on this before and it was stated this wasnt your issue, however after having checked myself and confirmed with the mod creator, the same version your using has all the docs present that makes the manual work. In the "assets\betterwithmods\docs" Folder. 

Your version of that jar file however has these missing. I have manually put these back, however this is something you need to correct with the jar file you are using in your latest modpack version.

This is with the latest version 3.0.7

**Comment by Therandus93** [comment]
you should be able to, i have done so. I have opened via 7-zip as an archive, this allows you to alter the files
. I have added in the missing Doc files myself and got it working.

**Comment by justinrusso** [comment]
I understand how to open a jar file and change files in it. A modified jar file cannot be published to twitch in pack releases. It will be denied.

**Comment by Therandus93** [comment]
ah i see thats unforutunate

**Comment by Therandus93** [comment]
i assumed that the BetterThanMods jar file was  aslightly early version because you have altered it slightly to comply wiht the changes the modpack does, if this isnt the case, could you then just update from the X.15 to X.21 version of the mod?

**Comment by Jandakast** [comment]
Just to clarify, updating the mod version requires us to release a Pack update. BWM 1.21 is what is currently in the 3.0.8 dev build and will be included in that update once we release it.
