### ISSUE TITLE
[3.0.7] Cooked Dire Wolf meat is always possible to eat

### ISSUE THREAD

**Issue by themark147** [DarkPacks/SevTech-Ages#2641]
## Bug Report

Cooked Dire Wolf meat is always possible to eat & doesnt matter you have full hungry bar

## Steps to Reproduce (for bugs)

1. Try to eat a cooked dire wolf meat
2. It will be possible to eating always

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8
* Launcher Used:
* Memory Allocated: 4GB
* Server/LAN/Single Player:
* Optifine Installed: true
* Shaders Enabled: false

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:
* Additional Content Installed:

**Comment by Stifling-Bossness** [comment]
There are a few foods like that, such as rice bread, and I believe that they're intentional to help fix your nutrition and such.

**Comment by kholat** [comment]
Theres a few foods like this yes, intentional i think

**Comment by themark147** [comment]
Oh i didnt think about that like that ... so if it's true so issue can be close

**Comment by artdude543** [comment]
Intentional.
