### ISSUE TITLE
Compacting drawer does not work a expected with some items

### ISSUE THREAD

**Issue by JDLogic** [DarkPacks/SevTech-Ages#2645]
## Bug Report
The compaction drawer from storage drawers allows some item conversions that it should not as there are no  bi-directional recipes. There are also several item conversions that a player would expect to work as there are bi-directional recipes. A full list items for stage 3 & 4 are given below. If you would like, I can put together a list for stage 5 as well.

## Expected Behaviour

     Stage 3:
        Should not work:
           Minecraft
		- 4x Sand <-> Sand Stone (Avoids ginding / gallagher)
		- 4x Red Sand <-> Red Sand Stone (Avoids ginding / gallagher)
		- 9x oreDict slimeball <-> Slime Block (Allows converting one type of slime ball to another)
		- 4x Brick <-> Bricks (No recipe for conversion back)
		- 4x Clay <-> Clay Block (Avoids pressing)

        Should Work:
           Minecraft
		- 9x Redstone <-> Block of Redstone
           Better with Mods
		- 9x Concentrated Hellfire <-> Concentrated Hellfire Block
		- 9x Soap <-> Block of Soap
           Dark Utilities
		- 4x Wither Dust <-> Wither Dust Block
           The Betweenlands
		- 9x Octine Ingot <-> Block of Octine
		- 9x Syrmorite Ingot <-> Block of Syrmorite
		- 9x Rubber Ball <-> Rubber Block
		- 9x Valonite Shard <-> Block of Valonite
		- 9x Slimy Bone <-> Slimy Bone Block
		- 9x Middle Gem <-> Middle Gem Block (All three colors)
           Twilight Forest
		- 9x Carminite <-> Block of Carminite
		- 9x Arctic Fur <-> Block of Arctic Fur

     Stage 4:
        Should Work:
           Applied Energistics
		- 4x Certus Quartz Crystal <-> Certus Quartz Block
		- 4x Fluix Crystal <-> Fluix Block
           Galacticraft
		- 9x Raw Silicon <-> Silicon Block
           Integrated Dynamics
		- 9x Crystalized Menril Chunk <-> Block of Crystalized Menril
		- 9x Crystalized Chorus Chunk <-> Block of Crystalized Chorus
           Extended Crafting
		- 9x Ender Nugget <-> Ender Ingot
		- 9x Ender Ingot <-> Block of Ender
		- 9x Ender Star Nugget <-> Enhanced Ender Ingot
		- 9x Enhanced Ender Ingot <-> Block of Enhanced Ender
		- 9x Ender Star <-> Block of Ender Stars

## Client Information
* Modpack Version: 3.0.7
* Java Version: 1.8 build 162
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: Removed for testing
* Shaders Enabled: Removed for testing

**Comment by timmit99** [comment]
see #2615 , most-likely will be a Won't fix.
