### ISSUE TITLE
Missing Grave

### ISSUE THREAD

**Issue by Ceyon77** [DarkPacks/SevTech-Ages#2648]
## Bug Report
Grave disappears when killed by Shoggoth.

## Expected Behaviour
The grave should not disappear when defeated by a Shoggoth.

## Steps to Reproduce (for bugs)
1. Find Shoggoth Lair.
2. Engage In Battle With A Pack Of Shoggoth.
3. Die.
## Logs
https://pastebin.com/gjD0Pma4
## Client Information
* Modpack Version: Current
* Java Version: Recommended
* Launcher Used: ATLauncher
* Memory Allocated: 16 GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Stifling-Bossness** [comment]
#2429
