### ISSUE TITLE
"Either the owning or receiving player is offline" when trying to retrieve an older grave

### ISSUE THREAD

**Issue by oskskills** [DarkPacks/SevTech-Ages#2650]
## Bug Report

I died to Lesser Shoggoths. and when i tried to retrieve my grave it says: "Either the owning or receiving player is offline". retrieving my latest grave works, however.

## Expected Behaviour
instead of restoring the grave i want it keeps saying "Either the owning or receiving player is offline" despite me being online

## Possible Solution
More of a work around: but I copied the inventory i needed into the "Latest" file and then used the command to restore the lastest inventory and it worked

## Steps to Reproduce (for bugs)
1. Die
2. use the Tmg_restore command

## Logs

* Client/Server Log: https://gist.github.com/oskskills/0764a0fdb2048aaedbc27d6e5f1bccaa

## Client Information

* Modpack Version: 3.0.7
* Java Version: Version 8 Update 171 (build 1.8.0_171-b11)
* Launcher Used: Twitch
* Memory Allocated: 12,288MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by justinrusso** [comment]
Is this all while using the `/tmg_restore` command? No interaction with the physical grave whatsoever for this issue?

**Comment by oskskills** [comment]
The grave had been destroyed by Lesser Shoggoths. would that cause it not to work?

**Comment by justinrusso** [comment]
`/tmg_restore` should work I would assume. Unfortunately, otherwise, there is no fix that I know of. We will be transitioning to a new gravestone mod for 3.1.0. Please be sure to get all the graves you have in the world recovered before updating!
