### ISSUE TITLE
wolf pelt boots + ice biome = super sonic

### ISSUE THREAD

**Issue by kholat** [DarkPacks/SevTech-Ages#2652]
## Bug Report
Unlimited speed on ice.

## Expected Behaviour
The speed from ice should have an upper limit or something?

## Possible Solution
idk

## Steps to Reproduce (for bugs)

1. Get wild dog pelt boots
2. Go very north, find glacier biome (ocean with ice)
3. Face in one direction with lots of ice, press and hold forward, press and hold sprint
4. You zip into that direction in faster-than-chunk-loading speed, can end bellow ice because it might not load as fast as you move (or fall into void).

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.9_171
* Launcher Used: SK launcher and twitch launcher
* Memory Allocated: 10GB
* Server/LAN/Single Player: lan and SP
* Optifine Installed: no 
* Shaders Enabled: idk

**Comment by artdude543** [comment]
Intentional. Have fun! ^_^
