### ISSUE TITLE
The Betweenlands achievments and other...

### ISSUE THREAD

**Issue by Gameswithjohn** [DarkPacks/SevTech-Ages#2655]
While I admittedly am not a huge fan of The Betweenlands, its a well made mod with lots of depth but anything that forces you into difficult combat in Minecraft (some just not well fleshed out) while sticking you in place constantly is not typically fun especially in 1.9+ combat, and the night cycles are more than a little of an added pain. It feels like something where you are either forced to cheese your way through the whole thing or wait until you are so OP that nothing matters, and at that point there isn't much of an incentive to complete it.

There are a few things that could be improved for this pack dealing with the Betweenlands starting with the achievement tabs. I love the use of the tabs to guide you through the progression, but unlike the Twilight Forrest achievements tab (or any of the specific ages ones), the Betweenlands has 7 with just a few things on most of them? Why not just put them all in one tab to make it far simpler to track your progress or quickly be able to look for what you are after in that land.

A way to negate the constantly being stuck to the ground would be great. The rubber boots help a little but don't help with the slime and for faster travel you are forced to switch between them and better (or more convenient boots like the slime ones) all the time just to walk about. This is like dealing with the Abyssal sludge, except that its constant in some sections of the Betweenlands, and since visibility is limited much of the day cycle its hard to avoid. 

Speaking of visibility, before you are able to get night vision potions in the Betweenlands (bringing ones in doesn't work), or any tech/magic mod for it, you are basically stuck in one place waiting for the night to pass because its pitch black making travel, or anything else, near impossible. Some way to either negate that or just brighten it up enough to travel before you have night vision would be amazing, be it some sort of Betweenlands amulet or just easier access to potions that would work (though you are already having to eat something extra because of the sickness effect). 

Again, I don't feel like The Betweenlands is a horrible mod, its just that a few of the aspects of it are more terribly tedious than adding a challenging yet rewarding experience.

Thanks for all the effort on this pack, all in all this whole pack is great, just could use a few balancing fixes for certain sections of the progression if possible. I'm not sure if these are things that can be worked on but were just possible suggestions from my perspective.

**Comment by justinrusso** [comment]
>  the Betweenlands has 7 with just a few things on most of them? Why not just put them all in one tab to make it far simpler to track your progress or quickly be able to look for what you are after in that land.

Those are created from the mod. Twilight Forest and Betweenlands' advancements are kept in.

>  The rubber boots help a little but don't help with the slime and for faster travel you are forced to switch between them and better (or more convenient boots like the slime ones) all the time just to walk about

I'm not sure what else we could do for this.

> Some way to either negate that or just brighten it up enough to travel before you have night vision would be amazing, be it some sort of Betweenlands amulet or just easier access to potions that would work (though you are already having to eat something extra because of the sickness effect).

Not sure... @Darkosto, do you have any opinion on this?

**Comment by Gameswithjohn** [comment]
I would personally make the suggestion to condense the Betweenlands achievements tabs to the Dev, but alas I'm just a pleb and would probably not accomplish much doing so. However, should such a prestigious and well knows person working on a hugely popular pack such as this mention it they might consider working on it... I mean if there was time, opportunity, and want to do so. 

For the night vision, could the standard night vision potions be white listed to not go bad when you transport them into the Betweenlands? That would make it slightly easier. Or maybe added as a set bonus for wearing all of a certain betweenlands armor, and only in the betweenlands, though I think an amulet would be preferable. 

I'm sorry, I don't have much of a suggestion for the slime issue. Possibly a "coating" for boots that negates that effect, similar to the other coating that you can already do for tools in that mod? So you would still have to progress some in the mod to get it, but then eventually be able to travel easily, maybe be able to put it on outside armor (such as the slime boots, etc.) as well. 

Honestly I wish I could be of more use than just making suggestions (bitching) but I have no real experience with coding, so all I can do is attempt to come up with possible ideas or solutions and those with more knowledge and experience see if they are possible. 

Thanks for taking the time no matter.

**Comment by justinrusso** [comment]
There are many people who create suggestions and issues on their tracker that are not of any popularity.

https://github.com/Angry-Pixel/The-Betweenlands/issues

Most of these suggestions relate back to the mod itself, not us. Please submit it there and link back to this issue as a reference.

**Comment by Darkosto** [comment]
The reason I have not condensed these advancements into a single tab like the Twilight Forest was prioritization of my time. There were many more higher priority issues needing to be dealt with before I came to trying to rewrite the tabs for Betweenlands. To give you some insight into how that would need to work: I would have to rewrite all of those myself, there's not really a copy/paste feature for how we have custom advancements setup. Those Betweenlands advancements are from the mod itself, not me. So, I would have to go through and recreate their work in a single tab. That's the part that does not feel high priority since those tabs/advancements already exist. I would also need to confirm all advancement criteria exist and if something in the betweenlands was a custom trigger, I would have to have the custom advancement mod add those. I don't really have time to condense these but if someone wants to PR it in, I would be fine with it.

There's nothing we can really do about having to switch boots. Mods would need to update to fix this and I really can't speak for other devs.

Brightening up the dimension isn't on our end. We don't have the ability to do this. These are issues you have with the mod itself, not the pack. So, these issues would be best sent to the Betweenlands devs as feature requests.

I hate to sound like I'm saying no or unable to help out but outside of condensing advancements we can't do much.

**Comment by Gameswithjohn** [comment]
You are both right of course, and I will take the time to make this suggestion to the betweenlands mod devs on their pages and link it back to this pack for reference. This is the first time I've dealt with such a responsive set of Devs on a pack/mod, so hopefully you'll excuse my ignorance here for not knowing where/what exactly to do for suggestions or issues other than here. 

Again, thanks for taking the time to respond, and though I'm doing little more than typing I understand that what you guys are doing is VERY difficult and while I might be open with my opinions I (and many others) are very thankful to your team working on something interesting and simply giving it out for people to enjoy.
