### ISSUE TITLE
[Suggestion] Recipe for turning Prismarine block to Prismarine Shard

### ISSUE THREAD

**Issue by Sparky1492** [DarkPacks/SevTech-Ages#2657]
## Context

I would like to suggest a recipe to create Prismarine Shards, via Mill Stone to grind Prismarine block to Prismarine Shards.  This would help aid in creating Sea Laterns.

**Comment by timmit99** [comment]
The twilight forest Uncrafting table should be able to do this

**Comment by Sparky1492** [comment]
My thought was to have easier access to Prismarine Shards during Stage Two for BloodMagic Alter.

**Comment by justinrusso** [comment]
This was something on the TODO list already. It is not intended for you to have to use the uncrafting table for this.

**Comment by WorldWarHulk** [comment]
You can do it with AbyssalCraft
