### ISSUE TITLE
Corn not growing

### ISSUE THREAD

**Issue by Rocksnotch** [DarkPacks/SevTech-Ages#2661]
# **Issue / Bug**
I see this posted before and closed, but still an issue. Corn just doesnt grow AT ALL no matter what I do!

# **Expected Behavior**
Corn should grow at some point.

# **Steps to Reproduce (for bugs)**
Find corn in the wild.
Try Bone meal, try watering can, nothing grows it

# **Logs**
Client/Server Log: Dont have em currently
Client Information
Modpack Version: 3.0.7
Java Version: 8
Launcher Used: Twitch
Memory Allocated: 6 GB
Server/LAN/Single Player: Single Player
Resourcepack Enabled?: No
Optifine Installed?: No

**Comment by artdude543** [comment]
This is already known and generally effects worlds already made. Closing as I've been in talks with the dev for ages now on this one.
