### ISSUE TITLE
Steves Carts Track Remover doesn't turn off

### ISSUE THREAD

**Issue by filekv5** [DarkPacks/SevTech-Ages#2665]
Steves Carts track remover does not stop removing tracks after passing the module toggler. Normally the track remover goes to the end of the line and starts removing rails. After it reaches the module toggler with advanced detector rail it stops removing tracks and goes back to the station.

Version
3.0.7
Mode 
Server and single player

**Comment by artdude543** [comment]
This would need reporting on the mods own tracker as it sounds like a bug purely on their side. We won't report this ourselves as it's not a bug in the pack nor nothing major.
