### ISSUE TITLE
Is it possible to install Optifine onto SevTech-Ages?

### ISSUE THREAD

**Issue by Booknut101** [DarkPacks/SevTech-Ages#2666]
I've been using the Twitch launcher and have been having trouble installing Optifine. (I usually have major lag spikes while playing Minecraft and Optifine clears the worst of them up) Is there any way to install Optifine onto this modpack? Thank you.

**Comment by Stifling-Bossness** [comment]
Just drop optifine in the mods folder in the Sevtech directory

**Comment by Booknut101** [comment]
Okay, thank you!
