### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by Splash2430** [DarkPacks/SevTech-Ages#2667]
Hi! I have the issue. I have a nice fps (100-150), but every 5-20 seconds appears little hovering. Sorry for my English, Im from Ukraine, but I hope you'll understand me. I have 8GB RAM, Windows 10, Intel i3-7130U 2.7 GHz. Help please, I don't know why it happens, I have nice notebook, low video settings, but anyway that freezing happens. 

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_171
* Memory Allocated: 8192
* Launcher Used: Twitch
* Server/LAN/Single Player: Single player
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by Dreadkong88** [comment]
I've had this issue as well until I turned off the nice foliage (better trees) the key to change the settings for it is defaulted F8 (but check your controls-keybind section to find yours)  I turned it off and it helped immensely with visual glitches and fps/lag in general

**Comment by Stifling-Bossness** [comment]
Every 5-20 seconds like Java garbage collection, are you using the recommended java arguments? 
They can be found here: https://github.com/DarkPacks/SevTech-Ages/wiki/Recommended-Java-Args
