### ISSUE TITLE
Hey!  Sharknado has stolen all of the sharks!

### ISSUE THREAD

**Issue by Dreadkong88** [DarkPacks/SevTech-Ages#2668]
![nodamnsharks](https://user-images.githubusercontent.com/39703279/40619846-9fced100-6264-11e8-8933-46e9951b9fc0.png)

Heya, in a previous version I had trouble finding any squid for the cartographer (age 1).  While I appreciate the increased spawn for squid to acquire ink sacks, the new complete lack of sharks makes making the burning hopper thing and moving to age 2 impossible.  I've spent five hours running by rivers, and floating in the ocean trying to get a single shark spawn.  Even went so far as to log out mid-ocean and back in to reset spawns.  On the bright side, I have found two guardian temples in all my roaming!

## Bug Report
Bugs could also not find any sharks for me.

## Expected Behaviour
Need Moar sharks!

## Possible Solution
Moar sharks!

## Steps to Reproduce (for bugs)
Float around in the ocean for hours!

1.
2.

## Logs
Yes, I floated in the ocean on logs.

* Client/Server Log:
* Crash Log:

## Client Information
My clients' information is privileged and classified.

* Modpack Version:  3.0.7
* Java Version:  1.12.2
* Launcher Used:  Rocket
* Memory Allocated:  All my mental capacity
* Server/LAN/Single Player:  I play alone, all by myself...  ;-;
* Optifine Installed: Negative. but I'm fine. shoo.
* Shaders Enabled:  Nerp

**Comment by Stifling-Bossness** [comment]
You can use a survivalist's strainer to get shark teeth

**Comment by Dreadkong88** [comment]
Cant make the survivalist strainer until age 2 ;]  I tried that too.

**Comment by Stifling-Bossness** [comment]
... yes you can? It's staged in age zero, and it's just sticks and string.

**Comment by Dreadkong88** [comment]
yes.. yes I can.  I apparently did not click right on the JEI screen to get to the one that did not say (unknown recipe)  Right.  Still are no sharks though, but I'll get toofs via strainer

**Comment by justinrusso** [comment]
We've had this discussion many times, and quite honestly I don't think anything here will change. Some will say they have too many sharks, others will have none. It's just Spawn chances.
