### ISSUE TITLE
Insanity of the Player launcher

### ISSUE THREAD

**Issue by Gameswithjohn** [DarkPacks/SevTech-Ages#2669]
I would like to suggest that the Cyclic Player Launcher is restricted for crafting until you at the least have Journey map, or better yet some form of teleportation. That item is game ending levels of crazy unless you want to cheat and TP yourself back to your starting location (without cords that's almost impossible and you probably didn't bother to write them down just in case from the compass or any other slight means you have when you are able to craft it). 

I was lucky to only manage to get a few full pages away from my location last night (in 4 different attempts and directions), so it only took me an hour of careful hopping back to the area I had already explored, but had I not been so lucky it would have almost ended my game. This item needs a safety warning, "Can cause anger, frustration, and sadness leading to starting over".

**Comment by Stifling-Bossness** [comment]
You can get an antique atlas in tutorial stage, and you can unlock journeymap early in stage 2. IMO, there's plenty of options for location management before you unlock the player launcher in stage 3.

**Comment by Gameswithjohn** [comment]
Yes the atlas does help you see where you are somewhat, and is great early on, but the Player launcher can glitch you many thousands of blocks away (I think mine being over 3 full page swipes in the atlas was close to 20k blocks away, and luckily being able to find it because it wasn't in a straight line from where I was) in only a few seconds. Part of this happening to me was while working on getting Journeymap, and that's a slight pain because of the Betweenlands, and that's why I mentioned being locked behind getting Journeymap. But as I said its just a suggestion, and only because of the limited access to coordinates for trekking back. This is just one of those things that without looking up issues with the item you wouldn't know that it could glitch you out like that, and its an unfortunate way to end your play through, especially if you happen to be stuck in somewhere other than the Overworld. With good packs like this one it is unfortunate to feel like rage quitting because of something like that, and I know there isn't a way to fully control everything, but it seems like its being attempted here for a better experience (including stopping people from being able to do some stupid stuff ruining their experience).

**Comment by artdude543** [comment]
This is intentional. It's also a troll. If you fire yourself miles away then I guess bad luck? Re-staging won't happen in regards as you have access to maps in the stage away way. So it's not like you _can't_ get back home. It's also aimed at servers for quick usage on shoving people around if they don't want to be near people. So it has intention along with funny quirks!
