### ISSUE TITLE
This Guy abuse

### ISSUE THREAD

**Issue by 1JustVlad1** [DarkPacks/SevTech-Ages#2672]
This guy abuse by charging armour instantly on the Venus

https://clips.twitch.tv/DeadLuckyMomRitzMitz

The issue is that you instantly charging armour, which makes you invulnerable and charger doesn't cost any energy.

**Comment by Legatonin** [comment]
I would do the same, but used mending on all my armor pieces and exp pylon spewing out exp orbs to repair it.

**Comment by Shananiganeer** [comment]
The charger goes from 42187RF to 41187RF while charging the helmet, but doesn't lose any RF while charging the other pieces.

**Comment by Shananiganeer** [comment]
I don't think MJR realized that the charger didn't expend any RF when filling the chest, legs, and boots.
