### ISSUE TITLE
Help menu pages crash game (or doesn't work)

### ISSUE THREAD

**Issue by BigIrukandji** [DarkPacks/SevTech-Ages#2674]
I noticed that when cycling through all of the available commands in the help pages (/help 1, /help 2, ect) some of the help pages will crash the client, but not all of the time. Sometimes it doesn't work at all and kicks out a "An unknown error occured while attempting to perform this command".

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
