### ISSUE TITLE
Twilight Forest Graphical Glitch Then Crash

### ISSUE THREAD

**Issue by MaxFirestorm** [DarkPacks/SevTech-Ages#2675]
## Bug Report
While exploring the Twilight Forest, graphics become incredibly glitched out, skybox seeming to "leak" out into the world before crashing the game. (I apologise if this description is... Lacking. The video attached can describe it better than I can in words)

## Expected Behaviour
....Not... doing... that?

## Possible Solution
No idea at all

## Steps to Reproduce (for bugs)
This has happened a couple of times in my streams in the last couple of days and I don't really have any step to "reproduce" it, per se. This has happened at least four times in the last two days and this video is the only clip I have of it.

However, the steps of the actual bug are as follows.

1. Pretzel (My stream music streaming player) stops playing and greys out its window entirely
2. The skybox colour seeps into the world.
3. Game crashes moments later.

Leaving the world via portal (or quitting to title and re-entering) during stage 2 fixes it, but it happens again later on (seemingly at random. I've not found any kind of defining factor that is *always* happening)

Video - https://www.youtube.com/watch?v=3WLI5zMRpBg

(It should also be noted that this crash took out Minecraft/Java, Streamlabs OBS **and** Pretzel as it went down)

## Logs

* Client/Server Log: https://gist.github.com/MaxFirestorm/26835fa789789d4ec82427f195eeb265
* Crash Log: https://pastebin.com/A8ikqpqY

## Client Information
* Modpack Version: 3.0.7
* Java Version: 1.8.0.161 (64bit)
* Launcher Used: Twitch
* Memory Allocated:8,192mb
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by artdude543** [comment]
Pretty clear error `java.lang.OutOfMemoryError: Batching chunks`

Try to use the following args https://pastebin.com/hWWUGGHQ but this is not a pack bug or issue. It's a memory issue on your end.
