### ISSUE TITLE
Equipped Iron Backpack (Age3)

### ISSUE THREAD

**Issue by KennyBurch** [DarkPacks/SevTech-Ages#2676]
## Bug Report
 Upon death the my 'equipped' iron backpack was no returned.  (The bug may be convincing the game to let me equip the backpack to being win)

## Expected Behaviour
Either:
A: Make the Equip/Unequip backpack disabled to be more robust
B: allow better recovery of the equipped backpack.

## Steps to Reproduce (for bugs)
1. Equip Iron backpack (even though it says Disabled)
  a. Highlight ironbackpack backpack
  b. Push the "**Equip/Unequip Backpack(Disabled)**" keybind
  c. Pushing the "**Open Backpack**" keybind (The backpack opens..and vanishes from hotbar)
2. Die (in my case, in the hunting dimension...but it seemed to be repeatable)

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version: latest
* Launcher Used: Multimc
* Memory Allocated: 6GB
* Server/LAN/Single Player: Server
* Optifine Installed: N
* Shaders Enabled: N

## Server Information
* Java Version: latest
* Operating System: Windows 10
* Hoster/Hosting Solution: Private
* Sponge (Non-Vanilla Forge) Server: N
* Additional Content Installed:

**Comment by artdude543** [comment]
Same issue as #2429

**Comment by KennyBurch** [comment]
I don't think this is the same as 2429. You can't use TMG command to restore as it doesn't keep the 'equipped' iron backpack data.

**Comment by artdude543** [comment]
Yes which the command is from the same mod with the same bug as not handling anything other than it's own stuff.
