### ISSUE TITLE
[Suggestion] Let crafting stump being used after crafting table creation

### ISSUE THREAD

**Issue by hron84** [DarkPacks/SevTech-Ages#2677]
This is just a simple thing and not really see what will it broke, so please, if it is not possible, let me know why.

So, after getting a potential to use vanilla crafting table, I found crafting stumps do not work anymore, or maybe just not for new recipes. However, sometimes I find them quite useful, for example when I have to use repeatedly a recipe with workblade, I'd prefer to keep a MK2 stump in place, put in the ingredient and as I need, I just put in workblade and get the required stuff. This could be useful before reaching Tinker's Crafting Station even if MK2 stumps have a chance to break. 

Also Crafting Stumps are just prettier and I want to use them as long as it is possible.

**Comment by artdude543** [comment]
The stumps are only staged for `tutorial, zero & baykok` this is intended and won't be changed. The pack is aimed at pushing the user to create the newer crafting tables/mechanics.

This may be reviewed again at a later stage, however. But if you want to modify the script to allow this for your instance.

Change the following:
File:
`scripts\staging\containers.zs`
Line 9: 
`mods.recipestages.Recipes.setContainerStage("primal_tech.inventory.ContainerWorkStump", allStages);`

**Comment by hron84** [comment]
Thanks for letting me know and providing a detailed answer. My private opinion is **most** crafting is just can done more comfortable in a crafting grid, however some people use crafting tables that can hold their content as an early game autocrafting solution. I see how you tried to help these people to get around it e.g. with the stirring recipe of leather, but I still can find usage for stumps in mass-crafting.

**Comment by LordHellscream** [comment]
why not use the TiCon crafting station? it holds all the items.

**Comment by hron84** [comment]
Yeah, that's I prefer crafting stump. In age 2, station is OK and I'll use stumps just as a decoration block.
