### ISSUE TITLE
The game crashed whilst initializing game; Unable to fit: chisel:blocks/bricks/bricks-solid

### ISSUE THREAD

**Issue by JekoDdragon** [DarkPacks/SevTech-Ages#2683]
## Bug Report
Game crashes on load. It's always in stage 3 out of 7, on texture stitching, this particular texture. It happened out of a sudden, it worked fine previously and I don't think I changed anything.

## Expected Behaviour
Well, it should load normally

## Steps to Reproduce (for bugs)
It's on loading the game, so just do that

## Logs
* Client/Server Log: The game crashed whilst initializing game Error: net.minecraft.client.renderer.StitcherException: Unable to fit: chisel:blocks/bricks/bricks-solid - size: 16x16 - Maybe try a lowerresolution resourcepack?
* Crash Log: https://pastebin.com/4mHnCE0E

## Client Information
* Modpack Version: 3.0.7
* Java Version: build 1.8.0_171-b11
* Launcher Used: twitch
* Memory Allocated: 4096m
* Server/LAN/Single Player: single, on load
* Optifine Installed: no
* Shaders Enabled: no

**Comment by artdude543** [comment]
Nothing we can do about this one. This is a Vanilla bug for donkeys now.

You could try using the following args: https://pastebin.com/hWWUGGHQ but other than that and maybe changing your Memory Allocation. This is a not a pack issue nor Forge.
