### ISSUE TITLE
Age 3 starlight transmutation not working

### ISSUE THREAD

**Issue by speakerman36** [DarkPacks/SevTech-Ages#2685]
## Bug Report
When trying to use Astral Sorcery's starlight transmutation on a block like iron ore or sand, it gives the particle effects like it is working but nothing happens. 

## Expected Behaviour
To my understanding making star metal ore was supposed to be possible this way in 3.0.7.

## Steps to Reproduce (for bugs)

1. Place floating crystal
2. Place iron ore block
3. Link the two with linking tool
[latest.log](https://github.com/DarkPacks/SevTech-Ages/files/2049420/latest.log)

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_161
* Launcher Used: Twitch
* Memory Allocated: 12,288 MB
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:
* Additional Content Installed:

**Comment by justinrusso** [comment]
What dimension are you in?

What particle effects is it doing? A screenshot would be ideal.

**Comment by speakerman36** [comment]
I did not realize that I did not have line of sight to the sky with the collector crystal
