### ISSUE TITLE
Carry On problem

### ISSUE THREAD

**Issue by Yusunoha** [DarkPacks/SevTech-Ages#2688]
The problem is, as you can guess, this mod isn't working for me at all. Is it perhaps locked behind an age? I thought I unlocked it after I wasn't able to carry Immersive Craft storage blocks anymore and I had to use Carry On, but that doesn't seem to be the case.

I tried changing hotkeys and using shift, nothing in my hands, but I wasn't able to get it to work at all.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by SnappyFrog** [comment]
It's too bad this isn't being worked on.  It's a major issue for me at the moment.  Not sure how to create an issue, but I'll try.

**Comment by monodemono** [comment]
This isn't being worked on because there's nothing to be worked on. This is neither a bug report nor a feature request. If anything this is user error.
