### ISSUE TITLE
[Item Dupe] Filtered Hopper from Better With Mods

### ISSUE THREAD

**Issue by Joriom** [DarkPacks/SevTech-Ages#2696]
## Bug Report
Many (2-4) filtered hoppers can collect the same item at the same time if its dropped exactly at the top edge shared by hoppers. Works for any item, even complicated oned like tinker tools. Dupe preserves all metadata of an object including enchantments, modifications, etc.
Already reported to Better With Mods as well.

## Expected Behaviour
Only single hopper should pick up the item, action should be canceled/unavailable for the rest.

## Possible Solution
Venom Bord of the East - Today at 12:03 PM
what a classic
all things that take from world have to check isDead on the entity

## Steps to Reproduce (for bugs)

1. Place two Filtered hoppers next to each other - side by side
2. Stand on top of them, directly on the border of blocks.
3. Drop item directly under you.
4. Both hoppers will pick up the dropped item.

## Logs
N/A

## Client Information
* Modpack Version: 3.0.7
* Java Version: 1.8.0.91 (x64)
* Launcher Used: Twitch App
* Memory Allocated: 4,338 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by artdude543** [comment]
Linked Issue: https://github.com/BetterWithMods/BetterWithMods/issues/993

**Comment by artdude543** [comment]
This is included in the next pack update.
