### ISSUE TITLE
Multiplayer corruption - unfamiliar item

### ISSUE THREAD

**Issue by Nephim** [DarkPacks/SevTech-Ages#2697]
## Bug Report

I have lost my player data on my multiplayer server... I was just standing, then i shut everything down and when I got back everything was gone, I was at the natural spawn, with no items. Everytime i try to pick something up, it drops it again. It says that it is an unfamiliar item. I even tried with dirt, grass and so on. I have tried a few different commands but nothing has been helping.

## Expected Behaviour

No matter what I try it dosent help, Ive even tried resetting my characters progression completely... I really dont know what more I can do.

## Possible Solution

It must have gotten corrupted somehow, if you can find out why in the logs perfect, but I have no idea how to replicate it other than just being unlucky. I just hope you can somehow help me fix this with a command or something.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log: client: https://pastebin.com/JCUBGvwf; https://pastebin.com/w3G5xhKi; Server: https://gist.github.com/Nephim/7360f4d7af9da152b36605ea71941395 (too big for Pastebin)
https://gist.github.com/Nephim/9b053b4ef741df502bddba1bffd68617 (Debug.log)
https://gist.github.com/Nephim/6c4f1d884fd45046ac20b8c6492e2eb9(This is when i started and lost everything)
https://gist.github.com/Nephim/c6874d20e925ffa42ac020d404570013(think its here where it happened.
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_171
* Launcher Used: AT launcher
* Memory Allocated: 4 GB on client, 6 GB on server
* Server/LAN/Single Player: Server, dedicated Linux running 16 GB ram and AMD FX 8350
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: 1.8.0_1.7.1 devkit
* Operating System: Linux ubuntu 16.04 LTS
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server: No, normal Server directly from the AT launcher
* Additional Content Installed:

**Comment by artdude543** [comment]
Sadly once the data is gone that's it. I'd recommend installing a backup mod for the server to help with this in case it happens again.

But command-wise you can do the following.

https://sevtechages.gamepedia.com/Useful_Commands#Advancement_Command

This will help you getting back to where you was! 🙂 Hopefully this helps ya out. If you join the Discord people in there can also help. I'll tag the issue so the bot posts a link for ya!
