### ISSUE TITLE
[Item Deletion Bug] Simple Storage + Compacting drawer

### ISSUE THREAD

**Issue by Donav22** [DarkPacks/SevTech-Ages#2698]
## Bug Report

I finally crafted Simple Storage, and hooked it up to my Storage Drawers controller, and some Actually Additions: Small Storage Crate.
I set the priority on the link at the Storage Drawers Controller to 10, and left the rest at 0.

I added a Storage Import Cable at the end of the line, and added 2 speed upgrades and 2 stack upgrades to that Import Cable.
I then went and gathered my other Crates that were all over my base and plunked them down one by one to dump them into the system. (6 small crates, 1 large).  I know I was safe doing this as there were 15 basically empty Small Storage Crates as part of the system: more than enough space to hold 6s+1l incoming.

When I plunked down the last crate (the large one), I went to look at my storage drawers and start manually sorting stacks, etc. (because I knew it would have put things like the atlas or other guide books in a drawer slot).  I noticed that the single compacting drawer in my network was empty and blinking.
Turns out that the system was putting each single item in that drawer then deleting it.  Of my 6s and 1l crate (which were each about 2/3 full of the latest stuff for age 4 like pneumaticraft, ender alloy, ...) 90+% of it was deleted.

Long story short, this was very much a setback, and after getting my backpack eaten (as in my last bug report), I am done with this modpack.

I will leave it installed to give you whatever screenshots you need or log files or ... but I am done.

![2018-05-31_13 28 21](https://user-images.githubusercontent.com/39231057/40797751-40bd5766-64d7-11e8-8498-96af1da7686b.png)
![2018-05-31_13 29 59](https://user-images.githubusercontent.com/39231057/40797752-40ce89f0-64d7-11e8-8d1b-f140af67001c.png)
![2018-05-31_13 30 59](https://user-images.githubusercontent.com/39231057/40797753-40ddda22-64d7-11e8-9121-10c090008dce.png)

P.S. If my storage layout looks familiar to anyone, it is basically Iskall85's layout.

## Expected Behaviour

The items would try to go to the Storage Drawers system, and over-flow into one of the other 1178 available slots in my current network setup.

## Possible Solution

A) Don't directly import into an empty compacting drawer
B) Only import to a compacting drawer if the item is compatable

## Steps to Reproduce (for bugs)
1. Set up Storage Drawers network
2. Set up some Small Storage Crates
3. Set up a Simple Storage network on all of the above
4. Set priority on Storage Drawer Controller to 10
5. Import from a Small Storage Crate (in my case)

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.0.8_25 64bit
* Launcher Used: Twitch
* Memory Allocated: 4GB
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: None

**Comment by Jandakast** [comment]
I spent about an hour this morning setting up an extensive storage network and hooking it to different things that store ores, bags, tools, and misc blocks to try and reproduce this. I have 14 small storage crates 50 4x4, 14 2x2, 28 singles and 11 compacting drawers all connected to the storage system using storage link cables on each Crate and on a controller with a priority of 10. emptied 32 large storage crates into the system with 0 item loss. I ended up with tools, an energy cell, and redstone ore in my compacting drawers (which don't compact to anything) but they didn't eat any items.

**Comment by artdude543** [comment]
Closing this as it's an old issue and 3.1.0 is due soon with a tonne of fixes/changes. That and we could not repro the issue, which is hard for us to debug. 

If you get the issue still in 3.1.0 please upload the world and re-report. Thanks!
