### ISSUE TITLE
Deleting items

### ISSUE THREAD

**Issue by RealTrueDeviL** [DarkPacks/SevTech-Ages#2699]
## Bug Report

Bug 1 : Went to Twilightlight Forest, got on my horse, got off near Lich tower, horse was deleted instantly..

Bug 2: Got into Lich tower, killed some zombies, open my Golden Backpack, put some stuff in it, closed it, killed more zombies.. Golden Backpack got deleted from inventory, lost everything in it, of which I don't remember what everything was, completely ruined gameplay, and any fun I was having in this pack...
[latest.log](https://github.com/DarkPacks/SevTech-Ages/files/2059411/latest.log)

So many errors, and I didn't see a single explanation as to why it deleted stuff...

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:
* Additional Content Installed:

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
