### ISSUE TITLE
Immersive Petroleum mining drill is invisible (3.0.7)

### ISSUE THREAD

**Issue by PotatoMaster26** [DarkPacks/SevTech-Ages#2700]
## Bug Report

As said in the title, the mining drill from immersive petroleum is textureless/invisible, its not a BIG problem, since it still works, but it is still quite annoying.
Also the revolver from immersive engineering is invisible.
## Expected Behaviour

Should be visible
## Possible Solution

Maybe changing something in the Video Settings (nothing yet)
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version: build 1.8.0_171-b11
* Launcher Used: ATlauncher
* Memory Allocated: 7680mb
* Server/LAN/Single Player: Single player
* Optifine Installed: Yes (most recent)
* Shaders Enabled: No

**Comment by artdude543** [comment]
Going to close this one and tag #2727 as it's not a pack issue. But client-side rendering issue. Changing settings would help and/or disable mods such as Optifine or Better Foilage etc... which impact the client rendering
