### ISSUE TITLE
Red and orange planes (visual bug, Spinning arms and glitchy movement

### ISSUE THREAD

**Issue by Ulfsson** [DarkPacks/SevTech-Ages#2701]
## Bug Report
For some reason, when I start my world, a strange orange and red glitchy mess appears across the screen, This is not effected by pressing F7 which i assumed at first. This also seems to only happen in this world.  (You can see this here: https://youtu.be/sw6PQ9sVE84)
The second issue i am having is whenever i move using WASD, i spin around and glitch all over the place. This only happens while moving and seems to happen in the terrains i tried this in. (This can be seen in a different world here: https://youtu.be/U2M79fGUx94)
The 3rd glitch can be seen in 3rd person of both videos. My arms seem to spin around out of control.
## Logs

* Client/Server Log:https://gist.github.com/Ulfsson/71e5f6ad7538711e836d3223abe46542
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version: jre.1.8.0_172
* Launcher Used: Twitch
* Memory Allocated:  6,180 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:
* Additional Content Installed:

## System Information
* CPU: i7 4790k
* MOBO: Gigabyte GA-z97x-Gaming 3
* GPU: GeForce GTX 980
* RAM: 20gb DDR3

**Comment by artdude543** [comment]
Try disabling the Mobendz mod, update your GPU drivers. Ensure the game is using them. Otherwise, this is not our issue sadly as your system is having issues trying to keep up with the rendering and is failing to do so.

**Comment by Ulfsson** [comment]
Although i doubt my system isn't able to run this mod pack, as i have seen other people with worse computers run it, i concede it may be something on my end. However, i cant see how my pc has anything to do with the weird collision bug that happens when trying to walk around. It only happens when touching the top of a block and doesn't happen when flying. I went into creative mode and flying around is normal, however when i land back down it still spins out for some reason.

I really like the look of this modpack and was excited to play it, unfortunately these issues have rendered it unplayable. Thanks for taking the time to help.
