### ISSUE TITLE
Add [Diet Hoppers]

### ISSUE THREAD

**Issue by MrDj200** [DarkPacks/SevTech-Ages#2704]
## Context

This mod changes the collisionbox of vanilla Hoppers. 
That allows you the access an inventory below the hopper.
Here is the situation that made me write this Request:
![PressureChamber from Pneumatic craft](https://i.imgur.com/hAA7iU1.jpg)
(This is a Vanilla Hopper on top of a PressureChamber from PneumaticCraft)

I can't access the Interface of the Block beneath the Hopper, which means I need to remove it before checking for problems.

## Mod Details
* Name: Diet Hoppers
* CurseForge Link: https://minecraft.curseforge.com/projects/diet-hoppers

**Comment by justinrusso** [comment]
https://github.com/DarkPacks/SevTech-Ages/issues/1092

**Comment by Jandakast** [comment]
This causes issues with other hoppers and as such will not be added.

https://github.com/rwtema/DietHopper/issues/5
