### ISSUE TITLE
betterwithmods lag

### ISSUE THREAD

**Issue by dodgythoughts** [DarkPacks/SevTech-Ages#2706]
using latest version
overworld TPS was around 8 or 9 
using laggogles i found that betterwithmods saw was causing it. I removed this block and tps went back up to 20.

not sure if it logs results somewhere... if you want any logs let me know.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
