### ISSUE TITLE
BAD INFORMATION: Language display of L key (SevTech progress) in Minecraft game world

### ISSUE THREAD

**Issue by Twlilght-Dream-Of-Magic** [DarkPacks/SevTech-Ages#2709]
## Bug Report

Minecraft game display language has changed, Press L key, then display game world process from player or team in the (SevTech:Ages) and mod user interface support by (Mod Pack Utilities).
But display language not changed of (SevTech:Ages) mod package user interface.

## Expected Behaviour

(Null)

## Possible Solution

(Null)

## Steps to Reproduce (for bugs)

1. Lanunch minecraft and forge mod from java support
2. Create one game world, config equal to "SevTech_V2" or config equal to "Default"
3. Go to settings menu and change minecraft game language.
4. Press L key, then display game world process from player or team in the SevTech:Ages mod package. (But display language not changed.)

## Logs

* Client/Server Log: (No need this text file)
* Crash Log: (Not exist this text file)

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_172 (Build 170114)
* Launcher Used:MultiMC 5 (Version 0.6.2-1222)
* Memory Allocated: 4096MB-8792MB
* Server/LAN/Single Player: (Online Player Name: Twilight_Magical)
* Optifine Installed: False
* Shaders Enabled: False

## Server Information
* Java Version: 1.8.0_172 (Build 170114)
* Operating System: Windows
* Hoster/Hosting Solution: (Null)
* Sponge (Non-Vanilla Forge) Server: (Null)
* Additional Content Installed: (Null)

**Comment by justinrusso** [comment]
We welcome any PRs for translation. We are not familiar with other languages and as such, we are not able to create alternative language support.
