### ISSUE TITLE
3.0.7 Excavation enchant does not work on the obsidian AIOT

### ISSUE THREAD

**Issue by LordHellscream** [DarkPacks/SevTech-Ages#2710]
Version 3.0.7:
Repro:
cheat in a excavation III book, enchant a obsidian AIOT on a vanilla anvil. 
dig some dirt/stone with excavate command like normal
Got warning message saying need excavation modifier or enchantment 

The enchantment works normally on other picks (like swift pick, or other pickaxes)

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
