### ISSUE TITLE
QoL request: Enable IE crusher to crush ingots into dust

### ISSUE THREAD

**Issue by LordHellscream** [DarkPacks/SevTech-Ages#2711]
In age 3, once ore processing is fully automated, you don't usually have any ores at hand. But sometimes it is needed for crafting recipe or alloying in arc furnace. We should be able to crush ingots back into dust in 1:1 ratio.
Another related request: make ingot and dust interchangeable in arc furnace, it's possible to do it with alloy kiln, not sure why It requires dust for some recipes.

**Comment by justinrusso** [comment]
> We should be able to crush ingots back into dust in 1:1 ratio

I believe this used to be how it was... maybe things changed with our re-vamp of that system. @artdude543?

> make ingot and dust interchangeable in arc furnace

This was originally the case but has since changed as it will cause conflicts if they are set up to be interchangeable.

**Comment by artdude543** [comment]
@justinrusso I'll get this one sorted/fixed after work. I know why it happens and how to fix cleanly.

**Comment by justinrusso** [comment]
Ah, this was already fixed for 3.0.8. See 0f0130cd6fa6cb86105a58808827208ddccd4b19
