### ISSUE TITLE
Stardust Not Duping As Intended

### ISSUE THREAD

**Issue by JauntyJaws** [DarkPacks/SevTech-Ages#2712]
## Bug Report
-When attempting to duplicate stardust, I create the 1 block hole, fill it with liquid starlight, and then throw in the rock crystal and the stardust. 
-Then, the celestial crystal cluster forms, and I let it grow until the crystal is emitting white particle effects, but upon breaking it I only receive the new celestial crystal, and ONE stardust back, as opposed to the expected two. I have seen multiple youtubers perform the exact same act as me and get two stardust back from the process, but have not a clue why it wouldn't be functioning properly in my single player world. 

## Expected Behaviour
It is expected that this process of transforming a rock crystal into a celestial crystal would yield two stardust instead of only returning the one input stardust.

## Steps to Reproduce (for bugs)
1. dig out one block from flat ground
2. dump in a bucket of liquid starlight
3. toss in a rock crystal (I was using crystals of lower purity) and stardust
4. break the celestial crystal cluster upon seeing white particle effects

## Client Information
* Modpack Version: 3.0.6
* Java Version: Version 8 Update 171
* Launcher Used: Twitch Forge
* Memory Allocated: 100% 7590MB 
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by justinrusso** [comment]
Please update to 3.0.7 and attempt to replicate the issue there. There were many updates from 3.0.6 to 3.0.7

**Comment by Degonsky** [comment]
Playing 3.0.7
Can tell - if I breack clusters with Silk Touch pickaxe (using tinker's one) stardust duplicates only near 50% of the times. Not sure in luck affects it, but when breacking with other pick,which has luck III on it, it always duplicates.

**Comment by Donav22** [comment]
Agreed. I noticed fewer stardust with silk touch as well. I would not say that my other pick always duplicated, but it did the majority of the time.

**Comment by timmit99** [comment]
I have luck 3 on my tinkers pick and ALWAYS get 2; I'm in 3.0.7.

**Comment by Hazmatik** [comment]
this is how the mod works there is a chance for a second and it's increased w/fortune
