### ISSUE TITLE
Unable to craft Excavate Modifier

### ISSUE THREAD

**Issue by Voidfulqt** [DarkPacks/SevTech-Ages#2713]
## Bug Report
 Simply trying to craft the Excavate Modifier. I tried with different crystals i.e. rock/celestial crystals, but there is no output item.

## Expected Behaviour
 The item should appear in the output slot of the craft as intended.

## Steps to Reproduce (for bugs)

1. Attempt to craft Excavator Modifier
2. Notice after the required materials are placed, the yielding item does not appear.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version: 8 Update 171
* Launcher Used: Twitch Client with Jar Launcher selected
* Memory Allocated: 7168MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Stifling-Bossness** [comment]
#2314
