### ISSUE TITLE
Unable to see the Astral Sorcery constellations on the sky.

### ISSUE THREAD

**Issue by Voidfulqt** [DarkPacks/SevTech-Ages#2714]
## Bug Report
 I have researched 4 constellations but they do not appear on the night sky.

## Expected Behaviour
 The constellations should appear on the night sky during it's certain moon phase.

## Steps to Reproduce (for bugs)

1. Research 1 or more constellations.
2. Notice how there is none of them on the night sky.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.7
* Java Version: 8 Update 171
* Launcher Used: Twitch Client with Jar Launcher selected
* Memory Allocated: 7168MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by artdude543** [comment]
Rending of the constellations is disabled by default as a workaround for people using Optifine. This won't be changed anytime soon.
