### ISSUE TITLE
getting this crash every time the game starts after changing some keybinds

### ISSUE THREAD

**Issue by OmegaRogue** [DarkPacks/SevTech-Ages#2715]
## Steps to Reproduce (for bugs)

1.idk what happened
2.

## Logs

* Client/Server Log: too big for pastebin
* Crash Log: https://pastebin.com/k6ppPuC6

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_161
* Launcher Used: old mc launcher via twitch
* Memory Allocated: 6.400MB
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: no
* Shaders Enabled: no

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:
* Additional Content Installed:

**Comment by artdude543** [comment]
Changing keybinds is buggy in general. We have pre-filled the keybinds which are shipped with the pack. As they work and been tested. Changing them are at your own risk sadly. Some mods updates in 3.0.8 have slight fixes for similar crashing. _But_ the underlying issue will be fixed in time.
