### ISSUE TITLE
Excavation enchant does not work on the obsidian AIOT

### ISSUE THREAD

**Issue by LordHellscream** [DarkPacks/SevTech-Ages#2717]
## Bug Report
Excavation enchant does not work on the obsidian AIOT

## Expected Behaviour
Excavation enchant works on the obsidian AIOT

## Possible Solution
No solution

## Steps to Reproduce (for bugs)
1 cheat in a excavation III book, enchant a obsidian AIOT on a vanilla anvil.
2 dig some dirt/stone with excavate command like normal
3 Got warning message saying need excavation modifier or enchantment

## Logs
Behavior issue, no logs
* Client/Server Log: n/a
* Crash Log: n/a

## Client Information

* Modpack Version: 3.0.7
* Java Version: 8-117
* Launcher Used: Jar
* Memory Allocated: 4G
* Server/LAN/Single Player: Single
* Optifine Installed: n/A
* Shaders Enabled: n/A

**Comment by artdude543** [comment]
You probably have the wrong enchant on the tool.

You need the `Excavate Enchant` not the `Excavation` one.

With the correct enchant the effect works as intended.

**Comment by LordHellscream** [comment]
I used the  same Excavation III enchantment book on regular pick and it worked perfectly.
Are you saying the AIOT requires a complete different enchantment to function?

**Comment by artdude543** [comment]
No the other enchantment is not even supposed to be in the game. The latter is the correct one to be using.

**Comment by LordHellscream** [comment]
Ok, i was very very sure the Excavation III book was obtained through random enchanting books on vanilla enchantment table. I've enchanted over ~books and I had only seen excavation and not the excavate enchant (i can see both from JEI).
What's the expected way obtain the Excavate enchant book?

**Comment by kamyu2** [comment]
You can get it from normal book enchanting, it is just pretty rare.  

Regarding the other enchant and AIOTs, it is an issue with the way Cyclic checks for a valid tool that causes it to pretty much always fail on items with multiple tool types.

**Comment by artdude543** [comment]
Yes it was missed in enchant checks. Its since been disabled so I'd get away from using it.
