### ISSUE TITLE
Crash on crafting Pneumaticraft Speed Upgrade SMP only

### ISSUE THREAD

**Issue by Iorce** [DarkPacks/SevTech-Ages#2722]
## Bug Report

Tried to craft a Pneumaticraft Speed Upgrade in a Crafting Station, both Client and Server crashed.
Does not crash in SSP. Speed Upgrade remains uncrafted.

## Expected Behaviour

No crash.

## Steps to Reproduce (for bugs)

1. Attempt to craft a Pneumaticraft Speed Upgrade in a Crafting Station

## Logs

* Client/Server Log: Requested from server owner
* Crash Log: https://pastebin.com/9aPVGJAm

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_151
* Launcher Used: Twitch App
* Memory Allocated: 6400MB
* Server/LAN/Single Player: SMP Server
* Optifine Installed: no
* Shaders Enabled: no

## Server Information
* Java Version: unknown
* Operating System: unknown
* Hoster/Hosting Solution: unknown
* Sponge (Non-Vanilla Forge) Server: no
* Additional Content Installed: no

**Comment by desht** [comment]
This is fixed in PneumaticCraft: Repressurized v0.6.6.  It should be completely safe to drop that into Sevtech 3.0.7.

**Comment by artdude543** [comment]
Yeah, we have this in dev already! Also @Iorce you need to post-crash logs with the issue. Next time I'll auto close this one due to missing logs but your lucky the dev found it before me :P

_I don't have time to wait if you requested them cos I can't do nothing with out them_
