### ISSUE TITLE
wrong blocks are shown?

### ISSUE THREAD

**Issue by StefanBzockt** [DarkPacks/SevTech-Ages#2723]
## Bug Report
 Wrong blocks are shown

## Expected Behaviour
 Shows the wrong Texture of a block in the chunk. It seems to be an issue with the ages? the netherrack in the nether is shown as low grade charcoal instead of netherrack. also the overworld. for example normal torches will be shown as Lit Fibre torches. OR stone bricks will be shown as normal Cobblestone

## Possible Solution
 IDK
 IDK

## Steps to Reproduce (for bugs)

1.This Bug is always when i log into this game, the chunks are not the blocks they supposed to be. A blockupdate,forces the chunk to get the real texture BUT i must do this for every chunk.

https://prnt.sc/jpxpac

## Logs

* Client Log: https://pastebin.com/QF2McmKX
Server Log: https://pastebin.com/nQGGUR6M 

## Client Information

* Modpack Version: 3.0.7
* Java Version: Currently using Java 1.8.0.171 (64 Bit)
* Launcher Used: Twitch Launcher
* Memory Allocated: 6144 MB given to Minecraft
* Server/LAN/Single Player: Server
* Optifine Installed: yes (Version 1.12.2_HD_U_D2)
* Shaders Enabled: dont use shaders

**Comment by artdude543** [comment]
This is a _you_ issue. Yes, they are hidden as another block. Your staging is not syncing correctly. From the looks your leaving enough time to sync on load, or you have something breaking the syncing. But we can't help on that side.

This is not a pack issue as it would wider and you're the first in a while. All I can advise is try using the args we recommend with the pack https://pastebin.com/hWWUGGHQ memory is good with your config. So you don't need to change that. And just wait for the world to fully load. Alt would be to use something like Java Scan to see what threads are holding up during the network init. But that's an advanced/complete thing to do.

Sorry :/

**Comment by StefanBzockt** [comment]
RIP :( this is not good :/
