### ISSUE TITLE
IE Pump Jack invisible and oriented wrong 

### ISSUE THREAD

**Issue by blakdragan7** [DarkPacks/SevTech-Ages#2727]
## Bug Report
The Pump jack from IE randomly disappears and then re orients itself in a different direction after being made into a multiblock structure. 

## Expected Behaviour
it to stay in the same position and actually render all the time

## Possible Solution
no idea

## Steps to Reproduce (for bugs)
1. Create multi block Pump Jack
2. Wait for a few minutes
3. watch crazy stuff happen

## Logs
* Client/Server Log:  https://pastebin.com/bKZFhgD0
* Crash Log: None

## Client Information
I have 2 SLI 970s on an intel processor 

* Modpack Version: 3.0.7
* Java Version: 1.8.0_171-b11 x64
* Launcher Used: Java launcher (to make using the newer java version easier)
* Memory Allocated: 8022 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: Tried with both, it happens with and without optifine
* Shaders Enabled: No

**Comment by blakdragan7** [comment]
here is a picture showing the invisible issue
![pic](https://user-images.githubusercontent.com/5482645/40882662-045b0426-66b7-11e8-93aa-4b434f4cc94c.png)

**Comment by artdude543** [comment]
This is _kind of fixed in 3.0.8_ and it's also a bug in MC itself with model rendering. Restarting the game would resolve this issue. However, if it still happens to try checking that it's not built over a chunk border if so move the machine to see if this helps.

But due to it being a bug beyond the scope of the pack. We can't help with this one. Sorry :/

**Comment by blakdragan7** [comment]
Ok so i did some testing. IE and IP in it's own modpack on minecraft 1.12.2 forge 14.23.4.2707 does not do this. Any part of the chunk doesn't do this. Same version for both mods. Going to try and update forge for sevtech and see if that works.

**Comment by blakdragan7** [comment]
That didn't fix it. Also logging out and re logging makes it show right for a few seconds but then it just goes away after about 2 seconds.

**Comment by blakdragan7** [comment]
Another update, I have tired near water and with and without optifine in standalone pack and nothing happened . So far I can only reproduce in sevtech. Going to try new world in sev tech as well

**Comment by blakdragan7** [comment]
odly enough just rotating the orientation of the multiblocked stopped it from happening. If anyone else runs into this problem just try spinning the multibock 90 degrees and it should go away on it's own.
