### ISSUE TITLE
Soggoth toomanygraves conflict

### ISSUE THREAD

**Issue by Sheepingtin** [DarkPacks/SevTech-Ages#2730]
## Bug Report
Soggoth deletes graves from toomanygraves losing all items and they are way to hard in general for this stage of the game. /tmg-restore [player] [date-time]

## Possible Solution
Turn on keep inventory /gamerule keepInventory true
Remove and install another grave mod 

sev 3.0.7

**Comment by z0mb13m4n** [comment]
Yeah this issue is the worst for this mod. Big thumbs down.

**Comment by artdude543** [comment]
Duplicate of #2429
