### ISSUE TITLE
Automated User isn't collecting Wildberry Bushes properly

### ISSUE THREAD

**Issue by TheReYzz** [DarkPacks/SevTech-Ages#2731]
## Bug Report
Automated User isn't collecting Wildberries properly. Wildberries from Bushes dissapear but they dont drop or appear in the User

## Expected Behaviour
It should collect Wildberries and drop them or put them in the Automated User

**Comment by pjc21** [comment]
Also came across this issue with Cyclic's Automated User when trying to automate red dye from wildberries. Ended up using an Item Router from Modular Routers.
- Activator Module's to right click on the bushes
- Sender Module Mk3 to send the buffer to a chest.

![2018-06-03_18 27 13](https://user-images.githubusercontent.com/4660190/40884691-f78375d0-675b-11e8-8cf5-908953ed94b3.png)
![2018-06-03_18 22 14](https://user-images.githubusercontent.com/4660190/40884695-0cb13212-675c-11e8-82f1-5bbbbce5dc50.png)

- Each of the 4 Activator Modules set to a different direction.
![2018-06-03_18 22 25](https://user-images.githubusercontent.com/4660190/40884735-aaa515a6-675c-11e8-97e1-51fc13852d41.png)

- The MK3 Sender Module can link to any storage chest in any dimension.
![2018-06-03_18 32 58](https://user-images.githubusercontent.com/4660190/40884738-b2d5a100-675c-11e8-82a9-0c7d808f193c.png)

**Comment by artdude543** [comment]
This is known due to staging and the block, not understanding. This _may_ be resolved in 3.0.8 or moved to 3.0.9 as we've found some new bugs fixing this one.

Closing this one and tagging back to the main one we are using for tracking #1692
