### ISSUE TITLE
Error when connecting/playing 

### ISSUE THREAD

**Issue by I3imbo** [DarkPacks/SevTech-Ages#2734]
Hello everyone,

Me and my gf are trying to play SevTech on a Hamachi hosted Server (I host it). We are playing on the modpack Version 3.0.7 and at the beginning we had no Problems at all. 
At some point, my gf started to get dcs while ingame and problems when Connecting. When we tried to discover the Betweenslands it happened even more often. Right now she cant even move 1 block before getting kicked again. Here is the Error log:

[log.txt](https://github.com/DarkPacks/SevTech-Ages/files/2065864/log.txt)
 
It would be nice if someone could help us, since we were enjoying the pack very much so far.

**Comment by I3imbo** [comment]
[debug.log](https://github.com/DarkPacks/SevTech-Ages/files/2065899/debug.log)
[latest.log](https://github.com/DarkPacks/SevTech-Ages/files/2065900/latest.log)
 
okay, heres everything. I just now deinstalled JourneyMap on the Server and both clients, because i read, that there is an issue with that. I can play just fine when im alone on the Server now, but when my gf tries to join she gets a "lost connection: disconnected" error, the server times out and i get kicked too...

**Comment by artdude543** [comment]
Going to throw this one to the Discord Support. Normally this is down to bad port forwarding also Hamachi is ehhh well yeah. SevTech requires a decent network stream from all parties connected. Any drop in connection will result in a disconnect.
