### ISSUE TITLE
Logistics "Handheld Crafter" Crash

### ISSUE THREAD

**Issue by FyreDrop** [DarkPacks/SevTech-Ages#2735]
## Bug Report
Using the Handheld crafter from inductive logistics and setting it to craft one of the recipes that don't function due to the "age block" in the regular auto-crafters will crash the client, and make the game unjoinable. Specifically tested with Actually Additions cheese.

## Expected Behaviour
Handheld crafter should batch craft using player inventory as a buffer. 

## Steps to Reproduce (for bugs)

1. Using handheld crafter, input milk bucket and egg in shapeless crafting.
2. Set batch to craft at least 1.
3. Set to "always run". 

## Logs

* Client/Server Log: ~~somehow exceeds pastebin's "free use" file size...
* Crash Log:  https://pastebin.com/fD8XZyvW

## Client Information

*Modpack Version: 3.0.7
*Java Version: 1.8.0.25
*Launcher Used: Twitch app
*Memory Allocated: 9,472 MB
*Server/LAN/Single Player: Single Player/LAN
*Optifine Installed: No
*Shaders Enabled: No

**Comment by CD4017BE** [comment]
It seems that the mod that disabled the recipe, did that by just setting its result to empty ... which is not a good idea and may likely cause other problems too, better remove the recipe entirely from the recipe list.

However, I now fixed the Portable Crafter to be robust against such malformed recipes (not crash anymore). It'll be in the next release.
