### ISSUE TITLE
Immersive Tech steam turbine only connects to IE connectors and no other power system

### ISSUE THREAD

**Issue by Midaychi** [DarkPacks/SevTech-Ages#2736]
## Bug Report
The steam turbine alternator from Immersive Tech is only able to connect to immersive engineering connectors and cannot connect to any other power system without using the IE connectors as an adapter. This means that the alternator can produce far more power than you can ever remove from it.

## Expected Behaviour
Expected to be able to use other forms of power connection, like every other immersive tech machine.

## Possible Solution
The issue might be fixed in 1.3.10, which was recently released a few days after this bug was reported on their issue tracker and the author claiming it should be fixed.

## Steps to Reproduce (for bugs)

1. Have steam turbine alternator power ports
2. Rub anything besides an IE power connector on it to no effect

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8
* Launcher Used: Twitch
* Memory Allocated: 4 gigs
* Server/LAN/Single Player: server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Jandakast** [comment]
1.3.10 of Immersive Tech still has an issue with Mekanism Universal cables attaching directly to the Alternator. My solution to this for now is putting a battery/energy cube/powercell connected directly to each of the 6 alternator power outputs, then connecting cables to those batteries. 

Reported to Mod Dev
https://github.com/FerroO2000/Immersive-Tech/issues/62

**Comment by Midaychi** [comment]
Nothing from the author since the issue was posted and linked. Rip.
