### ISSUE TITLE
Add Thermal Dynamics to the pack because Mekanism cables and transporters are broken

### ISSUE THREAD

**Issue by SlyCedix** [DarkPacks/SevTech-Ages#2737]
## Context
It's a known issue that cyclic power cables do not input energy to sided machines properly, in addition to their fairly limited throughput. 
PrinceOfAmber/Cyclic#788

Mekanism cables need to be relaid often to continue working. 
aidancbrady/Mekanism#4676

Without either of those cables, the options for power transfer are:
 * BC Kinesis pipes, which are severely limited in throughput.
 * Immersive Engineering HV Wires, which have decent throughput on (32768 rf/t), but you have to risk having non-insulated cables everywhere
 * Actually Additions Energy Relays, which are gated behind the atomic reconstructor
 * RF tools wireless powercells, which are prohibitively expensive in stage 5 when the need for high throughput energy cables starts to manifest iteslf.

RF tools powercells can be made cheaper by using mekanism pipes to distribute power contained within a single chunk, but those still need to be relaid quite frequently.

## Solution
Add Thermal Dynamics and Thermal Foundation(Disabling the ores of course) which is only ducts, this shouldn't be too many block IDs, as I'm pretty sure Dynamics only adds 4 block IDs, and Foundation adds 8 without any configuration, I will test some settings to see if I can get that number down

**Comment by Stifling-Bossness** [comment]
As said by @artdude543 in #1940 
> None of CoFH mods are being added to the pack ever. That as we don't have any space Id's for the mods as they are reserved for other mods.
Mekanism are working on the issue but it's going to take time to do so.

**Comment by SlyCedix** [comment]
Mekanism has been working in the issue for 9 months, at this point it seems like it will not get fixed until they rewrite the whole cabling system.

**Comment by SlyCedix** [comment]
I should point out that it doesn't necessarily need to be the thermal mods, but currently there is no working logistical item transport or high capacity energy transport in the pack for the early late game.

These 2 mods add about 12 Block IDs together, which is why I suggested them, I could not find a mod that added fewer for the same result.

**Comment by SlyCedix** [comment]
Also not quite sure why the block ID limit is a problem at all, considering this is a thing:

https://minecraft.curseforge.com/projects/notenoughids

**Comment by justinrusso** [comment]
>There's also NotEnoughIDs

People need to stop recommending Not Enough IDs. The mod has issues corrupting worlds and we are not taking that chance. The mod also has not been touched in nearly a year. You state that yourself.

>These 2 mods add about 12 Block IDs together

We only have 7 IDs.

**Comment by artdude543** [comment]
Nothing from CoFH is being added period. Nor are any of the ID shifting mods being used.

**Comment by artdude543** [comment]
To add a note the Cyclic issue is being looked into, as with the Mekanism issue. Yes, it's taking time for them. But they have lives a really busy IRL jobs. So if you want it done faster pay one of them and I'm sure it'll get done!
