### ISSUE TITLE
Lost Gold Backpack on the top of a Cragrock Tower.

### ISSUE THREAD

**Issue by NaturalHate** [DarkPacks/SevTech-Ages#2738]
After several hours of exploring the betweenlands and finding just random swamp shit I finally found one of those towers, activating wisps and everything. While I fought my way up there I deposited all the loot to the other crap I found exploring the swamp, inside of my Gold Backpack. The backpack, unlike the simple one sits inside of my inventory, not on my hotbar and I open it by pressing I. Right before I went to the very top I did some repairs, I'm fairly certain that it was still there a that time. However after clearing the top of the spawners and looting the chests and pots I noticed that I cannot press I anymore to open the backpack. Checking the inventory I can confirm that it is simply gone, I looked around and couldn't find anything, stepping down the tower started to "collapse" (kinda) and I had to run down, almost dying thanks to the climbing gloves.
At the bottom I quickly changed to lan mode to enable cheats and spawned in some crates and ender hoppers, placing them in and around the tower with some crates beneath in an attempt to grab my backpack, if I somehow happened to throw it out of my inventory, but unfortunately that did not helped either.
I checked the logs briefly and couldn't find anything either but I'll paste a copy of the part where I added a map marker when discovering the tower to the end where I spawned in the items.

[Clientlog](https://pastebin.com/KEBnwmb5)

Modpack Version: 3.0.7
Java Version: 1.8.0_161
Launcher Used: MultiMC
Memory Allocated: 4GB
Server/LAN/Single Player: SP
Optifine Installed: No.
Shaders Enabled: No.

**Comment by artdude543** [comment]
There is nothing we can do about this. It's not a bug at all. You must off dropped the item. It's gone sorry.

**Comment by NaturalHate** [comment]
Nope.
Don't dismiss me just because you think I'm stupid, I already said I'm sure I did not drop it considering I don't even touch the damn thing, like ever, and don't have it in the hotbar either.

I actually just started the pack up again onto a suspicion, the only explanation that I can now think about.
And that is actually what I can now confirm: 
**It is a bug**, the bug that you can actually shift click the backpack into its own inventory, basically sending the damn thing into the void. So yeah, in my routine of using the fancy shift mouse drag features to quickly move items into the backpack, which is when I moved the packback into itself and then it was gone. So no, not stupid, just expected the game to behave like it should behave, thus experienced a bug.

Doubt it is possible to recover but if anyone know if there's still some way to view the content (I'm going to guess this process does not actually delete the stored data) so I can maybe replace it that'd be nice.

**Comment by artdude543** [comment]
Backpack issues have been known/resolved for a while now. See closed/opened issues. The data is stored on the item itself so once it's gone that's it. Nill/Null/Undefined Gone!

Not sure where you got the _stupid_ thought from. I did not say a word about yourself just said _It's Gone_ Items don't just _vanish_ from inventories you either put it in something or it dropped from your inventory. There are hotkeys for this; you may of accidentally mashed keys and hit it.

Like in regards to the issue. It's resolved.
