### ISSUE TITLE
Spam-clicking `j` will show minimap until you stop spam-clicking

### ISSUE THREAD

**Issue by bretterer** [DarkPacks/SevTech-Ages#2744]
## Bug Report
On a new install of SevTech-Ages, v3.0.7, hitting `j` will flash journey map.  If you spam-press `j` you can see the mini map enough to get your location.  This is available to be done as soon as you start a new world.

## Expected Behaviour
The minimap should not show up when you do not have access to this.

## Possible Solution
Possibly clear the hot-keys for journey map from the start

## Steps to Reproduce (for bugs)
1. download v3.0.7 of SevTech-Ages
2. Create a new world with profile `sevtech-v2`
3. load into the new world
4. spam-press `j`

## Logs
Logs not relevant

## Client Information
* Modpack Version: 3.0.7
* Java Version: 
* Launcher Used: Twitch with JAR Launcher selected
* Memory Allocated: 8GB
* Server/LAN/Single Player: SP
* Optifine Installed: No
* Shaders Enabled: No

**Comment by artdude543** [comment]
This won't get fixed due to how the mods work with blocking certain things. Spam all you need. Blocking of key binds won't happen as this causes other un-intended effects.

**Comment by bretterer** [comment]
Sounds good... Just thought I would mention it.  I didn't see anything about this anywhere.
