### ISSUE TITLE
Non-Item Entities Invisible after traveling between dimensions.

### ISSUE THREAD

**Issue by Qhman34** [DarkPacks/SevTech-Ages#2746]
Currently, when I travel to the Hunting Dimension or the Beneath, mobs are completely invisible. There is no rendering of the player in F5 mode either. Simply closing and reopening the world does not rectify the issue, and it is only resolved when I completely reboot my game.

I hadn't seen anyone else post this problem, so I can only imagine I'm one of the lucky few that have every encountered this strange behaviour. If anyone could enlighten as to what is going on here, that would be great.

On the off chance that this is an actual issue with the modpack itself, then it should be easy to duplicate. Simply entering a new dimension should result in invisible mobs. I should note that this began happening around the time that the quest tree started leading me into the abysalcraft section, so it could have something to do with that as well.

I don't have a crash report, but i can provide the operational log if neccesary. I haven't at this point because pastebin wanted to make me pay to paste the whole log

* Modpack Version: 3.0.7
* Java Version: 1.8.0_161
* Launcher Used: Twitch
* Memory Allocated: 7168 MB
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled: No

**Comment by artdude543** [comment]
This sounds like a memory issue. But this is not a pack issue.

Please try using the following args: https://pastebin.com/hWWUGGHQ and to tweak the memory set to the game, try 6Gb if you can.

Likewise, disable the mods which change how some things are rendered in game. And disable mipmapping these may help. But this is a client issue at the end of the day. Which are also MC bugs on certain systems/setup which we can't fix nor will it ever in 1.12

For further help and support, I'll get the bot to post the Discord link. But as this is not a pack issue. It won't be further discussed on here.
