### ISSUE TITLE
NetworkDispatcher exception

### ISSUE THREAD

**Issue by leocade** [DarkPacks/SevTech-Ages#2751]
## Bug Report

When a player loses connection due to internet issues on their side the server goes into an error loop and the player is unable to connect. They get the message "timed out"

## Expected Behaviour

player should be able to reconnect and console should not spam connection closed by remote host

## Possible Solution

I think it has something to do with the server not correctly removing the player when they disconnect

## Steps to Reproduce (for bugs)

1. player loses connection due to internet issues on their end
2. console goes into an exception loop, slowing down server performance for already connected individuals
3. server eventually crashes (within 4 hours)
4. restarting the server resolves exception loop issue and allows disconnected the player to connect again

## Logs

* Client/Server Log: 
https://gist.github.com/leocade/23faeb0b8b726195dedff2bb7ff8f7c4
The issue is down at the bottom of the log, around lines 3000
* Crash Log:

## Client Information

* Modpack Version: 3.07
* Java Version: 8 64bit
* Launcher Used: atlauncher
* Memory Allocated: 4GB
* Server/LAN/Single Player: server
* Optifine Installed: yes
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.07

* Additional Content Installed: 
spawn commands
world border
chunk pregenerator

## Server Information
* Java Version: 8 64bit
* Operating System: windows 10
* Hoster/Hosting Solution: none
* Sponge (Non-Vanilla Forge) Server: none

**Comment by artdude543** [comment]
Not our fault. This is a server issue with not cleaning the connections. Make sure the system has enough memory available as each connection uses memory. Also, make the server auto reboot after x time.

Forge and MC itself does not have this issue nor it's been seen since early 1.6.x as it was fixed. So this is purely a _you_ issue. Sorry.
