### ISSUE TITLE
Mechanical Squeezer draining all power instantly from Advanced Generators Gas Turbine

### ISSUE THREAD

**Issue by Deepcage** [DarkPacks/SevTech-Ages#2752]
## Bug Report
When hooking up the mechanical squeezer from Integrated Dynamics, via aGalacticraft Aluminum Wire, to Advanced Generators Gas Turbine, all stored energy is instantly consumed.

## Expected Behaviour
It should only consume the power it needs to fill its 100.000 RF capacity and whatever it needs to operate. Nothing more.

## Possible Solution
Sorry, i wish i knew.

## Steps to Reproduce (for bugs)
1. Produce power with advanced generators turbine
2. Store power in any of the same mods Power Capacitors (i was using High Density)
3. Connect Aluminum Wire to Flux generator
4. Connect Mechanical Squeezer to Wire
5. Poof! All energy produced/stored = gone!

## Logs
N/A

## Client Information
* Modpack Version: 3.0.7
* Java Version: 8 update 161
* Launcher Used: MyM Launcher (www.mineyourmind.net)
* Memory Allocated: 8GB
* Server/LAN/Single Player: Online Server
* Optifine Installed: No
* Shaders Enabled: Yes

## World Information

* Modpack Version world created in: 1.12.2

* Additional Content Installed: Unknown.

## Server Information
Sorry, i wish i knew, just an end-user.
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by Pultex** [comment]
I thought that is why the added the power adapter
