### ISSUE TITLE
Inductive Logistics Tank Crafting Crash

### ISSUE THREAD

**Issue by DarkHeroZark** [DarkPacks/SevTech-Ages#2753]
## Bug Report

   Crafting recipes recognize the Inductive Logistics Tanks as buckets of liquid in applicable recipes, but trying to craft the item crashes the game.

## Expected Behaviour

   Either the tanks should not be recognized as buckets of liquid for crafting or they work as bucket replacements to make liquid crafting a less tedious process

## Steps to Reproduce (for bugs)

1. Get an Inductive Logistics "Fluid Tank | Large" filled with some buckets of Lubricant 
2. Use a Tinker's Crafting Table to craft Pneumaticraft Security Upgrades
3. Grabbing the Security upgrade should crash the game.

## Logs

* Client/Server Log: https://pastebin.com/X5MtwFRU
* Crash Log: https://pastebin.com/78mThyfW

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_171
* Launcher Used: Twitch
* Memory Allocated:  6 GB
* Server/LAN/Single Player: Server
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by artdude543** [comment]
@desht was this fixed in newer builds? Or is this one known about?

**Comment by artdude543** [comment]
Okay looking at the commits this was fixed in newer builds. So marking this as fixed in dev!

**Comment by desht** [comment]
Yep, can confirm this fixed in PNC:R 0.6.6.
