### ISSUE TITLE
Download Error "Better Builders Wands" Twitch

### ISSUE THREAD

**Issue by PROTOSSxHERO** [DarkPacks/SevTech-Ages#2754]
## Bug Report

Twitch will not download properly. Download stops sometime after 220/239 Mods downloaded because of "Better Builders Wands"
## Expected Behaviour

Download the pack from twitch, Will not fully download, 2 errors: Profile Error and Addon Install Error
## Possible Solution

DON'T USE TWITCH. Use the ATLauncher. It worked for me then.
## Steps to Reproduce (for bugs)

1.https://media.forgecdn.net/files/2443/194/BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar
gives me 
"This XML file does not appear to have any style information associated with it. The document tree is shown below.
[Error]
[Code]AccessDenied[/Code]
[Message]Access Denied[/Message]
[RequestId]9DD0CADD15E7BD31[/RequestId]
[HostId]
Yu/Mf3Ihm3TQ4xL2M1UIDZGKkyKGTL+UnzmMfhzQcxx61sa8DvAPzVFBhIGtJxxgSgav0PqCxDQ=
[/HostId]
[/Error]"
2.Addon Install Error
"Twitch encountered a problem during this operation

Error:
Failed to download: https://files.forgecdn.net/files/2443/194/BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar"

3. Profile Error
Literally same this as 2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

6 gigs memory to minecraft through twitch
4 MB allocated to addons through twitch
* Modpack Version: SevTech: Ages - 3.0.7
* Java Version: 1.8.0_161
* Launcher Used: Twitch
* Memory Allocated: 6 GB
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

**Comment by artdude543** [comment]
Not our issue. This is a Client Issue with Twitch. Use ATLauncher is the issue is still happening after an hour.
