### ISSUE TITLE
Crash When Entering Betweenlands (First Visit)

### ISSUE THREAD

**Issue by Newman2393** [DarkPacks/SevTech-Ages#2755]
General
Game Crashes when entering Betweenlands for the first time. I can see the hotbar when items should be, health, hunger, and some other bar I've never seen before. The word "Wilderness" appears on the screen. Game goes not responding, and then crashes.

Issue / Bug

- Game crashes when loading Betweenlands

Expected Behavior

- The items I carried in to show up, and to actually see the terrain.

Possible Solution

Not really sure what to do here. I see several entries in the logs that say "Could not find any matching ingredients to remove". Some message from JEI.

Steps to Reproduce (for bugs)
I walk in to the portal, and crash.

Logs

Patebin: https://pastebin.com/bmtDmJar

Client Information

Modpack Version: 3.0.7
Java Version: 1.8.0.171 (64 Bit)
Launcher Used: Jar Launcher
Memory Allocated: 8,192 MB
Server/LAN/Single Player: Single Player
Resourcepack Enabled?: No
Optifine Installed?: No.

**Comment by SudzBud** [comment]
I get same issue with any portal. Betweenlands, The beneath, and Nether. If my interface shows up, it is brief empty and then back to Server lists.

**Comment by artdude543** [comment]
Thank you for reporting an issue!

It appears you are logging an issue for a crash, but you have either not uploaded to PasteBin/Gist etc.. of the actual crash report. This report contains the needed data to help to locate the cause and a possible fix. To find the file needed please review the following for either of the launchers.

## Twitch
1. Select the SevTech Pack to view the modpack page.
2. Click the `...` button on the top right just next to `Get More Content`.
3. Click `Open Folder`.
4. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it. 

## ATLauncher
1. Select the Instances tab, then scroll to the instance of SevTech.
2. Click the bottom right button named `Open Folder`
3. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it.

For any other launcher should be a similar process, if not consult with Google if you are not sure on how to find the folder. The information contained in these reports is critical for getting the crash fixed/looked into.

## Servers
For servers the process if farilt simple. Go the folder cotaining all the sever files/folder and you will see a folder called `crash-reports` follow the same process as above by getting the lastest one and uploading it to a text store.

**Comment by Newman2393** [comment]
I don't have a crash-reports folder. I'm guessing that's because it's actually Java that crashes. I should have mentioned that initially, so when it crashes it boots me out of minecraft completely, and then comes back with the log from the pastebin.

**Comment by SudzBud** [comment]
I have a crash-reports folder, but am not getting a report log generated on the crash. I do get the error:
![image](https://user-images.githubusercontent.com/8115888/41000796-1aaa8a12-68dd-11e8-8571-fc6d65135df4.png)
Connection Lost
Internal Exception: java.nio.channels.ClosedChannelException
Back to server list

Playing in Single Player World.
