### ISSUE TITLE
Can't clean my Dirty Plates!

### ISSUE THREAD

**Issue by WizzleWuzzle** [DarkPacks/SevTech-Ages#2758]
## Bug Report
Through Remnant trading, you can obtain both "Beef on a plate"and "Wool Cloth". If you eat the beef, you're left with a "Dirty Plate" yet no way to clean it because combining it with a wool cloth does not work.

## Expected Behaviour
I expect to be able to do my dishes like a good boy.

## Possible Solution
Please allow the Plate recipie, the plate on a food recipe, the wool cloth recipe, and finally let me do my chores by allowing me to clean my dishes

## Steps to Reproduce 

1. Trade with Remnant to get Beef on a plate
2. Trade with Remnant to get Wool Cloth
3. Eat Beef on a plate and get a dirty plate
4. Let the dirty dishes pile up

**Comment by artdude543** [comment]
This is intentional. As the plates are hidden from the game and not meant to be used. Trading is still a mechanic as we don't remove the trade. But we're not going to add a cleaning recipe back in. Due to the fact, the item is not intended for use in the pack.
