### ISSUE TITLE
Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by Genotypek** [DarkPacks/SevTech-Ages#2761]
## Bug Report
Hello. Me and my wife have a problem with minecraft 1.12.2 forge server with mods. We want to play together SevTech Ages modpack, everything went smoothly to the moment of connection to the server.

Server is running on my PC on LAN using Hamachi or even WAN with port fowarding.

Every time she tries to connect to my server, she's getting kicked from it instantly. The error is: "Connection Lost. Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host." OR "Connection Lost. Timed out."

It's definitely server fault. Bukkit 1.12.2 works perfectly, but of course it can't run any mods. I decided to add this property into start bat file: "-Dfml.readTimeout=900" to give player more time to connect. It changed nothing.

So 1.12.2 vanilla doesn't work. 1.12.2 with SevTech Ages modpack doesn't work. Bukkit 1.12.2 Works perfectly.

We tried to run vanilla 1.12.1 server - works perfectly too!

That's why I think it's 1.12.2 server fault. I even tried to use several forge versions, but ineffectively.

I have read in the Internet that there's a possibility to connect 1.12.2 servers using 1.12.1 minecraft client, but it says that client is outdated and I have to update it, so it doesn't help.

We really want to enjoy this modpack, it's brilliant.

## Possible Solution
I don't completely know.

What didn't help:
- Updating java to the latest 172 build,
- Changing starting bat file java arguments,
- Modifying server.properties file,
- Using Hamachi (VPN),
- Using WAN port forwarding,
- It's not about my internet speed,
- Changing java security settings,
- Turning off firewall/antivirus and/or making exceptions for firewall,
- Allocating more RAM,
- Changing priority for Java and Minecraft launcher,
- Wiping DNS cache,

When server works:
- When we're in the same phisical LAN, next to us each other, BUT not by server files. Only by singleplayer "Open for LAN".

Everything works the same in both ways. Me as host or She as host.

## Steps to Reproduce (for bugs)
1. Start the server.
2. Connect to the server.

## Logs
* Server Log:
Part1: https://pastebin.com/vjwiKruT
Part2: https://pastebin.com/ZU77z10q
Part3: https://pastebin.com/udsenRAb

* ClientLog:
https://pastebin.com/9peJuYGS

## Client Information
* Modpack Version: 3.0.7 (latest)
* Java Version: Java 8 JRE x64 Update 172
* Launcher Used: Original Minecraft Premium Java Edition
* Memory Allocated: 6GB Client
* Server/LAN/Single Player: Server(Port fowarding)/LAN (VPN Hamachi)
* Optifine Installed: Yes
* Shaders Enabled: Nope

## World Information
* Modpack Version world created in:
SevTech Ages 3.0.7 (Latest)
* Additional Content Installed:
Nothing

## Server Information
* Java Version: Java 8 JRE x64 Update 172
* Operating System: Windows 10 Home (x64)
* Memory Allocated: 8GB server
* Hoster/Hosting Solution:  Hosting on the same PC on which I'm playing.
* Sponge (Non-Vanilla Forge) Server: No

Greeting, Genotypek.

**Comment by artdude543** [comment]
To add a couple of things to this.

- This is not an issue with 1.12.2 servers don't believe what the internet always says.
- This modpack has a lot of mods/systems which require a lot of talking back and forth from the client -> server and backward. If you have any kind of slow connection client side or server side you'll lose connection.
- Hamachi is not ideal either as that itself has latency issues which will make this issue occur more often.
- But your memory allocation is good!
- If I'm assuming this correctly. Do you live in the same house? If so just connect directly to the machine which is running the server. Otherwise maybe looking in dedicated hosting may be an option.

**Comment by Genotypek** [comment]
For the next 4 months we won't live in the same house.
I easily connected my 2 laptops to the server which were in my house. I'm trying to make this server work 4 days already . I know that Hamachi isn't good for that, that's why I made port forward on my router and firewall, then properly configured server.properties.
That's really strange because clear vanilla 1.12.2 server without mods/forge has the same error.
1.12.2 bukkit works fine, 0 problems.
1.12.1 vanilla works goo too.

I didn't take this opinion from the internet, but from my own research. Is it possible to run the server not using vanilla server file? Like bukkit? (Which works fine)

**Comment by artdude543** [comment]
- Bukkit won't work for this kind of setup. The only alternative is Sponge (Which is the next generation of server thingy)
- Our next major update which changes over to a newer system for syncing and handling staging will fix a major issue with the networking code. But Vanilla servers (I.E. No mods will always work regardless of setup) this pack is network intensive as I've stated. Bukkit has minimal networking going on after connection success. Likewise for Vanilla.
- I know dedicated servers are generally fine for connections. But have noticed with all the reports we get about issues connection/booting. 9/10 are locally hosted solutions using Hamachi and/or port forwarding. They could be set up wrong but we're not in the realms to dig into that, our support only covers so much before we don't have the time/resources to help out further.
- I'd always recommend using dedicated/purchases servers as you'll get the support from the host with issues and they are tested to ensure they work. I understand about costs and regards but it's a thing of cost = support, and self-hosted meaning crawling the net and finding the help.
- I can't think of anything else off the top of my head you could try before I have to step away from other jobs/actions to help out further. Sorry.
