### ISSUE TITLE
Galacticraft Sealed Space Block additions

### ISSUE THREAD

**Issue by Iorce** [DarkPacks/SevTech-Ages#2764]
## Context

Galacticraft is supposed to add modifications of the Glass block as oxygen sealing blocks for the Oxygen Sealer (machine needed to fill rooms in space with oxygen). Chisel and Tinker's Construct glass blocks however are not detected automatically (all solid blocks count as sealing by default, Galacticraft tries to find glass-type blocks to add them to the list).
[The Galacticraft Wiki mentions Tinker's Glass as example for a possibly wanted oxygen sealable block that is not detected automatically.](https://wiki.micdoodle8.com/wiki/Sealed_space#Working_with_other_mods)

As a more personal note, Tinker's Construct Clear Glass is amongst the least-invading of all glass types and my favorite glass type for all glass buildings, especially glass domes/cubes. When using a Celestial Gateway for inter dimensional transport, an encasement made of Clear Glass also allows for the full beauty of the Celestial Gateway structure on minimal space.

A Clear Glass encasement is the perfect habitat for test subjects as they will feel like they are not imprisoned at all.

Also please remove Glass panes from the list, they even count if used in the ceiling/floor.

<details><summary>For the time being, the following near-invisible glass types work</summary>

* AE2 Quartz Glass & Vibrand Quartz Glass
* PneumaticCraft Pressure Chamber Glass</details>

## Config/Script Details
* Link: [Galacticraft Sealable blocks for Oxygen Sealers Wiki entry](https://wiki.micdoodle8.com/wiki/Config#Sealable_blocks_for_Oxygen_Sealers)
* Gist: [core.conf additions](https://gist.github.com/Iorce/53c08a8742d010c7371b530f472d9ac1)

**Comment by artdude543** [comment]
Am I presuming you have tested the config change?

**Comment by Iorce** [comment]
I actually have not yet, will do tomorrow.
Format is consistent with the how to on the Galacticraft wiki though.

**Comment by Iorce** [comment]
It works except for chisel:glass:* and dyed variants. Can't exactly put my finger on it but my guess is on the unlocalized name which contains tile. ...

**Comment by Iorce** [comment]
I take it back, didn't have a lot of time 8 hours ago, I'll get back to it later today (in a couple hours) and look for the error.

**Comment by Iorce** [comment]
![2018-06-06_18 53 47](https://user-images.githubusercontent.com/23401986/41053114-02a467f6-69bb-11e8-8446-bc6bcd90c845.png)
From left to right: 

 * PneumaticCraft Pressure Chamber Glass (Sealed)
 * Primal Core Soul Glass (Sealed)
 * Tconstruct Seared Glass (Not Sealed)
 * Natura Heat Glass (Not Sealed)
 * Natura Soul Glass (Not Sealed)
 * Ferdinant's Flowered Dyed Glass (red) (Not Sealed) (Assuming it doesn't work for any color (different Meta IDs)
 * Mekanism Structural Glass (Not Sealed)
 * Chisel Red Stained Glass (Panel) (Not Sealed) (Assuming it doesn't work for any color (different name) or texture (different Meta IDs)
 * Tconstruct Clear Glass (Sealed)
 * Tconstruct Clear Light Grey Stained Glass (Not Sealed) (Assuming it doesn't work for any color (different Meta ID's)
 * Actually Additions Greenhouse Glass (Sealed)
 * Immersive Engineering Insulating Glass (Not Sealed)

The Not Sealed entries consist of:
 * All glass types that have Meta ID (Mekanism Structured Glass, IE Insulating Glass, Natura Heat & Soul Glass, colored glass types, texture variating glass types (Chisel)) 

And, additionally, Tconstruct Seared Glass.

**Comment by Iorce** [comment]
Updated the gist, testing it now but I changed all... irregularities.

**Comment by artdude543** [comment]
Sweet thanks. I'll test it after work and merge it into the pack! Thanks for your work on this!

**Comment by artdude543** [comment]
Okay, so some stuff errors in the console which is fine. But we need to fix them for the next update. And go over it in more detail.

_I did a speed check over and missed the console errors so my bad but we're pushing 3.0.8 now so will be left behind_

**Comment by Iorce** [comment]
Typo in mod name: ferdinandsflowers (I spelled it ferdinantsflowers) it's fixed now.

**Comment by valrosss** [comment]
is is possible to add RF tools Shield Blocks?

**Comment by Iorce** [comment]
Yes, if you can give me the ID. (Modname:blockname:meta)

**Comment by artdude543** [comment]
Going to close this one now. As we've added the main blocks. And I'm not happy to add RF Shields to the listing. You're forced to either use GC methods or build a base. Not cheat with a "magical" shield.

😄
