### ISSUE TITLE
Excessive Oil/Diesel/Water glitch

### ISSUE THREAD

**Issue by krisbjornsen** [DarkPacks/SevTech-Ages#2767]
## Bug Report

If you break a BC Factory Tank with at least 1 bucket of Oil, Diesel, or Water in it and get shards of any of them, you can place the shards as inputs into the Solar Tower(Water) or Distillation Tower(Oil/Diesel), and 1 shard will completely fill up the input tank for that tower. Presumably this would work for any 'input' which would allow a liquid shard to input to an internal reservoir for a multiblock construct.

## Expected Behaviour

A single shard of perhaps 500 mB of liquid should only input the same quantity of liquid to a tank.

## Possible Solution

Make sure the input values are being properly tracked with shards.

## Steps to Reproduce (for bugs)

1. Place empty Tank on a block.
2. Input 1 Bucket of Target Liquid into Tank.
3. Use pick to break Tank, producing 1 Tank and 2 500 mB shards of Target Liquid.
4. Place 1 shard into blue input square of construct with matching internal liquid storage.
5. Profit.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.6
* Java Version: latest as of June 4, 2018
* Launcher Used: ATLauncher
* Memory Allocated: 4 GB
* Server/LAN/Single Player: server
* Optifine Installed: unknown
* Shaders Enabled: unknown

## World Information

* Modpack Version world created in:

* Additional Content Installed:

**Comment by justinrusso** [comment]
Please update to the latest pack version before reporting issues. This has been fixed.
