### ISSUE TITLE
Evershifting fountain deletes containment chalices

### ISSUE THREAD

**Issue by Midaychi** [DarkPacks/SevTech-Ages#2770]
## Bug Report
In astral sorcery, you are supposed to be able to build a structure and put an evershifting fountain in the center middle, a neuromantic prime underneath the fountain and a containment chalice above. Currently, I found a whiteish blue liquid with the isofosic resonator and build the well above it with the structure and stuff exactly as depicted in the book, and placed a chalice nearby outside of the ring to catch the liquid it should mine up. Placing a bucket into the chalice spawns a spark entity of starlight liquid, which travels down to the neuromantic prime, and as soon as the poof happens the chalice spontaneously deletes itself and no liquid is mined.

## Expected Behaviour
Expected the neruomantic prime to get powered and start delivering liquid to nearby chalices.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)

1. Find a liquid squirty souce with the isofosic resonator.
2. Build well and structure exactly as depicted in book
3. place chalice above and neuromanic prime below, and at least one chalice additional within 16 blocks of the fountain (to catch the liquid that should get mined but doesn't)
4. Place bucket of starlight liquid in the chalice above the well, hoping for it to be powered, but instead watch your dreams get crushed in a fizzling cheese shower.

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8
* Launcher Used: Twitch
* Memory Allocated: 4gb
* Server/LAN/Single Player: server
* Optifine Installed: NO
* Shaders Enabled: nope

## World Information

* Modpack Version world created in: 3.0.5

**Comment by Midaychi** [comment]
As an addenum, in a different structure I just had 2 chalices touching against the infusion altar and was collecting starlight from the light wells just fine.  Everything seemed fine until I put an object into the infusion altar, after which all existing sparkles and both chalices spontaneously deleted themselves from existence. 

This might be caused by a mod interaction or something, possibly the camouflage mod? Something that checks on entity updates or something is just straight up deleting chalices. It happens also if you pour liquid near the chalice.

**Comment by Midaychi** [comment]
Breaking the block you placed the chalice on also deletes it, even if you placed it on a wall.

**Comment by DralinZero** [comment]
I found the following steps to reproduce this bug:

1. Place a chalice in the world.
1.2. Place block next to it -> nothing happens.

2. Pick up the chalice with the Cyclic Sack of Holding.
3. Place it down somewhere else.
4. Place a Block next to it.
5. Chalice is now gone.
