### ISSUE TITLE
Can't see amount of liquid contained in a containment chalice + carry on doesn't work.

### ISSUE THREAD

**Issue by Wigalot** [DarkPacks/SevTech-Ages#2772]
## Bug Report
There is no item or way of seeing how much liquid is in a containment chalice. Even mousing over does not show. (I'm in Age 5)

## Expected Behaviour
Usually mousing over a containment chalice shows the volume of liquid contained. 

## Possible Solution
Allow in waila in appropriate age?

## Steps to Reproduce (for bugs)
1. Place containment chalice
2. Add liquid
3. Mouse over
4. Fail

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8
* Launcher Used: Twitch
* Memory Allocated: 4GB
* Server/LAN/Single Player: LAN/Single Player
* Optifine Installed: Nope
* Shaders Enabled: Nope

## World Information
* Modpack Version world created in: 3.0.4

Edit: As a side note, I have not changed or edited any configs.

Edit2: I also noticed carry on doesn't work with the containment chalice where as it has in previous versions.

**Comment by Midaychi** [comment]
You also can't see the discovered constellations in the sky, so it's probably something to do with the render method that AS uses conflicting with the render methods Sevtech uses.

**Comment by pjc21** [comment]
@Midaychi - In order to see the discovered constellations in the sky you need to add the dimension ID to the 'skySupportedDimensions' & 'weakSkyRenders' in the AS config.
- config\astralsorcery.cfg

find the below lines in the AS config & add the 0. This will allow you to see constellations in the overworld as it's dimension ID is 0.
```
# Whitelist of dimension ID's that will have special sky rendering [default: [0]]
    S:skySupportedDimensions <
        0
     >
# IF a dimensionId is listed in 'skySupportedDimensions' you can add it here to keep its sky render, but AS will try to render only constellations on top of its existing sky render. [default: ]
    S:weakSkyRenders <
        0
     >
```
