### ISSUE TITLE
Ichor Not Present

### ISSUE THREAD

**Issue by zagates** [DarkPacks/SevTech-Ages#2773]
## Bug Report
It seems that ichor has been removed from the game, but soulsand still does not grow in either a vanilla fashion or when using lava/water as the hydration source

## Steps to Reproduce
I'm running the most recent version of sevtech ages as of 6/6/18. In JEI Ichor is not present when searching "@netherex", and when travelling to arctic abyss biomes there is no natural ichor.

**Comment by Midaychi** [comment]
I found Ichor in world. It was nowhere near a frozen nether biome and it was just a small pool in some barely perceptible alcove pocket in the middle of nowhere I accidentally saw because it kind of looked like liquid redstone from a distance.
