### ISSUE TITLE
Not sure if it is bug

### ISSUE THREAD

**Issue by Yuky0212** [DarkPacks/SevTech-Ages#2774]
## Bug Report
I am using the Seve tech ages version3.0.6, I had builded the excavator from Immersive Engineering, but it don't dig up the vein that I sampled.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by timmit99** [comment]
Fill out the template completely. It's there for a reason. Include relevent information I. The relevent areas. How did you set up the excavator? Did it excavate anything at all?
