### ISSUE TITLE
Reinforced Coke Brick Breaks Instantly (Even With Bare Hand)

### ISSUE THREAD

**Issue by MaxFirestorm** [DarkPacks/SevTech-Ages#2784]
## Bug Report
When Reinforced Coke Bricks are placed in the world but *not* part of the Advanced Coke Oven Multiblock (as in, not yet hit with the Engineer's Hammer to form the multiblock), the blocks break instantly, even when using your bare hands, resulting in losing the block.

## Expected Behaviour
Normal block breaking behavious similar to that of Reinforced Blast Brick

## Possible Solution
Change block hardness to that of Reinforced Blast Brick

## Steps to Reproduce (for bugs)
1. Place Reinforced Coke Brick in world
2. Punch it

## Logs
* Client/Server Log: N/A
* Crash Log: N/A

## Client Information
    Modpack Version: 3.0.7
    Java Version: 1.8.0.161 (64bit)
    Launcher Used: Twitch
    Memory Allocated:8,192mb
    Server/LAN/Single Player: Single Player
    Optifine Installed: No
    Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.4/5ish
* Additional Content Installed: None

**Comment by LordHellscream** [comment]
yes and they get destroyed as well.
