### ISSUE TITLE
Ceramics Channels do not appear to work in SevTech-Ages

### ISSUE THREAD

**Issue by BattleNachos** [DarkPacks/SevTech-Ages#2787]
The Porcelain Faucet from Ceramics works as described and can pour water from one container to another below it.  However when trying to use the Faucet to pour from a container into a Channel the animation will start and even a little water will flow into the channel but then it stops.  Nothing else happens.  The Channel does not fill, or flow in any direction or configuration, with or without tanks connected on, under, or around.

SevTech Ages 3.0.7
Age 1

To reproduce:
Connect a Porcelain Faucet to a Clay or Oak Barrel.  Lay Channels underneath in any configuration; connect barrels or not.  Click the Faucet to start.

**Comment by Aedaeum** [comment]
Have you tried the channel to just constantly pull out molten metal? I can't get that to work either, it does nothing.

**Comment by Darkosto** [comment]
I have been using Seared and Porcelain channels with faucets since the pack has released. Every version they have worked perfectly fine when you use them correctly. There are graphics in the channels to help point where the liquid will go. 

This is not a bug, and right before I started typing this message out I was using them with no issues.

**Comment by monodemono** [comment]
Make sure you're using them properly. Below is proof that they work. For the sake of being thorough, I did every combination of porcelain and seared faucet/channel.

<img width="1920" alt="screen shot 2018-06-08 at 14 29 32" src="https://user-images.githubusercontent.com/1161277/41181995-ba426638-6b28-11e8-8131-32cbc2c6d914.png">
<img width="1920" alt="screen shot 2018-06-08 at 14 29 57" src="https://user-images.githubusercontent.com/1161277/41181996-ba62e6ec-6b28-11e8-8a84-eacf6f846b63.png">
<img width="1920" alt="screen shot 2018-06-08 at 14 30 47" src="https://user-images.githubusercontent.com/1161277/41181997-ba7cbbb2-6b28-11e8-83b1-d4adc2edf1f1.png">
<img width="1920" alt="screen shot 2018-06-08 at 14 30 56" src="https://user-images.githubusercontent.com/1161277/41181998-ba979126-6b28-11e8-9699-bf81347d87af.png">

**Comment by BattleNachos** [comment]
Works now, guess I just needed a restart.  Sorry guys.
