### ISSUE TITLE
Bone multiply in crafting grid after repairing sharpbone

### ISSUE THREAD

**Issue by ray1997** [DarkPacks/SevTech-Ages#2790]
For some weird reason when I try to repair "Sharp bone supposedly it should decrease. But instead, it doubles from the current amount.

[And I record a video of it as well](https://1drv.ms/v/s!AsPczr3-hqPBioElD-GWUp8rEunQyw)

I was on the latest version of the pack. This issue is not really critical so I guess it not really that important :/

**Comment by Stifling-Bossness** [comment]
#2358

**Comment by artdude543** [comment]
Duplicate of #2358
