### ISSUE TITLE
crashing in the hunting dimnsion 

### ISSUE THREAD

**Issue by V0odoofyxen** [DarkPacks/SevTech-Ages#2793]
i've been playing mostly in peaceful today i built and entered the  hunting demnsion while in peacful spent probly an hour maybe more building a mobfarm/ safety cage/ tunnel thing with no problems then did 1or 2 of runs on easy, in the demsion for maybe 15/20 mins killing mobs, it was either on the second or third run i put down a couple of blocks in the middle of the cage, might have put it on to normal for more mobs and was just geting ready to step a way for a moment when the game crashed. pack  re load up in hunting dimension in peaceful with no problem, crashed as pretty much straight away once i changed out of peaceful, did this a couple of thimes on the third reload i also changed the chunkload? from 12 to 8 when i changed out of peacful, forth reload stayed in HD in peaceful 10/15 mins,no problems, went back to ow,  changed out of peaceful, no problems went back to hg in peaceful changed to  easy, normal, hard over 15/20 mins crash once i changed to hard mode. is this just a mob load issue or somthing else?

first crash - https://pastebin.com/XXyijVXd
1st reload - https://pastebin.com/sknDKcnZ
2nd reload - https://pastebin.com/0jibpy5n   
3rd reload - https://pastebin.com/XgvPid6W
4th - https://pastebin.com/3b0qPxWC

## Logs

* Client/Server Log:
* Crash Log:

* Modpack Version: 3.0.7
* Java Version: latest -171?
* Launcher Used: native
* Memory Allocated:8,704mb
* Server/LAN/Single Player: single player, no sever
* Optifine Installed:  sortex fanver moded
* Shaders Enabled:

## World Information

* Modpack Version world created in:3.0.7

* Additional Content Installed:

**Comment by V0odoofyxen** [comment]
had two  more crashes
https://pastebin.com/1C0fzXpy
https://pastebin.com/wdQZ8C3P
last crash had just re loaded straight into the hd moved 4/5 blocks and crashed.

**Comment by Stifling-Bossness** [comment]
This should be fixed in 3.0.8 according to #2456

**Comment by artdude543** [comment]
Fixed in next update.
