### ISSUE TITLE
SevTech: Ages crash on startup

### ISSUE THREAD

**Issue by bunnysmile** [DarkPacks/SevTech-Ages#2794]
## Bug Report
My friend keeps getting the same crash on the step 3/7 and dont know what is the problem.
And by the way i don't know what to send to see the error

## Steps to Reproduce (for bugs)

1.
2.

## Logs
[ATLauncher-Log_2018-06-08_20-32-51.log](https://github.com/DarkPacks/SevTech-Ages/files/2085953/ATLauncher-Log_2018-06-08_20-32-51.log)
* Crash Log: [ATLauncher-Log_2018-06-08_20-32-51.log](https://github.com/DarkPacks/SevTech-Ages/files/2085953/ATLauncher-Log_2018-06-08_20-32-51.log)

**Comment by artdude543** [comment]
It tells you what is wrong

`[08/6/2018 20:33:09 PM] [WARN]You're using 32 bit Java on a 64 bit Windows install!`

Read the log files. This is also a Discord matter.

**Comment by bunnysmile** [comment]
anyway thanks for the information it really helped a lot
