### ISSUE TITLE
Cyclic Hydrator creates white concrete regardless of Powder color

### ISSUE THREAD

**Issue by krezack** [DarkPacks/SevTech-Ages#2795]
## Bug Report
Inserting any color Concrete Powder into the Cyclic Hydrator creates White Concrete.

## Expected Behaviour
Inserting Concrete Powder will create Concrete of the same color as the powder.

## Steps to Reproduce (for bugs)
1. Insert Concrete Powder of any color
2. Receive White Concrete

## Client Information
* Modpack Version: 3.08
* Java Version: 1.8.0_171
* Launcher Used: Twitch
* Memory Allocated: 10923MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.05
* Additional Content Installed: None

**Comment by Vercci** [comment]
Reported this to the cyclic dev and they supposedly put out a fix 
https://github.com/PrinceOfAmber/Cyclic/issues/867

Here's hoping it works.

**Comment by RyogaK** [comment]
@Darkosto Would you update the cyclic to 1.15.16?

**Comment by Tahakk** [comment]
My guess is that in 3.0.9 there will be few mod updates, until than you are on your own.

**Comment by artdude543** [comment]
Will be fixed when 3.1.0 releases 😄
