### ISSUE TITLE
Backpack upgrades and contents removed when using Pneumaticcraft on placed backpack

### ISSUE THREAD

**Issue by mummabia** [DarkPacks/SevTech-Ages#2798]
## Bug Report
Clicking with a Pneumaticcraft wrench on a placed Improved Backpack backpack, will rotate the backpack and reset the bag back to default.  All items, colour, name and upgrades are removed.  Items do not return after relogging and/or restarting game.  Problem found in 3.0.7 and remains in 3.0.8

## Expected Behaviour
Backpack rotates.  Items and backpack configuration to remain as is.

## Suggestion
Disable use of Pneumaticcraft wrench on Improved Backpacks.

## Steps to Reproduce (for bugs)

1. Do one or more of the following changes to a default Improved Backpack.
* Upgrade backpack to at least a stone upgrade
* Change colour of pack to anything but brown
* Place one or more item into the backpack 
* Rename the backpack.  
2.  Place the bag on the ground.
3. Right click the bag with a Pneumaticcraft wrench one or more times, the bag will rotate.
4. Right click the bag to view empty inventory and note bag has been reset to default.

## Client Information

* Modpack Version: 3.0.8
* Java Version: 8.0.1710.11
* Launcher Used: Twitch
* Memory Allocated: 12
* Server/LAN/Single Player: Single and LAN
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by DreenDex** [comment]
Does this wrench removes nbt data of all blocks when rotating?

**Comment by mummabia** [comment]
I've only noticed this occurring on the backpack as it was an accidental click.  Otherwise, I've only used the wrench on machines with no problem.

**Comment by vadis365** [comment]
Hello,
@DreenDex - I cant find a repo with visible SRC for the mod - but if you add this to the TE for the backpack, it should stop wrenches causing problems rotating blocks and removing their NBT contents.

@Override
	public boolean shouldRefresh(World world, BlockPos pos, IBlockState oldState, IBlockState newState) {
	return oldState.getBlock() != newState.getBlock();
}

Had to add this to my own mods when the same issue popped up.
Cheers,
Me.

**Comment by DreenDex** [comment]
Fixed in Improved Backpacks 1.3.0.0. Many thanks @vadis365.
This can be closed after updating the mod.

**Comment by artdude543** [comment]
Will be fixed in 3.1.0 😄
