### ISSUE TITLE
Cyclic Hydrator can't craft more than 1 stack of items at a time

### ISSUE THREAD

**Issue by Fitmit** [DarkPacks/SevTech-Ages#2799]
## Bug Report
Cyclic Hydrator as of 3.0.8 can not take separate stacks of items. (There is also a black bar on the left side with no texture, not sure if this is a mechanic or something for use later.) The GUI also does not update, and I assume it uses power now?

## Expected Behaviour
-Put in 4 stacks of items, does not work.
-Put in 1 stack, works fine.

**Comment by Fitmit** [comment]
Gui also doesn't update while open. and I assume it requires power to operate now?

**Comment by SmileMore79** [comment]
ive noticed same thing nee power for it have no ideal what to do

**Comment by SmileMore79** [comment]
how you give it power
