### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Danilxxx6** [DarkPacks/SevTech-Ages#2806]
After update 3.0.8 i played like 2 hours and closed the game. Now i can't open it again, it crashes everytime  i try to open it. Minecraft client doesn't appear at all, ATLauncher disappears for a second and appears again. 

Here is crash log-https://paste.atlauncher.com/view/73840329( lines form 52 to 58 are red and i haven't seen them before)

**Comment by artdude543** [comment]
You have duplicated mods. Reinstall the entire instance. Backup your world before hand

**Comment by Danilxxx6** [comment]
It worked thank you! Its weird however i checked my mods and i didn't have any duplicates.
