### ISSUE TITLE
server friend cant use attunement altar

### ISSUE THREAD

**Issue by jal21** [DarkPacks/SevTech-Ages#2809]
me and my friend are using a server to paly the pack. i built a attunement altar and i used it, then my friend tried to use it. the attunement altar dint do anything. after that we throw some Crystals in and the Crystals  said "there seams to be something here" to him not to me. he has the tier 4 alter(the gold one) also we are on the latest version 3.0.8. i was the one that placed it but i don't see that as the problem. i am the "host" but i don't see that as the problem either

**Comment by artdude543** [comment]
For him to use it. He needs to learn the entire AS mod from the start like you did. This is intended and won't change. Either that or you do all the xrafyimg recipes as your allowed to use the alter.
