### ISSUE TITLE
Moon deathloop (or probably just dying repeatedly in quick succession) causes "Bed missing or obstructed"

### ISSUE THREAD

**Issue by Iorce** [DarkPacks/SevTech-Ages#2812]
## Bug Report
Dying repeatedly (on the moon) causes the "Bed missing or obstructed" message and resets the spawn point.
![2018-06-09_13 24 53](https://user-images.githubusercontent.com/23401986/41191028-3feb5e46-6be9-11e8-8160-620f48a125c5.png)
(Picture taken in SSP on a new flat world with gamestages added artificially (but no advancements added because I didn't want to waste time which is why Journeymap doesn't work)

Going back to the Overworld lets you still respawn at the original spawn location, /gchouston brings you back to the original spawn location instead of your home bed.

## Expected Behaviour

Spawn point should not be reset.

## Steps to Reproduce (for bugs)

0. Set a spawn point with a bed (at night in SSP)
1. Fly to the moon
2. Don't have anything equipped
3. Be in survival mode
4. Die 3-5 times in a row. Tell me if you notice a game freeze on respawn, so I can open another issue report.

## Client Information

* Modpack Version: 3.0.8 (SSP), 3.0.7
* Java Version: 1.8.0_161 64 bit
* Launcher Used: Twitch App
* Memory Allocated: 6400MB
* Server/LAN/Single Player: SSP & SMP
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.7, 3.0.8 (SSP), 3.0.6 (SMP)

* Additional Content Installed: no

## Server Information
* Java Version: unknown
* Operating System: unknown
* Hoster/Hosting Solution: unknown
* Sponge (Non-Vanilla Forge) Server: no

**Comment by justinrusso** [comment]
Does this happen on 3.0.8?

**Comment by Iorce** [comment]
Still relevant in 3.0.8

**Comment by Iorce** [comment]
Can you please update the label to be not outdated? It is still relevant in 3.0.8.
