### ISSUE TITLE
Temple Blocks recipe unfairly low

### ISSUE THREAD

**Issue by dman11235** [DarkPacks/SevTech-Ages#2814]
Temple Block recipe appears to be reduced to give 1 block, as opposed to the normal 8-32 (I can't remember the vanilla Chisel recipe, I think it's normally 16).

![2018-06-09_12 01 27](https://user-images.githubusercontent.com/9954872/41193644-f88ecc6a-6bdc-11e8-9c05-bbf1181367e4.png)

**Comment by Iorce** [comment]
Also affects colored wool.

**Comment by Stifling-Bossness** [comment]
@Iorce Did you test in 3.0.8? #2307 Marks the issue as completed and closed for 3.0.8.
