### ISSUE TITLE
Can't see items held in another player's hands.

### ISSUE THREAD

**Issue by Genotypek** [DarkPacks/SevTech-Ages#2815]
## Bug Report
On multiplayer I can't see items held by another players. It appears only for moment, almost instantly it disappears and I see empty hand. Even weapons are desappears.
Exceptions:
- Pickaxes,
- Axes,
- Death compass,

## Possible Solution
100% sure it's not optifine. Today I did clean update to 3.0.8 and it's still the same.

## Steps to Reproduce (for bugs)
Idk, just log in and see that players have empty hands.

## Client Information

* Modpack Version: 3.0.7 and 3.0.8
* Java Version: Java 8 Update 172 x64
* Launcher Used: Twitch app,
* Memory Allocated: 10GB
* Server/LAN/Single Player: Dedicated server AND lan,
* Optifine Installed: Yes 1.12.2 HD U D3, BUT without it's the same.
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.7
* Additional Content Installed: no

## Server Information
* Java Version: Java 8 Update 171 x64
* Operating System: Linux Debian 9
* Hoster/Hosting Solution: Dedicated Server
* Sponge (Non-Vanilla Forge) Server: No.

**Comment by iDarper** [comment]
Might be an issue with spongeforge.

**Comment by Genotypek** [comment]
https://youtu.be/GrZ0vPTh3WI

There's a video which shows what is happening.
