### ISSUE TITLE
Help With Missing Registry Entries

### ISSUE THREAD

**Issue by BlueKitRed** [DarkPacks/SevTech-Ages#2816]
## Bug Report
When loading a world it states there are 9 missing entries after updating the modpack
![issue](https://user-images.githubusercontent.com/40123413/41194317-97512b2c-6be7-11e8-9637-609927ece852.jpg)
-----------------------------------------------------------------------------------------------------------
## Logs
* Client Log (Latest): https://gist.github.com/BlueKitRed/084719e2a13f8c69ec5663030869ae7f
-----------------------------------------------------------------------------------------------------------
## Client Information
* Modpack Version: 3.0.8
* Java Version: 8
* Launcher Used: ATLauncher
* Memory Allocated: 4096mb
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: 1.12.2 HD
-----------------------------------------------------------------------------------------------------------
## World Information
* Modpack Version world created in: 3.0.7
-----------------------------------------------------------------------------------------------------------
## Other Comments
Not sure if it is going to make a big difference if I start and it says it will remove the entries, but would rather be safe

**Comment by artdude543** [comment]
You can click yes. It's fine
