### ISSUE TITLE
upgrade from 3.0.7 to 3.0.8 world no longer generating

### ISSUE THREAD

**Issue by pocketpacket** [DarkPacks/SevTech-Ages#2817]
Upgraded the world from 3.0.7 gen to 3.0.8
on a linux server. I thought all was fine until
wanted to make sure new chunks are 
generating ok, Turns out I was wrong.

Pictures attached. 
![2018-06-09_06 41 16](https://user-images.githubusercontent.com/40080476/41194754-b6120df4-6bd5-11e8-8690-56cbfab4af55.png)
![2018-06-09_10 57 54](https://user-images.githubusercontent.com/40080476/41194755-b62b9bd4-6bd5-11e8-9c78-6a738ac14dee.png)
![2018-06-09_10 57 59](https://user-images.githubusercontent.com/40080476/41194756-b644b07e-6bd5-11e8-9b9d-ac14e5f874d4.png)
![2018-06-09_10 58 28](https://user-images.githubusercontent.com/40080476/41194757-b65df0b6-6bd5-11e8-8066-947e6034c32b.png)

**Comment by artdude543** [comment]
Are you using our provided server download? If yes did you copy over the server.properties file?

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by pocketpacket** [comment]
Yes, I used your download for the server update
Yes. The only difference between your server.properties file and mine
the new one has dc_preset: notSet and mine is default, but I added or
changed mine to notSet anyway. I covered every corner. This is a 3.0.7
world that is I have a custom seed, custom world folder, whitelisted, pvp off
the only difference is the dc_preset

**Comment by pocketpacket** [comment]
i rolled everything back to 3.0.7 and going to try again, I covered
everything, It just competely did not gen at all the first time once
I hit new gen.

**Comment by Blargerist** [comment]
A server log would be useful.

**Comment by pocketpacket** [comment]
give me a min and i'll post one from the first time.

**Comment by pocketpacket** [comment]
[debug.log](https://github.com/DarkPacks/SevTech-Ages/files/2087288/debug.log)
[debug-1.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2087289/debug-1.log.gz)
[debug-2.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2087290/debug-2.log.gz)
[latest.log](https://github.com/DarkPacks/SevTech-Ages/files/2087291/latest.log)

**Comment by pocketpacket** [comment]
i'll have some lunch and check back. before I try updating again

**Comment by Blargerist** [comment]
Please put logs on Github Gist or Pastebin....

**Comment by Blargerist** [comment]
Github Gist should be able to handle it. If not, just make multiple?

**Comment by pocketpacket** [comment]
pocketpacket / gist:c2880c0ad76d730e2c5e9694ff7e12ee

sorry, never used this site before. does this work?

**Comment by pocketpacket** [comment]
if it does then i'll post the latest.log also

**Comment by Blargerist** [comment]
It works, but strangely none of the errors I'm looking for.... What does your world/DimensionalControlPreset.txt file say?

**Comment by pocketpacket** [comment]
checking

**Comment by pocketpacket** [comment]
all the good stuff is in this debug log :/

**Comment by pocketpacket** [comment]
Well I rolled it back to 7, some of the players are trying to login with 8,
but with what happened I cannot let them play on it if nothing else will
gen.
