### ISSUE TITLE
Silicon ore no longer their

### ISSUE THREAD

**Issue by tapegreen** [DarkPacks/SevTech-Ages#2818]
Bug Report
I recentially updated to the newest version of the pack and silicon no longer appears where they used to be. I have dug 3 separate holes in places i haven't been in a long time and the ores are no longer their.
Expected Behaviour
The ore should be their, but it isn't.
Steps to Reproduce (for bugs)
1.Go back to version 3.0.7 and locate silicon ore
2. Update to 3.0.8
3.Return to spot and notice the lack of silicon

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
