### ISSUE TITLE
Server crash when trying to start it

### ISSUE THREAD

**Issue by Boyownik** [DarkPacks/SevTech-Ages#2819]
## Bug Report
When i run server start script after about minute server crashes. I have 4GB ram vps, tried assign 4 and 3 gigs with same result. SevTech:Ages 3.0.8.

## Expected Behaviour
Server generate map and be alive

## Possible Solution
Have no idea

## Steps to Reproduce (for bugs)
Run server

## Logs

* Crash Log: https://pastebin.com/CgWitv3z

## Server Information
* Java Version:1.8.0_171
* Operating System: Ubuntu 3.13.0-149-generic
* Hoster/Hosting Solution:VPS KVM
* Sponge (Non-Vanilla Forge) Server: just used your installer, clean forge

**Comment by artdude543** [comment]
You have a broken upload/download. Re-download the server files and upload/copy over fresh versions of the Jars. This is the issue here.
