### ISSUE TITLE
[3.0.8] Bed Bug... Player never woke up, or stuck in bed...

### ISSUE THREAD

**Issue by Fireztonez** [DarkPacks/SevTech-Ages#2821]
After the update to the version 3.0.8 of sevtech, bug when sleep appen multiple times... In most case, the player just not woke yo automatically, need to press ESC to woke up (But the night pass ;) ).

The last time, I go to the bed, for pass the night, but the player never Woke up, and ESC doesn't work, I'm completly stuck in the bed, can't do anything... I have to quit and restart the modpack...

I have now added BedPatch (I don't know why you remove from the pack, but I will see if is better!).

Take note, I add 3 mods in the modpack; 
- Fullscreen Windowed (Borderless)
- Twitch Chat Integration
- Chat Tweaks
But I don't think this problem is caused by that 3 mods (look like the Vanilla Bed Bug)...

Fireztonez

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
