### ISSUE TITLE
Update from 3.0.7 to 3.0.8 Crash on start up.

### ISSUE THREAD

**Issue by BushTrocity** [DarkPacks/SevTech-Ages#2824]
After updating the server to the newest version the server is crashing on start up.
I have tried fresh versions of the mod jars that is listing in the log and new zip of the server. still same errors. 
Here is the log: https://pastebin.com/gHQZZ3gc

**Comment by artdude543** [comment]
You have a broken upload/download. Re-download the server files and upload/copy over fresh versions of the Jars. This is the issue here.

**Comment by BushTrocity** [comment]
I have and im still having the same error
