### ISSUE TITLE
Symorite bucket turns to Weedwood bucket?

### ISSUE THREAD

**Issue by Avalynne** [DarkPacks/SevTech-Ages#2826]
## Bug Report
I don't know if anyone else has run into this issue, but a couple of players on a server I help staff has found (and reproduced) putting a symorite bucket into a brewing barrel, only to have it come back to him as a weedwood bucket. I'm pretty sure that's not supposed to happen. I told him I would post to the GitHub, which is the best I can do at the moment. If anyone could let me know of some kind of fix (or maybe we're doing something wrong), that would be awesome.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
