### ISSUE TITLE
server crash migrating to 3.0.8

### ISSUE THREAD

**Issue by axel11** [DarkPacks/SevTech-Ages#2828]
i did the steps in the update text file to update the server. i even tried a brand new download of 3.0.8 and just moved the world and prestige in and still crashes.

https://pastebin.com/GKKxS9yQ is the crash dump

i have two custom mods installed:
worldedit 6.1.8
 betterrecords1.12.2-1.5.5

these mods worked in 3.0.7

also the server works in 3.0.8 if i dont migrate my world. Anyone have any ideas?

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
