### ISSUE TITLE
PrimalCore barrel lids won't come off

### ISSUE THREAD

**Issue by Shad0wdrag0n** [DarkPacks/SevTech-Ages#2829]
This can be deleted. Seems CarryOn was overriding the Shift+right click command.

## Bug Report
I put some lids on my PrimalCore barrels so I could move them. When I put them down again I shift+right clicked on the tops to remove the lids, but only ended up picking up the barrels again. Now it seems I can't open the barrels. Is this intended, or a bug?

## Steps to Reproduce (for bugs)
1. Put lid on barrel
2. Shift+click to remove lid

## Client Information
* Modpack Version: 3.0.8
* Java Version: 8u171
* Launcher Used: Twitch
* Memory Allocated: 4g
* Server/LAN/Single Player: single
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Jimjhd** [comment]
I guess it is a bug. For now, u still can remove lids from barrels by shift right click them with non-empty hand.

**Comment by artdude543** [comment]
This is a side effect from CarryOn the suggestion above is the way to get around it.
