### ISSUE TITLE
Client Crash on Joining Server.

### ISSUE THREAD

**Issue by BushTrocity** [DarkPacks/SevTech-Ages#2832]
Had a ruff time updating the server. Im getting the errors that is in the log on start up and then the errors upon joining. The files that it is saying are missing are in fact where they should be and unchanged from last version. Im giving up on trying to fix it tonight and will try again tomorrow.

## Steps to Reproduce (for bugs)
Unknown 
## Logs
https://pastebin.com/h19keyRH

## Client Information

* Modpack Version:3.0.8
* Java Version:1.8.0_141
* Launcher Used:Twitch App
* Memory Allocated:6GB
* Server/LAN/Single Player:Server
* Optifine Installed:No
* Shaders Enabled:No

## Server Information
* Java Version:1.8.0_141
* Operating System:Linux:amd64:3.14.32
* Hoster/Hosting Solution:Onlinegamehost

**Comment by artdude543** [comment]
Your online game host is causing the issues. Your missing files again. Contact them for support. We don't deal with that side of things. We've tested this update for a month and it's fine on new and old worlds; but something is messing with your configs/mods.
