### ISSUE TITLE
World is invisible when i move

### ISSUE THREAD

**Issue by BestPone** [DarkPacks/SevTech-Ages#2833]
The game works fine and i can see the world when i load in, but if i move an inch it just flings off the screen at hyperspeed. and there were some weird things i saw like spinning leaves and huge plants. I have no idea what happened and the only thing i did was dedicate more ram to minecraft. :/

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by BestPone** [comment]
Oh so just fuck you then
