### ISSUE TITLE
World "disappears" and camera spinning around

### ISSUE THREAD

**Issue by Scarmaker** [DarkPacks/SevTech-Ages#2836]
Modpack Sevtech Ages 1.12
Walking a few steps, then chunks disappear, camera start flipping around then chunks loading again. After next step samething. I can clearly see ,by watching villagers they have the same issues...
Whatever I do,
new world, old map same issue.
Reinstalled grafic drivers, and cpu
Changed all graphic settings, priorized java, took another java version and many other things.
Not able to play

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
