### ISSUE TITLE
thebetweenlands Failed to load new mod instance.

### ISSUE THREAD

**Issue by thewismit** [DarkPacks/SevTech-Ages#2839]
## Bug Report
thebetweenlands Failed to load new mod instance.

## Expected Behaviour
successful server boot

## Possible Solution
unknown - attempted to delete DIM20, no change.

## Steps to Reproduce (for bugs)
start server

## Logs

* Client/Server Log:
* Crash Log:
https://gist.github.com/thewismit/39dbe831d3457ff6702294a8fb43b30f
## Client Information

* Modpack Version:
N/A
* Java Version:
N/A
* Launcher Used:
N/A
* Memory Allocated:
N/A
* Server/LAN/Single Player:
N/A
* Optifine Installed:
N/A
* Shaders Enabled:
N/A

## World Information

* Modpack Version world created in:
3.0.7

* Additional Content Installed:

## Server Information
* Java Version:
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
* Operating System:
Ubunt 16.0.4 LTS
* Hoster/Hosting Solution:
self-hosted
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
Your install is broken your missing the Core mod for Between Lands which is downloaded/extracted from the main mod Jar. Ensure file permissions allows the Server Jar to make modifications to the mod dir. Or upload the one from your client instance.

**Comment by thewismit** [comment]
Thanks so much for replying. I forgot to re-apply permissions for MSCS after updating and this fixed it.
