### ISSUE TITLE
Hunger effect prevents eating

### ISSUE THREAD

**Issue by Iorce** [DarkPacks/SevTech-Ages#2842]
## Bug Report

Cannot eat food while affected by hunger potion effect.

## Expected Behaviour

Should be able to eat regardless of hunger effect.

## Steps to Reproduce (for bugs)

1. Eat Rotten Flesh or use /effect @p hunger 10
2. Try to eat something within the next 10 seconds

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_161 64 bit
* Launcher Used: Twitch app
* Memory Allocated: 6400MB
* Server/LAN/Single Player: SSP // Testworld
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: no

**Comment by artdude543** [comment]
This is intentional for the pack.
