### ISSUE TITLE
Hunting dimension portal spawns shoggoths

### ISSUE THREAD

**Issue by KorvinSzanto** [DarkPacks/SevTech-Ages#2844]
## Bug Report
Hunting dimension portal spawns shoggoths after the latest updates causing surprise mob griefing. Since hunting dimension portals are generally pretty safe, this leads to shoggoths being spawned where they definitely should not be spawned. They will chase after any livestock and will break through blocks on their way there.

## Expected Behaviour
Shoggoths should spawn in their lairs and in some cases when charging a necronomicon, not randomly on top of the hunting portal.

## Possible Solution
Remove shoggoths from the hunting dimension portal spawn table

## Steps to Reproduce (for bugs)

1. Build a hunting dimension portal far away from any statues or shoggoth lairs
2. Wait for one to spawn

## Logs
* N/a

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_171
* Launcher Used: Twitch
* Memory Allocated: 7g
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: Yes

## World Information

* Modpack Version world created in: 3.0.6

* Additional Content Installed: N/a

## Server Information
* Java Version: Not sure
* Operating System: OSX
* Hoster/Hosting Solution: N/a
* Sponge (Non-Vanilla Forge) Server: Not sure

**Comment by artdude543** [comment]
Them spawning from the portal is intentional. As it picks mobs at random. So better fence up the portals!

**Comment by LordHellscream** [comment]
As much as I love this pack (i really do), the Shoggoth griefing is killing the fan base, and it really need to be dealt with if not by the mod maker,
