### ISSUE TITLE
List of food items which are not recognized by Nutrition (and some special cases)

### ISSUE THREAD

**Issue by Iorce** [DarkPacks/SevTech-Ages#2845]
## Issue Description

I do not want this to be viewed as a bug report because some things most certainly are not an oversight, rather a discussion for clarification (so it won't be asked again). Some of the items might not be obtainable. Some items might be in a very broad sense of being a food item (not restoring hunger directly).

The following food items could have but don't have any nutrition values:
### Fruit
Fruit Products
* Apple of Lofty Stature (cyclicmagic:food_step)
* Corrupted Chorus Fruit (cyclicmagic:corrupted_chorus)

Other (they're listed under fruit because Jello and Candy items give fruit nutrition)
* Congealed Magma Cream (nex:food_congealed_magma_cream)
* Sinuous Resin (primal:sinuous_resin)
* Slime Ball (Blue) (tconstruct:edible:1)
* Slime Ball (Purple) (tconstruct:edible:2)
* Slime Ball (Orange) (tconstruct:edible:4)
* Gelatinous Slime Drop (Green) (tconstruct:edible:30)
* Gelatinous Slime Drop (Blue) (tconstruct:edible:31)
* Gelatinous Slime Drop (Purple) (tconstruct:edible:32)
* Gelatinous Slime Drop (Orange) (tconstruct:edible:34)
* Candy Cane (thebetweenalnds:candy_cane)

### Grain
Seeds
*  Rush Seeds (primal:rush_seeds)
* Yew Seeds (primal:yew_seed)

Other
* Ground Wheat (primal:wheat_ground)

### Protein
Flesh/Meat
* Coralium plagued flesh on a bone (abyssalcraft:corbone)
* Coralium plagued flesh (abyssalcraft:corflesh)
* Raw Imphide (natura:edibles:0)
* Rotten Bat Meat (primal:bat_meat_rotten)
* Charqui (primal:llama_meat_charqui)
Chocolate (is made with milk)
* actuallyadditions:item_food:9
* betterwithmods:chocolate

Other (might technically not be a food item)
* Rotten Anti-Flesh (abyssalcraft:antiflesh)
* Anti-Spider Eye (abyssalcraft:antispidereye)
* Milk (minecraft:milk_bucket)

### Vegetable
Plant parts
* Daucus Murn Root (primal:daucus_murn_root)
* Devils' Tongue Sepals (primal:devils_tongue_sepals)
* Devils' Tongue Tendril (primal:devils_tongue_tendril)
* Molding Potato (primal:potato_rotten)

Other (might technically not be a food item)
* Brown Elder Mushroom (nex:plant_mushroom_elder)
* Red Elder Mushroom (nex:plant_mushroom_elder)
* Sinuous Spore (primal:sinuous_spores)
* Equisetum Ineris Spore (primal:void_seed)

### Universal
* Heart Container (cyclicmagic:heart_food)
* Inventory Crafting Table (cyclicmagic:crafting_food)
* Inventory Upgade (cyclicmagic:inventory_food)

### Uncategorized
* Bottle of X (rustic:fluid_bottle) (shares more similarity with a potion, no meta IDs, they might have to be assigned all to one nutrition)
* Nibblestick (thebetweenlands:nibblestick) (could be vegetable)

Fat (could be fit into protein, though...?)
* Bear Fat (primal:bear_fat)
* Lard (primal:lard)
* Salo (primal:salo)
* Suet (primal:suet)

## Expected Behaviour

Most food items should have nutrition values, even if they state 0.0% (Anti-Meat, however honestly I think it should be a negative value if possible). For everything else, it should be specified that it is intended for them to not have a nutrition value.

## Possible Solution

I would volunteer to take care of the Nutrition config once it's clarified which items should and which should not have nutrition values and, if modifiable, how much. Some items that have nutrition values have 0.0% added by eating, for example Anti-Beef (abyssalcraft:antibeef) which might or might be a solution/case for items on this list.

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_161 64 bit
* Launcher Used: Twitch app
* Memory Allocated: 6400 MB
* Server/LAN/Single Player: SSP
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: no

**Comment by artdude543** [comment]
As referenced in #2017 the list mentioned above are items not in our current interest to give any values too. We may, however, review this again at a later date. But the latter issue is our main one for tracking foods.
