### ISSUE TITLE
Dupe Bug - Fluid Tank with Treated Wood Planks- Inductive Logistics

### ISSUE THREAD

**Issue by Inferndragon** [DarkPacks/SevTech-Ages#2846]
## Bug Report
Duplication of "Inductive Logistics" Creosote Oil tank [Any Size] while using the "Treated Planks Recipe".

## Expected Behaviour
Inductive Logistics fluid tank should either stay in the crafting grid itself.

## Possible Solution
Prevent the Fluid Tank after craft to enter the inventory of the player.

## Steps to Reproduce (for bugs)
1.  Acquire any tank from Inductive Logistics, a storage request table and oak planks.
2. Fill the Inductive Logistic Tank with Creosote Oil.
3. Use the recipe to create treated planks and replace the Bucket with the tank.
4. Press Shift to create multiple recipes of the treated planks.
(Only Works when you shift)

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 3.0.7
* Java Version: 1.8.0_171
* Launcher Used: Twitch Launcher
* Memory Allocated:  8192 MB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.7

## Server Information
* Java Version: 1.8.0_171
* Operating System: N/A
* Hoster/Hosting Solution: Nitrado
* Sponge (Non-Vanilla Forge) Server: None

**Comment by Midaychi** [comment]
..Isn't that just working as intentionally, as you're crafting from the tank? Does it use up a buckets worth of liquid from the tank every craft?

**Comment by Inferndragon** [comment]
It uses up a buckets worth each time. But when you shift click the craft. It actually makes multiple version of the tank.... I had 1 tank of creosote oil... ended up with 63 tanks with the same amount of fluid inside each of them. So i was technically duping the contents of the tank and the tank itself.
