### ISSUE TITLE
Bloodwood tree drops a lot of redstone

### ISSUE THREAD

**Issue by Azrazal** [DarkPacks/SevTech-Ages#2848]
It allows skipping finding redstone ore or cinnabar ore veins

## Context

I used my normal tinkers pickaxe with luck 3 and excavate on it to destroy a Bloodwood tree from Natura. It dropped a huge amount of redstone dust. I searched and found that it was meant to occasionally drop some. I then took a sapling and planted it (upside down on netherrack) to test, and received over **4 and a half stacks** of redstone dust from the single tree.

I highly doubt this should be possible, and expect that this tree dropping redstone at all is probably not wanted

I am using sevtech 3.0.8, and have made no changes to any configs except disabling the Better Foliage mod. I am well in to age 3, and do not no if this also gives access to redstone early

**Comment by monodemono** [comment]
After a bit of deliberation we've decided this isn't worth changing.
