### ISSUE TITLE
Teleport to Nether crash and location change

### ISSUE THREAD

**Issue by Azrazal** [DarkPacks/SevTech-Ages#2849]
## Bug Report
Using normal nether portal to return to the nether, portal that i had used with no problems half an hour earlier. have not built or destroyed any portals in the meantime.

Crash was while it was loading up the nether. It mentioned something about disconnecting from the server, and 'returned' me to the server list screen instead of fully crashing the client. I am not playing on a separate server, just a normal single player game through the client.

When I logged back in, I found myself in the nether, however at about 2000 blocks south of my portal.
I have noticed that my Y coordinate is the same as where my first (out of 2) portals is, which is where i last exited the nether (the 2 portals being a couple hundred blocks from each other). There is no sign of any portal near where I showed up.

## Expected Behaviour
I expected after the crash to be where my portal is, but I am roughly 2000 blocks south of there

I do not know, but i suspect my Z coordinate is where the portal is in the overworld
edit: i have now managed to return back to my base, and the coordinates of the overworld portal are the same as the coordinates that i showed up in the nether. and i have gone back to the nether and come out of portal where expected without a crash.

## Possible Solution
not a clue

## Steps to Reproduce (for bugs)
no idea what caused it, was just using nether portal normally
edit: after returning, i went through the portal again, but the bug did not repeat

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/fDFDK8zd

## Client Information

* Modpack Version: 3.0.8
* Java Version: Version 8 Update 171 (build 1.8.0_171-b11)
* Launcher Used: twitch
* Memory Allocated: 7 GB (out of 16GB on computer)
* Server/LAN/Single Player: Single Player
* Optifine Installed: no
* Shaders Enabled: no

no changes to config files or mods except disabled Better Foliage from the in game menu

also loading with java args from sevtech guide: -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

## World Information

* Modpack Version world created in:
3.0.7

**Comment by artdude543** [comment]
Again as in other issues with the same thing/title

`java.lang.OutOfMemoryError: Initializing game`

You ran out of memory loading the world. It's also possible for world corruption. You can try deleting the nether dim and let it regen. Or backup the `level.dat` and rename the `level.dat_old` to `level.dat` and see if this helps.
