### ISSUE TITLE
[Suggestion] Slime saplings

### ISSUE THREAD

**Issue by Gameswithjohn** [DarkPacks/SevTech-Ages#2854]
With the TC armor additions and the bonsai mod it would be nice having the ability, at some point, to either be able to find or craft the slime saplings. Maybe I simply have missed them in the pack so far or am not far enough along to find them, but as of yet I'm only seeing them in JEI.

Thanks.

**Comment by kamyu2** [comment]
You can eventually get all of the slime saplings from the botanic void miner from environmental tech.

**Comment by LordHellscream** [comment]
you can craft various slime in Age3. 
Magma slime can be created with lava bucket, magma cream and green slimeballs 
Green slime can be created with wheat, clay and water in the mixer.
Blue slime can be created with blue dyes (lappis/flower) and blue glowshroom (from nether, and can be grown/farmed).
Purple slime can be created with purple dyes and purple gem thingy from the nether.

**Comment by Gameswithjohn** [comment]
Kamyu2 thank you, I wasn't aware of that.

LordHellscreem, Thanks for taking the time to explaining those, I have already been doing that since it is plainly listed in JEI, maybe I should have added that I already knew of those methods so there was no confusion. I was specifically mentioning it because it was an easier way and seemed to fit with the addition of the bonsai mod since you could also get normal tree drops from cutting trees, etc., and that is just a mod to add convenience later on.

**Comment by Gameswithjohn** [comment]
Guess this can be closed out then.
