### ISSUE TITLE
Energy Bridge Receiver not working in overworld

### ISSUE THREAD

**Issue by CyaNox** [DarkPacks/SevTech-Ages#2856]
The Energy Bridge Receiver from Ender Utilities is not working in the overworld since the bedrock layer is replaced by Bedrock-B-Gone.

Doing a `/setblock ~ 0 ~ minecraft:bedrock` while standing on the location of the Receiver made it work.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by CyaNox** [comment]
There was no issue template when I created this issue. all that was in there was the following:

```
<!--
Thanks for taking the time to filing an issue. Before you submit, please read the following:

Check for other issues already opened, to see if your issue/suggestion has been reported already.
Ensure that you have all the relevant information on hand. Such as logs/reports and information about a request/change.
-->
```
