### ISSUE TITLE
Issue template issue?

### ISSUE THREAD

**Issue by CyaNox** [DarkPacks/SevTech-Ages#2858]
Clicking `New issue` on the [issues](https://github.com/DarkPacks/SevTech-Ages/issues) page while not being logged in to github followed by signing in will redirect you directly to the following issue template and you are not presented with an issue template choice:
```
<!--
Thanks for taking the time to filing an issue. Before you submit, please read the following:

Check for other issues already opened, to see if your issue/suggestion has been reported already.
Ensure that you have all the relevant information on hand. Such as logs/reports and information about a request/change.
-->
```

Maybe clarify in [ISSUE_TEMPLATE.md](https://github.com/DarkPacks/SevTech-Ages/blob/master/.github/ISSUE_TEMPLATE.md) that one needs to select a different issue template else their issue is ignored?

**Comment by artdude543** [comment]
This is just how GitHub works for logged out users.

**Comment by CyaNox** [comment]
I disagree. As you can see in #2856 it is presumed that I have deliberately ignored or deleted the template which I did not. This is accusational and therefore comes over as rude.

I know you are working with a template there but it is still rude.

Even changing that default template to the "bug report" template would have avoided this annoyance and the unintended rudeness. So I'd like to propose you change this "default" template.

**Comment by artdude543** [comment]
The `choose` feature in GitHub allows having more than one kind of template. It's known to bug out sometimes and not actually take you to the right place. But that's not our fault.

But default if an issue does not follow the template it will be ignored and closed. You can take this in the wrong way if you want but we won't change how we handle issues. I have updated my auto-response to contain a link to the choose page. And I'll update the default template to contain a link to said page also.

But the default template won't ever be the bug report one. It defeats the point of using the multi-choice system. You can't get upset about an auto response. We need defined issues with content and data. We're not being paid to handle your issues or make the pack. It's a hobby. You want to report an issue then give us all the details and logs/screenshots etc...

But I have taken your comments on board and are planning on making some changes.
