### ISSUE TITLE
Energy Bridge Receiver not working in overworld

### ISSUE THREAD

**Issue by CyaNox** [DarkPacks/SevTech-Ages#2859]
## Bug Report

The Energy Bridge Receiver from Ender Utilities is not working in the overworld since the bedrock layer is replaced by Bedrock-B-Gone.
The energy bridge did not create its beacons and therefore did not activated.

## Expected Behaviour

The beacons to light up either red or greenish.

## Possible Solution
Workaround: Doing a `/setblock ~ 0 ~ minecraft:bedrock` while standing on the location of the Receiver made it work.

## Steps to Reproduce (for bugs)

1. Build the energy bridge multiblock structure as described on: https://minecraft.curseforge.com/projects/ender-utilities
2. Ensure you dug straight down to bedrock below the bridge receiver block and that the sky is not obstructed.
3. Apply workaround to see it actually works with the correct bedrock block.

## Logs

* Client/Server Log: [Client](https://pastebin.com/VQT8tLTk) [Server](https://pastebin.com/DfxiNtsu)
* Crash Log: N/A

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_171
* Launcher Used: MultiMC
* Memory Allocated: 4G
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.7

* Additional Content Installed: None

## Server Information
* Java Version: 1.8.0_171
* Operating System: Linux
* Hoster/Hosting Solution: Self
* Sponge (Non-Vanilla Forge) Server: No

**Comment by artdude543** [comment]
The mod has updated to allow a config entry of blocks. When the new update of SevTech is planned it will be included with the changes.

**Comment by artdude543** [comment]
Will be fixed when 3.1.0 releases 😄
