### ISSUE TITLE
Primal Tech Clay Kiln uncraftable in Age 0 [3.0.8]

### ISSUE THREAD

**Issue by Heraklade** [DarkPacks/SevTech-Ages#2861]
## Bug Report
Current Behavior:
The clay Kiln, used to make Low Grade Charcoal, has become uncraftable in Age 0,
The recipe, which seems to have changed with the Update to Version 3.0.8, now no longer requires a cobblestone slab. However, this new recipe cannot be crafted in the Workstump, or the Workstump Mk 2 for that matter.
The advancement info still states that the clay kiln requires clay and a cobblestone slab to be crafted 

## Expected Behaviour
Clay Kiln has to be craftable, in order to progress further into the advancement tree

## Possible Solution
Revert to the old crafting recipe (with the cobblestone slab) or make the new crafting recipe (without the slab) a valid crafting recipe

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_25 64bit
* Launcher Used: Twitch
* Memory Allocated: 4GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: Optifine

**Comment by bombcar** [comment]
My version 3.0.8 has the recipe taking any cobblestone slab.

**Comment by artdude543** [comment]
The recipe is still valid your doing something wrong. It was changed to allow more slab types.
