### ISSUE TITLE
Trying to use geolosys field manual freezes the game

### ISSUE THREAD

**Issue by milibucket** [DarkPacks/SevTech-Ages#2863]
Game version: 3.0.8
World created in: 3.0.6
Optifine used 
When I try to open the field manual, the game freezes, I waited for like 5 minutes and the game is still stuck, sorry I didnt wait till the game crashes by itself, I just force shut down as I run out of patience

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by milibucket** [comment]
Oops! really sorry, I will read trough the rules this time, and re-create a new one. Sorry for the trouble
