### ISSUE TITLE
Sentient armor gem not turning on

### ISSUE THREAD

**Issue by pepi-tsankov** [DarkPacks/SevTech-Ages#2864]
Type: bug, loss of item ability?
 What happened:
I crafted a sentient gem.
Then I turned it on and off to see if it works.
Then I turned it on and moved it to my inventory.
Then I moved it into a golden backpack.
Closed the backpack.
Opened the backpack, took the gem out and turned it off.
The gem will now no longer turn on.

I am running the current version of the modpack (3.0.8)

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
