### ISSUE TITLE
crash when ftbutilites is added to server

### ISSUE THREAD

**Issue by dodgythoughts** [DarkPacks/SevTech-Ages#2865]
## Bug Report

Ftbutilites added to stop griefing on public server, worked fine under v3.0.7 but 3.0.8 causes a crash.

## Expected Behaviour

Ftbutilites should allow chunk claiming.

## Possible Solution

have logged this with FTButilties github
https://github.com/LatvianModder/FTBUtilities/issues/780

## Steps to Reproduce (for bugs)

1.add ftbutilities/ftblib to server files
2.run

## Logs

* Client/Server Log:
* Crash Log:
https://pastebin.com/0i06D0nL

## Client Information

* Modpack Version: 3.0.8
* Java Version: 
* Launcher Used:Linux
* Memory Allocated:20480MB
* Server
* Optifine Installed:no
* Shaders Enabled:no

## World Information

* Modpack Version world created in:

* Additional Content Installed:
ftbutilties/ftblib
sampler
laggoggles

## Server Information
* Java Version:1.8.0_171
* Operating System:Ubuntu server
* Hoster/Hosting Solution:my own.:

**Comment by artdude543** [comment]
Sorry support for additional mods installed is not given. You can try our Discord. But the tracker is out of bounds for modded installations of the modpack.
