### ISSUE TITLE
Ladder Skin Reset - Block state

### ISSUE THREAD

**Issue by pocketpacket** [DarkPacks/SevTech-Ages#2866]
## Bug Report

**Login and ladders return to block sate, until any ladder is broken
then they return to normal. Yes, this is minor**

**A ladder should be a ladder, after being made.. sure**

## Expected Behaviour

**a ladder, you climb it and stuff. Minor bug but happens over and over**

**Ladder skin = Good, Block ladder = bad**

## Possible Solution

no comment

no comment

## Steps to Reproduce (for bugs)

![2018-06-12_07 04 59](https://user-images.githubusercontent.com/40080476/41316745-097459c4-6e48-11e8-8fb5-dc6d85bc7e7e.png)
![2018-06-12_07 05 28](https://user-images.githubusercontent.com/40080476/41316746-098f6764-6e48-11e8-98c4-82a29397c681.png)
![2018-06-12_07 05 47](https://user-images.githubusercontent.com/40080476/41316747-09ac6e0e-6e48-11e8-9702-1f811d28290a.png)

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.8 Client and 3.0.8 Server
* Java Version:8.171
* Launcher Used: Minecraft, Forge
* Memory Allocated: 16-19 server , 8 client
* Server/LAN/Single Player: Server, Internet
* Optifine Installed: Yes 1,12,2 HD_UD1
* Shaders Enabled: No, SoarTex Fanver, yes

## World Information

**World Generated in 3.0.7 May 11th,  updated to 3.0.8, no issue in 3.0.7**

* Modpack Version world created in: 

**Just what came in pack.**

* Additional Content Installed:

None

## Server Information
* Java Version: 8.171
* Operating System: Ubuntu 18.4
* Hoster/Hosting Solution: Me, Multi-Player, Yes
* Sponge (Non-Vanilla Forge) Server: Forge 2707

**Comment by artdude543** [comment]
This is known and can't be fixed till later on in development. I.E. When GameStages 2.0 lands when ever.
