### ISSUE TITLE
IE Assembler won't form

### ISSUE THREAD

**Issue by AndrewR73** [DarkPacks/SevTech-Ages#2868]
## Bug Report
The Immersive Engineering Assembler multi-block structure will not form when (right) clicking the conveyor belt as directed by the in-game IE Manual (also instructed on IE Wiki). When clicking the conveyor the belt will rotate instead of forming the Assembler, Ctrl+Clicking causes the belt to angle up/down, and clicking any other block does nothing. After the first click, the conveyor rotates, and all subsequent clicks then display the message "You cannot for this Multiblock! Further Progression is Required."

## Expected Behaviour
Using the Projector, and placing all the pieces parts in their correct location shows a green box outline, a click of the hammer on either conveyor is supposed to form the Assembler. I have ensured proper construction, but the formation will not happen regardless which conveyor belt is clicked.

## Steps to Reproduce (for bugs)
1. Use Projector or follow image in IE Manual to form multi-block structure
2. Use Engineer's Hammer to right-click the desired input conveyor belt
3. Formation does not happen

## Client Information
* Modpack Version: 3.0.8
* Java Version: 1.8.0_161
* Launcher Used: Twitch
* Memory Allocated: 10GB
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.6
* Additional Content Installed: none
![2018-06-12_16 18 45](https://user-images.githubusercontent.com/8558973/41323594-45559ea0-6e64-11e8-8743-62c360c7f24f.png)
![2018-06-12_16 59 00](https://user-images.githubusercontent.com/8558973/41323595-456c52d0-6e64-11e8-9c6c-cc169deee45f.png)

**Comment by Stifling-Bossness** [comment]
Looking at #1803 They seemed to be having some issues with staging it, so it forming the multiblock may have been disabled?

On an unrelated note, you should probably dial back your memory allocation to 7-8GB-ish as higher values can see degradation in performance.

**Comment by artdude543** [comment]
The conveyors are probs in the wrong direction. The projector displays these wrong. Change the direction and it will form. But this is not a pack issue.

**Comment by AndrewR73** [comment]
@artdude543 ... I'm sorry but you are very much wrong in this case. If you look at the structure of the Assembler it is a symmetrical build along the perpendicular center-line... that is, one conveyor in, light engineering block, one conveyor out. It's a 3x3 footprint. The conveyors both rotate in the same direction, one going into the machine, the other coming out. It doesn't matter which one is input or output, just that one is in the other out. I have placed the conveyors per the projector, per the online WIKI, per any other documentation for IM, and the structure *WILL NOT FORM*. I have used this mod in numerous other packs, performed the same action in all those other packs, with the expected result. This pack, it doesn't work. Hitting the conveyor with the hammer (as you are supposed to) only rotates the conveyor. I have tried from both sides. I have rotated both conveyors first one way then the other, opposite each other, away from each other, you name it. Nothing. This is broken.

I reject your "User Error" assessment and request another actual look into this.

**Comment by artdude543** [comment]
I did test thing along with all the same reports on here and our Discord about the same exact thing. The conveyors were always in the wrong orientation. You can reject this as much as you like but that won't change a thing.

It's not broken I can tell you that now. The next thing you could check is that your staging is correct by using the command `/gamestage info` to see if you have the correct stage. But that fact I've just watched a stream about 5 mins ago build one and form one on 3.0.8 shows to me that it's working fine. I'll even boot up an instance and make a video if you'd like?

On another note as pointed out by @Stifling-Bossness the Assembler is currently worthless as it's not staged on anything above Tutorial _(and some cases Zero)_ in terms of crafting due to a bug. So it's currently a waste of materials making one till that bug is fixed.

**Comment by AndrewR73** [comment]
@artdude543 I appreciate the depth of information this time around. I have run into far too many admins that seem to dismiss (almost out of hand) issues that arise as "User Error", and it gets frustrating after a while. With that said, thanks for responding...

I have created a short (2min) video showing what I am talking about: https://www.youtube.com/watch?v=a7aUiXAjeoY

Please tell me if I am doing something facepalm-worthy stupid here, but it just is not working.

I have built the Assembler exactly per the IM Manual/Wiki: https://ftb.gamepedia.com/Assembler_(Immersive_Engineering) but as you'll see, nothing is happening.

I ran the command you suggested, and what I get back is:
"zero, one, three_mob, tutorial, two, three"

Is this stage info preventing me from forming the Assesmbler?

But your comment about the staging of the Assembler from @Stifling-Bossness (as I understnad what you're saying) the Assembler doesn't work on any stage above the initial Tutorial stage? I am currently on Age 3, and I was just looking for a way to automate some of the more mundane crafting tasks, and as I have used IM in the past, and in those packs the Assembler fit the bill quite nicely. This still doesn't explain why I cannot get the thing to form, but regardless, if it is not going to work for recipes unlocked at higher Ages, then you're right... there is no point. Not sure why this decision was made, but it seems a little restricting to the player over and beyond the restrictions already in place. But that's just my opinion.

Thanks again for the reply, and appreciate the help.

-- Andrew

**Comment by TheBunz90** [comment]
I have this same issue, my question is does the Assembler actually not unlock till Age 4? I'm currently in Age 3, have crafted everything I need to and placed it down correctly but the machine will not form and gives the same errors you showed in your video.

**Comment by artdude543** [comment]
As stated in my comment above @TheBunz90 it's pointless to make the machine due to the technical limitation that it can't make anything above stages Tutorial (which is the stuff you'd probs want to work) we have no idea when this will work again.

Unless you want to automate Tutorial things but not sure what tbh. But forming does work its a tad buggy and it does check for rotation on the conveyors one needs to be in and other out. Other than that it's not a pack issue.

**Comment by Deepsniper** [comment]
I would like to mention I have received the same error. Was attempting to build the assembler in Age 3 to turn melons into seeds. Should be simple right? but the system isnt working. 

Any update on this yet?

**Comment by TheBunz90** [comment]
Pretty sure the assembler isn't supposed to be available until Age 4 it's just sort of coincedental that all the pieces needed for it are available in Age 3. I actually took a look at the code myself and found a staging file for Immersive Engineering machines that had both the Assembler and Bottling machine listed under "Stage 4" which I assume means Age 4.

This is just my guess but...pretty certain.
