### ISSUE TITLE
Client crash on server

### ISSUE THREAD

**Issue by Athenus** [DarkPacks/SevTech-Ages#2869]
## Steps to Reproduce (for bugs)

1. The game just crashed. Happened for both my friend and me. Only crashes client, not the server. This only started happening after updating to the latest 3.0.8 version.

## Logs
* Client Log: https://pastebin.com/Rt9TWZte
* Crash Log: https://pastebin.com/3TJSC4yZ

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0.161
* Launcher Used: Twitch
* Memory Allocated: 6 Gigs
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.7

* Additional Content Installed:

## Server Information
* Java Version: 1.8.0.161
* Operating System: Mac OSX
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
Your client install is broken and missing files. Re-Install the entire client.
