### ISSUE TITLE
Collecting ore samples before you are supposed to.

### ISSUE THREAD

**Issue by ShakeforProtein** [DarkPacks/SevTech-Ages#2872]
## Bug Report

Using Chisel & Bits it is possible to collect ore samples from rocks before you know what they are. By chiselling the ground under the rock, it will break into it's sample regardless of whether you knew it was a sample. I imagine this is not intended but cannot suggest a way to prevent it that would leave my massively chisel and bits base standing.

## Client Information

* Modpack Version: 3.0.7
* Java Version:  Not sure, the most recent one.
* Launcher Used: 8GB
* Memory Allocated: 9
* Server/LAN/Single Player: SP
* Optifine Installed: Yes
* Shaders Enabled: Anything that came preinstalled with the pack

## World Information

* Modpack Version world created in: 3.0.6 / 7

* Additional Content Installed: Just optifine

**Comment by artdude543** [comment]
This is known and can't be fixed w/o major changes to the base code from the mods we use. It's a pointless thing anyhow. Who would waste their time to do this full time?
