### ISSUE TITLE
[3.0.8] No ages after update, advancements persist.

### ISSUE THREAD

**Issue by OrpheusSummanus** [DarkPacks/SevTech-Ages#2873]
## Bug Report
Stages don't persist after server update.

## Expected Behaviour
Expected to be able to keep playing as before the update.

## Possible Solution
Re-sync command that checks the player advancements and updates stages accordingly (cant find such a command if it already exists)

## Steps to Reproduce (for bugs)
1. Played on 3.0.7 progression through the pack as usual
2. Updated server to 3.0.8
3. Moved over the world save, ops and server properties

## Logs
- client / server do not crash - if needed I can grab the latest log of my client and the server regardless.
* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 3.0.8
* Java Version: openjdk:8-jre
* Launcher Used: Twitch app
* Memory Allocated: 3072MB+
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.6
* Additional Content Installed:

## Server Information
* Java Version: openjdk:8-jre
* Operating System: 
* Hoster/Hosting Solution: Nodecraft
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
If stages are missing you did not upload the files correctly. And/or missing the scripts folder on the server or client. This is a _you_ issue. Re-upload all the files to the server, after deleting the folders mentioned on the update notes.
