### ISSUE TITLE
LAN Quest Bug

### ISSUE THREAD

**Issue by Datsukorn** [DarkPacks/SevTech-Ages#2875]
I think this issue may be already known in the community but I still couldn't find much on the issue. When playing on a LAN hosted world, it seems like only the host is able to complete quests, even when you are teamed using the friends mod. And even when you are not using it, players who are not the host still can't complete quests.

Me and my friend are using the most recent version of the pack at the time of this writing and have both allocated 6 GB of RAM.

**Comment by therealbill** [comment]
I just ran into this as well, went looking and found this bug report. So I'm adding a "me too" to it.

**Comment by artdude543** [comment]
Sadly LAN is not supported via our normal support methods. You can try our Discord to see if anyone can help in regards. But due to the number of issues LAN itself-causes with modpacks. We don't advise on using them. And suggest that you use dedicated server instances.
