### ISSUE TITLE
Water wheel duplication

### ISSUE THREAD

**Issue by liquorice-wb** [DarkPacks/SevTech-Ages#2876]
Latest update (V3.0.8)
Better With Mods water wheel duplicating when axle holding it is broken (drops 1 axle and 2 water wheels). Easily replicatable.

**Comment by artdude543** [comment]
_Can you report this on the BWM own tracker please also, you can't expect us to report all issues to mod devs ourselves_

_(Canned response)_

Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
