### ISSUE TITLE
Hydrator from Cyclic no longer working?

### ISSUE THREAD

**Issue by sharktemplar** [DarkPacks/SevTech-Ages#2877]
I used the hydrator to create packed ice before the most recent update and it worked fine, but now there is a black meter bar to the left of the water meter, and hovering your cursor over it displays overlapping pop-up info near the top of the black meter. 
It also no longer produces packed ice (or maybe anything at all, have not tested it with anything but packed ice crafting attempts) 
I'm not a dummy, I made sure it was set to Always On and didn't require a redstone signal.

**Comment by Stifling-Bossness** [comment]
It now requires RF

**Comment by PrinceOfAmber** [comment]
Yes please make sure it has water, power, and the redstone signal is set up.



![hydrator](https://user-images.githubusercontent.com/621529/41391242-4608b874-6f4e-11e8-8175-adbf96ccd089.gif)

[GIF test was done in isolation not within modpack, don't close without verifying]

**Comment by artdude543** [comment]
Yes, it requires RF and Water to function. I guess we missed this on the changelog notes. But as shown above  _(and I tested)_ it works when supplied with the required resources.
