### ISSUE TITLE
Severe, consistent lag spike every 3 minutes

### ISSUE THREAD

**Issue by sharktemplar** [DarkPacks/SevTech-Ages#2884]
I have a huge mob farm which is roughly 2 chunks long and 3 chunks wide, built high in the air and has a large lighting system to easily deactivate spawning within it. It's currently disabled so no spawning, no experience, and no items of any kind are being created or processed, however every 3 minutes exactly, I receive a huge, very severe lag spike that lasts for over 9 seconds, completely locking my javaw.exe into an unresponsive state. 
I already had to go in and change aroma to only backup every 60 minutes instead of every 30 because the constant backing up resulting in obnoxiously long periods of time where everything froze up until the backup was complete was just too insufferable to bear, so I suspect aroma may also be doing something else in the background every 3 minutes which checks the surroundings of my player, and due to my mob farm being so huge to maximize efficiency, I suspect that might be what's causing this. 

It is making my mob farm borderline unplayable to be near, and I was planning on building a great deal more right beside it as well so as to keep it running whilst I constructed other very large build projects next to it. 

Is there anything that was added in the most recent update for sevtech that might be causing this? It only happens near/beside/inside of my mob farm, but I do not think it is linked to simply having the structure loaded in a chunk, as I built it above my base, so the blocks that make it up are actually loaded in 24/7, but only when I go up to it does the absolutely unbearable 9+ second lag-spike occur every 3 minutes approximately. 

Screenshot of said mobfarm, from perspective of my ground base looking upwards: https://i.imgur.com/UkUgf1D.png

Any tips on what mods were added which I might try to disable entirely to see if it stops? I simply cannot continue playing sevtech anywhere near my mob farm with this happening at perfect consistency. 

I always give sevtech 10 gigabytes of ram to work with, so I very very much doubt it's a problem like that.

Edit: On further inspection, it appears the lag spike INITIALLY occurs every 3 minutes consistently, however I notice the javaw.exe begins taking more and more and more memory according to my task manager that eventually these lag spikes occur every 5 seconds when it surpasses 12,600,000K. 
I usually only start reaching that memory usage when doing mass-exploring that causes an enormous amount of new generation of the environment to occur, but now simply being near my mob farm causes the memory to skyrocket at a rate even quicker than large terrain generation used to.
Something that was added in this last update is seriously slurping my resources dry to the point the game begins chugging along, unable to keep up simply by me standing there doing absolutely nothing, and without anything actively changing nearby besides a stoked cauldron's bellow changing states back and forth constantly as intended. 
I literally am incapable of playing sevtech for longer than 10 minutes anywhere near one of my most valuable builds that I was planning on moving everything to. 
If this can't be pinpointed and fixed, can anyone please direct me to the necessary instructions to revert sevtech to the previous update so I can at least continue construction and await a more stable update? 

Edit 2: In case it is worth mentioning, during these huge lag spikes, the javaw.exe CPU jumps to 75-80 where it usually hangs around 35 at all other times. Something the new update added that is told to operate every 3-ish minutes in the background is definitely causing this. 

Edit 3: Restarting my computer and launching sevtech again causes the same behavior, however I have discovered a caveat that may or may not act as an obnoxious, temporary quick-fix for my situation that hopefully can help others who have enormous/complicated builds that run into this issue: 
Once my javaw.exe that is Minecraft itself reached 13,000,000K memory usage (according to task manager), saving and quitting to the main menu, then loading the world back up has removed the consistent 3-minute mega-lagspike and CPU usage bumped down to the regular 17 average... but only for a time. The memory still increases for no reason up to exponentially unnecessary levels. It raised all the way up to 14,120,000K over the course of roughly 20 minutes before jumping back down to 13,700,000K and immediately resuming the consistent 3-minute lag-spikes and the doubled CPU usage back to 35.
Not to mention that just sitting in the main menu rests the CPU usage at around 11,700,000K when before this most recent sevtech update, sitting in the main menu would never go above about 8,000,000K for me and that was only immediately after saving and quitting out of doing heavy terrain-generation exploration. 
Will edit again if I find any further behavior. This is seriously completely destroying my sevtech experience, which sucks because I have probably over 300 hours invested in this and had no plans of slowing (currently at beginning of age 4 and like to take my sweet time).

**Comment by artdude543** [comment]
_Sorry about doing this but this has to be done to enforce the rules copy this information over to the fixed issue however in the correct section but make sure **all** the data is filled in_

_(Canned Response)_

Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
