### ISSUE TITLE
No way past Age 0, short of cheating via command line.

### ISSUE THREAD

**Issue by Solverbolt** [DarkPacks/SevTech-Ages#2885]
## Bug Report
 Attempting to make the final achievements but none of the recipes work.

## Expected Behaviour
 How about actually verifying that the recipes that you implement in a modpack actually work, instead of claiming they work, and then warming your hands with your own exhaust. 

## Possible Solution
 At this point, I have ZERO faith in this modpack of ever being fixed. its a joke and a poor one at that

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

Frankly, I am going to stop submitting information, as I am using the most current version of everything, short of my OS being Windows 7, because Windows 10 is almost as big of a joke as this modpack.

**Comment by Stifling-Bossness** [comment]
If you're not going to put in the effort of properly reporting an issue, then why should the devs put in the effort to solve it?

**Comment by Solverbolt** [comment]
just like a worthless coward. The moment i played this modpack, i could tell
