### ISSUE TITLE
Work Blade can be repaired in Item Repairer despite work blade tooltip

### ISSUE THREAD

**Issue by Stifling-Bossness** [DarkPacks/SevTech-Ages#2886]
## Bug Report
Despite their tooltip saying "Can not be repaired," work blades can be repaired in the Actually Additions Item Repairer.

## Expected Behaviour
Work blades cannot be repaired, or no "can't repair" tooltip.

## Possible Solution
If the item repairer has a blacklist, add work blades to it, or adjust the tooltip?

## Steps to Reproduce (for bugs)
1. Damage a work blade (For my test, I used an iron work blade)
2. Shove it in the item repairer and watch that durability tick up

## Logs
* Client Log: https://gist.github.com/Stifling-Bossness/f8371f55e55cb72344b9ec5c8187d2ea

## Client Information
* Modpack Version: 3.0.8
* Java Version: 8_172
* Launcher Used: Twitch 7.5.6736.42856
* Memory Allocated: 7GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No
* Mods Disabled: Better Foliage, Fancy Block Particles

## World Information
* Modpack Version world created in: 3.0.6

**Comment by mtitus13** [comment]
As an addendum, if you repair a flint work blade with flaked flint, the flaked flint amount will multiply. For example, putting a flint work blade in with a full stack of flaked flint (64) will cause the stack to become 122 when you take the partially repaired work blade from the results side

**Comment by Stifling-Bossness** [comment]
@mtitus13 That sounds very similar to #2358 , which should have been fixed in 3.0.8
