### ISSUE TITLE
Using Field manual freezes the game

### ISSUE THREAD

**Issue by milibucket** [DarkPacks/SevTech-Ages#2887]
## **Bug Report**

Trying to open a geolosys field manual freezes the game, I force shut down minecraft after waiting for 5 minutes as the game did not respond.

## Expected Behaviour
I wanted to check the Y levels of gold ore but when I opens the field manual it just freezes the game instead of bring up a gui

## Steps to Reproduce (for bugs)
Try to open geolosys field manual ingame

## Logs

* Client/Server Log: https://pastebin.com/B3z096iZ
* Crash Log: The force shut down did not create crash report

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_161
* Launcher Used: Minecraft official launcher (the one downloaded from minecraft.com)
* Memory Allocated: 6G 
* JVM Arg: -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn3G
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: Yes 1.12.2 HD_U_D1
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.6

* Additional Content Installed: 
   sound filters mod
   oops mod
   torohealth mod
   dynamic surrounding mod
   sound reloader mod
   Optifine
   LagGoggles mod
   Mmmmmmm(target dummys) mod
   Dramatic skies resourcepack
   Audiocraft as resources pack
* Mods deleted:
   Smooth font
   Better foliage

**Comment by ByteTemplar** [comment]
If you add any mods to modpack, you wont get any support here...

You might try the Discord server...

**Comment by artdude543** [comment]
Yeahhh this is a Discord thing. You have way too many mods installed for this. Including ones which change how rendering works.

**Comment by xchoo** [comment]
Can confirm, Optifine will crash the client when you try to open the Geolosys manual.
