### ISSUE TITLE
Mining Osmium with Silk Touch generates ContentTweaker ore, which can't be processed normally

### ISSUE THREAD

**Issue by wlf773** [DarkPacks/SevTech-Ages#2890]
## Bug Report

ContentTweaker Osmium Ore can't be processed in the same ways as Mekanism Osmium Ore, and is obtained by STing Osmium.

## Expected Behaviour

STing Osmium gives Mekanism Osmium Ore OR ContentTweaker Osmium Ore is processed the same as Mekanism Osmium Ore.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
