### ISSUE TITLE
LAN Players Advancements Not Advancing

### ISSUE THREAD

**Issue by MokahTGS** [DarkPacks/SevTech-Ages#2895]
## Bug Report
Players in a Singleplayer hosted LAN game are not advancing each others advancements when completing them.  The host player can do advancements and they sync to the LAN player.  If the LAN player does them they do not sync.

Before the last update this bug did not happen.  Something changed that makes this impossible to play in a hosted LAN environment.

I don't understand how this was working before in our LAN environment and now it doesn't?  This bug makes it impossible to play in LAN.

## Expected Behaviour
Advancements sync to all players no matter who does them on the team.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 3.0.8
* Java Version: 8
* Launcher Used: Twitch
* Memory Allocated: 8g
* Server/LAN/Single Player: SP Hosted LAN
* Optifine Installed: Nope
* Shaders Enabled: Nope

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed:

**Comment by Stifling-Bossness** [comment]
LAN is broken by default (even in vanilla it's kinda wonky), the recommended way is to use the dedicated server software.
