### ISSUE TITLE
PrimalCore Fire Bow doesn't show in NEI/JEI and doesn't function as intended

### ISSUE THREAD

**Issue by monodemono** [DarkPacks/SevTech-Ages#2896]
## Bug Report
The PrimalCore Fire Bow doesn't show in NEI/JEI (as shown below) and the tooltip says it can be used to light torches at the cost of sticks, but the only way to use it on a torch is to shift+right click, but upon doing so it just sets fire to the block next to the torch instead of the torch itself (also shown below).

<img width="1920" alt="screen shot 2018-06-15 at 19 11 42" src="https://user-images.githubusercontent.com/1161277/41494946-37d69ecc-70d1-11e8-92ff-1814b1bdeedb.png">
<img width="1920" alt="screen shot 2018-06-15 at 19 26 12" src="https://user-images.githubusercontent.com/1161277/41494993-01d7207a-70d2-11e8-90e5-8ae7a561e3a9.png">

## Expected Behaviour
The Fire Bow should be in NEI/JEI, and it should change the Un-Lit Fibre Torch to a Lit Fibre Torch, and shouldn't set the neighboring block on fire for that matter.

## Steps to Reproduce (for bugs)
1. Type "Fire Bow" or "@PrimalCore" or anything else into NEI/JEI that should bring it up, and note that it's not there.
2. Put an Un-Lit Fibre Torch down, and right click it, and shift+right click it with the Fire Bow in your hand and sticks on your hot bar.
3. Notice that the torch never lights, and instead the block next to the torch on the side of the torch that you were shift+right clicking lights on fire.

## Client Information
* Modpack Version: 3.0.8
* Java Version: 1.8.0_171 (64-bit)
* Launcher Used: Twitch
* Memory Allocated: 8,192 MB
* Server/LAN/Single Player: Single (Creative)

## World Information
* Modpack Version world created in: 3.0.7

**Comment by An-Sar** [comment]
support for lighting the fibre torch has been added in dev to PrimalCore, included for next release (0.6.57)
