### ISSUE TITLE
Celestial Gateway/Mekanism Teleporter not working correctly on Extra Planets

### ISSUE THREAD

**Issue by z0dri3L** [DarkPacks/SevTech-Ages#2897]
## Bug Report
I play on SP and I have Celestial Gateways (CGs) and Mekanism teleporters on many planets and moons of Galacticraft and Extra Planets, but after loading my world while being in my base in the overworld only Ceres and Jupiter are available. In the CG the stars for all other locations in other dimensions (Moon, Mars, Venus, Phobos, Deimos, Asteroids) cannot be seen/selected. The same is true for the Mekanism portable teleporter (PT). I can see all the CGs in the overworld and those in the nether. After entering the dimension via a rocket, it also appears in the CG and PT until I exit and load my world again. I have Weirding Gadget very close to all CGs and teleporters with anchor upgrades installed. 

## Expected Behaviour
All existent CGs and Mekanism teleporters near Weirding Gadgets OR with installed anchor upgrades should be available when loading/entering my world.
Also: I already used the CGs in modpack version 3.0.7 and they worked fine for Moon and Mars. I read they changed the dimensions for all the planets lately. Maybe that's the cause?

## Possible Solution
Check/change the chunk/dimension loading of Weirding Gadget and the anchor upgrades (?)

## Steps to Reproduce (for bugs)
1. Place down CGs and/or Mekanism teleporters (with anchor upgrades installed) in the Overworld, Nether, Moon, Mars, Asteroids, Ceres,, Jupiter, Saturn (...) and with Weirding Gadgets nearby.
2. Exit/close world in the Overworld dimension.
3. Load and enter world in the Overworld dimension.
4. Only see CGs and Mekanism porting points of the Overworld, Nether and maybe Ceres and Jupiter.

## Logs
* Client/Server Log:
https://gist.github.com/z0dri3L/bb00f81af127ff25ba4b9aaa8167b3bb
* Crash Log:

## Client Information
* Modpack Version: 3.0.8
* Java Version: 1.8.0_171
* Launcher Used: MultiMC 5 0.6.2-1222
* Memory Allocated: 8000 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: OptiFine_1.12.2_HD_U_D3
* Shaders Enabled: no

## World Information
* Modpack Version world created in: 3.0.6
* Additional Content Installed: OptiFine_1.12.2_HD_U_D3

**Comment by Stifling-Bossness** [comment]
I believe this is related to/a duplicate of #2004
