### ISSUE TITLE
Game freeze from Geolosys Manual

### ISSUE THREAD

**Issue by zamyt** [DarkPacks/SevTech-Ages#2901]
## Bug Report
The game froze when i tried to open the field manual of geolosys.

## Steps to Reproduce (for bugs)
Open the geolosys manual. I tried a 2nd time and still game froze.

## Logs
There are no logs since i had to manualy close minecraft the 1st time. The 2nd time my whole pc froze so i had to force restart by holding the power button.

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_161
* Launcher Used: ATLauncher
* Memory Allocated: 5GB
* Server/LAN/Single Player: Single Player with cheats enabled.
* Optifine Installed: Yes.
* Shaders Enabled: No.

## World Information

* Modpack Version world created in: 3.0.4 or 3.0.5 or maybe 3.0.7 not sure.

* Additional Content Installed: Disabled Better Foliage, Fancy Block Particles, Smooth Font.

I also have these java arguments: -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

**Comment by kristu** [comment]
i have same problem too and my java version is 1.8.0_171

**Comment by xchoo** [comment]
Do you have optifine installed? I found that with optifine installed, the game would freeze when opening this manual.

**Comment by Aegisix** [comment]
There is already a fix for this in the Geolosys cfg file - set the unicode setting at the bottom to false. The reason for the crash is that Optifine doesn't support unicode. (and probably will never)

**Comment by artdude543** [comment]
This a compat issue at the end of the day. Geo did some changes in the newest update so that _could_ help but this is an Optifine issue.

Thanks for the report!
