### ISSUE TITLE
Game Crashes after loading world

### ISSUE THREAD

**Issue by aprilsjester** [DarkPacks/SevTech-Ages#2902]
## Bug Report

crash after exiting the loading screen (i can see my hotbar but crash soon follows)
## Expected Behaviour

not crashing...
## Steps to Reproduce (for bugs)

occurs whenever I load into the world. started crashing on the at launcher for no apparent reason when loading the world and started crashing on the twitch launcher once a pile of sticks was destroyed

## Logs

* Client/Server Log:
* Crash Log:
[crash-2018-06-16_18.56.47-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/2108354/crash-2018-06-16_18.56.47-server.txt)

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_161
* Launcher Used: Twitch 
* Memory Allocated: 8Gb
* Server/LAN/Single Player: Single Player
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: most likely 3.0.7

* Additional Content Installed: none

**Comment by Stifling-Bossness** [comment]
> Then upload the latest/crash logs to PasteBin or Gist. DON'T Upload them to GitHub

It says this in the template, edit your post or reply with the URL once you've uploaded the crash log elsewhere.

**Comment by aprilsjester** [comment]
https://pastebin.com/dp81tHed

**Comment by artdude543** [comment]
You have a broken region file. Which won't be fixable. You'll have to find that file which is broken in the save files and delete it for it to regenerate for the world to be usable again.

Note: Obvs anything in that chunk/region will be deleted.

This tool can help find the file for the cords: https://dinnerbone.com/minecraft/tools/coordinates/

Which are: `World: (460,64,253), Chunk: (at 12,4,13 in 28,15;)`

Note: That Minecraft can report the wrong thing for cords and/or more than one may be broken. So you may end up losing the entire world in that case. But there is nothing from the pack side we can do. Sorry.
