### ISSUE TITLE
SevTech Crash Second Run

### ISSUE THREAD

**Issue by BoboTheHunter** [DarkPacks/SevTech-Ages#2910]
## Crash Report
After a clean install the pack starts up fine, but after closing the game and starting it back up again it crashes at the end of step 6/7. Furthermore the same crash happens when exiting a server.

## Logs

* Client/Server Log:
* Crash Log: [Crash Log](https://pastebin.com/SkVZx6zT)
## Client Information
* Modpack Version: 3.0.8
* Java Version: 1.8.0_25
* Launcher Used: Twitch
* Memory Allocated: 8192 MB
* Server/LAN/Single Player:
* Optifine Installed: No
* Shaders Enabled: No

## Edit
Thinking things that change between a clean install and a second run of a pack: 
-    The options

Appearantly assigning someting to 'mouse button 4' crashes on loading the main menu. 

It even prevents from joining a server:
- Internal Exception: com.google.common.util.concurrent.UncheckedExecutionException: net.minecraftforge.fml.common.Loader.ExceptionModCrash: Caught exception from Minecraft Forge (forge)

**Comment by temp1011** [comment]
Same thing as https://github.com/DarkPacks/SevTech-Ages/issues/2893?
