### ISSUE TITLE
Bronze tools require copper to construct

### ISSUE THREAD

**Issue by xchoo** [DarkPacks/SevTech-Ages#2911]
## Bug Report
Bronze tool recipes requires copper plates. (Tested with bronze pickaxe only -- requires bronze ingots to repair)

## Expected Behaviour
Bronze tools should require bronze plates to construct, no?

## Possible Solution
Change recipe to use bronze plates.

## Steps to Reproduce (for bugs)
1. Get to Age 1
2. Try to construct bronze tools
3. See that copper plates are used.

## Client Information
* Modpack Version: 3.0.8
* Java Version: 1.8.0_171
* Launcher Used: MultiMC
* Memory Allocated: 6GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.6
* Additional Content Installed: None

**Comment by Stifling-Bossness** [comment]
Duplicate of #2802

**Comment by xchoo** [comment]
Whoops! I searched the open issues for this report. Neglected to search the closed issues.. :stuck_out_tongue:
