### ISSUE TITLE
slim boots vanish when i log off my friends server but will reappear when i click my boot slot 

### ISSUE THREAD

**Issue by DynamicTypo** [DarkPacks/SevTech-Ages#2913]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
Known won't be fixed for about another update or two.
