### ISSUE TITLE
Better With Mods Saw giving wrong moulding variants

### ISSUE THREAD

**Issue by Unit42** [DarkPacks/SevTech-Ages#2916]
When using the saw from Better With Mods on wood sidings it gives the correct moulding for the first siding cut and then all subsequent wood sidings will give that variant of moulding instead of their own.

Reproduction:
1. Set up a saw with a waterwheel or windmill
2. Chop some wood planks into sidings
3. Cut the sidings into mouldings
4. Change the wood variant and repeat steps 2 and 3 to receive the wrong variant of mouldings.

**Comment by kingmen30264** [comment]
We are showing the same error as well. We are playing on a server atm. I have not tried it in Singleplayer.

**Comment by sixlettervariables** [comment]
Why is this closed? This is an open and definitely not stale bug.

**Comment by artdude543** [comment]
The issue has been fixed in the mod. There was another issue used for tracking. The bot does what it wants lol.

**Comment by Gandorhar** [comment]
Bug stilm exists btw :)

**Comment by artdude543** [comment]
As said in my comment "another issue was used for tracking" it's fixed for the next update.
