### ISSUE TITLE
I dont know how to craft a stone pan

### ISSUE THREAD

**Issue by TaulantMerlaku** [DarkPacks/SevTech-Ages#2924]
well ive been stuck in this quest for a while and it requires a ender pearl for that i need ender dust wich i already got but i dont have a stone pan wich is needed to make a pan cast for the ender pearl and it doesnt show into jei how to get that or make it anyone help i've been stuck here for a while

**Comment by Tahakk** [comment]
Try to ask on [Discord](https://discordapp.com/invite/darkosto), Git is more for the bugs than support :)
