### ISSUE TITLE
Mob Grinding Utils mod won't ever drop certain drops

### ISSUE THREAD

**Issue by sharktemplar** [DarkPacks/SevTech-Ages#2926]
## Bug Report
The mob masher and iron spikes from the mob_grinding_utils mod will kill a mob and have it drop its experience (leading the player to assume it counts as a player-done kill) however, after having my huge mob farm (which still locks up minecraft constantly from the new 3.0.8 update) running for many many hours collectively, I can confirm that neither the iron spikes nor the mob masher will drop mob drops exclusive to player kills. This alone isn't that huge of an issue, but a rather more serious caveat is that Arcane Scrolls don't drop when killing a mob with iron spikes or a mob masher either. You would think this would mean Arcane Scrolls are player-kill-exclusive drops, however using reed spikes also results in obtaining scrolls, and reed spikes do not drop experience (to my knowledge) and thus are not considered player-done kills. 
Considering villager trades were overwritten to be progression-oriented trades, several arcane scrolls that used to be obtained through trading are now impossible to obtain in sevtech ages, meaning the ones that DO drop from mobs are that much more precious, and mob farms are essentially the only way to obtain multiple arcane scrolls in a practical manner. 

## Expected Behaviour
Mob Masher and Iron Spikes from Mob Grinding Utils mod should drop everything expected of it. 

## Possible Solution
Either change these blocks to kill differently so they drop what they should, or at least modify the description to disclose that using these blocks will NOT result in player-kill drops OR Arcane Scrolls, and that a player trap from dark utilities should be used instead to obtain player-kill drops and Arcane Scrolls specifically. 

## Steps to Reproduce (for bugs)

1. Create a mob farm where iron spikes or a mob masher from Mob Grinding Utils is what kills the spawned mobs. 
2. Idle as long as you want, and I promise you won't get ANY arcane scrolls.
3. To test player-kill drops, spawn spiders in and kill them with iron spikes or a mob masher. I guarantee you will not obtain ANY spider eyes, as those only drop when killed by a player. You WILL get experience, but you will NOT get Arcane Scrolls or spider eyes from them. 

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_172
* Launcher Used: Twitch App
* Memory Allocated: 10 Gigabytes
* Server/LAN/Single Player: Singleplayer
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in: 3.0.6

* Additional Content Installed: None

**Comment by vadis365** [comment]
Hello,
Iron spikes will drop XP but DO NOT count as player kills, they are their own Damage source.
The Mob Masher is a fake player though and should drop anything that a player drop would.
Not sure what is going on here. Will need testing.
Cheers,
Me.

**Comment by sharktemplar** [comment]
Well I can assure you the mob masher doesn't drop player-kill items from mobs. When swapping out my mob masher that I had been using for literally over a dozen hours of mob farm operation to a player trap from dark utilities, it was slower yes, but I began receiving creeper oysters within the first two minutes, which apparently are a player-kill drop from creepers I didn't even know of. I also immediately began collecting Arcane Scrolls within the first 10 minutes. Not sure if it's how SevTech implemented the mod or the mod itself, but mob mashers absolutely do not provide player-kill drops, though testing mob mashers with zombie pigmen DOES seem to cause them to agro to the player as though the player had attacked them, so it's some bizarre confusing behavior indeed at least for use of the mod in SevTech.

**Comment by inviktus** [comment]
Can confirm, mob masher not getting any drops at all. Have used with blitz and wither skeletons.. using enderio to spawn mobs.
I'm on v0.1.8.22 of mob grinding utils.
