### ISSUE TITLE
Sponge Server Crash with Extra Planets

### ISSUE THREAD

**Issue by RussianSanity** [DarkPacks/SevTech-Ages#2927]
## Bug Report
https://pastebin.com/PpeBTthA (sponge debug log)
https://pastebin.com/0XDXp8z0 (crashlog)
Whenever someone is loading chunks on the Extra Planets (this one in particular is Uranus) the console for the server continuously gets spammed with the following error you see in the pastebin link and if left unattended long enough the server eventually hangs up and crashes
It doesn't happen right away when the planet is loaded, it takes about 5 minutes or so before it begins.
This only began happening after the latest update (v3.0.8) to Sevtech.  We've tried both recent recommended builds to Sponge and even an experimental build (builds 3169, 3178, and 3206) in hope this would be fixed but it's a no-go so far on that end.

## Expected Behaviour
Explore the planets without it crashing the server for everyone. 

## Possible Solution
Contact MJRLegends for possible fix, if not Spongeforge? 

## Steps to Reproduce (for bugs)
1. Load the planet you desire
2. Begin exploring for about 5-10 minutes

## Logs

* Client/Server Log: https://pastebin.com/PpeBTthA (sponge debug log, other log is too large to view)
* Crash Log: https://pastebin.com/0XDXp8z0

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:
**This is a server issue, not client**

## World Information

* Modpack Version world created in: 3.0.7

* Additional Content Installed: Spongeforge, (plugin mods are: Tick Profiler, Better Chunkloader, Universeguard, Stackban, Prism, Nucleus, LuckPerms, GriefPrevention, and a custom plugin written by developers of our staff team)

## Server Information
* Java Version: 1.8.0_161, Oracle Corporation
* Operating System: Linux (amd64) version 4.9.33-mod-std-ipv6-64
* Hoster/Hosting Solution: OVH Canada
* Sponge (Non-Vanilla Forge) Server: spongeforge-1.12.2-2705-7.1.0-BETA-3206

**Comment by artdude543** [comment]
@bloodmc could you take this one a gander for me? To confirm if this is a Sponge issue of the mods fault.

**Comment by bloodmc** [comment]
@artdude543 SpongeForge's fault, have the user create a ticket here

https://github.com/SpongePowered/SpongeForge/issues

**Comment by artdude543** [comment]
Well, damn thanks for the quick response! @RussianSanity please create an issue using the link above and link back to here so we can track along the issue!

**Comment by RussianSanity** [comment]
Thank you for responding so quick. It's been reported [HERE](https://github.com/SpongePowered/SpongeForge/issues/2242)

**Comment by MJRLegends** [comment]
@artdude543 I believe this might have been fixed see comments on spongeforge issue report https://github.com/SpongePowered/SpongeForge/issues/2242
