### ISSUE TITLE
Game Crashes on preparation to launch

### ISSUE THREAD

**Issue by Ausmosis** [DarkPacks/SevTech-Ages#2933]
## Bug Report
 The launcher simply crashes following the launcher saying "preparing". I have not had this issue for the past two versions.

## Expected Behaviour
 The game to launch.

## Steps to Reproduce (for bugs)

1. Press Play on the Sevtech Ages profile on the Twitch app.
2. Select play Sevtech on the minecraft launcher

## Logs

* Client/Server Log: https://pastebin.com/zzXFnpaZ
* Crash Log: 

## Client Information

* Modpack Version: 3.0.8
* Java Version: 8.171
* Launcher Used: 2.0.1049 
* Memory Allocated: 12, 288 MB
* Server/LAN/Single Player:
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.6 or 3.0.7

* Additional Content Installed:

**Comment by Tahakk** [comment]
You can go to your Twitch launcher mod Profile, click on three dots near right up corner, and try **Repair Minecraft**, it just helped me today :)

**Comment by artdude543** [comment]
Yeah, your install is broken. Use the repair option and then if not re-install the modpack :)
