### ISSUE TITLE
Cant Craft Logic Processors and Engineers Processors

### ISSUE THREAD

**Issue by CherryPie** [DarkPacks/SevTech-Ages#2936]
## Bug Report
 Recipe for above items not showing up or being made with inscriber!--- If you're suggesting a change/improvement, tell us how it should work -->

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:1.12.2
* Operating System:linex
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
Because they are not used... You need to use the RS ones. If you found a recipe still using them. Please report that. Also, fill all the template in... next time your issue will be auto-closed and ignored.

**Comment by CherryPie** [comment]
thank you and sorry I'm new to this
