### ISSUE TITLE
Crash when traveling between Dimensions

### ISSUE THREAD

**Issue by AndrewR73** [DarkPacks/SevTech-Ages#2941]
## Bug Report
When I travel between dimensions (Nether, BetweenLands, The End, etc) the game takes far longer than it should to load the destination, and 9 out of 10 times I am met with an onscreen message "Lost connection to Internal Server" followed by this screen:
![image](https://user-images.githubusercontent.com/8558973/41699660-b245ace6-74d9-11e8-8517-69253c5862ce.png)
"Connection Lost
Internal Exception: java.nio.channels.ClosedChannelException"

However, when I look in my "...\Curse\Minecraft\Instances\SevTech Ages\crash-reports" folder, there is no crash report. The game does not completely crash, only the world, and I am kicked back to the Minecraft multiplayer servers screen. Clicking [Cancel] brings me back to the SevTech main menu where I can bring up the Single Player screen and go back into my game.

## Expected Behaviour
I should be able to go back and forth between dimensions without a crash.

## Steps to Reproduce (for bugs)
1. Go to a dimension portal
2. Walk through, sneak through, jump into ... portal type depending
3. Wait for destination dimension to load
4. Meet with Connection error

## Logs
* Crash Log: As stated previously, this crash does not result in a crash log or file. Would provide if it did.

## Client Information

* Modpack Version: 3.0.8
![image](https://user-images.githubusercontent.com/8558973/41700001-6353d156-74db-11e8-8eb8-d51c1dc3a05d.png)
* Java Version: 1.8.0_161
![image](https://user-images.githubusercontent.com/8558973/41699980-4caeaef8-74db-11e8-94fd-30b2246e34b9.png)
* Launcher Used: Twitch
* Memory Allocated: 10GB
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.6
* Additional Content Installed: n/a

**Comment by Tahakk** [comment]
You have no crash report because it is not a crash. In this cases you have to look into logs\latest.log

**Comment by IcedCoffeee** [comment]
This has been happening to me pretty often, it also sometimes deletes the space suite from your armor slots.

**Comment by artdude543** [comment]
This won't be fixed for a while until our next major update comes out which has no eta nor will it have for at least a good 2/3 weeks.

Relates #2388
