### ISSUE TITLE
Cavemen do not break ore samples immediately

### ISSUE THREAD

**Issue by keybounce** [DarkPacks/SevTech-Ages#2944]
## Bug Report

Some rocks break instantly; others do not. My friends tell me that I can't see the ore sample in the non-instants. I thought that disguised items were supposed to have the same break time as their disguise.

## Expected Behaviour

Since an ore sample is just a rock, it should break like a rock.

## Steps to Reproduce (for bugs)

1.  Be a caveman.
2.  Break an ore sample.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
This was already reported ages ago. This can't be fixed as of yet due to how the mod works and it's not easily fixable.
