### ISSUE TITLE
Move the "Flint pickaxe" to after the work stump.

### ISSUE THREAD

**Issue by keybounce** [DarkPacks/SevTech-Ages#2947]
## Context

After "on the chopping block", I see that more things open up as you advance in the tutorial advancements. However, the flint pickaxe trio shows up well before the work stump, even though it cannot be made until after the work stump.

This is confusing. The stuff that needs the work stump should be after the work stump. Otherwise I'm looking around trying to figure out how to make a crafting table, and accidentally stumbling upon the work stump before the tutorial is showing it to me.

**Comment by artdude543** [comment]
Won't be changed it's how the maker wanted it layed out.
