### ISSUE TITLE
JEI's recipe browser/move item button does not work on the work stump

### ISSUE THREAD

**Issue by keybounce** [DarkPacks/SevTech-Ages#2949]
## Bug Report

Attempting to use JEI's recipe browser/move item button on the work stump results in the chopping block being considered a missing item.

Oh, hey, I'm now in age 0.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
Intended.
