### ISSUE TITLE
Spear and tomahawk have a different style for damage and attack speed than every other weapon.

### ISSUE THREAD

**Issue by keybounce** [DarkPacks/SevTech-Ages#2950]
## Bug Report

Spear and tomahawk have a different style for damage and attack speed than every other weapon.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
As intended by the mod developer.
