### ISSUE TITLE
There does not seem to be any way to look at recipes or use JEI's "put items into a crafting grid" with a work stump

### ISSUE THREAD

**Issue by keybounce** [DarkPacks/SevTech-Ages#2953]
## Context

How do you take advantage of JEI's ability to put stuff in a crafting grid with the work stumps? I can manage the 2 by 2's in my personal grid, but can't even figure out how to bring up the recipes on the work stumps.

**Comment by Tahakk** [comment]
You just don't. That is the beauty of early game in this pack, you have to deserve it.
