### ISSUE TITLE
Chopping logs on a chopping block works badly.

### ISSUE THREAD

**Issue by keybounce** [DarkPacks/SevTech-Ages#2954]
## Context
Attempting to use a flint hatchet, a chopping block, and a wood log to make planks does not work well. Holding down break/attack results in breaking the chopping block and wood log. To actually make planks, you have to pulse (press release, press release, press release) break/attack.

What I would like to see: trying to break a log that is on the chopping block will break the log, not the chopping block. Especially when combined with a hopper, this makes it much easier to get planks.

Alternately, distinguish between aiming at the log versus aiming at the chopping block.

**Comment by artdude543** [comment]
You tap attack on the chopping block..... stop wasting our time with these issues use discord....
