### ISSUE TITLE
Recipe

### ISSUE THREAD

**Issue by FederiKFX** [DarkPacks/SevTech-Ages#2955]
Please remove this recipe

![image](https://user-images.githubusercontent.com/40461916/41716564-82d222c4-755f-11e8-9615-2476842e3721.png)

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
