### ISSUE TITLE
Advanced Primal Chest item duping

### ISSUE THREAD

**Issue by mmcmain** [DarkPacks/SevTech-Ages#2958]
Version 3.0.8 of the pack.

Ctrl-Left Click from an Advanced Primal Chest gives you 64 minus the number of items in the chest to your inventory. For example: 5 items in chest, Ctrl-Left Click gives 59 items. If you have a full stack it gives you 64.

I searched but couldn't find this reported previously.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
