### ISSUE TITLE
Texture (Chests, Animals, Ect.) Disappear when entering or leaving Dimension and on Relog of Server

### ISSUE THREAD

**Issue by Dragonhatch1** [DarkPacks/SevTech-Ages#2960]
## Bug Report

When i enter a dimension, alot of textures like animals, people, chests and such become invisible. I can still interact with them, but they are invisible on my screen. This also happens when i log off and back on the server. 

## Expected Behaviour

When i enter a dimension, alot of textures like animals, people, chests and such become invisible. I can still interact with them, but they are invisible on my screen. This also happens when i log off and back on the server. 

## Steps to Reproduce (for bugs)

1. Enter or Leave any dimension
2. Relog

## Logs

* Client/Server Log: https://gist.github.com/Dragonhatch1/bf8cc8d8d2bf1b27c1311b3e9203d3b6
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version:  Native Launcher (1.8.0.171 I believe?)
* Launcher Used: Twitch
* Memory Allocated: 6 Gb
* Server/LAN/Single Player: Server and Single-Player
* Optifine Installed: Yes. Have Replicated without Optifine.
* Shaders Enabled: No.

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None.

**Comment by Dragonhatch1** [comment]
I just made sure that my client was running on 1.8.0.171 and i am still encountering this.

**Comment by Stifling-Bossness** [comment]
Resolved via Discord, changing BetterFPS back to "Riven's Half" algorithm was the solution.

**Comment by Dragonhatch1** [comment]
Other way around. Changing it back to vanilla was the Solution.

**Comment by Dragonhatch1** [comment]
Is there a Way i can get this Issue reopened, due to the fact that it has started reoccuring again.

**Comment by Dragonhatch1** [comment]
Even with my BetterFPs set to Vanilla Algorithm Mode. Textures still Disappear.
