### ISSUE TITLE
Unable to craft logic Processors or Engineers Circuits

### ISSUE THREAD

**Issue by CherryPie** [DarkPacks/SevTech-Ages#2962]
## Bug Report
Nasa workbench Uses Logic Processors and Engineering circuit both of which cant be crafted

## Expected Behaviour
???

## Steps to Reproduce (for bugs)

1.???
2.???

## Logs

* Client/Server Log:
[ATLauncher-Log_2018-06-20_12-29-03.log](https://github.com/DarkPacks/SevTech-Ages/files/2125205/ATLauncher-Log_2018-06-20_12-29-03.log)

* Crash Log:

## Client Information

 4096 mb
* Modpack Version:3.0.8
* Java Version: 9
* Launcher Used: atlauncher 3.2.3.10
* Memory Allocated: 4096 mb
* Server/LAN/Single Player: single
* Optifine Installed:n
* Shaders Enabled:n

## World Information
 
* Modpack Version world created in: 3.0.6 estimate

* Additional Content Installed:

**Comment by timmit99** [comment]
The workbench uses the Processores which are made in the AE2 Inscriber:
![image](https://user-images.githubusercontent.com/8399317/41751368-eb55fcf6-758e-11e8-96f2-12548a57be33.png)
![image](https://user-images.githubusercontent.com/8399317/41751372-f2661d00-758e-11e8-8222-c6d12a9e977e.png)
![image](https://user-images.githubusercontent.com/8399317/41751375-f895d83c-758e-11e8-9d80-cf0d4b3faab3.png)

**Comment by CherryPie** [comment]
I'm not able to craft them

**Comment by CherryPie** [comment]
Like doing the recipes don't craft the logic processor or engineer circuit

**Comment by CherryPie** [comment]
And jei doesn't show them either

**Comment by timmit99** [comment]
Interesting, And you are on 3.0.8? what happens when you click it in JEI?

**Comment by CherryPie** [comment]
Its as if it don't got a recipe.

**Comment by CherryPie** [comment]
Any ideas?
