### ISSUE TITLE
About BetterFPS

### ISSUE THREAD

**Issue by idontlikethis** [DarkPacks/SevTech-Ages#2964]
Hi, guys.. I hate to make a false issue like this, but I don't know how else to contact you. And heck, maybe it IS a real issue, I don't know.

But mainly, this is just a question about BetterFPS. I've used it before in other Twitch modpacks and not had this problem, so I don't know about it. But what happens is I try changing to a different algorithm for better FPS and it tells me I need to restart my game. I've said no a few times because I don't know why I would need to, but one time I did say yes to restarting my game and it didn't even actually restart, it just closed.

IS this supposed to happen?

**Comment by timmit99** [comment]
Have you tried the Discord? That's where they want support questions like this to go.

**Comment by idontlikethis** [comment]
Um.. No, I have not. I didn't know they had a Discord.

**Comment by timmit99** [comment]
![image](https://user-images.githubusercontent.com/8399317/41751006-03f1fa46-758d-11e8-8055-08a1b8ca99b7.png)

Here it is on the main page.

**Comment by timmit99** [comment]
Head on over and they can help get your issues sorted out.

**Comment by idontlikethis** [comment]
Thank you, sire!
