### ISSUE TITLE
Making wood slabs only yields 3 instead of Vanilla's 6

### ISSUE THREAD

**Issue by evan-fisha** [DarkPacks/SevTech-Ages#2967]
## Context

In Vanilla, you get six wood slabs from the three blocks used in the recipe. In Sevtech, you only get 3. I don't know if this is intentional, but it's kind of illogical either way. I believe it is this way for all wood slab recipes. Anyway, I'd like the wood slab recipes to yield 6 slabs instead of 3 because conservation of matter is very important in this video game lol. It's probably an easy config change. Also, it'd be neat if a way to make slabs with the chopping block was added, but that's minor.

## Config/Script Details
* Link:

**Comment by artdude543** [comment]
Recipe is intended. Additional recipes may he added later down the line however. We have this noted internally for review.
