### ISSUE TITLE
Stellar Refraction Table book enchantments don't apply correctly

### ISSUE THREAD

**Issue by sharktemplar** [DarkPacks/SevTech-Ages#2968]
## Bug Report
The Stellar Refraction Table from Astral Sorcery is unique in that it allows players to obtain enchantments that actually go a few levels above vanilla enchantment max, such as Discidia providing sharpness and power 6, as well as Horologium providing Looting 5 and Fortune 6. When applying these enchantments to a book, then using said book to try and enchant an item, it automatically bumps that enchantment down to the maximum level allowed. 
Applying a pickaxe with Fortune 6 via an enchanted book obtained by the refraction table results in a pickaxe with fortune 3, not 6. 
These are rather difficult-to-obtain enchantments, especially horologium as that constellation is only visible 1 in every 36 nights because of a solar eclipse which doesn't show in SevTech skies properly as SevTech has omitted the Astral Sorcery sky aesthetic entirely, making it quite tedious to wait for Horologium to appear in the night's sky and thus acquire enchantments for looting and fortune which breach the maximum of 3 for each. 

If this was intended, it's an exceptionally stupid decision to have player's chasing a specific goal only to unfairly steal it from them after they've already invested all of the necessary time and effort. I very much doubt it was though, as having a Stellar Refraction Table enchant an item directly applies that enchantment correctly, i.e. enchanting a pick straight from the refraction table applies fortune 6 as it should, but storing it in a book is completely pointless as an anvil forces fortune back down to 3 when using that book. 

## Expected Behaviour
Items having the enchantments stated on an enchantment book actually applied to them in the same way they appeared on the book. 

## Possible Solution
If this is a design choice for whatever terrible reason, modify the description for a Refraction Table to mention that enchanted books have a hard level cap that is ONLY ENFORCED when applied to an item so that players don't get cheated out of high-end enchanted items.
If this is a bug, please resolve it so max-level-surpassing enchantments acquired by a Stellar Refraction Table have their effects and levels correctly applied items that the table's books are used to enchant. 

## Steps to Reproduce (for bugs)

1. Acquire an Engraved Glass with Horologium in it so that Fortune/Looting 4-6 is what it provides. 
2. Enchant a regular book through the Stellar Refraction Table so the book clearly reads Fortune/Looting 4-6
3. Use that book to try and enchant any item that accepts Fortune or Looting
4. Behold as you wasted your time, and the item refuses to go any higher than Fortune 3 or Looting 3, while still consuming your enchanted book. 

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_172 64bit
* Launcher Used: Twitch App
* Memory Allocated: 10G
* Server/LAN/Single Player: Singleplayer
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in: 3.0.6

* Additional Content Installed: None

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by masschoas** [comment]
This is because you're making a vanilla based enchanted book which still obeys vanilla enchanting rules for what can/cant be on an item.

**Comment by sharktemplar** [comment]
Well I know for a fact this doesn't happen as a result of astral sorcery the mod (or at least, didn't before) because I've seen others who used the stellar refraction table, made a book enchantment and applied it to an item and the enchantment was applied correctly even though it surpassed that enchantment level cap according to vanilla. 
There's something not working here and I'm unsure if it's astral sorcery or sevtech but it absolutely should not be the way it is.

**Comment by MuteTiefling** [comment]
Put your item in the stellar refractory table, not the book. What you might have seen are people applying books through other mod items. I believe the Dark Iron Anvil from EnderIO, for example, would allow you to apply these books without loss. Vanilla will always knock them down. You can try this in a pure vanilla world if you want. Just cheat in an Efficiency X book and try applying it to anything. It's going to be knocked down.

**Comment by sharktemplar** [comment]
Yeah... I already said in the post itself placing the item directly into the table applies the enchantment correctly. My point is the stellar refraction table should either provide unique enchantment books which don't get knocked down, or its own type of enchantment-book-applying feature to avoid this, or something. I am well aware of how the issue works, but it still should not work the way it does.

**Comment by monodemono** [comment]
Vanilla issue, can't be fixed.
