### ISSUE TITLE
New World

### ISSUE THREAD

**Issue by CreeperBlaster** [DarkPacks/SevTech-Ages#2969]
When I was succesfully installed the game and launched it, i created my first world but i didnt got out of the loading terrain suddenly my game crash when i try to create nor reload the world pls. help me

I am using ATLauncher Because i dont have a prem acc in mc
i maxed out the Maximum and Initial RAM to the highest 
and the version of the modpack im using is 3.0.8

**Comment by artdude543** [comment]
If you don't own a minecraft / mojang account your not going to get any help.... support the makers, buy buying an account.
