### ISSUE TITLE
Water Wheel Duplication?

### ISSUE THREAD

**Issue by IgnisFlamme** [DarkPacks/SevTech-Ages#2971]
## Bug Report
Water Wheel duplicates when placed on an axle and then broken.

## Expected Behaviour
When broken, should return an axle and a water wheel instead of two water wheels.

## Possible Solution
No clue, bad coding due to overlapping entities.

## Steps to Reproduce (for bugs)

1. Place gearbox
2. Place axle
3. Place water wheel on axle
4. Break the axle. (IMPORTANT!!)

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: latest
* Launcher Used: MultiMC
* Memory Allocated: 8gb
* Server/LAN/Single Player: Single Player
* Optifine Installed: No 
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.7

* Additional Content Installed: No

**Comment by Stifling-Bossness** [comment]
Reported as solved on [BWM's gitlab](https://gitlab.com/BetterWithMods/BetterWithMods/issues/1027) in dev, so hopefully fixed in 3.0.9

**Comment by IgnisFlamme** [comment]
I'll close it when 3.0.9 is released.

**Comment by artdude543** [comment]
This will be fixed in 3.1.0
