### ISSUE TITLE
Astral sorcery constellation paper. Duplicate discidia papers (3). The only other paper i got is evorsio. 

### ISSUE THREAD

**Issue by tveedie** [DarkPacks/SevTech-Ages#2972]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by timmit99** [comment]
Please fill out the Template... Its there for a reason...
