### ISSUE TITLE
Well Of Suffering continues to damage mobs and drain LP even though altar is full

### ISSUE THREAD

**Issue by Shovinus** [DarkPacks/SevTech-Ages#2975]
## Bug Report
I have a well of suffering with about 100 chickens that are being kept alive by an astral ritual - the regen one. It easily keeps the chickens alive as an Good accelerated crystal. However once the altar is full and doing nothing it carries on draining LP from soul network and damaging the chickens.
## Expected Behaviour
If the altar is full it is not meant to drain LP or attack the chickens (At least according to previous documentation. I can find)

## Steps to Reproduce (for bugs)
Create Blood altar (I have level 4 but does not seem to matter the level) 
setup Well of suffering ritual and astral ritual pedastal with high level aevitas and accelerated crystal, link to your well of suffering area using anchor if needed. Add about 100 chicken (though I doubt that matters)
Activate the suffering ritual
Watch as chickens get hurt despite well being full, also LP still drains.

**Comment by monodemono** [comment]
Current documentation does not reflect what you have stated. It will not drain any LP or damage any mobs if there's no altar in range, as stated in the Sanguine Scientiem. If you wish for this behavior to change, take it up with the mod devs, as this is not a pack issue.

**Comment by Shovinus** [comment]
Yeh it aint the Mod pack fault I guess, it is BM, it is just BM stated if altar full it stops but didn't so assumed you set something in the pack

**Comment by monodemono** [comment]
> it is just BM stated if altar full it stops

No it does not.

**Comment by Shovinus** [comment]
I checked twice mate in the in-game documentation but I will check again later

On 24 Jul 2018 05:05, monodemono <notifications@github.com> wrote:

it is just BM stated if altar full it stops

No it does not.

**Comment by monodemono** [comment]
This is the last response you will get on this matter.

<img width="1920" alt="screen shot 2018-07-23 at 22 46 22" src="https://user-images.githubusercontent.com/1161277/43119215-57bba1d0-8eca-11e8-87e6-62ec93fa2bdb.png">
<img width="1920" alt="screen shot 2018-07-23 at 22 46 24" src="https://user-images.githubusercontent.com/1161277/43119216-57d78e72-8eca-11e8-9502-d83fc56598c5.png">

> For those of you who prefer to use mobs instead of your own health, the Well of Suffering damages all living non-player entities in a 10 block radius and places the health in a connected altar. The ritual will look for a blood altar within its range, checking 5 blocks horizontally and 10 blocks vertically unaltered. When it finds an altar, it will store its location internally - if there isn't an altar nearby, the ritual will not work. The ritual will deal 1 HP per entity and place 25 LP into the altar (100 for peaceful animals), which can be augmented with sacrifice runes.

"**if there isn't an altar nearby, the ritual will not work.**"

This is all it says on this matter. There is nothing about it stopping when full.

This matter is closed.
