### ISSUE TITLE
Missing textures bug?

### ISSUE THREAD

**Issue by otter98** [DarkPacks/SevTech-Ages#2976]
Hello everyone,
After The recent update to the modpack was added, my textures have been vanishing, I cannot see the mobs, only their swords and the animals are vanishing, as well as chests. 

This happened before I updated, whilst using a texture pack and without it. It also still happens after I've updated my version of sevtech - with and without the texture pack.

I disabled a couple of the mods which are non essential - better foliage and one of the text mods. Any help would be appreciated, thank you.

![minecraft horse bug](https://user-images.githubusercontent.com/40505086/41801741-3513606e-7674-11e8-88ba-2e58a493eff2.png)

**Comment by Stifling-Bossness** [comment]
Please use the template, as it provides some of the info that's used to speed the process along. Also, did you make sure to restart your client completely after switching resource packs?

**Comment by otter98** [comment]
Yes I did restart my client
