### ISSUE TITLE
models missing/invissible 

### ISSUE THREAD

**Issue by Mythage** [DarkPacks/SevTech-Ages#2978]
## Bug Report
big problem over here. some models are bicomiing invissible. like chest, villigars, players and all the animails. some one knows how to fix this 
![2018-06-23_14 49 51](https://user-images.githubusercontent.com/22367065/41810281-56f4755a-76fc-11e8-877e-260b25fc7830.png)

## Logs

* Client/Server Log:
* Crash Log:
[2018-06-23-2.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2130015/2018-06-23-2.log.gz)

## Client Information
the settings -->
* Modpack Version: 3.0.8
* Java Version: 1.8
* Launcher Used: Twich
* Memory Allocated: 10g
* Server/LAN/Single Player: LAN and Single player
* Optifine Installed: no clue
* Shaders Enabled: no clue

## World Information

* Modpack Version world created in: 3.0.8

**Comment by timmit99** [comment]
Please fill out the issue template (which you DELETED) it gives the dev's information about the modpack version, your java version and other things that can help them solve issues.

**Comment by Mythage** [comment]
hope this is beter for you
