### ISSUE TITLE
Copper and bronze tools bad recipies

### ISSUE THREAD

**Issue by Genotypek** [DarkPacks/SevTech-Ages#2979]
## Bug Report
1. Copper tools have no recepies, so they're impossible to craft,
2. Every bronze tool is craftable by copper.

## Expected Behaviour
When using copper, there should be crafted copper tools,
When using bronze, there sould be crafter bronze tools,

## Possible Solution
Repair recepies.

## Steps to Reproduce (for bugs)
At very first, just open NEI.
Or try to craft them.

## Client Information
* Modpack Version: 3.0.8

**Comment by Stifling-Bossness** [comment]
Duplicate of #2802
