### ISSUE TITLE
Change the start of Age 5 to getting moonstone

### ISSUE THREAD

**Issue by QuietHelper** [DarkPacks/SevTech-Ages#2996]
The current setup makes people die if they are playing on a server.

The slowness caused by getting to age 5 makes it where you crash on the moon right as you see Welcome to Age 5.  I think this will only happen on servers as the sync between client and server does not stop your decent but on the client the only version it would.

**Comment by artdude543** [comment]
This won't be changed or fixed until our next major re-write of scripts and updates to the mods which control the staging.
