### ISSUE TITLE
[Age 1] Breaking a water wheel with a Black Quartz AIOT duplicates the water wheel.

### ISSUE THREAD

**Issue by Rothuith** [DarkPacks/SevTech-Ages#2997]
## Bug Report

Breaking a water wheel with a Black Quartz AIOT duplicates the water wheel.

## Expected Behaviour

Should break the block normally and drop one water wheel.

## Steps to Reproduce (for bugs)

1. Place down water wheel with an axle and wooden gearbox.
2. Break with Black Quartz AIOT.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: Latest SevTech
* Java Version:
* Launcher Used: Twitch
* Memory Allocated:
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: Latest

* Additional Content Installed: No

## Server Information
* Java Version: 9
* Operating System: Ubuntu 16.04
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by Serolar** [comment]
This is a duplicate issue. See #2971 
Definitely not specific.

**Comment by Rothuith** [comment]
Just noticed this was a duplicate issue. Sorry.
