### ISSUE TITLE
Second players items/advancements

### ISSUE THREAD

**Issue by TheChanMan117** [DarkPacks/SevTech-Ages#2999]
## Bug Report

When a second player disconnects after playing and reconnects later their items/advancements haven't been saved. The third time they logged in the second player's inventory/achievements wer full of the items/advancements from the first time they disconnected.

## Expected Behaviour

Items/advancements are not saved.

## Steps to Reproduce (for bugs)

1. Log a second player in on a LAN network.
2. Pick up an item/make an advancement
3. Disconnect
4. Reconnect and observe inventory/advancements

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used: 1.12.2
* Memory Allocated: 8192MB
* Server/LAN/Single Player: LAN
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None
[2018-06-25-3.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2139159/2018-06-25-3.log.gz)

**Comment by artdude543** [comment]
Sadly LAN worlds are not supported on this tracker due to the vast amount of issues it causes. The only command you can use to help is:

`/tf forcesync`

But apart from that or moving to a dedicated server we can't help you here. But I'll get the bot to point you where some help can be given.
