### ISSUE TITLE
 World making sevtech server stop when starting up 

### ISSUE THREAD

**Issue by soulfoood** [DarkPacks/SevTech-Ages#3000]
## Bug Report

Me and my friend were playing sevtech and we got decently far when i started up the server the next day and it stopped at the line at the bottom of the log here: https://paste.feed-the-beast.com/view/de279a99 it didnt do this the day before, so i decided to do some troubleshooting. I figured out that the world was an issue. The way i figured this out was when i took the world file out of the server folder and restarted the server, it went up fine. Here is the world file: https://drive.google.com/drive/folders/1z8rBU5d0O9mDBzmHT0fDjsBkhdxMYP2A?usp=sharing

## Expected Behaviour

Obviously it is not working the way it should because the server should start up fine like it did the first day.
## Possible Solution

Something with the world file is corrupted or something, possibly the level.dat/level.dat_old?

## Steps to Reproduce (for bugs)

1. create a server and replace the world file with the linked one above (google drive link)
2. start up the server

## Logs

* Client/Server Log:  https://paste.feed-the-beast.com/view/de279a99
* Crash Log: no crash logs were in the crash log folder

## Client Information

* Modpack Version: 1.12.2
* Java Version: 64x
* Launcher Used: AT Launcher
* Memory Allocated: 6gb
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 1.12.2

* Additional Content Installed: none

## Server Information
* Java Version: 64x
* Operating System: win 10 64x
* Hoster/Hosting Solution: I created the server and is hosted on my network. PS: i've tried to restart my network and my computer. Neither have had any success.
* Sponge (Non-Vanilla Forge) Server: The server was installed from AT's site

**Comment by artdude543** [comment]
You have broken scripts/configs re-install all of them and you should be fine. I've booted your world on a fresh instance fine.

Also please use https://minecraft.curseforge.com/projects/sevtech-ages/files/2570735 over the ATLauncher ones we don't give support when their files are used. But I can't reproduce your bug/issue.
