### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by StarZxz** [DarkPacks/SevTech-Ages#3003]
# Bug Report
I can enter the game can also enter the map, but when I was running in the plains or synthetic items when suddenly stuck at home, after the game is flash back, sometimes I can play for 1 hour, smooth 60 FPS caton flash back less than 1 minutes, sometimes I don't know is what reason, without warning, and there is no rule that one time I used a spear fishing, just throwing spear out of the game is stuck, I heard the spear into the sound in the water, the game screen does not move, the next seconds left,Sometimes when I click on the "control" or "language" button, there's a caton flash back,I wonder if a flash memory leak caused the JAVA games flash back, but wikipedia says running within the JAVA 6 gb Yes, I don't know how to do it. What a good modpack it is. I wanted to play with my friends, but I met this problem. What should I do? thank you!
# Expected Behaviour
I don't know what happened. I may have a chance of flashback no matter what I do. Once I walked in my home and I flashed back. There was no law, no sign.
# Possible Solution
I don't know, I think it's probably a problem with an operation in the background that suddenly my Java memory exceeds its maximum memory
# Steps to Reproduce (for bugs)
Walk home;
Click the "language" and "control" buttons;
Used a spear fishing;
Craft or place or break a block;
Run to darkland, 1680M away;
There is no correlation and no sign or pattern;
# Logs
latest.log:[https://paste.feed-the-beast.com/view/214d2315];
betterfoliage.log:[https://paste.feed-the-beast.com/view/0feb0c4d]
# Client Information
Minecraft version:1.12.2;
Modpacks version:3.0.8;
Forge version:14.23.4.2707;
Resourcepacks:default
Java Version: 64x;
Launcher Used: HMCL 3.1.59;
Memory Allocated: 6144MB;
Server/LAN/Single Player: Single Player;
Optifine Installed: no;
Shaders Enabled: no;
No mod delete or add
# Computer Information
CPU:AMD Athlon X4 760K Quad Core quad-core 3.8GHZ;
GPU:Nvidia GeForce GTX 750 Ti;
SSD:SDSSDA120G;
Memory chips:Apacer DDR3 1600MHz 4GB + Apacer DDR3 1600MHz 8GB;
Mainboard:ASUS A58M-E
# World Information
Modpack Version world created in: 1.12.2;
Additional Content Installed: none
# other
I am a Chinese, I am not good at English, so I use the Chinese computer translation software to translate my words into English, if the words are not appropriate or difficult to understand I am very sorry!

**Comment by artdude543** [comment]
So first there is no crash at all. Nothing in the logs indicate this. Java version is fine _(64x)_ is also wrong FYI we want the version, not your architecture.

All I can suggest is to try with custom args found here: http://bit.ly/DarkostoJavaArgs and see if that helps. But there is not crash nor any _error_ thrown in the logs which are going to cause an issue.
