### ISSUE TITLE
World is corrupted after updating server

### ISSUE THREAD

**Issue by anony55** [DarkPacks/SevTech-Ages#3004]
## Bug Report

When updating the server from 3.0.6 -> 3.0.7 or from 3.0.6 -> 3.0.8, Forge first prompts to confirm the removal of blocks and suggests that the world may have become corrupted. After answering the prompt with, "/fml confirm" and joining the server, the server will crash and upon reboot the world will be corrupt with mismatched blocks everywhere (random doors from Primal, etc.)

## Expected Behaviour

When previously updated, the world would be intact and playable but from versions 3.0.6 -> 3.0.7 the world becomes corrupt.

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1. Run a SevTech 3.0.6 server
2. Attempt an upgrade to SevTech 3.0.7 following the steps in 'UPDATE.txt'
3. Launch 3.0.7 server (updated from 3.0.6)
4. Answer all Forge prompts with, "/fml confirm"
5. Join server (server crashes)
6. Restart server
7. Join server
8. Corrupted world upon joining

## Logs

* Server Log: (Gist) Full File -https://gist.githubusercontent.com/anony55/50a6dd47a24dfd58236d37a3468a4bd6/raw/2681aa6b7dc6e74b2dbc559dfb07420042db78ed/Latest.txt
Truncated Version -
https://gist.github.com/anony55/50a6dd47a24dfd58236d37a3468a4bd6

## Client Information

* Modpack Version: 3.0.6, 3.0.7, 3.0.8
* Java Version: Version 8 Update 171 (Build 1.8.0_171-b11)
* Launcher Used: Twitch
* Memory Allocated: 10 Gigabytes (Server), 5 Gigabytes (Client)
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.5

* Additional Content Installed: BetterRecords, Cosmetic Armour Reloaded, MalisisDoors, MalisisCore
ALL ADDITIONAL CONTENT WAS UNINSTALLED IN 3.0.6 BEFORE ATTEMPTED UPDATE!

## Server Information
* Java Version: Version 8 Update 171 (Same as client, different PC)
* Operating System: Windows 10 Pro
* Hoster/Hosting Solution: Hoster
* Sponge (Non-Vanilla Forge) Server: N/A (Vanilla)

## Corruption Screenshots (Additional)
* Overworld:
(Immersive Engineering Structures) https://i.imgur.com/uwnivM1.jpg
(Ex. Storage Room) https://i.imgur.com/lIfpn42.png
https://i.imgur.com/b4fIytj.jpg
* Twilight Forest:
(Naga Maze) https://i.imgur.com/Cxu0jMX.jpg

**Comment by Stifling-Bossness** [comment]
Adding MalisisDoors likely put your world at the block ID limit, and combining that with the additions from 3.0.7, the block ID limit was most likely exceeded. All of your blocks being shifted to being another seems to support this. Note that removing the mods will _not_ help, as the blocks will still be saved as IDs in your world. Your best option right now is to roll back to a save from before you added the mods, or you're going to be stuck with 3.0.6 for the duration of your world.

**Comment by anony55** [comment]
@Stifling-Bossness Alright, that clears this up. Thank you for the quick reply!

**Comment by artdude543** [comment]
Closing as it's been answered above. But yes we don't recommend installing additional mods. For various reasons this being the main one.
