### ISSUE TITLE
v3.0.8 Totemic: Rite of Spring

### ISSUE THREAD

**Issue by N0lRShadow** [DarkPacks/SevTech-Ages#3006]
## Bug Report
Trying to perform Rite of Spring for Red Cedar Saplings. 

## Expected Behaviour
Particle effect appears to show ceremony was completed, but HUD for the song/timer meter reset and icons are gone

## Steps to Reproduce (for bugs)
1. Create totem base
2. Set up drum
3. Place some saplings
4. Start ceremony with Shift-R/C Flute then with empty have Shift+R/C drum
5. With rattle in hand, target drum and hold right click

## Client Information

* Modpack Version: v3.0.8
* Java Version: 8 Update 171 (build 1.8.0_171-b11)
* Launcher Used: Jar Launcher
* Memory Allocated: 6-8GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: Yes

I have tried using different instrument combination to just drum and both flutes. Different sapling placement as well. Restarted both client and server.

Image of HUD after ceremony completes:

https://gyazo.com/6c1baa8a82db0fbb0197e74ba3c1e058

**Comment by misterplus** [comment]
I'm pretty sure you need a vanilla sapling for this to work.

**Comment by artdude543** [comment]
Needs to be a Vanilla Sapling as far as I'm aware.
