### ISSUE TITLE
Spawner Seeker - server crash

### ISSUE THREAD

**Issue by Joriom** [DarkPacks/SevTech-Ages#3007]
## Bug Report
Using Spawner Seeker from Cyclic Mod causes ConcurrentModificationException and forces server shutdown - only in certain locations.

## Details
After using spawner Seeker client hears Spawner Seeker sound but gets disconnected with server shutdown message.
After server reload the "orb" spawned by Spawner Seeker stays in the place it appeared and does not seem to decay nor move. It is still visible to clients though.

Logging in after clean server startup in "safe" (where Spawner Seeker does not cause crash) location allows use of Spawner Seeker without problems. Moving back to "bugged" locations causes every usage of Spawner Seeker to crash the server.

Logging in after clean server startap in "bugged" location and moving outside of loaded chunk radius away from "bugged" location still causes server to crash on Spawner Seeker usage.

In my case "bugged" location seems to be at least 11x11 chunk area around my house. Not sure if it does happen in different locations. It includes, but is not limited to:
* all the items/structurest needed for stage 3 up to oil processing;
* extensive power lines (insulated LV wires from Immersive Engineering)
* IE windmills, water wheels
* Few chiseled blocks
* IE Metal Press
* Blaze spawner, 2 skeleton spawners and zombie spawner (brought from Nether and Twilight Forest using "shift + rightclick with empty hand" mechanic for block movement) [Spawner Seeker worked fine with Blaze spawner in overworld, not sure about the rest]
(if required, world available for download on demand)

(Untill its fixed, I would be glad if anyone could suggest solution to getting rid of the floating orb itself? I don't have backup of the world and the orb at my house entrance is unsightly.)

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
Unsure - cause of location becoming bugged is not obvious.

## Logs
Server logs available directly:
[crash-...-server.txt](http://dev.joriom.pl/sevtechlog20180628/crash-2018-06-28_15.42.26-server.txt) (52 KB)
[debug.log](http://dev.joriom.pl/sevtechlog20180628/debug.log) (17 766 KB)
[latest.log](http://dev.joriom.pl/sevtechlog20180628/latest.log) (1 380 KB)
[debug-1.log (Last 10 hours)](http://dev.joriom.pl/sevtechlog20180628/debug-1.log) (97 515 KB)
[2018-06-28-1.log (Last 10 hours)](http://dev.joriom.pl/sevtechlog20180628/2018-06-28-1.log) (89 KB)

## Client Information
* Modpack Version: 3.0.8
* Java Version: 1.8.0_171, Oracle Corporation
* Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
* Memory Allocated: 851505816 bytes (812 MB) / 2919235584 bytes (2784 MB) up to 3019898880 bytes (2880 MB)
* JVM Flags: 8 total; -Xms1024M -Xmx2860M -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
* Server (running in offline mode)

## World Information
* Modpack Version world created in: 3.0.7
* Content Removed: Aroma Backup

Sadly, due to server start time being around 15 minutes I can't experiment freeling to narrow down possible causes. Can test some things up on request though.

**Comment by bobbnu** [comment]
I noticed this everywhere on Saturn after a few hours there on a private world

**Comment by NWBeez** [comment]
I have this problem everytime I try to use the spawn seeker.

**Comment by NightcoreIsla** [comment]
my server have this problem too
try keep out it but that will become hard for search galactic dungeon
need fix please QwQ
