### ISSUE TITLE
Add Creative ME Storage Cell (AE) recipe using the Ultimate Singularity

### ISSUE THREAD

**Issue by Stifling-Bossness** [DarkPacks/SevTech-Ages#3008]
## Context
The Creative Cell allows unlimited items to be withdrawn (when configured in a cell workbench), which obviously seems overpowered. However, the Ultimate Singularity requires so much of so many different materials, that I feel it's a perfect fit to be used in the recipe of the Cell, because at that point you've got to have nearly infinite materials anyways.

**Comment by Vercci** [comment]
If it uses every other creative item possible to craft sure.
