### ISSUE TITLE
Server mods don't work properly

### ISSUE THREAD

**Issue by Sinigon** [DarkPacks/SevTech-Ages#3009]
I've created a world in a singleplayer mode and it's ok, all works properly. But with the server this doesn't work: items doesn't drop (drops but still you have it in your inventory but it is invisible), no small rocks or stick drops from leafes and etc even if I copy singleplayer created world to the server. And advencements doesn't work too on the server.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
