### ISSUE TITLE
baubles staying on death/deleting when getting resurrected by astral sorcery Phoenix fire

### ISSUE THREAD

**Issue by iamgeorgeclooney** [DarkPacks/SevTech-Ages#3011]
## Bug Report
 whenever anyone on the sever dies they keep all baubles equipped when they should be dropped on death?

being attuned to armara and having phoenix fire resurrect you deletes all baubles equipped in baubles slot

## Expected Behaviour
 baubles shouldn't dissapear and should drop on death if that is the intended behaviour

## Steps to Reproduce (for bugs)

1. be attuned to armara from astral sorcery,
2.take damage to get the phoenix fire buff,
3, take what would be lethal damage and get resurrected 
4, all baubles have dissapeared/been deleted

## Logs

* Client/Server Log: https://gist.github.com/iamgeorgeclooney/ee1d326871545b2f5624a4ea242fc00c
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: 
* Launcher Used: twitch
* Memory Allocated: 8gb
* Server/LAN/Single Player: server
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution: apex hosting
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
Related and dupe to #2429

**Comment by AndrwTherJager** [comment]
This is not related to #2429. It is very easy to reproduce when a player is attuned to armara and takes lethal damage their baubles disappear. It just happened to me a few minutes ago

**Comment by iamgeorgeclooney** [comment]
@artdude543 take it as you didn't actually read, has nothing to do with grave not spawning, as stated above it is extremely easy to reproduce and you dont have to actually "die" to reproduce as i stated but thanks for your input :)

**Comment by artdude543** [comment]
It's related due the fact the grave mod "hacks" into events which AS uses on _fake_ "death" which breaks the effect. I won't tag an issue for no apparent reason...

**Comment by Yamza** [comment]
Had this effect me last night as well. Was using a bauble bag to store all of my tools, walked into an HV cable, the Phoenix effect was activated and deleted all my baubles.

**Comment by The-Key** [comment]
This specific interaction isn't the fault of tomb many graves. The current release of Twilight Forest has a bug that causes baubles to be kept after death, and this has had buggy interactions with several mods that modify death. The bug has been fixed in dev builds of Twilight Forest though. 
https://github.com/TeamTwilight/twilightforest/issues/542
https://github.com/TeamTwilight/twilightforest/issues/574

**Comment by Phantum** [comment]
Is there anyway to recover the deleted baubles?  OTHER than a backup?  (my last backup was 6 hours ago) 

:(

**Comment by Ncrpts** [comment]
I confirm this happend to a player on my server twice.
