### ISSUE TITLE
Hellfire in Stoke Cauldron warning disappeared

### ISSUE THREAD

**Issue by monodemono** [DarkPacks/SevTech-Ages#3012]
## Bug Report
In 3.0.6 if you checked what recipes Hellfire Dust could be used in, you could see a warning that it was "HIGHLY VOLATILE" in a stoked cauldron or crucible, but as of 3.0.7 (and still in 3.0.8) this warning is gone.
3.0.6
<img width="1920" alt="screen shot 2018-06-28 at 23 18 18" src="https://user-images.githubusercontent.com/1161277/42077090-8e5d4aba-7b2c-11e8-886b-0df3f2c9fe9e.png">
3.0.6
<img width="1920" alt="screen shot 2018-06-28 at 23 18 20" src="https://user-images.githubusercontent.com/1161277/42077091-8e84ca36-7b2c-11e8-8e19-41beafad0e1d.png">
3.0.7
<img width="1920" alt="screen shot 2018-06-28 at 23 37 11" src="https://user-images.githubusercontent.com/1161277/42077092-8e9ee754-7b2c-11e8-9efc-eff9d9a67f1c.png">

## Expected Behaviour
Expected the warning recipe to still be there when checking Hellfire Dust's usages.

## Possible Solution
Check with the mod author to see if they accidentally broke this, or add a fake "HIGHLY VOLATILE" invisible item to fake the recipe using a script.

## Steps to Reproduce (for bugs)
1. Make a 3.0.6 instance.
2. Run it, and check the Hellfire Dust recipe usages by right clicking it in JEI, or hovering over it and pressing U.
3. Note that in the Stoked Cauldron and Stoked Crucible tabs, there is a warning that it is "HIGHLY VOLATILE"
4. Make a 3.0.7 or 3.0.8 instance.
5. Check Hellfire Dust recipe usage (as explained above).
6. Note that there is no warning anymore.

## Client Information
* Modpack Version: 3.0.6 and 3.0.7 and 3.0.8
* Java Version: 1.8.0_171 (64 bit)
* Launcher Used: Twitch
* Memory Allocated: 8,192 MB

**Comment by artdude543** [comment]
Eh, not really an issue for the modpack. Feel free to make an issue for the mod itself.

**Comment by monodemono** [comment]
Just an update in case anyone comes across this at a later date. I've been informed this removal was intended.
