### ISSUE TITLE
Sevtech Crashing after launching out of Native Launcher

### ISSUE THREAD

**Issue by MontanaBlock** [DarkPacks/SevTech-Ages#3015]
## Bug Report

Sevtech crashing after starting it in Native launcher out of twitch desktop app. Gets about 1/3 of the way loading and crashes with the following report. Have not been able to find this problem online yet.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Crash Log: https://pastebin.com/ehzvE3tb

## Client Information

* Modpack Version: 3.0.8
* Java Version: Version 8 Update 171  (build 1.8.0_171-bit
* Launcher Used: Native launcher
* Memory Allocated:  5,888 MB
* Server/LAN/Single Player: Single
* Optifine Installed:  NO
* Shaders Enabled:  NO

**Comment by artdude543** [comment]
Reinstall the pack. Your missing mods. Also if you are using a folder share like Drive or Dropbox this will also cause the issue with mods vanishing.
