### ISSUE TITLE
Server crash on load. Not sure what is going on.

### ISSUE THREAD

**Issue by TheBlueFabbit** [DarkPacks/SevTech-Ages#3018]
[crash-2018-06-30_00.10.57-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/2151449/crash-2018-06-30_00.10.57-server.txt)

Here is the crash log, not sure 100% what is causing it, everything was working fine, then my friend and I logged off the server. Upon trying to load up again, server started crashing on boot.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
