### ISSUE TITLE
Crash when using builder wands when interacting near Car Mod blocks

### ISSUE THREAD

**Issue by jasonn1124** [DarkPacks/SevTech-Ages#3019]
## Bug Report
I was using a Platinum wand to horizontally extend chiseled andesite (big tile) as flooring. On the same Y-level beside it was a Car Mod fluid pipe for piping glycerol into a Cyclic trash void (Also same Y-level, but not directly beside). On the Y-level directly above that was a splitting tank from Car Mod.

As I recall, after using the platinum wand to extend 1 block's worth of chiseled andesite, Minecraft froze and crashed. I relaunched using the twitch launcher and tried to login, but crashed again. This happened 2 more times after that, following which I gave up.

## Expected Behaviour
Minecraft not crashing.

## Possible Solution
I'm not a programmer, nor even really a coder. But looking at the log, and trying to recall what I did, I think it might have something to do with me holding the platinum wand and mousing over things from Car mod.

## Steps to Reproduce (for bugs)
Not confirmed but pretty sure.
Hold a platinum wand.
Mouse over a car mod fluid pipe.

## Logs
* Crash Log: https://pastebin.com/aLf4frJq

## Client Information

* Modpack Version: 3.0.8
* Java Version: Latest
* Launcher Used: Twitch launcher
* Memory Allocated: 10.9gb
* Server/LAN/Single Player: Multiplayer server (4 players online, no one else nearby)
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.6

* Additional Content Installed:  NONE

**Comment by artdude543** [comment]
Yes, advice would be to not use the chisel with the car mod items. This would also need reporting on their tracker. If you could help out and pretty much either paste this issue or link back to it.

Thanks!
