### ISSUE TITLE
Twilight Forest Animals Spawning in Compact Machines

### ISSUE THREAD

**Issue by RussianSanity** [DarkPacks/SevTech-Ages#3020]
## Bug Report
Twilight Forest Animals spawn in Compact Machines if in the proper Twilight Forest biome (on a server)
https://i.imgur.com/Zb5lgVC.png 
Unsure if this happens in singleplayer since its hard to find a specific biome without cheaty commands like /thru or /top. When I tried in Singleplayer I got a different biome and it didn't spawn anything.

## Expected Behaviour
No animals are supposed to be spawning in this dimension at all lol

## Possible Solution
Remove biomes from the Compact Machines dimension and it should work as intended?

## Steps to Reproduce (for bugs)

1: Step into a Compact Machine that's within a Twilight Forest biome
2: Put a chunkloader down (whether from the modpack or custom plugin)
3: Exit Compact Machine and wait for animal spawns

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

Client Information
Modpack Version: 3.0.8
Java Version: Java 8 update 171 (64-Bit)
Launcher Used: Twitch
Memory Allocated: 8GB
Server/LAN/Single Player: Single Player
Optifine Installed: No
Shaders Enabled: No

World Information
Modpack Version world created in: 3.0.7
Additional Content Installed: Spongeforge, (plugin mods are: Tick Profiler, Better Chunkloader, Universeguard, Stackban, Prism, Nucleus, LuckPerms, GriefPrevention, and a custom plugin written by developers of our staff team)

Server Information
Java Version: 1.8.0_161, Oracle Corporation
Operating System: Linux (amd64) version 4.9.33-mod-std-ipv6-64
Hoster/Hosting Solution: OVH Canada
Sponge (Non-Vanilla Forge) Server: spongeforge-1.12.2-2705-7.1.0-BETA-3243

**Comment by artdude543** [comment]
This is something we can't fix as it's mod side related. Not really a bug tbh it does happen with other biomes other mods add.

But feel free to make an issue with the mod dev about this. But I'm not deeming this a bug for the pack as it's not breaking or anything.
