### ISSUE TITLE
suggestions page

### ISSUE THREAD

**Issue by AireagoirSteam** [DarkPacks/SevTech-Ages#3022]
Hello was wondering if the creation of a mod suggestions page might be possible.
although featuring say a list of, mod comparability, how he mod fits in with the tech or survival aspect of the pack, what items could be turned on or off.

although I am not sure if such a page would create more problems
although two main suggestions for this pack that I would say would be Immersive railroading
this uses most components from immersive engineering and would fit in with the factory industrial age, can be use for fluid or item transport and has steam and electrical trains.

and the second would be impractical storage which could be another storage option since in regards with mining or tree farming or even building materials it makes a nice realistic way of storing things and would fit well I feel with the practical survival feel of the pack.

anyway thank you for creating this pack I'm very much enjoying playing t.

**Comment by artdude543** [comment]
https://github.com/DarkPacks/SevTech-Ages/issues/new?template=FEATURE_REQUEST.md
