### ISSUE TITLE
Ultimate Car Mod: Use different fuel(s)

### ISSUE THREAD

**Issue by MelficeSilesius** [DarkPacks/SevTech-Ages#3024]
Right now, the Ultimate Car Mod uses its own fuel, Bio Diesel. The mod also provides its own infrastructure to make this fuel.
However, the progression already has the player set up Immersive Engineering/Petroleum infrastructure which has us creating Diesel and, with a second distillation, Gasoline and Kerosene. Immersive Engineering also has a Biodiesel.

My suggestion is to change the fuels used from the mod's own Bio Diesel, to using Gasoline, Diesel, and Biodiesel.
Not because it makes things easier, but because it removes some tedium in setting up yet another set of machinery that already exists in another mod. It would also free up some IDs, presumably.

Find below an example of the changes I personally made in my configs.

car.json
`{"cars": [
 {
  "acceleration": 0.032,
  "reverseSpeed": 0.2,
  "id": "car_wood",
  "speed": 0.5,
  "fluids": [{
   "efficiency": 0.3,
   "fluid": "gasoline"
  }]
 },
 {
  "acceleration": 0.032,
  "reverseSpeed": 0.2,
  "id": "car_big_wood",
  "speed": 0.48,
  "fluids": [{
   "efficiency": 0.2,
   "fluid": "gasoline"
  },{
"efficiency": 0.4,
"fluid": "diesel"
}]
 },
 {
  "acceleration": 0.032,
  "reverseSpeed": 0.2,
  "id": "car_transporter",
  "speed": 0.4,
  "fluids": [{
   "efficiency": 0.3,
   "fluid": "diesel"
  }]
 },
 {
  "acceleration": 0.04,
  "reverseSpeed": 0.2,
  "id": "car_sport",
  "speed": 0.65,
  "fluids": [{
   "efficiency": 0.12,
   "fluid": "gasoline"
  }]
 }
]}`

fuelstation.json
`{"valid_fluids": ["diesel","gasoline"]}`

**Comment by icha-senpai** [comment]
I like the idea of giving the Ultimate Car mod access to other fuels from other mods
