### ISSUE TITLE
Crash on MP and SP

### ISSUE THREAD

**Issue by TheZIGI** [DarkPacks/SevTech-Ages#3029]
## Bug Report

After creating singleplayer or trying to connect to multiplayer server game crashes

## Expected Behaviour

Not to crash

## Possible Solution

Removing the Antique Atlas fixes it, but unable to play without it

## Steps to Reproduce (for bugs)

1. Install pack from Twitch
2. Launch
3. Start Singleplayer or try to connect to multiplayer server

## Logs

* Client/Server Log: https://gist.github.com/TheZIGI/156bc7bccd9057c82a5fef55113fbd85

## Client Information

* Modpack Version: 3.0.8
* Java Version: 8 Update 51 64-bit -> Twitch default
* Launcher Used: Twitch
* Memory Allocated: ~8GB
* Server/LAN/Single Player: Single Player + MP
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: Sever was created in 3.0.7

* Additional Content Installed: None

## Server Information
* Java Version: 8 Update 171 64-bit
* Operating System: W10
* Hoster/Hosting Solution: Own hosting
* Sponge (Non-Vanilla Forge) Server: Default Forge

## Similar issues 
* https://github.com/DarkPacks/SevTech-Ages/issues/818

**Comment by artdude543** [comment]
This is not a pack issue. You have permission issues with the install. As it's unable to read/create needed folders. Especially ones which the Atlas mod uses.

Please look into ensuring that the pack or the user used to run the pack has sufficient permissions. Also if you are using a cloud drive for the pack don't. It's pointless and leads to similar issues like this. But refer to Google or our Discord for additional support on permissions.
