### ISSUE TITLE
Pulp crafting recipe possibly wrong

### ISSUE THREAD

**Issue by Trinsdar** [DarkPacks/SevTech-Ages#3030]
## Bug Report
when pulp is crafted in the crafting table with one sawdust and one glue it crafts 3 pulp.

## Expected Behaviour
it should craft one pulp, not 3 pulp

## Possible Solution
just change the recipe to make one pulp, not 3.

## Steps to Reproduce (for bugs)
1. grab one sawdust, one glue, and one fluid bladder with water
2. craft the pulp in the crafting table
3. it creates 3

I will upload a video later once I'm at my computer.

https://imgur.com/a/o6TqpjU

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 3.08
* Java Version: 8_u161
* Launcher Used: multimc
* Memory Allocated: 6-8 gigs
* Server/LAN/Single Player: single player
* Optifine Installed: yes
* Shaders Enabled: no

## World Information
* Modpack Version world created in: 3.04
* Additional Content Installed: Extra cells 2, Ae2 stuff, wireless crafting terminal, Morph-o-tool, akashic tome, expanded bone meal.

Will test it with default pack later.

Edit: I put up this issue as the wooden basin makes the same amount but with three sawdust instead of one

Edit 2: uploaded video, which was made with default pack.

**Comment by artdude543** [comment]
The recipe is intentional.
