### ISSUE TITLE
Major Lag

### ISSUE THREAD

**Issue by lmccarty19** [DarkPacks/SevTech-Ages#3032]
I have major lag issues and I dont know why?
I tryed putting it on the lowest settings and it lags, I mean every time I do something it freezes then unfreezes every 5 seconds?
Anyone know why. It stays at a solid 60fps

**Comment by LouisTakePILLz** [comment]
There's a [discord server](https://discordapp.com/invite/darkosto) for these kind of questions.

Chances are you don't have enough memory allocated.
Check the pinned messages on the `#client-discussion` channel.
