### ISSUE TITLE
Constructs Armory Crash

### ISSUE THREAD

**Issue by Telemnaar** [DarkPacks/SevTech-Ages#3035]
Found some issue with PvP and Constructs Armory, I started using steel armor with copper elements from the forementioned mod. Friend of mine wanted to run a test on the armor and shot me with a crossbow which resulted in a servercrash, 2 times.

[2018-06-23-1.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2159133/2018-06-23-1.log.gz)
[2018-07-02-1.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2159134/2018-07-02-1.log.gz)
[2018-07-03-1.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2159135/2018-07-03-1.log.gz)
[2018-07-03-2.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2159136/2018-07-03-2.log.gz)
[debug-1.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2159137/debug-1.log.gz)
[debug-2.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2159138/debug-2.log.gz)

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
