### ISSUE TITLE
Atomic Disassembler Vein Mode Not Functioning Properly When Mining Ores

### ISSUE THREAD

**Issue by dajms3** [DarkPacks/SevTech-Ages#3039]
## Bug Report

While in vein mode, the atomic disassembler from mekanism returns all but the mined block as cobblestone when mining ores. One ore is dropped (for the one directly mined) and cobblestone is dropped for all the vein-mined ores.

## Expected Behaviour

All of the ore that vein-mode mined should drop as ore clusters/respective items rather than cobblestone. 

## Steps to Reproduce (for bugs)

1. Put a powered atomic disassembler into vein mode
2. mine either a geolosis ore or a normal (coralium ore also experienced this bug)
3. see that a ton of cobblestone is dropped rather than ore clusters

## Logs

* Client/Server Log: https://gist.github.com/dajms3/354e62e16ea05c918f55a8d1975359dc.js
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: jre1.8.0_172
* Launcher Used: Twitch
* Memory Allocated: 6144MB
* Server/LAN/Single Player: single player
* Optifine Installed: yes
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.7

* Additional Content Installed: none

**Comment by dajms3** [comment]
Ok, thanks. Back to Tcon Picks it is then.

**Comment by KIck86** [comment]
the same issue is occurring with the vertical digger from actually additions, mines ores from the over world as cobblestone and ores from the nether as low grade charcoal blocks

**Comment by artdude543** [comment]
This is resolved for 3.1.0 (when it comes out)
