### ISSUE TITLE
Various metal Chests causes SEVERE lag with Item Extraction Cable & Dropped Item Interface

### ISSUE THREAD

**Issue by Sorbe** [DarkPacks/SevTech-Ages#3040]
## Bug Report
If you use a _Copper Chest_ instead of a vanilla _Chest_, with an _Item Extraction Cable_, and put in a _Celestial Crystal_ in the _Copper Chest_ SEVERE crushing lag occurs.  The Celestial Crystal appears in the world causing a graphics artifact and the game slow to a near stop (<<1fps). (as shown by the final screenshot)

_Copper Chest_ -> _Item Extraction Cable_ -> _Dropped Item Interface_ (Severe Game Lag)

Also repros with a _Gold Chest_, but with a vanilla _Chest_, none of this happens.

_Chest_ -> _Item Extraction Cable_ -> _Dropped Item Interface_  (OK)

## Expected Behaviour
The Celestial Crystal should be extracted by the Item Extraction Cable and placed in the world normally by the Dropped Item Interface. (as shown by the first set of screenshots).

## Possible Solution
Don't use the larger chests in this scenario.

## Steps to Reproduce (for bugs)
(see above and these following images)
![2018-07-04_01 57 09](https://user-images.githubusercontent.com/7958470/42268172-b2c06f3e-7f2f-11e8-9c73-7b9f1060b191.png)
![2018-07-04_01 57 10](https://user-images.githubusercontent.com/7958470/42268173-b2dd6ea4-7f2f-11e8-8890-6934dbcb5bcb.png)
![2018-07-04_01 57 13](https://user-images.githubusercontent.com/7958470/42268174-b2f76f5c-7f2f-11e8-90eb-0274b24b5014.png)
![2018-07-04_01 57 28](https://user-images.githubusercontent.com/7958470/42268175-b3100fd0-7f2f-11e8-8503-c03cd3b3db14.png)
![2018-07-04_01 57 40](https://user-images.githubusercontent.com/7958470/42268176-b32a629a-7f2f-11e8-9342-3961dfc2300f.png)

## Client Information

Sevtech V3.0.8
Java 8u172 x64
Twitch.Tv / Jar Launcher
8GB Java VM Allocated
Both single player and SMP
No Optifine
No Shaders

## World Information
Fresh Single Player world with V3.0.8

**Comment by artdude543** [comment]
This would need reporting to both AS and Iron Chest repo. Not just linked here. Make issues on each mod and link back to here for tracking purposes.

**Comment by artdude543** [comment]
This bug has been fixed in the mod which is included in 3.1.0 :)
