### ISSUE TITLE
Watering Concrete

### ISSUE THREAD

**Issue by Ridgure** [DarkPacks/SevTech-Ages#3043]
## Context
Happy Birthday Darkosto, 

I am tired of placing my concrete powder next to water and spending (SevTech) Ages mining it and picking it back up. I have not progressed enough to unlock the hydrator so there is no machine that can transform my concrete powder into concrete FeelsBadMan. I have a watering can left from one of the quests and figured I could just water my concrete? I guess not though. Could this be a feature?

Thanks,
  - Ridgure

**Comment by artdude543** [comment]
Watering concrete could be a thing but it won't be part of the pack, due to how the staging and progression is layed out. You'll have to wait for the hydrator sorry mate :(

**Comment by Ridgure** [comment]
Thank you for the quick response and no problem!
