### ISSUE TITLE
3.0.8 Dead Server - I'm done

### ISSUE THREAD

**Issue by ghost** [DarkPacks/SevTech-Ages#3044]
The more that peopled played; The more it crashed and had issues.
It is so bad now that people just stopped playing so i'm done. I'm sorry
for the people who wasted time on this mod pack, maybe single player
is ok, but the server is horrible. I have not even posted most of the
problems because the problems that I did I post, still remain.

Just a big waste of time. 

END OF SERVER

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in: 3.0.7 May 11th 

* Additional Content Installed:

## Server Information
* Java Version: 1.8. 171
* Operating System: Ubuntu 18.04
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server: Provided mod pack / forge / mc

**Comment by artdude543** [comment]
Thank you for reporting an issue!

It appears you are logging an issue for a crash, but you have either not uploaded to PasteBin/Gist etc.. of the actual crash report. This report contains the needed data to help to locate the cause and a possible fix. To find the file needed please review the following for either of the launchers.

## Twitch
1. Select the SevTech Pack to view the modpack page.
2. Click the `...` button on the top right just next to `Get More Content`.
3. Click `Open Folder`.
4. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it. 

## ATLauncher
1. Select the Instances tab, then scroll to the instance of SevTech.
2. Click the bottom right button named `Open Folder`
3. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it.

For any other launcher should be a similar process, if not consult with Google if you are not sure on how to find the folder. The information contained in these reports is critical for getting the crash fixed/looked into.

## Servers
For servers the process if farilt simple. Go the folder cotaining all the sever files/folder and you will see a folder called `crash-reports` follow the same process as above by getting the lastest one and uploading it to a text store.
