### ISSUE TITLE
Add Expanded Bonemeal

### ISSUE THREAD

**Issue by Trinsdar** [DarkPacks/SevTech-Ages#3046]
## Context
It allows to bonemeal sugar cane, cactus, and other plants previously not bonemealable. It would be really useful for before one has a watering can. Every feature can be turned off for if you want only certain things enabled.

## Mod Details
* Name: Expanded Bonemeal
* CurseForge Link: https://minecraft.curseforge.com/projects/expandedbonemeal

**Comment by artdude543** [comment]
This is something which does not match the need for the pack sadly. There are means to make these items grow faster already in the game. Like AS has a powerful system!

But thanks for your suggestion!
