### ISSUE TITLE
Hydra glitched out after I died when fighting

### ISSUE THREAD

**Issue by ridelower** [DarkPacks/SevTech-Ages#3047]
## Bug Report

While fighting Hydra I died and when I returned all of his heads were missing and it was labeled as unknown.  I am unable to do any damage to him now.  I had a friend also confirm this issue on the server who is not running any shaders.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: Version 8 Update 171 (build 1.8.0_171-b11)
* Launcher Used: Twitch
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Server
* Optifine Installed: 
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by ridelower** [comment]
![hydra](https://user-images.githubusercontent.com/40842501/42296734-c3830e6e-7fbe-11e8-866b-0cd491f109c4.png)

**Comment by artdude543** [comment]
I'm closing this due to lack of information. That and your details are very vague on what actually happened. The issue could also have been a rare case which is harder to track down which we don't have the manpower for. If you find the issue again report direct to the TF team.

Thanks.
