### ISSUE TITLE
Can't turn on game? First time?

### ISSUE THREAD

**Issue by godlyberries** [DarkPacks/SevTech-Ages#3048]
## Bug Report
I have not played the mod pack before so I am not sure how it is supposed to behave but I installed it according to instruction, and I get this error message every time I try to open the game 
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) 

## Expected Behaviour
 I get this error message in stead of the game opening 
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I don't think this is supposed to happen?

## Steps to Reproduce (for bugs)

1. Open twitch launcher
2. Press play on minecraft launcher

## Logs

I opened my folder via the twitch launcher and could not find any logs, sorry!
* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: Unknown (?)
* Launcher Used: Minecraft forge/Twitch (?)
* Memory Allocated: 48 GB of my Mac has been used and I have 121 available
* Server/LAN/Single Player: Single player at the moment
* Optifine Installed: Nope
* Shaders Enabled: Just a texture pack

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by godlyberries** [comment]
Again forgive me for my first upload a few days ago as I did not follow the instructions for upload, I am really new to understanding all of this programming and terms! I thank you so much for all your time and hard work! :)

**Comment by artdude543** [comment]
Okay from the crash report (I'll let you off for not uploading it to Gist as you re-posted the issue with better details this time 😄 ) 

But you seem to be running a version of Java which modded MC does not support. You need to stay on Version 8 and nothing higher. Please remove the newer versions and install the latest version of 8.

**Comment by godlyberries** [comment]
Sorry about that! I really don't understand much about modding and such!! I will get my partner to help me out tonight with that! Thank you!! :)

**Comment by ShadowRage908** [comment]
I'm having this same problem. Even after I downloaded and installed Java version 8, I am still getting the following error:

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
Error: Could not find or load main class .Library.Java.JavaVirtualMachines.jdk1.8.0_66.jdk.Contents.Home.jre.bin.java

How do I fix this???
