### ISSUE TITLE
3.0.8 Cannot Cast Float to Int JustARaftMod

### ISSUE THREAD

**Issue by KaffineAddict** [DarkPacks/SevTech-Ages#3050]
## Bug Report
Cannot log into the server. After terrain generation the entire client crashes.

## Expected Behaviour
Client Crashes back to desktop

## Possible Solution
Likely need to put some testcase logic in somewhere to validate arguments. Rebooting the server works but is not a great solution as it has to be reset whenever this occurs

## Steps to Reproduce (for bugs)
Unfortunately I am not 100% how to cause it

Running around the world in wolf boots I got it to occur. Driving around in the immersive raft I also got it to occur. Seems to possibly happen when the server lags  while running around.

## Logs

* Crash Log: https://pastebin.com/Z3uGBKSq

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_171
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.7
* Additional Content Installed: None

**Comment by artdude543** [comment]
@Mrbysco any ideas on this one. The fact we both tried to replicate the issue to no avail but random people seem to get it.

I did debug some mods and none of the ones which edit entities touch this mod. So I'm clueless on what _could_ be causing said issue _again_.

**Comment by Mrbysco** [comment]
Yeah... 1.1.2 should've fixed these issues.
I can't even find the lines that the crash report spewed...

I'm baffled
