### ISSUE TITLE
Coal not spawning in world after unlocking stage one. Version 3.0.8

### ISSUE THREAD

**Issue by yarma92** [DarkPacks/SevTech-Ages#3052]
## Bug Report
 I have a world generated with 3.0.8 that does not appear to have coal in it. I've run around quite a bit with the dousing rod and can not find coal. Also can't seem to find any surface samples for coal. I have ran the oredistribution command in a chunk that should have coal, located where it should be a dug down to it. there is supposed to be some between y1-10 yet its just stone. Running the oredistribution command again while im where it should be reports a lower value of coal, so I have mined through it, though it appears as just stone in the game. This seems to be a reproduction of #2030. All others ores have generated without issue and been located.

## Expected Behaviour
 Expect the dousing rod to be able to report that coal is detected but it does not. Digging down to coal located with /oredistibution 1 1 10 I would expect to see coal but all i encounter is stone. 

## Steps to Reproduce (for bugs)

No reproduction steps but I can provide the world and screenshots. 
![sevtechcoal](https://user-images.githubusercontent.com/2682099/42344323-e61a1866-8093-11e8-8770-99cd4f97e1c8.png)

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0.144
* Launcher Used: Twitch
* Memory Allocated:6GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None

**Comment by artdude543** [comment]
`/oredistibution` won't work it's buggy and when it does work it's wrong for the ore types. As it does not understand our custom ore generation.

Reloading the pack/server will normally fix the showing of the coal rocks. But they **do** generate but sometimes less in some seeds but this is all RNG and nothing can be done in the pack in regards to the issue.

So, sadly you'll have to keep exploring the world till you find the clusters and dig the chunk for the coal. If you get stuck some more you can use our Discord to talk to other users to see if they have some tips/pointers for ya.
