### ISSUE TITLE
Galacticraft CargoLoader "void" item if break

### ISSUE THREAD

**Issue by kileroy** [DarkPacks/SevTech-Ages#3053]
Hi, lovy lova tralala, this modpack is great, down to business : 

## Bug Report
Second, the cargo loader, maybe the unloader too, don’t thrown out there inventory when broken, they just… vanish to the void, kind of annoying for the scavenger that I am, destroying all the crate and stuff after checking what inside. Possibly with the unloader too

## Expected Behaviour
When broken, the cargoloader should do as the chest does, trowing the item it conten in a 'slpash'.

## Steps to Reproduce (for bugs)
I found mine in a space ship in the asteorid field but :
1. Put item in the cargoloader 
2. Break the cargo loader and loose all item in it.

## Logs
[2018-07-04-1.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2168004/2018-07-04-1.log.gz)
[2018-07-04-2.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2168005/2018-07-04-2.log.gz)
No crash on my part.

## Client Information
* Modpack Version: Latest, so 3.0.8
* Java Version: 1.8.0_172-b11
* Launcher Used: Twitch
* Memory Allocated: 7.5 gig
* Server/LAN/Single Player: I'm lonely, Single player
* Optifine Installed: Nop
* Shaders Enabled: Nop

## World Information
* Modpack Version world created in: Hmm, good question... I think it was 4 older versions ago.

**Comment by Azrazal** [comment]
figured i would just jump in here.

this is not a bug, it is intended to work like this, you need to hook it up to unload items from the one found in asteroid bases. any that you place yourself should be fine to take the items out

as far as i know, that means powering it, and connecting to a launch pad with some ship that has cargo space. i did this with the cargo rocket

there is some description of this here: https://wiki.micdoodle8.com/wiki/Strange_Seed

**Comment by kileroy** [comment]
Yea I figure that loading it in a vehicule is the "way of doing it", but 'voiding' the item if breaking... Would be better if it retain them, at least.  
Nowaday, thank for the info!
