### ISSUE TITLE
Galacticraft Slimeling backpack conflict with Ender Utilitie L.M.M.

### ISSUE THREAD

**Issue by kileroy** [DarkPacks/SevTech-Ages#3055]
Hello there, lovy lova tralala, this modpack is awesome, here a bug: 

## Bug Report
Talking inventory, third, is kind of a conflict with Ender utility, The L.M.M. work nice and fine with the slimeling… but if you put them a little back pack thing for them, take it with the gun and repute it in the world, the pack back disappear, with the inventory it has too.

## Expected Behaviour
The slimeling keep his backpack, AND the item it contained when 'release'.

## Steps to Reproduce (for bugs)
1. Have a slimeling with a backpack on, item in
2. Store it in the L.M.M. of ender utility and put releasing it.
3. Check the slimeling, with no backpack.

## Logs
[2018-07-04-1.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2168004/2018-07-04-1.log.gz)
[2018-07-04-2.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2168005/2018-07-04-2.log.gz)
No crash on my part.

## Client Information
* Modpack Version: Latest, so 3.0.8
* Java Version: 1.8.0_172-b11
* Launcher Used: Twitch
* Memory Allocated: 7.5 gig
* Server/LAN/Single Player: I'm lonely, Single player
* Optifine Installed: Nop
* Shaders Enabled: Nop

## World Information
* Modpack Version world created in: Hmm, good question... I think it was 4 older versions ago

**Comment by monodemono** [comment]
This issue seems to be on Ender Utilites end. I'll post this to their issue tracker later.
