### ISSUE TITLE
Sevtech other players can't complete advancements.

### ISSUE THREAD

**Issue by pugmoore** [DarkPacks/SevTech-Ages#3056]
I am playing sevtech ages 3.0.8 server and i am in a party with my friend but when my friend can't complete advancements. I can pick up an item and it will complete that advancement but when he trys it wont complete the advancement. Is there a fix?

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
