### ISSUE TITLE
Cannot join server anymore

### ISSUE THREAD

**Issue by blipblapjack** [DarkPacks/SevTech-Ages#3058]
## Bug Report

When me or my friends try to join our server it lets us in for a tiny amount of time and then boots us with the message "A fatal error has occurred, this connection is terminated"
## Expected Behaviour

When me or my friends try to join our server it lets us in for a tiny amount of time and then boots us with the message "A fatal error has occurred, this connection is terminated"
## Steps to Reproduce (for bugs)

1. We try to join the server
2. It lets us in for a second before booting us with the message "A fatal error has occurred, this connection is terminated

## Logs

* Client/Server Log: https://pastebin.com/2kPWwwqn (client, just the last bit) https://pastebin.com/pTqpjqaw (server, everything it said inbetween me trying to connect and being dropped)
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: version 8
* Launcher Used: twitch/curse
* Memory Allocated: 12288 mb for client, 6 gb for server
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: 

## Server Information
* Java Version: 
* Operating System: 
* Hoster/Hosting Solution: 
* Sponge (Non-Vanilla Forge) Server: 

I have tried removing fancy particles on the client and server already

**Comment by Serolar** [comment]
It would definitely help to fill out the "Server Information" Section. Please take the time to provide this important information, as the problem states dedicated server activity.

Thank you for your time, 
From a fellow Pack-Player, 
Serolar
