### ISSUE TITLE
Missing Water 

### ISSUE THREAD

**Issue by Crussell09** [DarkPacks/SevTech-Ages#3060]
## Bug Report
Water is completely transparent whilst in a weedwood boat in the between lands making gen finding easy

## Expected Behaviour
water should be visible

## Possible Solution
most likely a graphical glitch that needs to be amended due to the camera being forced into 3rdperson

## Steps to Reproduce (for bugs)
when in a weedwood boat water will act as such but be completely invisible in the betweenlands

**Comment by Stifling-Bossness** [comment]
Duplicate of #2506
