### ISSUE TITLE
Game crashed, lost mods, recipes, entities, more?

### ISSUE THREAD

**Issue by etan311** [DarkPacks/SevTech-Ages#3065]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used: twitch
* Memory Allocated: 8gb
* Server/LAN/Single Player: single player
* Optifine Installed: no
* Shaders Enabled: no

## World Information
 3.0.8
* Modpack Version world created in: 3.0.7

* Additional Content Installed: none

I had been getting random crashes, including heavy lag, especially when music would play (1-2 seconds after start, heavy lag for 5-10 seconds, then end abruptly and music would stop). Latest crash, loaded back in, and saw the following, https://imgur.com/a/s2kE6Ye. 

Mac Mini (late 2012)
macOS High Sierra 10.13.5
2.3 GHz Intel Core i7
10 GB 1600 MHz DDR3
Intel HD Graphics 4000 1536 MB

Not sure what other info would be relevant, so please let me know.

Any help appreciated.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by artdude543** [comment]
Thank you for reporting an issue!

It appears you are logging an issue for a crash, but you have either not uploaded to PasteBin/Gist etc.. of the actual crash report. This report contains the needed data to help to locate the cause and a possible fix. To find the file needed please review the following for either of the launchers.

## Twitch
1. Select the SevTech Pack to view the modpack page.
2. Click the `...` button on the top right just next to `Get More Content`.
3. Click `Open Folder`.
4. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it. 

## ATLauncher
1. Select the Instances tab, then scroll to the instance of SevTech.
2. Click the bottom right button named `Open Folder`
3. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it.

For any other launcher should be a similar process, if not consult with Google if you are not sure on how to find the folder. The information contained in these reports is critical for getting the crash fixed/looked into.

## Servers
For servers the process if farilt simple. Go the folder cotaining all the sever files/folder and you will see a folder called `crash-reports` follow the same process as above by getting the lastest one and uploading it to a text store.
