### ISSUE TITLE
Crash when placing sound muffler (CME crash - I think that is important?)

### ISSUE THREAD

**Issue by somepeoplejustwanttocode** [DarkPacks/SevTech-Ages#3071]
Game crashed once I placed a sound muffler. If its any use, I placed it right next to my sheep pen, with about 10 sheep in it.

Crash report: https://pastebin.com/u4SvqKme

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
