### ISSUE TITLE
Bronze tools use copper plates

### ISSUE THREAD

**Issue by elmatador316** [DarkPacks/SevTech-Ages#3072]
Playing on 3.0.8

All the recipes for the bronze tools take copper plates, and there are not recipes for the copper tools.

Everything else is pretty self-explanitory...

**Comment by elmatador316** [comment]
This is in age 2 BTW - not sure if the recipe changes in later ages

**Comment by Stifling-Bossness** [comment]
Duplicate of #2802 please use the search function (and search in CLOSED issues as well)
