### ISSUE TITLE
Advancements are reset when BSOD'd.

### ISSUE THREAD

**Issue by Just-Kohai** [DarkPacks/SevTech-Ages#3073]
## Bug Report

Advancements are reset when BSOD'd.
## Expected Behaviour

Advancements should regenerated from the most recent backup world.
## Possible Solution

Save all progression data in a backup world. When loading a backup world, read and write the progression data into the world when loading it up again.
## Steps to Reproduce (for bugs)

1. Start a world with SevTech Ages 3.0.8
2. Reach Age 1 or above.
3. BSOD.
4. Load the world again.
5. Advancements should be reset. Despite having recipes unlocked.

## Logs

* Client/Server Log: N/A. BSOD'd
* Crash Log: N/A. BSOD'd

## Client Information

* Modpack Version: 3.0.8
* Java Version: Java 8 Update 171 (build 1.8.0_171-b11)
* Launcher Used: MultiMC (Imported from ZIP)
* Memory Allocated: 6144 MB
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None.

**Comment by artdude543** [comment]
Well you blue screened nothing managed to saved. So not our fault or the packs.
