### ISSUE TITLE
3.0.8 turntable auto-fill crafting station diamonds glitch

### ISSUE THREAD

**Issue by joebywan** [DarkPacks/SevTech-Ages#3075]
## Steps to Reproduce (for bugs)

1. Age 2
2. Tinkers Crafting Station
3. Have items in inventory for crafting turntable
4. Search for turntable recipe & click the plus sign to auto-fill the crafting table with the items to craft the turntable.
5. Shows a stack of 64 diamonds in the result window instead of the turntable

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0 171
* Launcher Used: Jar launcher
* Memory Allocated: 8GB
* Server/LAN/Single Player: Dedicated server running on lan
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed:

## Server Information
* Java Version: 1.8.0 171
* Operating System: Win7
* Hoster/Hosting Solution: Self
* Sponge (Non-Vanilla Forge) Server: No idea what this is.

**Comment by monodemono** [comment]
Could not reproduce.

Clicked the +:
<img width="1920" alt="screen shot 2018-07-09 at 05 36 16" src="https://user-images.githubusercontent.com/1161277/42450784-26a27b96-833a-11e8-890c-88e1fbfaaec2.png">

Shift-clicked the +:
<img width="1920" alt="screen shot 2018-07-09 at 05 36 40" src="https://user-images.githubusercontent.com/1161277/42450814-3bba553a-833a-11e8-86dc-c704600cd9bf.png">

**Comment by Gepett0** [comment]
Happened to me once or twice while mass crafting pistons. Crafting result showed a stack of diamonds, although i got the correct amount of pistons shift-clicking the result.
