### ISSUE TITLE
Translocators Not Working As Intended When Stocking an Inventory

### ISSUE THREAD

**Issue by dajms3** [DarkPacks/SevTech-Ages#3078]
## Bug Report
a translocator supplying to one in regulate mode will only attempt to pull from the first slot of an attached inventory even if there are whitelisted items in other slots.

## Expected Behaviour
The input translocator should check every slot and not just the first filled slot, that way its possible to insert a set amount of multiple types of items with a single translocator when the input inventory has excess items.

## Steps to Reproduce (for bugs)

1. Attach two chests with translocators
2. set one in output mode, right click a diamond nugget on it to put it in regulate mode, and put 1 potato and 1 carrot in the filter
3. In the input chest, put, in this order, a stack of cobblestone, a stack of potatoes, and a stack of carrots
4. The cobblestone essentially blocks the translocators from transferring the potatoes and carrots. This will also occur if you wanted to supply one potato and one carrot but put a stack of each in the input chest;the excess potatoes would block the carrots from going through. 

## Logs

* Client/Server Log: https://gist.github.com/dajms3/e94344624c5ed5ed134a08a3e084d9fc

## Client Information

* Modpack Version: 3.0.8
* Java Version: jre 1.8.0_172
* Launcher Used: Twitch
* Memory Allocated: 6144 MB
* Server/LAN/Single Player: single player
* Optifine Installed: yes
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.7

* Additional Content Installed: none

**Comment by artdude543** [comment]
https://github.com/TheCBProject/Translocators/issues/36

**Comment by artdude543** [comment]
Will be fixed when 3.1.0 releases 😄
