### ISSUE TITLE
Eye of ender obtainable and usable in Age 2

### ISSUE THREAD

**Issue by elmatador316** [DarkPacks/SevTech-Ages#3079]
I just noticed that the Eye of Ender is available as a sarlight infusion recipe in Age 2.  I know there are other items that are like this (thinking glowstone in the Twilight Forest chests) but they aren't really usable until later on.  The issue comes up with the fact the Powerstone Tracker is now able to be crafted as well, which I am assuming is supposed to be gated.  I just made the item, but I'm too scared to actually use it (I'm assuming it's gated behind age 3 for a reason)

Suggested Fix: Made the Eye of Ender recipe for starlight transmutation locked behind Age 3.

Thanks, keep up the awesome work!

**Comment by monodemono** [comment]
Fixed in next release.
