### ISSUE TITLE
Generator block (IE) render issues

### ISSUE THREAD

**Issue by tupseny** [DarkPacks/SevTech-Ages#3080]
## Bug Report
When i try to check Generator block (immersive engineering) recipe in jei client is crashing. Texture pack was installed, so i clicked on the block in JEI and it crashed. I removed all texture packs. Texture of block is invisible in JEI. I tried to find recipe of generator block via steel ingot usages. When i got the page with recipe client crashed.

## Expected Behaviour
The recipe of Generator Block should be shown. Texture of block should be visible in JEI.

## Possible Solution

Remove CTM mod (Connected Textures Mod)

## Steps to Reproduce (for bugs)

**I** Invisible texture
1. Open JEI and search for "@Immersive"
2. Find spaces in list, where generator block must be.

**II** Crash client
1. Install texture pack
2. Open JEI and search for Generator Block.
3. Click on the icon of generator block in JEI.

## Logs

* Crash Log: _Find recipe of block via steel usages_ (https://pastebin.com/itamkHhs)
* Crash Log: _Check recipe in JEI then texture pack is installed_ (https://pastebin.com/CCrF1eP4)

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_51
* Launcher Used: Twitch
* Memory Allocated: 5,5G
* Server/LAN/Single Player: Server (The Goon Squad https://thegoonsquadeu.enjin.com/)
* Optifine Installed: NO
* Shaders Enabled: NO

## World Information

* Modpack Version world created in: ~3.0.6

* Additional Content Installed: NO

## Server Information
* Java Version: NI
* Operating System: NI
* Hoster/Hosting Solution: https://thegoonsquadeu.enjin.com/
* Sponge (Non-Vanilla Forge) Server: NI

**Comment by artdude543** [comment]
Will be fixed when 3.1.0 releases 😄
