### ISSUE TITLE
Homemade server keeps saying we timed out

### ISSUE THREAD

**Issue by soulfoood** [DarkPacks/SevTech-Ages#3081]
## Bug Report

My homemade (privately owned, *downloaded official sevtech server*) server keeps telling me and my friend that we timed out. The server says it is up. When I log in the first time after starting it up, it looks as though i am in the world however after about a minute or so it kicks me out as "timed out." This also happened to my friend. I also know that my port forwarding is correct because my server worked in the past. I've tried to restart my computer and router multiple times, non have worked so far.

## Expected Behaviour

Usually, and this happened before about a month ago, it lets us in.

## Steps to Reproduce (for bugs)

1. I don't know how you would reproduce due to the fact that I don't know what is causing it.

## Logs

* Client/Server Log: https://paste.feed-the-beast.com/view/35c51543
* Crash Log: no crashes have occured

## Client Information

* Modpack Version: 3.08
* Java Version: 64x
* Launcher Used: ATLauncher
* Memory Allocated: 6gb
* Server/LAN/Single Player: server
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: how would i figure this out?

* Additional Content Installed: none

## Server Information
* Java Version: 64x
* Operating System: 64x windows ten
* Hoster/Hosting Solution: Myself
* Sponge (Non-Vanilla Forge) Server: no

**Comment by artdude543** [comment]
This sort of issue will be _fixed_ when out GS 2.0 update lands. For now, it's something players have to deal with or find a way better the network connection to the server. Or increase the timeout which if your using our server files the option can be tweaked on the `settings.bat/sh` file.

Other than waiting for the update, there's not a lot which can be done in regards. Sorry.
