### ISSUE TITLE
Horses/Donkeys cannot be bred

### ISSUE THREAD

**Issue by Serolar** [DarkPacks/SevTech-Ages#3084]
## Bug Report
Using a golden carrot/apple on a horse/donkey makes you mount the steed, and doesn't consume the golden fruit.

## Expected Behaviour
Using a Golden Apple/Carrot on a Horse/Donkey should activate its Love Mode, allowing for the breeding of the noble steeds.

## Possible Solution
Investigate which mod alters the horse entity, and see if they'll code in the proper call?

## Steps to Reproduce (for bugs)

1. Make Golden Apple/Carrot. (Stage 2 Required)
2. Right-Click on Tamed Horse while holding said Golden Fruit.
3. Get off horse.

## Logs

* Client/Server Log: https://pastebin.com/RUiJgsxX 
(I don't think this will help at all, but here it is.)
* Crash Log: No Crash Log

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_172
* Launcher Used: Twitch/MultiMC Symlink
* Memory Allocated: 6GB
* Server/LAN/Single Player: SinglePlayer
* Optifine Installed: Nope
* Shaders Enabled: Nope

## World Information

* Modpack Version world created in: 3.0.0

* Additional Content Installed: MineMenu

**Comment by Hobos8MaLunch** [comment]
You can mate horses from the ceremonies I had the same issue but if you sing the song of springs it will make them mate. Check out the book of totemic. (Not sure if that is the correct song but it's one of them)

**Comment by artdude543** [comment]
We have a mod which prevents the usage of golden items. This is intended. You need to use the ceremonies.
