### ISSUE TITLE
Missing mapping for part with FMP

### ISSUE THREAD

**Issue by dayne** [DarkPacks/SevTech-Ages#3085]
## Bug Report
3.0.8 Server crashes on load due to error related to missing mapping ID `minecraft:redstone_torch` in the ForgeMultipart plugin.

```
[05:23:50] [Server thread/ERROR]: [ForgeMultiPartCBE]: Missing mapping for part with ID: minecraft:redstone_torch
[05:23:50] [Server thread/ERROR]: [MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at codechicken.multipart.handler.MultipartSaveLoad$TileNBTContainer.onLoad(MultipartSaveLoad.scala:29) ~[MultipartSaveLoad$TileNBTContainer.class:?]	
```

## Expected Behavior
Server loads and is available for use

## Possible Solution
Update to newer version of ForgeMultipart.   SevTech 3.0.8 currently uses ForgeMultipart-1.12.2-2.4.2.58-universal.jar 

They appear to have recognized this save/load issue related to redstone torches and fixed it in this github commit: 

https://github.com/TheCBProject/ForgeMultipart/commit/b996fe4c0bff80f43c84427490057368799956d2

They appear to have 2.4.2.60 version out however this thread here a person is reporting that the issue is still in version 2.4.2.60.  See discussion in https://github.com/TheCBProject/ForgeMultipart/issues/27

## Steps to Reproduce (for bugs)
Not sure how to cause this to reproduce yet. Restoring from backup now and we'll pay attention to new deploys of redstone to see if we can detect what we did.

We have a backup of our world that crashes on load and could bundle it up and host for download if that would be helpful to somebody with more experience debugging/testing.

## Logs
* Client/Server Log: https://gist.github.com/026add6a9d8ce14d22269b873652297e
* Crash Log:  https://gist.github.com/199b3d673336fd1135a2366ec270d701

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version: 3.0.8
* Java Version:  openjdk version "1.8.0_171" - 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11
* Launcher Used: ServerStart.sh
* Memory Allocated: 8184M
* Server/LAN/Single Player: Server
* World created with 3.0.8 and we've not added anything beyond default SevTech
* We've gotten to tech level 3 - so just getting going serious with redstone fancy things now.

## Kudos
Thank you for this wonderful mod for Minecraft!

My friends and I have been minecrafters early into minecraft (like first 100,000 or so people - we had to figure out how to pay in euros) and had never done any of the mods -- just been staying in touch with the vanilla experience.  SevTech inspired all of us to dive back in and work as a team to build up from sticks and stones into a minecraft tech industry.  We are having a blast!

**Comment by artdude543** [comment]
Will be fixed in 3.1.0 😄
