### ISSUE TITLE
Crash on desktop at random times

### ISSUE THREAD

**Issue by baghett2616** [DarkPacks/SevTech-Ages#3086]
## Bug Report
The game crashes to desktop at random times for no apparent reason.
Laptop specs:
Asus Notebook U36SG
Intel Core i5 2.5GHz (all 4 cores active)
8 GB RAM (4 GB Allocated to modpack)
Nvidia Geforce 610m 1GB
Windows 10

## Steps to Reproduce (for bugs)
None really, the game just crashes randomly, either after it finishes loading (which btw takes an awfully long time 30-40 mins at best) or at random times when playing (tried running it several times, no pattern that i could see)

## Logs
https://pastebin.com/YNtxcYN9

## Client Information

* Modpack Version: 3.7
* Java Version: latest (according to the twitch launcher)
* Launcher Used: native
* Memory Allocated: 4GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.7

**Comment by artdude543** [comment]
You ran out of memory pretty clear from the crash report. Allocate a tad more and you should be fine.
