### ISSUE TITLE
SevTech Ages 3.0.8 Crash on Item Render

### ISSUE THREAD

**Issue by Sbarb1** [DarkPacks/SevTech-Ages#3088]
## Bug Report

Crashes when rendering an item in the progression screen on age 2, seems to be a twilight forest block

## Expected Behaviour

When item is being called to render it crashes the game

## Steps to Reproduce (for bugs)

1. Open the progression screen
2. Choose age 2

https://youtu.be/HyD2in2ISPY
## Logs

* Client/Server Log:
https://gist.github.com/Sbarb1/c11378ef1aaf10a8245a1debefa23673
* Crash Log:
https://gist.github.com/Sbarb1/7744229da89234d91ae1d2db04c77f2e

## Client Information

* Modpack Version: 3.0.8
* Java Version: jre1.8.0_171
* Launcher Used: twitch
* Memory Allocated: 6,026
* Server/LAN/Single Player: Single Player
* Optifine Installed: no
* Shaders Enabled: only default settings

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None

**Comment by artdude543** [comment]
Fixed in 3.1.0 😄
