### ISSUE TITLE
The Irridescent Alter recipe for Constellation paper gives Discidia paper

### ISSUE THREAD

**Issue by Lokiare** [DarkPacks/SevTech-Ages#3094]
I'm running from Twitch.tv PC app up to date version.

When using an Irridescent Alter to create constellation paper, it only gives Discidia paper. Since you only need one of these in the game, I'm thinking it might be a mistake and should give the blank constellation paper.
![screenshot 2018-07-11 14 25 34](https://user-images.githubusercontent.com/1618213/42594936-4d7f3f14-8516-11e8-976c-0ddf0734fd2f.png)

**Comment by justinrusso** [comment]
Since there was much uncertainty, I'm leaving this up to be looked into.

**Comment by justinrusso** [comment]
This is intentional.
