### ISSUE TITLE
Horses cannot breed by Rite of Spring

### ISSUE THREAD

**Issue by Serolar** [DarkPacks/SevTech-Ages#3095]
## Bug Report
Activating the Rite of Spring, with only 2 Horses in the Area of Effect does nothing.

## Expected Behaviour
2 Horses in the Rite of Spring AoE should allow a baby horse to show up.

## Possible Solution
Uhh, you got me.

## Steps to Reproduce (for bugs)

1. Have 2 Horses in a Pen, doesn't matter how small, as long as they fit in the Rite of Spring's range.
2. Perform the Rite of Spring, where Both bars on the Ceremony HUD Become Empty for a time.
3. Watch the HUD for the Ceremony fade away, leaving what was there before.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_172
* Launcher Used: Twitch/MultiMC Symlink
* Memory Allocated: 6GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: Nope
* Shaders Enabled: Nope

## World Information

* Modpack Version world created in: 3.0.0

* Additional Content Installed: MineMenu

**Comment by techdude** [comment]
I had this same issue and I finally figured it out. You can't breed horses until they have been both tamed. Tame the horses and then try again and it should work.

**Comment by artdude543** [comment]
Both horses need to be tamed to allow breading.
