### ISSUE TITLE
Recipes for Copper/Bronze Tools in Age One Mismatched

### ISSUE THREAD

**Issue by MasterMilitia** [DarkPacks/SevTech-Ages#3096]
When trying to craft bronze tools I noticed that their recipe uses copper plates rather than bronze ones, copper tools are also thus uncraftable in age one. Armour seems to be fine however. Simple fix is just to update the craft tweaker recipe using the correct plate item ID.

**Comment by artdude543** [comment]
Already fixed. Check other issues before opening them...
