### ISSUE TITLE
Mekanism Universal Cable Stops Transmitting After Chunk Unload

### ISSUE THREAD

**Issue by AndrewR73** [DarkPacks/SevTech-Ages#3097]
## Bug Report
When I travel to another area of the map far enough from my base (or to another dimension -- Nether, End, Moon, etc.) that the chunks of the base become unloaded, when I return all the Mekanism Universal Cables I have around the base are no longer transmitting power:
![2018-07-12_11 57 26](https://user-images.githubusercontent.com/8558973/42654105-52b3afc2-85cc-11e8-91d4-73e8a651e4a9.png)

Checking the power generator unit shows it/they are functioning and producing power but the cable just isn't transmitting it:
![2018-07-12_11 57 48](https://user-images.githubusercontent.com/8558973/42654116-5f318062-85cc-11e8-811e-f0fcadba0d78.png)

I can break the cable and put it back, which will start the power flowing again, but only for those cable pieces I broke and replaced:
![2018-07-12_12 06 24](https://user-images.githubusercontent.com/8558973/42654150-7f6f8b30-85cc-11e8-8c12-3c3ab83f4f5b.png)

The only way I can fix it is to log-off and restart the world.

## Expected Behaviour
The Mekanism Universal Cable should transmit power from the generator to receiver at all times, provided power exists, when the chunk is loaded or re-loaded.

## Possible Solution
unknown

## Steps to Reproduce (for bugs)

1. Create some kind of RF power generator device.
2. Use Mekanism Universal Cable to connect the power generator to a power consumer device, and ensure power is flowing normally.
3. Leave the area of the power generator so that the chunk it is in is unloaded.
4. Return to the area to find the power no longer flowing.

## Logs
* Client/Server Log:
[latest.log](https://github.com/DarkPacks/SevTech-Ages/files/2189962/latest.log)
* Crash Log:
n/a

## Client Information
* Modpack Version: 3.0.8
* Java Version: 1.8.0_161
* Launcher Used: Twitch
* Memory Allocated: 10GB
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.6
* Additional Content Installed: n/a

**Comment by pepi-tsankov** [comment]
The current temporary fix is to have the area chunk loaded. And this is caused by the cables going over chunk borders. I am not sure how this could be fixed too. But not only mekanism cables have this problem- the cyclic ones do it as well. At least.there might be more.

**Comment by artdude543** [comment]
Mekanism know about this issue and have been trying to fix it for ages to no avail nothing we can do in regards to it the issue.

In regards to Cyclic unless you have 100% prove the bug with reproductions. That needs to be made into it's own issue.
