### ISSUE TITLE
Game Crash - Reason Unknown

### ISSUE THREAD

**Issue by AndrewR73** [DarkPacks/SevTech-Ages#3098]
## Bug Report
Running around a desert looking for ores/resources, using JournyMap to mark the locations of any found. Night approached, to avoid fighting mobs, dug down to mine up a vein of Hematite. Digging a 2x1 hole straight down, stopped when the first block of Hematite Ore was found. Using Tinker's pick, performed an Excavate until the pick worn down. With ore still remaining, jumped into the new open cavity to gather up the rest. Right after hitting the bottom, the game froze, then crashed -- complete hard crash back to Windows desktop.

## Expected Behaviour
Game should play normally, without lag or crash, regardless of movement by the player.

## Possible Solution
n/a?

## Steps to Reproduce (for bugs)
Described steps leading to crash above.

## Logs
* Client/Server Log: 
[latest.log](https://github.com/DarkPacks/SevTech-Ages/files/2190113/latest.log)

* Crash Log: 
[crash-2018-07-12_12.51.49-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/2190123/crash-2018-07-12_12.51.49-server.txt)

## Client Information
* Modpack Version: 3.0.8
* Java Version: 1.8.0_161
* Launcher Used: Twitch
* Memory Allocated: 10GB
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.6
* Additional Content Installed: n/a

**Comment by Serolar** [comment]
Please put your Logs and Crash Reports in a site like Pastebin or Gist, it helps us know they're not randomly malicious. They might not be, but it's safer that way.

Thank you for your time,
Serolar

**Comment by AndrewR73** [comment]
Fair enough @Serolar ....

Latest.log (due to size of file and limitations of PasteBin Free, the log is of approximately an hour prior to crash to crash point)
 - https://pastebin.com/Hwd78m3g

crash-2018-07-12_12.51.49-server.txt
 - https://pastebin.com/jNdrbP8D

-- Andrew

**Comment by AndrewR73** [comment]
Had another game crash out of the blue like last time. This time however I was gliding from my Astral Sorcery area (up in the sky) down to my main base using my AS Mantle like an Elytra. Was coming around the back side of the base in a slow clockwise turn about to land and... crash, back to Windows desktop.

Latest.log
 - https://pastebin.com/iGhJ2PjD

crash-2018-07-17_11.03.44-client.txt
 - https://pastebin.com/WstAaJYz

-- Andrew

**Comment by artdude543** [comment]
This will be "patch/fixed" in 3.1.0
