### ISSUE TITLE
Chunks wont load/Random death's/Destroyed my world

### ISSUE THREAD

**Issue by BiDDo** [DarkPacks/SevTech-Ages#3099]
Log: 

## Bug Report
- Issue Occurred post performing AS attunement ritual to the X looking constellation on both the player and a celestial crystal to create first collector crystal.  Noticed no effect in place on player.  Created collector crystal. Zombies spawned in fully lit secured area (F7 on to check always) randomly and killed me as I was AFK.  On respawn noticed whole region and the corner of my base where the AS constructions were de-spawned and now randomly player die's in an unpredicatable way.  Additionally unable to pick up any item's have received a Graves notice with item list and am not able to SHIFT collect my grave, collect XP or other world drops. 

## Expected Behaviour
Chunks wont re-generate, half my world is gone, random deaths. Large SADFACE because Sevtech Effort and this is the second time my world has de-spawned chunks in this manner. 

## Possible Solution
Given I was doing AS rituals and in AS constructions and chunks including this are gone maybe thats the source? 

## Steps to Reproduce (for bugs)
Not really sure how to reproduce its not like it had a specify cause and effect cycle.

## Logs
https://gist.github.com/BiDDo/05db87994bef80908c4c6538036ea2c1

## Client Information
MC Launcher 2.1.1216
Not using Twitch App because bad. 
Forge 1.12.2-14.23.3.2681
 JVM Arguments: -Xmx6g -Xms1g -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

* Modpack Version: Sevtech 3.07
* Java Version:
* Launcher Used: MC 2.1.1216/ Forge 1.12.2-14.23.3.2681
* Memory Allocated: 6GB (absorbs about 12 in real term looking at monitor)
* Server/LAN/Single Player: Singleplayer
* Optifine Installed:  YES (Using Texture pack Chroma Hills 128x)
* Shaders Enabled: NO

## World Information
Better Foliage disabled only. 
![biddo wprld death](https://user-images.githubusercontent.com/41171981/42664443-2612e1ba-867e-11e8-84ef-871d678209ba.png)

**Comment by artdude543** [comment]
This entire report is invalid and support is voided.

1. You're using the Vanilla Launcher for this pack. AtLaucher/MultiMC/Twitch are covered for support.
2. Your Forge version is not the one we've shipped with the pack.
3. It's a custom install which you've probs broken something in regards.

Please use a launcher we've released the pack on.
