### ISSUE TITLE
Mob grinding server crash

### ISSUE THREAD

**Issue by Warzer1** [DarkPacks/SevTech-Ages#3100]
**Bug Report**
Edited:  it seems the mob grinder crashes the server when a player gets pulled into them with vector plates.
Additionally if you crash while stuck in the grinder you end up in a server crash loop.  I am going to restore from backup to fix.

**Expected Behaviour**
Server shouldn't crash

Possible Solution
unknown

Steps to Reproduce (for bugs)
build a mob farm with mobgrindingutils I had 2 of the grinders with upgrades was full health when it crashed.

Described steps leading to crash above.
Logs

    Client/Server Log:
[latest.log](https://github.com/DarkPacks/SevTech-Ages/files/2190769/latest.log)
I have a debug log as well but its 18mb i can zip and provide if needed.
this log is too big for pastebin.
    Crash Log:

Mob grinder crash: 
[crash-2018-07-12_20.11.38-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/2190765/crash-2018-07-12_20.11.38-server.txt)

https://pastebin.com/V9eQ0qmX

Server Information

    Modpack Version: 3.0.8
    Java Version: 1.8.0_171
    Memory Allocated: 2GB
    Server
    Optifine Installed: No
    Shaders Enabled: No

World Information

    Modpack Version world created in: 3.0.8
    Additional Content Installed: laggoggles

**Comment by artdude543** [comment]
This would be fixed in the next update. No ETA as of yet.

**Comment by artdude543** [comment]
Will be fixed when 3.1.0 lands 😄
