### ISSUE TITLE
Crash when apply redstone to Block Dispenser from Better with Mods

### ISSUE THREAD

**Issue by Kooplah** [DarkPacks/SevTech-Ages#3101]
## Bug Report

Server crashes when powering Better with Mods Block Dispenser with redstone, while it has a block in it.

## Expected Behaviour

It should place the block in front of the dispenser.

## Possible Solution

Voodoo?

## Steps to Reproduce (for bugs)

1. Place at least one block in the block dispenser
2. Apply redstone signal to block dispenser
2. View crash report

## Logs

* Client/Server Log: https://pastebin.com/JwCJErhc  (This is only the last chunk of the log, as it was too large to pastebin the whole thing.)
* Crash Log: https://pastebin.com/g53WMwiP

## Client Information

* Modpack Version: 3.0.8
* Java Version: build 1.8.0_171-b11
* Launcher Used: Twitch
* Memory Allocated: 5GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.7

* Additional Content Installed: None

**Comment by artdude543** [comment]
What block was in the placer? Kind of critical information missing...

**Comment by Kooplah** [comment]
Heh. Yeah sorry I'm not the best at reporting things.

I tested several blocks. Cobblestone, dirt, dark oak vanilla logs and planks and birch logs from vanilla. All vanilla items, nothing was chiselled or anything like that.

**Comment by artdude543** [comment]
Fixed with https://gitlab.com/BetterWithMods/BetterWithMods/commit/0ee8ab15e49d21a31f3a78bd324e2ec9411d2771

Mod will be updated when the next update lands.

**Comment by artdude543** [comment]
Will be fixed in 3.1.0 😄

**Comment by Tander** [comment]
3.0.8, still crashes. Oh, hope 3.1.0 will be soon.
