### ISSUE TITLE
Betweenland Potions Always At Base Stats

### ISSUE THREAD

**Issue by Emblin13** [DarkPacks/SevTech-Ages#3103]
## Bug Report
When creating a Betweenlands infusion, regardless of how much essence is added, and how long the infuser is stirred, the infusions always come out at potency 1, duration 1.

## Expected Behaviour
I should get an infusion with potency and duration which match the amount of essence used. For example, for a healing elixir, if I use 3 yeowynn and 3 ordaniis, I should be getting a healing elixir with potency of 3, duration of 3.

## Steps to Reproduce (for bugs)
1. Find an infusion recipe to make
2. Get the appropriate vials of essence to make it
3. Put the vials of essence in a water-filled infuser in any ratio you want (total essence can't exceed 6).
4. Stir the infuser until it gives an audio cue and changes color
5. Shift rightclick the infuser with a bucket, and pour it into an alembic
6. Let the alembic finish processing the infusion
7. Retrieve the infusion by rightclicking the alembic with a dentrothyst vial
8. Watch in despair as you get infusions with potency 1, duration 1, regardless of what you do.

## Logs
* Client/Server Log: https://gist.github.com/Emblin13/4b9023bb208f6fba765a5b29c3be82e6
* Crash Log: None

## Client Information
I am in stage 2. I have 8Gb allocated to this pack.

* Modpack Version: 3.0.8 (current)
* Java Version: Version 8 Update 171 (build 1.8.0_171-b11)
* Launcher Used: Twitch
* Memory Allocated: 8Gb
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: Nope
* Shaders Enabled: None

## World Information
* Modpack Version world created in: World was created 3 days ago (version 3.0.8)
* Additional Content Installed: None

**Comment by monodemono** [comment]
Unable to replicate...

<img width="1920" alt="screen shot 2018-07-20 at 17 35 07" src="https://user-images.githubusercontent.com/1161277/43030295-47bbd770-8c43-11e8-88f7-f13c814d02e3.png">
<img width="1920" alt="screen shot 2018-07-20 at 17 35 09" src="https://user-images.githubusercontent.com/1161277/43030298-49dea1fe-8c43-11e8-8130-7f1db9513fae.png">

**Comment by monodemono** [comment]
One more piece of proof that was requested in discord before I close this issue.

<img width="1920" alt="screen_shot_2018-07-20_at_22 47 25" src="https://user-images.githubusercontent.com/1161277/43041149-4156f436-8d0c-11e8-8848-748fed02b788.png">
<img width="1920" alt="screen_shot_2018-07-20_at_22 47 26" src="https://user-images.githubusercontent.com/1161277/43041150-439fe644-8d0c-11e8-8839-14191b40e95d.png">
<img width="1920" alt="screen_shot_2018-07-20_at_22 47 28" src="https://user-images.githubusercontent.com/1161277/43041151-456155da-8d0c-11e8-91da-f3c2c499308f.png">
