### ISSUE TITLE
Won't load with Optifine

### ISSUE THREAD

**Issue by Shad0wdrag0n** [DarkPacks/SevTech-Ages#3104]
## Bug Report
I've reached a point where minecraft is pausing for a couple seconds every few seconds while playing Sevtech, making it pretty much unplayable. I tried to put Optifine into the mods folder, but when I try to load the game I end up with an error saying "It looks like you are using an unsupported modified version of the game." I tried clicking on the crash report but it wouldn't do anything. When I clicked on more info I got: 
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Caliper (caliper)

Is this a bug, or is there something else you're supposed to do to get Optifine working with Sevtech?

## Steps to Reproduce (for bugs)
1. Put Optifine into the mods folder
2. start up sevtech

## Client Information
* Modpack Version: 3.0.8
* Java Version: jre-8u171
* Launcher Used: Twitch
* Memory Allocated: 4gb
* Server/LAN/Single Player: single
* Optifine Installed: no, that's the problem
* Shaders Enabled: no

**Comment by Emblin13** [comment]
I noticed you have only 4Gb of memory allocated to Sevtech. Sevtech, like most big modpacks, should be given 8Gb if you want it to run without issues. Allocating more memory won't fix the optifine problem, but you won't need optifine after this.

**Comment by Shad0wdrag0n** [comment]
4gb is what the pack defaults to when it loads. I've tried running it with 5gb but it didn't make any difference. My computer only has 8gb total, so I guess I won't be able to play this unless I get more memory. Although, I have heard that allocating too much memory can also cause problems, so wouldn't doubling the default memory allocation also cause problems in sevtech?

**Comment by Emblin13** [comment]
Allocating too much memory only causes problems if your computer can't handle it. However, I didn't realize your computer only had 8Gb of ram... In this case, I wouldn't allocate any more than like 5Gb. 

Hopefully you can get the help you need to add in optifine. Good luck.

**Comment by Shad0wdrag0n** [comment]
My computer actually has 12gb, but giving minecraft 8gb of that still seems like a lot. I'll bump it up a bit more and see if it helps, otherwise I hope there's a way to get optifine to work.
