### ISSUE TITLE
Unknown cause server crash

### ISSUE THREAD

**Issue by Warzer1** [DarkPacks/SevTech-Ages#3105]
looking for help to find the actually issue so i can put more accurate info into this server crash report.

## Bug Report
Server crashed after entering the twilight forest.  I am not sure if it actually had anything to do with it.
we have 2 total users on the server and both were on and in the TF

## Expected Behaviour
not crash

## Possible Solution
no clue as of yet

## Steps to Reproduce (for bugs)
seems completely random but has happened a few times

## Logs

* Client/Server Log:
reduced set of logs as they were to large for pastebin
https://pastebin.com/FEN4wpiQ
* Crash Log:
no crash log created for this crash.

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.171
* Launcher Used:none
* Memory Allocated:2gb
* Server/LAN/Single Player: server
* Optifine Installed:no
* Shaders Enabled:no

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed:
laggoggles 

## Server Information
* Java Version:1.8.171
* Operating System:unknown (hosted)
* Hoster/Hosting Solution: https://www.minecraft-hosting.pro
* Sponge (Non-Vanilla Forge) Server:unknown

**Comment by artdude543** [comment]
`[20:50:03] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [§rServer§r] §rServer§r §rshutdown§r §rin§r §r10§r §rseconds!§r §rSaving..§r`

This has nothing to do with us. Either your server host is closing the server after you hit a RAM cap or high CPU usage.

But the server is not crashing but being told to shutdown cleanly. Which is very clear from the logs. You'll need to contact your server host on this matter.
