### ISSUE TITLE
Game Not Saving Properly

### ISSUE THREAD

**Issue by Emblin13** [DarkPacks/SevTech-Ages#3106]
## Bug Report
Every once in a while (happened to me twice so far), I will exit my save, and the game is stuck on "shutting down internal server" forever. I can wait hours but it will not finish, so I am forced to shut it down before it finishes. When I load the save later, changes to my things like my inventory are saved, but block changes are reverted many minutes back. This most recent time, I quit the game after mining half of an hour, came back and found that things like tool durability, inventory, and markings on my map were saved, but my chest full of ore was missing, and all of the ore I know I mined had reappeared.

## Expected Behaviour
The game saves as it should.

## Steps to Reproduce (for bugs)
1. Play game
2. Disconnect
3. Seemingly random chance to get this bug

## Logs
* Client/Server Log: https://gist.github.com/Emblin13/c88754f3c66bea4d9f9754134b70bf28
* Crash Log: None

## Client Information
* Modpack Version: 3.0.8 (current)
* Java Version: Version 8 Update 171 (build 1.8.0_171-b11)
* Launcher Used: Twitch
* Memory Allocated: 8Gb
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: Nope
* Shaders Enabled: None

## World Information
* Modpack Version world created in: World was created 4 days ago (version 3.0.8)
* Additional Content Installed: None

**Comment by artdude543** [comment]
The Twitch Launcher is not using the correct version of Java. Please follow this guide on how to force it to use the correct one: https://docs.google.com/document/d/e/2PACX-1vR5muyi1m7Zy_qSwrzeb9e3tbbRlksguNUb_Pvm3pn9eDpsIkUj5qQUq6WFPPdEoVWZq91WvvH57KzC/pub
