### ISSUE TITLE
Add the NotEnoughIDs mod to raise the BlockID limit

### ISSUE THREAD

**Issue by florensie** [DarkPacks/SevTech-Ages#3107]
## Context

This mod extends the maximum amount of item and block IDs. This simply allows for a lot more content. See issue #2460 for example.

## Mod Details
* Name: NotEnoughIDs
* CurseForge Link: https://minecraft.curseforge.com/projects/notenoughids

**Comment by monodemono** [comment]
This is already being considered. The problem with it is it can cause world corruptions, but these issues are being worked on, and once it's safe to use it'll be added to the pack.

**Comment by Trinsdar** [comment]
A better one would be [justenoughIDs](https://minecraft.curseforge.com/projects/jeid) as it doesn't have those issues.

**Comment by artdude543** [comment]
We're going to look into using JEID for the next major update. But this is not confirmed as we need to heavily test it along with tweaks etc... But I'm going to close this issue as NEID we're not going to touch with a barge pole. But JEID is something in our eyes.
