### ISSUE TITLE
Quark "pistons move t es" causes crash when pushing/pulling Cyclic Redstone Clock

### ISSUE THREAD

**Issue by Bustean** [DarkPacks/SevTech-Ages#3110]
## Bug Report

If the smeltery faucet is activated by a redstone clock and tries to pour molten ender pearls into an ingot cast the game will crash.

## Expected Behaviour

Game crash
## Possible Solution

It may be something on tinker's side, maybe the faucet is forcing something weird when activated by redstone, because right clicking the faucet with an empty hand did nothing. (i'm no modder, i' taking a wild guess) 

## Steps to Reproduce (for bugs)

1.Have a smeltery setup with molten ender pearls, a table and ingot cast 
2.The redstone clock (from cyclic) can be lowered next to the faucet via a sticky piston
3.Activate the piston with a lever such that the clock moves next to the faucet and activates it (upon activation, the game crashes) - It is repeatable
4.I don't know if it is necessary, but the smeltery was already pouring molten ender into a pan cast on a table next to the problematic one

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/26YqSt7a

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0.172 (64bit)
* Launcher Used: Twitch, jar launcher
* Memory Allocated: 6656 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes, HD U D3
* Shaders Enabled: Yes, Sildur's Vibrant Shaders lite

## World Information

* Modpack Version world created in: might be 3.0.7, if not 3.0.8

* Additional Content Installed: I remember installing some extra mods that did not work, but they're not in the mods list (perhaps the update from 3.0.7 to 3.0.8 removed them)

**Comment by monodemono** [comment]
I'm unable to recreate this behavior...

<img width="1920" alt="screen shot 2018-07-21 at 14 52 36" src="https://user-images.githubusercontent.com/1161277/43040326-fb73aa10-8cf5-11e8-98cb-7428e9e03ed8.png">

However upon reviewing the crash log, it looks to me more like it's just an issue between the redstone clock and the piston. After experimenting a bit, I did also manage to induce a crash using just sticky pistons and redstone clocks, without using a smeltery at all.

https://gist.github.com/monodemono/4e8307388df521018141636f48a540ac

I'll forward this report to the cyclic github.

**Comment by monodemono** [comment]
Scratch that. Tested it in a pack with just Cyclic, and I immediately noticed that redstone clocks interact with sticky pistons differently. It's likely something that's already fixed within the mod, and just required a mod update, which is already present in the next pack update. I'm going to test this later with the development build of the pack just to make sure, but I think this issue is already resolved.
