### ISSUE TITLE
Whittled fire sticks don't work in multiplayer

### ISSUE THREAD

**Issue by Lolgast** [DarkPacks/SevTech-Ages#3111]
## Bug Report
I'm trying to light a fire under my kiln/grate on a multiplayer server, but I just can't get it to work. I've tried lighting a fire on other surfaces (low grade charcoal, grass, cobblestone), but that won't work either. To eliminate silly mistakes, I also tried making a fire in singleplayer, but I didn't have any issues there. I'd almost think it would be a server issue, but I've tried on 2 servers. Additionally, though I haven't checked for the first server, nobody seems to have problems on the second server I tried. Another user teleported to me and was able to light a fire without problems at the same place I was trying to set fire to/.

## Expected Behaviour
A fire starts after using whittled fire sticks.

## Steps to Reproduce

1. I take a whittled fire sticks in my offhand and one selected on my hotbar
2. I rightclick on the block I want to set fire to
3. The (or at least, an) animation plays which seems correct to me
4. No fire is lit and the whittled fire sticks are not consumed

## Logs

* Client/Server Log: https://gist.github.com/Lolgast/3c14ea88b0c297135c497c9508b38acc

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_171
* Launcher Used: ATLauncher 3.2.3.10
* Memory Allocated: 4096 MB
* Server/LAN/Single Player: Server (Brierie and KingdomsCity)
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: According to the site, KingdomsCity is running the latest SevTech version

* Additional Content Installed: None

**Comment by artdude543** [comment]
This has been working fine for ages. With both servers, we test one and play one. Including Streamers are having no issues on _correct_ servers. 9/10 this turned out to be an issue with these custom servers changing settings or having grief prevention turned on. (One being disabling fire creation) you'll need to talk to the server owners/support.

This is not anything we can solve/change.

**Comment by Lolgast** [comment]
Update: I've actually been able to fix this. Turns out, connecting directly to the sevtech server rather than the lobby, and then going to the sevtech server fixes it. Not sure why this would be a problem, but if anyone else has this problem, you can try this.
