### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Renatas14** [DarkPacks/SevTech-Ages#3112]
Hey, my books (totemic) and achievements always in english... i googled just every site but didn't found anything usefull. This guy have everything in russian https://www.youtube.com/watch?v=Gzb3Gwk5ovY (7:19) i found wiki in russian but i want it in game... well tried find config there i can change text but didn't find it.

**Comment by artdude543** [comment]
Do you change your language for the game? Or your System? This is an issue not for the tracker either.

**Comment by Renatas14** [comment]
All devs,moderators turned off private messages and community can't answer 1day already, great "CLOSED"

**Comment by Tahakk** [comment]
Wow, a whole day, outrageous!
Go and use Discord if you want answers. Jeez

**Comment by Renatas14** [comment]
I meant discord didn't answered whole day so i was confused who im supposed to ask. But today again asked and someone replay.
