### ISSUE TITLE
Actually Additions Rice unabled to be processed properly.

### ISSUE THREAD

**Issue by Sinxar** [DarkPacks/SevTech-Ages#3113]
## Bug Report

Actually Additons rice is unable to be processed in some machines. Instead an unobtainable form of Rice from Better With Addons is listed.

## Expected Behaviour

Actually Additions rice to be processed in the machines.

## Possible Solution

I think this is just a recipe issue, however I cannot say for sure. I have attached pictures to show what I am talking about.

## Steps to Reproduce (for bugs)

Look in JEI on how to process Rice from Actually Additions. You will see it can only be ground with Horsepower machines or the Better With Mods grinder. However if you continue, look at the Rice Dough. then go back a step. It is listing the Better With Addons Rice Stalk to be processed in the expected machines but as far as I am aware it is unobtainable.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0 update 171
* Launcher Used: Twitch
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: 

This images show the unobtainable rice taking the spot of the Actually Additons rice.
![2018-07-16_12 25 35](https://user-images.githubusercontent.com/3210315/42771273-a5809a6e-88f4-11e8-88b7-76cedc6e3ffe.png)

![2018-07-16_12 25 27](https://user-images.githubusercontent.com/3210315/42771289-b2bd765c-88f4-11e8-8eb8-0ceeea894c4d.png)

**Comment by artdude543** [comment]
This is resolved for 3.1.0 :)
