### ISSUE TITLE
Adwind Found in Sevtech

### ISSUE THREAD

**Issue by beewyka819** [DarkPacks/SevTech-Ages#3116]
I was using the FixMe Stick to clean out my computer, and it appears that it found the Adwind malware within one of the mods in Sevtech (this malware seems prevalent in the Minecraft modding community). It doesn't say which mod specifically. 

Here's an image of the results: https://imgur.com/gallery/LVJyzxc

This is serious as the malware can install itself onto other jars in the pack given time. I'd recommend finding which mod is infected and seeing if you can find another copy of it without the infection or a similar mod without it (or you can contact the mod author).

**Comment by beewyka819** [comment]
It says that it's in the backups, so hopefully this was just in an older version, and not in the newer? Wouldn't hurt to make sure though

**Comment by artdude543** [comment]
This has pretty much nothing to do with us. Your all tells you the file with the issue. This would need reporting on Curse as all but a few of the mods are pulled from Curse. *ALL* files uploaded to Curse are put through vigorous file checks/scans and checked by humans after the backend processes it.

We can't control that process. The mods we pull/upload ourselves also go through a similar process. If this was a file in your backups. Then it's way out of our control as you may just have malware on your own PC which is affecting other files.

But thanks for your post and _some_ details_ but this is something out of the scope we can control or debug. When we perform our own checks before uploading any modpack update.

**Comment by beewyka819** [comment]
Hopefully it is what you said and it just spread from something else on my PC. either way it should be gone now. But yeah I only get mods/modpacks from Curse so it seems to be a slipup with their system. Hopefully its been on my PC from awhile ago and they fixed it since then. I'm also sorry for the lack of details, that's all I had.
