### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by xRavingBanana** [DarkPacks/SevTech-Ages#3118]
## Bug Report
 Game crashes shortly after putting cobble stone into a clay kiln

## Expected Behaviour
 i put a piece of cobble stone into the clay kiln and a few seconds later the game crashes

## Steps to Reproduce (for bugs)

1. Place cobblestone in fired clay kiln
2.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/dZdNqCCy

## Client Information

* Modpack Version: 3.0.8
* Java Version: Version 8 Update 171
* Launcher Used: Twitch
* Memory Allocated: 8gb
* Server/LAN/Single Player: Single player
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: Created in version 3.0.8

* Additional Content Installed: None

**Comment by ktylhy** [comment]
how to fix this?!

**Comment by xRavingBanana** [comment]
Ktylhy, I figured one way to fix this, and that’s to stop using twitch launcher and use atl launcher, I’ve had no problems since switching

**Comment by artdude543** [comment]
Will be fixed when 3.1.0 lands 😄

**Comment by ktylhy** [comment]
Ok, but I use TLauncher and don't have Minecraft license D:

**Comment by artdude543** [comment]
Then you won't get anymore help. Buy the game.
