### ISSUE TITLE
Immersive Petroleum Motorboat - upgrades not working

### ISSUE THREAD

**Issue by RoyalSertr** [DarkPacks/SevTech-Ages#3120]
## Bug Report
Immersive Petroleum Motorboat does not properly use upgrades (Emergency paddles., Expanded Fuel Tank etc.). You can add them through Engineer's Workbench, but when the boat is placed in the world, the default is used instead of upgraded.

Oddly enough, if you pick up the boat (Shift+Right click?), the upgrades show on the model. But as soon as you put it back down, the upgrade graphic disappears.

## Steps to Reproduce (for bugs)
1. Put Motorboat into Engineer's Workbench and add any upgrades
2. Place boat into the world.

Latest version (3.0.8)

**Comment by Martok88** [comment]
I'm also experiencing this issue in Sevtech Ages 3.0.8, however the upgrades seem to work fine in creative mode for some reason.
