### ISSUE TITLE
Suggestion - add Pam's HarvestCraft

### ISSUE THREAD

**Issue by RoyalSertr** [DarkPacks/SevTech-Ages#3121]
## Context
Suggestion - add mod Pam's HarvestCraft

Reason: The modpack includes Cooking for Blockheads. Without HarvestCraft, its cooking utensils and ingredients, the cooking feels empty and missing a lot of options. I feel like during Age 4, you should be able to make fancy efficient food (soups, full meals, ...) without using the cauldron.

## Mod Details
* Name: Pam's HarvestCraft
* CurseForge Link: https://minecraft.curseforge.com/projects/pams-harvestcraft

**Comment by artdude543** [comment]
This mod was never planned for the pack the from the getgo. It won't be added in future versions either.

But thanks for the suggestion!
