### ISSUE TITLE
Stuck in Age 0

### ISSUE THREAD

**Issue by TKDWarrior** [DarkPacks/SevTech-Ages#3125]
## Bug Report

Last night before logging off my friend and I completed the "let's get down and melty" progress achievement for age 0 and unlocked age 1.  We got the big announcement, fanfare etc.  That seemed like a good point to call it a night. When I logged on today I am still stuck in age 0.  In the L menu i have the age 1 tab unlocked, but if I type "/gamestage info" it says "zero, tutorial, zero_mob" and I don't have access to any of the age 1 recipes.  The one and only achievement that I haven't finished from age 0 is the boss fight. 

## Expected Behaviour

I should have access to age 1 items, instead, I have the age 1 tab under the "L" menu, but cannot access any of the recipes required to get the achievements such as aqueducts or the standard crafting table.

## Possible Solution

no idea

## Steps to Reproduce (for bugs)

1. Finish achievements to get to age 1
2. Get excited by all the new possibilities
3. decide to pick it up again tomorrow and go to bed
4. log on the next day and be really disappointed when you can't do anything new or access age 1 content

## Logs

* Client/Server Log: https://gist.github.com/TKDWarrior/5fe6255674406934343def6021003fea
* Crash Log: no crash occurred

## Client Information

* Modpack Version: 3.0.8
* Java Version: Version 8 update 171
* Launcher Used: Twitch
* Memory Allocated: 6 Gb
* Server/LAN/Single Player: Single player, open to LAN when my friend wants to join but same problem either way
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 

* Additional Content Installed: none

**Comment by artdude543** [comment]
Sadly this is not a pack issue. LAN is known in the world to cause more issues than solve. Reading this seems your save data was made corrupt. Anything could have done this.

To give yourself the stage use the commands in the game.

`/gamestage add @p one`

But apart from that and/or switching to a dedicated server which we push for this pack. We can't prevent this kind of thing from happening.
