### ISSUE TITLE
Soul Sand in filtered hopper not working

### ISSUE THREAD

**Issue by Warzer1** [DarkPacks/SevTech-Ages#3126]
## Bug Report
when you put sand in a soul sand filtered hopper (better with mods) it doesn't accept the sand and thus does not create soul sand

## Expected Behaviour
for soul sand to be created

## Possible Solution
none yet

## Steps to Reproduce (for bugs)

1.setup a better with mods hopper
2.add filter material soul sand
3. add sand

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version:3.0.8
* Java Version:1.8.171
* Launcher Used:twitch
* Memory Allocated: 7gb
* Server/LAN/Single Player: Server
* Optifine Installed:no
* Shaders Enabled:no

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version: 1.8.171
* Operating System: linux
* Hoster/Hosting Solution: https://www.minecraft-hosting.pro
* Sponge (Non-Vanilla Forge) Server:

**Comment by NarimaanV** [comment]
I'm having the same problem in Sevtech 3.0.8 Age 3. How is this considered a support request? There's an explicit recipe in the game (recipe 21/21 in the filtered hopper recipe list) that isn't working.

**Comment by monodemono** [comment]
Because including you there is now only two people in over one million downloads who have had this issue. Especially considering the fact that 3.0.8 has been out for over two months now and everyone has been able to progress past this point just fine.
