### ISSUE TITLE
Caveman Hate Tree! Stuck at 1/2 On MMP

### ISSUE THREAD

**Issue by Tylerun** [DarkPacks/SevTech-Ages#3127]
Expected Behavior
Have had 8 different users test this issue on our server. Clean server install and issue persisted where we could not complete the aforementioned advancement of "Caveman Hate Tree!"  Strange issue where it works single player but will not allow advancement in server environment. Does anyone have any ideas or previous experiences where it will not work so i can start to narrow it down? 

## Client Information -Many Clients Varying settings. 
* Modpack Version: 3.0.8
* Java Version: 8 Update 161
* Launcher Used: Twitch
* Memory Allocated: Server 8GB
* Server/LAN/Single Player: Server
* Optifine Installed: False
* Shaders Enabled: False

## World Information
* Modpack Version world created in: 3.0.8 
* Additional Content Installed: Plugins: Bstats, Catclearlag, Griefprevention, luckperms, magibridge, nucleus, placeholderapi, playerglow, tabmanager, and worldedit all latest. 

## Server Information
* Java Version: 8 Update 161
* Operating System: Windows 10 Pro
* Hoster/Hosting Solution: Private -BungeeCord
* Sponge (Non-Vanilla Forge) Server: Sponge = Yes latest

**Comment by artdude543** [comment]
Spong has some issues with advancements. But as this is a Sponge server we don't offer support from the pack devs. So I would advise on asking someone on the Sponge Forums/Discord for support on this matter.  In a plain Forge server, all events/advancements work fine. So we know for a fact it's an isolated issue with Sponge and/or Plugins used.
