### ISSUE TITLE
Croup-riding wolfs

### ISSUE THREAD

**Issue by DavidSarif** [DarkPacks/SevTech-Ages#3128]
## Bug Report

When you use sitting domesticated wolf (from minecraft) as horse power, it's riding in circles on its croup. It looks funny but annoying. If I use standing domesticated wolf as horse power, it will only run after me and break the lead.

## Expected Behaviour

Domesticated wolf stands up and runs in circles.

## Possible Solution

Maybe make new status for domesticated wolf when it is used as horse power: standing and running, but not chasing master.

## Steps to Reproduce (for bugs)

1. Find and domesticate wolf with bones.
2. Use lead on this wolf.
3. Attach at horsepowered grindstone.
4. Sit the wolf down.
5. Put wheat in grindstone.
6. See and laugh.

## Logs

No log errors encountered. It's just unintended interaction between mods and vanilla minecraft.

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_171
* Launcher Used: ATLauncher
* Memory Allocated: 6 Gb
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in:
near 8 of July 2018

* Additional Content Installed:
No

**Comment by artdude543** [comment]
This is just how it works. And the interaction, not a whole lot can be done about this. Nor it's worth the dev putting time into "patching" a minor "quirk".
