### ISSUE TITLE
Game crashes breaking chisel n bits block

### ISSUE THREAD

**Issue by wiblu** [DarkPacks/SevTech-Ages#3129]
## Bug Report
I was using Mercury stone from galacticraft to create chisel n bits blocks and when i tried to break the block using a pickaxe ( from tinkers) minecraft crashes.

## Expected Behaviour
Should be able to break and pick up block like others.

## Steps to Reproduce (for bugs)

1.Chisel n bits some Mercury stone
2. Try to break said mercury stone with pickaxe

## Logs

* Client Log: https://pastebin.com/HBzA0Ttj

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0.171(64bit)
* Launcher Used: Twitch
* Memory Allocated: 4.5G
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.7

* Additional Content Installed: none

**Comment by artdude543** [comment]
@MJRLegends is this an issue on your side or Chisel Bits?

**Comment by MJRLegends** [comment]
Does the bits for Mercury Stone show in the creative tab or/and JEI?

**Comment by MJRLegends** [comment]
Also does blocks from the Moon or Mars do the same thing and cause a crash?

**Comment by wiblu** [comment]
Mercury Stone bits show up in the creative tab.
Game doesn't crash if i break the structure in creative mode but does when i switch back to survival.
it crashes the instant i click it to mine it, doesn't matter what i use pick, shovel, empty hand it crashes
Moon and Mars blocks cause crash too.
Happens in both server world and single player.

**Comment by wiblu** [comment]
Also made up a custom modpack with galacticraft, planets and chisel & bits straight from the sevtech folder so its the same versions and this wouldn't cause the crash when mining the bits.
not sure if this info helps or not

**Comment by MJRLegends** [comment]
Please report to chisel & bits, and let me know if its something im doing wrong to let me know i will happily with them

**Comment by AlgorithmX2** [comment]
The build I sent you shares the same version number as the current release, however release 14.20 will be the version that contains the final published fix for the crash.

**Comment by artdude543** [comment]
Will be fixed in the update included in 3.1.0
