### ISSUE TITLE
Tinkers tank bugging/deleting mass quantities of fluids.

### ISSUE THREAD

**Issue by SkullDood** [DarkPacks/SevTech-Ages#3130]
## Bug Report
 After filling the tinkers tank with over 80 buckets of diesel the volume of the diesel suddenly disappeared and only its name is visible. There is no way to extract the diesel. 
 

## Expected Behaviour

 The volume of every other fluid in the tank is visible, and the large amount of space the diesel took up is now a small sliver in the tank.
What it should look like when I hover over with mouse: 
![work](https://user-images.githubusercontent.com/12023361/42915936-a28f7432-8ad0-11e8-970b-620ed90e456f.jpg)

What it looks like now: 
![no work](https://user-images.githubusercontent.com/12023361/42915941-a7f22942-8ad0-11e8-8f4e-4b711ed6dbbe.jpg)

## Possible Solution
 None

## Steps to Reproduce (for bugs)

1.Fill tinkers tank with fluid using fluid transport pipes from an oil distillery.
2. 

## Logs
 
[latest.log](https://github.com/DarkPacks/SevTech-Ages/files/2207861/latest.log)

## Client Information

* Modpack Version: 3.0.8
* Java Version:
* Launcher Used: Twitch
* Memory Allocated: 11GB
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
 3.0.8
* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
I tested this on a server, and could not reproduce the issue. All fluids going in was correct and when pulling out to machines/pipes are also correct. Even tried to make a loop bug but that also passed the test.

Seems like a one-off issue. Or a machine/pipe was using the fluid which your unaware off? But I can't reproduce the issue based on your report along with trying to abuse known fluid loop bugs.
