### ISSUE TITLE
Unable to progress stages/gain achievements after transferring Singleplayer world to Server and then back to SP

### ISSUE THREAD

**Issue by BaneOfHades** [DarkPacks/SevTech-Ages#3131]
## Bug Report

Created a Single player world, then moved the world file to a server. Played with friend on server (got to age 3). At this point I tried to transfer the server world back to a Single-player (with the intention of playing on Lan). This put me in the positon (and inventory) that I left off at the time the world was transferred to the server. The advancements page still shows me in Age 3, but I am locked into age 1, and unable to gain any achievements/ progress ages. 

I tested by opening to Lan, and my friend is able to log on in the place he was on the server. I also tested running from his account, and in that case he is put in the original position, and I am able to log on properly.

Together Forever commands don't seem to change anything either.

## Expected Behaviour

Should log me in in the position I was in the server, and allow advancementsprogression

## Possible Solution

I believe there is some client-side player data I need to delete to get it to work properly, but am unable to find it
## Steps to Reproduce (for bugs)

1. Create new Single-player world
2. Transfer the world file to a server
3. Log onto server and gain achievments/ change stages
4. transfer server world file back to singleplayer
5. Log onto world

## Logs

* Client/Server Log: https://pastebin.com/RKFGCvnz
* Crash Log: 

## Client Information

* Modpack Version: 3.0.8
* Java Version:
* Launcher Used: Twitch
* Memory Allocated: 3072 MB
* Server/LAN/Single Player: Server/Lan
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None

## Server Information
* Java Version: 
* Operating System: Windows
* Hoster/Hosting Solution: Local Host
* Sponge (Non-Vanilla Forge) Server: No

**Comment by artdude543** [comment]
So this is not a pack issue. But a _you_ issue in regards that you've missed folders/files from the server instance when copying down to your client.

You need to make sure **all** files/folders are copied over. Even ones outside of the world folder on the server side. Also, LAN is not recommended at all if your wanting to play with friends. Stick to using a dedicated server. You'll run into the endless bugs/issues LAN has (inherited from Vanilla bugs)

But if you want to stick to LAN make sure you copy all files/folders and your good. I've tested this now and it worked fine.
