### ISSUE TITLE
Crash when interacting with the AS book

### ISSUE THREAD

**Issue by DocteurSamo** [DarkPacks/SevTech-Ages#3133]
## Bug Report
 Simple crash, the game just shut down when I press R to see the recipe of the starmetal ore, or see the chapter Attunement in the Astral Sorcery in the book. This crash prevent the continuation of the purple advancement, because I can't know how to create the starmetal. 

Edit: I restart my game a lot to test  when i crash, and i see that i now crash when i open the advancement page 2, especially after I did the starlight altar upgrade advancement. I suppose that my game crash when he try to render an item from twilight forest.

## Logs
This crash report is especially when i try to open the Attunement chapter 
* Crash Log: https://pastebin.com/D4nwQvpP

## Client Information

* Modpack Version:3.0.8
* Java Version: 1.8.0.171 (64 bit)
* Launcher Used: Launcher Jar
* Memory Allocated: 6G
* Server/LAN/Single Player:Single player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8
*  No Additional Content Installed
* World in realistic.
* In age 2

**Comment by Monkeyman42001** [comment]
I have the exact same problem, which caused me to end up giving up on my world because i couldnt advance any further. hopefully they will fix this soon
