### ISSUE TITLE
Server crashes when anyone tries to join, and you get disconnected. (internal exception java.io.ioexception)

### ISSUE THREAD

**Issue by toffeln** [DarkPacks/SevTech-Ages#3134]
Bug Report: Disconnected from server, and the server crashes when anyone tries to join, we played less than 14 h ago wtihout problem.
We're just about to enter Age 2.

internal exception java.io.ioexception

Expected Behaviour: Join without disconnection
Possible Solution: None
Steps to Reproduce (for bugs)

Logs

    Client/Server Log:  https://pastebin.com/8wBMzPsZ
    Crash Log: https://pastebin.com/8wBMzPsZ

Client Information

    Modpack Version: 3.0.8
    Java Version: Newest 181
    Launcher Used: Twitch
    Memory Allocated:  8GB
    Server/LAN/Single Player: Server Online, direct connect IP
    Optifine Installed: no
    Shaders Enabled: no

World Information

    Modpack Version world created in: 3.0.8

    Additional Content Installed: None

Server Information

    Java Version: Newest Java 181
    Operating System: Windows 10
    Hoster/Hosting Solution: ?
    Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
Thank you for reporting an issue!

It appears you are logging an issue for a crash, but you have either not uploaded to PasteBin/Gist etc.. of the actual crash report. This report contains the needed data to help to locate the cause and a possible fix. To find the file needed please review the following for either of the launchers.

## Twitch
1. Select the SevTech Pack to view the modpack page.
2. Click the `...` button on the top right just next to `Get More Content`.
3. Click `Open Folder`.
4. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it. 

## ATLauncher
1. Select the Instances tab, then scroll to the instance of SevTech.
2. Click the bottom right button named `Open Folder`
3. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it.

For any other launcher should be a similar process, if not consult with Google if you are not sure on how to find the folder. The information contained in these reports is critical for getting the crash fixed/looked into.

## Servers
For servers the process if farilt simple. Go the folder cotaining all the sever files/folder and you will see a folder called `crash-reports` follow the same process as above by getting the lastest one and uploading it to a text store.

**Comment by toffeln** [comment]
I'll get to it and send the right crash report soon
