### ISSUE TITLE
Fishtraps, bug, didn't create any, can they spawn?

### ISSUE THREAD

**Issue by toffeln** [DarkPacks/SevTech-Ages#3138]
Just an quick question.
We hade the bug with the fishtraps causing the game to crash.
But we haven't built any fishtraps, can they spawn in themselfs, like in villages and so on?
Our backup didn't work either.
All this is really confusing and we're glad you're taking your time to look into our problem!

**Comment by artdude543** [comment]
I already said what you can do in the issue I closed. Don't make another issue...
