### ISSUE TITLE
Gamebreaking Actually Additions "Easter Egg"

### ISSUE THREAD

**Issue by TheVeyra** [DarkPacks/SevTech-Ages#3140]
## Context

There is a small chance to obtain any item in the game via the Actually Additons Atomic Reconstructor. This.. "easter egg"... will be most likely available in any 1.10+ pack with the mod. If you right click the Atomic Reconstructor 500 times with the "11" music disc, it will get the Lens of Disruption which will generate completely random items for energy. More info at the bottom of [this page](https://ftb.gamepedia.com/Atomic_Reconstructor). There is also a [Reddit post](https://www.reddit.com/r/feedthebeast/comments/6nisuv/atomic_reconstructor_lens_of_disruption_is_this_a/) with a small comment from the AA dev about it. Already had a user on my server obtain creative energy cells which he used to power the reconstructors to make more items.

## Config/Script Details
* Config Line:
\# 11?
I:"What is 11"=11
Not sure how to work it though.

**Comment by artdude543** [comment]
Thank you for the report. This will be changed in the config to disable the ability for it to work.
