### ISSUE TITLE
Magic Map shows nothing on map

### ISSUE THREAD

**Issue by ichimo** [DarkPacks/SevTech-Ages#3143]
## Bug Report
When activating the magic map it creates the map but shows no picture or icons for the surrounding in the twilight for hills or dungeons

## Expected Behaviour
Map does not show anything on the map when created

## Steps to Reproduce (for bugs)

1.Get Magic Map and activate it in overworld or twilight

## Logs
I couldn't find anything in the logs saying there was something wrong

## Client Information

* Modpack Version:3.0.8
* Java Version:8 update 151
* Launcher Used:ATLauncher
* Memory Allocated:6Gb
* Server/LAN/Single Player:Server
* Optifine Installed:Yes
* Shaders Enabled:No

## World Information
* Modpack Version world created in: 3.0.8

**Comment by artdude543** [comment]
This is a bug with TF you need to load the map in the dimension. Log out and back in again. If you take the map back to the Overworld. When you come back to the TF you need to relog again. It's an issue with switching dimensions.

So leave the map in the TF when you switch back. It will save on the re-logs :)

**Comment by ichimo** [comment]
Relogged, switched DIM, came back, Relogged.  It doesn't work.

**Comment by artdude543** [comment]
That's the fix given from the TF. Otherwise, you'll have to wait for the update which perma fixes the issue.
