### ISSUE TITLE
Bronze sword requires copper plates

### ISSUE THREAD

**Issue by Jersh** [DarkPacks/SevTech-Ages#3144]
AS title says, no recipie for copper sword in age 1, bronze sword requires copper plates.

[https://imgur.com/a/Mill2Tq](url)

**Comment by artdude543** [comment]
Really? Not even going to bother finding the fixed issue as you clearly did not bother searching before hand.

**Comment by Jersh** [comment]
My bad, I searched but I was using the default is:open flag
