### ISSUE TITLE
while using server the advancements page is broken please help even creating a brand new server has not worked

### ISSUE THREAD

**Issue by Shadow6751a** [DarkPacks/SevTech-Ages#3146]
when I hit l for the advanements page it says "there does not seem to be anything here... :("
I have tried making a single player world and it worked in single player but when I transferred it to the server the advancements still did not work I even cleared the server of worlds and it still would not work please help
heres what it looks like when I open the advancements page
<img width="839" alt="capture" src="https://user-images.githubusercontent.com/41488029/43020131-01f58e22-8c2d-11e8-830b-7596aa502be0.PNG">
edit I created a brand new server and the advancements were still broken

**Comment by artdude543** [comment]
Your server install is broken. Use the files we provide on Curse. You can find it via Google.
