### ISSUE TITLE
Waterwheels drop 2 waterwheel items when broken

### ISSUE THREAD

**Issue by somepeoplejustwanttocode** [DarkPacks/SevTech-Ages#3153]
## Bug Report

Breaking a Better With Mods waterwheel, placed on an axle, drops 2 waterwheel items and the axle.

## Expected Behaviour

Breaking the waterwheel gives you 1 waterwheel item and the axle it is placed on.

## Steps to Reproduce (for bugs)
1. Place down an axle
2. Place a waterwheel on the axle
3. Break the waterwheel

## Logs
* Client/Server Log: https://gist.github.com/somepeoplejustwanttocode/7bdd971c7a1b0a39883b22bfaa7c0c59 (probably should be warned its 2MB with ~16000 lines, most of which is just the game loading)
* Crash Log: (n/a: bug doesn't cause crash)

## Client Information

* Modpack Version: 3.0.8
* Java Version: 8 update 171 (build 1.8.0_171-b11)
* Launcher Used: Twitch App
* Memory Allocated: 5888MB
* Server/LAN/Single Player: Single player
* Optifine Installed: False
* Shaders Enabled: False

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: false

**Comment by artdude543** [comment]
This is already fixed. And there is an issue for it already. Use the search feature....
