### ISSUE TITLE
Game crashes during start-up

### ISSUE THREAD

**Issue by Twilight-Ember** [DarkPacks/SevTech-Ages#3156]
## Bug Report
On start-up just after launching Sevtech it crashes, I had no previous issue loading my game file, but seemingly randomly it just stopped booting up from the launcher, it gets about 5 minutes in and crashes. It's a soft crash back to the launcher menu, but it always fails to load the game. Seeing as how the game isn't effected if I boot up a new file, I'm not sure if one of my files is broken. 

## Expected Behaviour
Launch Sevtech from the launcher, loads about half way, then crashes back to the launcher.

## Possible Solution
I can temporally "FIX" my save by launching a new file from the launcher and then transferring my files over to the new save before loading my save file world. Game play is not effected past this point as everything will then run just fine, but once the game is closed the whole process has to be repeated.

## Steps to Reproduce (for bugs)
Since I don't know what the problem is so I'm unsure as how to recreate it, sorry

## Logs
Crash Log: [HERE](https://gist.github.com/Twilight-Ember/d2fe2da7dfd2f85149a61104ab916b95)

## Client Information
*    Modpack Version: 3.0.8
*    Java Version: jre1.8.0_172
*    Launcher Used: twitch
*    Memory Allocated: 5GB
*    Server/LAN/Single Player: Single Player
*    Optifine Installed: no
*    Shaders Enabled: no

## World Information
*   Modpack Version world created in: 3.0.4
*   Additional Content Installed: None

**Comment by artdude543** [comment]
You have corrupt config files. Re-install the entire pack and try again. You're also using an old version of Java which will cause other crashes. If your using the Twitch Launcher follow this guide: https://docs.google.com/document/d/e/2PACX-1vR5muyi1m7Zy_qSwrzeb9e3tbbRlksguNUb_Pvm3pn9eDpsIkUj5qQUq6WFPPdEoVWZq91WvvH57KzC/pub For the other launchers just update your Java on the System and change the Java version they are using via the launcher settings.
