### ISSUE TITLE
Crash after startup

### ISSUE THREAD

**Issue by ziat007** [DarkPacks/SevTech-Ages#3169]
### Bug Report
The game crashes immediately after it loads up to the title screen.
I have changed nothing that should be effect the game from the previous launch. (nVidia drivers are same, Java is same, Windows was not updated as far as I know {Win10})
I have tried rechecking the Minecraft profile.

### Logs

[crash-2018-07-24_21.56.24-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/2225148/crash-2018-07-24_21.56.24-client.txt)

### Client Information
Modpack Version:3.0.8
Java Version: 1.8.0.181 (64 bit)
Launcher Used: Launcher Jar
Memory Allocated: 11G
Server/LAN/Single Player: Irrelevant
Optifine Installed: No
Shaders Enabled: No
Launcher: Twitch

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
