### ISSUE TITLE
Shoggoths Break progression

### ISSUE THREAD

**Issue by bane2571** [DarkPacks/SevTech-Ages#3172]
There are a few issues along this line but this is specifically about the fact that Shoggoths post acid spit update (from my point of view) make the mod pack progression block at the end of age 1 without cheating.

## Bug Report
The shoggoth acid spit ability does excessive damage and seems to pass through walls. Because of this, coupled with the requirement to have 6 present to summon a statue, it is impossible (in my experience) for even multiple players to acquire Statues with age 1 equipment, thereby causing progression to stall in Age 1.

On top of this, the mob griefing of acid spit means that any shoggoth spawning near a home base can completely ruin your day.

## Expected Behaviour
Shoggoths, while difficult, should be defeatable in Age 1 and it should be possible to clear a lair with 6 shoggoths.

## Possible Solution
Disable acid spit on shoggoth

## Steps to Reproduce (for bugs)
1. Find Shoggoth lair
2. Attempt to remove a statue from the lair
3. Die. a Lot.

Some proposed solutions that don't work:
Move up to the shoggoth so they don't spit - there are 6 shoggoths, 1 will always spit.
Farm the flesh - in principle this works but it is incredibly tedious and does not address the fact that book charging also summons griefing shoggoths.
Tunnel under the shoggoths - we tried this and it seemed to work but the constant acid spam destroyed the statue so we got nothing.
Shoggoths won't shoot at eye level, only foot level - this works until the ooze builds up, then the shoggoth are on multiple levels.

## Logs
N/A

## Client Information
N/A

## World Information
* Modpack Version world created in: Current version (downloaded 20/07/18)

I realise this ticket is basically just griping but it took us a full night of 3 people dying repeatedly and we managed to get out with no statue and 8 flesh. In the end we have agree that any new statues are spawned in by creative and mob griefing is permanently disabled on our server. This is just to make the mod pack playable, otherwise we would have stopped playing entirely.

**Comment by monodemono** [comment]
There's 3 ways of obtaining statues, and 2 ways to fight Shoggoths.

Obtaining statues:
1. Get 6+ shoggoth outside on dry land in a group, and they will build the statue (you alraedy know about this one as you're complaining about it).
2. Kill some shoggoths to obtain their flesh, and obtain some monolith stone by mining it from their lair, and craft the statues.
    a. Killing shoggoths is made much easier by luring them out one by one and using a shield, it completely blocks their acid spit attacks.
    b. If you stay close enough to a shoggoth they won't spit, they can't attack directly below themselves, and water slows them down. Just stay close, dive under, hit them, and then swim back and up for air, and you can easily kill them.
3. Just mine away some chunks of the lair carefully (a shield helps) you can trade them in at a Farming for Blockheads market for shoggoth flesh, and use that with some leftover monolith stone to make the statues without ever having to fight the shoggoth directly.

If you would have just checked your JEI recipes, you could've figured out on your own.
