### ISSUE TITLE
Better With Mods water wheel duplicates when broken

### ISSUE THREAD

**Issue by olabgaming** [DarkPacks/SevTech-Ages#3180]
The water wheel drops 2 wheels when broken.

**Comment by monodemono** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by olabgaming** [comment]
My apologies. The template you mention did not appear when adding the post.
Only a message requesting to ensure that the bug hasn't been posted
already. I did not intentionally ignore nor deliberately delete anything as
you assumed.

**Comment by monodemono** [comment]
Well you ignored that message too because the thing you're reporting has been posted multiple times already anyways.

This is the last reply you'll get on this matter.
