### ISSUE TITLE
Server Crashing on Load

### ISSUE THREAD

**Issue by Ninjawolf0007** [DarkPacks/SevTech-Ages#3181]
## Bug Report
The server gets through pre-initialization however, it gets to this point:

`[17:24:22] [Server thread/INFO] [contenttweaker]: Module Vanilla CraftTweaker has successfully loaded
[17:24:22] [Server thread/INFO] [contenttweaker]: Module Materials has successfully loaded`

## Expected Behaviour
The server should start fine.

## Steps to Reproduce (for bugs)

1. Start the modpack server 

## Logs
* Client/Server Log: https://pastebin.com/c9VMn4dK
* More specifically, here is where the actual crash is: https://pastebin.com/uHy8fwg2

## Client Information

* Modpack Version: 3.0.8
* Java Version: JRE1.8.0_181
* Launcher Used: command prompt was used to launch the server
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: None

## World Information

* Modpack Version world created in: 3.0.4 or 3.0.6

* Additional Content Installed: None

## Server Information
* Java Version: JRE1.8.0_181
* Operating System: Windows 10 Home
* Hoster/Hosting Solution: Hosting from a desktop
* Sponge (Non-Vanilla Forge) Server: forge-1.12.2-14.23.4.2707-universal

Similar to: https://github.com/DarkPacks/SevTech-Ages/issues/2542
However, updating the Java version did not help.

**Comment by artdude543** [comment]
You configs are corrupt. Re-Copy/Upload to the server host/files and try again. The error is thrown from one of the JSON files not valid (Aka broke)

Sometimes caused by iffy downloads from Curse. Also, make sure you are using the official server files. But the main issue is broken config files 😄 hope this helps ya!
