### ISSUE TITLE
Modular machinery no recipes / cant make liquids with modular machinery machines

### ISSUE THREAD

**Issue by DrSpghetto** [DarkPacks/SevTech-Ages#3185]
Ive been playing on sevtech ages with my friend and in order to progress we need to make propene, after inputting the naphtha and steam into the chemical mixer (with the blueprint inside) it says no matching recipes found. took a look in the recipes folder just to find it empty.

To reproduce:
1.Make a sevtech ages server
2.Progress to age 3 (propene advancement)
3. Find out your unable to make propene

Game didnt crash nor are there any errors so i think its just the recipes not being there.

Sevtech ages 3.0.8
Mc vers: 1.12.2
Added the veinminer mod (server side only)

--Found out after trying to make propene and troubleshooting the chemical mixer and looked up videos just to find out i did everything right.

* Modpack Version: 3.0.8
* Java Version: Version 8 Update 181 (build 1.8.0_181-b13)
* Launcher Used: Twitch
* Memory Allocated: Allocated 7g RAM to the client (Twitch)
Allocated 6g RAM to the server
 
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

World Information
World was created with the latest version (3.0.8) Downloaded from the server pack in the Files section
* Additional Content Installed: Veinminer (server side)

Server Information
* Java Version: Version 8 Update 181 (build 1.8.0_181-b13)
* Operating System: Windows 10 64-bit
* Hoster/Hosting Solution: My pc
* Sponge (Non-Vanilla Forge) Server: Placed sponge in the mod folder once, then removed it (restarted between modifications and after)

**Comment by artdude543** [comment]
Throwing this one to Discord. The machine **DOES** have recipes. As they are done via CraftTweaker scripts. You must have had something derped up or something. But this is classed as a player/support issue. So will be thrown to Discord. Please follow the response from the bot.
