### ISSUE TITLE
SevTech-Ages Crashes After Upgrading Luminous Crafting Table and trying to open Age 2 Advancement Page

### ISSUE THREAD

**Issue by gamerknoob** [DarkPacks/SevTech-Ages#3186]
## Bug Report
The game is crashing after I upgraded the luminous crafting table in Age 2 and now when I go to open the Age 2 Advancements page it crashes.

## Expected Behaviour
It shouldn't crash

## Steps to Reproduce (for bugs)

Opening Age 2 Advancement page

## Logs
 https://pastebin.com/jQ1bPBPm

## Client Information

* Modpack Version: 3.0.8
* Java Version: Java 8 Update 151 64-bit
* Launcher Used: Twitch
* Memory Allocated: 6,180 MB
* Server/LAN/Single Player: Server
* Optifine Installed: false
* Shaders Enabled: false

## World Information
* Modpack Version world created in: 3.0.8 (I believe)

**Comment by artdude543** [comment]
Duplicate of #3118
