### ISSUE TITLE
Industrial Mill can't Mill Bonemeal

### ISSUE THREAD

**Issue by RedBlockFilms** [DarkPacks/SevTech-Ages#3189]
## Bug Report
The industrial millstone, (the modular machine) can't grind bones into bonemeal

## Expected Behaviour
The industrial millstone should grind bones into bonemeal like the millstone can

## Possible Solution
..fix it?

## Steps to Reproduce (for bugs)
1. Attempt to create bonemeal in the industrial mill
2. Fail
3. Be sad

## Logs
Not needed

## Client Information
Not needed

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: Optifine

**Comment by artdude543** [comment]
Fixed in https://github.com/DarkPacks/SevTech-Ages/commit/6c33333574861468d6b0ed14c0ba1b36fe9132fd
