### ISSUE TITLE
Null pointer render horsepower chopping block

### ISSUE THREAD

**Issue by iamrenan** [DarkPacks/SevTech-Ages#3190]
## Bug Report
When loading my world, minecraft crashes and reports a crash with "se.gory_moon.horsepower". This apparently happened after I crafted the horse powered chopping block.

## Expected Behaviour
Game should load and render the chopping block normally. If there's a way to fix this without removing my save please tell me :(

## Logs

* Client/Server Log: https://gist.github.com/iamrenan/dd5c3f960a4706235c459472f5a02ff7
* Crash Log: https://gist.github.com/iamrenan/297f7e5452d452b69a2705e745506a1a

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_73
* Launcher Used: Twitch
* Memory Allocated: 6444mb
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None

**Comment by artdude543** [comment]
@GoryMoon want me to make an issue on your tracker for this one?

**Comment by xIceFox** [comment]
Maybe you can load the world in MC Edot and remove the horse chopping block out of world/invenrory this should work to rescue your world.
If this doesn't work you can look into the Aroma Backup folder there should be some of your backups

Tip for future: type /backup in chat every 30 minutes so you dont loose all of your gamedata 😊

Have a nice day, 
xIceFox

**Comment by GoryMoon** [comment]
This have been fixed ~10 days ago and uploaded to curse @artdude543

**Comment by artdude543** [comment]
Sweet. That's in the build for beta 3.1.0 :) Thanks for the update!
