### ISSUE TITLE
Advancements reset to zero

### ISSUE THREAD

**Issue by Maple-Kade** [DarkPacks/SevTech-Ages#3193]
Ya so I was in age 4 and was putting in energy cables to replace wires. This was at 7/27/2018 at 2:56p.m. by the way. So I had died a bunch of times to some before I looked at my advancements to see what I could work on. And to my shock it was back at the tutorial age. Though non of th items where reset or unknown. How do i fix this?
## Server Information
* Java Version:1.8.0_51
* Operating System:java
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server: 14.23.4.2707

**Comment by DrSpghetto** [comment]
Stupid question, did you make sure that you're on the right page in the advancements tab? ^^

**Comment by Maple-Kade** [comment]
No all other ages where gone. Leaving me at where one would begin when first playing only with all the items unlocked
