### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by claytertots** [DarkPacks/SevTech-Ages#3194]
## Bug Report
As I load up game crashes

## Expected Behaviour
I expect it to fully load
## Logs
https://pastebin.com/nt9iBbC1

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_171
* Launcher Used: Twitch native launcher and jar launcher
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in:

* Additional Content Installed:

**Comment by artdude543** [comment]
You have broken configs. You need to reinstall the pack.
