### ISSUE TITLE
Can not craft grass fibre mesh! -.-

### ISSUE THREAD

**Issue by azzakanazza** [DarkPacks/SevTech-Ages#3197]
Bug Report:
Pretty simply and pathetically, I and my two friends on my server can not craft grass fibre mesh.

What I've Done So Far:
-restarted server
-redownloaded modpack
-/gamestage add @p tutorial for myself and players, then restarted server and clients
-cried cuz i thought playing a modpack was simple and that they function correctly in the first 3 mintues of playtime

Logs:
Rofl there aren't logs for this, i don't even need to post an image cuz i've seen posts about this exact issue before, but none of the 'fixes' have actually worked which is why i'm making this post.

Client Information:
Most recent client as of 29/7/18, w/ minecraft v 1 12.2

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
