### ISSUE TITLE
Hamburger recipe mismatch

### ISSUE THREAD

**Issue by Lokiare** [DarkPacks/SevTech-Ages#3198]
![screenshot 2018-07-28 23 40 58](https://user-images.githubusercontent.com/1618213/43363027-1592ebfc-92c0-11e8-9d0d-9e0cd61feb1d.png)
![screenshot 2018-07-28 23 42 30](https://user-images.githubusercontent.com/1618213/43363028-17536534-92c0-11e8-8e78-2eba52ce9ce5.png)

The recipe in JEI is different when you go to craft it. It possibly has something to do with the durability of the knife.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by artdude543** [comment]
Wrong issue LEL!
