### ISSUE TITLE
Sevtech Ages

### ISSUE THREAD

**Issue by zaney212** [DarkPacks/SevTech-Ages#3199]
## Bug Report
As I go to open Sevtech Ages, [ERROR]: Game ended with bad state (exit code 1) is displayed in the Launcher Log.

## Expected Behaviour
I expected for the Sevtech Ages pack to load up, yet nothing did.

## Steps to Reproduce (for bugs)
1. Open Twitch 
2. Click 'Play' on Sevtech Ages
3. Login to Java
4. Make sure that the Sevtech Ages profile is selected
5. Click Play

## Logs
* Crash Log: [https://pastebin.com/3Bit5UBN](https://pastebin.com/3Bit5UBN)

## Client Information
* Modpack Version: forge - 14.23.4.2707      Sevtech: Ages - 3.0.8   
* Java Version: 9.0.1 (according to crash log)
* Launcher Used:  Minecraft Launcher unknown (through bootstrap 100) started on osx... (according to crash log) otherwise, Twitch
* Memory Allocated: unknown
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

Thanks,
zaney212

**Comment by justinrusso** [comment]
Please install Java 8 - Forge does not support 9 or above.
