### ISSUE TITLE
Gold detecting with Dowsing Rod and the /oredistribution [3.0.8]

### ISSUE THREAD

**Issue by Ylimess** [DarkPacks/SevTech-Ages#3207]
### Bug Report
I can't find gold when i see gold sample.

## Expected Behaviour
Found gold sample. Searching whit the Dowsing Rod in age 2 but not find gold under. I was reading to fix that but nothing in version 3.0.8. Next i cherche whit the /oredistribution on top of chunck with gold sample but nothing too. I testing it on many chunk with gold sample.

## Possible Solution
I don't know how thats works but if you can find a way to fix it i will be really happy.

## Steps to Reproduce (for bugs)
1-Searching gold sample
2-Take the Dowsing Rod and click every were to find gold
3-Tried /oredistibution to find gold

## Client Information

* Modpack Version: 3.0.8
* Java Version: Version 8 update 181
* Launcher Used: Twitch 
* Memory Allocated: 6144 mo
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by monodemono** [comment]
It's there, just keep looking.
