### ISSUE TITLE
Hydra glitched out, unable to complete

### ISSUE THREAD

**Issue by techdude** [DarkPacks/SevTech-Ages#3208]
## Bug Report

I went to fight the hydra and died on the first attempt. I respawned in the regular world, and I then went to go recover my stuff. When I got back to the hydra, it turned around and it's tail deleted my grave, so I had to look up how to fix that (I used the command /tmg_restore techcaleb latest). When I returned to the hydra after gearing up in the overworld some more, the hydra was missing all its heads, and instead only had a body. In addition, it was taking no damage at all from either ranged or mele sources. Now my progression in the mod pack is halted until I can figure out how to fix the glitch.

Note that it looks like someone tried to report this before, but didn't provide enough info [#issue 3047](https://github.com/DarkPacks/SevTech-Ages/issues/3047).

## Expected Behaviour

I would expect the hydra to still be there, and to be able to fight it.

## Possible Solution

Not sure.

## Steps to Reproduce (for bugs)

I'm not sure if these will work, but as best as I can tell these are the steps I did. 

Here is also a video showing what it looks like after it is glitched (sorry, I wasn't recording during the time leading up to the glitch) - [https://www.youtube.com/watch?v=f_P0NWdFzxs](https://www.youtube.com/watch?v=f_P0NWdFzxs). 

1.  Go fight hydra. Die near the feet (possibly killed by the tail? It felt like a 1 hit K.O. and I have fire protection IV on some leggings).
2. Respawn in the overworld (my twilight forest spawns have always been broken. Usually I spawn at the top of some snow tower in acid rain and I have to quickly open to lan and change the gamemode to creative so I can get out of there, otherwise I end up in a spawn loop. However, this is the first time I've died in the twilight forest and spawned in the overworld).
3. Gear up with armor and a sword and go back to twilight forest to recover grave.
4. When you get there and run toward the side where your grave is, the hydra spins, and it's tail collides with the grave deleting it.
5. Go on top of the dome the hydra is on, and open to lan with cheats enabled so you can use the /tmg_restore command (there was a substantial wait here because I haven't had this happen before and I was searching on the forums to find out if it was even possible).
6. Run /tmg_restore <yourname> latest
7. Return to overworld to get bow and arrows. Craft arrows, and bring infinity bow and baykok's bow.
8. Return to twilight forest and go to fight the hydra again.
9. Hydra is broken when you return.

Note that I have shut down and restarted at least 3 times, so it's not just a display glitch.

## Logs

* Client/Server Log: https://pastebin.com/uzsnhj6H (trimmed down to last 400 ish KB so I can post it on pastebin. should be enough though as this goes back a few days.
* Crash Log: I don't know where this is.

## Client Information

* Modpack Version: 3.0.8
* Java Version: Minecraft 1.12.2
* Launcher Used: Twitch (listed as Forge 14.23.4.2707)
* Memory Allocated: 12GB
* Server/LAN/Single Player: Single Player, sometimes opening to LAN to access creative mode to fix glitches.
* Optifine Installed: I don't think so, unless it is in the modpack.
* Shaders Enabled: Not sure where this is.

## World Information

* Modpack Version world created in: I don't remember the version, but I started playing about 3 weeks ago

* Additional Content Installed: Only this modpack is installed on this computer.

## Server Information
* Java Version: 1.8.0_51-b16
* Operating System: Windows 10 Pro
* Hoster/Hosting Solution: Local
* Sponge (Non-Vanilla Forge) Server: None

**Comment by monodemono** [comment]
> Now my progression in the mod pack is halted until I can figure out how to fix the glitch.

You can just go find another hydra elsewhere.

**Comment by artdude543** [comment]
In regards to the whole _glitch_ this is something which we can't control nor fix. This would need reporting direct to the TwilightForest Tracker someone has already opened an issue with them: https://github.com/TeamTwilight/twilightforest/issues/518 so if you can update that issue with your findings. They can look into it there. But other than finding another Hydra (which won't break your progression at all) there is nothing we can do in regards. But this is not a pack breaking issue also. So on that thought. Thank you for reporting the issue, but as this not pack breaking I'm going to close this off but track the other issue on TF to see if a fix/solution is found in regards.

I could never reproduce this also. So it's an odd one. But thank you for your detail information and using the template. As this helps us and helps mod devs when tracking issues! Feel free to tag me if I've missed something or you get an update in regards 😄
