### ISSUE TITLE
Timeout during first-time install

### ISSUE THREAD

**Issue by Thornxanthos** [DarkPacks/SevTech-Ages#3209]
Apologies, I'm completely new to GitHub and have no idea how to upload logs. The error is fairly simple though. I'm attempting to install the modpack for the first time and it stalls during the install of The Betweenlands with a timeout error message. 

"Timeout attempting to download: https//files.forgecdn.net/files/2555/385/TheBetweenlands-3.3.8-universal.jar"

I've attempted this several times over the last 6 hours to no effect. Kind of stuck on where to go from here.

**Comment by artdude543** [comment]
Not our fault. You'll have to keep trying or contact Twitch/Curse support.

Also thanks for ignoring the template!
