### ISSUE TITLE
YoYo Shear Upgrade Drops Wool

### ISSUE THREAD

**Issue by Rahmiel** [DarkPacks/SevTech-Ages#3210]
Issue: The Shears upgrade for YoYos allows you to shear sheep for wool blocks

Expected Outcome: Getting fleece not Wool Blocks

Steps to Reproduce: Make a Rad YoYo, Hit a Sheep with It, Profit!

I checked the issues and couldn't find this one, not sure if I'm blind but don't tell me I didn't look.

**Comment by monodemono** [comment]
fixed with a5a0eb0
