### ISSUE TITLE
Game Crash While Changing Texture Pack To Faithful 64

### ISSUE THREAD

**Issue by ProWittingSword** [DarkPacks/SevTech-Ages#3212]
## Bug Report
Game Crash

## Expected Behaviour
Um....change the texture pack? Haha

## Steps to Reproduce (for bugs)
I got Faithful x64 and tried to apply it, but after 5-10 minutes of waiting, the game just crashes.

## Logs

* Client/Server Log:
* Crash Log: This is what it said when it crashed: The game crashed whilst updating screen events
The game crashed whilst updating screen events
Error: java.lang.OutOfMemoryError: GC overhead limit exceeded (Do I just need to put more RAM into it?)

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
Thanks for filling in the needed details! _not..._

Yes, more memory is required when using an RP.

**Comment by ProWittingSword** [comment]
Sorry...new to this site. Didn't even see those xD
