### ISSUE TITLE
Server unable to start

### ISSUE THREAD

**Issue by FaytCloud** [DarkPacks/SevTech-Ages#3213]
## Bug Report

this shows up at the bottom of my server load, and it stops loading, no commands, not even the one it tells me to input will work, not even stop, i have tried alternate capitalization, adding /, and removing parts, such as setLenient(true), just saying yes, accept or true, nothing at all registers to the system

[BetterFps Update Checker/WARN] [BetterFps]: Could not check for updates: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
## Possible Solution

i only found 1 other post about this issue on june 22, that was closed without an answer
## Steps to Reproduce (for bugs)

1.start server off serverstart.bat
2.

## Logs

* Client/Server Log:https://gist.github.com/FaytCloud/c4f2f2198db1ddb0b95cc6deb8fa6690
* Crash Log:no crash log, it freezes and is required to shut the program down

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8---- i believe, latest and standard version
* Launcher Used: jar off twitch
* Memory Allocated: 6-8gb
* Server/LAN/Single Player: server
* Optifine Installed:No
* Shaders Enabled:No

## World Information

* Modpack Version world created in: 3.0.4

* Additional Content Installed:

## Server Information
* Java Version: 1.8
* Operating System: win 10
* Hoster/Hosting Solution: Home dedicated server
* Sponge (Non-Vanilla Forge) Server:

**Comment by BadToad2000** [comment]
I am not working on this project, but I noticed your log indicated a failure to bind to port. Are you certain there is not a server instance running on the machine already? Applied Energistics threw an exception after this, but the failure to bind the port means that shouldn't have mattered.

```
[18:23:51] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer]: **** FAILED TO BIND TO PORT!
[18:23:51] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer]: The exception was: java.net.BindException: Address already in use: bind
[18:23:51] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer]: Perhaps a server is already running on that port?
[18:23:51] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
```

Try restarting PC or use Task Manager to kill any running java apps...

**Comment by artdude543** [comment]
Error is as above ^ Logs tell a hundrud stories and tell you the issue straight away 😜

**Comment by FaytCloud** [comment]
i have no other java tasks or server's running just this one
