### ISSUE TITLE
Block Texture changes while breaking a block

### ISSUE THREAD

**Issue by pat1017** [DarkPacks/SevTech-Ages#3219]
## Bug Report

whenever i break a block in sevtech 3.0.8 it shows the cras slowly expanding and then it shows a diamon block texture over the block texture that im trying to break.

## Expected Behaviour

block should just break without an issue

## Steps to Reproduce (for bugs)

1. Break block
2. watch the textures of the block

## Logs

* Client/Server Log: https://pastebin.com/VzZ2EYvP
* Crash Log: No Crash

## Client Information

* Modpack Version: 3.0.8
* Java Version: 8
* Launcher Used: ATLauncher
* Memory Allocated: 9 GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed:

## Server Information
* Java Version: No Access
* Operating System: No Access
* Hoster/Hosting Solution: No Access
* Sponge (Non-Vanilla Forge) Server: No Access

**Comment by artdude543** [comment]
You need to restart the pack. You have a bugged resource loading issue. Simple fix. Reload.
