### ISSUE TITLE
SevTech: Ages+Ender IO. - Could not find a crafting ingredient for 'GEAR_WOOD in <recipe> 'Gear, Wood'

### ISSUE THREAD

**Issue by xCARVENx** [DarkPacks/SevTech-Ages#3221]
Help correct a small defect. I understand that only one recipe needs to be corrected, but not in my power to understand exactly where and how.
### =============================
== ENDER IO FATAL RECIPE ERROR ==
### =============================
Cannot register recipes as configured. This means that either your custom recipe files 
have an error or another mod does bad things to vanilla items or the Ore Dictionary. 
### =============================
== Bad file ==
 recipes/materials.xml
### =============================
 == Error Message ==
Could not find a crafting ingredient for 'GEAR_WOOD in <recipe> 'Gear, Wood'
### ===========================
Note: If this is a modpack, report to the modpack author, not to the Ender IO team.
### =============================
 A custom exception was thrown by a mod, the game will display an error screen and halt.
com.enderio.core.client.EnderCoreModConflictException: 
## Expected Behaviour
I've added this wonderful mod to an excellent build, since without it it's completely impossible to imagine a maincraft. But now, as I understood the recipe of the gradient bar, it conflicts with the recipe of the wooden pole from Ender IO.

## Possible Solution
I tried to change the ingredients of the craft, changed the name, disconnected the craft - but all without result.

## Steps to Reproduce (for bugs)
1. Just add Ender IO and his Core .

## Logs
* Crash Log:https://yadi.sk/i/-pKF1K2A3Zt7yw

## Client Information
* Modpack Version:SevTech+Ages-3.0.8
* Java Version:build 1.8.0_171-b11
* Launcher Used:Twitch
* Memory Allocated:
* Single Player:9Gb/16Gb
* Optifine Installed:No
* Shaders Enabled:No

## World Information
* Additional Content Installed:
EnderCore-1.12.2-0.5.35
EnderIO-1.12.2-5.0.29

**Comment by monodemono** [comment]
Ender IO is not present in SevTech, and by altering the pack you have made it impossible for us to provide you with any actual support for your issues.

Closed for being off topic.

**Comment by xCARVENx** [comment]
Is it difficult to leave this topic for a week? The error is that it's empty, maybe someone would have decided it (
