### ISSUE TITLE
World froze/crashed after breaking a wall in the Tinkers Construct smeltery while full of fluids.

### ISSUE THREAD

**Issue by Vilkath** [DarkPacks/SevTech-Ages#3222]
So I am in Age 2 of Sevetech ages and I just got a Smeltery Controller, melted a few things and realized i needed to move my drain to another side. So I pulled out my pick axe and broke one of the seared windows holding lava. I almost thought all the stuff would come rushing out and kill me but instead the world just froze and went non responsive.

After the game crashed any time I reload the world it crashes again. I am pretty sure I can recover from a world's back up but still an issue.

I hope these are the right logs, I just copied the last 3 with today's
[2018-08-03-3.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2259206/2018-08-03-3.log.gz)
[2018-08-03-1.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2259207/2018-08-03-1.log.gz)
[2018-08-03-2.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2259208/2018-08-03-2.log.gz)

 date on them since the whole folder is over 25mb even zipped, and the file limit is 10mb here.

**Comment by Vilkath** [comment]
Took a tiny clip of a recording I was doing at the time of the problem happening. Just in case I didn't explain myself well enough.

https://www.youtube.com/watch?v=a-5VRN06Gyc&feature=youtu.be

Not really much to see, but there it is if it helps.

**Comment by monodemono** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by Vilkath** [comment]
Well I thought i'd help the mod pack work... included the files and a link to the event happening itself. Didn't even see the 5 pages of text for the form as it I didn't scroll down. I gotta be honest ignoring the problem that I provided the logs for and video footage because I didn't do so kind of turns me off of bothering to report the bug.
