### ISSUE TITLE
ClassCastException when interacting with advancements or JEI

### ISSUE THREAD

**Issue by SpenceDiNicolantonio** [DarkPacks/SevTech-Ages#3224]
## Bug Report

Game crashes upon clicking the Age 2 advancement tab and specific items in the JEI. In every case, the [crash log](https://public.pezzer.io/minecraft/crash-2018-08-04_14.23.07-client.txt) shows a ClassCastException being thrown:

`java.lang.ClassCastException: it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap cannot be cast to gnu.trove.map.hash.TIntObjectHashMap`

I'm not sure when the crashes triggered by JEI interactions started, but the crashes triggered by the Age 2 advancement tab started after crafting a Starlight Crafting Altar and receiving credit for the associated advancement.

## Expected Behaviour

Clicking the Age 2 advancement tab displays the content of that tab in the view.

## Steps to Reproduce (for bugs)

1. Bring up the advancements view (press 'L' key)
2. Click on the "Age 2" advancement tab

## Logs

* [Client/Server Log](https://public.pezzer.io/minecraft/2018-08-04-1.log)
* [Crash Log](https://public.pezzer.io/minecraft/crash-2018-08-04_14.23.07-client.txt)

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8
* Launcher Used: Twitch
* Memory Allocated: 11GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: N/A

## World Information

* Modpack Version world created in: 3.0.8
* Additional Content Installed: None

## Server Information
* Java Version: 1.8
* Operating System: Ubuntu 16.04
* Hoster/Hosting Solution: Private VPS

**Comment by SpenceDiNicolantonio** [comment]
For further reference, I found a specific interaction in JEI that triggers a ClassCastException. Left-clicking on Starmetal Ore yielded [this crash log](https://public.pezzer.io/minecraft/crash-2018-08-04_15.18.28-client.txt).

**Comment by artdude543** [comment]
Fixed in 3.1.0 :)
