### ISSUE TITLE
Crash when loading the game

### ISSUE THREAD

**Issue by Aliexis82** [DarkPacks/SevTech-Ages#3226]
## Bug Report
 Hello, Minecraft crash in the step 4 of the loading

## Steps to Reproduce (for bugs)

1.I open Twitch app
2.Lanch Sevtech
3.Push play in minecraft laucher which has just opened

## Logs

* Client/Server Log:
* Crash Log:The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Inventory Tweaks (inventorytweaks)

## Client Information

* Modpack Version: 3.0.8
* Java Version: I don't have, Mc use the java version integraded in
* Launcher Used:Twitch
* Memory Allocated: 7G
* Server/LAN/Single Player: Single Player
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
Thank you for reporting an issue!

It appears you are logging an issue for a crash, but you have either not uploaded to PasteBin/Gist etc.. of the actual crash report. This report contains the needed data to help to locate the cause and a possible fix. To find the file needed please review the following for either of the launchers.

## Twitch
1. Select the SevTech Pack to view the modpack page.
2. Click the `...` button on the top right just next to `Get More Content`.
3. Click `Open Folder`.
4. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it. 

## ATLauncher
1. Select the Instances tab, then scroll to the instance of SevTech.
2. Click the bottom right button named `Open Folder`
3. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it.

For any other launcher should be a similar process, if not consult with Google if you are not sure on how to find the folder. The information contained in these reports is critical for getting the crash fixed/looked into.

## Servers
For servers the process if farilt simple. Go the folder cotaining all the sever files/folder and you will see a folder called `crash-reports` follow the same process as above by getting the lastest one and uploading it to a text store.

**Comment by Aliexis82** [comment]
Sorry to have forgotten the Crash Report, here it is:
https://pastebin.com/4nqVdEYc
Maybe it's not the right one with respect to the error message. I tried several times so I had a lot of crash report. But nothing changed
