### ISSUE TITLE
Twilight Forest End Achievements Unobtainable

### ISSUE THREAD

**Issue by Orichlol** [DarkPacks/SevTech-Ages#3232]
Seems like I can't trigger the last 2 Twilight Forest achievements "Past the Thorns" and "So Castle Very Wow" I got the lamp, burnt a bunch of bramble, walked up to the castle with the stairs, opened a blue door, climbed all the way to the main castle, climbed the towers to the top and read the sign saying that the last boss will be there.

Sevtech: Ages V3.0.8
No Optifine
Java 1.8.0.161
Faithful 32x and Faithful 32x Modded

(Cut/pasted this bug report for 3.0.8 ... still doesn't work)

**Comment by Azrazal** [comment]
the say [NYI] on them, meaning 'not yet implemented'
hope that helps

**Comment by monodemono** [comment]
The Twilight Forest advancements are the vanilla advancements from within the mod, not custom ones added by us. If you want to file a bug report about this, file it on their bug tracker, not ours, but given that the castle is unfinished still, they probably already know.
