### ISSUE TITLE
Crashes on launch. 

### ISSUE THREAD

**Issue by simonjc72** [DarkPacks/SevTech-Ages#3233]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:3.0.8
* Java Version:
* Launcher Used:
* Memory Allocated:8144
* Server/LAN/Single Player:
* Optifine Installed: Yes
* Shaders Enabled: No
[crash-2018-08-06_21.53.30-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/2264809/crash-2018-08-06_21.53.30-client.txt)

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System: Windows 10
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
