### ISSUE TITLE
Update Galacticraft to .181

### ISSUE THREAD

**Issue by stolenwhisper** [DarkPacks/SevTech-Ages#3235]
Optifine is not recommended for this pack but is required for shaders. Core samples are invisible in older optifine versions. Newest optifine corrects this. However current version of Galacticraft crashes with newest optifine as its not detected. Newest glacticraft fixes this issue.

**Comment by monodemono** [comment]
Optifine D1 and D2 don't make core samples invisible, and don't crash in the pack, Galacticraft is being updated in the next release anyways, and you ignored the template, so I'm just gonna go ahead and close this.
