### ISSUE TITLE
Lag 1 FPS (Not the usual problem)

### ISSUE THREAD

**Issue by HurtsAsHell** [DarkPacks/SevTech-Ages#3236]
After months of playing, suddenly, the modpack began to make me IMPOSSIBLE lag, 1 FPS, I can not do any DUBUG mincraft (F3 + ...) I think for the lag; I tried to reinstall the modpack by eliminating twitch backups; I tried to decrease all the graphic settings and add RAM (up to 9GB dedicated to MC) to the launcher; I tried to recreate the world from 0 and play on servers, the problem remains. I also did to use all the recommended settings on the forum (even if I did not need it) did not help.

## Logs

* Client/Server Log: Latest : https://gist.github.com/HurtsAsHell/414c22fad4ff3768accc7013c50093f9, no log Zip
* Crash Log: No crash

## Client Information

* Modpack Version: 3.0.8
* Java Version: 8.0.1810.13
* Launcher Used: Twitch
* Memory Allocated: 6, now 9 (GB)
* Server/LAN/Single Player: Server / Single Player
* Optifine Installed: Not now
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8 and I do not remember exactly in which, if there is a way to know it, I send it to you

* Additional Content Installed: Nothing

## Server Information
* Java Version: the same of client
* Operating System: Windows - 10
* Hoster/Hosting Solution: Local Host
* Sponge (Non-Vanilla Forge) Server: No

Fatal : This error was found by opening the world (just generated);
21:06:15	FML	main	fatal	Suppressed additional 139 model loading errors for domain immersivepetroleum
21:06:15	FML	main	fatal	Suppressed additional 24 model loading errors for domain betterwithaddons
21:06:15	FML	main	fatal	Suppressed additional 8 model loading errors for domain immersiveengineering
fatal

I do not know if these other logs can serve you, I'll place them anyway; Excuse me for the mess, next time I will try to be tidier :

21:09:27	betterwithmods	Server thread	warn	Result CookingPotTests : Total : 2, Passed: 0, Failed 2
21:09:42	FML	Server thread	warn	PrimalCore loaded a new chunk [-3, 11] in dimension 0 (overworld) while populating chunk [-3, 10], causing cascading worldgen lag.
21:09:42	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:42	FML	Server thread	warn	PrimalCore loaded a new chunk [-2, 11] in dimension 0 (overworld) while populating chunk [-3, 10], causing cascading worldgen lag.
21:09:42	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:46	FML	Server thread	warn	PrimalCore loaded a new chunk [12, 12] in dimension 0 (overworld) while populating chunk [12, 11], causing cascading worldgen lag.
21:09:46	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:46	FML	Server thread	warn	PrimalCore loaded a new chunk [13, 11] in dimension 0 (overworld) while populating chunk [12, 11], causing cascading worldgen lag.
21:09:46	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:46	FML	Server thread	warn	PrimalCore loaded a new chunk [13, 12] in dimension 0 (overworld) while populating chunk [12, 11], causing cascading worldgen lag.
21:09:46	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:46	net.minecraft.server.MinecraftServer	Server thread	warn	Can't keep up! Did the system time change, or is the server overloaded? Running 17584ms behind, skipping 351 tick(s)
21:09:51	FML	Server thread	warn	Geolosys loaded a new chunk [25, -36] in dimension 0 (overworld) while populating chunk [26, -35], causing cascading worldgen lag.
21:09:51	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:52	FML	Server thread	warn	PrimalCore loaded a new chunk [19, 9] in dimension 0 (overworld) while populating chunk [18, 9], causing cascading worldgen lag.
21:09:52	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:53	FML	Server thread	warn	Geolosys loaded a new chunk [12, -44] in dimension 0 (overworld) while populating chunk [12, -43], causing cascading worldgen lag.
21:09:53	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:54	FML	Server thread	warn	Geolosys loaded a new chunk [-17, -32] in dimension 0 (overworld) while populating chunk [-17, -31], causing cascading worldgen lag.
21:09:54	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:54	FML	Server thread	warn	PrimalCore loaded a new chunk [34, -14] in dimension 0 (overworld) while populating chunk [34, -15], causing cascading worldgen lag.
21:09:54	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:54	FML	Server thread	warn	PrimalCore loaded a new chunk [35, -14] in dimension 0 (overworld) while populating chunk [34, -15], causing cascading worldgen lag.
21:09:54	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:54	FML	Server thread	warn	PrimalCore loaded a new chunk [36, -13] in dimension 0 (overworld) while populating chunk [35, -14], causing cascading worldgen lag.
21:09:54	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:54	FML	Server thread	warn	PrimalCore loaded a new chunk [35, -13] in dimension 0 (overworld) while populating chunk [35, -14], causing cascading worldgen lag.
21:09:54	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:54	FML	Server thread	warn	PrimalCore loaded a new chunk [34, -13] in dimension 0 (overworld) while populating chunk [35, -14], causing cascading worldgen lag.
21:09:54	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:54	FML	Server thread	warn	PrimalCore loaded a new chunk [34, -12] in dimension 0 (overworld) while populating chunk [34, -13], causing cascading worldgen lag.
21:09:54	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:54	FML	Server thread	warn	PrimalCore loaded a new chunk [35, -12] in dimension 0 (overworld) while populating chunk [34, -12], causing cascading worldgen lag.
21:09:54	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:54	FML	Server thread	warn	PrimalCore loaded a new chunk [34, -10] in dimension 0 (overworld) while populating chunk [34, -12], causing cascading worldgen lag.
21:09:54	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:54	FML	Server thread	warn	PrimalCore loaded a new chunk [35, -11] in dimension 0 (overworld) while populating chunk [34, -12], causing cascading worldgen lag.
21:09:54	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:54	FML	Server thread	warn	PrimalCore loaded a new chunk [34, -11] in dimension 0 (overworld) while populating chunk [34, -12], causing cascading worldgen lag.
21:09:54	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:54	FML	Server thread	warn	PrimalCore loaded a new chunk [35, -10] in dimension 0 (overworld) while populating chunk [34, -11], causing cascading worldgen lag.
21:09:54	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:54	FML	Server thread	warn	PrimalCore loaded a new chunk [36, -14] in dimension 0 (overworld) while populating chunk [35, -14], causing cascading worldgen lag.
21:09:54	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:09:54	FML	Server thread	warn	PrimalCore loaded a new chunk [35, -15] in dimension 0 (overworld) while populating chunk [34, -15], causing cascading worldgen lag.
21:09:54	FML	Server thread	warn	Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Comment by artdude543** [comment]
So, I'm going to start with "It's not a pack problem". FPS issues will always be a problem for this game and modded Minecraft in general.

From what I can tell you from your logs. You Java is really out of date you should be on the latest version of 8. Details [here](https://docs.google.com/document/d/e/2PACX-1vR5muyi1m7Zy_qSwrzeb9e3tbbRlksguNUb_Pvm3pn9eDpsIkUj5qQUq6WFPPdEoVWZq91WvvH57KzC/pub) you also have a fairly outdated GPU (For the requirements needed for this pack).

To put it short; this pack was made for a high-end system (for a single person). You can only do as much as you can in regards with args and keeping Java/GPU Drivers up to date. Past that you can only upgrade hardware. The 3.1.0 update does have some perf boost. But it still won't "solve" the minority of people with slower systems.

This is a hard bearing pack with rendering and world generation. Sadly you need a beast to play it well enough. You can disable mods such as Better Foliage which will give you some back. Or try Optifine but results may vary. Also running a server for your world will help off-load some to that and give your client more breathing space.

Also Primal logging. Not a bug has never been. Likewise for other mods with similar logging from Forge. It's a warning for a potential issue. (Which was busted ages ago that's not actually harmful)

There is not much more you can do in regards. Maybe you chat on our Discord for further help but other than the norm steps. That's about all the work that can be done.

Thanks for logging an issue!

**Comment by HurtsAsHell** [comment]
I do not know if you understand, I arrived at stage 3 and I played for two months
I did 100 FPS all this time, I can not suddenly make 1 fps; I think it's a bug, then I do not know

**Comment by Gamebuster19901** [comment]
This is https://github.com/An-Sar/PrimalCore/issues/110, and it is a bug. Primal Core needs updating.

**Comment by artdude543** [comment]
To be clear it's not a **bug** which would even drop FPS.  Many modpacks have these spam in logs and they all play fine. The pack has a tonne of rendering heavy mods which from Stage 3 + you unlock these and they all start to create fun for clients to handle/render.

Welcome to the wonderful game which not optimized for this.
