### ISSUE TITLE
Tier 10 Electric Rocket won't take off

### ISSUE THREAD

**Issue by cheriekeks** [DarkPacks/SevTech-Ages#3237]
## Bug Report
The Tier 10 Electric Rocket won't take off, even tho it is powered / charged and on the correct launch pad.

## Expected Behaviour
The Tier 10 Electric Rocket should lift off once the launch key is pressed

## Possible Solution
Seems to be a mod issue which needs to be addressed, solution for now: disable the recipe since it is very expensive to craft and doesn't work once you did.

Link to issue tracker from Extra Planets: https://github.com/MJRLegends/ExtraPlanets/issues/340

## Steps to Reproduce (for bugs)

1. Build Tier 10 Electric Rocket
2. Place Tier 10 Electric Rocket on 5x5 Powered Rocket Launch Pad
3. Place Vehicle Charger next to Launch Pad and power it!
4. Wait till Rocket is charged
5. Press Launch key (Space by default)

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_51
* Launcher Used: Twitch / Curse
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Additional Content Installed: None

## Server Information
* Java Version: 1.8.0_171
* Operating System: Debian 9 (Stretch)
* Hoster/Hosting Solution: Hetzner Cloud Server (http://hetzner.de)
* Sponge (Non-Vanilla Forge) Server: No

**Comment by artdude543** [comment]
We won't disable the recipe (Which will require a pack update). We'll update the mod when it's out which will fix the issue. As part of our release cycle. But thanks for the report!

**Comment by artdude543** [comment]
Mod has been updated/will be in the 3.1.0 update :)
