### ISSUE TITLE
Server side of SSP crashes when changing dimensions

### ISSUE THREAD

**Issue by KollinsPlays** [DarkPacks/SevTech-Ages#3239]
## Bug Report

Occasionally, while changing dimensions in an SSP world, I experience a crash of sorts. It doesn't appear to generate a crash log and instead of crashing the client, I get dumped to the server list screen with an error, "Connection Lost
Internal Exception: java.nio.channels.ClosedChannelException" 

I copied from the latest.log near the time of the crash: https://paste.ee/d/ZN795 Please let me know if there are other steps I can take to capture useful information.

## Steps to Reproduce (for bugs)

1. switch dimensions (in age 4?)
2.

## Logs

* Client/Server Log: https://paste.ee/d/ZN795
* Crash Log:

Client Information

    Modpack Version: 3.0.8
    Java Version: Version 8 update 171 build 1.8.0_171-b11
    Launcher Used: MultiMC
    Memory Allocated: 5023MB
    Server/LAN/Single Player: SSP
    Optifine Installed: No
    Shaders Enabled: No

World Information

    Modpack Version world created in: 3.0.8

    Additional Content Installed: none

Server Information

    Java Version:
    Operating System: Windows 7 x64
    Hoster/Hosting Solution:
    Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
This will be helped when 3.1.0 lands. We have done as much as we can from the mods side. So if the issue persists there is nothing more we can do. It's all about networking/loading times etc.. which are out of our control.
