### ISSUE TITLE
Request to add In-Game Wiki Mod for PneumaticCraft

### ISSUE THREAD

**Issue by Sinxar** [DarkPacks/SevTech-Ages#3240]
## Context

A lot of questions come up about the basic functionality of PneumaticCraft and the documentation is incredibly sparse at best. It is a quite powerful mod but most people who has to use it for the first time has to watch tons of videos or rely on outdated information. Not sure how well this actually works in SevTech but if you can make it work without being intrusive (people claim it blocks your view when looking at supported blocks) it would be great for people who never used pneumaticcraft before.

I don't agree with the choice to not make a normal wiki and force people to use another mod for documentation, but until he author comes to his senses there isn't much else a person can do.

## Mod Details
* Name: In-Game Wiki Mod
* CurseForge Link: https://minecraft.curseforge.com/projects/in-game-wiki-mod

**Comment by artdude543** [comment]
Has been included for 3.1.0.

You'll see this when the update lands 😄
