### ISSUE TITLE
Chisel Blocks (Diamond, Emerald etc.)

### ISSUE THREAD

**Issue by Brutzelhirn** [DarkPacks/SevTech-Ages#3241]
Since me and my friends reached the highest age we wanted to start building our base and i wanted to use the different chisel blocks for diamond and emerald blocks, which can be seen in the NEI interface on the right if you type in diamond or emerald. The problem is, that we can't produce these blocks in any way, there ist no crafting recipe and none of the different chisels, neither iron Chisel or diamond chisel or IChisel worked. Not even TC chisels with supremium. We also enabled them in the chisel config from our server ofc, but that doesn't seem to work. Is there any way to get these Blocks or are they disabled somewhere else?
## Expected Behaviour

Chisel Diamond Blocks in Richt-Click GUI or left click 
## Possible Solution

Make the Chisel Configuration from the Server work in any way?
## Steps to Reproduce (for bugs)

1.Take a Chisel and a Diamond Block
2. Try chiseling it into something else than a Diamond Block

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: 8.0.1810.13
* Launcher Used: ATLauncher
* Memory Allocated: 7680 MB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.7

* Additional Content Installed: None 

## Server Information
* Java Version: the newest 
* Operating System:
* Hoster/Hosting Solution: Nitrado
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
Similar issue here: #2092 (Will keep locked to one issue)
