### ISSUE TITLE
Add Simple Logic Wires and Simple Logic Gates?

### ISSUE THREAD

**Issue by Trinsdar** [DarkPacks/SevTech-Ages#3243]
## Context
It is a mod that adds better redstone wires like the project red wires and some gates like the project red gates, but is much less used and doesn't have all the other bloat that project red has. And it uses mc multipart instead of forge mutipart.
## Mod Details
* Names: Simple Logic Wires and Simple Logic Gates
* CurseForge Links: https://minecraft.curseforge.com/projects/simplelogic-gates
https://minecraft.curseforge.com/projects/simplelogic-wires

**Comment by monodemono** [comment]
Pretty much all of this functionality is present in both RFTools and Integrated Dynamics, which are both present in this pack, so adding these mods would be redundant.
