### ISSUE TITLE
Can't Get Silicon Ore Advancement

### ISSUE THREAD

**Issue by Heroshrine** [DarkPacks/SevTech-Ages#3245]
### Bug:
When I mine silicon ore, I don't get the advancement for it. This might be because I'm using a Tinker's Construct pickaxe.

### Expected Behavior:
To get the Silicon Ore advancement when I mine for it.

### Possible Solution:
Add support for tinker's construct tools (if that's whats causing it)

### Steps to Reproduce:
1. Make tinker's construct pickaxe with these materials: 
    *Knightmetal for tool rod
    *Cobalt Pickaxe Head
    *Ardite Binding
2. Add these modifiers to it:
    *Excavate (25/25)
    *Mending Moss
    *Haste (50/50)
    *Luck 1
3. Apply Gauntlet of Far Reach on chestplate
4. Find silicon ore, and not having the advancement for it, mine it.

### Information:
* Modpack Version:
* Java Version: 3.0.8
* Launcher Used: Twitch
* Memory Allocated: 8G
* Server/LAN/Single Player: Server
* Optifine Installed: Was installed, but I removed it.
* Shaders Enabled: No.

### World Information:
* Modpack Version world created in: Unknown
* Additional Content Installed: FTB lib, FTB utilities.

### Server Information:
I do not host the server.

**Comment by Heroshrine** [comment]
Most likely a bug with tinker's construct. I just mined assorted quartz, but didn't get the advancement either. It's most likely caused by one of the modifiers, as I've mined ores with tinkers construct tools before and gotten advancements for them. (My guess is on Luck)

**Comment by Azrazal** [comment]
is it possible that you didnt craft the prospector needed for those? the advancements all activate when you pick up the item, so the tool shouldnt have any effect.

**Comment by Heroshrine** [comment]
Yes, i crafted the prospector. And the advancements don't all activate when you pick up an item. Some you have to take a certain action, like mining.

**Comment by artdude543** [comment]
You need to process the silicon ore to get the advancement. Mining the ore does not trigger it.

**Comment by Heroshrine** [comment]
Should be more specific then, it says dig for it.
