### ISSUE TITLE
Can't make Stone Bricks Mouldings

### ISSUE THREAD

**Issue by ByFe** [DarkPacks/SevTech-Ages#3246]
## Bug Report
Cutting Stone Bricks Siding with the Saw from Better With Mods doesn't give Stone Bricks Mouldings but Stone Mouldings.

## Expected Behaviour
Get Stone Bricks Mouldings.

## Steps to Reproduce (for bugs)
Put Stone Bricks Sidings into Saw.

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_172
* Memory Allocated: 8192 MB

## World Information
* Modpack Version world created in: 3.0.4?!

**Comment by artdude543** [comment]
This will be fixed in 3.1.0 😄
