### ISSUE TITLE
Inventory disappears after chiseling cobblestone light block

### ISSUE THREAD

**Issue by Jersh** [DarkPacks/SevTech-Ages#3253]
## Bug Report

I accidently clicked on a Ferdinand's flowers cobblestone light block whilst holding the Chisel from Chisel and my inventory disappeared, selecting the galacticraft tab brought it back but it stopped updating as i mined items. a client restart fixed it.

## Expected Behaviour

Guess it shouldn't do what it did

## Steps to Reproduce (for bugs)

1. couldn't actually get it to reproduce upon testing.

## Logs

* Client/Server Log:
https://pastebin.com/aVtBNLnb

## Client Information

* Modpack Version: 2.08
* Java Version: 1.8 64 Bit
* Launcher Used: AT Launcher
* Memory Allocated: 8 Gb
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 2.08

* Additional Content Installed: None

**Comment by artdude543** [comment]
Already fixed for 3.1.0 😄
