### ISSUE TITLE
Item/block render causes crash

### ISSUE THREAD

**Issue by arkD** [DarkPacks/SevTech-Ages#3254]
Reinstall fixed this issue, but thought maybe I should share anyway

Item/block render causes  crash

## Bug Report
Item/block render causes to desktop crash

## Expected Behaviour
1. don't render item or delete maybe?

## Possible Solution
1. somehow delete the offending block
2. a reinstall fixed this issue

## Steps to Reproduce (for bugs)
1. log into the server
2. crash to desktop

## Logs
* Client/Server Log: https://goo.gl/t3wV9L   //was too large for pastebin
* Crash Log: https://pastebin.com/MUT4BX1a

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8
* Launcher Used: Twitch
* Memory Allocated: ~8G
* Server/LAN/Single Player: server
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.7

* Additional Content Installed: FTBUtilities, FTBCore

**Comment by artdude543** [comment]
Fixed in 3.1.0 (Also check closed issues before posting one)
