### ISSUE TITLE
Shearing sheep with a rancher

### ISSUE THREAD

**Issue by MaucnAD** [DarkPacks/SevTech-Ages#3258]
I don't know if this is intended or not, but if you shear sheep with the industrial foregoing Animal Rancher, you get regular wool. 
Now obviously this is great because you get a lot more wool, but it feels like cheating. 

Please tell me if it's something you missed or not.

**Comment by Tahakk** [comment]
You can do the same with astral sorcery in Age 2 already in WAY faster way. Take it as reward for your hard work.

**Comment by monodemono** [comment]
We're fine with this. When you reach age 4 you've toiled enough to get wool. Certain menial tasks are meant to get easier as you progress further.
