### ISSUE TITLE
Bad frame freeze

### ISSUE THREAD

**Issue by Shade0890** [DarkPacks/SevTech-Ages#3259]
## Bug Report

My games frames freeze every 5-10 seconds and its getting really annoying. I have the correct recommended settings along with the recommended Java parameters 

## Expected Behaviour

I expect my game to not freeze every 5 seconds.

## Possible Solution

Not sure exactly whats wrong. I have run other very big mod packs fine without any lag

## Steps to Reproduce (for bugs)

1. https://www.dropbox.com/s/odtcb7rjjnlcgk1/2018-08-11%2022-15-05.mp4?dl=0

## Logs

* Client/Server Log: https://www.dropbox.com/s/vwhoc19kjdq04cu/latest.log?dl=0
* Crash Log: Doesn't crash

## Client Information

* Modpack Version:3.0.8
* Java Version: jre-8u18-windows-64x
* Launcher Used: Twitch
* Memory Allocated: max 3702m min 256 
* Server/LAN/Single Player: Single Player
* Optifine Installed: No optifine
* Shaders Enabled: No shaders

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None

**Comment by TheSnowyChickens** [comment]
Sometimes I also have freezes, but it has a longer time between it.

But this may occures, because my CPU is "old" and AMD. :D

**Comment by Shade0890** [comment]
@TheSnowyChickens Its a pretty new cpu and Its a nvidia

**Comment by Tahakk** [comment]
Never heard of nvidia CPU tho, but can you bump up RAM a little bit? Not sure if 3.7G is enough, look at F3 tab if RAM isn't topping
