### ISSUE TITLE
Can't type the timestamp for tmg_restore 

### ISSUE THREAD

**Issue by QuinShire** [DarkPacks/SevTech-Ages#3268]
Whenever i type in tmg_restore QuinShire 21:01:38_15/August/2018
it says either the owner's name is misspelled or the timestamp is invalid.

**Comment by QuinShire** [comment]
Nah wasnt me

**Comment by monodemono** [comment]
I have no idea what you're trying to say, but we've closed this issue because it's neither a bug nor feature request, it's user error which you're seeking support for. To do that, go to the discord, not here. I'm not locking this conversation as it's off topic and unnecessary.
