### ISSUE TITLE
Does not create a Beneath teleporter through the Necronomicon. How can I fix it?

### ISSUE THREAD

**Issue by Besh51** [DarkPacks/SevTech-Ages#3270]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by Tahakk** [comment]
fill out the form, noone will help you this way
