### ISSUE TITLE
Start up Crash: Null Pointer on language detection

### ISSUE THREAD

**Issue by TheSnowyChickens** [DarkPacks/SevTech-Ages#3271]
## Bug Report
Start up crash with a clean install.
I had befor a crash with Astral (I wanted to do this : https://ftb.gamepedia.com/Armara )

## Expected Behaviour
No crash.

## Possible Solution
Update Geolosys? (Crash log say something with Geo.)

## Steps to Reproduce (for bugs)
1. Start game
2. Wait
3. Crash

## Logs
* Client/Server Log: https://pastebin.com/ZgUT885z (I hope it is the right one)
* Crash Log: https://pastebin.com/Kkh415Aq

## Client Information
* Modpack Version: 3.0.8
* Java Version: J8_U51 (from MC launcher, but it also dont work with J8_U181 + 10 GB)
* Launcher Used: Curse
* Memory Allocated: default Curse (7GB)
* Server/LAN/Single Player: Client, but I want to connect to a Server 
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed: No

**Comment by Maikar23** [comment]
mine is crashing now too. Been playing for weeks and something updated this morning when I went to load the pack. Now crashes on launch.

https://pastebin.com/guAA39cp

The game crashed whilst initializing game
Error: java.lang.NullPointerException: Initializing game

**Comment by Odingod** [comment]
Same thing happens to me and the log is similar. It's the geolosys getTranslation for me too that throws the NullPointerException.

**Comment by Alcorsa** [comment]
Me too. Crashed every time after Loading Entity Render stage
https://pastebin.com/LAtjfcEQ
p.s. and yes Windows10 was updated last night

**Comment by akaikishi** [comment]
Here is a band-aide fix...
I had the same errors start this morning on 3 different PCs (Win7 and Win10).  They were working fine last night!
I went into the Twitch client's settings, then selected 'Minecraft' on the left menu, set 'Launch Method' to Jar Launcher instead of Native, then made sure the Java Version was pointed to my PC's installed Java folder. Tested using jre 1.8.0_171 and 181 on Win7, then jre 1.8.0_144 on Win10.
After making this change, it allowed me to boot the game just fine, though it uses a different style launcher. So, you will want to sign back in to that launcher, then close it, then reopen it to get the Sevtech profile loaded.

**Comment by jakdax99rb** [comment]
@akaikishi 's fix worked for me. Thanks man.

**Comment by swestrup** [comment]
I'm having the exact same issue as everyone else. The game ran fine yesterday, but today it's crashing on init with a Null Pointer Exception in Geolosys. I've uploaded my crash report, but I doubt it contains anything new: https://paste.ee/p/z1psG

I'm playing under Linux and using the MultiMC launcher, so the above workaround doesn't work for me.

**Comment by Sirheavens** [comment]
How might one implement @akaikishi 's fix in MultiMC?

**Comment by jtarnold** [comment]
I manually updated Geolysis mod to v2.1.0 and it seems to have worked also using the standard launcher from the Twitch client.

**Comment by artdude543** [comment]
Whatever you do. Don't update Geolysis unless you want to lose your world...

I'm going to lock this as the issue needs confirming by the developers of the modpack. Not "ideas"

**Comment by artdude543** [comment]
This has been identified as a bug on Mojang's side. They are aware and patching the files. You'll need to wait for the cache to reset and re-launch your game, which will re-download the assets files which contains the fix.

This will take a bit to propagate. So keep trying and it will eventually work. Note: You may need to restart the launcher each time for it to force check/download the files.

Thanks for the report guys! This was a fun one. 😆

**Comment by artdude543** [comment]
Closing this now. As Mojang changed the files on their end. And the update would be "patched" in the update to Forge. But the band-aid from Mojang will stick for the time being.
