### ISSUE TITLE
Effects

### ISSUE THREAD

**Issue by BeardedGamer0** [DarkPacks/SevTech-Ages#3288]
<!--
Thanks for taking the time to filing an issue. Before you submit, please read the following:

Check for other issues already opened, to see if your issue/suggestion has been reported already.
Ensure that you have all the relevant information on hand. Such as logs/reports and information about a request/change.

When I returned from TheBetweenLands I still have the Weakness and MiningFatigue and the timer goes down to 25 and resets to 30... have tried relog but still there... nothing in my inventory from TheBetweenLands either.... is this normal or glitched.... how to get rid of?

**Comment by BeardedGamer0** [comment]
Yeah thanks for the help…..

Sent from Mail for Windows 10

**Comment by monodemono** [comment]
Help with what? Your title is one word and your report is literally blank. Try actually filling out an issue report next time?
