### ISSUE TITLE
sync disconnect

### ISSUE THREAD

**Issue by All-Is-Fair** [DarkPacks/SevTech-Ages#3291]
player on team wasn't on when age advanced from 0 to 1, whenever the player tries to connect to the server makes the connection but then get team synced and disconnects

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
