### ISSUE TITLE
IE assembler not working

### ISSUE THREAD

**Issue by tgiddings** [DarkPacks/SevTech-Ages#3293]
## Bug Report

The IE assembler does not craft even though it has power, sufficient materials, and a crafting recipe. Applying a redstone signal to the control blocks or changing the control blocks' mode with the engineer's hammer does not resolve the issue. Additionally, following the steps in the "steps to reproduce" section in a world where IE and Immersive Petroleum are the only installed mods yields the expected behavior.
## Expected Behaviour

The assembler uses the materials in the internal inventory to craft the items in the configured recipe.

## Steps to Reproduce (for bugs)

1. Create a new world
2. Grant the player all advancements using the command `/advancement grant {player} everything`
3. Place the blocks for an assembler
4. Form the multiblock with engineer's hammer
5. Place a creative energy source nearby
6. Attach the creative energy source to the multiblock's power input using MV wiring
7. Spawn in a stack of Oak planks
8. Enter the recipe for a crafting table into the assembler
9. place the planks into the crafting table's inventory

Note: I have reproduced the issue with the recipe for insulated MV wire coils and with the recipe for Pneumaticraft's circuit board.

## Logs

* Client/Server Log: https://gist.github.com/tgiddings/9a6a1a34eeee6cc16c9e04a1fb136b0f
* Crash Log: N/A

## Client Information

* Modpack Version: 3.0.8
* Java Version: OpenJDK 1.8.0_171
* Launcher Used: ATLauncher
* Memory Allocated: 4096 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: None

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: N/a (There are mods in the disabled mods folder but I tested the issue in a world which was made while those mods were disabled and performed the test while those mods were disabled. The mods are Immersive Railroading 1.3.2, TrackAPI 1.1, and In-game wiki 1.4.4.15)

**Comment by artdude543** [comment]
Yes. The issue will never be fixed due to how the staging mods work and the interactions over 4 differ mods. You'll have to use another crafter. It's still in talks to find a fix but that won't happen any time soon.
