### ISSUE TITLE
Server suddenly started crashing out of nowhere

### ISSUE THREAD

**Issue by paddlegoose** [DarkPacks/SevTech-Ages#3299]
## Bug Report
Me and a buddy of mine were playing on our server, then it started crashing all of a sudden whenever we would join it.
All help is appreciated guys! Thanks! 

##Expected behaviour
It would normally just let us play and all of a sudden, it's not working anymore 

##Steps to Reproduce
1. Launch serverstart.bat
2. Join server
3. Crash

##Logs
* Client/Server Log: https://pastebin.com/q66aWmZU
* Crash Log: https://pastebin.com/wPneR09v

## Client Information
* Modpack Version: v3.0.8
* Java Version: 1.8.0.171 64bit
* Launcher Used: Twitch Launcher
* Memory Allocated: 6-12gb
* Server/LAN/Single Player: Server

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None at all

**Comment by artdude543** [comment]
Resolved in 3.1.0 😄 Should be out in the new week or two. But if you can't wait you can manually update Forge MultiPart (Note clients will need the update also)
