### ISSUE TITLE
i died and have no grave

### ISSUE THREAD

**Issue by ozzythefat** [DarkPacks/SevTech-Ages#3300]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by ozzythefat** [comment]
i was three feet from my house then out of nowhere a shoggoth popped up and killed me i respawned and the shoggoth was gone and i had no grave

**Comment by artdude543** [comment]
Known issue and resolved for 3.1.0 also there is a command to give yourself items back. Also thanks for using the template!
