### ISSUE TITLE
Rock Crystals Extremely Rare/Don't even work

### ISSUE THREAD

**Issue by lethalshark** [DarkPacks/SevTech-Ages#3301]
Me and my buddy have been trying to find rock crystal for ages. We learned that rock crystal is only found on the surface in Sevtech after trying to use the wand to find underground crystals. Now after finding 2 surface rock crystal samples, we still can't get any of the actual crystals, because breaking them gives us stardust. I've tried spawning in a few samples to test and all of them have given stardust. We need help since I really can't figure out how I'm supposed to get these crystals. Thanks.

**Comment by artdude543** [comment]
The samples are above ground. And then you dig underground to the mine the "ore block" which is the crystal.

Whoever told you that they are only above ground is very wrong... and getting the dust from the sample is intended.
