### ISSUE TITLE
Other user gets kicked out after ~30 seconds

### ISSUE THREAD

**Issue by JepsenDK** [DarkPacks/SevTech-Ages#3302]
Hi everyone.

I have an issue with my friend cant log in all of a sudden. I suspect a faulty character save or something, but havent seem to pin point the exact problem.

I have tried ALOT of things, but none seems to help.
I have deleted his playerdata. I have deleted NEI and progression data.

I have only a few saved games, an one of those he cant log into. The other one which is old he can log into.

I am not sure if this is a problem with the server config, though I can log in normally. Or it is a client problem. 

I am playing on LAN and he is connected through a VPN. It have worked before, and there should be no problem with the Internet line.

I have run out of ideas, so any suggestions would be nice.

**Comment by artdude543** [comment]
LAN is not supported for SevTech. Due to the number of mods we use for staging which require networking updates. And LAN does not like the amount of traffic caused. Dedicated servers are the way to go.

**Comment by JepsenDK** [comment]
What i ment was, that I have a dedicated server which I am connecting to through LAN.

So the server should be cool and running perfectly.

**Comment by artdude543** [comment]
VPN's will face the same issue in regards to the traffic going back and forth they cap out at the certain point.

This is normally resolved by switching to using port forwarding or using an actual "server" machine from a host or provider.
