### ISSUE TITLE
Dropping broken hatchet while holding firestick in offhand

### ISSUE THREAD

**Issue by xIceFox** [DarkPacks/SevTech-Ages#3305]
## Bug Report
World crash, not able to reload the World again.

## Possible Solution
Reload world in MCEdit remove dropped entitys

## Logs

This are the report and log when i try to reload the broken world
* Client/Server Log: https://pastebin.com/J4ySSXGm
* Crash Log: https://pastebin.com/7dDG8U1J

## Client Information
* Modpack Version: 3.0.8
* Java Version: 8
* Launcher Used: Twitch
* Memory Allocated: 6400
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
1.12.2
* Modpack Version world created in:
3.0.8

**Comment by artdude543** [comment]
@vadis365 any chance you could look into this one? 🙂

**Comment by xIceFox** [comment]
Possible fix for People that have this problem, its not important if this is the same problem, load the world in MC Edit choose the area where you dropped the item that crashes your world, remove all entities. Works again 😀

**Comment by vadis365** [comment]
Will look in to this - it's unusual as the line where the error is happening is actually behind a check to see if the player has a fire stick in each hand. O.o
