### ISSUE TITLE
Game crashes upon world generation/loading into a world

### ISSUE THREAD

**Issue by agarcia1396** [DarkPacks/SevTech-Ages#3309]
## Bug Report
Sevtech crashes upon the generation or loading into a world. The game cannot be played. 

I have re-downloaded the modpack several times, allocated more/less ram, restarted my PC, snipped some unnecessary bloat mods (better foliage for example) checked my drivers for updates, and updated java, but nothing works. The most I have gotten to in this modpack is the starting message. 

I am new to this thing, so I apologize if my report isn't up to snuff. 
## Steps to Reproduce (for bugs)

1. Load Modpack
2. Load into/Generate new world
3. Load into world
4. Immediately crash

## Logs
* Crash Log: https://pastebin.com/67RQPXTz

## Client Information
* Modpack Version: 3.0.8
* Java Version: 1.8.0.181 (64 bit)
* Launcher Used: Twitch (Both native and jar seems to do nothing to fix the problem.)
* Memory Allocated: Varied between 4-8 GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
Crash happens on any type of load generation, even superflat.

**Comment by artdude543** [comment]
There are no crashes attached. And the logs posted do not contain any errors. Going to throw this one to Discord once you figure out to get the correct logs needed.
