### ISSUE TITLE
Java crashes when attempting to load into world (Now with actual crash log)

### ISSUE THREAD

**Issue by agarcia1396** [DarkPacks/SevTech-Ages#3311]
## Bug Report
Re-posting this since the last one got closed because I don't know what a crash log is, hopefully this is the right one. 

Sevtech crashes upon the generation or loading into a world. The game cannot be played. 

I have re-downloaded the modpack several times, allocated more/less ram, restarted my PC, snipped some unnecessary bloat mods (better foliage for example) checked my drivers for updates, and updated java, but nothing works. The most I have gotten to in this modpack is the starting message. I have also now tried a bandaid fix by reverting to a previous version of Java, still does not work. 

## Steps to Reproduce (for bugs)

1. Load Modpack
2. Load into/Generate new world
3. Load into world
4. Immediately crash

## Logs
* Crash Log: https://pastebin.com/MTqTYWYK

## Client Information
* Modpack Version: 3.0.8
* Java Version: 1.8.0.181 (64 bit)
* Launcher Used: Twitch (Both native and jar seems to do nothing to fix the problem.)
* Memory Allocated: Varied between 4-8 GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
Crash happens on any type of load generation, even superflat.

**Comment by artdude543** [comment]
Not the correct log again. This is the Java Dump I want the crash report.....

**Comment by artdude543** [comment]
Thank you for reporting an issue!

It appears you are logging an issue for a crash, but you have either not uploaded to PasteBin/Gist etc.. of the actual crash report. This report contains the needed data to help to locate the cause and a possible fix. To find the file needed please review the following for either of the launchers.

## Twitch
1. Select the SevTech Pack to view the modpack page.
2. Click the `...` button on the top right just next to `Get More Content`.
3. Click `Open Folder`.
4. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it. 

## ATLauncher
1. Select the Instances tab, then scroll to the instance of SevTech.
2. Click the bottom right button named `Open Folder`
3. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it.

For any other launcher should be a similar process, if not consult with Google if you are not sure on how to find the folder. The information contained in these reports is critical for getting the crash fixed/looked into.

## Servers
For servers the process if farilt simple. Go the folder cotaining all the sever files/folder and you will see a folder called `crash-reports` follow the same process as above by getting the lastest one and uploading it to a text store.

**Comment by agarcia1396** [comment]
I must be dumb because I cannot find any folder labeled "Crash-Reports". I have a log folder, but that only contains the log I posted last night. I apologize.

**Comment by artdude543** [comment]
So from reading the Java Dump this a you issue. You're missing a mod somewhere and a mod is calling `botania` which is not in the pack. And none of the mods have that integration enabled. So either you installed more mods or you broke the configs.

But w/o the crash I can't help any further nor can anyone else. That and your Java Dump is not complete either. So based on that there is nothing more we can do.

You can try re-install the pack/java/drivers etc.. to see but unless you can provide the needed logs we can help. Sorry.
