### ISSUE TITLE
Crash opening inventory in creative w/death compass

### ISSUE THREAD

**Issue by Targren** [DarkPacks/SevTech-Ages#3312]
## Bug Report
Opening the inventory GUI in creative mode while in possession of a death compass (either in inventory or hotbar) causes hard crash. 

## Expected Behaviour
Inventory GUI opens 

## Possible Solution
Appears to be a rendering issue?

## Steps to Reproduce (for bugs)

1. Empty Inventory
2. Die in survival to obtain death compass
3. Change gamemode to creative 
4. Open Inventory GUI

## Logs

* Client/Server Log: https://paste.ee/p/ys8cv
* Crash Log: https://paste.ee/p/boc0f

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_171
* Launcher Used: MultiMC
* Memory Allocated: 6GB
* Server/LAN/Single Player: SSP
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

**Comment by artdude543** [comment]
Already fixed for 3.1.0 look for similar issues before posting a new one...

**Comment by Targren** [comment]
I did a search for "compass" and went back to May, didn't see anything that looked like the same issue.
