### ISSUE TITLE
(3.0.8) Geolosys ore mining lag

### ISSUE THREAD

**Issue by Astarall** [DarkPacks/SevTech-Ages#3313]
## Bug Report
When mining iron geolosys ores in current sevtech (in a non-edited version of the modpack), there is update lag on mining ores from geolosys. 

## Expected Behaviour
Ores take awhile to update once being mined. Other blocks do not have this issue. 

## Steps to Reproduce (for bugs)
Find geolosys ore vein for iron (hematite)
Mine said ore

**Comment by artdude543** [comment]
Invalid issue. As commented by another user on the issue you commented on. The mod updated with more tweaks for 3.1.0. After that if the issue still happens there is nothing more anyone can do.
