### ISSUE TITLE
cant autocraft Leather in age 4

### ISSUE THREAD

**Issue by MarcusKron** [DarkPacks/SevTech-Ages#3314]
The whole process to create Leather with the modular machinery start with Pelt in Raw hide which is not automatic craftable as it requires a work blade.

Like plastic and paper, i aspect that is all the process autocraftable.

**Comment by artdude543** [comment]
Do you know you can use tools in AE/RS? This is not an issue and fully automatable using either AE/RS or even auto crafters from other mods. (Which I've seen YouTubers/Twitchers use)

So the process is automatable. You just need to be clever on how you do it. We've enabled a better recipe but we're not going to make it that easy 🦊
