### ISSUE TITLE
Terracotta Siding Turns Into Bricks Moulding

### ISSUE THREAD

**Issue by Kinamet** [DarkPacks/SevTech-Ages#3318]
## Bug Report
Placing Terracotta Siding in front of a saw from Better With Mods turns it into Bricks Moulding. 

## Expected Behaviour
Terracotta Siding should become Terracotta Moulding according to JEI

## Steps to Reproduce (for bugs)

1. Acquire terracotta
2. Place in front of saw
3. Get terracotta siding
4. Repeat step 2
5.  Get bricks moulding

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
Already fixed for 3.1.0. _(And an issue for the same kind of issue was already closed).._
