### ISSUE TITLE
Misstyped triuph function

### ISSUE THREAD

**Issue by joker876** [DarkPacks/SevTech-Ages#3319]
there is a mistake in 
[prestige_add_500.txt](https://github.com/DarkPacks/SevTech-Ages/files/2319330/prestige_add_500.txt)
 a file (config/triumph/functions/prestige_add_500.txt). Now, command is: "prestige add @p 200" but should be "prestige add @p 500" as file name suggests.

**Comment by monodemono** [comment]
Doesn't matter, the prestige system isn't implemented yet anyways, and once it is it's likely going to be completely overhauled.

**Comment by JoelZBub** [comment]
I'd like to point out here that I've learned how to search closed reports to avoid creating duplicates.
