### ISSUE TITLE
Server crash using a PRC inside a compact machine

### ISSUE THREAD

**Issue by 0anth** [DarkPacks/SevTech-Ages#3320]
## Bug Report
When crafting a HDPE pellet with a Pressurized Reaction Chamber (PRC) from Mekanism, inside a compact machine from Compact Machines 3, the server crashes.

This results in a crash loop, requiring a server rollback to fix.

## Expected Behaviour
No issues crafting HDPE pellets in the overworld. Only occurring inside a compact machine world.

## Possible Solution
Updated Mekanism to the latest version, no change.

## Steps to Reproduce (for bugs)
1. Create a compact machine world and enter it
2. Spawn a Pressurized Reaction Chamber (PRC)
3. Provide it a pipe to eject out of the compact machine world
4. Provide it with Liquid Ethylene, Oxygen and Substrate
5. When progress bar hits 100% server will crash

## Logs
Client/Server Log:  https://pastebin.com/ckth6dRP

## Client Information
N/A

## World Information
Modpack Version world created in: 3.0.8
Additional Content Installed: N/A

## Server Information
* Java Version: 8 update 181
* Operating System: Windows 10 Enterprise x64
* Hoster/Hosting Solution: N/A
* Sponge (Non-Vanilla Forge) Server: N/A

**Comment by artdude543** [comment]
This would need reporting to the Mekanism tracker, as it's issue from the looks with pipe routing. Also, your solution of "updating" is not always the correct method. Unless the issue has been reported previously and fixed.
