### ISSUE TITLE
Better With Mods - Saw gives first moulding created, regardless of type-change

### ISSUE THREAD

**Issue by ranger135xp** [DarkPacks/SevTech-Ages#3321]
## Bug Report
The Better With Mods Saw will give you the same wood planks moulding that you created initially even when you change kinds.

## Expected Behaviour
If using Oak Wood on the Saw, Oak product is expected for all stages of cuts
If using Birch Wood on the Saw, Birch product is expected for all stages of cuts
Etc.

## Possible Solution
None found.

## Steps to Reproduce (for bugs)
1. Use Oak Wood Planks Siding with the Saw to craft Oak Wood Planks Moulding.
2. Next, use Birch Wood Planks Siding with the Saw and you get Oak Wood Planks Moulding.

Works if you start with Birch and try to make Oak, you'll get Birch instead.
The Siding pieces come out correctly, appears only Moulding is affected.
Have not tried with others. Does it even with all related stackables/items removed from inventory.
Does it until server reboot.

## Logs
Are they needed for this case?

## Client Information

* Modpack Version: 3.0.8
* Java Version: v8 181
* Launcher Used: ATL
* Memory Allocated: 6GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: Server-side: Chunk Pregenerator, Random Patches

## Server Information
* Java Version: v8 181
* Operating System: Debian
* Hoster/Hosting Solution: Local VM on Hyper-V
* Sponge (Non-Vanilla Forge) Server: No

**Comment by artdude543** [comment]
Great use of the search feature! This is already fixed for the next update.
