### ISSUE TITLE
Molten Iron WAILA Recipe Crash

### ISSUE THREAD

**Issue by GoodBob** [DarkPacks/SevTech-Ages#3324]
## Bug Report
When trying to see waila recipes on molten iron. Instant Crash 

## Expected Behaviour
Show molten iron recipes.

## Possible Solution
Not looking at molten iron's recipes.

## Steps to Reproduce (for bugs)
1. In at least Age 2, enter inventory, search for molten iron
2. Right or left click molten iron
3. Experience crash.

## Logs
* Client/Server Log: https://pastebin.com/s9WZ5xRZ
* Crash Log:

## Client Information
* Modpack Version: 3.0.8
* Java Version: 8 1.8.1
* Launcher Used: Twitch
* Memory Allocated: 7g
* Server/LAN/Single Player: Single Player
* Optifine Installed: N
* Shaders Enabled: N

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed:

**Comment by artdude543** [comment]
Fixed for 3.1.0
