### ISSUE TITLE
Server crashes upon launch

### ISSUE THREAD

**Issue by Jedacus** [DarkPacks/SevTech-Ages#3326]
Hi, my server crashes every time I launch it, I managed to join for about a minute and then it crashed again the last time I tried. I haven't edited any of the mod files or anything. Any help would be great thanks!
[crash-2018-08-26_12.27.36-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/2321672/crash-2018-08-26_12.27.36-server.txt)

**Comment by artdude543** [comment]
This kind of crash is non-fixable. But you can try the following.

- You can try re-generating the world
- Upgrade your Java to the latest **8** version. _(1.8.0_66 is very old)_
- Reinstall again and try again.

But that's the only options for the crash you got. Side note upload to PasteBin/Gist next time. Also, use the template we provide. Normally I'd auto-close and ignore. But I'm being nice today.
