### ISSUE TITLE
Disable Double Chests

### ISSUE THREAD

**Issue by rafikiblue565** [DarkPacks/SevTech-Ages#3327]
Hello all,

I am thoroughly enjoying this mod and had just a small suggestion.

While playing in Age 1 I do not want to invest in the early iron chests because I already have enough space with vanilla double chests.

My suggestion is to disable double chests until a later age, which would make for a stronger incentive to invest resources into the early iron chests.

Thank you,

Awesome mod.

**Comment by artdude543** [comment]
Ummm, why? And no, lol

We're not going to disable vanilla logic. People can use what they want for storage. We force so much but still allow the player to make their own choices.

We are not like other packs which tell you what to do all the time for force storage. Once things unlock you can do whatever in freedom. Having it all locked down makes people not want to play the pack/s.
