### ISSUE TITLE
Game crashes when opening the advancement panel after getting a certain advancement

### ISSUE THREAD

**Issue by thenwaf** [DarkPacks/SevTech-Ages#3328]
## Bug Report

The game crashes every time the "Age 2" tab of the advancements panel is opened. Started occuring after getting the tier 2 luminous crafting table achievement. This has softlocked my advancement, since I can't look at my age 2 advancement panel without my game crashing.

## Expected Behaviour

There are no problems with the other tabs of the advancement panel. Loading a previous backup and retrying yielded the same result, so I'm assuming it's either recreatable or my save file is haunted.

When clicked on the panel, it crashes instantly without showing the Age 2 panel at all.

## Possible Solution

A certain texture or block image (or anything) that appears in the advancements panel after getting the aforementioned advancement might not be loading properly.

## Steps to Reproduce (for bugs)

1. Get the achievement for the upgraded luminous crafting table
2. Open the "Age 2" section of the advancement panel
I'm not really sure.

## Logs

* Client/Server Log: [gist link](https://gist.github.com/thenwaf/b2074c1305d0cc47dafcf3dc955b8fb9)
* Crash Log: [pastebin link](https://pastebin.com/6VPWc6hK)

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.12.2 (modded) forge-14.23.4.2747
* Launcher Used: Twitch
* Memory Allocated: 5060 MB
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.7

* Additional Content Installed: None

**Comment by artdude543** [comment]
Already fixed for 3.1.0. Search is this amazing feature also!
