### ISSUE TITLE
AE2 Energy Cells way too late in ages and way too expensive to play this on a server without issues

### ISSUE THREAD

**Issue by mindforger** [DarkPacks/SevTech-Ages#3329]
I am playing this with some friends who are quite far and have already setup an pretty big ME system

they use large storage crate from actually additions and we figured out, that their ME system suffers from low power capacity, lagging the heck out of the server because it is constantly rebooting when someoone takes large amounts of items from it or drops items while mining in it

energy cells are an essential part for ME systems to work properly! they should not be kept so deep in late game and should be more affordable, because when played on servers, depending on how people set up their stuff, this puts immense and unrequired strain on the server

**Comment by artdude543** [comment]
They are staged in place for a reason. Re-Staging won't happen for anything in AE sorry.

In terms of this so-called "server strain" there is no evidence to support that from yourselves or from the mod itself (as most issues are public knowledge) and I've never come over this one before. And I run a lot of servers.

But in terms of the OP re-staging won't happen for the block sorry.

**Comment by mindforger** [comment]
>there is no evidence to support that from yourselves or from the mod itself 

If you watch the issue tracker from ae, this issue is very common, i am supporting on those issues regularily

What kind of evidence would you expect? We just did some testing by observing the movement of the sky and pricking myself with the sacrificial dagger on the blood altar while under regeneration effect, where the healing is stopping during tick lag. You could also observe this on the import bus, as it started to slow down.

Simply try it yourself.

Build an me System with 8 large chest, fill it with random stuff, including broken tools and armor (and other nbt heavy stuff), add and power it through only the me controller. Add one import chest and bus on max speed upgrade and now pull an inventory full of redstone and put it back in. Enjoy the tick lag

**Comment by artdude543** [comment]
I tested the layout specified last night. Along with booted up an old server with a massive network (which does not use any batteries) and I did not notice anything noticeable in terms of tick lag. The only lag was from an old version of a client-side mod being used.

After dipping over the issues over on AE. I still don't see a need to have to re-stage a part of tech to get around an issue with a mod. Stages are worked out for a reason to follow a tech flow. Recipes are also a set in a stone so won't be changed.

I'll look over the staging for 3.1.0 (as somethings shifted but from other mods) but as of current staging is locked down, so I can't promise anything. And no another issue is not needed.

**Comment by mindforger** [comment]
i will setup a local running server with sampler this evening and rebuild the setup

after looking through the code of AE2 you might be able to make this happen way quicker when leaving out the controller, so only use an acceptor, 6 storage busses on large crates filled to at least 50%, 1 terminal and one fully speed upgraded import bus, then drop down a large crate full of redstone dust and watch the import bus slowing down because of tickrate (internal feature) and try sampling at the same time ... i don't know exactly if there is any loggable information on when the ME runs out of power but it should run out of power for sure and reboot

**Comment by artdude543** [comment]
I'm aware that extensive testing can be done and the issue will arise. I'm not arguing that fact :P But that won't change the fact staging is solid and we don't like changing things to get around issues in mods.

But not how development/iterations work. Re-Staging is not just as simple as switching some configs, it's a major change which will affect players in current gameplay. I thank you for your commitment for wanting this to be known, and I don't need the proof from yourself I've had a chat with some devs on the matter. But from internal talks, it's still in the air if we even want to change the staging.

Based on the information we have on the pack and playthroughs most are using RS. And AE is sub-usage as people want to wait till later on in the gameplay (which is actually intended from our view) so that lessens the chance of a re-stage happening.

**Comment by artdude543** [comment]
And tbh Stage 5 is not hard to get into. If it's really an issue people want to get around making a dirty storage system and just complete the needed advancements for Stage 4 to step over to the next age.

**Comment by mindforger** [comment]
you'd wonder how less people care to read the instructions and flop an dirty ME together, thinking an ultimate energy cube has enough power .. but the input is limited by the capacity of the ME system per tick ... and start complaining about unfinished crafting jobs or only getting half a stack of items out the system

if you now even hide the energy cells in the next age you practically provoke this issue to happen that is my concern here

besides me and my friends running into this issue ... they already advanced that far and built some energy cells to eliminate the problem ... AE2 devs did not yet open up to change the internal capacity of several blocks with configs, because if the acceptor and controller would have a way bigger internal capacity the problem would not arise that early with such dirty setups

an controller has an internal power capacity of 8kAEU where the normal energy cell hast 200kAEU

i don't know how the acceptor is handling this, it seems to have no capacity but an internal RF Buffer that it can convert AEUs from (and i currently don't know the conversion ration either)

but maybe that is why plugging in a controller helps a little when using an acceptor but when only powering through the CPU does seem to be worse

**Comment by artdude543** [comment]
Yes, okay so that enforces my point I sent to AE a long time ago about adding configs or allowing the buffers to change.

I don't want/feel it's valid for a modpack to _fix_ or _dirty fix_ an issue which is purely a mod issue.

**Comment by mindforger** [comment]
well it isn't a mod issue, the design and the website clearly states that energy cells are to use for exactly this ... in your case it would be an remedy for a design flaw to move energy cells in a later age than the me system itself (not meant to sound rude but i don't know nicer words to translate it)

**Comment by artdude543** [comment]
As the designer currently. I'll reconsider the new information but in hindsight, it's a config which should be provided by the mod. Modpacks which use this new kind of staging method should not have to change our vision based on _limitations_ from the mods we use.

I'm aware of how clear it's stated, but that does not mean we _have_ to follow it like a bible. Your the first to report this issue. And I'm managing around 13 large YouTubers/Twitchers servers running the pack and we're yet to see this issue. (And some have massive networks already)

It's he said she said issue. I'll talk with the rest of the team later in regards. But from my current viewpoint, I still don't see/want to change the staging. As the issue itself is not produced enough to warrant the change. Also changing one battery then shifts the balance of the pack as then you have access earlier than we want. So again it's not a simple issue for us.

**Comment by mindforger** [comment]
>So again it's not a simple issue for us.

i know that standpoint/situation very well :) (man i need to improve my english skills a bit)
