### ISSUE TITLE
AE2 Fluid storage support (Extra Cells)

### ISSUE THREAD

**Issue by MaucnAD** [DarkPacks/SevTech-Ages#3330]
Since refined storage has fluid storage built into the mod, I feel Extra cells should be added for AE2 fluid support. It does need some recipe changes most likely so that it is a little balanced around the pack. 
It should be accesible at the same time Refined Storage is (Age 5).

I understand I can use Refined storage, but I dont like using both of the mods, and I like AE2 more. RS is just a way easier AE2

* Name: Extra cells 2

* CurseForge Link:
https://minecraft.curseforge.com/projects/extracells2

**Comment by MaucnAD** [comment]
Oh, and maybe wireless crafting monitor for AE2 as well? 

https://minecraft.curseforge.com/projects/wireless-crafting-terminal

**Comment by artdude543** [comment]
Duplicate of #1042
