### ISSUE TITLE
Server error when my friends try to enter!

### ISSUE THREAD

**Issue by xMaltez** [DarkPacks/SevTech-Ages#3332]
hey , i created a server , put my ip static and i forward my router ports , i did this all using this guide : https://www.youtube.com/watch?v=U-f4Ih6eSb0 ; and when my friends try to connect  this error still appears : ''io.netty.channel.abstractchannel$annotatedconnectexception connection refused no further information'' already search for solutions and i couldnt found nothing that solve that.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
