### ISSUE TITLE
Reference #925

### ISSUE THREAD

**Issue by Shovinus** [DarkPacks/SevTech-Ages#3333]
re: #925
(Made new because bot locked before I saw this)
I can make this compatible with Sevtech, I already actually use it on my private Sevtech server.
There is configs to stop abuse, such as not using falling entities and instead just placing the blocks in end position. I am currently looking also to see if it is possible to override the falling entity class so that the blocks will not pop off regardless.
I have already added tool exceptions, adding one for "hand" should not be a major issue.
As far as lag is concerned there is no lag as I have made a large effort to avoid, not only optimising the calculation but also offloading the calculation to a separate thread to stop any game lock up, it also has configs for max block moves per tick, as well as max blocks before doing a relocation move (so trees like redwoods or great oaks are not turned in to entities).
I have tested this in multiplayer and even if I chopped down a redwood no one else on the server could tell.

**Comment by Shovinus** [comment]
Also someone said it was added to Sevtech before, I don't see how that is possible given I had at that time only just released it.
Possibly he meant the old Chop Down mod, which tbh this mod only uses the idea of moving the tree to a 45 degree angle and then dropping, the rest of the code has been completely redone, re-optimised and configured. Part of which was offloading the calculation to a different thread. If there is one thing I cannot stand it is one persons actions affecting anothers gameplay experience.

**Comment by artdude543** [comment]
It's not being added. Regardless that it was in pre alpha versions. It was removed due to overheads it was causing and it's not worth the extra work for a minor addition. Your free to add it to your own version but it will never be added into the main pack.

We don't have to explain ourselves. No means no.

**Comment by Shovinus** [comment]
... I wasn't asking you to, just updating you on progress and differences. I am not the one who raised the original request for it. I just picked up on it while browsing and looking for bug reports. I keep trying to fine tune it.
Please hold off on the negative attitude I am just a coder trying to make the mod better for the community, the more input it has the faster I can fine tune it. If you have examples of it adding overhead I would information on it so I can check why and improve.

**Comment by artdude543** [comment]
I'm aware that you make the mod. But this was done ages ago from the early days of the pack, and the data with it is long gone.

You can try and reach out to Dark (when he's back from his holidays) to see if he still knows of the issues it was causing.

It's also not _negative attitude_ this is a bug tracker for the modpack. _(And all issues should follow the format we provide)_ Not a tracker for mods, the rules would need be upheld. You can ask about in our Discord if anyone has used the mod for data/feedback. But this tracker is not the place for it.
