### ISSUE TITLE
Crashed game is launched 

### ISSUE THREAD

**Issue by BlockBite** [DarkPacks/SevTech-Ages#3334]
## Bug Report
Game was launched, I saw a logo "SevTech Ages", and game was crushed (tried to launch 4 times = crush)
 
## Expected Behaviour
 Crush

## Steps to Reproduce (for bugs)

1.
2.

## Logs
 https://drive.google.com/open?id=1S-uZhWBl94Kq_fYuIsNIc7LIdBhpcMqN (log)

* Client/Server Log:
* Crash Log: https://pastebin.com/g7MS4Uu2 (crash report), 

## Client Information

* Modpack Version: 3.0.8
* Java Version: latest
* Launcher Used: TwitchApp
* Memory Allocated: 6 GB
* Server/LAN/Single Player: ---
* Optifine Installed: 3 times - nope, last time - yes
* Shaders Enabled: no

## World Information

* Modpack Version world created in:

* Additional Content Installed:

**Comment by artdude543** [comment]
Your Minecraft Install is broken/invalid. You can use the repair option on the dropdown for SevTech and Twitch will repair the install.

If still crashing after that re-install the entire pack. Also, make sure you're using D2 or D3 of Optifine as they are the only versions which work. (If your using it)

Other than that that's the steps to solve your crash issue.
