### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by Roosterington** [DarkPacks/SevTech-Ages#3339]
## Bug Report
Modpack crashes on startup

## Steps to Reproduce (for bugs)

1.Click play
2. Get message "An unexpected issues has occurred and the game crashed , we're sorry for the inconvenience"

## Logs

Couldn't get hash for net/minecraftforge/forge/1.12.2-14.23.4.2707/forge-1.12.2-14.23.4.2707.jar from https://modloaders.forgecdn.net/647622546/maven/net/minecraftforge/forge/1.12.2-14.23.4.2707/forge-1.12.2-14.23.4.2707.jar.sha1: HTTP 403: Forbidden
--
13:35:27 | launcher | Have local file C:/Users\filip\OneDrive\Documents\Curse\Minecraft\Install\libraries\net/minecraftforge/forge/1.12.2-14.23.4.2707/forge-1.12.2-14.23.4.2707.jar but don't know what size or hash it should be. Have to assume it's good.
13:35:27 | launcher | Couldn't get hash for org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar.sha1: HTTP 403: Forbidden
13:35:27 | launcher | Couldn't get hash for org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar.sha1: HTTP 403: Forbidden
13:35:27 | launcher | Couldn't get hash for org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar.sha1: HTTP 403: Forbidden
13:35:27 | launcher | Couldn't get hash for org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar.sha1: HTTP 403: Forbidden
13:35:27 | launcher | Have local file C:/Users\filip\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/ow2/asm/asm-all/5.2/asm-all-5.2.jar but don't know what size or hash it should be. Have to assume it's good.
13:35:27 | launcher | Have local file C:/Users\filip\OneDrive\Documents\Curse\Minecraft\Install\libraries\jline/jline/2.13/jline-2.13.jar but don't know what size or hash it should be. Have to assume it's good.
13:35:27 | launcher | Have local file C:/Users\filip\OneDrive\Documents\Curse\Minecraft\Install\libraries\com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar but don't know what size or hash it should be. Have to assume it's good.
13:35:27 | launcher | Have local file C:/Users\filip\OneDrive\Documents\Curse\Minecraft\Install\libraries\com/typesafe/config/1.2.1/config-1.2.1.jar but don't know what size or hash it should be. Have to assume it's good.
13:35:27 | launcher | Have local file C:/Users\filip\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar but don't know what size or hash it should be. Have to assume it's good.
13:35:27 | launcher | Couldn't get hash for org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar.sha1: HTTP 403: Forbidden
13:35:27 | launcher | Have local file C:/Users\filip\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
13:35:27 | launcher | Have local file C:/Users\filip\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
13:35:27 | launcher | Have local file C:/Users\filip\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
13:35:27 | launcher | Have local file C:/Users\filip\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
13:35:27 | launcher | Couldn't get hash for org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar.sha1: HTTP 403: Forbidden
13:35:27 | launcher | Have local file C:/Users\filip\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar but don't know what size or hash it should be. Have to assume it's good.
13:35:27 | launcher | Couldn't get hash for org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar.sha1: HTTP 403: Forbidden
13:35:27 | launcher | Have local file C:/Users\filip\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar but don't know what size or hash it should be. Have to assume it's good.
13:35:27 | launcher | Couldn't get hash for org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar.sha1: HTTP 403: Forbidden
13:35:27 | launcher | Have local file C:/Users\filip\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar but don't know what size or hash it should be. Have to assume it's good.
13:35:27 | launcher | Couldn't get hash for org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar from https://modloaders.forgecdn.net/647622546/maven/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar.sha1: HTTP 403: Forbidden
13:35:27 | launcher | Have local file C:/Users\filip\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar but don't know what size or hash it should be. Have to assume it's good.
13:35:27 | launcher | Couldn't get hash for org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar from https://modloaders.forgecdn.net/647622546/maven/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar.sha1: HTTP 403: Forbidden
13:35:27 | launcher | Have local file C:/Users\filip\OneDrive\Documents\Curse\Minecraft\Install\libraries\org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar but don't know what size or hash it should be. Have to assume it's good.
13:35:28 | launcher | Couldn't get hash for 1.12.2 jar from https://s3.amazonaws.com/Minecraft.Download/versions/1.12.2/1.12.2.jar.sha1: HTTP 403: Forbidden
13:35:28 | launcher | Have local file C:/Users\filip\OneDrive\Documents\Curse\Minecraft\Install\versions\1.12.2/1.12.2.jar but don't know what size or hash it should be. Have to assume it's good.
13:35:29 | launcher | Checking installations.
13:35:29 | launcher | Minecraft client forge-14.23.4.2707 is ready to start.
13:35:29 | launcher | Starting!
13:35:30 | launcher | Using default game log configuration client-1.12.xml (outputs XML)
15:35:33 | game | 2018-09-01 13:35:33,338 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream   <log4j:Event logger="LaunchWrapper" timestamp="1535801733668" level="INFO" thread="main">     <log4j:Message><![CDATA[Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker]]></log4j:Message>   </log4j:Event>
15:35:33 | monitor | expected <
13:35:33 | LaunchWrapper | Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
13:35:33 | LaunchWrapper | Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
13:35:33 | FML | Forge Mod Loader version 14.23.4.2707 for Minecraft 1.12.2 loading
13:35:33 | FML | Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\filip\OneDrive\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_51
13:35:46 | FML | Searching C:\Users\filip\OneDrive\Documents\Curse\Minecraft\Instances\SevTech Ages\mods for mods
13:35:46 | FML | Searching C:\Users\filip\OneDrive\Documents\Curse\Minecraft\Instances\SevTech Ages\mods\1.12.2 for mods
13:35:46 | FML | Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.1.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
15:35:46 | game | 2018-09-01 13:35:46,228 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream 2018-09-01 13:35:46,242 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream   <log4j:Event logger="FML" timestamp="1535801746307" level="WARN" thread="main">     <log4j:Message><![CDATA[The coremod AppleCore (squeek.applecore.AppleCore) is not signed!]]></log4j:Message>   </log4j:Event>
15:35:46 | monitor | expected <
13:35:46 | FML | Found FMLCorePluginContainsFMLMod marker in Aroma1997Core-1.12.2-1.3.0.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
13:35:46 | FML | The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
13:35:46 | FML | Found FMLCorePluginContainsFMLMod marker in astralsorcery-1.12.2-1.8.10.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
13:35:46 | FML | The coremod hellfirepvp.astralsorcery.core.AstralCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
13:35:46 | FML | [AstralCore] Initialized.
13:35:46 | FML | Found FMLCorePluginContainsFMLMod marker in BetterFoliage-MC1.12-2.1.10.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
13:35:46 | FML | The coremod mods.betterfoliage.loader.BetterFoliageLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
13:35:46 | FML | The coremod BetterFoliageLoader (mods.betterfoliage.loader.BetterFoliageLoader) is not signed!
13:35:46 | FML | Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
13:35:46 | FML | The coremod com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
13:35:46 | FML | Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
13:35:46 | FML | Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12-0.3.0.15.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
13:35:46 | FML | The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
13:35:46 | FML | The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
13:35:46 | FML | Found FMLCorePluginContainsFMLMod marker in Farseek-1.12-2.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
13:35:46 | FML | The coremod farseek.core.FarseekCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
13:35:46 | FML | The coremod FarseekCoreMod (farseek.core.FarseekCoreMod) is not signed!
13:35:46 | FML | Found FMLCorePluginContainsFMLMod marker in foamfix-0.9.9.1-1.12.2-anarchy.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
13:35:46 | FML | The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
13:35:46 | FML | Found FMLCorePluginContainsFMLMod marker in Forgelin-1.6.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
13:35:46 | FML | The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
13:35:46 | FML | The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
13:35:46 | FML | Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.64-dev.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
13:35:46 | FML | The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
13:35:46 | FML | The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
13:35:46 | FML | The coremod IvToolkit (ivorius.ivtoolkit.IvToolkitLoadingPlugin) is not signed!
13:35:47 | FML | The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
13:35:47 | FML | The coremod MicdoodlePlugin (micdoodle8.mods.miccore.MicdoodlePlugin) is not signed!
13:35:47 | FML | The coremod api.player.forge.PlayerAPIPlugin is requesting minecraft version 1.12.1 and minecraft is 1.12.2. It will be ignored.
13:35:47 | FML | Found FMLCorePluginContainsFMLMod marker in Quark-r1.4-123.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
13:35:47 | FML | The coremod vazkii.quark.base.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
13:35:47 | FML | The coremod LoadingPlugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
13:35:47 | FML | Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
13:35:47 | FML | The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
13:35:47 | FML | Found FMLCorePluginContainsFMLMod marker in SmoothFont-1.12.2-1.15.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
13:35:47 | FML | The coremod bre.smoothfont.asm.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
13:35:47 | FML | The coremod CorePlugin (bre.smoothfont.asm.CorePlugin) is not signed!
13:35:47 | FML | The coremod blusunrize.immersiveengineering.common.asm.IELoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
13:35:47 | LaunchWrapper | Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
13:35:47 | LaunchWrapper | Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
13:35:47 | LaunchWrapper | Loading tweak class name codechicken.asm.internal.Tweaker
13:35:47 | LaunchWrapper | Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
13:35:47 | LaunchWrapper | Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
13:35:47 | LaunchWrapper | Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
13:35:47 | LaunchWrapper | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
13:35:49 | FML | Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty.
13:35:49 | LaunchWrapper | Unable to launch java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt. 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:166) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt. 	at net.minecraftforge.fml.common.patcher.ClassPatchManager.applyPatch(ClassPatchManager.java:113) 	at net.minecraftforge.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:76) 	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:219) 	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:192) 	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:161) 	at net.minecraftforge.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:187) 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:161) 	... 2 more
15:35:49 | game | Exception in thread "main"   <log4j:Event logger="STDERR" timestamp="1535801749158" level="INFO" thread="main">     <log4j:Message><![CDATA[[java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException]]></log4j:Message>   </log4j:Event>
15:35:49 | monitor | expected <
13:35:49 | STDERR | [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
13:35:49 | STDERR | [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
13:35:49 | STDERR | [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
13:35:49 | STDERR | [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
13:35:49 | STDERR | [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
13:35:49 | STDERR | [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
13:35:49 | launcher | Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
15:35:49 | monitor | Process crashed with exit code 1

## Client Information

* Modpack Version: 3.0.8
* Java Version: Don't know , i believe latest
* Launcher Used: Twitch
* Memory Allocated: -Xmx3072m -Xms256m
* Server/LAN/Single Player: single player ( doesn't matter , game crashes on startup)
* Optifine Installed: no
* Shaders Enabled: no

**Comment by artdude543** [comment]
Your game install is broken. Reinstall the entire pack and use the Repair Minecraft option for the pack.

Also, learn to use PasteBin plz!
