### ISSUE TITLE
Sevtech/Venus/Corrosion Compatibility

### ISSUE THREAD

**Issue by Pandoxy** [DarkPacks/SevTech-Ages#3340]
## Bug Report

Corrosion on Venus still after the supposed fix in 3.0.8 still destroys your armour and kills you within two minutes. Nearly impossible to get the shield controller to even survive that.

## Expected Behaviour

In regular Galacticraft you are able to just tank the armour murder with regular vanilla armour, but with the addition of extra planets you need that space suit to even survive anywhere. So normally it would be possible with armour but not with Extra Planets.

## Possible Solution

I would suggest either moving the shield controller spawn to the Asteroids, possibly somewhere in those abandoned space stations that are in the asteroids, or even just in the mars dungeon. Rather why not remove corrosion entirely from Venus itself?

## Steps to Reproduce (for bugs)

1. Equip required gear for Venus (breathing equipment, tier 2 armour & tier 2 thermal padding)
2. Go to Venus
3. Get absolutely destroyed by the corrosion.
4. Realize you cannot get the shield controller.

## Logs

* Client/Server Log: no crash
* Crash Log: no crash

## Client Information

* Modpack Version: 3.0.8
* Java Version:
* Launcher Used: Twitch
* Memory Allocated: 10Gb ish
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: No

**Comment by artdude543** [comment]
Corrosion is not _"disabled"_ but radiation was turned off. This would be an issue to take up with MJR on his tracker. Unless @MJRLegends wants to take info here and reply?

**Comment by MJRLegends** [comment]
@artdude543 Fixed in latest version sevtech released version is very old by now :D

**Comment by artdude543** [comment]
Sweet so this is fixed for 3.1.0 then ^_^
