### ISSUE TITLE
Crash on Advancements Twilight forest tab, and age 2 tab.

### ISSUE THREAD

**Issue by Phantum** [DarkPacks/SevTech-Ages#3341]
## Bug Report
open advancements, click either twilight forest, or age 2, proceed to watch game crash.

## Expected Behaviour
show me the age to advancements

## Possible Solution
no idea

## Steps to Reproduce (for bugs)
1. log into server
2. open advancements and click on age 2, or twilight forest.

## Logs
* Client/Server Log:
* Crash Log: https://pastebin.com/4kLKrYt5

## Client Information
* Modpack Version: 3.0.8
* Java Version: 1.8.0.181
* Launcher Used: Twitch
* Memory Allocated: 10,752 MB
* Server/LAN/Single Player: server
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in: 3.0.1
* Additional Content Installed: schematica, mclink

## Server Information
* Java Version: 1.8.0.181
* Operating System:linux
* Hoster/Hosting Solution: nodecraft

**Comment by Phantum** [comment]
Must have been a corrupted mod installation or something.  Downgrading back to 3.0.7 and then back to 3.0.8 seems to have fixed it.

**Comment by artdude543** [comment]
Will be fully fixed in 3.1.0 :)
