### ISSUE TITLE
Pneumaticcraft Minigun dealing no damage

### ISSUE THREAD

**Issue by elitegmr** [DarkPacks/SevTech-Ages#3343]
## Bug Report

I tried out using the pneumaticcraft minigun in creative mode, and trying to shoot enemies with it does no damage most of the time. Every once in a great while (say once every 5-10 seconds) it might hit an enemy once for 12 damage or so, but that's it. I tried holding down the right mouse button, clicking the right mouse button repeatedly, using different types of ammo, using it on different mobs (vanilla and other mods), and being in creative or survival mode. EDIT: oh yeah and the gun definitely looks like it's firing and all, it's got the bullet spraying animation, the noises, it's using up ammo, but enemies completely ignore it and don't even flash red or anything.

## Expected Behaviour

The weapon should probably do damage at a decent rate, I'd imagine.

## Possible Solution

Remove the crafting recipe if it turns out the weapon is indeed broken.

## Steps to Reproduce (for bugs)

1. Make a new creative world.
2. Spawn in a minigun and some gun ammo.
3. Try shooting any mob with it.

## Logs

* Client/Server Log: https://pastebin.com/wS2eX9hy
* Crash Log: none

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_181
* Launcher Used: ATLauncher
* Memory Allocated: 4GB
* Server/LAN/Single Player: single player
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: none

**Comment by artdude543** [comment]
As this is indeed an issue with Pneumaticcraft can you report this with them? Going to close this one as it's a pure issue with the mod. But feel free to link back to this issue on your other report :)

Thanks for reporting tho!
