### ISSUE TITLE
Can't enter and stay in the Sevtech server after reaching the Creative Stage

### ISSUE THREAD

**Issue by Maxcrss** [DarkPacks/SevTech-Ages#3345]
## Bug Report
I didn't have an issue with logging into the server and staying on before reaching the creative stage. After I reached the creative stage, I was disconnected from the server, and any time I try to enter the server at my base I either get disconnected, bumped to the server hub, or I crash. Logs are not always. 

## Expected Behaviour
Not getting kicked. 

## Possible Solution
No freaking clue

## Steps to Reproduce (for bugs)

1.
2.

## Logs
* Client/Server Log:

[2018-08-31-1.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2349872/2018-08-31-1.log.gz)
[2018-08-31-2.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2349873/2018-08-31-2.log.gz)
[2018-09-01-1.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2349874/2018-09-01-1.log.gz)
[2018-09-01-2.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/2349875/2018-09-01-2.log.gz)

* Crash Log:
This is the only crash report that I have since the issue started.

[crash-2018-08-26_14.11.21-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/2349877/crash-2018-08-26_14.11.21-client.txt)

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_181
* Launcher Used: Twitch
* Memory Allocated: 4098 before the disconnects started happening, up to 8196 after
* Server/LAN/Single Player: Server
* Optifine Installed: Yes
* Shaders Enabled: No

## World Information

Modpack Version world created in: 3.0.7

Additional Content Installed: Tick Profiler, BetterChunkloader, Universeguard, Stackban, Prism, Nucleus, LuckPerms, GriefPrevention, Spark, and a custom plugin written by developers of our staff team)

## Server Information
Java Version: 1.8.0_161, Oracle Corporation
Operating System: Linux (amd64) version 4.9.33-mod-std-ipv6-64
Hoster/Hosting Solution: OVH Canada
* Sponge (Non-Vanilla Forge) Server: spongeforge-1.12.2-2705-7.1.0-BETA-3422

**Comment by artdude543** [comment]
Sponge support needs to go via the Discord. We don't offer support from servers using Sponge. But some of the devs and people who would help are in our Discord.
