### ISSUE TITLE
"Minecraft failed to start!" Error when launching from ATLauncher suddenly

### ISSUE THREAD

**Issue by ElitistEllie** [DarkPacks/SevTech-Ages#3347]
Pack was launching fine from ATL, then one day I saw a post saying the vanillafix mc mod was good for when the pack crashes so I don't have to wait to relaunch, installed that no problem game still ran fine, but recently I tried using the CurseForge server files (https://minecraft.curseforge.com/projects/sevtech-ages/files/2570732#additional-files) to host a multiplayer server with my friend, but now my game crashes during modpack loadup and Vanillafix gives me a "Minecraft failed to start!" error, if I disable Vanillafix the application just closes and the launcher opens again

https://paste.dimdev.org/wojekufoxu.mccrash

this is the log Vanillafix gives me a link to, not really sure what I can do as I can't really understand the log

**Comment by artdude543** [comment]
Known issue for Vanilla (Has been a bug since Alpha) you'll need to try from re-installing graphics drivers/Java and rebooting the PC.

As it's an issue between the JVM and Graphics. Something we can't control.
