### ISSUE TITLE
Spawner Seeker Crahes the game

### ISSUE THREAD

**Issue by tkkot** [DarkPacks/SevTech-Ages#3351]
## Bug Report

Using the Spawner Seeker sometimes crashes the client.

## Expected Behaviour

The game crashes when using the Seeker.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
[latest.log](https://github.com/DarkPacks/SevTech-Ages/files/2363277/latest.log)

* Crash Log:
[crash-2018-09-08_13.48.15-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/2363278/crash-2018-09-08_13.48.15-server.txt)

## Client Information

* Modpack Version:3.0.8
* Java Version:8 181
* Launcher Used:Twitch Launcher
* Memory Allocated:10204 MB
* Server/LAN/Single Player:Single Player
* Optifine Installed:Yes
* Shaders Enabled:No

## World Information

* Modpack Version world created in:3.0.6?

* Additional Content Installed:
Opti-Fine

**Comment by artdude543** [comment]
Should be resolved for 3.1.0 when it ships.
