### ISSUE TITLE
Sigils don't work in Sigil of Holding unless they've been used first

### ISSUE THREAD

**Issue by littlebeast** [DarkPacks/SevTech-Ages#3352]
### Bug Report
If a new sigil from Blood Magic is placed into the Sigil of Holding without first using it, the sigil will not function.

### Expected Behaviour
One would expect it to immediately work upon creation.

### Steps to Reproduce

1. Create a new sigil.
2. Without using it, place the sigil into the Sigil of Holding.
3. Attempt to use it.

### Context
In the end of Age 2.

### Client Information
- Modpack Version: 3.0.8
- Java Version: Version 8 Update 171
- Launcher Used: Twitch
- Memory Allocated: ? (6.7GB Available)
- Server/LAN/Single Player: Single Player
- Resourcepack Enabled?: No
- Optifine Installed?: No

**Comment by artdude543** [comment]
This is intended from the mod. That you need to bind them first.
