### ISSUE TITLE
Crashes on first launch

### ISSUE THREAD

**Issue by hjoyn** [DarkPacks/SevTech-Ages#3353]
Bug Report
Attempting to launch the pack for the first time results in a crash near end of loading. 

Expected Behaviour
The game launches successfully. 

Possible Solution
Unknown. 

Steps to Reproduce (for bugs)
1. Launch the game. 

Logs:
Latest Log:
https://www.dropbox.com/s/f8jfv7knqlljb6p/latest.log?dl=0

Crash Log:
https://www.dropbox.com/s/74tvnozbqn7ldxv/crash-2018-09-10_18.33.25-client.txt?dl=0

Client Information
Modpack Version: 3.0.8
Java Version: 8.181
Launcher Used: MultiMC
Memory Allocated: 4096 MB
Server/LAN/Single Player: Single Player
Optifine Installed: No
Shaders Enabled: No
World Information:
No world created
Additional Content Installed:
None

**Comment by TheSnowyChickens** [comment]
Try with more memory.

**Comment by hjoyn** [comment]
5 gb of ram results in it launching, thanks. What is the recommended memory allocation, and, if applicable, jvm settings?
