### ISSUE TITLE
Sevtech crashes after using a Galacticraft Cryogenic Chamber 

### ISSUE THREAD

**Issue by jnwebster** [DarkPacks/SevTech-Ages#3354]
## Bug Report
I'm in Sevtech 3.0.8 and I'm beginning the Galacticraft grind.
I set up a small base on Mars and put in a Cryogenic Chamber to sleep through the night.
I use Astral Sorcery's Celestial Gateway to travel back and forth between my Mars base and my overworld base.

I slept in the Cryogenic Chamber once, returned to the overworld shortly after, and on my return trip to Mars (using the celestial gateway) the game crashed.
Here is the crashdump from that initial crash:
Crash 1: https://pastebin.com/UH0RybyK

I restarted the game after this, and now every time I attempt to use the Cryogenic Chamber it crashes again.
Here are the two crashdumps from those events:
Crash 2: https://pastebin.com/YarHPaRq
Crash 3: https://pastebin.com/uayxGFP4

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
