### ISSUE TITLE
Added Rubies Mod to SevTech

### ISSUE THREAD

**Issue by VirxEpicoder** [DarkPacks/SevTech-Ages#3355]
## Context

It would make age 5 (or 6) awesome because if you get a lot of diamonds you can become the most OP thing ever, and get very powerful and durable armor and tools. There's not just rubies; there's other things like tanzanite, emerald, and morganite (and others, like invisible armor, golden armor, lit blocks, and still more.) Some of the things (like steel) may be able to be unlocked in age 3 or before. (Also, it does add some ore gen.) If it helps, this mod is an open source mod.

## Mod Details
* Name: Rubies Mod
* CurseForge Link: [To Rubies Mod -->](https://minecraft.curseforge.com/projects/rubies-mod?gameCategorySlug=mc-mods&projectID=298036)

**Comment by artdude543** [comment]
Thanks for your suggestion for the mod. But sadly it does not meet the needs/wants for the pack. The pack has a set route/mining mechanic/design. To which this mod would change that and imbalance a lot of mods/recipes.

The armor is nice along with other tools. But you can achieve close/similar traits from TiC and AS.

But thanks for the suggestion tho!
