### ISSUE TITLE
Multiplying Water Wheel (Better With Mods)

### ISSUE THREAD

**Issue by Zaalu** [DarkPacks/SevTech-Ages#3358]
## Bug Report
When you break an axle that has a water wheel on it it will drop 2 water wheels instead of the 1 on it.
I have successfully endlessly multiplied water wheels from a single one this way.

## Expected Behaviour
It should only drop the water wheel on it (1).

## Steps to Reproduce (for bugs)
Attach a water wheel (better with mods) to an axle and then break the axle with an axe (dead center of water wheel)

## Client Information
* Modpack Version: 3.0.8
* Java Version: Version 8 Update 171 (build 1.0.8_171_b11)
* Launcher Used: Twitch
* Memory Allocated: 6GB
* Server/LAN/Single Player: Single Player and Multiplayer
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed: None

**Comment by Serolar** [comment]
This will be fixed in the next release of Sevtech, to my understanding, due to about 8 duplicate reports of this. 
See closed issue #2971
