### ISSUE TITLE
Crash using Biblocraft Tapemeasure

### ISSUE THREAD

**Issue by Goreko** [DarkPacks/SevTech-Ages#3359]
## Bug Report
Crash on use of Biblocraft tape measure, used to work fine but now fails at rendering a pole and crashes game upon loading into the server, just my client crashes.

## Expected Behaviour
Not to crash when using tape measure

## Steps to Reproduce (for bugs)

1. Be me
2. ???
3. Do not profit

## Logs

* Client/Server Log: [https://gist.github.com/Goreko/d1d6214f26bfaa8431b41655f67843b8]
[2018-09-12-3.log](https://github.com/DarkPacks/SevTech-Ages/files/2373814/2018-09-12-3.log)
[crash-2018-09-12_02.03.50-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/2373815/crash-2018-09-12_02.03.50-client.txt)

* Crash Log: [https://pastebin.com/uk2PXy6c]

## Client Information

* Modpack Version: 3.0.8
* Java Version:  Version 8 update 181 build 1.8.0_181-b13
* Launcher Used: Twitch
* Memory Allocated: 7.8 Gb
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: Vivecraft, not used by myself

## Server Information
* Java Version: Version 8 update 181 build 1.8.0_181-b13
* Operating System: Windows 10
* Hoster/Hosting Solution: Friends Server, using default hosting technique
* Sponge (Non-Vanilla Forge) Server:

**Comment by Serolar** [comment]
The crash log (I missed the pastebin link first time around) seems to mention Bibliocraft and Better Foliage, and testing this in my single-player world, without Better Foliage, yields no crash. 
A more accurate Step Process might be:
1. Have Better Foliage active on client.
2. Use Bibliocraft Tape Measure on surface.
3. Scan Crash log for consistency.

Thank you for your time,
Serolar

**Comment by artdude543** [comment]
Should be resolved for 3.1.0 (when it comes out)
