### ISSUE TITLE
Game Crash When opening the Creative Menu

### ISSUE THREAD

**Issue by hilo1009** [DarkPacks/SevTech-Ages#3361]
## Bug Report
I have just recently unlocked Age 3, and I switched my gamemode to creative to grab a block (i know i was being lazy). Upon trying to open the inventory the game crashes.
## Expected Behavior
Instead of being able to access the creative tabs (which I have done before) the game crashes.
## Logs
https://pastebin.com/embed_js/4Zbb5kZC

## Client Information
* Modpack Version:3.0.8
* Java Version:
* Launcher Used:Twitch
* Memory Allocated:8.5gb
* Server/LAN/Single Player:Single Player
* Optifine Installed:Yes
* Shaders Enabled:No

* Additional Content Installed: Vein Miner

**Comment by artdude543** [comment]
Fixed for 3.1.0. Learn to search closed issues. Thanks!
