### ISSUE TITLE
crash opening backpack

### ISSUE THREAD

**Issue by bignose100** [DarkPacks/SevTech-Ages#3362]
I am unsure how to read crash logs and dont know why the mod pack crashes when i open an improved backpack.  Please help

[crash-2018-09-13_16.09.10-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/2380856/crash-2018-09-13_16.09.10-client.txt)

**Comment by monodemono** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
