### ISSUE TITLE
Crash in the Beneath

### ISSUE THREAD

**Issue by ShadeofDunwall** [DarkPacks/SevTech-Ages#3381]
Alright, so first off, i'm new to working with this all of this, so sorry if i did something wrong. this is my first real delving into modded minecraft, and bug reports.

## Bug Report
I'm most of the way through age 1, currently working on getting aquamarine. however, i left the game inside the beneath, and now my world won't load. minecraft starts, i've created and loaded a new world and it seems to work just fine, but my existing world won't load, it just crashes minecraft. i'm using ATLauncher.

## Expected Behaviour
I expect my world to load.

## Possible Solution
???

## Steps to Reproduce (for bugs)
I don't know. exit minecraft in the beneath?

## Logs
The ATLauncher gives this error: "Exception in thread "Client Shutdown Thread" AL lib: (EE) alc_cleanup: 1 device not closed"
note: i only have minecraft open, so i'm not sure what it's saying isn't closed.
Here's the crash report: https://pastebin.com/KSzsrH2E

## Client Information

* Modpack Version: Sevtech: Ages 3.0.8
* Java Version: Java\jre1.8.0_181
* Launcher Used: ATLauncher
* Memory Allocated: 256 initial,  4096 maximum
* Server/LAN/Single Player: Singleplayer, Enter LAN to activates cheats
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8, the sevtech preset.
* Additional Content Installed: None

**Comment by thedarkcolour** [comment]
Change the difficulty of the world in level.dat. Use NBTExplorer and edit the Difficulty:2 entry to Difficulty:0

**Comment by artdude543** [comment]
Fixed for 3.1.0
