### ISSUE TITLE
Shutting down internal server between dimensions

### ISSUE THREAD

**Issue by BananaTassium** [DarkPacks/SevTech-Ages#3385]
# Bug Report
I'm having a bug that has actually been reported before and supposedly fixed, but I never stopped having the issue. To quickly summarize, when going between dimensions on occasion (realistically, it's actually around 50% of the time) it tells me 'shutting down internal server' and I have to re-open the save. It was reported on 3.0.6 in issue #1911 it looks like, and I'm currently playing on 3.0.8, but it is still happening.

## Expected Behaviour
I would expect that it would load normally.
## Possible Solution
???

## Steps to Reproduce (for bugs)
1. Go between dimensions

## Logs
* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 3.0.8
* Java Version: 1.8.0.181?
* Launcher Used: Twitch
* Memory Allocated: 8192 MB
* Server/LAN/Single Player: Single player
* Optifine Installed: Nope
* Shaders Enabled: Nope

## World Information
* Modpack Version world created in: 3.0.6 or 3.0.5 I think.
* Additional Content Installed: None

**Comment by artdude543** [comment]
Closing as you failed to follow the template and give logs. Also refer to discord for help.
