### ISSUE TITLE
Client Crash when entering server

### ISSUE THREAD

**Issue by MayusYT** [DarkPacks/SevTech-Ages#3388]
## Bug Report

Client crashes when joining a server
Client crash log: https://pastebin.com/uPMrH5d2

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log: Server: https://pastebin.com/7yF1XkXS
* Crash Log: https://pastebin.com/uPMrH5d2

## Client Information

* Modpack Version: 3.0.8
* Java Version: 10
* Launcher Used: Twitch
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Server
* Optifine Installed: /
* Shaders Enabled: /

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: /

## Server Information
* Java Version: 8
* Operating System: Windows 10
* Hoster/Hosting Solution: Self-hosted
* Sponge (Non-Vanilla Forge) Server: Yes

## Server log
https://pastebin.com/7yF1XkXS

**Comment by artdude543** [comment]
Will be fixed in 3.1.0
