### ISSUE TITLE
Add FastFurnace

### ISSUE THREAD

**Issue by Shadows-of-Fire** [DarkPacks/SevTech-Ages#3390]
## Context
FastFurnace is a mod that provides a significant (>70%) performance increase for the furnace.  I've probably mentioned this to Darko already, and it may already be in for next update, but I figured I'd drop this here anyway.

## Mod Details
* Name: FastFurnace
* CurseForge Link: https://minecraft.curseforge.com/projects/fastfurnace

**Comment by artdude543** [comment]
Added in the 3.1.0 update
