### ISSUE TITLE
Make IE Excavator Mine Platinum! (and others)

### ISSUE THREAD

**Issue by blasksun** [DarkPacks/SevTech-Ages#3391]
Pack version - 3.0.8
Geolosys version - 1.12.2-1.9.3
Forge version- 14.23.4.2707

As i have found out Immersive Engineering Excavator multi-block only spins aimlessly without spilling any ore items while mining Platinum so i've gone and investigated matter? which resulted in finding that crafttweaker file config is all wrong on adding materials to Excavator.

The file at:
> src/scripts/crafttweaker/integrations/mods/immersive/engineering/excavator.zs

Should be changed on: 
   `  "platinum.addOre("geolosysOrePlatinum", 0.50);"`
 to 
    `  "platinum.addOre("oreGeolosysPlatinum", 0.50);" `
for OreBlock variant (which doesnt have uses on its own)
or more logically to 
   `platinum.addOre("orePlatinum", 0.50); `
for OreItem drop, so it would be usable.

I could of ended it here, but I've looked thru all excavatable ores and fixed their names to oredict names
so now all of them should be minable.  [attached link](https://github.com/blasksun/SevTech-Fix/blob/master/excavator.zs)

**Comment by artdude543** [comment]
Going to tag this to this issue #3025
