### ISSUE TITLE
The torch launcher works on the moon

### ISSUE THREAD

**Issue by TKDWarrior** [DarkPacks/SevTech-Ages#3392]
## Bug Report
The torch launcher is able to place normal torches on the moon 

## Expected Behaviour
standard minecraft torches shouldn't work on moon. 

## Possible Solution
probably just a true/false flag somewhere in the code

## Steps to Reproduce (for bugs)

1. Build a torch launcher from Cyclic
2. Go to the moon
3. shoot torches everywhere

## Logs

* Client/Server Log: https://gist.githubusercontent.com/TKDWarrior/8172c9c1d090b55733c106448f7e82ed/raw/ae10afe5143d15edd07124118fa62fb85ec5d05a/latest.log
* Crash Log: N/A didn't crash

## Client Information

* Modpack Version: 3.0.8
* Java Version: version 8 update 181
* Launcher Used: twitch
* Memory Allocated: ~7Gb
* Server/LAN/Single Player: Server
* Optifine Installed:no
* Shaders Enabled:don't think so?  don't know

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed:

**Comment by artdude543** [comment]
@PrinceOfAmber would this be something you'd need to add a case support for? I don't feel this is on GC as it's nothing to do with them. It's also an _eh_ issue in regards it's not breaking or anything.

**Comment by artdude543** [comment]
After reviewing this again. I feel it's not worth the hassle for the mods to add specific support for mods and dimensions that _should_ not do _x or y_.

This is purley up to the modders on both sides if they should add support/checks for this. But we won't be forcing this upon them to do. Thanks for the report tho!
