### ISSUE TITLE
Hearty Stew bug

### ISSUE THREAD

**Issue by xtended2l** [DarkPacks/SevTech-Ages#3393]
## Bug Report
Hey! Hearty Stew is not consumed when I eat, while it gives me intended amount of saturation. Moreover, it returns empty bowls each time I eat. I am at age 1 currently, version 3.0.8, regular installation, dont know what to add.

## Expected Behaviour
Hearty Stew should disappear from the inventory when consumed.

## Client Information
Modpack Version: 3.0.8
Forge Version: forge-14.23.4.2760
Java Version: ...
Launcher Used: twitch
Memory Allocated: 8175
Server/LAN/Single Player: SP/LAN/MP
Optifine Installed: NO
Shaders Enabled: NO

**Comment by jngeist** [comment]
Deeply odd--I'm also on 3.0.8 and not experiencing this issue. Returning empty bowls is intended, I believe, but the stew itself should obviously be removed from your inventory.

Two questions to make sure that I'm not making false assumptions. First, are you in creative? I assume not, but I think that would explain items not being consumed on use. Second, is there a second stack of hearty stew in your inventory? If your inventory is being auto-sorted, that would possibly mean that its being restocked from your inventory, so the hotbar number doesn't decrement, but the one in your inventory does.

**Comment by xtended2l** [comment]
I have to add, that it happens with every dish in bowl. Chicken soup, Beetrout soup, etc.
And no, I'm not in creative. At first I played an ordinary survival game with my wife over the LAN. And I thought the LAN may cause this issue, but then I checked that in SP and it was the same. Now, I deployed a dedicated server in the internet, because a friend of mine just joined playing minecraft with us, and the issue with hearty stew persists so far(we started from scratch) for all of us.

**Comment by Bucket777** [comment]
Try downgrading your forge to 14.23.4.2707. I had this same issue as well as a rendering crash and downgrading to this version fix a few things.

**Comment by hereticalDev** [comment]
It looks like this was fixed in Better With Mods version 1.12-2.3.5 https://gitlab.com/BetterWithMods/BetterWithMods/commit/b514cf0554f3a15465540dca3aa5c99c177f4783

**Comment by artdude543** [comment]
This will be resolved for when 3.1.0 comes out.
