### ISSUE TITLE
Glowstone torch launcher

### ISSUE THREAD

**Issue by TKDWarrior** [DarkPacks/SevTech-Ages#3394]
## Context

I think it would be very useful if there was a glowstone torch launcher - just like the regular torch launcher from Cyclic but that shoots glowstone torches instead so that it can be used in space/other planets where standard torches shouldn't work because of the vacuum.  Maybe make the recipe the same as the torch launcher but with blocks of glowstone instead of blocks of coal

**Comment by monodemono** [comment]
We make modpacks, not mods. Request this from a mod developer.
