### ISSUE TITLE
Crystal Chest Age 3

### ISSUE THREAD

**Issue by Nezaruke** [DarkPacks/SevTech-Ages#3396]
Okay so I was able to do this three time and found it interesting you can obviously make the crystal chest in like age 2 with the liquid starlight and while in age three i found a block placer while going over what I can do with redstone alloy plates, so I put 2 crystal chests in it to see what would happen and it made my game crash when I reopened that game a crystal chest was placed in front of the placer and there was still 2 in it. Also I was able to repeat this 3 more times it did crash each time but also gave me a free chest each time as well thanky for reading this!

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
