### ISSUE TITLE
Elytra bug

### ISSUE THREAD

**Issue by DavidSarif** [DarkPacks/SevTech-Ages#3400]
## Bug Report

The game shuts down when elytra is equipped at chest slot. If I load the world after this, the game shuts down if I try to open inventory..

## Expected Behaviour
Server does not shut down when elytra is equipped.

## Steps to Reproduce (for bugs)

1. Obtain elytra
2. Equip elytra to the chest slot

## Logs

* Client/Server Log:
* Crash Log:  https://pastebin.com/HaBuu0WY

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0.181
* Launcher Used: ATLauncher
* Memory Allocated: 8 Gb
* Server/LAN/Single Player: Single Player
* Optifine Installed: -
* Shaders Enabled: -

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: -

**Comment by artdude543** [comment]
Should be fixed in mod updates for 3.1.0
