### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Ampmasterful** [DarkPacks/SevTech-Ages#3401]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.

https://pastebin.com/LrzrWDiN

Cant provide too much more info.
crashed on "Phase 2" of game launch.

**Comment by monodemono** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
