### ISSUE TITLE
3.0.8 Crash trying to view advancements after creating starlight crafting altar

### ISSUE THREAD

**Issue by kingnothin** [DarkPacks/SevTech-Ages#3402]
## Bug Report
Client crashes when trying to view Age 2 advancement page after completing the Starlight Crafting Altar step.

## Expected Behaviour
It shows the advancements page

## Steps to Reproduce (for bugs)
1. Hit L to view advancements
2. Click the Age 2 tab

## Logs
* Client/Server Log: https://pastebin.com/RGWkeuZR
* Crash Log: https://pastebin.com/5JAJAyRf

## Client Information
* Modpack Version: 3.0.8
* Java Version: Not sure, settings say it's using the bundled runtime
* Launcher Used: Twitch
* Memory Allocated: ~5GB
* Server/LAN/Single Player: Server (running on the same machine)
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed: None

## Server Information
* Java Version: 1.8.0_171-b11
* Operating System: Win10
* Hoster/Hosting Solution: N/A
* Sponge (Non-Vanilla Forge) Server: N/A

**Comment by artdude543** [comment]
Fixed for 3.1.0

**Comment by kingnothin** [comment]
I'm happy to hear this will be fixed in the next update. As there is no eta for that, can you recommend any sort of work around so that I could keep enjoying this pack in the meantime?

**Comment by johnhargrove** [comment]
@kingnothin I know your comment is a couple months old, but I had this issue as well and downgrading Forge seemed to fix it. I went to build 2707. I'm not sure why this would fix it, or what the likely side effects of using an older Forge are, but for people who have this issue it seems to correct it.
