### ISSUE TITLE
Crash after encounter with unloaded chunks

### ISSUE THREAD

**Issue by NucleoBLAST** [DarkPacks/SevTech-Ages#3403]
My first Sevtech-ages map crashes when I approach a boundary between unloaded and loaded chunks in a specific area and attempt to save and quit out of the game.

The game successfully saves and closes away from the un-generated chunks. Once the chunks are attempted to be generated and you attemp to sdave an quit the game crashes. Once the issue chunks are loaded the crash will happen even if you move away to the distance where those chucks would unload the crash still occurs. Horses and zombies that were in the area seem to despawn after encountering the unloaded chunks. 

Modpack version:3.0.8
Installed through the twitch app mod page. 

Save (zipped)
[Rev sucks.zip](https://github.com/DarkPacks/SevTech-Ages/files/2431054/Rev.sucks.zip)

Creative mode was activated and you will load in pointed directly at the problem chunks

Launcher log
[Minecraft launcher log.txt](https://github.com/DarkPacks/SevTech-Ages/files/2431017/Minecraft.launcher.log.txt)

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
