### ISSUE TITLE
Process crashed with exitcode -1073740791

### ISSUE THREAD

**Issue by ReportBot9009** [DarkPacks/SevTech-Ages#3404]
Hello,
I am having a problem with this crash exitcode -1073740791

My setup:
i7 4790
32GB RAM
850 EVO SSD 512GB
EVGA 1080Ti Black (non oc'ed version)

I am running Sevtech 3.0.8 with 512-8192GB allocated.

I have Optifine installed with SEUS Renewed 1.0 as well as Fairy Lights and the newer Light Level Indicator Mod installed.

My Java parameters are:
-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

Recently after a lot of world exploration I am getting an instant 2 second pause then crash with the exitcode in the tite of this post. I will be standing still for 10 seconds or have left my computer for a couple minutes at a time and come back to the crash. This has been more frequent as time progresses and has been crashing at 15-30min intervals.

I've removed optifine and the extra mods and am still having the problem.

Currently paste.ee is down for maintenance and pastbin is too small for the log, so I just copy and pasted my log into a notepad and attached. If you know of another paste service online I'm more than happy to paste it over there.

[Exitcode.txt](https://github.com/DarkPacks/SevTech-Ages/files/2431068/Exitcode.txt)

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
