### ISSUE TITLE
[ME drive bug] The game crashed whilst tesselating block model Error: java.lang.NullPointerException: Tesselating block model

### ISSUE THREAD

**Issue by Bartimeus92** [DarkPacks/SevTech-Ages#3406]
## Bug Report
 when having in a chunk an Me-controller connected to a Me-Drive and some mekanism machine (crusher, enrichment chamber, metallurgic infuser, energized smelter)  and also some inductive logistics item extraction/injection/transport pipe connected to those machine the client crashes on login.
(all shown in the video)
the same problem is encountered by 4 different players on the server ( everyone playing)
## Steps to Reproduce (for bugs)
https://www.twitch.tv/videos/316465012

## Logs
* Crash Log: two different crash report (Twitch log) of the same problem
https://pastebin.com/fBDGwAb5
https://pastebin.com/VUE6m4cS

## Client Information
* Modpack Version: SevTech: Ages version 3.0.8
* Java Version: 1.8.0_51
* Launcher Used: Twitch 
* Memory Allocated: 5.888 MB
* Server/LAN/Single Player: Server
* Optifine Installed: using twitch installation for the modpack
* Shaders Enabled: no

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed: nothing

**Comment by thedarkcolour** [comment]
Can you convert the video to MP4? [video converter](https://video.online-convert.com/convert-to-mp4)

**Comment by Bartimeus92** [comment]
can u suggest me where to upload the video?

**Comment by Bartimeus92** [comment]
converted!

**Comment by thedarkcolour** [comment]
Try using the backup that was created towards the end of the video.

**Comment by thedarkcolour** [comment]
Have you considered using VanillaFix to go back to the title screen after the crash?

**Comment by Bartimeus92** [comment]
I don't even know what VanillaFix is

**Comment by artdude543** [comment]
Should be resolved in the 3.1.0 update. Please open again if the issue persists.

_Note: The update is not out yet however_
