### ISSUE TITLE
Constant Moon Crashing

### ISSUE THREAD

**Issue by KingKippo** [DarkPacks/SevTech-Ages#3409]
## Bug Report
Moon crashes after seconds following world load. Unsure whether it is exclusive to the moon or not; it crashes way too often to do anything.

## Expected Behaviour
The game will freeze up for a couple of seconds, then it will go to the main screen with a not responding error. I have to close out at this point.

## Possible Solution
I have tried reinstalling, changing settings to be less resource-intensive (had no problems with crashes from that before), and rebooting. I am at a complete and total loss.

## Steps to Reproduce (for bugs)
Be unlucky, I guess. It started happening all of the sudden, and makes the game unplayable.

## Logs

https://pastebin.com/ZP7xJi22

I have noticed that the crash-log mentions an exception of the server tick-loop variety. This leads me to believe that this might be related to another problem I've had where whenever there is a dimensional shift, the game freezes up, gives me a closed channel exception, then boots me to the server screen despite being a singleplayer file. I haven't opened to LAN, so that can't be part of it.

## Client Information

Processor: AMD FX(tm)-4300 Quad Core Processor 3.80 GHz

Initial Memory/RAM: 256 MB
Maximum Memory/RAM: 6144 MB
PermGen Size: 1024 MB

Client-Side file

## World Information

SevTech Ages v3.0.8

**Comment by KingKippo** [comment]
Also, this my first time using Github, so it may be shoddily done. If so, I apologize. Patience is very much appreciated.

**Comment by artdude543** [comment]
Fixed for 3.1.0.

You also did _okay_ for your first issue. Next, you post something to stick to what we're after/wanting. Rather than modifying them and adding your own values for things. Such as Client Info. We have them stated for a reason to make debugging/helping way easier. 😄
