### ISSUE TITLE
Can't turn Eucalyptus planks into sticks.(possibly all natura wood?)

### ISSUE THREAD

**Issue by MrGundum** [DarkPacks/SevTech-Ages#3410]
## Bug Report
can't put eucalyptus plank on chopping block and chop into sticks.

## Expected Behaviour
being able to chop the planks into sticks.

## Possible Solution
Add natura wood to stick creation recipe?
noticed all the natura wood are missing tags that default minecraft wood have not sure if related.
missing : plankWoodCopy/barrelPlank/plank"wood type"

## Steps to Reproduce (for bugs)
try to put eucalyptus wood on chopping block

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
default

## World Information
default

* Modpack Version world created in:3.08

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
Already fixed for upcoming 3.1.0
