### ISSUE TITLE
Age 1 No crafting recipe for Yew Gate/ Yew Fence

### ISSUE THREAD

**Issue by MrGundum** [DarkPacks/SevTech-Ages#3412]
## Bug Report
Can not craft yew fence or gate.
Shows up in JEI but when clicking it there is not recipe for it.

## Expected Behaviour
Be able to craft the item.

## Possible Solution
Add the recipes to recipes list.

## Steps to Reproduce (for bugs)
Try to craft Yew gate/ Yew Fence.

## Logs
NA

## Client Information
Default

## World Information
Default

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
Fixed for the next update.
