### ISSUE TITLE
crashing on start up

### ISSUE THREAD

**Issue by yt937** [DarkPacks/SevTech-Ages#3414]
## Logs
https://gist.github.com/yt937/68f80760669ac10dede12455cc54d3a9

## Client Information
i am using the at launcher with the latest version of sev tech and the latest version of java as well
i have 4gb allocated to the game

**Comment by artdude543** [comment]
Vanilla issue. Reinstall Java/G-Card Drivers etc... also next time use the entirety of the issue template. It's there for a reason.

Thanks!
