### ISSUE TITLE
Missing Recipes for Natura's Doors, Fences, and Gates

### ISSUE THREAD

**Issue by MissJae72** [DarkPacks/SevTech-Ages#3415]
Yes, it's happening again. I saw the previous issue posted by Sngglbear600 for 3.0.6 and that it was resolved in 3.0.7, but I couldn't find a new issue brought about regarding the 3.0.8 version. They are, of course, showing up as "known" items, with names. But in JEI, when I press on the different doors, fences, and gates from Natura, they don't open a recipe log AND when I try to craft them the way it would normally, they don't register an output value at all.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
