### ISSUE TITLE
Achievements not unlocking - stevescarts + piston

### ISSUE THREAD

**Issue by Eeketh** [DarkPacks/SevTech-Ages#3416]
## Bug Report
I created a piston, after having unlocked the Twilight achievement.
Looking at the contents of src/config/triumph/script/triumph/stage2/piston.txt, I would expect this to be the only requirement for getting the achievement, but it wouldn't register.

Another player already had the piston achievement without issue, so attempted the next achievement - triumph:stage2/stevescarts, which I believe from reading the relevant script only requires holding a coal engine - however this wasn't working for him either.

I used a command to give myself the piston, to ensure the metadata was correct, but no luck, so I awarded myself the achievement using a command, after which I experienced the same issue with the stevescarts achievement.

To investigate where the issue may be coming from, I tested one of the other achievements requiring an item to be held, triumph:stage2/stopwatch, which was awarded successfully when giving myself the necessary item, so the issue seems to be specific to these 2 achievements.

## Expected Behaviour
I should have been awarded the piston achievement, and myself and my friend should have been awarded the stevescarts achievement.

## Possible Solution
The log has a significant amount of "Can't keep up!" errors, which may be related, though the fact the stopwatch achievement was awarded successfully makes me doubt this.

## Steps to Reproduce (for bugs)
* Create piston/engine
* Achievement not awarded

## Logs
*Server Log: https://pastebin.com/43yS2s0g

## Client Information
* Modpack Version: 3.0.8
* Java Version:  1.8.0_172
* Launcher Used: ATLauncher
* Memory Allocated: 8083MB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed: N/A

## Server Information
* Java Version: 1.8.0_181-b13
* Operating System: OS is CentOS v7
* Hoster/Hosting Solution: private (home server running hyper-v)
* Sponge (Non-Vanilla Forge) Server: No

**Comment by artdude543** [comment]
If advancements are not being triggered you are more than likely missing key parts as _most_ require the previous and so forth.

You can try re-uploading the config files to be sure nothing is corrupt. But this is a singular issue with your setup somewhere. So going to throw this one to Discord for further help if needed.

But check that you have **all** needed advancements to progress. I've tested this now on a server and it's all working as intended. So as long as you've not changed any mods/forge versions the system will work. But I would check your player, re-upload the files and then try again. If it's still not working then please use Discord and seek further help from there.

Thanks!
