### ISSUE TITLE
RE: Missing Recipes for Natura's Doors, Fences, and Gates

### ISSUE THREAD

**Issue by MissJae72** [DarkPacks/SevTech-Ages#3418]
First of all, I'm really very sorry for ignoring the template before. I misunderstood. I had looked at Sngglbear600's and assumed the template was something Github created and SevTech didn't care about, but I know now! Thank you.

## Bug Report
When clicking the items in JEI, the different doors, fences, and gates from Natura don't open a recipe log AND when I try to craft them the way it would normally, they don't register an output value at all.

## Expected Behaviour
The items in should show a recipe log in JEI, but they don't. They should also be able to be crafted as intended, but they're not.

## Steps to Reproduce (for bugs)

1. Reach Stage One
2. Search "@Natura" in JEI
3. Try clicking on any door, fence, or gate.
4. Try using the regular crafting table and/or the work stump to create any of those Natura items.

## Logs

* Client/Server Log: [Gist](https://gist.github.com/MissJae72/e8b7b1ebf702e0e470ddc3f54ce062fc)

## Client Information

* Modpack Version: 3.0.8
* Java Version: Version 8 Update 171
* Launcher Used: Twitch
* Memory Allocated: 6 GB
* Server/LAN/Single Player: It first happened in a LAN server with this same world, but it's also happening in Single Player, which is where I got the latest log from.
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None

**Comment by artdude543** [comment]
Fixed for 3.1.0
