### ISSUE TITLE
Game crashes while loading world

### ISSUE THREAD

**Issue by darargon** [DarkPacks/SevTech-Ages#3419]
## Bug Report

Game crashes when loading my world while it is showing the dirt background loading screen.
## Expected Behaviour

Have the world load up and start 
## Logs

* Client/Server Log: https://gist.github.com/darargon/e603ae227ce66846b4b95ec60bd7f835
* Crash Log: https://pastebin.com/ERHhEyB3

## Client Information

* Modpack Version: 3.0.8
* Java Version: 8
* Launcher Used: Twitch
* Memory Allocated: 5029 MB
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

**Comment by artdude543** [comment]
Fixed for 3.1.0
