### ISSUE TITLE
Game fails while loading ( crash )

### ISSUE THREAD

**Issue by Coltphyton** [DarkPacks/SevTech-Ages#3420]
## Steps to Reproduce (for bugs)

1. Started Modpack
2. Crash at  * Finishing Up *

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/JYCDGVmF

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_171
* Launcher Used: Curse/Twitch
* Memory Allocated: 7,5 GB
* Server/LAN/Single Player: S.P
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 

* Additional Content Installed:

**Comment by Coltphyton** [comment]
tried to update jave to 1.8.0_181...now if i want to start the Modpack , it says *Could not create the Java Virtual Machine...After this , the launcher will be closed.

**Comment by artdude543** [comment]
Throwing to Discord as this is a key mapping issue and they know the fix on there :)
