### ISSUE TITLE
Chicken Soup is endless

### ISSUE THREAD

**Issue by Njbud13** [DarkPacks/SevTech-Ages#3421]
## Bug Report
Eating the Chicken Soup (5138 betterwithmods:chicken_soup) will not reduce the numer of Chicken soups but will give nurishment and an empty bowl (0281 minecraft:bowl).

## Expected Behaviour
It should reduce the number of Chicken Soups by 1 when used.

## Possible Solution
Reduce number of Chicken Soups by 1 on consume.

## Steps to Reproduce (for bugs)
1. Create Chicken Soup (#5138)
2. Eat it

## Logs
N/A

## Client Information
settings -->
* Modpack Version: 3.0.8
* Java Version: not sure? forge-14.23.4.2760 if thats what you're looking for
* Launcher Used: 2.1.1432 via twitch
* Memory Allocated: 12288
* Server/LAN/Single Player: Single player
* Optifine Installed: not sure
* Shaders Enabled: i do not think so

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed: no

![2018-10-05_11 52 50](https://user-images.githubusercontent.com/22496230/46529386-8f528680-c896-11e8-8925-22c97145f333.png)
![2018-10-05_11 53 02](https://user-images.githubusercontent.com/22496230/46529390-937ea400-c896-11e8-814a-6fecbf34fc9c.png)

**Comment by xtended2l** [comment]
The same here. With all type of dishes in bowls.

**Comment by Bucket777** [comment]
The json file for sevtech 3.0.8 wants to use forge-14.23.4.2707 - try and downgrade to this, it has fixed this issue and a few other things for me.

**Comment by hereticalDev** [comment]
It looks like this was fixed in Better With Mods version 1.12-2.3.5 https://gitlab.com/BetterWithMods/BetterWithMods/commit/b514cf0554f3a15465540dca3aa5c99c177f4783

**Comment by artdude543** [comment]
Sweet yep is fixed for that build. So will be in the 3.1.0 update. Thanks for linking that!
