### ISSUE TITLE
Game crashes while make a new World

### ISSUE THREAD

**Issue by Coltphyton** [DarkPacks/SevTech-Ages#3422]
## Possible Solution
 /
 /

## Steps to Reproduce (for bugs)

1. Start creating new world
2. Game says : *Loading World* then *Building Terrain* then *0%* and after this it crashes...

## Logs

* Client/Server Log: /
* Crash Log: https://pastebin.com/QkwDAg84

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_181
* Launcher Used: Curse 
* Memory Allocated: 6.912 MB
* Server/LAN/Single Player: S.P
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed:

**Comment by artdude543** [comment]
Fixed for 3.1.0
