### ISSUE TITLE
Suggestion to add Blockcraftery, Thaumcraft and Aether II.

### ISSUE THREAD

**Issue by EliteSkylu** [DarkPacks/SevTech-Ages#3423]
These are mods which I miss in the modpack. Blockcraftery is a very light mod that I am arleady added on my own but it could be implemented in the future. Thaumcraft is the best magic mod and the Aether is the one of the oldest minecraft mods that adds a new awesome dimension but isn't finished yet. 

## Mod Details
* Name: BlockCraftery
* CurseForge Link: https://minecraft.curseforge.com/projects/blockcraftery

* Name: Thaumcraft 
* CurseForge Link: https://minecraft.curseforge.com/projects/thaumcraft

* Name: Aether II
* CurseForge Link: https://minecraft.curseforge.com/projects/the-aether-ii?gameCategorySlug=mc-mods&projectID=223796

**Comment by artdude543** [comment]
Block craft can be done with chisel and bits, without the need to waste block Id's.  Thaumcraft won't ever be added to pack as it does not fit to out spec.

Aether is the same tbh. The pack is designed around a set idea/spec. Aether would make a mess of staging also leading to problems for new and returning players.

But thanks for your suggestions. Hope the above makes sense for ya
