### ISSUE TITLE
Enable Tinker's Construct tool: Kama

### ISSUE THREAD

**Issue by i4n-b** [DarkPacks/SevTech-Ages#3425]
## Context

I like to use Tinker's Construct, but for some reason, one of the tool categories (tconstruct:kama) is disabled. Surely, when I get to space, such a simple tool would exist, but when I try to craft the tool in the workbench, I cannot, because the kama head is on stage: disabled (I can craft it in the part builder, but I can't use it in the tool workbench).

I tried looking for some detail or explanation on it, and why it is disabled, but I couldn't find it in the changelog. So I'm not sure if it was disabled by accident, or if it wasn't whitelisted.

The only advancement that might get "broken" by the kama is the one for getting those blue shears for obtaining moss in the Betweenlands. It could be enabled after that advancement, or in the age after it.

## Config/Script Details
* Link:

**Comment by artdude543** [comment]
Karam is deliberate disabled as it did not fit right, and we did not like it. Advancements are still however achievable without it. We won't disable something with out checking ;)
