### ISSUE TITLE
Bug/QOL Reparing stone mallet in crafting table costs to much stone.

### ISSUE THREAD

**Issue by MrGundum** [DarkPacks/SevTech-Ages#3428]
## Bug Report
When you repair a stone mallet in a crafting window it costs 3 stone to repair it,
but it only costs 1 stone to actually craft the mallet

## Expected Behaviour
Repair stone mallet with 1 stone just like a stone shovel.

## Possible Solution
Change repair 'recipe' to only require 1 stone.

**Comment by artdude543** [comment]
This is intended. Repairing was never going to be a thing overall but it stayed and some thing was made more costly and the mod which handles this auto generates the costs.

Also it's stone, one of the cheapest materials in the game :P 

But yeah this won't change unless the mod changes it's generation method.
