### ISSUE TITLE
World suddenly running at 0 fps

### ISSUE THREAD

**Issue by Jebadooba** [DarkPacks/SevTech-Ages#3429]
## Bug Report
 Sevtech was working fine yesterday. I changed my graphics card and all other games work fine. My current and all new worlds in Sevtech only, are running at 0 fps and refuse to load when I start them. I have checked what happens when the game loads and there seems to be many errors on startup. The game doesn't actually crash.

## Expected Behaviour
 Instead of my normal 30-60 frames, the world will not load at all, no matter what settings I change.

## Possible Solution
 The 3 fatal errors when the game loads are model loading errors with Immersive Engineering, Immersive Petroleum, and Better With Addons. This does not include the other 803 errors.

## Steps to Reproduce (for bugs)

1.
2.

## Logs
 

* Client/Server Log: https://gist.github.com/Jebadooba/78b2518310da662065b8e111f2f9afc0
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: Native
* Launcher Used: Twitch
* Memory Allocated: 5120MB
* Server/LAN/Single Player: single player
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: created on 5/31/2018 so probably 3.0.7

* Additional Content Installed: none

**Comment by artdude543** [comment]
_Pasted from the bot as it's down for updates_

We use the issue tracker exclusively for bug reports and feature requests. However, this issue appears to be a support request. Please use our Discord for support. https://discord.gg/darkosto
