### ISSUE TITLE
Add Buildcraft Wires

### ISSUE THREAD

**Issue by Shurimano** [DarkPacks/SevTech-Ages#3431]
## Context
Just asking to add Buildcraft wires, and energy part, to this awesome modepack.
Thanks.
 

## Mod Details
* Name: Buildcraft
* CurseForge Link: https://minecraft.curseforge.com/projects/buildcraft?gameCategorySlug=mc-mods&projectID=61811

**Comment by artdude543** [comment]
Nope. BuildCraft Energy is not going to be part of the pack.

It was picked out right at the start of the pack due to various reasons. Which we won't delve into.

But thanks for your suggestion!
