### ISSUE TITLE
progression crashing

### ISSUE THREAD

**Issue by potatius** [DarkPacks/SevTech-Ages#3433]
idk how to use this site and the template was deleted and dont know how to get it back sooo,.. ill just tell ya the issue.

every time i click the age 2 to see my progress it crashes and idk why. its also a server so might effect it. 
[crash-2018-10-10_01.41.32-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/2463475/crash-2018-10-10_01.41.32-client.txt)

**Comment by artdude543** [comment]
Fixed for 3.1.0 and the template does not just vanish, so yeah... Also, use PasteBin or Gist. We don't want to download files. Regardless of what they are.
