### ISSUE TITLE
Severe performance issues on good hardware that are unique to this modpack

### ISSUE THREAD

**Issue by chippledipple** [DarkPacks/SevTech-Ages#3434]
Hi there! I know performance-related bug reports are usually unrelated to the actual modpack, but I think my scenario might be an exception. I installed the modpack today and quickly began experiencing horrible performance for no clear reason. My PC should easily be able to handle it- vanilla minecraft runs smoothly around 200fps, and other modpacks seem to work as well. I'm not too unfamiliar with modded minecraft, so I did my best to try and fix the issue and absolutely nothing seems to work. From what I can tell, the issue seems to be uncommon and might be a bug unique to my hardware. 

My framerate lingers around ~30 fps, with an additional CPU lag spike (100% usage) every time garbage collection kicks in. My CPU% stays around 60%, jumping up to the 90s when the lag is at its worst. Memory allocation is static at 93% (7808mb) with the total usage creeping up, eventually resetting back down again. I also experience occasional visual bugs, like the block breaking texture being swapped with random sprites, and tree flickering when mipmaps are enabled (not sure if these are related.) 

**Here are my specs:**
Processor: i5-4690K CPU @ 3.50GHz
Memory: 16.0 GB
OS: Windows 10 (64-bit)
SSD: PNY CS900 480GB
HDD: 1TB 
Nvidia control panel settings for javaw.exe: https://imgur.com/a/G0cg5Om

**What I've tried so far:**
- Uninstalling all Minecraft related files from my PC
- Re-installing the modpack
- Installing the most recent graphic drivers
- Completely uninstalling java and ensuring I have the most recent 64bit version installed 
- Allocating 8gb of ram via the Twitch client settings
- Uninstalling visual mods like better foliage and smooth font
- Installing Optifine (seems to help slightly, but creates visual bugs) 
- Turning mipmaps off (doesn't make much of a difference) 
- Turning VSync off/on (doesn't make much of a difference)
- Setting task manager priority to high 
- Benchmarking BetterFPS algorithms (currently using Vanilla algorithm) 
- Using the jar launcher via Twitch 
- Using the recommended jvm args (set within Twitch launcher and the jar launcher)
- Ensuring via the in-game F3 menu that my GPU is being used (not dedicated graphics)
- Ensuring via the in-game F3 menu that Minecraft is using java 1.8.0_181 (64 bit)
- Using third party launchers such as MultiMC 
- Installing java in different locations 
- Installing VanillaFix (doesn't do anything)
- Following every optimization guide out there

I'm stumped. Any help would be well appreciated :)

**Comment by chippledipple** [comment]
Update: Ran some CPU benchmarks, temps are stable and normal despite usage going through the roof.

**Comment by monodemono** [comment]
Set fasterAnimations to 0 in foamfix.cfg

**Comment by chippledipple** [comment]
> Set fasterAnimations to 0 in foamfix.cfg

This unfortunately didn't help :(
