### ISSUE TITLE
100% GPU Load on World Start

### ISSUE THREAD

**Issue by ghzdude** [DarkPacks/SevTech-Ages#3440]
## Bug Report

Upon loading into any world, GPU load spikes to ~100%. Game is unplayable at < 0FPS. Issue persists after a reinstall. Issue does not occur on other mod packs (tested on Project Ozone 2 and Sky Factory 3). Issue is recent and started within October.

## Expected Behaviour

GPU load should be around 20-50%, not 100%. Usual FPS ~30-60.

## Logs

* Client/Server Log: https://gist.github.com/ghzdude/c2b823e52628eae7210171f4bb21cf34
* Crash Log: NA

## Client Information

* Modpack Version: Sevtech 3.0.8
* Java Version: 1.8.0_181-b13 / Version 8 Update 181
* Launcher Used: Twitch Launcher
* Memory Allocated:  6GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: Sevtech 3.0.8

* Additional Content Installed: None

**Comment by Dutchs** [comment]
This is caused by a incompatibility with AMD drivers and a foamfix tweak,
in: .\SevTech Ages\config\foamfix.cfg
under texures, set I:fasterAnimation=0
