### ISSUE TITLE
Server Crash when Breaking a Torch

### ISSUE THREAD

**Issue by cyanidearsenic** [DarkPacks/SevTech-Ages#3443]
I was playing in the world waiting for bronze to smelt and then i tried to break a torch and it just kept disappearing and then my sister told me that my nephew's Minecraft had crashed.
Now it opens all the way but crashes whenever i try to load the world.

[crash-2018-10-17_11.16.40-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/2488407/crash-2018-10-17_11.16.40-server.txt)

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
