### ISSUE TITLE
[Help Wanted] Mod interaction when staging causes JEI issues.

### ISSUE THREAD

**Issue by justinrusso** [DarkPacks/SevTech-Ages#3450]
Going to put this here so it is publicly known, a place for reference, and opening it for others to look into as well.

During the refactor of SevTech: Ages 3.1.0 update, we ran into an issue where staging items caused a conflict where they would not appear in JEI. The recipes would not exist in JEI either, but the recipe still works as shown just below.
![image](https://user-images.githubusercontent.com/25138621/47270220-84565200-d536-11e8-8aaa-bd88b18fe474.png)

The Horse Chopping Block is staged to zero. When the Tinker's tooltable is staged (`<tconstruct:tooltables:*>`), a few horsepower items, such as the horsepower chopping block (`<horsepower:chopping_block>`), disappear from JEI and recipes will not show even when clicking `R` on the item when shown in the crafting bench.

Scripts for testing & logs: https://gist.github.com/artdude543/b8900dfc2c3c645101c18a699e74405f

Additional issue where recipe exists, but no output for chopper: ![image](https://i.artdude.uk/T0QGrND8.png)

### Versions:
Forge: 14.23.4.2757
CraftTweaker: 1.12-4.1.9
Recipe Stages: 1.1.1
Item Stages: 2.0.36
Horse Power: 2.6.1.68
JEI: 4.11.0.212

**Comment by artdude543** [comment]
This is now resolved enough for us to continue debugging this internally; with a minor issue which is not game breaking for the modpack. But the main issue is pretty much resolved as per OP.
