### ISSUE TITLE
Really bad FPS

### ISSUE THREAD

**Issue by HaoSs07B** [DarkPacks/SevTech-Ages#3451]
The game is really unplayable, installed the pack yesterday and tried to find a solution for this since then.
Here's a pic of F3 active ingame.
http://prntscr.com/l8yglw

**Comment by dcoolArne** [comment]
Hi, i had the same Problem. Try to use 18.5.1 amd driver. This fixed it for me.

**Comment by HaoSs07B** [comment]
> Hi, i had the same Problem. Try to use 18.5.1 amd driver. This fixed it for me.

This fixed my issue, thank you!
