### ISSUE TITLE
Darkwood Slab into Liquid Barrels recipe Age Zero

### ISSUE THREAD

**Issue by ColdBeat** [DarkPacks/SevTech-Ages#3455]
Maybe i should send it as feature request idk.
Could be more easy if the barrel accept the darkwood slab, i can craft it with darkwood plank but not the slab (should use it from other wood)

## Bug Report
Can't craft Barrels with darkwood slabs
Additional just to know: u can actually make a bronze sword with 2 copper plates (and can't make a copper sword because don't have recipe btw)

## Possible Solution
Change the recipe or the way the game take that slabs

## Client Information
* Modpack Version:3.0.8
* Memory Allocated:6Gb Ram
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed:No

**Comment by artdude543** [comment]
This was mentioned a while back, we changed some of the wood types allowed for 3.1.0 but some are not allowed for reasons to force the player to look around the world for the current tree types.

But look out for 3.1.0 with some minor tweaks/changed in regards. But other than that the wood types allowed won't be changed.
