### ISSUE TITLE
[request] change day/night length

### ISSUE THREAD

**Issue by choum33** [DarkPacks/SevTech-Ages#3458]
Hello and thanks for you great work.

As there is a lot of things to do in this modpack day and night it would be great if you can include a mod (like too much time for 1.7.10) to double daytime and night time.
Easier to explore during day.
Easier to work on astral sorcery for exemple (or hunt) at night. And avoid to be blocked for long time at home waiting to finish some sorcery (as we can't skip day by sleeping LOL)

I deployed this on my last homemade modpacked server and my players loved it ;)

My best reguards

**Comment by artdude543** [comment]
Nope. These mods break other mods and create bugs/issues.

You can use other mods to quick switch to-night again, however. So you can _already_ do this natively with the pack.
