### ISSUE TITLE
[suggestion] advanced rocketry

### ISSUE THREAD

**Issue by choum33** [DarkPacks/SevTech-Ages#3459]
Hello,

I played a lot with galaxycraft and advanced rocketry. Advanced rocketry is really more interesting to play with solid multiblock machines, space missions, space station building etc.
Advanced rocketry need lot of night to make observatory works, as we use night for astral sorcery it would be a good combination ;)
Would it be possible to include it?

Thanks

**Comment by artdude543** [comment]
This mod won't be added. As we focus mainly on GalacticCraft. That and we don't want to make the pack harder to run with mods worlds to load, along with more "stuff" which is not really necessary.

But thanks for the suggestion tho!
