### ISSUE TITLE
Done translating in French, not sure how to add it to my current server

### ISSUE THREAD

**Issue by meteovio** [DarkPacks/SevTech-Ages#3464]
Hello,

As per mentioned in #1040 it's now possible to suggest translation for the SevTech: Ages advancements.
I'm playing with a bunch of french people so I thought providing a translation for them would be cool, so I did download the lang file and translated every lines, but I wasn't able to push the changes onto my server.

I'm aware the changes have to be made within the Triumph config folder, and I edited the advancements there with the translation I had made, but it basically broke everyone's advancement. I can't wrap my head around how the system is made. I thought the advancements were ID based, but it looks like changing the flavor text can break the progression, somehow?

Could someone clarify how I can change the advancements now, without breaking the mechanics behind it? 

I'll provide my translated file in the correct repo subfolder once I'm done correcting it :)

Many thanks,
Alex

**Comment by meteovio** [comment]
Okay, the issue is still unresolved but I'm done with the translation. It should definitely be double-checked by some other french speaking person as there might be a bias. 

I'm not comfortable enough with GitHub to upload the file myself so I'll just attach it here and let someone working on the project add it properly.

[fr_FR.zip](https://github.com/DarkPacks/SevTech-Ages/files/2534910/fr_FR.zip)

**Comment by artdude543** [comment]
Closing in favour for #3469
