### ISSUE TITLE
Sevtech Crash on Loading, Ubuntu

### ISSUE THREAD

**Issue by Spenser715** [DarkPacks/SevTech-Ages#3465]
## Bug Report

Sevtech crashes at end of phase 3 beginning of phase 4 of loading.

## Expected Behaviour

Expect game to load

## Steps to Reproduce (for bugs)

1.fresh install of Ubuntu 18.04.1 on custom build PC with Intel Core i5-6500 CPU @3.20 GHz x4, Nvidia GTX 1060 3GB, 16GB RAM
2.Load Sevtech via MultiMC

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/qfdWhYnw

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_181
* Launcher Used: MultiMC
* Memory Allocated: 8064 MB
* Server/LAN/Single Player: LAN
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.7

* Additional Content Installed:

**Comment by artdude543** [comment]
You have changed the supported Forge version. Drop back to `14.23.4.2707`. This crash is due to that. Never update Forge in modpacks.
