### ISSUE TITLE
PneumaticCraft Drones Not Using Digging Tools

### ISSUE THREAD

**Issue by Seferan** [DarkPacks/SevTech-Ages#3467]
## Bug Report

PneumaticCraft drones have the ability to dig blocks in an area using drone programming.  Drones have the ability to use tools (Pickaxes/Shovels/etc) from their inventory to speed this process.  This is currently broken using Pickaxes on SevTech-Ages V3.0.8.   This can be seen by "requiring" the drone to use tools and giving the drone an iron pickaxe. The drones will provide an error indicating that no blocks can be interacted with.  This happens despite the drone having the correct tool (Pickaxe).  If the drone is reprogrammed to not "require" the tool, it will proceed to mine the blocks, but not use the tool as it should.

I attempted to reproduce this with PneumaticCraft v0.6.6 (same as the SevTech) but the drones behave as expected.  As result, it appears to be an issue within the ModPack

## Expected Behaviour

The expected behavior is the drone should navigate to the area to mine and dig out the blocks.  

## Possible Solution

I can only imagine this is due incorrect interaction with another mod.  

## Steps to Reproduce (for bugs)

Create SuperFlat with Preset, Cheats Enabled
3;minecraft:bedrock,3*minecraft:stone

/gamerule doMobSpawning false
/gamestage add @p 4
/tp 0 5 0
/setblock 3 5 0 chest 0 replace {Items:[{id: "iron_pickaxe",Slot: 0,Count: 1}]}
/setblock 0 4 2 pneumaticcraft:creative_compressor 
/setblock 0 4 1 pneumaticcraft:charging_station 3
/setblock -1 4 2 pneumaticcraft:programmer 3

/give @p pneumaticcraft:pneumatic_wrench
/give @p pneumaticcraft:drone
/give @p pneumaticcraft:speed_upgrade 10
/give @p pneumaticcraft:dispenser_upgrade

1) Right Click Creative Compressor and set to 20 BAR
2) Right Click Charging Station
2A) Add 10 Speed Upgrades & 1 Dispenser Upgrade to Station
2B) Place Drone in Charging Station and wait until 10 Bars of Pressure.  Then pickup Drone
3) Open Programmer
3A) Select Import/Export from Paste Bin (Icon on Left)
3B) Paste in Link https://pastebin.com/Ahvqe3kh
3C) Click Get From PasteBin
3D) Hit ESC and verify Programmer is displayed
3E) Place Drone in Box to Top Right
3F) Click Export Program
3G) Pickup Drone and Close Charging Station Interface

/give @p pneumaticcraft:pneumatic_helmet
/give @p pneumaticcraft:entity_tracker_upgrade
/give @p pneumaticcraft:dispenser_upgrade

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: 
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server & Single Plaer
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: v3,0.8

* Additional Content Installed:

## Server Information
The issue reproduces on my server as well, but since it also reproduces on Single Player, it is likely easier to troubleshoot in a standalone environment.

**Comment by artdude543** [comment]
This was an issue with staging and the Drones not having any stages to actually do work. This will be resolved when 3.1.0 comes out.
