### ISSUE TITLE
Please update Construct's Armory

### ISSUE THREAD

**Issue by ZyorTaelon** [DarkPacks/SevTech-Ages#3471]
While messing with my armor I tried to add the Traveler's Cloak of invisibility. It made my character invisible but not the armor itself, which kind of defeats the purpose when you want to jumpscare friends on your server.
I found https://github.com/TheIllusiveC4/ConstructsArmory/issues/97 which suggests more recent versions of conarm contain a bugfix for this issue. They are currently at Beta version 1.12.2-0.0.23-rc3.jar  whereas sevtech 3.0.8 contains 1.12.2-0.0.21-rc1.

Thank you for this great modpack!

**Comment by monodemono** [comment]
Constructs Armory will be updated in the next release of the pack.
