### ISSUE TITLE
(Suggestion) Use One Probe instead of Waila

### ISSUE THREAD

**Issue by RedBlockFilms** [DarkPacks/SevTech-Ages#3473]
## Context
As the name implies, use one probe instead of waila. In my opinion, it is much easier to use and better for machinery because you can view additional information that waila does not have. I assume staging may work differently, but oneprobe can require the probe to be in your inventory to function. Again, not sure how this would be staged but at first glance doesn't seem too hard
## Mod Details
* Name: OneProbe
* CurseForge Link: https://minecraft.curseforge.com/projects/the-one-probe

**Comment by artdude543** [comment]
Waila is out prefered mod for displaying information to the user. OneProbe does have its ups but it also has more issues over Waila.

As with some tweaks/integrations, we got added specifically for Waila it would be a waste to move to another mod when the current does the job we need. Along with if we needed anything extra it would be a breeze to get added.

But thanks for the suggestion though!
