### ISSUE TITLE
"Kama head" exists in "Stage Disabled," instead of "Stage 2"

### ISSUE THREAD

**Issue by rubycona** [DarkPacks/SevTech-Ages#3474]
## Bug Report
Using the "Tinker's Construct" tool station et al, the Kama Head pattern, when selected from the Stencil Table, says that it will be available at "Stage Unavailable." Further, there's no sign that the Kama Head exists anywhere in the JEI list.

## Expected Behaviour
For all the other patterns / creations, they are either immediately available, or say they're unavailable, with the stage of unlocking mentioned. (For instance, the "Chisel Head" says it will be available at Stage Three.) I would expect Kama Head to be the same.

## Possible Solution
Fix the recipe thing to recognize one of the stages? Presumably stage 2, since there's comments online that people use the Kama at stage 2?

## Steps to Reproduce (for bugs)

1. Open JEI in Stage 2.
2. Type in "Kama."
3. Observe the lack of results.

Version 2.

1. Open Tinker's Construct - Stencil Table.
2. Put in a Blank Pattern in the left-most slot.
3. Select the Kama Head. (It's the 3rd row from the top, 3rd from the left. It's in between the Excavator Head and the Scythe Head.)
4. Hover the mouse over the selected pattern, and read the message.

## Logs
There isn't an error log, since it didn't crash. That said, it also happens on the other computers in my family.

* Client/Server Log: None
* Crash Log: None

## Client Information
There are no other mods installed.

* Modpack Version: 3.0.8
* Java Version: Version 8 Update 161
* Launcher Used: Twitch
* Memory Allocated: 7mb and 10mb (two different computers)
* Server/LAN/Single Player: Multiplayer
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed: None

## Server Information
* Java Version: Version 8
* Operating System: Win 7
* Hoster/Hosting Solution: Private
* Sponge (Non-Vanilla Forge) Server: No clue what this is asking for, but I figure it's not that important, since it's not crashing.

**Comment by monodemono** [comment]
Kama's disabled on purpose, this is not a bug.
