### ISSUE TITLE
More a Question

### ISSUE THREAD

**Issue by Inyaahead** [DarkPacks/SevTech-Ages#3475]
Hi,
I'm just wondering if there would be a way added in the modpack to disable the leveling of players in the sev tech ages pack. So the way that you don't have to pick up stones and plant fibre etc.
If it is able to disable the mods causing it, would someone like to explain me how. fan of the modpack just not the leveling aspect " the age" aspect is not my genre.

**Comment by monodemono** [comment]
I'm not 100% sure what you're asking, but I can tell that it involves serious modifications, in which case the answer is no, it is not possible, and doing so would invalidate any support you would receive.

Furthermore, this modpack is designed the way it is for a reason, if you're not a fan of the "ages" mechanic, then there's plenty of other packs out there that you can play instead, you don't have to play THIS PACK.

Lastly, this issue tracker is for tracking bugs, not support, in the future, please direct any support questions to our discord.
