### ISSUE TITLE
Add tips without using hacks.

### ISSUE THREAD

**Issue by darkhax** [DarkPacks/SevTech-Ages#3476]
## Bug Report
You're using ResourceLoader to load custom tips for the Just The Tips mod. This is fine, but the mod already adds a system for adding tips that does not require ResourceLoader. It's easy to implement custom tips properly though. 

## Expected Behaviour
Tips should be loaded using the intended config mechanic instead of through ResourceLoader as a hack. 

## Possible Solution
Place the `tips.txt` file in `config/justthetips/tips.txt` instead of resource loader.

**Comment by artdude543** [comment]
Wait huh? I feel this is valid if anything. ResourceLoader is used for custom assets but we can move to use the config dir method. It's like a two-second job lol

**Comment by darkhax** [comment]
@artdude543 I will send you some details of why I closed this issue in Discord.
