### ISSUE TITLE
[Crash] Exception in server tick loop.

### ISSUE THREAD

**Issue by onyxphoenix1231** [DarkPacks/SevTech-Ages#3477]
## Steps to Reproduce (for bugs)

1. Start server

## Logs

* Client/Server Log: https://pastebin.com/515r0y5x

## Client Information

* Modpack Version: 3.08
* Java Version: 
* Launcher Used: Twitch Launcher
* Memory Allocated: 6 gb
* Server/LAN/Single Player: Server
* Optifine Installed: Yes
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.08

* Additional Content Installed:

## Server Information
* Java Version:  1.8.0_181
* Operating System: Windows 10

**Comment by artdude543** [comment]
Has already been reported, and resolved for 3.1.0
