### ISSUE TITLE
Environmental Tech Void Miner is Missing Mica

### ISSUE THREAD

**Issue by techdude** [DarkPacks/SevTech-Ages#3478]
## Bug Report

I left my level 2 void miner running for several hours with the white laser lens so I can get Mica (required for all of the environmental tech modifiers). However, no Mica has dropped.
## Expected Behaviour

 The rate according to JEI should be 8.81% so with a white laser lens there should be a fairly steady stream of mica available. Instead no mica is mined at all.

## Possible Solution

Looking at the values in src/config/environmentaltech/multiblocks/void_miner/ore/tier_2.json, it appears that the entry for mica is missing (it also looks like it is missing from all the other tiers as well). The entry should be something like (with the correct weight of course)

```
{
      "target": "white",
      "weight": 8,
      "count": 1,
      "id": "environmentaltech:mica"
 }
```

As far as progression, I think it is reasonable to require tier 2 for mica since it is the first tier where you can start using modifiers (and hence you need mica).

## Steps to Reproduce (for bugs)

1. Create a tier 2 void miner
2. Add a white laser lens
3. Let it run ad-nauseum, voiding everything except mica
4. Observe that no mica will be produced

## Logs

* Client/Server Log: https://gist.github.com/techdude/9b91bd7b39c4ebada6840baeb1c4d61d
* Crash Log: I don't know where this is, but I can provide it if needed.

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_51
* Launcher Used: Curse/Twitch
* Memory Allocated: 12GB
* Server/LAN/Single Player: Single Player w/Occasional LAN
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None

**Comment by techdude** [comment]
Just a quick update, I tried the config change mentioned here on a local world and it looks like that fixed it. A weight of 8 gives it 9.12% with the white lens according to JEI.

**Comment by Azrazal** [comment]
random person here, just checking, was that the void miner, or the resource miner. i had no issue with mine getting mica

**Comment by techdude** [comment]
It is a tier 2 void ore miner.
