### ISSUE TITLE
SevTech client on tlauncher crashed on start

### ISSUE THREAD

**Issue by Gelarion** [DarkPacks/SevTech-Ages#3480]
## Bug Report

Crash on startup of sevtech ages modpack
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:
https://pastebin.com/b2VaJSiA
## Client Information

* Modpack Version:3.0.8
* Java Version:191
* Launcher Used:TLauncher
* Memory Allocated:10GB
* Server/LAN/Single Player:SP
* Optifine Installed:Yes
* Shaders Enabled:

## World Information

SevTech Ages
* Modpack Version world created in:1.12.2

* Additional Content Installed:None

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by Prelart** [comment]
Hmm i have the same issue.

**Comment by monodemono** [comment]
We do not support tlauncher. If you get it to work in tlauncher, great, good for you, but if you want help for your crashes and other issues, you must use either Twitch or ATLauncher (or MultiMC).

**Comment by artdude543** [comment]
You are also using an unsupported version of Optfine Supported builds: `Use D2 or D3.`
