### ISSUE TITLE
Advancement won't work (Starlight Upgrade)

### ISSUE THREAD

**Issue by rotyler** [DarkPacks/SevTech-Ages#3490]
## Bug Report
I'm in age 2, and the advancement for the starlight crafting altar won't work.
I made the altar and the structure, I've tried picking up the altar in my hand, but nothing works.

## Expected Behaviour
It should just give me the "Starlight Upgrade" advancement

## Possible Solution
Is there a command to give me the advancement, so I can just keep going?

## Steps to Reproduce (for bugs)

1. make starlight crafting altar
2. the advancement doesn't do anything
3. make structure mentioned in the journal
4. nothing happens still

## Client Information

* Modpack Version: 3.0.8
* Java Version: java 8 update 31 (1.8.0_31-b13)
* Launcher Used: Twitch
* Memory Allocated: 9495 (on twitch)
* Server/LAN/Single Player: Single Player
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.4, i think 

* Additional Content Installed: I added discord rich presence

**Comment by rotyler** [comment]
update: found out how to just give myself the advancement, but now I'm having a new problem.
So i did /advancement grant rotyler only triumph:stage2/astable2 and I got the notification for it. However, When I went to open the advancements the game crashed. here's the file:
[crash-2018-11-22_18.31.18-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/2609555/crash-2018-11-22_18.31.18-client.txt)

**Comment by rotyler** [comment]
Update 2: removing CTM fixed the problem, but I'm not sure if that will have negative effects on the rest of the game

**Comment by MrGundum** [comment]
did you just give yourself the altar?
if so that doesn't work, you have to do the actual upgrade ritual on the tier 1 altar and then it will upgrade to the next tier unlocking the achievements.

**Comment by artdude543** [comment]
The crash your also explaining (as I'm not going to download files) is resolved for 3.1.0 and is avoidable in some instances but it's random, as to when it happens/wants to crash.
