### ISSUE TITLE
Geolsys causing massive lag

### ISSUE THREAD

**Issue by ShadowPauler** [DarkPacks/SevTech-Ages#3498]
## Bug Report
Server reports that chunk generation is causing lag

## Expected Behaviour
Server lags badly

## Possible Solution
Remove Geolsys

## Steps to Reproduce (for bugs)
1. Play Sevtech and mine Geolsys ore

## Logs
https://pastebin.com/5gQmYwje

## Client Information
Experiencing lag when 6+ players connected.
Doesn't lag alone, but Geolsys ores lag when mined.
They have plenty of RAM and CPU power to play on the server

* Modpack Version: 3.0.8
* Java Version: Java 8
* Launcher Used: Official Sevtech pack/Twitch for client
* Memory Allocated: 16GB RAM
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
The world was created in 3.0.8, and is brand new.

## Server Information
* Java Version: Java 8
* Operating System: Windows 10
* Hoster/Hosting Solution: Home
* Sponge (Non-Vanilla Forge) Server: Forge
CPU: Ryzen 7
RAM: 16GB DDR4 3000Mhz
Storage: 500GB SSD

Note: The server is dedicated for the server only! It is not used for playing games. Windows is just easier to use for me, and will always be. This top of the line hardware shouldn't be lagging AT ALL with 6 people total nor 1 person mining Geolsys ore all alone on the server.

Note: Using Capiler, 2800+ chunks are loaded and are constantly generating more and more.

**Comment by artdude543** [comment]
Some changes to the mod are in for 3.1.0 along for others. But Geolsys is not the main cause and never was the root causer. It's a long list of issues and the modpack does a lot of checking for stages, so all block interaction will trigger _"lag"_ per say.

But we have some optimizations for the next version.
