### ISSUE TITLE
Drone(s) causing server to crash on loading?

### ISSUE THREAD

**Issue by 3HoursLater** [DarkPacks/SevTech-Ages#3499]
Hello, first time posting, hope this is what you need. Our server worked fine until after we made some PneumaticCraft drones. Now it doesn't start up.

Sevtech 3.0.8

Issue / Bug
The server crashes when loading

Expected Behavior
Should start and work

Possible Solution
Something to do with PneumaticCraft drones? How to remove them without resorting to MCEdit?

Steps to Reproduce (for bugs)
Try to load server

Crash Log:
[sev-error-report.txt](https://github.com/DarkPacks/SevTech-Ages/files/2640333/sev-error-report.txt)

Server Information
Java Version: 8 Update 181
Operating System: Win 7 Pro
Hoster/Hosting Solution: Hoster
Sponge (Non-Vanilla Forge) Server?: unsure
Additional Content Installed?: N

**Comment by 3HoursLater** [comment]
Loaded from backup ok (phew). Crash caused by placing a drone that had a magnet upgrade applied.

**Comment by artdude543** [comment]
This issue will be fully resolved when 3.1.0 launchers. Also, we have a template for issues. Please use that next time otherwise the issue will be closed/ignored. Thanks!
