### ISSUE TITLE
Crash with Galacticraft and Compact Machines

### ISSUE THREAD

**Issue by RLGingerBiscuit** [DarkPacks/SevTech-Ages#3506]
## Bug Report

When i load the game, it loads to the game but crashes after a second with the error: 
java.lang.VerifyError: Bad type on operand stack
After a bit of research i found out that it was galacticraft and removed it and extraplanets. It then crashed again with the error:  
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Compact Machines 3 (compactmachines3)
So after i removed that, it worked fine but obviously without galacticraft and compact machines so i thought that might break some of the quests and wrote this crash report.
Also, i was previously able to play just fine.

## Logs

* Client/Server Log:
* Crash Log with galacticraft and compact machines: https://pastebin.com/un8KVW27
* Crash Log without galacticraft but with compact machines: https://pastebin.com/5Re1VamK

## Client Information

* Modpack Version: 3.0.8
* Java Version: Version 8 Update 191 (build 1.8.0_191-b12)
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by artdude543** [comment]
So the game is not using the Java version you have given it's using 1.8.0_51 please can you follow this guide to force the correct 8 version and try again for me https://docs.google.com/document/d/e/2PACX-1vR5muyi1m7Zy_qSwrzeb9e3tbbRlksguNUb_Pvm3pn9eDpsIkUj5qQUq6WFPPdEoVWZq91WvvH57KzC/pub
