### ISSUE TITLE
Unable to Enter New World

### ISSUE THREAD

**Issue by Master-Yin** [DarkPacks/SevTech-Ages#3507]
[crash-2018-12-10_00.31.42-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/2661960/crash-2018-12-10_00.31.42-client.txt)

Finding the attached text file of the crash log. I have found nothing besides:
'The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: Could not initialize class sun.font.SunFontManager'

Only thing I am doing is loading into a world.

**Comment by artdude543** [comment]
I'm going to guess that you have a bad Java Version and/or broken install. Ensure that the launcher is using the latest version of Java 8 and no more. Also, this is a guess as I'm not downloading files when you're told to **not** to that in the template you completely ignored.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
