### ISSUE TITLE
Fish traps causing OOM Exception

### ISSUE THREAD

**Issue by Ibcrootbeer** [DarkPacks/SevTech-Ages#3508]
## Bug Report
When I start the server everything starts up as normal but when someone connects to the server but when someone connects to it the server crashes. There was a similar issue opened but no response. https://github.com/DarkPacks/SevTech-Ages/issues/2548

## Steps to Reproduce
I'm unsure how to reproduce the issue. We haven't placed any fish traps down.

## Logs
Server log: https://pastebin.com/TSS0vzTR
Crash log: https://pastebin.com/MP9LCqGU

## Client Information
Modpack Version: 3.0.8
Java Version: 1.8.0_191
Launcher Used: Twitch
Memory Allocated: 8GB
Server/LAN/Single Player: Server hosted locally
Optifine Installed: Not manually
Shaders Enabled: Not manually

## World Information
Modpack Version world created in: 3.0.8

## Server Information
Java Version: 1.8.0_191
Operating System: Windows 10
Hoster/Hosting Solution: localhost

**Comment by artdude543** [comment]
Sadly there is not a lot which can be done with this issue. Other than you trying to use MCEdit to delete the offending blocks from the world.

It's a complex issue which won't be easily resolved anytime soon.

Sorry that you've occurred the issue, it's a rare case which is hard to replicate in a test environment. It's also a collection of mods which escalate to this bug which makes it even harder to track :/

But using MCEdit will fix the issue, and I've known of people doing this and having good success rates 😄

**Comment by Ibcrootbeer** [comment]
Ok, thanks. The last ticket didn't give a resolutions for it so that's why I opened this one. Since it's a rare case we may just restart the server and see if it happens again.
