### ISSUE TITLE
Server crashes upon loading certain area/joining

### ISSUE THREAD

**Issue by joonaaa** [DarkPacks/SevTech-Ages#3512]
## Bug Report
The server crashes upon loading a certain area.

## Expected Behavior
Once getting to stage 3 (not exactly right after but these problems didn't occur in stage 2), the server crashes upon loading a certain area. I was in that area at the time the server crashes and when i'm joining the server the server crashes. however, when my friend joins who was somewhat around 100 chunks away was able to join the server without the server crashing. 

The same thing happend to my second server since we thought it wouldn't happen the second time. It did happen not long after we went stage 3. 

## Possible Solution
can't think of a solution.

## Steps to Reproduce (for bugs)
1. Progressing to stage 3 in the server
2. not doing much more with progressing.
3. improving our base, making to bigger, making to more efficient, better looking, organized. 
4. server suddenly crashes (second time happend on a TP, first time didn't).
5. craches again upon joining server
6. tried to run the same world on a new server. same problem
7. tried to run the same world on in singleplayer on 2 different computers. same problem

## Logs
* Client/Server Log: https://pastebin.com/MpUJGff8
* Crash Log: https://pastebin.com/3rgXYE6F

## Client Information
 settings -->
* Modpack Version: 3.0.8
* Java Version: 1.8.0_191
* Launcher Used: Twitch Client
* Memory Allocated: 5.7 GB
* Server/LAN/Single Player: Server another laptop 
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed: none

## Server Information
* Java Version: 1.8.0_191
* Operating System: Lenovo Intel Core i7-3612QM CPU @ 2.10 GHz laptop
                                 8.00 GB ram (no changes made for ram allocated to server) 
* Hoster/Hosting Solution: I do not understand the meaning of this
* Sponge (Non-Vanilla Forge) Server: I did not use sponge

I really hope i have given the necessary information.

**Comment by artdude543** [comment]
Resolved for when 3.1.0 lands. Also a duplicate.
