### ISSUE TITLE
Crash Upon Start Up

### ISSUE THREAD

**Issue by papapada314** [DarkPacks/SevTech-Ages#3515]
If entries are blank, I am unsure where to find the information.
## Bug Report

Game is fine after initial start up after install. Crashes upon exiting game and every subsequent start up. I can remove the profile on the Twitch app and reinstall to have the game work fine again, but starts crashing again upon exiting the game

## Expected Behaviour

Game crashes upon start up after initial start up when it shouldn't be

## Steps to Reproduce (for bugs)

1. Install modpack
2. Start up
3. Exit modpack causing initial crash
4. Start up modpack causing all subsequent crashes

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/XrbPAYN3

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0.191 (64-bit)
* Launcher Used:
* Memory Allocated: 6GB
* Server/LAN/Single Player:Server
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment]
Delete your options.txt file and don't change any key binds. This is a known issue for 1.12 MC and we have no idea if we will see a fix for it.
