### ISSUE TITLE
java.lang.IllegalStateException: Keyboard must be created before you can query key state

### ISSUE THREAD

**Issue by metaphoricalstate** [DarkPacks/SevTech-Ages#3516]
## Bug Report
Loads mods to 7/7 then crashes.

## Expected Behaviour
Loads completely then goes to home screen

## Possible Solution
If I reinstall the game it works until the first time I try to go fullscreen then it crashes and continues to crash every subsequent launch until I reinstall the modpack(happens with both twitch/ATLauncher)

## Steps to Reproduce (for bugs)

1. Launch Game
2. Press F10 to go fullscreen
3. Game Crashes
4. relaunch game
5. game crashes after loading but before going to the minecraft screen
5. return to step 4 infinitely

## Logs

* Client/Server Log: https://pastebin.com/nFnnjDM5 
* Crash Log: https://pastebin.com/E0aru2bw

## Client Information

* Modpack Version: 3.0.8
* Java Version: Version 8 Update 191
* Launcher Used: Twitch and ATLauncher
* Memory Allocated: 5GB
* Server/LAN/Single Player: All
* Optifine Installed: no
* Shaders Enabled: no

I have dual monitors if that could be effecting this.

## World Information
Never entered a world.

**Comment by artdude543** [comment]
This is a known issue with mods and users changing key binds. Basically, the only fix as of current (this is also an issue for 1.11 MC) is to not change any key binds or try to use mouse ones, as you'll keep crashing.

I doubt this will be resolved for 1.12 but looks to have better support/fixes in 1.13+
