### ISSUE TITLE
SevTech Ages runs at 0/1 fps with no cpu/gpu/ram overloading

### ISSUE THREAD

**Issue by LeleKaos** [DarkPacks/SevTech-Ages#3518]
## Bug Report
The pack runs at 0/1 fps with 3 out of 10 Gigabyte of ram used.

## Expected Behaviour
The pack runs at 0/1 fps with 3 out of 10 Gigabyte of ram used.

## Possible Solution
Since in the pack is installed the FoamFix mod that is supposed to eliminate some sort of problems, with my configuration (I7 6700k, RX480 8GB Nitro+ OC, 16GB DDR4 ram) seems that the version that is used in this version of the pack (Currently the 0.9.9.1 - anarchy) doesn't collaborate very well with my RX480, because a friend of mine that have my same pc configuration but with a GTX1080 instead of the RX480, runs finely, so than i've tried with an old Nvidia gt730 that solved all the problems.

In these days i'm playing also the Enigmatica2 that have the FoamFix mod too but with a newer version that had solved all the issues with my RX480.

## Steps to Reproduce (for bugs)
1.Have an RX480 in your pc build

## Logs
* Client/Server Log:  https://gist.github.com/LeleKaos/c711cc04be052cce6235899cd8d206ab
* Crash Log: NONE

## Client Information
* Modpack Version: 3.0.8
* Java Version: 1.8.0_51
* Launcher Used: Twitch
* Memory Allocated: 10 Gigabyte
* Server/LAN/Single Player: everyone
* Optifine Installed: NO
* Shaders Enabled: NO

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed: NONE

**Comment by Chubbbs856** [comment]
Hello, my friend just recently got a brand new build with a RX 570 and we spent hours trying to fix this issue and this sounds familiar to his issue. I hope everything works. (This was originally a fix for a different mod pack we found on reddit but it seemed to fix the issue for him.)

Steps to fix

if you are playing modded minecraft, navigate to the mod folder and find the file foamfix.cfg. For me this was found in "C:\Users[me]\Documents\Curse\Minecraft\Instances\All the Mods 3\config\foamfix.cfg"

right click and edit with your notepad of choice

find the following config:



    # Disables texture animations. [default: false]
    B:disableTextureAnimations=false
4. change that =false to =true
