### ISSUE TITLE
In-World Crafting broken

### ISSUE THREAD

**Issue by LycanBlackpaw** [DarkPacks/SevTech-Ages#3521]
## Bug Report

It is impossible to craft most items that require In-World crafting, such as Celestial Crystals and Fluix, due to the item physics causing items to float.

## Expected Behaviour

Item crafts as expected (Example: Rock Crystal + Stardust in Liquid Starlight for Celestial Crystal Cluster)
## Possible Solution

Remove in-world crafting items from the item physics list
## Steps to Reproduce (for bugs)

1. Item thrown into appropriate liquid (Example: rock crystal + stardust in liquid starlight)
2. Wait for item to craft/convert (celestial crystal)
3. Nothing happens (optional: item also despawns despite supposedly never doing so)

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: 8 Update 191
* Launcher Used: MultiMC
* Memory Allocated: 4.5GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: No

## Server Information
* Java Version: Unknown
* Operating System: Unknown
* Hoster/Hosting Solution: Unknown
* Sponge (Non-Vanilla Forge) Server: No

**Comment by Scorpwanna** [comment]
I too am having trouble crafting. I can't even make a Grass Fiber Mesh at the beginning. I put the sticks and twine/fiber in or even just use JEI to do it for me and no mesh shows up.
