### ISSUE TITLE
Scanner not detecting Galacticraft Silicon deposits in Overworld.

### ISSUE THREAD

**Issue by Danekjovax** [DarkPacks/SevTech-Ages#3522]
Using the Scanner device from Scannable mod, you can detect most overworld ores, but silicon seems to not be detected.  Given that it is also an ore not being mined with the Void Ore Miner (see other ticket), it is still one that requires manual mining to obtain.  Seems counter-intuitive that you must rely on age 1 methods to obtain an ore used in age 4+.

Please add this device to the scanner's radar!!

Thank you. 

![2019-01-01_17 28 17](https://user-images.githubusercontent.com/10191173/50576945-ee1e9200-0dea-11e9-866a-5fd52eec982b.png)
![2019-01-01_17 28 20](https://user-images.githubusercontent.com/10191173/50576946-f080ec00-0dea-11e9-9aaf-fcdb106a7f59.png)
![2019-01-01_17 28 25](https://user-images.githubusercontent.com/10191173/50576947-f1b21900-0dea-11e9-86c2-2a22f2fe1fa4.png)

**Comment by komega13** [comment]
silicon still doesn't detected by scannable scanner (galacticraft planet ore, galacticraft core ore) only the red looking silicon ore is detected from galacticraft planets (I think this is the mars planet silicon ore) . Playing on sevtech ages modpack the void miner doesn't provide silicon so th eonly way to get this ressource is the old way mining that is a bit disapointing when you are in age 5 and crafting space rocket but still use your old pickaxe digging tunnel for some ressource . Asteroid dimension have some heavy load of silicon and meteoric iron that cannot be finding, I've spent 2 full hours yesterday . thanks for your work :)

**Comment by justinrusso** [comment]
The silicon ore is considered a common ore in the Ore Scanner. As the scanner is able to pick up the one ore, this seems to be a mod issue at this point. My guess would be on Galacticraft as we've had multiple issues with oredicts in that mod.

**Comment by sam-kirby** [comment]
micdoodle8/Galacticraft#3970

**Comment by micdoodle8** [comment]
Should be fixed in GC Build 279

**Comment by Danekjovax** [comment]
I'd be happy to test this, though I'll have to reload SevTech (it's been over a year since I've played!). ;2)

**Comment by sam-kirby** [comment]
The update with this fix in hasn't been released yet.

**Comment by Danekjovax** [comment]
That's fine.  Let me know at that time, and I'll be happy to help test things.  Thanks!
