### ISSUE TITLE
SevTech crash on loading

### ISSUE THREAD

**Issue by Una0294** [DarkPacks/SevTech-Ages#3523]
I just installed SevTech Ages and loading it the first time and creating a world worked fine but try to load it a second time always results in crashes. I had unistalled and Reinstall (deleting the past world) and started fresh and it all loaded fine. I created a world again and stopped playing but couldn't launch the game again.

Copy of what the crash report says: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)

Crash report: 
[crash-2019-01-03_08.42.30-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/2722179/crash-2019-01-03_08.42.30-client.txt)

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
