### ISSUE TITLE
Crashed when starting SevTech-Ages

### ISSUE THREAD

**Issue by Mum-Get-The-Camera** [DarkPacks/SevTech-Ages#3531]
I got SevTech-Ages installed and when i try to start it up i get this error, and i just don't know what to do. 
this is the error i got...:

Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by JHamberg** [comment]
What launcher are you using? Remove any mentions of `-XX:PermSize` or `-XX:MaxPermSize` from Java launch arguments and try again.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
