### ISSUE TITLE
Primaltech saw strips item nbt

### ISSUE THREAD

**Issue by Saereth** [DarkPacks/SevTech-Ages#3542]
## Bug Report

The primaltech saw strips nbt data of any item placed on it

## Expected Behaviour

NBT should be preserved

## Possible Solution

disallow items to be placed on it that dont have a recipe and/or support nbt of the item

## Steps to Reproduce (for bugs)

1. place an item on the saw that has nbt, a vanilla enchanted book will work
2. pick up book, enchantments now stripped

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: Sevtech Ages 3.0.8
* Java Version: 8 build 191
* Launcher Used: Twitch
* Memory Allocated: 5.5gb
* Server/LAN/Single Player: Single player and Multiplayer both affected
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed:
nothing

## Server Information
* Java Version: V8 build 191
* Operating System: Win10
* Hoster/Hosting Solution: personal
* Sponge (Non-Vanilla Forge) Server: Vanilla

**Comment by vadis365** [comment]
Fixed in Primal Tech Version 0.3.4
https://minecraft.curseforge.com/projects/primal-tech/files/2691363

**Comment by sk2048** [comment]
Closed in 2869088
