### ISSUE TITLE
[3.1.0-beta.1] Findings

### ISSUE THREAD

**Issue by joshrpg** [DarkPacks/SevTech-Ages#3545]
Current game stage: Age 5 / Creative
World Type: Server world to Single Player

Hope this is an okay format because firstnecron didn't specify format :bowtie: 

Current game stage: Age 5 / Creative
World Type: Server world to Single Player

* Minor (more minor annoyances than broken):
	* Pretty sure this known due to it being the mod, but the weirding gadget is sideways
	* RS crafting recipes broke because of removed of items/recipes changed
	* pneumatic craft multi-block structures will need to be re-created
	* Astral Sorcery EXP reset
	* Bonsai pot's may break because of the change how dirt isn't in the pot by default
	
* Advancement Issues:
	* Creative Energy Cube is in stageCreative and stageCreativeUnused which causes it to show unfamiliar
	* item.refinedstorage: upgrade.5.name (interdimensional upgrade) in jei and no icon, it was removed from RS but it probably shows up because of the staging

**Comment by justinrusso** [comment]
What do you mean by "Astral Sorcery EXP reset"?

By "RS crafting recipes broke" do you mean that recipes you configured for auto-crafting now don't work as the recipes no longer exist (in an intentional way)?

**Comment by joshrpg** [comment]
What do you mean by "Astral Sorcery EXP reset"?

**Astral Sorcery has its own exp for its perks**

By "RS crafting recipes broke" do you mean that recipes you configured for auto-crafting now don't work as the recipes no longer exist (in an intentional way)?

**Yeah, I know its an expected outcome but thought it was worth mentioning for release notes because you know there's always going to be those people that are like "WhAt ThE heCkn u Guys Do'in?!"**

**Comment by joshrpg** [comment]
On the astral sorcery stuff, it only seems EXP was reset other progress is fine from what I can tell. EXP was reset by the mod probably due to the fact that there are a lot more perks? So not a bad thing actually.

**Comment by Terpo** [comment]
As far as I know in newer versions of AS the whole Player Attunement changed. So the Attunement state will get reset with the update. This is intentional and not a bug (my opinion).

**Comment by joshrpg** [comment]
> As far as I know in newer versions of AS the whole Player Attunement changed. So the Attunement state will get reset with the update. This is intentional and not a bug (my opinion).

Yes, the "Minor" part is more or less stuff that should just be part of the changelog or referenced it some other form of release notes. As someone who professionally releases stuff, it's always nice to refer to something and say"Well I did technically tell you this". 

Kind of like ToS agreements, no one reads them but its companies "free get out of jail card" when you (the consumer) does something wrong.

**Comment by justinrusso** [comment]
> Creative Energy Cube is in stageCreative and stageCreativeUnused which causes it to show unfamiliar

I'm not able to replicate this. I'm only seeing it staged as creative to me.

**Comment by joshrpg** [comment]
I also just tried to replicate it and I also couldn't do it? Maybe that instance it messed up on loading the scripts? 

IDK, disregard that then.
