### ISSUE TITLE
Resource pack not working. (F32)

### ISSUE THREAD

**Issue by LordFiha** [DarkPacks/SevTech-Ages#3546]
## Bug Report
My resource pack isn't working even after restarting everything including the launcher, (The resource pack is f32). When I click resource pack it shows that f32 is the priority pack in game and in the main menu but nothings changed. (Update, new stuff like tin and bronze have the resource pack textures, but everything vanilla doesn't?)

## Expected Behaviour
Resource pack working.

## Client Information

* Modpack Version: Newest
* Java Version: 64 bit
* Launcher Used: ATL
* Memory Allocated: 4gb
* Server/LAN/Single Player: Single
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Boomflex** [comment]
You will need to allow up to 6GB for a x32 pack.

**Comment by LordFiha** [comment]
Thx
