### ISSUE TITLE
[3.1.0-beta.1] Sariras recipe for making nether brick not hidden

### ISSUE THREAD

**Issue by bgarrison25** [DarkPacks/SevTech-Ages#3548]
## Bug Report

The Sariras recipes for making nether brick are disabled and should not show up in JEI but do. 

## Expected Behaviour

The JEI recipe for making nether brick with Sariras mod shows up even though its disabled.

## Possible Solution

make it not show up. All the items are "familiar" and you don't realize that they are disabled until you try hovering over one of the "jars" that Sariras uses to make it. 

## Steps to Reproduce (for bugs)

Look at the ways to make nether brick in JEI. See that there is a tab for Sariras.

## World Information
[3.1.0-beta.1]

## Server Information
* Operating System: Windows 10
* Hoster/Hosting Solution: Self Served Server

**Comment by justinrusso** [comment]
Seems like this has been resolved.
