### ISSUE TITLE
Game crash 

### ISSUE THREAD

**Issue by Sheogorath108** [DarkPacks/SevTech-Ages#3554]
Clean new Version of modpack.

## Bug Report
Game Loads to home screen, crashes when opening a world or making a world.

## Expected Behaviour
game crashes to loading world

## Possible Solution
maybe the Waila mod is to blame

## Steps to Reproduce (for bugs)
1. Run new clean version of game on my computer
2. Create or load new world 
3. Crash game

## Logs

 Client/Server Log: https://gist.github.com/Sheogorath108/67b1923f4fc472d8e0605012d1fa5439
 Crash Log: https://gist.github.com/Sheogorath108/cd1dd46371cbee827b46b97384af25e5

## Client Information

 Modpack Version: 3.0.8
* Java Version: 8 update 201
* Launcher Used: twitch
* Memory Allocated: 6gb
* Server/LAN/Single Player: single 
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: no

**Comment by Stifling-Bossness** [comment]
You say you're using Java 8 201, but the log says you're using the default version. You'll have to into your Twitch settings and change it to use the Jar launcher instead of native. It might not be the cause of your crash, but it's definitely going to reduce the amount of issues you have.
