### ISSUE TITLE
Can I translate all quests from English to Korean?

### ISSUE THREAD

**Issue by wanybae** [DarkPacks/SevTech-Ages#3555]
## Context

I think lots of Minecraft player in Korea want to play modpacks but a big issue is a language.
If you don't mind, I want to translate all quests to Korean.

**Comment by justinrusso** [comment]
You can PR this if you'd like.

All of the quests are in the lang file. https://github.com/DarkPacks/SevTech-Ages/blob/master/src/resources/sevtechages/lang/en_us.lang
