### ISSUE TITLE
F7 spawn overlay is almost invisible with a shader

### ISSUE THREAD

**Issue by gendalv** [DarkPacks/SevTech-Ages#3556]
3.0.8, OptiFine_1.12.2_HD_U_D3 with SEUS-renewed 1.0.0 Shader 
which option might fix this?

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
