### ISSUE TITLE
[3.1.0-beta.2] Advancements don't show in new age

### ISSUE THREAD

**Issue by scollenburg** [DarkPacks/SevTech-Ages#3558]
## Bug Report

When advancing to a new age, the page of advancements is mostly blank. Exiting & restarting the world (single player) causes the advancements to show.

I don't think this is tied to a specific age. This has happened entering Age 1 and Age 2.

This happens regardless of being in creative mode or survival mode.

I have not tested this in server mode.

## Expected Behaviour

Advancements will show immediately upon reaching a new age.

## Possible Solution
Unknown.

## Steps to Reproduce (for bugs)
1. Complete an age.
2. Open advancements. 
3. Weep quietly for a few seconds.
4. Exit & reopen the world.
5. Chive on, until you complete the next age.

## Logs
n/a. No crash.

## World Information
* Modpack Version world created in: 3.1.0 beta2

**Comment by justinrusso** [comment]
Fixed in https://github.com/DarkPacks/SevTech-Ages/commit/5161973310919f8ee363fdf071a415bf292b766b
