### ISSUE TITLE
My game wont start

### ISSUE THREAD

**Issue by BrackishBook225** [DarkPacks/SevTech-Ages#3560]
## Bug Report
My game doesn't work

## Steps to Reproduce (for bugs)
1.I launched the game from Twitch with the Jar launcher
2.I pressed play and it came back with either Java didn't have enough space for object heap or when I edited the Jvm argument to have "-Xmx1000m" instead of something else the game started up at the blue loading screen but stopped at "Loading - Initializing mods phase 1"

## Logs
* Crash Log: https://pastebin.com/3wh3Qv6D

## Client Information

* Modpack Version: 3.0.8
* Java Version: 8
* Launcher Used: Jar
* Memory Allocated: 6400 MB
* Optifine Installed: No

**Comment by Streamcyper** [comment]
It looks like it is only allocating  966 MB  in the java argument. SevTech should have at least 5Gb of RAM 
[SevTech System Requirements ](https://sevtechages.gamepedia.com/System_requirements)

If you try change the Jvm Argument from -Xmx1000m to -Xmx6400m

Don't have a good reason for why that wouldn't have been carried over from the twitch launcher if you have it set to 6400mb there correctly.
