### ISSUE TITLE
Game Crash on load after the first time

### ISSUE THREAD

**Issue by leZellu** [DarkPacks/SevTech-Ages#3562]
## Bug Report
Can start the game after the installation, but crash when I quit to the Menu, then refuse to start ever again, crashing every time at the end of the mods loading.
_"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)"_

## Expected Behaviour
The pack loads on the first launch after the installation, then refuses to load again, leading to a crash.

## Possible Solution
Tried uninstalling and installing the pack again, multiple times, concluding to the same point, the first time it does works, once I quit its over.
Tried uninstalling Java and every versions of it, then installing the last up to date.
Tried to change Forge Version in the Twitch client.
Without success.

## Steps to Reproduce (for bugs)
1. Install the pack from the Twitch Client. _(Allowing the use of +6Go of RAM.)_
2. Launch the game.
3. Play.
4. Leaving to the Menu leads to a game crash.
5. Modpack doesn't load anymore.

## Logs

* Client/Server Log: https://pastebin.com/b5PzdxRX
* Crash Log: _"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)"_

## Client Information

* Modpack Version: 3.0.8
* Java Version: 8
* Launcher Used: Twitch App.
* Memory Allocated: 6Go
* Server/LAN/Single Player: Server/Singleplayer _(Did not try LAN)_
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.8

* Additional Content Installed: None

## Server Information
* Java Version: 
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

Thank you in advance for the help, I've been unable to find any clue or help on the web.

**Comment by artdude543** [comment]
You need to delete your `options.txt` and then it will load.

Your using Key Binds which are not supported such as Mouse Keys and some adaptive keys. This is due to issues with the lib MC uses as well as some mods. TLDR: Try to not use _none_ keyboard keys for any key binds.

**Comment by leZellu** [comment]
Ok, it does works now, thank you for your help !
