### ISSUE TITLE
SevTech World Crashing Right Before World Enter

### ISSUE THREAD

**Issue by StompNinja** [DarkPacks/SevTech-Ages#3566]
https://gist.github.com/StompNinja/5957536b2cecda0b6fe6712fa9794fd8

## Bug Report
Upon opening instance, I am able to load and get to Sevtech start menu, as well as click on my world to begin playing it. However, after loading for about 30 seconds-1 minute, the window closes right before I should enter the world and takes me back to the ATLauncher window. 

## Expected Behaviour
Expected the world to load and then allow me to play.

## Possible Solution
Unsure as I do not have any experience with coding. I tried copying world to new instance, but the same issue occurred. Also tried opening a new world in the new instance. This worked, so I guess there's a problem with my main world, which I really hope is not the case because I am in Age 2.

## Steps to Reproduce (for bugs)
1. Launch Instance and wait for load
2. Select world and hit play
3. Wait for world to load until point of near completion, then crash

## Logs

* Client/Server Log: https://gist.github.com/StompNinja/5957536b2cecda0b6fe6712fa9794fd8
* Crash Log: https://gist.github.com/StompNinja/5957536b2cecda0b6fe6712fa9794fd8

## Client Information

* Modpack Version: SevTech 3.0.8
* Java Version: 1.8.0_201
* Launcher Used: ATLauncher
* Memory Allocated: Initial: 1024 Max: 5120
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: N/A

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:
*** Unsure what this section means***

**Comment by artdude543** [comment]
Reports need to be uploaded to Gist or Pastebin as clearly stated in the template. Please update the issue to that please, or it won't be looked at.

**Comment by StompNinja** [comment]
I thought I did do that. I copied the crash report, went to Pastebin, made it into a paste and then copied the link. Will try again tomorrow, sorry for the mistake.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by StompNinja** [comment]
@artdude543 Tried using Gist instead. Please notify me if I do so correctly, and if not, what I need to do to fix it. Sorry for all the trouble, thank you for the help.

**Comment by artdude543** [comment]
Okay, so one of the mod files is corrupt. Can you re-install the pack for me, ideally if you can use the Twitch/Curse launcher as your more guaranteed for full files.

Also ensure the install is not on **any** cloud-based file system such as Dropbox/G-Drive/OneDrive etc... as this will make the issue occur all the time, along with incurring data loss.

**Comment by StompNinja** [comment]
@artdude543 Installed Twitch and SevTech, loaded up Minecraft and got this error message: https://gist.github.com/StompNinja/33e8dd8d14a2c9df8db81ce528381db5

**Comment by artdude543** [comment]
Yeah, this is the issue `OneDrive` is being used here. You can't do this. You need to locate the install of the OneDrive "link" and onto either the Desktop or Downloads. Basically, any folder which OneDrive is not backing up. As now the entire install of Curse is being backed on your Drive which will eat all the space in seconds.

On the launcher settings, you can change the location of the install files for Minecraft/Other Mods. Then you'll need to delete the `Curse` folder in your documents. Likewise for ATLauncher probably, as no cloud-based hosting can be used for Minecraft or any game tbh.

**Comment by StompNinja** [comment]
@artdude543 Same thing occurred in Twitch. Crashed when the game was starting to load. Here is the crash report https://gist.github.com/StompNinja/1ffd7977aaf317016834f3bdb12f02ff

**Comment by artdude543** [comment]
Your not getting my point. The game is **still** running in a cloud drive..... Change it and your problems will be resolved. This is causing the files to not be readable as another app is reading them to back/sync then with the cloud server thus preventing the game from using them. As Windows only allows a single read to a file at any one time.

**Comment by StompNinja** [comment]
@artdude543 Think I found my mistake. I had moved the file from OneDrive to Downloads, but I think it needed further permission to remove the file. They are now (hopefully) being removed and I will try to reload the game afterwards.

**Comment by StompNinja** [comment]
@artdude543 Well, it didn't work. I have 0 idea what I'm doing wrong. The Curse file is in downloads, not OneDrive, and the deleted OneDrive file has been removed from the Recycle Bin. Any ideas? I'm sorry to keep being a bother, but I just can't get this to work.

**Comment by StompNinja** [comment]
@artdude543 Over the past couple of days I've also tried to move the file to the desktop and also uninstalling OneDrive. Just wanted to let you know that neither worked just in case one of those would've been your suggestion. I doubt that though because I was just trying to do stuff that sounded like it might work, but I have no coding expertise at all. Thank you for the help.

**Comment by justinrusso** [comment]
Please continue this discussion on the discord link provided above.

I'd recommend asking in the #client-discussion under the SevTech Support category.
