### ISSUE TITLE
Forced Auto Jump

### ISSUE THREAD

**Issue by FootrottFlats** [DarkPacks/SevTech-Ages#3576]
## Config/Script Details
* Link:

## Mod Details
* Name:
* CurseForge Link:

**Comment by FootrottFlats** [comment]
Forced to Autojump in start of game.  Gotten killed already many times do to this feature.  if you hate autojump then you need to find a new game.  You CAN NOT turn this off.    Would love to play the game but hate auto jump so much ... have deleted this game.    Auto jump (or step assist) is about the worst thing you are FORCED to use  it has no value but you are forced to use it.   Mod rating...  0 due to forced autojump

**Comment by Stifling-Bossness** [comment]
You can disable it by crafting an Apple of Lofty Stature later on. You're forced to use it because nobody would use it if it was optional. I, for one, have really enjoyed the feature after getting used to it. Really handy for not wearing out your space bar early ;)
