### ISSUE TITLE
Move CompactMachines.txt to the Stage 5 folder from stage 3

### ISSUE THREAD

**Issue by Darkosto** [DarkPacks/SevTech-Ages#3594]
Also change this line to fix the issue: 

`visibleIf("triumph:stage3/root")`

to 

`visibleIf("triumph:stage5/root")`

and fix 

`setTranslatedDescription("advancements.stage3.compactmachines.description")`

**Comment by justinrusso** [comment]
This may cause players to lose the advancement if they already had it obtained. If so, the player will need to re-grant the advancement using `/advancement grant @p triumph:stage5/compactmachines` or pick up a Miniaturization Field Projector.
