### ISSUE TITLE
Create Recipe to Clear Death Compass NBT Data

### ISSUE THREAD

**Issue by Darkosto** [DarkPacks/SevTech-Ages#3597]
When creating the Death Compass singularity, the compasses don't stack and make this a pain in the ass. Can we create a recipe that players can autocraft to clear NBT data and stack them? 

Once that recipe is finished, confirm stacking is possible.

**Comment by justinrusso** [comment]
Unfortunately, it appears the Death Compasses dont stack even with no nbt data.

**Comment by justinrusso** [comment]
Closed in a7f898be72a6a00f4b46e583e7b50e66660019be
