### ISSUE TITLE
Error: java.lang.NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by Elderad** [DarkPacks/SevTech-Ages#3601]
## Bug Report

Attempted to reload world after getting some stuttering (routinely happens after playing for an extended period of time) but crashed at "building terrain". Tried to restore from backup but had the  same problem.
## Steps to Reproduce (for bugs)

    Open Game
    Open saved game
    Loading world
    Rendering Chunks
    0%
    Crash

## Logs

* Crash Log: https://pastebin.com/scFenjde

## Client Information

I had just set up a vanilla redstone clock to see if it worked on the bellows, noticed I was getting stuttering so tried to reload world which usually fixes it and crashed. Had spent around twenty minutes trying to make it as small as possible with varying degrees of success. Tried restoring from a backup that should have been before I even had the bellows.
* Modpack Version: 3.0.8
* Java Version: (build 1.8.0_45-b14)
* Launcher Used: Native
* Memory Allocated: 4608
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.6 (estimate)

* Additional Content Installed: None

**Comment by sk2048** [comment]
Hello, this is a familiar issue, and relates to your redstone clock. In the version of Forge Multipart in version 3.0.8 it is possible to place multiple redstone devices (redstone torches for example) in one block, but they are stored to disk incorrectly causing a crash on load.

You will either have to restore from a backup that does not include the problematic block(s), or edit them out with MCEdit or another NBT editor.

The discord is a good place to get support with this.
