### ISSUE TITLE
Ore Excavation modifier missing in Age 3

### ISSUE THREAD

**Issue by IntrACate** [DarkPacks/SevTech-Ages#3602]
## Bug Report
The Ore Excavation modifier for Tinker's tools is missing from JEI. I tried crafting the recipe in a crafting table and nothing was produced.

## Expected Behaviour
Once advancing to Age 3, I expected to be able to craft the Ore Excavation modifier for Tinker's tools.

## Possible Solution
Could updating OreExcavation and OreExcavationIntegration to latest versions fix?

## Steps to Reproduce (for bugs)
1. Advanced to Age 3.
2. Searched JEI exhaustively for all aspects of Ore Excavation modification. Ore Excavation enchanted books I - V are present for non-Tinker's tools, but the Tinker's modification is missing.

## Logs
* Client/Server Log: https://gist.github.com/IntrACate/dbea033504710a7bc90e194648c5eb4d

## Client Information
* Modpack Version: 3.0.8
* Java Version: 1.8.0_201-b09
* Launcher Used: Twitch
* Memory Allocated: 12 GB+
* Server/LAN/Single Player: SSP
* Optifine Installed: no
* Shaders Enabled: no, I am using a version of the Sphax texture pack

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed: none

The only change at all to the modpack is a config change in The Betweenlands config to decease entities around player from I think 250 to 200 and total entities from 600 to 500.

**Comment by justinrusso** [comment]
Its called "Excavate Modifier" and it shows in age 3. Are you sure you haven't updated mods or installed/removed any?
