### ISSUE TITLE
JourneyMap minimap doesn't display when obtaining Mapping stage

### ISSUE THREAD

**Issue by JayJay1989** [DarkPacks/SevTech-Ages#3613]
## Bug Report
Upgraded my server to the latest beta version. Journeymap doesnt work anymore. 
Tried a SP game and granted advancement until mapping, with same result.

## Client Information
* Modpack Version: 3.1.0
* Java Version: 
* Launcher Used: twitch launcher
* Memory Allocated: 12gb
* Server/LAN/Single Player: Single player and Multi player
* Optifine Installed: none
* Shaders Enabled: none

**Comment by sk2048** [comment]
Hello, this does not appear to be an issue with JourneyMap staging, but with the default settings exported for JourneyMap. The minimap is hidden by default, try pressing the key '\' assuming you haven't changed your keybindings.

You should also be able to access the fullscreen map by pressing 'j', and waypoints by pressing 'b'.

**Comment by JayJay1989** [comment]
ok thx. But the minimap should be shown when you get the advancement

**Comment by sk2048** [comment]
I realise this, and I'm looking at updating the default config now.

**Comment by sk2048** [comment]
An update on this, the issue is not on the modpack side, but in jmapstages. Until an update for that mod is released players will have to enable their minimaps using the keybind described above or the journeymap configuration menu.

**Comment by justinrusso** [comment]
There is a PR available that may fix this issue: https://github.com/Darkhax-Minecraft/JourneyMapStages/pull/9
