### ISSUE TITLE
Other woods besides Oak aren't giving bark when crafted in inventory. IE Birch, Dark Oak

### ISSUE THREAD

**Issue by JackRuby1** [DarkPacks/SevTech-Ages#3621]
## Bug Report
When you craft Logs with a work blade in your inventory you should be getting that particular wood's bark, but if you use other logs like dark oak or birch, you don't get the bark just the stripped log.
Working: https://gyazo.com/fbd135bd56dabaae12883c302cd73a09
Not working: https://gyazo.com/5d1da78545e1a980c72e28bc9be3bfdc https://gyazo.com/d20f2730228c2164d86f8cae58c561e6
## Expected Behaviour
Placing logs + work blade in inventory crafting grib and getting bark and stripped logs back.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.1.1
* Java Version: Latest
* Launcher Used: Twitch
* Memory Allocated: 6gb
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.1.1

* Additional Content Installed: No

## Server Information
Darkphan's sub server

**Comment by justinrusso** [comment]
Can't reproduce this on SP, will need a server to check if there is maybe some issue there.

**Comment by justinrusso** [comment]
This is only happening on servers. When the blade and log are placed in the same row next to eachother, the issue will occur. Its acting as if there is a shaped recipe that exists, but there does not appear to be one...
