### ISSUE TITLE
I can't see the game

### ISSUE THREAD

**Issue by ArekuDragon** [DarkPacks/SevTech-Ages#3623]
I don't have minecraft premium, so I'm trying to make it work using a launcher. I've read that the only thing you have to do in order to install this pack is to copy everything from the "override" folder to the ".minecraft" folder. I did so, but the only difference I see in game are the mods which are in the mods folder. I've seen how this pack is supposed to work, but i can't see anything of that. There are no rocks, fiber, nor anything; I can make an axe without doing anything like passing "ages". Is basically the same game, but with a few mods on it. Can someone help me?

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by monodemono** [comment]
> I don't have minecraft premium

We neither condone, nor support piracy, in any way, shape, or form. By not having a paid Minecraft account, you will simply have to play something else. I understand the desire to play it, but you either have to pay for it, or figure it out yourself. We will not help you steal from Mojang/Microsoft/anybody.
