### ISSUE TITLE
Totemic rite of spring does not work

### ISSUE THREAD

**Issue by Dannyred123** [DarkPacks/SevTech-Ages#3627]
## Bug Report

When completing the rite of spring ceremony, it doesnt make animals breed. Even though I have food on me.

## Expected Behaviour

When completing the rite of spring ceremony it should make animals breed when food is inside your inventory

On the latest beta version, the version of totemic requires us to have food on us to make animals breed. When completing the rite of spring ceremony and having food on me it does not breed the animals. The difference is the ceremony should make the animals breed.

## Steps to Reproduce (for bugs)

1. [https://youtu.be/9Xf9eHQbRV0](url)
2. Have food on you wheat, cooked meat ect. Do the rite of spring ceremony.

## Logs

* Client/Server Log: [https://pastebin.com/FM6kFTv9](url)
* Crash Log: none

## Client Information

* Modpack Version: 3.1.1
* Java Version: Version 8 Update 201
* Launcher Used: AT Launcher
* Memory Allocated: 8 GB 
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: I believe it was the one before 3.1.1 so 3.1.0?

* Additional Content Installed:
VanillaFix-1.0.10-99

**Comment by sk2048** [comment]
The food must be on the ground - there's even an advancement to clarify that!
"When the Rite of Spring is performed, nearby animals will breed, but only if you drop food on the ground near the totem"

**Comment by Dannyred123** [comment]
> The food must be on the ground - there's even an advancement to clarify that!
> "When the Rite of Spring is performed, nearby animals will breed, but only if you drop food on the ground near the totem"

**Comment by Dannyred123** [comment]
Ohhhh, I didn't see that advancement because I was on an older build, thanks for letting me know!
