### ISSUE TITLE
Rustic Crushing Tub Staged to 1, requires Iron to make.

### ISSUE THREAD

**Issue by JackRuby1** [DarkPacks/SevTech-Ages#3630]
## Bug Report
Rustic crushing tub requires iron to make it, but it's in stage 1, either recipe needs changing or restaged to 2

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 311
* Java Version: Latest
* Launcher Used: Twitch
* Memory Allocated: 6gb
* Server/LAN/Single Player: server (darkphan)
* Optifine Installed:no
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by GearsOfClockwork** [comment]
I'd like to point out that the Barrel from Rustic also has this issue.
