### ISSUE TITLE
Bibliocraft clock GUI doesn't stay open

### ISSUE THREAD

**Issue by IntrACate** [DarkPacks/SevTech-Ages#3638]
## Bug Report
Sneak-right clicking on the Bibliocraft clock causes the GUI to appear for a short moment before it disappears again.

## Expected Behaviour
GUI stays on the screen after shift-right clicking the clock until you do the appropriate action to close it (not sure what default action is).

## Possible Solution
No ideas, nothing for this in the Bibliocraft config file.

## Steps to Reproduce (for bugs)
1. Place the Buildcraft clock in the world (specifically the spruce version, didn't test others).
2. Sneak-right click the clock with nothing in hand or off-hand.
3. GUI appears for a brief moment (it also looks like you stop sneaking while the GUI is displayed even with the sneak key still depressed).
4. The GUI disappears and your character moves back to sneaking position.

## Logs
https://gist.github.com/IntrACate/ff95076a6476f757ec43facfecabfb2e

## Client Information
* Modpack Version: 3.0.8
* Java Version: 1.8.0_201-b09
* Launcher Used: Twitch/Native launcher
* Memory Allocated: ~12 GB
* Server/LAN/Single Player: SSP
* Optifine Installed: No
* Shaders Enabled: No
* forge-14.23.4.2707
* Texture Pack: Sphax compilation 128x

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed: None
* Additional Information: Age 3

**Comment by sk2048** [comment]
This may be a conflict between the functionality of Carry On and Bibliocraft. Nuchaz/BiblioCraft#604 suggests that this can be resolved by rebinding the carry on key to an alternative.

Would you please give this a try and report back whether it fixes your issue?

**Comment by IntrACate** [comment]
Confirmed, that solves it.
