### ISSUE TITLE
Immersive Petroleum Crashes

### ISSUE THREAD

**Issue by ZeekDaGeek** [DarkPacks/SevTech-Ages#3644]
## Bug Report
It appears that the registry for fluids that Immersive Petroleum uses for looking up drilled cores and pumping has been shifted or changed in some way. This means that any time you look at  a core sample from before 3.1.0 it will crash you and all pumps that exist prior to will either spam console or crash as well.

## Possible solutions
Immersive Petroleum needs to update how it renders to not give a Null Point Exception, or pump results need to be the same between versions.

## Steps to Reproduce (for bugs)

1. Install 3.0.8 and create some Core Samples.
2. Place the Core Samples in the world.
3. Put Pump Jacks down on areas with oil
4. Update to 3.1.0/3.1.1.
5. Look at the Core Samples. Enjoy your client crash.
6. Observe your console to see the errors, load some chunks with Pump Jacks to see if they crash you (crashes are not always guaranteed).

## Logs
* Client Core Sample Rendering Crash: https://pastebin.com/8JmctByM
* Server Pump Jack Spam: https://pastebin.com/WgAETACT
* Server Pump Jack Crash: https://pastebin.com/8bv0fDJu

## Client Information

* Modpack Version: **3.1.1**
* Java Version: **The one the Minecraft Launcher downloads for you automatically nowadays.**
* Launcher Used: **Twitch Launcher -> Minecraft Launcher**
* Memory Allocated: **12gb**
* Server/LAN/Single Player: **Server / Singleplayer**
* Optifine Installed: **No**
* Shaders Enabled: **No**

## World Information
* Modpack Version world created in: **3.0.8**

## Server Information
* Java Version: **1.8.0_171**
* Operating System: **Debian**
* Hoster/Hosting Solution: **Dedicated**
* Sponge (Non-Vanilla Forge) Server: **Nope**

**Comment by ZeekDaGeek** [comment]
After further investigating it seems Excavation over all is broken. Trying to create a new core sample doesn't give you anything when you right click and instead gives the following error:

https://pastebin.com/vsbE98Z3

**Comment by sk2048** [comment]
Thanks for the report, this may sound like an odd question but it is related. Do you know what biome you're doing this in?

**Comment by ZeekDaGeek** [comment]
I was going to submit a new bug report but I'll post it here instead to not spam the issues.

## Bug Report
Journey Map Staging is currently broken in 3.1.0/3.1.1 and as a result it's breaking /crafttweaker/postInit.cz. It seems like it doesn't register properly in CraftTweaker.

So far I've noticed that this caused issue #3644 by making all of the Immersive Petroleum pump jacked fluids to be unregistered.

```
function initSpecificStaging() {
        // Staging Specific Scripts
        scripts.crafttweaker.staging.containers.init();
        scripts.crafttweaker.staging.dimensions.init();
        scripts.crafttweaker.staging.enchantments.init();
        scripts.crafttweaker.staging.journeymap.init();
        scripts.crafttweaker.staging.liquidAndGas.init();
        scripts.crafttweaker.staging.mobGear.init();
        scripts.crafttweaker.staging.mobs.init();
        scripts.crafttweaker.staging.multiblock.immersiveEngineering.init();
        scripts.crafttweaker.staging.ores.init();
        scripts.crafttweaker.staging.tinkers.init();
        scripts.crafttweaker.staging.waila.init();
}
```
Everything in the above category is most likely not working right.

## Possible Solution
Hot fix JourneyMapStaging to work with CraftTweaker.
Comment it out.

## Steps to Reproduce (for bugs)
1. /ct log
2. grep -i "error" ./crafttweaker.log

**Comment by sk2048** [comment]
What do you mean journeymapstaging isn't working right?

**Comment by ZeekDaGeek** [comment]
Hmm I guess something must have gone wrong with my SevTech Server zip. There was no JourneyMapStages was corrupted or something, once I downloaded it again separately from CurseForge it seems to be working fine.

Sorry for the confusion. I lost like 5 hours on this. >.<
