### ISSUE TITLE
A couple more broken recipes

### ISSUE THREAD

**Issue by GearsOfClockwork** [DarkPacks/SevTech-Ages#3651]
## Bug Report

Both the key from the Ultimate Car Mod and fertilizer from Better With Mods have broken recipes.

## Steps to Reproduce (for bugs)

1. For the key, simply look it up in JEI. It claims the key is crafted from an empty crafting grid.
2. The fertilizer doesn't show up in JEI at all. It shows up as a recipe for the cauldron when you put in 8 of various types of foods. None of the foods actually craft into fertilizer.

## Client Information

* Modpack Version: 3.1.1
* Java Version: 1.8.0_201
* Launcher Used: MultiMC
* Memory Allocated: 8G
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None

**Comment by darkedone02** [comment]
I had similar issues as well with both the Tomato and Chili Peppers to make Fertilizer
