### ISSUE TITLE
Crashes when I touch any key

### ISSUE THREAD

**Issue by stenkatt** [DarkPacks/SevTech-Ages#3654]
## Bug Report
The game keeps crashing everytime I hit a key on the keyboard, I tried switching keyboard but that didnt work. I can use my mouse perfectly fine but everytime I try to move ahead or just presses a key, it shuts down the server. This happened when I tried to change key for opening journey map. Im in age 2 at the moment. Please help me I love sevtech so much

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version:
* Launcher Used:
* Memory Allocated: 6
* Server/LAN/Single Player:
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
