### ISSUE TITLE
Grave spawning at weird locations

### ISSUE THREAD

**Issue by Reudo** [DarkPacks/SevTech-Ages#3656]
## Bug Report

My grave was a chunk away under the earth after a death. (I got electrocuted by phantom wire from Immersive Engineering). 
I could locate my grave  with the key though.

![2019-03-24_22 44 12](https://user-images.githubusercontent.com/48895679/54888860-4ec8e280-4ea1-11e9-8b80-1b36c09e5106.png)
![2019-03-24_22 43 36](https://user-images.githubusercontent.com/48895679/54888861-4ec8e280-4ea1-11e9-9c2e-24503a81c691.png)

* Client/Server Log: https://gist.github.com/Reudo/819a387d21b3871fe8baeb06a6a2b2f6

## Client Information
* Modpack Version: 3.1.1
* Java Version: V8 Update 201
* Launcher Used: Twitch
* Memory Allocated: 8,5GB
* Server/LAN/Single Player: Server 
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in: 3.0.8

**Comment by Corail31** [comment]
If it can help you on this strange behavior, the grave try to find a place always in the same chunk (so not another) & try to find an ideal place by looking up and down progressively.
So for me, there was no ideal place where you were for a 2 tall square place that would suit to you (allowing to tp over the grave) ;)

**Comment by sk2048** [comment]
Situation explained by mod author, nothing more that can be done.
