### ISSUE TITLE
Literal Easter Eggs

### ISSUE THREAD

**Issue by sk2048** [DarkPacks/SevTech-Ages#3658]
## Bug Report

Steve's Carts adds easter eggs to the game around Easter. As these items are ordinarily hidden, they have never been staged.

![Screenshot](https://user-images.githubusercontent.com/23245543/54901348-14296f00-4ece-11e9-9a19-7aefa3c6c2a8.png)

Now they show up in JEI in all ages. Based on when they can be obtained, they should be assigned the following stages:

* `<stevescarts:modulecomponents:66>` - Explosive Easter Egg - Stage Zero - Weak explosion at player when eaten
* `<stevescarts:modulecomponents:67>` - Burning Easter Egg - Stage Three - Sets player on fire
* `<stevescarts:modulecomponents:68>` - Glistening Easter Egg - Stage Two - Gives regeneration for 2 seconds
* `<stevescarts:modulecomponents:69>` - Chocolate Easter Egg - Stage Zero - Gives high level speed effect for 15 seconds
* `<stevescarts:modulecomponents:70>` - Painted Easter Egg - One time drop from adding egg basket to cart, which then functions as a normal top chest - Drops random Steve's Carts modules when used - including creative modules.
* `<stevescarts:modulecomponents:71>` - Basket - Crafting component for Egg Basket only.
* `<stevescarts:cartmodule:74>.withTag({Data: 1 as byte})` - Egg Basket - Stage Three

Based on when they're actually useful, they should be assigned to Stage 3. All but the painted egg are effectively just crafting ingredients for the Egg Basket, which can't be put on a cart until stage 3.

The events can also be disabled in the config: https://github.com/DarkPacks/SevTech-Ages/blob/master/src/config/stevescarts.cfg#L108

## Expected Behaviour

This is somewhat unexpected.

## Possible Solution

Listed above.

## Steps to Reproduce (for bugs)

1. Login to a world during Steve's Carts Easter event
2. See Easter Eggs in JEI

## Logs

* Client/Server Log: irrelevant
* Crash Log: No Crash

## Client Information

* Modpack Version: 3.1.1
* Java Version: Oracle 1.8.0_201
* Launcher Used: MultiMC
* Memory Allocated: 6GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.1.1

* Additional Content Installed: None

**Comment by justinrusso** [comment]
Event items should just get disabled.
