### ISSUE TITLE
Extremely high startup time + Extremely long lag spikes

### ISSUE THREAD

**Issue by Pimhazeveld** [DarkPacks/SevTech-Ages#3665]
## Bug Report
It takes around 30 minutes to start up the game and another 30 to load up the world I'm playing in.
(I have visited every dimension up to twilight forest)

The game generally runs ok for a while until it randomly freezes for another +/-10 minutes or until I quit the game and restart (which takes another hour ): )

I have an internet tab open most of the time when I play the game (with youtube playing) But I have tried playing without anything open but the results aren't noticable.

## Logs
These are the logs from my latest session and were shown on the launcher. Not sure how useful they are. There's other log files but I have no idea what to do with them because they're .gz files
https://pastebin.com/G1e3yfbk

## Client Information
* Modpack Version: 3.1.1
* Java Version: jre 1.8.0_201
* Launcher Used: Twitch launcher
* Memory Allocated: 8GB (7.86 available)
* Server/LAN/Single Player: singleplayer
* Optifine Installed: no
* Shaders Enabled: no
* Specs: Intel(R) core i7-8750H *2.20GHz 64 bits
* I used these java arguments from https://borg286.github.io/sevtech/ : -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=51 -XX:G1HeapRegionSize=32M

## World Information
* Modpack Version world created in: version 3.1.1
* Additional Content Installed: none
* Removed Content: Better foilage, nutrition and smooth font
* FPS cap: 30
* Render distance: 4
* graphics: fast

**Comment by sk2048** [comment]
Would you mind uploading a couple of the stall reports, apparently being saved to `D:\Curse\Minecraft\Instances\SevTech Ages (1)\stall-reports\`

The log itself doesn't give much to go on, other than your system is struggling immensely, despite decent specs.

**Comment by Reudo** [comment]
I had this before I upgraded my ram. I had 16GB and Java would take up to 10GB at some point (I am playing with a texture pack though).  It usually happend after 2 or more hours of playing and restarting fixed that. 
If you only have 8GB in your Pc that might be a problem.

**Comment by Pimhazeveld** [comment]
> Would you mind uploading a couple of the stall reports, apparently being saved to `D:\Curse\Minecraft\Instances\SevTech Ages (1)\stall-reports\`
> 
> The log itself doesn't give much to go on, other than your system is struggling immensely, despite decent specs.

Sure. There's like 40 stall reports in the folder. Here's the latest 3
https://pastebin.com/6thbcy8X
https://pastebin.com/5aA0EsNc
https://pastebin.com/tczKqSrp

**Comment by Pimhazeveld** [comment]
> I had this before I upgraded my ram. I had 16GB and Java would take up to 10GB at some point (I am playing with a texture pack though). It usually happend after 2 or more hours of playing and restarting fixed that.
> If you only have 8GB in your Pc that might be a problem.

Upgrading the RAM is already something that I wanted to try. Glad to get some confirmation that it can solve the problem so I guess I could try that.
