### ISSUE TITLE
Various blocks from PrimalCore drop nothing when broken

### ISSUE THREAD

**Issue by GearsOfClockwork** [DarkPacks/SevTech-Ages#3673]
## Bug Report

Dried Mud and the following stone types from PrimalCore don't drop anything when broken:

*Common
*Sarson
*Bluestone
*Ortho
*Greenschist
*Blueschist
*Desiccated
*Soul
*Scoria
*Porphyry
*Purpurite
*Ferocalcite
*Carbonite
*Nether
*Eroded End
*Hornblend

## Expected Behaviour

The different types of stone should drop their cobble variants (except dried mud, which should drop itself).

## Client Information

* Modpack Version: 3.1.1
* Java Version: 1.8.0_201
* Launcher Used: MultiMC
* Memory Allocated: 8G
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None

Edit: Fixed Java version

**Comment by Stifling-Bossness** [comment]
> Java Version: 14.23.5.2823

That's your Forge version, not your Java version. Probably not important for this report, but I see you making a lot of them so I figured I should point it out.

**Comment by GearsOfClockwork** [comment]
> 
> 
> > Java Version: 14.23.5.2823
> 
> That's your Forge version, not your Java version. Probably not important for this report, but I see you making a lot of them so I figured I should point it out.

Fixed

**Comment by sk2048** [comment]
Might be worth pointing out that that is not the version of Forge that's included in the pack. 3.1.1 shipped with 14.23.5.2815

Can you confirm this happens without this and any other updates you may have applied yourself please.

**Comment by GearsOfClockwork** [comment]
Yes, they're still broken in 14.23.5.2815, although I don't see why that would matter.

**Comment by sk2048** [comment]
Thank you for confirming that. Found the issue and fixed - crafttweaker updated, changing the type it was expecting in the drops array.
