### ISSUE TITLE
Extra Planets Heavy-Duty Plate (tier 8) recipe broken

### ISSUE THREAD

**Issue by abortu** [DarkPacks/SevTech-Ages#3676]
## Bug Report

It looks like there is a bad recipe for the tier 8 Heavy-Duty plate for the Galacticraft Compressor. This is used to make the tier 8 rocket from Extra Planets. The hydraulic press recipe requires a tier 7 plate, and 5 zinc. The GC compressor recipe requires a tier 7 plate, 3 zinc, and 2 unfamiliar items. 

## Expected Behaviour

To be able to craft tier 8 Heavy-Duty Plates in the Galacticraft compressor.

## Possible Solution

Use the hydraulic press, the recipe appears to be correct there.

## Steps to Reproduce (for bugs)

N/A, recipe issue, not a bug.

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: 3.1.1
* Java Version: 1.8.0_201
* Launcher Used: MuliMC
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: N/A

## Server Information
* Java Version: Oracle 1.8_201
* Operating System: Linux
* Hoster/Hosting Solution: N/A, local server
* Sponge (Non-Vanilla Forge) Server: N/A

**Comment by abortu** [comment]
![tier_8_plate_recipe](https://user-images.githubusercontent.com/5572099/55126257-beb9b180-50c9-11e9-9aa8-975473029036.png)

**Comment by abortu** [comment]
I've been following this issue and the fix. The question I have is will the affect the hydraulic press as noted in https://github.com/DarkPacks/SevTech-Ages/issues/3168 ? Since both zinc and zinc plates will be required, will the hydraulic press try take the normal zinc and compress them to plates instead? I apologize for being ignorant on this topic, just curious.

**Comment by sk2048** [comment]
No, I saw that issue. The Tier 8 HD plate is crafted using 5 compressed zinc after this PR. The only use for zinc ingots in the hydraulic press will be to make compressed zinc, so if they're in there that's probably what you want.

This follows the pattern set by the other tiers of HD plates.

**Comment by abortu** [comment]
Awesome, I can deal with that. Thanks for taking the time to answer my question!
