### ISSUE TITLE
Pneumaticcraft Minigun dealing no damage

### ISSUE THREAD

**Issue by derelky** [DarkPacks/SevTech-Ages#3680]
## Bug Report

The Minigun do no damage or only in close combat. Also if the ammunition was modified with a potion it dealing no damage at all.

## Expected Behaviour

The Mingun do Damage to entities	

## Possible Solution

As it was a bug in Pneumaticcraft itself it could be a solution to update the Mod the newest Version

## Steps to Reproduce (for bugs)

1.Craft a Minigun and shoot on entities
2.Made potion ammunition and try it

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: 3.1.1
* Java Version: 1.8.0_201
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:1.8.0_201
* Operating System: Windows Server
* Hoster/Hosting Solution: N/A, Root server
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
Closing as minigun seems to work fine for me
