### ISSUE TITLE
"help" command throws PlayerNotFoundException when ran from server console

### ISSUE THREAD

**Issue by Dutchs** [DarkPacks/SevTech-Ages#3681]
## Bug Report
When running the "help" command from the server console it throws said error and fails to give the command output
`[com.buuz135.togetherforever.command.TogetherForeverDebug:func_184882_a:57]: net.minecraft.command.PlayerNotFoundException: commands.generic.player.unspecified`

TogetherForever related issue: https://github.com/Buuz135/Together-Forever/issues/20

## Expected Behaviour
print out the help output to the console

## Steps to Reproduce (for bugs)
1. run the "help" command from the server command line

## Logs
* Server Log: https://pastebin.com/yc7mVAYv

## Client Information
* Modpack Version: 3.1.1
* Server/LAN/Single Player: Server

## Server Information
* Java Version: 1.8.0_181 64-bit
* Operating System: Win10
* Hoster/Hosting Solution: Dedicated Machine
* Sponge (Non-Vanilla Forge) Server: No

**Comment by sk2048** [comment]
Should be resolved in next release
