### ISSUE TITLE
Recipes that required rose red now broken

### ISSUE THREAD

**Issue by GearsOfClockwork** [DarkPacks/SevTech-Ages#3682]
## Bug Report

The pre-launch checklist, alicio sapling, and red sand's hydrator recipe require the now disabled rose red.

## Possible Solution

Make them craftable with red dye instead.

## Steps to Reproduce (for bugs)

Check JEI

## Client Information

* Modpack Version: 3.1.1
* Java Version: 1.8.0_201
* Launcher Used: MultiMC
* Memory Allocated: 8G
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None

**Comment by sk2048** [comment]
I wasn't able to resolve the issue with the Hydrator recipe. Reported a bug to Cyclic regarding their CraftTweaker integration: Lothrazar/Cyclic#1100
