### ISSUE TITLE
all advancements shown

### ISSUE THREAD

**Issue by HangerG** [DarkPacks/SevTech-Ages#3684]
## Bug Report
for some reason all advancements are shown 
## Expected Behaviour
it shouldnt show all advancement only those who are near or complete

**Comment by HangerG** [comment]
also i use multimc so that might be problem hmm?

**Comment by Stifling-Bossness** [comment]
Is it showing **all** advancements or all the ones for your current age? It was changed to show all the ones for your current age.

**Comment by HangerG** [comment]
curent age

**Comment by justinrusso** [comment]
This was an intended change
