### ISSUE TITLE
Rendering Issues

### ISSUE THREAD

**Issue by MashiroShiinaX** [DarkPacks/SevTech-Ages#3688]
## Bug Report
Things like Chunk Borderlines overlay (F9), the Scanner Device (to look for rare ores) and even stuff like colored cobblestone have rendering issues. The Chunk borderlines flicker extremely and seem to be all over the place; The colored cobblestone reveals Waypoint beacon beames when looked through specific angles and the Scanner Device marked ores also flicker extremely.
My girlfriend and I both suddenly started having this problem when playing 3.1.1; We just recently decided to start fresh after stopping in 3.0.9, so this is a clean fresh install aswell.

I recorded a video showing off the issue. (Ignore the random stuttering, that's just a recording bug I encountered, because I was too lazy to actually record the game and instead used display capture)

Video: https://mashiroshiina.s-ul.eu/llf90Bkf.mp4

## Client Information
* Modpack Version: 3.1.1
* Java Version: 1.8.0_191
* Launcher Used: ATLauncher
* Memory Allocated: 6GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: 1.8.0_191
* Operating System: Windows
* Hoster/Hosting Solution: Personal
* Sponge (Non-Vanilla Forge) Server: No; used the server that's made by the ATLauncher aswell.

**Comment by TheMingo888** [comment]
I've cant relate to the first two problems you mentioned, but I also noticed the odd rendering with Pickle Tweaks coloured cobblestone. The floor of my house is made of Lime Cobblestone, and I recently put down an Astral Sorcery cave illuminator nearby. I can see the individual astral sorcery illumination effects randomly spread throughout the caves below, which doesn't happen for any other block to my knowledge.

**Comment by TheMingo888** [comment]
It seems the author of PickleTweaks may have already fixed this problem in the latest update (2.1.2). See BlakeBr0/PickleTweaks#31

**Comment by MashiroShiinaX** [comment]
Yeah I also started having really weird animation glitches with other things such as the Autonimous User (Unsure if that's how it was spelled), but basically the top part of it won't be "animated", but like around the entire block it slightly flickers the animation.

Same with my Astral Sorcery ritual, it's like a rave party lmao

**Comment by Dutchs** [comment]
This is due to being at extreme coordinates, a normal player generally wont be able to reach these distances from spawn without commands.
