### ISSUE TITLE
Hard Crash When Using Normal Chests and Block Placers

### ISSUE THREAD

**Issue by funmaster524** [DarkPacks/SevTech-Ages#3689]
## Bug Report
Whenever you put a chest in a cyclic block placer, and it places that chest next to another chest, it causes the client of anybody who loads those chunks to hard crash the launcher. 

## Expected Behaviour

Ideally it would just place the chest, or at least it should be impossible to put chests into the cyclic block placer.
Probably has something to do with the merger of the two chests not happening correctly. 

## Steps to Reproduce (for bugs)

1. place down a cyclic block placer
2. set the output to be facing adjacent to a chest
3. put chests in the block placer
4. activate the chest (either by redstone or by toggling the redstone needed light)

One way to resolve this on a server is to delete the block through commands /fill , but anybody who loads the chunks will crash. 

Fixing this bug should be a relatively high priority, because it is abusable

## Logs

Very easy bug to reproduce, I have some crash reports, but new ones are pretty easy to generate so you may as well just go at it. I'm not too familiar with the upload methods spoken of in the post guidelines,

## Client Information
  BNBGamingCore (BNBGamingCore-1.12.2-0.8.0.jar)
  AstralCore (astralsorcery-1.12.2-1.8.10.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.177.jar)
  CTMCorePlugin (CTM-MC1.12-0.3.0.15.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  CorePlugin (SmoothFont-1.12.2-1.15.jar)
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  FarseekCoreMod (Farseek-1.12-2.3.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)

## World Information
Only tested in multiplayer, probably works in singleplayer too.

**Comment by sk2048** [comment]
Cannot reproduce.

https://streamable.com/nmq7i

You've deleted and ignored valuable parts of the issue template, if you hadn't done that I'd probably have been able to spend less time on this.

Based on your list of coremods (why?), it seems you're running on SevTech 3.0.8. Update to 3.1.1 and your issue should be gone. If not please update this issue, complete with logs and relevant version information. Any future reports lacking this information are likely to be ignored.

**Comment by funmaster524** [comment]
Sorry to waste your time, first time making a bug report, and I didnt know where to find all the information asked for in the form. Its probably an issue with the older version.
