### ISSUE TITLE
Iron Chest's chests inventory disappearing until reopened.

### ISSUE THREAD

**Issue by irondragon12** [DarkPacks/SevTech-Ages#3696]
Sorry but there is no log since this isnt crashing me, however this started yesterday night when i started the game up. I opened a iron chest's chest and my stuff was showing it's contents but after a few seconds that content was blank. I dont know what version i started in because ive never looked and im not sure how to find it on atlauncher as im not use to it. Plus i cant show any proof as i dont know how to record my screen. So plz dont just close this right away. I would love it if i could get a fix for it. Thank You. Just found this.
![Just Say This](https://user-images.githubusercontent.com/30564310/55674988-a63b5b00-5870-11e9-801d-92082bf0c049.PNG)

**Comment by Semi0ne** [comment]
I'm having the same issue. After a little digging it seems to be a known issue between Tinkers' Construct Mod and Iron Chests Mod.

https://github.com/progwml6/ironchest/issues/162
https://github.com/SlimeKnights/TinkersConstruct/issues/3670

It seems to be specifically related to any Iron Chests in the same chunk as the Smeltery Controller. Do you have a Smeltery in the same chunk as your chests? (you can hit the "F9" key to show chunk borders).

My solution will be to just not use any of the Iron Chests variants in the same chunk as the Smeltery. The Vanilla, Weedwood, PrimalChests and BiblioCraft chests don't have this issue for me.

**Comment by irondragon12** [comment]
i dont think they are close enough, but i will check. so thanks
