### ISSUE TITLE
RFTools Control Workbench doesn't craft

### ISSUE THREAD

**Issue by adkinss** [DarkPacks/SevTech-Ages#3697]
## Bug Report
When using the RFTools Control Workbench, crafting ingredients can be placed onto the crafting grid, but the crafted item cannot be pulled out.  The crafted item is shown correctly in the crafting output cell, but when clicked, it disappears.  The crafting ingredients are not consumed, suggesting the item was never actually crafted.

This appears to be a SevTech bug.  This bug existed in 3.0.8.  I installed a fresh copy of 3.1.1 and tried it out there and it still does not work.  However, running a Vanilla+Forge version of Minecraft with only the RFTools related mods installed, the workbench works as expected.

## Expected Behavior
The expected behavior is that when ingredients are placed onto the crafting grid, you can click on the crafted item shown in the output cell and place it into the inventory.  It is also expected that this will consume the ingredients, either updating the grid with the remaining unused ingredients or clearing the crafting grid entirely.

## Possible Solution
I looked through the configs and scripts and couldn't find anything that could be causing this issue.  It is possible this is a mod interaction.  Until it has been identified as to which mod is interacting badly with RFTools Control, a solution cannot be determined. 

## Steps to Reproduce Bug
1. Fresh install of SevTech Ages 3.1.1
2. Single Player - Creative Super Flat World
3. Place down Workbench and then click on it to open the crafting grid
4. Place ingredients for any valid recipe in crafting grid.  I used Oak Wood Planks to form a Chest.
5. When the crafted item is shown, try to drag it to the inventory.  It will immediately disappear.

## Steps to Reproduce Expected Behavior
1. Fresh install of Minecraft configured for 1.12.2
2. Installed Forge for 1.12.2.  Tested with forge-1.12.2-14.23.4.2707 (the version used for 3.0.8) and with forge-1.12.2-14.23.5.2815 (the version used for 3.1.1)
3. Copied the RFTool related mods from the SevTech 3.1.1 mods folder to the Vanilla Minecraft mods folder: immcraft-1.12-1.5.1.jar, mcjtylib-1.12-3.1.1.jar, rftools-1.12-7.61.jar, rftoolsctrl-1.12-1.9.3.jar, xnet-1.12-1.7.6.jar
4. Followed all the same steps as I did in SevTech, except I am able to successfully drag the crafted item to the inventory and see the ingredients update accordingly in the crafting grid.

## Logs
I examined the logs (particularly debug.log) and did not find anything either.  Even more so, while interacting with the workbench, the failure to craft or extract the crafted item did not trigger a single log entry in the debug log.  Here are the relevant logs:
* [ATLauncher-Log.log](https://drive.google.com/file/d/17LC0X2AL8SmoTvdv5HaFlnl24qGYG7-f/view?usp=sharing)
* [latest.log](https://drive.google.com/file/d/1fX5qs-5dxP5xxK3rDVd-kvzLrZZWv-En/view?usp=sharing)
* [debug.log](https://drive.google.com/file/d/1cXSc2mb7kzxHPbyNGAjJg9hvtAEhLQOK/view?usp=sharing)

## Client Information
* Modpack Version: SevTech 3.1.1 and SevTech 3.0.8
* Java Version: 1.8.0_201-b09
* Launcher Used: ATLauncher
* Memory Allocated: 12GB
* Server/LAN/Single Player: Single 3.1.1, Single 3.0.8, Server 3.0.8
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: All worlds created in version tested

**Comment by adkinss** [comment]
I messed around with enabling and disabling mods for awhile in hopes I could determine which mods might be contributing to the bad behavior of the Workbench.  I did confirm that ZenStages is one of the mods that breaks the Workbench.  If all mods are enabled, the Workbench does not work.  Disabling ONLY the ZenStages mod allows the Workbench to work.

However, running a minimal mod setup with just the RFTools related mods and ZenStages (and CraftTweaker, since it is required), the Workbench works as expected.  This suggests another mod is involved.

**Comment by sk2048** [comment]
Seems the Workbench doesn't like staged crafting recipes.

The mods you removed (ZenStages and ModTweaker) would have stopped all of SevTech's scripts from running, thus there'd be no staged recipes.

Your minimal test environments would not have staged recipes without including recipe stages
and first writing some scripts, so you wouldn't see an issue.

I'm pretty certain this isn't something we can resolve (note: there's no FakePlayer in RFTools Control), so probably needs reporting to McJty or jaredlll08
