### ISSUE TITLE
Unable to craft Spawner Seeker

### ISSUE THREAD

**Issue by JayJay1989** [DarkPacks/SevTech-Ages#3699]
## Bug Report
Unable to craft Spawner seeker, nether wart isnt spawning in nether fortresses, only their soul sand or in new loaded chunks nothing.
-To craft nether wart you need the atomic reconstructor which need compressed desh (from Mars) but you need the new rocket to go to there.

## Possible Solution
- fix nether wart spawn in nether fortresses 
- other compressed material in place of desh

## Client Information
* Modpack Version: 3.1.1 BEta
* Java Version: 1.8
* Launcher Used: Twitch
* Memory Allocated: 12GB
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed: none

## Server Information
* Java Version: 1.8 openjdk
* Operating System: Ubuntu 16.04
* Hoster/Hosting Solution: Pterodactyl panel

**Comment by Dutchs** [comment]
have you tried looking around for more stairs with soulsand?
as in 3.0.8 i had found some that did not have netherwarts, but eventually did find one that did.
and just testing a newly created 3.1.1 world they also spawned.
