### ISSUE TITLE
Vanilla Minecraft Bricks (not the block) placed in Cyclic Hydrator makes Wool

### ISSUE THREAD

**Issue by TheWallsPlayer** [DarkPacks/SevTech-Ages#3700]
https://i.imgur.com/DF4s765.png

## Bug Report
^ Problem in title
The result should be Clay, not Wool.

## Steps to Reproduce (for bugs)
1. Place vanilla Minecraft bricks in input slot of Cyclic Hydrator

World was created on version 3.0.8 of Sevtech Ages, and the server is currently updated to version 3.1.1.

**Comment by sk2048** [comment]
This doesn't happen for me, even in worlds imported from 3.0.8 or on a server.

Additionally, SevTech is not doing anything to modify Hydrator recipes.
