### ISSUE TITLE
Cyclic Extractors and Cables occasionally drop Sticks when broken

### ISSUE THREAD

**Issue by GearsOfClockwork** [DarkPacks/SevTech-Ages#3709]
## Bug Report

When breaking cyclic cables or extracters, they sometimes also drop sticks, as if some file or another is regarding them as leaf blocks.

## Expected Behaviour

They should only drop themselves.

## Steps to Reproduce (for bugs)

1. Just place down a few cables and break them.

## Client Information

* Modpack Version: 3.1.1
* Java Version: 1.8.0_201
* Launcher Used: MultiMC
* Memory Allocated: 8G
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None

**Comment by sk2048** [comment]
Funny side effect of this line:

https://github.com/Lothrazar/Cyclic/blob/develop/src/main/java/com/lothrazar/cyclicmagic/block/cable/BlockCableBase.java#L111

Will see if there's a way to stop that happening.

**Comment by Lothrazar** [comment]
Yeah looks like material was used as a shortcut to make shears harvest the cables faster ' super(Material.LEAVES);//leaves so that shears can harvest' . there could be alternate way to get that harvest level

but something else is adding a drop to material = LEAVES.   

#3710 is probably enough IDK
