### ISSUE TITLE
Primal Core blocks not craftable / harvestable.

### ISSUE THREAD

**Issue by verticaljelly** [DarkPacks/SevTech-Ages#3714]
## Bug Report
Most of the primal core blocks aren't craftable:
All clay blocks added by Primal Core : Cinn Clay, Terraclay etc require some brick making item which can't be crafted. Also, the recipes for blocks require some "cobble" form of the clay block which has no recipe
All Stone types added by Primal Core can not be harvested in age 0 or 1. Hopefully that's not the intended behaviour, but if it is put something in the description of the blocks or just hide them like everything else. 

## Expected Behaviour
Just like before, the stone blocks to be craftable (they were craftable on the server but not on single player) 
All clay versions should either drop the clay block or have recipes (before the clay blocks could be made into bricks by roasting them in the grill. This is perfectly adequate, if you want to make the recipes difficult but please add a recipe using the bricks to create the actual blocks.

## Steps to Reproduce (for bugs)
1. Try to harvest bluestone, blueshist, ferrocalcite or any other stone ore added by primal core. 
2. Try to do something with the terraclay or any other primal core clay type 

## Client Information

* Modpack Version: 3.1.1
* Java Version: 1.8
* Launcher Used: Twitch
* Memory Allocated: 12G
* Server/LAN/Single Player: SP
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.1.1 brand new world.

* Additional Content Installed: None.

**Comment by sk2048** [comment]
I'm not sure I follow all of this, is there anything here that isn't resolved by #3675?

**Comment by verticaljelly** [comment]
I think the bit about stone types is fixed but the bit about the clay types is not as you said yourself.
Should I modify this to mention only the clay as the stone part is fixed by the #3673 ?
