### ISSUE TITLE
Galacticraft Titanium Unobtainable

### ISSUE THREAD

**Issue by GearsOfClockwork** [DarkPacks/SevTech-Ages#3715]
## Bug Report

I finally found ilmenite ore in the asteroid belt, but when I tried to mine it, it didn't drop anything.
Titanium is vital for Galacticraft progression past the asteroid belt.

## Expected Behaviour

Ilmenite should drop titanium clusters (as well as iron, according to the wiki).

## Client Information

* Modpack Version: 3.1.1
* Java Version: 1.8.0_201
* Launcher Used: MultiMC
* Memory Allocated: 8G
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None

**Comment by sk2048** [comment]
This is resolved by #3675
