### ISSUE TITLE
Equipping armor from off hand deletes Tinkers chest plate

### ISSUE THREAD

**Issue by SuperSandro2000** [DarkPacks/SevTech-Ages#3722]
## Bug Report
I had a blood pack in my off hand and tried equipping it while wearing a Tinkers chest plate. My chest plate got deleted and was no where to be found.

## Expected Behaviour
A error sound and nothing happens.

## Steps to Reproduce (for bugs)

1. Equip Tinkers armor
2. put blood pack or possibly any other chest plate in your off hand
3. try equipping the off hand chest plate
4. try to find your Tinkers chestplate

## Logs

* Client/Server Log:
* Crash Log: no crash

## Client Information

* Modpack Version: 3.1.1
* Java Version: 1.8
* Launcher Used: Twitch Launcher
* Memory Allocated: 4608 MB
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed:

## Server Information
* Java Version: 1.8.0_191
* Operating System: Ubuntu 18.10 Cosmic Clutterfish
* Hoster/Hosting Solution: selfhosted
* Sponge (Non-Vanilla Forge) Server: no

**Comment by sk2048** [comment]
This appears to happen whatever armour you're wearing whenever you right-click with a blood letter's pack in the off hand.

Armour swaps as expected if using any other available chest plate in off hand.

Blacklisting the Blood Letter's Pack changes the issue such that the Blood Letter's Pack is now deleted instead.

Will blacklist it and submit an issue to Blood Magic.
