### ISSUE TITLE
Chinese translation was unreadable code

### ISSUE THREAD

**Issue by luzeas** [DarkPacks/SevTech-Ages#3726]
How should the latest version be translated into Chinese？
Where are the titles and descriptions of the achievement?
I don't know where to start.
Would you please tell me where the translated documents are？
thanks.

**Comment by Streamcyper** [comment]
The language localization file for advancments and tips is located under \resources\sevtechages\lang I would guess that to translate it you could just copy one of those and start working out from that. The name of the file would then be " zh_CH " I'm guessing (just running of from https://wpastra.com/docs/complete-list-wordpress-locale-codes/ "

**Comment by sk2048** [comment]
Take a copy of this file: https://github.com/DarkPacks/SevTech-Ages/blob/master/src/resources/sevtechages/lang/en_us.lang
(or if you understand French or Russian better, use that as a starting point!)

Rename it as @Streamcyper described above, though keep it lower case.

Leave everything on the left of the equals sign as it is. Replace everything on the right with your translation.

When you're done, and if you're happy to share what you've done for inclusion in the pack, it would be great if you could open a pull request.

**Comment by luzeas** [comment]
Emmm，all of the Chinese  is unreadable code.
Changing to utf8 and Unicode doesn't help either.
What went wrong？

**Comment by luzeas** [comment]
![360截图17130410104136129](https://user-images.githubusercontent.com/39876309/56425784-533dbb00-62e8-11e9-93d4-a5cf85d0492d.png)
![360截图18550210336439](https://user-images.githubusercontent.com/39876309/56425830-8718e080-62e8-11e9-84e5-d92e7d0dfee7.png)

This is translated，But the text in the game is garbled
Transcoding is fine

**Comment by sk2048** [comment]
Would you mind uploading a copy of the file you're working on here and I'll take a look at it. As there is a Russian translation using the Cyrillic alphabet it seems the mod is capable of displaying unicode characters and so hopefully this is just an issue with encoding.

**Comment by luzeas** [comment]
This is the file being translated
https://github.com/luzeas/minecraft

**Comment by sk2048** [comment]
It does seem to be an encoding issue, file downloaded from your repo is ISO-8859-1 but displayed as though it is UTF-8

When converted to UTF-8 it works in Minecraft.

<img width="368" alt="Screenshot 2019-04-19 at 16 10 28" src="https://user-images.githubusercontent.com/23245543/56430710-17dac680-62bf-11e9-8d4b-c96a6a635c26.png">

**Comment by luzeas** [comment]
=。= Emmmm，What operating system do you use？Windows？Linux？
The file will change from  UTF-8  to ANSI when star game every time.

**Comment by sk2048** [comment]
[Here is](https://raw.githubusercontent.com/sk2048/SevTech-Ages/lang/zh_cn/src/resources/sevtechages/lang/zh_cn.lang) a correctly encoded version of your file, download it and work from that. Works on Windows and Linux.

**Comment by luzeas** [comment]
I have found the reason.
Resource loader will force a change to the language file encoding，consequently , Chinese characters are unreadable code.Have you fixed it？
Hopefully a new version will be released soon and fix this issue

**Comment by sk2048** [comment]
Someone has offered a Chinese Localisation for SkyFactory 4, you may be able to follow their example or ask how they've generated their lang file to aid in your translation of SevTech?

https://github.com/Darkosto/SkyFactory4/pull/22

**Comment by xpesir** [comment]
使用unicode是可行的，但是需要打开'强制使用unicode字体'。
可以使用unicode，但你需要打开'强制Unicode字体'

**Comment by xpesir** [comment]
使用unicode是可行的，但是需要打开'强制使用unicode字体'。
It's possible to use unicode, but you need to turn on'Mandatory Unicode Font'
