### ISSUE TITLE
CTD when opening Antique Atlas in the end

### ISSUE THREAD

**Issue by SuperSandro2000** [DarkPacks/SevTech-Ages#3731]
## Bug Report

Crash to desktop when opening the Antique Atlas in the end Dimension after discovering a end city.

## Expected Behaviour

Not crash

## Possible Solution

Forward to the Author of the mod

## Steps to Reproduce (for bugs)

1. Discover End City
2. Open Atlas

## Logs

* Client/Server Log:  [2019-04-19-4.log.gz](https://github.com/DarkPacks/SevTech-Ages/files/3097858/2019-04-19-4.log.gz)

* Crash Log: [crash-2019-04-19_12.46.21-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/3097855/crash-2019-04-19_12.46.21-client.txt)

## Client Information

* Modpack Version: 3.1.1
* Java Version: 1.8
* Launcher Used: Twitch
* Memory Allocated: 4608 MB
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: some JEI addons

## Server Information
* Java Version: 1.8
* Operating System: Ubuntu
* Hoster/Hosting Solution: myself
* Sponge (Non-Vanilla Forge) Server: no

**Comment by sk2048** [comment]
Antique Atlas have fixed this but not yet released a version with the fix present.

AntiqueAtlasTeam/AntiqueAtlas#215

**Comment by SuperSandro2000** [comment]
Good to know. I keep an eye on that.
