### ISSUE TITLE
Game interaction stopped when crafting hopper

### ISSUE THREAD

**Issue by Nunbear** [DarkPacks/SevTech-Ages#3733]
When crafting a hopper with 5 iron and 2 oak wood using the remote control from simple storage and holding the button to craft a stack my bag filled up with sticks and stopped the pack from letting me interact with anything and stopped the pack from being able to close.

**Comment by sk2048** [comment]
You're in the wrong place, try [here](https://github.com/Darkosto/SkyFactory4Issues/issues) and don't ignore the template.
