### ISSUE TITLE
Cascading WorldGen!

### ISSUE THREAD

**Issue by DrTHC** [DarkPacks/SevTech-Ages#3734]
[I](url) run a little private server that 7 of us regularly go on that runs SevTech Ages 24/7. When Loading in new chunks the server spits out "[Server thread/WARN] [FML] Please report this to the mods issue tracker. [FML] PrimalCore loaded a new chunk [-68, -144] in dimension 0 <overworld> while populating chunk [-69, -144], causing cascading worldgen lag." I have googled and checked the config checked that forge worldgen modifier was active and it is and this is causing huge server lag for everyone. 

I currently have 7.5gb ram allocated to it so we shouldnt be experiancing lag! 
![unknown](https://user-images.githubusercontent.com/49798294/56447333-a2dbb100-62ff-11e9-9e75-626c3c447f65.png)

**Comment by Streamcyper** [comment]
Normally this message appears whenever a something forces more than a single chuck to update. If you do not experience any lag it should not be an issue but if you are experiencing lag I would recommend doing a pre-generation of the world, especially so with 7 players. A oped player can do that with using /forge generation (use the /forge help generation if you need it). I would also recommend restarting the server with regular intervals if possible.

**Comment by DrTHC** [comment]
Ok I shall give the pregeneration ago, I restart the server 2 times a day automatically. :)
