### ISSUE TITLE
Betweenlands inventory disappearing

### ISSUE THREAD

**Issue by IMaFishEatshark** [DarkPacks/SevTech-Ages#3738]
Bug Report 
betweenlands inventory disappears when charm of keeping procs

Steps to Reproduce
1. equip charm of keeping 3
2. equip betweenlands inventory items
3. die and see if they disappear

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
