### ISSUE TITLE
Cauldron with Simplestorage Network

### ISSUE THREAD

**Issue by DarkHope88** [DarkPacks/SevTech-Ages#3739]
## Steps to Reproduce (for bugs)

1. take a torch on the ground
2. set a Cauldron i think Iron in First line # #, second:# #, third: ###
3. Take a Cobble generator Tear 1 next to it
4. Take a Import Simple storage item cable to the couldron and to the Cobblestone generator tear 1
5 take a wrench and click on the point on Couldron.

## Logs

* Client/Server Log:
* Crash Log:     https://pastebin.com/32v8d8qH

## Client Information

* Modpack Version:SF 4
* Java Version:java version "1.8.0_202"
* Launcher Used: Twitch
* Memory Allocated: -Xmx3228m -Xms256m -XX:PermSize=256m -Dminecraft.applet.TargetDirectory="C:\Users\schar\Twitch\Minecraft\Instances\SkyFactory 4" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US
* Server/LAN/Single Player: Server
* Optifine Installed:NO
* Shaders Enabled:NO

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:1.8
* Operating System:Windows Server 2012 R2
* Hoster/Hosting Solution: Contabo
* Sponge (Non-Vanilla Forge) Server: the Standart Serverfiles

**Comment by sk2048** [comment]
This is the issue tracker for SevTech Ages. Please see Darkosto/SkyFactory4Issues
