### ISSUE TITLE
gamerule reduceDebugInfo doesn't work

### ISSUE THREAD

**Issue by TheNeolix** [DarkPacks/SevTech-Ages#3740]
## Bug Report
 coordinates are not showing up anymore for some reason, yesterday it worked fine by using the command /gamerule reduceDebugInfo false, in chat options it's set to OFF as well, and still the debug option (F3) is the same, nor cannot use any coordinates mods with this modpack, yesterday it worked fine and today it just doesn't which it frustrating me to the max limits

## Expected Behaviour
 Nothing happpens

## Possible Solution
 I would say implement 1 more mod into this modpack which would allow us to enable or disable coordinates, where I believe some people don't want to play with it abut some want to, when I'm taking an adventure I also want to get back home to my base and be lost and look for my base for hours

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
* Launcher Used: native
* Memory Allocated: 8Gb
* Server/LAN/Single Player: LAN, single player
* Optifine Installed: Yes, 1.12.1 D3
* Shaders Enabled: No

## World Information
 3.0.8
* Modpack Version world created in: 3.0.8

* Additional Content Installed: No

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
There is a mod in this pack that allows you to view your coordinates, biome, speed, etc. It's called Informational Accessories. It is responsible for removing the information and readding it when you obtain the correct items. A compass will give you your coordinates for example.

There is also a very early game map mod called Antique Atlas. This is my preferred way of navigating in the early game.

Many people choose to die near/in their base before an adventure in the early game and get a death compass that will point them right back there.
