### ISSUE TITLE
Request to update Astral Sorcery to fix sporadic server crash

### ISSUE THREAD

**Issue by alex2069** [DarkPacks/SevTech-Ages#3745]
Using 3.1.1 I've been getting a rare/sporadic server crash when using the telescope from Astral Sorcery.
I reported (updated) their issue with the crash details: https://github.com/HellFirePvP/AstralSorcery/issues/725
The response was to update Astral Sorcery (not sure if you need more details or anything - I haven't really looked into it much beyond the crash report).

**Comment by sk2048** [comment]
Already plan to include a sufficiently updated version in the next pack release

https://github.com/sk2048/SevTech-Ages/blob/mod-update/geolosys/src/config/mputils/changelog.txt#L37
