### ISSUE TITLE
PneumaticCraft Pressure Chamber and Assembly Line working really really unreliable

### ISSUE THREAD

**Issue by SuperSandro2000** [DarkPacks/SevTech-Ages#3746]
## Bug Report
Pressure chamber voids items for the empty PCB and other items unless you replace on of the its blocks.
Assembly line refuses to work. Eventually it will work when placing the machines at the right star constellation.
Pressure is high enough both times.

## Expected Behaviour
That it just works like in 1.7.10.

## Possible Solution
Update the mod, get the issue fixed, remove it until it works, add alternative recipes to avoid the mod.

## Steps to Reproduce (for bugs)
1. Build pressure chamber
2. craft items
3. possibly wait or restart server. No real idea what causes the issue right now.
4. try to craft something

## Logs
* Client/Server Log: 
* Crash Log: no applicable

## Client Information
* Modpack Version: 3.1.1
* Java Version: 1.8
* Launcher Used: Twitch
* Memory Allocated: 4864
* Server/LAN/Single Player: Server
* Optifine Installed: no 
* Shaders Enabled: no

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed: McMultiPart, JEI Addons

## Server Information
* Java Version: 1.8
* Operating System: Ubuntu
* Hoster/Hosting Solution: selfhosted
* Sponge (Non-Vanilla Forge) Server: no

**Comment by sk2048** [comment]
I cannot seem to reproduce any of the issues you've described. I made 3 stacks of Empty PCBs in a pressure chamber, piped them into an assembly system and that turned all of them into unassembled PCBs without issue.

Every time you craft with the pressure chamber, the pressure drops slightly - same with opening the interfaces. Make sure your pressure chamber stays above the pressure threshold and don't leave items sitting in the pressure chamber for too long. I noticed that ghosts of the items the pressure chamber produced were sometimes left there until a block was broken. These were not real items, it was just a visual bug. The correct number of items were produced and outputted.

The assembly line requires that the drill and laser are both directly adjacent to the platform. This has, as far as I'm aware, always been the case. Other than that it is not fussy.
