### ISSUE TITLE
1 FPS Trouble

### ISSUE THREAD

**Issue by xmirniygod** [DarkPacks/SevTech-Ages#3747]
I played your modpack like 1 month ago and everything was fine, but now I have reinstalled and I have problems with 1fps

* Client/Server Log: http://rgho.st/8Sph9ShCr
* Crash Log: no crash 
![32](https://user-images.githubusercontent.com/50048845/56850221-4896ad80-6908-11e9-8493-d701bf332911.png)

* Modpack Version: 3.08
* Launcher Used: 1 
* Memory Allocated: 6144mb
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

* Additional Content Installed: No

**Comment by xmirniygod** [comment]
UPD : 
GPU : Sapphire Radeon RX470 NITRO+
CPU : Intel core i5 3340
RAM : 12gb ddr3

**Comment by SuperSandro2000** [comment]
You should probably check F3 whats going on. Maybe you limited the game to 1 FPS by accident?
