### ISSUE TITLE
Hellfire forge broken lesser tartaric gem

### ISSUE THREAD

**Issue by maxall41** [DarkPacks/SevTech-Ages#3748]
when i try to make a lesser gem nothing happens ive looked over the recipe 1000 times and im using a petty gem with 12.0 will power

**Comment by sk2048** [comment]
If you hover over the arrow of the Hellfire Forge recipes in JEI it will tell you how much Demonic Will you need. The lesser gem requires a minimum of 60 stored will, but it will only consume 20 of it.
