### ISSUE TITLE
Streams mod and Water control extreme

### ISSUE THREAD

**Issue by ToxicVenom3** [DarkPacks/SevTech-Ages#3751]
With the latest mod pack (3.1.1) I ran into an issue  where I was unable to find any flowing streams. While I was exploring I ran into multiple places where it looked like streams would have been. After doing some digging through the streams source code I was able to get them working again. All I did was add  'streams:FixedFlowBlock' (without the apostrophes) to the infinite bioms section of the water control mod config and it worked like a charm.

**Comment by sk2048** [comment]
I have not seen any issue with the generation of streams in 3.1.1, in fact I just went and found one in new chunks in my testing world to validate this.

You have identified a custom block class which the streams mod uses to prevent the water from stopping flowing if it receives a block update. This is not a biome, and adding it to a list of permitted biomes will not have an effect. These blocks are in fact unaffected by Water Control Extreme and you can use a stream of sufficient depth to provide you with infinite water.

I suspect you just got unlucky and did not find one prior to making that change to the config.
