### ISSUE TITLE
Crash when loading world, seems related to Astral Sorcery perks?

### ISSUE THREAD

**Issue by X3n0n3x** [DarkPacks/SevTech-Ages#3753]
## Bug Report

Last night everything seemed to be working fine, but now trying to play again, every time I go to "SinglePlayer" then select my world and click "Play" and it starts loading, after ~30 seconds or so it notes that it's "Shutting down internal server" then closes the game out and gives me a crash report.  This happens every time, and even when attempted to load slightly earlier backups.

## Expected Behaviour

I should be able to load and play my world normally.

## Possible Solution

The first bunch of entries in the crash report are all things like:

`java.lang.NullPointerException: Unexpected error at hellfirepvp.astralsorcery.common.constellation.perk.PerkLevelManager.resolveLevelCap(PerkLevelManager.java:110)`

so it makes me think it's related to the Astral Sorcery perk system?

This makes sense because last night is when I unlocked the Astral Sorcery perk system for the first time, in Age 2. Additionally, while I picked the attunement which levels up by placing blocks first, I noticed that it leveled up extremely slowly, taking quite a while to just get halfway up level 1, so I crafted & used a "Shifting Star" item to swap my attunement to 'Vicio," which levels up by moving instead. Suddenly I was gaining whole attunement levels just from walking from one side of my base to the other (I had on Wild Dog boots, lots of Dirt Paths, and a few 5x Horse Totems around, so I run at a decent speed I guess). After a half hour or so of just moving around my base and fiddling with more Astral Sorcery stuff, I was at attunement level 14, which seems ridiculously quick given how slowly I was leveling up with the old constellation. Perhaps this is related to my current crash? I continued playing for another few hours after this without noticing any problems, it is only now when trying to load the world that it crashes.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log: latest.log at  https://gist.github.com/X3n0n3x/689efacb45e19859c458ab0b52b888d1
* Crash Log: crash-2019-05-01_13.14.29-client at https://pastebin.com/W9TCRfQN

## Client Information

* Modpack Version: 3.1.1
* Java Version: Java v1.8.0.181 (64 bit)
* Launcher Used: Twitch, with JAR Launcher
* Memory Allocated: 8192 MB
* Server/LAN/Single Player: Singleplayer 
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8 (I updated to v3.1.1 at the very end of Age 1, just before advancing to Age 2)

* Additional Content Installed: No other mods, but I disabled "SmoothFonts" via Twitch profile options for performance, and am also using these "Additional Arguments" in Twitch Launcher:
`-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`

**Comment by X3n0n3x** [comment]
**UPDATE:**

Apparently this problem has [happened to others](https://github.com/HellFirePvP/AstralSorcery/issues/1092), and supposedly was fixed in v1.12.2-1.10.12, so I will attempt updating Astral Sorcery to v1.12.2-1.10.17 using the Twitch "update" button in the "installed Mods" list for Sevtech, and we'll see what happens.

**Comment by sk2048** [comment]
Closed by 2869088
