### ISSUE TITLE
Lost advancements

### ISSUE THREAD

**Issue by AMR2586** [DarkPacks/SevTech-Ages#3755]
Hello,

When I updated from 3.0.8 to 3.1.1 I lost my advancements and now all my items appear as "unfamiliar." When I try to pick things up to quickly re-learn them, it still doesn't work. 

Is there a way to restore my advancements?

Thank you,
Adam

**Comment by AMR2586** [comment]
I can't even pick up dirt. Everything is unfamiliar.

**Comment by AMR2586** [comment]
Nothing shows up as in JEI except a couple enchanted books.

**Comment by sk2048** [comment]
So it shouldn't be possible for you not to understand dirt, every player is given the game stage required for that on login. Try quitting and loading in again.

If that doesn't work there's a bunch of commands to run to fix things:
`/gamestage add @p tutorial` to get the basics understood again.

For every age you've completed, run the following command
`/advancement grant @p from triumph:age<number>/root`
So if you were mid way through age 2 do
```
/advancement grant @p from triumph:age0/root
/advancement grant @p from triumph:age1/root
```
And then it's probably easiest to just do the advancements from that point on.

**Comment by AMR2586** [comment]
So, the "/gamestage add @p tutorial" worked to understand basics. However, while the rest of the commands seem to give me back the advancements, non-basic items still show up as unfamiliar. When I highlight over them, they still say I need so-and-so from age 0 or age 2 or whichever it happens to be, despite having achievements through age 4.

**Comment by AMR2586** [comment]
Author
AMR2586 <https://github.com/AMR2586> commented 2 hours ago <https://github.com/DarkPacks/SevTech-Ages/issues/3755#issuecomment-489369352>
So, the "/gamestage add @p <https://github.com/p> tutorial" worked to understand basics. However, while the rest of the commands seem to give me back the advancements, non-basic items still show up as unfamiliar. When I highlight over them, they still say I need so-and-so from age 0 or age 2 or whichever it happens to be, despite having achievements through age 4.
