### ISSUE TITLE
[3.1.1] Crushed Quartz can only be made in BetterWithMods mill stone

### ISSUE THREAD

**Issue by Stifling-Bossness** [DarkPacks/SevTech-Ages#3757]
## Bug Report
Crushed Quartz, used for making stardust in the starlight infuser, is only obtainable by crushing nether quartz in the Better With Mods mill stone. Changes in 3.1.x made crushing quartz in other machines gives you either Certus Quartz dust or Nether Quartz dust, neither of which can be used to make stardust. This makes making stardust in the later game a relative pain.

[Crushed Quartz](https://i.imgur.com/8yTdO8I.png)
[Stardust](https://i.imgur.com/tAai5Kk.png)

## Expected Behaviour
Able to use any or either type of crushed quartz to make stardust.

## Possible Solution
(1) Change stardust recipe to use either type of crushed quartz.
(2) Add additional stardust recipes using either type of crushed quartz.
(3) Make Crushed Quartz obtainable in more ways.

## Client Information
* Modpack Version: 3.1.1
* Java Version: Java 8 64-bit 212
* Launcher Used: Twitch
* Memory Allocated: 7GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes, E4
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.6-ish
* Additional Content Installed: VanillaFix, Phosphor, Akashic Tome, Morph-O-Tool.

**Comment by kyrandita** [comment]
I noticed the other day this is an issue with multiple recipes with the mill stone vs later tiers
regular millstone works on various types of netherrack, industrial mill only work on "pure" netherrack...
