### ISSUE TITLE
[3.1.1] Health resetting when loading world

### ISSUE THREAD

**Issue by Stifling-Bossness** [DarkPacks/SevTech-Ages#3758]
## Bug Report
I have 3.5-ish health bars worth of hearts, but everytime I load the world I get set back down to 1.5-ish health bars. I can regain the hearts as normal, but this is fairly annoying and draining my food stocks. This only started after updating to 3.1.x, so I believe it's tied to the new Astral Sorcery perk tree where I get most of my hearts.

## Expected Behaviour
Retain your hearts upon reloading a world or changing dimensions.

## Steps to Reproduce (for bugs)
1. Have an above-normal amount of hearts
2. Reload the world
3. Notice your hearts are below your previous amount, and spend a stupid amount of food to regen.

## Logs
* Client/Server Log: https://gist.github.com/Stifling-Bossness/e5df41b1a43c9c52cd3f7e41010180fe

## Client Information
* Modpack Version: 3.1.1
* Java Version: Java 8 64-bit 212
* Launcher Used: Twitch
* Memory Allocated: 7GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes, E4
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.6-ish
* Additional Content Installed: VanillaFix, Phosphor, Akashic Tome, Morph-O-Tool

**Comment by GearsOfClockwork** [comment]
Why is this labeled as cannot reproduce? You have Aevitas perks, right?
I had this problem too, and I found this:

[https://github.com/HellFirePvP/AstralSorcery/issues/1017](url)

It's 3 months old, but they didn't sound like they wanted to fix it.

**Comment by Stifling-Bossness** [comment]
Yup, that's the same issue. So I guess since it's an issue with AS and not SevTech, I'll close this.

**Comment by sk2048** [comment]
@GearsOfClockwork Labelled as cannot reproduce as I added a bunch of nutrition to my player (above-normal hearts), changed dimensions a bunch, reloaded the world, reloaded the pack and still could not get it to happen to me. Thank you for placing the cause of this issue though.
