### ISSUE TITLE
[3.0.8] astral sorcery resonating wand issue

### ISSUE THREAD

**Issue by Ironbloodclaw** [DarkPacks/SevTech-Ages#3760]
## Bug Report
for some reason the astral sorcery resonating wand doesn't seem to work to find crystals i can't seem to get it to even work under artificial means by putting down the ore and checking then

## Expected Behaviour
the particles or ray of light or what ever it is to show up 

## Possible Solution
no idea

## Steps to Reproduce (for bugs)

1. just seems to have happened as if it was just randomly by instance of the pack

## Client Information

* Modpack Version: 3.0.8
* Java Version: 10 i think
* Launcher Used: twitch
* Memory Allocated: 3888 Mb
* Server/LAN/Single Player :Single player
* Optifine Installed: N/A
* Shaders Enabled: N/A

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None

**Comment by sk2048** [comment]
```
Rock Crystals are important for Astral Sorcery progression. Find a Rock Crystal sample on the surface and dig down to find the ore between Y3 and Y18
```
The resonating wand does not have that function in this pack, the advancement description above describes how to find Rock Crystals.

**Comment by Ironbloodclaw** [comment]
ok well that isn't what the modpack said at all on my end and more so i've been digging there haven't found zilch even more so with the dowsing rod so not sure whats going O.o?

**Comment by Ironbloodclaw** [comment]
also not trying to be rude i'm just finding it impossible to find these >.<
