### ISSUE TITLE
[3.1.1] Pre-Launch Checklist book is only available in age 5

### ISSUE THREAD

**Issue by Stifling-Bossness** [DarkPacks/SevTech-Ages#3762]
## Context
Having the book available in age 4 may help prevent some people from landing on the moon with an inadequate oxygen setup. The book does, however, have info on landing on planets beyond the moon, so perhaps having some sort of additional pre-loaded checklist may be a preferential alternative.

**Comment by sk2048** [comment]
It's my opinion that the pre-launch checklist provides no useful guidance to players travelling to the moon and so I will not be adjusting the staging of it.
