### ISSUE TITLE
Suggestion: Make Construction Paste craftable in the Hydrator

### ISSUE THREAD

**Issue by GearsOfClockwork** [DarkPacks/SevTech-Ages#3766]
## Context

It would make it much easier to produce, since you can't just use the building gadget in the water without potentially messing up the coastline.  I doubt it would be too OP because vanilla concrete can be made in the hydrator anyways.

**Comment by sk2048** [comment]
I think a change in Building Gadgets renders this invalid. In v2.6.7 of the mod, the authors changed how construction paste was obtained - the new process is outlined below (copied from their changelog, obviously not all the listed machines are available in SevTech):

* Craft a construction powder block.
  * Convert the powder into a dense construction block by either placing it in the word next to water, or using one of the following machines:
    * Fluid Transposer [Thermal Expansion]
    * Hydrator [Cyclic]
    * Moistener [Forestry]
* Get paste from the block by either:
  * Breaking it, yielding 1-3 paste.
  * Using machines:
    * Convert it into dense construction chunks (1 block -> 4 chunks):
      * Pulverizer [Thermal Expansion]
      * Macerator [Industrial Craft 2]
      * Grinder [Applied Energistics 2]
      * Crusher [Mekanism]
      * Crusher [Immersive Engineering]
      * Crusher [Actually Additions]
    * Convert the chunks into paste using any of the machines listed in step 3 (1 chunk -> 1 paste).

**Comment by GearsOfClockwork** [comment]
Alright, cool. If that update is going to be in the next version, I guess I'll close this.
