### ISSUE TITLE
[3.1.1] Ender Utilities Handy Bag crash

### ISSUE THREAD

**Issue by Stifling-Bossness** [DarkPacks/SevTech-Ages#3768]
## Bug Report
I was rapidly changing the tool in my hotbar by pressing 2 (the slot in the hotbar I wanted) and it crashed the game. I think it's related to the fact that I've got a large handy bag equipped, it changes the inventory screen.

## Steps to Reproduce (for bugs)
1. Equip large Handy Bag from Ender Utilities
2. Rapidly (multiple times per second) change items in your hotbar by pressing the corresponding key
3. Crash

## Logs
* Client/Server Log: https://gist.github.com/Stifling-Bossness/f0308f85b6b441e0bd0fcc3533392ae4
* Crash Log: https://gist.github.com/Stifling-Bossness/597758d76337fb3cecdf673c002da7b4

## Client Information
* Modpack Version: 3.1.1
* Java Version: Java 8 64-bit 212
* Launcher Used: Twitch
* Memory Allocated: 7GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes, E4
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.6-ish
* Additional Content Installed: Akashic Tome, Morph-O-Tool, MCMultiPart, VanillaFix, Phosphor

**Comment by sk2048** [comment]
Looks like a race condition between pressing a number key and clicking?

**Comment by sk2048** [comment]
Nothing we can really do here, and seems to be an edge case.
