### ISSUE TITLE
Update Constructs Armory

### ISSUE THREAD

**Issue by cinnamennen** [DarkPacks/SevTech-Ages#3771]
same request as #3307.
There is a bug in the used version of Constructs's Armory, it'd be nice to see it updated.

Previous issue was closed to be fixed in the next update, but that never came to fruition

**Comment by sk2048** [comment]
The current latest version of this pack (3.1.1) includes version 1.2.3 of Construct's Armory. This was released on 16/01/2019, whilst the issue you reference was committed to their repo on the 12th June 2018. There is no reason this fix wouldn't be included in the released version of the mod.

If there is still an issue, then you should file an issue with ConArm and copy us in on it.

**Comment by cinnamennen** [comment]
Ah, it's fixed in beta releases
