### ISSUE TITLE
Modular Machinery version mismatch in 3.10beta

### ISSUE THREAD

**Issue by bigtimeweenfan** [DarkPacks/SevTech-Ages#3772]
Just installed 3.10 beta server and 3.10 client. Looks like there might be a client/server version mismatch:

[20:27:39] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: ===== lost connection: Server Mod rejections:
Modular Machinery: Requires version 1.9.5 but client has 1.9.6.

I confirmed on server side it is indeed modularmachinery-1.9.5.jar

**Comment by sk2048** [comment]
Make sure to use 3.1.1, which uses Modular Machinery 1.9.5 as a bug in 1.9.6 will prevent you from producing plastic required for progression.

**Comment by bigtimeweenfan** [comment]
Yeah, closed this. I'm a dummy. Thought my server was 3.10, and I was using 3.11. doh!
