### ISSUE TITLE
[3.1.1] Twitch version crashes trying to enter new world (not tech-savvy user)

### ISSUE THREAD

**Issue by aerowx** [DarkPacks/SevTech-Ages#3773]
## Bug Report

Fresh install of Twitch 3.1.1 modpack crashes after starting a new world, updated Java, still crashes

## Expected Behaviour

Game lets me play the modpack without CTD

## Possible Solution

n/a: not tech-savvy

## Steps to Reproduce (for bugs)

1. Install fresh version 3.1.1 from Twitch
2. Start up game, change mouse sensitivity to 130 and master volume to 50
3. Create new world
4. Load in the game and see the Buildcraft notice pop up
5. Java CTD

## Logs

* Client/Server Log:
* Crash Log:

I don't know what the differences are between these two (directions would be appreciated), so here is the SevTech Ages\logs\latest.log (divided into 4 parts, as I do not have the pro version of Pastebin)
Part 1: https://pastebin.com/ELCGwpSC
Part 2: https://pastebin.com/JQSzPdyX
Part 3: https://pastebin.com/adBxPHQJ
Part 4: https://pastebin.com/Um89GjBP

## Client Information

* Modpack Version: 3.1.1
* Java Version: Java 8 version 1.8.0_211 64-bit
* Launcher Used: Twitch
* Memory Allocated: 7168mb
* Server/LAN/Single Player: single player
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.1.1 new world

* Additional Content Installed: n/a

**Comment by sk2048** [comment]
Your log cuts off with no error, whilst errors in Minecraft are handled fairly gracefully.

Something is either killing Java (antivirus?) or the JVM itself is doing something so serious it terminates itself immediately. Is there a file named something like hs_err_pid<some_number>.log?
