### ISSUE TITLE
Stage 0 finished ! but still stage 1 mod locked

### ISSUE THREAD

**Issue by DjDjalilo** [DarkPacks/SevTech-Ages#3777]
## Bug Report
Hi i just finish the stage 0 but i still have the old mod nothing new , i can't craft a regular crafting table.

## Steps to Reproduce (for bugs)

1. Craft the last smelter.
2.  firework to congrate me and tell me Stage 0 complete.
3. Stage 1 unlocked in Advancement menu "L".
4. Still with old mod .
5. try to craft regular crafting table and nothing happens.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:3.1.1
* Java Version:7
* Launcher Used: ATlauncher 
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single player
* Optifine Installed: NO
* Shaders Enabled: NO

## World Information
3.1.1
* Modpack Version world created in: 3.1.1

* Additional Content Installed:

**Comment by DjDjalilo** [comment]
here some screenshots : 
https://imgur.com/a/WPjvYfp
https://imgur.com/a/5yqpYOy
https://imgur.com/a/OJHOA3k

**Comment by sk2048** [comment]
Java 7 is not supported, we recommend the latest Java 8 - 1.8.0_211

**Comment by DjDjalilo** [comment]
@sk2048 i update it and still the same probleme

**Comment by sk2048** [comment]
The trigger to unlock the next age fires when you unlock the advancement. As you haven't unlocked it again, it's not the same problem.

Do you have cheats enabled?

**Comment by DjDjalilo** [comment]
@sk2048  yeah !

**Comment by sk2048** [comment]
Run the following commands:
`/advancement revoke @p only triumph:stage0/melter`
`/advancement grant @p only triumph:stage0/melter`

That should rerun the trigger and hopefully put you in the correct age.

**Comment by DjDjalilo** [comment]
@sk2048 yeah its working thank you !
