### ISSUE TITLE
Birch log stacks still craftable (Possibly others)

### ISSUE THREAD

**Issue by FlyveHest** [DarkPacks/SevTech-Ages#3778]
## Bug Report
I'm guessing that log stacks shouldn't be craftable, so charcoal should be generated using other methods, and they aren't for oak, but you can craft them using birch.

## Expected Behaviour
Birch log stacks shouldn't be craftable.

## Possible Solution
It seems like the recipe is only disable for oak wood.

## Steps to Reproduce (for bugs)
1. Strip birch wood of bark
2. Chop them
3. Put 9 split logs in crafting
4. Get stack

## Client Information

* Modpack Version: 3.1.1

**Comment by sk2048** [comment]
Couldn't reproduce this, possibly an issue with your install.
