### ISSUE TITLE
Lost my progression when moving from single to multiplayer

### ISSUE THREAD

**Issue by DjDjalilo** [DarkPacks/SevTech-Ages#3781]
## Bug Report
Hi, recently i wanted to play with my brother (in lan) so i made a server and i juste replace the "world" folder by my saves in single player , but when i run the server and connect in, i lost all my progression (stuffs, quest...et ) and i play with the same accouny.

## Steps to Reproduce (for bugs)

1.Create a server
2.Start the server to generate a new world
3.Stop the server
4.Delete the "world" folder
5.Copy my old save in single player
6.Paste it on ly server folder
7.Rename it into "world"
8.Start the server
9.the cmd sad some entities missing and if i want to continue or not
10.i put the command : /fml confirm
11. the server succefully stared
12. i connect on the server
13. i lost all my progression but the block , item in chest , structure still there. 

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:3.1.1
* Java Version:8
* Launcher Used:AtLauncher
* Memory Allocated:8GB
* Server/LAN/Single Player:LAN (or server iam not sure...)
* Optifine Installed:No
* Shaders Enabled:No

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:8
* Operating System: Windows 10
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
I'd be interested to know what entries went missing. That shouldn't have happened. Could be a config mismatch between your client and server. Maybe try this again with the server files from Curseforge (ATLauncher server files are automatically generated and sometimes that causes problems).

If that doesn't work, you can restore advancements using commands:

For every age you've completed, run the following command
`/advancement grant @p from triumph:age<number>/root`
So if you were mid way through age 2 do

`/advancement grant @p from triumph:age0/root`
`/advancement grant @p from triumph:age1/root`
