### ISSUE TITLE
Game crashes after loading game

### ISSUE THREAD

**Issue by TheRandomWeeb** [DarkPacks/SevTech-Ages#3788]
## Bug Report
The game crashes when I finally load to the title screen

## Expected Behaviour
Not crashing

## Steps to Reproduce (for bugs)
1. Load game
2. Wait for the loading to finish
3. Crash

## Logs
* Client/Server Log:
* Crash Log: https://pastebin.com/XHGwXenD

## Client Information
* Modpack Version: 3.1.1
* Java Version: Java 8 Update 211 
* Launcher Used: Twitch
* Memory Allocated: 8gb
* Server/LAN/Single Player: Server turned on but haven't joined yet
* Optifine Installed: Yes
* Shaders Enabled: Yes

**Comment by sk2048** [comment]
You are using the wrong version of Optifine; SevTech 3.0.8 is fairly old and changes made in Forge mean newer versions will not work. Either update SevTech to 3.1.1 or use Optifine D3.
