### ISSUE TITLE
[3.1.1] Dye powder in Manual Grindstone gives flowers

### ISSUE THREAD

**Issue by delax** [DarkPacks/SevTech-Ages#3790]
## Bug Report

Only a subset of flowers (and ink sacs etc) can be ground into their respective dye powder.
All dye powders can be ground into some plant.
![error small](https://user-images.githubusercontent.com/2775517/58398332-c098e600-8022-11e9-8888-c8029d134d5a.jpg)

## Expected Behaviour

The automated crushers show the correct recipes
![error small 2](https://user-images.githubusercontent.com/2775517/58398720-f38fa980-8023-11e9-8644-caac26fadced.jpg)

## Possible Solution

Appears to be a zs script error

## Steps to Reproduce (for bugs)

1. Be in Stage 0
2. Use manual Horsepower grindstone to Grind any dye
3. Collect Flower
4. Use BWM grindstone to grind flower into dye
5. return to 2

## Logs
No crashing involved

## World Information

* Modpack Version world created in: 3.1.1

**Comment by sk2048** [comment]
Closed in a568a8a
