### ISSUE TITLE
Starting the game from jar launcher

### ISSUE THREAD

**Issue by rjzvara** [DarkPacks/SevTech-Ages#3792]
## Bug Report

crashing at launch from jar launcher

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:  https://pastebin.com/rBU24d97

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.211
* Launcher Used: jar
* Memory Allocated: 8gb
* Server/LAN/Single Player: singplayer
* Optifine Installed: yes
* Shaders Enabled: no

**Comment by sk2048** [comment]
You've got the wrong version of optifine. Use D3 for SevTech 3.0.8 or update to SevTech 3.1.1 to use E3.
