### ISSUE TITLE
[3.1.2 beta] Immersive Engineering Metal Press not showing in JEI

### ISSUE THREAD

**Issue by sk2048** [DarkPacks/SevTech-Ages#3793]
## Bug Report
Metal press JEI plugin doesn't seem to work with newer versions of JEI. Confirmed in minimal instance (JEI 4.15.0.279, IE 0.12-89) - no relevant log output.

## Possible Solution

* Diagnose issue, report to JEI or IE, hope for fix before release else downgrade JEI
* Possibly fix with SevTweaks

## Steps to Reproduce (for bugs)

1. Check recipes of any Mold
2. Confirm recipes still work despite not showing up in JEI

## Client Information

* Modpack Version: 3.1.2
* Java Version: Oracle 1.8.0_211
* Launcher Used: Twitch
* Memory Allocated: 5GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.1.2

* Additional Content Installed: None

**Comment by Darkosto** [comment]
JEI version 4.15.0.283 fixes this. I've updated the mod in the pack. 

What issues does this version of JEI cause that we weren't using it already?

**Comment by sk2048** [comment]
The metal press didn't show up in JEI and 283 was not released when I last updated mods.

If this is now fixed then I am not aware of any issues that would prevent us using 283.
