### ISSUE TITLE
Single Player Crash

### ISSUE THREAD

**Issue by Flamebom** [DarkPacks/SevTech-Ages#3794]
The game crashes upon loading,
## Steps to Reproduce (for bugs)

1. Try to load world
2. Crash and get kicked to launcher

## Logs

* Client/Server Log:https://pastebin.com/0zrf6bPN
* Crash Log: None

## Client Information
* Modpack Version:3.11
* Java Version: 8u211
* Launcher Used: Twitch
* Memory Allocated:5120
* Server/LAN/Single Player: Single Player though other people were connected via LAN
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.11

* Additional Content Installed: No

There's some random spikes some times when I play and I'm using Open J9

**Comment by sk2048** [comment]
This pack (and modded Minecraft in general) does not play well with OpenJ9, use OpenJDK or Oracle implementations.
