### ISSUE TITLE
Issue with setting up the server for the first time "failed to BIND"

### ISSUE THREAD

**Issue by beng934** [DarkPacks/SevTech-Ages#3797]
https://pastebin.com/T1hjxCMT
 No other mods installed.

## Bug Report
Server start isn't starting the server and keeps coming up with errors about failing to bind?
Pasted a log above^

I've tried just using my public IP but it doesn't seem to work. I've tried to port forward the specific port purely for this but it also gives the same error.

## Steps to Reproduce (for bugs)

1. https://pastebin.com/T1hjxCMT
2.

## Logs

* Client/Server Log: https://pastebin.com/T1hjxCMT
* Crash Log:

## Client Information

* Modpack Version: 3.1.1
* Java Version: Latest
* Launcher Used: Twitch mods
* Memory Allocated: 8gb
* Server/LAN/Single Player: Server
* Optifine Installed: Not sure what this is
* Shaders Enabled: ?

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System: Windows 10
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by Streamcyper** [comment]
You would probably have better luck getting help with this over at the discord https://discord.gg/darkosto
