### ISSUE TITLE
3.1.1 Tutorial Impossible to Complete

### ISSUE THREAD

**Issue by The-Beholder** [DarkPacks/SevTech-Ages#3798]
## Bug Report
When I go to craft the Grass Fiber Mesh I can't because it needs a 3x3 grid, which is impossible at that point, and when I craft a Chopping Block (after cheating in a mesh) it won't take the log, it places it like the chopping block was a slab.
![2019-06-01_10 59 16](https://user-images.githubusercontent.com/51269679/58751102-bbdb9400-845f-11e9-8f41-2a3a1a1f14cd.png)

## Expected Behaviour
When I click on the Grass Mesh in JEI it shows the 3x3 instead of a 2x2 like it should, it shows the sticks in the corners and the fiber in the rest of the space.

## Client Information

* Modpack Version: 3.1.1
* Java Version: 8
* Launcher Used: Forge
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: False
* Shaders Enabled: False

## World Information
* Modpack Version world created in: 3.1.1

**Comment by Streamcyper** [comment]
It shows it in a 3x3 crafting window, but it only 4 items 2 sticks and 2 plant twine.... Perfectly fine to craft in your inventory.

**Comment by The-Beholder** [comment]
![2019-06-01_11 49 43](https://user-images.githubusercontent.com/51269679/58751392-686b4500-8463-11e9-8a13-071b49dc9ab7.png)

**Comment by Streamcyper** [comment]
Doesn't look like the scripts have activated properly. As the recipe doesn't look staged, and you should not have all the different crafting stations on the side, and that is not the normal recipe. I would recommend going to the discord  https://discord.gg/darkosto

**Comment by The-Beholder** [comment]
> Doesn't look like the scripts have activated properly. As the recipe doesn't look staged, and you should not have all the different crafting stations on the side, and that is not the normal recipe. I would recommend going to the discord https://discord.gg/darkosto

What about the Chopping Block?

**Comment by The-Beholder** [comment]
Apparently, I downloaded wrong. Thank you @Streamcyper!
