### ISSUE TITLE
Magma Verus drops from Shulkers but is disabled

### ISSUE THREAD

**Issue by sk2048** [DarkPacks/SevTech-Ages#3799]
Magma Cream Verus can be crafted to make a block similar to magma cream that deals magic damage and also provides an updraft for players flying overhead using elytra.

This would make a nice addition for making frequent flight lanes that could be flown along without using rockets.

## Possible Solution

Either remove the drop or stage the item and block.

## Client Information

* Modpack Version: 3.1.2 beta

**Comment by Darkosto** [comment]
The drops and block can be set to Stage 4 and allowed to be crafted at that point.
