### ISSUE TITLE
RFE: allow rice slimeballs to be created via the Jerrycan once it is gated in

### ISSUE THREAD

**Issue by WebDragon** [DarkPacks/SevTech-Ages#3801]
## Context
1. making rice slimeballs out of rice dough is currently confined to 1 bucket at a time. it would be an immense QoL improvement if you could use the Jerrycan to create 10 at once, similarly to how you can use the jerrycan to mass-produce treated wood and other items. 

2. also, while this is technically a separate issue, the Jerrycan should show as an option for creating some of these items in bulk if that were at all possible to show in JEI. I can open a separate ticket for this if you prefer/desire.

**Comment by sk2048** [comment]
I've spent longer on this than I care to admit..

The 2nd point - alternative options for fluid storage are hidden from JEI deliberately to reduce clutter. This means they also get hidden from recipes. Also, when the jerrycan is allowed to display for these recipes, it shows as empty as the NBT tag in the recipe is technically invalid - it specifies only a fluid name, but not an amount.

**Comment by sk2048** [comment]
![2019-06-04_17 44 41](https://user-images.githubusercontent.com/23245543/58897548-741f6b80-86f0-11e9-90c1-04401fba83a6.png)

**Comment by WebDragon** [comment]
well the Jerrycan doesn't necessarily have to show as an option -- it doesn't for the Treated Wood + Creosote; it just has to **_work_** for rice slimeballs.

**Comment by sk2048** [comment]
The recipe works, it took a while because I wanted to make sure you couldn't use a Jerrycan with less than 1000mB of fluid to perform the craft. The only remaining issue is how it displays in JEI.

**Comment by WebDragon** [comment]
Oh? well, congrats and thank you! even halfway there is great and perfectly on-par with what I've come to expect from IE w.r.t. the treated wood recipe.
