### ISSUE TITLE
cannot apply texture pack

### ISSUE THREAD

**Issue by aidnabedding** [DarkPacks/SevTech-Ages#3802]
## Bug Report
game crashes when trying to load with a texture pack

## Expected Behaviour
texture pack changes and game continues with new textures

## Possible Solution
tried adding more (and less) RAM, althogh it did not seem to affect it
combining the vanilla and modded textures into one file did not seem to help

## Steps to Reproduce (for bugs)
1. add resourcepacks to folder
2. select resourcepacks
3. press the "done" button

## Logs
* Client/Server Log:
* Crash Log: https://pastebin.com/E97aBRtB

## Client Information

* Modpack Version: 3.1.1
* Java Version: jre1.8.0_211
* Launcher Used: Twitch
* Memory Allocated: 7gb
* Server/LAN/Single Player: server
* Optifine Installed: no 
* Shaders Enabled: no

**Comment by sk2048** [comment]
`Unable to fit: betterwithmods:blocks/rope_side - size: 64x64 - Maybe try a lowerresolution resourcepack?`

You may not have enough RAM allocated, or enough VRAM available for the texture pack you are trying to use.
