### ISSUE TITLE
Mod Dependency Missing on install

### ISSUE THREAD

**Issue by DragonSlayerDX3** [DarkPacks/SevTech-Ages#3803]
When I try to download the modpack, it downloads the pack and unzips it for a little, before failing, deleting everything, and throwing up a splash saying "Cannot Find addon dependency 242247". It does this every single time I try, without fail. Any suggestions?

![Capture](https://user-images.githubusercontent.com/26584211/58919717-19404100-86fd-11e9-894b-d25a4f96eb0e.PNG)

**Comment by DragonSlayerDX3** [comment]
_I would attach labels to this if I could but this is legitimately my first time using Github in forever and IDK how to_

**Comment by sk2048** [comment]
Unfortunately, this appears to be an issue with the Twitch launcher, which we have no control over.

You can try installing the pack through MultiMC or ATLauncher, or wait for Twitch to fix the issue.
