### ISSUE TITLE
3.1.1 Something Strange in Towerwood

### ISSUE THREAD

**Issue by CypherRPG** [DarkPacks/SevTech-Ages#3804]
## Bug Report

While fighting the Ur-Ghast using the ghast traps did not receive the Something Strange in Towerwood advancement.  

## Expected Behaviour

I was fighting the Ur-Ghast and using the Ghast Traps.  I defeated several Carminite Ghastlings and used the traps to defeat the Ur-Ghast.  I received the Tears for Fire advancement but did not receive the Something Strange in Towerwood advancement.

## Possible Solution

Upon some investigation of the triumph scripts, there appears to be no script for this advancement.  I did a search for any references for ghast_trap and found none.  I believe that if a triumph script is written for this advancement it would solve the issue.  However, I may have missed something in my search.

## Steps to Reproduce (for bugs)

1.  Simply use the traps to defeat the Ur-Ghast to reproduce the issue.
2.

## Logs

* Client/Server Log:  Unable to paste log to Pastebin.  Exceed 512 kb limit.  Am happy to provide a different way.  However, have provided screenshot.
![sevtech 3 1 1](https://user-images.githubusercontent.com/51390074/58925089-45b38780-8714-11e9-9205-915aadcb0c64.jpg)

* Crash Log: No crash log since issue did not cause crash.

## Client Information

* Modpack Version: 3.1.1
* Java Version: 1.8.0_211 64-bit
* Launcher Used: MultiMC 0.6.5-1302
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes, OptiFine_1.12.2_HD_U_E3 
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.1.1

* Additional Content Installed: No

**Comment by sk2048** [comment]
There is no Triumph script because the Twilight Forest advancements are not modified. I'm not sure why overwriting it would make a difference as we're still relying on the TF trigger.

**Comment by CypherRPG** [comment]
Sam,

Thanks for the response and I understand.  BTW, great pack.
