### ISSUE TITLE
Crashing after texture stitching then it said that it was corrupted after reinstall

### ISSUE THREAD

**Issue by Zevatronic** [DarkPacks/SevTech-Ages#3807]
## Bug Report
crashing after texture stitching

## Expected Behaviour
load up to main menu
has crashes almost every time I load it up at the same point and it has made me hit myself in the head over it

## Possible Solution
the bug could be something in the way items are loaded

## Steps to Reproduce (for bugs)

1.start game
2.wait until crash
it goes through random periods of crashing or being fine

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:3.1.1
* Java Version:
* Launcher Used:ATLauncher
* Memory Allocated: Max Mem 6,144
* Server/LAN/Single Player:single
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.1.1 (minecraft 1.12.2)

* Additional Content Installed: sphax64x and sevtech texture patch

[crash-2019-06-12_12.52.04-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/3283327/crash-2019-06-12_12.52.04-client.txt)
[crash-2019-06-12_13.05.20-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/3283328/crash-2019-06-12_13.05.20-client.txt)
[crash-2019-06-12_13.18.55-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/3283329/crash-2019-06-12_13.18.55-client.txt)
[crash-2019-06-12_14.38.09-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/3283330/crash-2019-06-12_14.38.09-client.txt)
[crash-2019-06-12_14.50.09-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/3283331/crash-2019-06-12_14.50.09-client.txt)
[crash-2019-06-12_10.21.27-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/3283332/crash-2019-06-12_10.21.27-client.txt)
[crash-2019-06-12_10.31.49-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/3283333/crash-2019-06-12_10.31.49-client.txt)

**Comment by Zevatronic** [comment]
https://i.imgur.com/82RRdYd.png

**Comment by Zevatronic** [comment]
it has been happening before I put the packs in

**Comment by sk2048** [comment]
This seems to be an issue with the amount of VRAM you have available - check you haven't got other applications open that would be using your GPU, and consider changing settings in Windows such that it's set up for performance - lowering its load on your GPU.
