### ISSUE TITLE
pumpjack divides by 0 + Faulty Core Sample Drill 

### ISSUE THREAD

**Issue by SteamDoge9000** [DarkPacks/SevTech-Ages#3810]
## Bug Report
whenever the pumpjack forms the game crashes and crashed upon loading of the world
while on this note the Core drill sample is failing to provide samples of materials that should be containing Reservoirs along with the no oil samples of ant kind being found.
## Expected Behaviour
When assembling a Pumpjack the game went into a crash state

hears an Additional bug that was found: when using the core drill, sometimes no core samples are given after a successful drilling with over sufficient power
when it does give samples there usual empty with no fluid and ore

## Possible Solution
for the core sample issue, add a Reservoir for galacticraft crude oil or revert to using the immersive petroleum crude oil that was removed 

## Steps to Reproduce (for bugs)

1. use the core drill to find a chunk where no sample is given despite a fully powered survey (this is explains the second bug with the lack of Reservoirs  and samples) (you may need to do this multiple times)
2. when you find a chuck where no sample is given despite the drill having enough power, assemble a pumpjack and complete the construction with a hammer

## Logs
Please note that the atempting to ceate a document on Hastebin of the log have met with it exceeding the maximum length that was allowed, resulting in me having to upload the txt document. Sorry for any inconvenience 
 

[latest.log](https://github.com/DarkPacks/SevTech-Ages/files/3312120/latest.log)

## Client Information

* Modpack Version: 3.1.1
* Java Version: defult version used for Twitch [ Java 1.8.0.51 (64bit)]
* Launcher Used: Twitch (Stranded Minecraft forge version as impimented in modpack [Version 14.23.5.2815]
* Memory Allocated: 12288 MB
* Server/LAN/Single Player: Singleplayer with LAN active
* Optifine Installed: No
* Shaders Enabled: Not as far as im aware of

## World Information

* Modpack Version world created in: 3.1.1

* Additional Content Installed:
please refer to this image for these are the addional mods that were added ouside the modpack install.
![image](https://user-images.githubusercontent.com/38770780/59880814-fb6d1000-937b-11e9-8c05-ca1202c9a44e.png)

**Comment by sk2048** [comment]
Unless you can recreate this issue without additional mods installed, we cannot provide support for this issue.

**Comment by SteamDoge9000** [comment]
ok ill atempt to recreate it without mods
ill just need some time
