### ISSUE TITLE
Dye mismatch/bug

### ISSUE THREAD

**Issue by SillyGoofball** [DarkPacks/SevTech-Ages#3814]
## Bug Report

Combining dye powder gives vanilla dye

## Expected Behaviour

Should give dye powder

## Possible Solution

I noticed the vanilla dyes were removed from oredictionary but they still show up and are unfamiliar items and are in stage disabled.

## Steps to Reproduce (for bugs)

1. Use blue and green dye powder in any crafting grid
2. Produces cyan dye

## Logs

* Client/Server Log: https://pastebin.com/UXbbucZb

## Client Information

* Modpack Version: 3.1.1
* Java Version: 1.12.2
* Launcher Used: ATLauncher
* Memory Allocated: 7 GB
* Server/LAN/Single Player: SP
* Optifine Installed: Yes
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

**Comment by sk2048** [comment]
<img width="448" alt="Screenshot 2019-06-22 at 09 05 26" src="https://user-images.githubusercontent.com/23245543/59961225-e227a900-94cc-11e9-8f9f-a72823cc92db.png">

This is not the case for me, perhaps you have a broken install. Could you provide a copy of crafttweaker.log - it's a large file so https://gist.github.com is probably the best way to send it.

**Comment by SillyGoofball** [comment]
Here's the log: https://gist.github.com/SillyGoofball/1a6ba6b04cc436decb3bfdb1a6dc3c19

**Comment by sk2048** [comment]
Your update from 3.0.8 to 3.1.1 has gone badly. You seem to have both the scripts from 3.0.8 and the scripts from 3.1.1 trying to load simultaneously. They are trying to do some of the same things and are conflicting with each other. Move your world over to a fresh install of 3.1.1 and your issues should go away.
