### ISSUE TITLE
Please help... I can't join in my world because it crash!

### ISSUE THREAD

**Issue by TheLuke04** [DarkPacks/SevTech-Ages#3816]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:[crash-2019-06-24_15.35.52-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/3321155/crash-2019-06-24_15.35.52-server.txt)

## Client Information

* Modpack Version: 1.12.2
* Java Version: Idk
* Launcher Used: Twitch
* Memory Allocated: 6 GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in:1.12.2

* Additional Content Installed: Nothing

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by TheLuke04** [comment]
[crash-2019-06-24_15.35.52-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/3321134/crash-2019-06-24_15.35.52-server.txt)

This is crash report

**Comment by sk2048** [comment]
This is a known issue in v3.0.8 of the pack caused by placing multiple of certain redstone components in a single block space. These are not saved correctly, and when next the game tries to load it it crashes.

You should update your game to version 3.1.1, the world should load correctly.

**Comment by TheLuke04** [comment]
thanks
