### ISSUE TITLE
Astral Sorcery Discidia Ritual not damaging Carminite Ghastlings.

### ISSUE THREAD

**Issue by JosephHelland** [DarkPacks/SevTech-Ages#3817]
Version: 3.1.1
Astral Sorcery ritual Discidia (damages hostile mobs) does not damage Carminite Ghastlings. Im experiencing this issue in the overworld, have not tried duplicating in Twilight Forest.

**Comment by sk2048** [comment]
This appears to be a bug with Astral Sorcery and their method of determining whether an Entity is hostile. Presently, no ghast variant is considered hostile.

I have submitted a report to them here HellFirePvP/AstralSorcery#1141

**Comment by JosephHelland** [comment]
@sk2048 This is weird, as I have used the astral discidia ritual in previous versions of Sevtech and it worked then. (8 months ago I believe was my prior play through)

**Comment by sk2048** [comment]
Specifically on ghasts?
