### ISSUE TITLE
Refined Storage Mystical Agriculture invalid patterns

### ISSUE THREAD

**Issue by Valeix** [DarkPacks/SevTech-Ages#3818]
## Bug Report

The following recipes in a refined storage pattern grid create a 'invalid pattern' when playing on a server. Single player is not affected.
  Aluminum Essence -> Aluminium Ingot
  Copper Essence -> Copper Ingot
  Tin Essence -> Tin Ingot
  Bronze Essence -> Bronze Ingot
  Silver Essence -> Silver Ingot
  Lead Essence -> Lead Ingot
  Steel Essence -> Steel Ingot
  Nickel Essence -> Nickle Ingot
  Constantan Essence -> Constantan Ingot
  Electrum Essence -> Electrum Ingot
  Titanium Essence -> Titanium Ingot
  Uranium Essence -> Uranium Ingot
  Platinum Essence -> Platinum Ingot
  Aluminum Brass Essence -> Aluminum Brass Ingot
  Knightslime Essence -> Knightslime Ingot
  Ardite Essence -> Ardite Ingot
  Cobalt Essence -> Cobalt Ingot
  Manyullyn Essence -> Manyullyn Ingot
  Osminum Essence -> Osmium Ingot
  Fiery Essence -> Fiery Ingot
  Meteoric Iron Essence -> Meteoric Iron Ingot
  Compressed Iron Essence -> Compressed Iron Ingot
  Quartz Enriched Iron Essence -> Quartz Enriched Iron Ingot 

There are a few of the essence -> ingot recipes that work on a server such as the refined obsidian
## Expected Behaviour

In the refined storage pattern grid with processing/oredict unchecked, placing 8 essences in the arrangement or importing the recipe from JEI using the + symbol shows that it is indeed the correct recipe. But when pushing the 'create' button with a blank or used pattern loaded nets a invalid pattern.
## Possible Solution

None
## Steps to Reproduce (for bugs)

1. Open the refined storage pattern grid block
2. Make sure Processing/Oredict are unchecked
3. Place 8 cobalt essence from mystical agriculture in a circle in the crafting grid area. 3 cobalt ingots will appear in the result area.
4. Place a refined storage Pattern in the pattern slot (above the arrow button pointing down)
5. Click the create button
6. Pattern returns as Invalid pattern

## Logs

* Client/Server Log: [Client](https://gist.github.com/Valeix/9b18483752f3df5a30a2ca0a21ab6e9d)
 [Server](https://gist.github.com/Valeix/b5734aad8ccc54dacb75ec40d042cdae)

## Client Information

* Modpack Version: 3.1.1
* Java Version: 1.8.0.51 (64 Bit)
* Launcher Used: Twitch
* Memory Allocated: 8192 MB
* Server/LAN/Single Player: Server
* Optifine Installed: False
* Shaders Enabled: False

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: mtqfix 1.12.2

## Server Information
* Java Version: 1.8.0.221
* Operating System: Windows 10
* Hoster/Hosting Solution: Myself

![Annotation 2019-06-26 182347](https://user-images.githubusercontent.com/52117232/60221501-8ef08600-983f-11e9-9ec4-770513553ca8.png)

![Annotation 2019-06-26 182239](https://user-images.githubusercontent.com/52117232/60221464-69637c80-983f-11e9-8e43-7e7cfb031e11.png)

**Comment by sk2048** [comment]
Note: worse with AE2

![Screenshot 2019-07-09 at 17 19 04](https://user-images.githubusercontent.com/23245543/60905958-0bd32500-a26e-11e9-9492-8252a59b878a.png)

In both cases, the patterns will work if placed in the correct machines.
