### ISSUE TITLE
Server Crash Upon Player Joining

### ISSUE THREAD

**Issue by ArcMester** [DarkPacks/SevTech-Ages#3822]
## Bug Report
 Server launches just fine when a player tries to connect it seems to shut down

## Expected Behaviour
 Should connect and be able to start to play
[crash-2019-06-27_23.43.36-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/3337896/crash-2019-06-27_23.43.36-server.txt)

## Steps to Reproduce (for bugs)

1. launch server
2. try to connect to server

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.11
* Java Version:
* Launcher Used: ATL
* Memory Allocated: 4GB
* Server/LAN/Single Player: Server
* Optifine Installed: Yes
* Shaders Enabled: Yes

## World Information

* Modpack Version world created in: 

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
Your server is unable to read in the Overloaded mod's config. Have you made changes to this that may make it invalid? If so, set it back to what it was.

If not, it may have been corrupted. I would suggest rebuilding your server following the instructions in UPDATE.txt distributed with the official server files from Curseforge to ensure nothing else is affected. This will keep your world intact.

**Comment by ArcMester** [comment]
I did start a new one the world did not matter seeing how it is a new server and no one has played on it yet.  The only setting i had changed were the RAM values within the launch options.  Now I am getting the following crash report. I accepted the EULA and am trying to launch it again as I am typing this.  This is a fantastic mod pack and i really want to play it with friends.  Thank you for the help.
[crash-2019-06-29_17.02.39-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/3342402/crash-2019-06-29_17.02.39-server.txt)

**Comment by sk2048** [comment]
I can't really tell what's going on here; it could be a read issue - check you haven't got cloud syncing setup on the folder containing your server instance.

The Discord tends to have friendly people on that can help, and faster than I have time to as well.
