### ISSUE TITLE
Crashing Upon Startup but only after attempting to connect to my own Hamatchi Server

### ISSUE THREAD

**Issue by Shadeflame3** [DarkPacks/SevTech-Ages#3823]
## Bug Report
I am unable to play on my Hamatchi Hosted SevTech ages Server. It produces an error stating "Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)" when I attempt to join it, not letting me connect to the world. If I close out and restart the modpack, when it nears the end of loading (6/7 or 7/7), it crashes entirely, giving me the error message above.

I have a friend who is able to connect to my server, and has played in the world for a bit, and I am able to connect to a public server just fine without any issue. The only modified files are the EULA and settings to turn pvp off on the server, no other files have been touched by me.

## Expected Behaviour
I expect to be able to join my server being hosted on my machine, and then be able to start the modpack up again after closing it out.

## Possible Solution
I haven't a clue.

## Steps to Reproduce (for bugs)

Starting from a fresh install of SevTech Ages client
1. Start Hamachi and allow it to connect.
2. Start the server and my client, waiting for both to complete.
3. Attempt to connect to my server using "localhost", other people on server not needed.
4. Get "Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)" on screen with the only option to cancel.
5. Close and restart SevTech Ages client (keeping the server up or closing it to restart).
6. SevTech Ages client crashes somewhere after stage 6/7 has gone underway for a time.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/xWHgcd1c

## Client Information

* Modpack Version: 3.0.8
* Java Version: 9.0.1.0 (64 Bit) (had tried with java 8, unsure what exact build)
* Launcher Used: Twitch
* Memory Allocated: 5 GB
* Server/LAN/Single Player: Single Player/Menu
* Optifine Installed: Unknown, whatever is default with the pack
* Shaders Enabled: Unknown, whatever is default with the pack

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None

## Additional Notes
I have absolutely no idea what I am doing that my friend has not. I have tried several different settings available to me in the game's client as well as twitch launcher.

Any help is much appreciated!

**Comment by sk2048** [comment]
The issue here is keybindings. LWJGL (on which Minecraft is built) has a bug where if you bind certain non-standard keys it will crash when something tries to detect if that key has been pressed.

These include additional mouse buttons.

It looks like you've bound a key related to backpacks to one such key. Try changing this and any other bindings that may be bound to non-standard keys. If that doesn't work, delete options.txt in your client instance folder to reset to default.

**Comment by Shadeflame3** [comment]
Thank you sk2048, the key bindings was exactly the issue!

I ended up configuring my controls when setting the server up, but nothing explicitly related to backpacks, so far as I could tell. I had bound my sprint and sneak keys to both of my thumb buttons and excavate to middle click, binding pick block instead to "-" on the numpad.

Hope this helps any future issues someone may come across!

**Comment by sk2048** [comment]
Ah, backpacks was listening for the sneak key being pressed to decide whether to show an extended tooltip! Sorry for the red herring, but glad you figured out which keys were at fault.
