### ISSUE TITLE
Crash with Maze Map in Twilight Forest (Ticking Player)

### ISSUE THREAD

**Issue by iimurpyh** [DarkPacks/SevTech-Ages#3828]
## Bug Report
Opening a Maze Map in the second Twilight Forest labyrinth has caused my game to crash.
Having the map in inventory and loading the world also causes a crash.
Deleting the map with an NBT editor and then making a new one causes the same issues.
I've asked elsewhere, and it seems other people have had similar crashes after opening a maze map.

## Expected Behaviour
Instead of the map loading in properly, the game crashes.
(Don't really know what else I'm supposed to put here :P)
## Possible Solution
Dunno.
This may be an issue with Twilight Forest and _not_ SevTech. If that turns out to be the case I'll contact them.

## Steps to Reproduce (for bugs)
I can't reproduce the bug in another world.
In the world that the crash occurs on, it happens consistently whenever a maze map is used on the labyrinth that I am in.

## Logs
Client/Server Log: https://paste.ubuntu.com/p/RtdgqsKfDs/
Crash Log: https://paste.ubuntu.com/p/6yDFQCzfVj/
(Logs after joining into the world with a corrupted map selected on hotbar. Causes immediate crash on world load.)

## Client Information
* Modpack Version: 3.1.1
* Java Version: 1.8.0.51 (64bit)
* Launcher Used: Twitch/Curse
* Memory Allocated: 12288 MB
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: Around 3.0.7 - all I remember is that it was created before the bronze / copper recipe issue was fixed. Twilight Forest was generated in the latest version.

* Additional Content Installed: None

**Comment by iimurpyh** [comment]
Update: This crash was the result of a [totemic issue](https://github.com/TeamTotemic/Totemic/issues/104) which has been fixed. Thus, updating the version of Totemic that SevTech uses would fix the issue.
Thanks to Reddit user u/Sheyinkage for finding this out :)

**Comment by sk2048** [comment]
Totemic has been updated to latest release in development environment already. Closing as fix will be in next release.
