### ISSUE TITLE
Astral Sorcery "Spatial Manipulation" Dupe crops

### ISSUE THREAD

**Issue by irecinius** [DarkPacks/SevTech-Ages#3829]
Sevtech Version: 3.1.1
Astral Sorcery 1.10.11

Upon unlocking Spatial Manipulation Perk, from Astral Sorcery, with a empty hand, right clicking a Vanilla crop (wheat, potato, carrot, beets) the produce and seeds are just added to your inventory, and the crop doesn't break, giving you infinite value

Side note the perk also affect Tinker's Scythe, it don't replant the seeds after using it to harvest.
Harvest works as intended.

Reprodution:
Unlocked Perks Via attuning to VICIO star, and went straight to "spatial manipulation" without getting anything else major.
Right click any grown crop.
Reproduced on a test world.

**Comment by sk2048** [comment]
For reference: TehNut/Harvest#18
