### ISSUE TITLE
Install Batch Folder Not Functioning,

### ISSUE THREAD

**Issue by Tertell** [DarkPacks/SevTech-Ages#3830]
## Bug Report
So, my computer got wiped during maintenance, and i was just re-downloading applications, and modpacks, I doubt there is anything on the computer that could be interfering with the download. I have downloaded the pack, and wanted to try setting up a server, i downloaded the server pack through the twitch launcher, copied it to a new folder and attempted to run the install batch folder. A window opened for a split second, but closed before any process was carried out and nothing changed in the server folder. I attempted to skip the step, but nothing further worked. - Not sure if this fts in bugs, as it isn't a problem with the modpack itself, but i can find no other source of instructions that are up to date with the switch to the twitch launcher.

## Expected Behaviour
Instead of the forge files being installed, preparing for the server launch, the window closes itself seconds after opening, and no process is carried out.

## Steps to Reproduce (for bugs)

1.Download modpack
2.download server file
3. Copy server files to new folder
4.attempt to run Install Batch file

## Client Information

* Modpack Version: 1.12.2
* Java Version: 8
* Launcher Used: Twitch
* Memory Allocated: 3000MB (but not relevant to question)
* Server/LAN/Single Player: Attempt to launch serber
* Optifine Installed: none
* Shaders Enabled: none

## Server Information
* Java Version: 8 
* Operating System: Windows 10
* Hoster/Hosting Solution: home PC
* Sponge (Non-Vanilla Forge) Server: (?) unknown

**Comment by sk2048** [comment]
The batch scripts are setup to use the server version of the JRE, which is more heavily optimised. You should download a version of Java with the server component. This component is included with the JDK which can be found [here](https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html). Download Java SE Development Kit 8u211 for Windows x64 (jdk-8u211-windows-x64.exe) and install it. If you need further help with this issue you should ask for it on Discord.
