### ISSUE TITLE
i cant age up from age 3 cuts it wont let me do the waterwheel achivment 

### ISSUE THREAD

**Issue by BFXGamer** [DarkPacks/SevTech-Ages#3831]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
The waterwheel advancement isn't even required to get to age 4. And without more information I can't work out why you're not getting the advancement. It triggers just fine for me on obtaining an Immersive Engineering Water Wheel.

**Comment by sk2048** [comment]
Closing due to lack of information.
