### ISSUE TITLE
Server crashes on startup first time

### ISSUE THREAD

**Issue by fridgemagnetyt** [DarkPacks/SevTech-Ages#3834]
## Bug Report

Server keeps crashing on startup. Sometime todo with betterwithmods as i read it.
## Steps to Reproduce (for bugs)

1. Run serverstart.bat
2. Crashes

## Logs

Client/Server Log: https://pastebin.com/MA95XeVC
Crash Log: https://pastebin.com/43y2q5rY

## Client Information

Modpack Version: 3.0.8
Java Version: Java 8 211 64bit. Also JDK 8.0.212.04-openj9
Launcher Used: Twitch
Memory Allocated: 8000
Server/LAN/Single Player: Server
Optifine Installed: No
Shaders Enabled: No

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
Java Version: Java 8 211 64bit. Also JDK 8.0.212.04-openj9
Operating System: Windows 10 64 bit
Hoster/Hosting Solution: Hosting on same desktop
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
OpenJ9 is not supported at this time. Use the HotSpot VM from either OpenJDK or Oracle.
