### ISSUE TITLE
Inferium Essence not craftable

### ISSUE THREAD

**Issue by BlackFranky** [DarkPacks/SevTech-Ages#3838]
## Bug Report
The recipe for Inferium Essence is not working.

## Expected Behaviour
The Atomic Reconstructor dousn't interact with the Saturn Slime Ore.

## Steps to Reproduce (for bugs)
1. Get Saturn Slime Ore
2. Drop it infront of an Atomic Reconstructor
3. Start the Atomic Reconstructor Laser

## Client Information
* Modpack Version: 3.1.1
* Launcher Used: Twitch
* Memory Allocated: 8 GiB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.8 (3 Weeks ago)

## Server Information
* Hoster/Hosting Solution: Nitrado

**Comment by GearsOfClockwork** [comment]
Seems to work just fine for me in 3.1.2. Have you tried updating?

**Comment by sk2048** [comment]
Also find this to be working in 3.1.2

**Comment by sk2048** [comment]
Worth noting that the energy buffer of the atomic reconstructor must be more than two thirds full for the transformation to occur
