### ISSUE TITLE
Server Setup

### ISSUE THREAD

**Issue by calmeep** [DarkPacks/SevTech-Ages#3839]
## Bug Report
 As soon as I click on the ServerStart Bat file it opens for a millisecond and closes. SO i cant start the server or run it.

## Expected Behaviour
 I think it should stay open so i can access the console and setup the server

## Possible Solution
 Give a solution or fix a startup file causing it.

## Steps to Reproduce (for bugs)

1. Opens Server start 
2. It closes serverstart right after

## Logs

* Client/Server Log: I believe this may have something to do with it
https://pastebin.com/embed_js/3gbNQHtP
and server logs arent made because of the crash
* Crash Log:

## Client Information

* Modpack Version: 
* Java Version: 
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version: 8.0.2110.12
* Operating System: Windows 10
* Hoster/Hosting Solution:I havent found one
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
You likely aren’t using a JRE that contains the server component. Installing the JDK is the easiest way to sort this issue.

Your log is unrelated. It suggests your client can’t read from the forge jar. Either it’s corrupted or you’re running the game from a directory that’s backed up by a cloud service provider that is locking access to files while it does its thing.
