### ISSUE TITLE
Client Returns to Title Screen

### ISSUE THREAD

**Issue by ijangoetbeard** [DarkPacks/SevTech-Ages#3842]
## Symptom 
* Clicking "Close" on getting started message when logging into SevTech server returns client to  client title screen.

## Steps to Reproduce 

* Video 
https://youtu.be/EE4PGKXgCLU?t=297 

## Logs
* Client Log: [https://gist.github.com/ijangoetbeard/56a291add9a84469b4b981a8af4872b5](url)

* Server Log: [https://gist.github.com/ijangoetbeard/ffe1e2b28d1cb2837415b9fffd1c826e](url)

* Crash Log (Only in Single Player. May or may not be related to this inquiry ticket. Might point to underlying issues for this inquiry ticket.): [https://gist.github.com/ijangoetbeard/e53acf43cabda7ef3b74a31a6c6d5800](url)

## Client Information
* Environment: Title screen and Connect to Server screen
* Modpack Version: 3.0.8
* Java Version: 1.8.0.77 (64 Bit)
* Launcher Used: Twitch
* Memory Allocated: 4096 MB
* Server/LAN/Single Player: Server
* Optifine Installed: False
* Shaders Enabled: False

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed: False

## Server Information
* Java Version: 8.0.1610.12 (64 Bit)
* Operating System: Windows 10
* Hoster/Hosting Solution: Personal hosting computer with port forwarding
* Sponge (Non-Vanilla Forge) Server: n/a

**Comment by sk2048** [comment]
You seem to be missing the scala standard library. Try reinstalling the pack.

Closing as not an issue with the pack but an issue with the launcher. Use Discord for support with this issue.
