### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by cdfa** [DarkPacks/SevTech-Ages#3843]
## Bug Report

Game crashes with fresh install from Twitch

## Logs

* Client/Server Log: N/A?
* Crash Log: https://pastebin.com/5uAVEpmu

## Client Information

* Modpack Version: 3.1.1
* Java Version: 1.8.0_211-b12
* Launcher Used: TLauncher 1.98.13
* Memory Allocated: 7168MB
* Server/LAN/Single Player: N/A
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: N/A

* Additional Content Installed: N/A

**Comment by sk2048** [comment]
Forge is unable to launch the game, potentially due to duplicates of BnBGamingCore. Have you recently updated and has this resulted in there being multiple instances of this or other mods in your mod folder?

**Comment by cdfa** [comment]
As a matter of fact yes, there is a `0.8.0` and a `0.10.0`. Looking further is seems there's also a duplicate BNBGamingLib `jar`: `11.2` and `17.5`. Very strange that Twitch created duplicate `jar`s like that. I'll try remove the older ones and see if that works.

**Comment by cdfa** [comment]
Ow wait, I know how this happened. I think I copied an updated instance over an old one. My bad! Sorry to bother you
