### ISSUE TITLE
Clay Kiln Conversion to Fired variant

### ISSUE THREAD

**Issue by sam-kirby** [DarkPacks/SevTech-Ages#3846]
## Bug Report

Clay Kiln will only convert to fired variant if there is something inside it (does not have to be a valid recipe)

## Expected Behaviour

Clay kiln converts when above fire regardless of whether there is something inside

## Possible Solution

Fix Primal Tech.

## Steps to Reproduce (for bugs)

1. Place Clay Kiln above fire
2. Wait forever
3. Place something inside. Converts in 10 seconds.

## Logs

N/A

## Client Information

* Modpack Version: 3.1.2
* Java Version: 1.8.0_202
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Any
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.1.2

* Additional Content Installed: None

**Comment by vadis365** [comment]
Should be fixed now as of latest release of PT.

**Comment by lghtngfan** [comment]
I've got the latest hotfix patch running on my server, and I had to use the work-around to get the kiln to fire.

**Comment by sam-kirby** [comment]
Whilst we have fixed this in development versions, we have not yet released a version with the fix in.
