### ISSUE TITLE
[3.1.2] Auto Cauldron structure requires "unfamiliar item"

### ISSUE THREAD

**Issue by Stifling-Bossness** [DarkPacks/SevTech-Ages#3851]
## Bug Report
The new auto cauldron structure requires an unfamiliar item, even though I'm in the creative age.
![](https://i.imgur.com/PTIlGXF.png)
It cycles through requiring low-grade charcoal or netherrack, but it doesn't cycle the unfamiliar item.

## Steps to Reproduce
1. Craft auto cauldron blueprint
2. Investigate blocks required

## Logs
* Client/Server Log: https://gist.github.com/Stifling-Bossness/df99caa15691bd306aacbcdb3c6588f7

## Client Information
* Modpack Version: 3.1.2
* Java Version: 8 221 64-bit
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: Yes, E4
* Shaders Enabled: Yes, ProjectLUMA

## World Information
* Modpack Version world created in: 3.0.6
* Additional Content Installed: 
Akashic Tome 1.2-12, LagGoggles FAT-4.6, MCMultiPart 2.5.3, Morph-O-Tool 1.2-21,
Phosphor 0.2.5, VanillaFix 1.0.10-99

**Comment by G1R-Productions** [comment]
What was the solution to this? I am on the latest beta version and have the same issue.
