### ISSUE TITLE
Bugs screen , achievements, striped screen

### ISSUE THREAD

**Issue by nikeron2517** [DarkPacks/SevTech-Ages#3852]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
We can't do anything with no information.

**Comment by nikeron2517** [comment]
Hello, I watch the bugs in the assembly after two entrances to the game.  then the character moves very quickly and especially the skin in the inventory, hands waving constantly.  same with animals.  there is a crack and optifeyn.  And the yellow and black stripes flicker constantly, and I move very strangely, press the key once it takes me over 1000 blocks from the place where I was.  Please help solve the problem. I would very much like to continue to play. I came to the second stage and that's it.  Right now, I can not get to the first one. I reinstalled many times in the same time.

**Comment by nikeron2517** [comment]
Minecraft download on: curse and have optifine hd u d3.
Java: 180 ..

**Comment by nikeron2517** [comment]
Can you unblock?

**Comment by sk2048** [comment]
There are two things that can cause that.

One is the betterFPS algorithm. Change it to `Rivens Half`. If it is already that, then use `Vanilla`.

Two is being at extreme coordinates, if changing the betterFPS algorithm doesn’t fix anything, `/tp 0 0 0`

If you need further support, contact us on discord. https://discord.gg/darkosto

**Comment by nikeron2517** [comment]
That i need to change algorithm on half rivens, and that will be normal?
And where a can find achievements file?
My achievements are lost.

**Comment by nikeron2517** [comment]
And what with coordinates?

вт, 23 июл. 2019 г., 19:07 Nikeron 2517 <nikeron2002@gmail.com>:

> That i need to change algorithm on half rivens, and that will be normal?
> And where a can find achievements file?
> My achievements are lost.
>

**Comment by nikeron2517** [comment]
Its not optifine?


вт, 23 июл. 2019 г., 19:08 Nikeron 2517 <nikeron2002@gmail.com>:

> And what with coordinates?
>
> вт, 23 июл. 2019 г., 19:07 Nikeron 2517 <nikeron2002@gmail.com>:
>
>> That i need to change algorithm on half rivens, and that will be normal?
>> And where a can find achievements file?
>> My achievements are lost.
>>
>

**Comment by nikeron2517** [comment]
When a relaunch Minecraft , than it have bugs , and i will reinstall it
