### ISSUE TITLE
OreMatic 5000 Mk2 stops working mid-operation and gives no output

### ISSUE THREAD

**Issue by kyazuki** [DarkPacks/SevTech-Ages#3855]
## Bug Report
OreMatic 5000 Mk2 is set up correctly and the multiblock is detected by the controller. The four fluid inputs are fed with water, oxygen gas, lubricant, and hydrogen chloride, and the energy input hatch with enough energy.
When a stack of illmenite ore is placed in the item input, one is consumed and the controller shows progress up to a certain percent, and then suddenly stops and reverts to saying "no matching recipe found."
No items are discharged, resulting in the input ore being lost.
After this happens once after the machine is set up or initialized by breaking and replacing a block, the machine no longer accepts and consumes any ores/items.
Also tested with iron cluster as the input and had the same result.

## Expected Behavior
For the OreMatic5000 mk2 to correctly process the inputs.

## Steps to Reproduce (for bugs)
1.Set up the OreMatic5000 Mk2.
2.Input an ingredient and watch the operation suddenly cancel out and the controller say "no matching recipes found".
3.Input more and find out that nothing happens.

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
What version are you having this issue in?

Is this on a server or client?

Please complete the rest of the template.

**Comment by sk2048** [comment]
Tested in 3.1.2 single player. Working without issue.

**Comment by sk2048** [comment]
The only explanation I have is your energy input hatch is insufficient. You can't use a tiny input hatch as it is capped at 128 FE/t, whilst the Orematic T2 uses 300 FE/t. If its buffer empties, the recipe becomes invalid and the current process is discarded.

**Comment by sk2048** [comment]
Further to this, T3 requires 600 FE/t so you must use at least a Reinforced Energy Input Hatch for that machine.

**Comment by kyazuki** [comment]
Thanks for the quick answer! Indeed my setup was using a tiny energy input hatch, and replacing it with the reinforced alternative fixed my issue.
Apologies for not checking thoroughly.
