### ISSUE TITLE
Issue downloading 

### ISSUE THREAD

**Issue by vr3zz** [DarkPacks/SevTech-Ages#3858]
I can't seem to be able to download this mudpack, I have the 1.12.2 version of MC installed and when I click the install button on the twitch app it gives me this error. 

"Object reference not set to an instance of an object" 
it seems to be getting most of the way downloaded and then crashing at the Deleting files section of the install. 

unfortunately I wasn't able to find any information on why this was happening any assistance would be greatly appreciated.

**Comment by sk2048** [comment]
This is a twitch issue that we have no control over. It will be resolved by them eventually. In the meantime, you can download the pack through ATLauncher or MultiMC.
