### ISSUE TITLE
Can't Craft empty Antique Atlas

### ISSUE THREAD

**Issue by Takachance** [DarkPacks/SevTech-Ages#3859]
As the title suggest. I can't make empty Antique Atlas while I play on servers or on single player. I'm on 3.1.2

**Comment by sk2048** [comment]
The crafting recipe works for me. Note the crafting recipe only unlocks in age 1. Prior to this, you must trade for it.

![Screenshot 2019-07-28 at 15 08 17](https://user-images.githubusercontent.com/23245543/62007802-d2455980-b149-11e9-97c4-04eabeae636f.png)

**Comment by Rdf** [comment]
I have a similar bug. Also a problem with crafting charcoal_hopper. Recipes are present in the JEI, by clicking the mouse, ingredients put on the workbench, but the result is not displayed/crafted. Used linux system (maybe it matters). When I take the scripts of earlier versions and change (primaltech.zs):
                                [<tconstruct: firewood: 0>],
                                [<primal_tech: wooden_hopper>]
to
                                [null, null, null],
                                [null, <tconstruct: firewood: 0>, null],
                                [null, <primal_tech: wooden_hopper>, null]
as well as (antiqueatlas.zs):
                                [<minecraft: leather: 0>, <primal: plant_cloth: 0>],
                                [<minecraft: leather: 0>, <primal: plant_cloth: 0>],
                                [<minecraft: leather: 0>, <primal: plant_cloth: 0>]
 to:
                                [<minecraft: leather: 0>, <primal: plant_cloth: 0>, null],
                                [<minecraft: leather: 0>, <primal: plant_cloth: 0>, null],
                                [<minecraft: leather: 0>, <primal: plant_cloth: 0>, null]
everything is fine

**Comment by sk2048** [comment]
The recipe works as described in scripts, JEI displays it incorrectly. See #3863 

To craft a charcoal hopper, put one firewood above a hopper or wooden hopper.

To craft the antique atlas place leather down the left side of the crafting grid, and plant cloth down the centre.

**Comment by sk2048** [comment]
It is not necessary to modify the scripts to craft these items.

**Comment by Rdf** [comment]
> To craft a charcoal hopper, put one firewood above a hopper or wooden hopper.
> 
> To craft the antique atlas place leather down the left side of the crafting grid, and plant cloth down the centre.
>
> It is not necessary to modify the scripts to craft these items.

It works. thanks
