### ISSUE TITLE
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CTM (ctm)

### ISSUE THREAD

**Issue by PopeCheese** [DarkPacks/SevTech-Ages#3860]
## Bug Report
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CTM (ctm)

Unable to access log file currently but I will update the post with them today. This is occuring on a friends PC and he hasn't come online yet. I am hoping I can figure this out before he does so I have a few things to try at that point.

## Expected Behaviour
The game loads.

## Steps to Reproduce (for bugs)
Download Minecraft and Forge 1.12.2. Download server files for SevTech Ages from Twitch (because downloading the client files or doing pretty much anything else on Twitch app never works), copy all mods out of server mod folder and move them into mod folder in %appdata% minecraft folder (also NotEnoughIDs). No previous mods in folder at all, fresh install. Run Launcher. Set to use 8 gigs of RAM in installations. Press Play. Crash when loading CTM.

**** I have followed these exact same steps on my own PC first and it works absolutely flawlessly. I have both a server and my client running, can connect to the server with all mods working. Researching the issue seems to indicate that the CTM files are outdated, or maybe too new, but this is inconsistent with the fact that I am using the same files (even going so far as to transfer my CTM mod to my friend's PC via file transfer to be sure) and it works for me.

## Logs
Unfortunately it is a friends PC and I don't have access to the logs right now. Will upload to this post later if needed once I can get them.

## Client Information

* Modpack Version: 3.0.8 (I believe, at least. Assuming this is the version that downloads with server pack because the "updated" date matches this versions release date in the "versions" tab. I'm not sure where to verify this.)
* Java Version: latest - build 1.8.0_221-b11
* Launcher Used: Minecraft Launcher (choose forge option 1.12.2 - 14.23.4.2707)
* Memory Allocated: 8 gigs
* Server/LAN/Single Player: singleplayer (for now, but will be connecting to a server I have already verified works on my PC)
* Optifine Installed:No
* Shaders Enabled:No

## World Information
SevTech Ages modpack

**Comment by sk2048** [comment]
Why are you adding Not Enough IDs?

**Comment by sk2048** [comment]
Any update on this?

**Comment by sk2048** [comment]
Making modifications to the pack voids support from us. There are too many variables to test to make this feasible for a team of volunteers.

Worth noting though that we use JustEnoughIDs in 3.1.0+, and whilst it is compatible with NEIDs it may result in you having more issues if you update.
