### ISSUE TITLE
Friend unable to connect but I can

### ISSUE THREAD

**Issue by jeffcubed** [DarkPacks/SevTech-Ages#3861]
I recently created a server for Sevtech. Whenever my friend tries to connect to the server, the connection times out. I have tried upping the time until a timeout. I am able to connect on a different device on a different network, though it is the same router. I have done everything you need to do to set up a server but it does not work. Any help would be much appreciated.

**Comment by sk2048** [comment]
I'll prefix this by saying you'll get faster replies if you message the #sevtech-server-support channel on Discord; https://discord.gg/darkosto

However before you do that, here's a couple of things that you may have missed assuming your friend is connecting over the internet, i.e. they're not on the same local network.

1. When your friend connects to you, they connect via your router. You therefore need to give them your router's external IP address. The easiest way to find this is to Google "What is my IP".

2. Your router needs to know how to handle your friend's connection attempt through a setup known as port forwarding. This tells the router that a connection from a stranger to a specific port should be sent on to your server to be dealt with and not ignored as is normally the case. https://portforward.com has guides on how to do this for most routers. Minecraft uses port 25565 over TCP only.

3. Any firewall or security software on your PC needs to know that the Minecraft server, or sometimes more generically Java, is allowed to accept incoming connections.
