### ISSUE TITLE
Really super laggy

### ISSUE THREAD

**Issue by Higuu** [DarkPacks/SevTech-Ages#3862]
## Bug Report

No matter what I do, it's really super nasty laggy.

## Expected Behaviour

I can't even walk without getting hit with a lag spike... That shouldn't happen.

## Possible Solution

I know that allocazting more RAM works, but I cant figure out how to do it? all the vids ive found online for that don't work for some reason.

## Steps to Reproduce (for bugs)

hhh idk tho? it just doesn't work

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0
* Java Version: 1.14
* Launcher Used: ????
* Memory Allocated: not sure, cant find it
* Server/LAN/Single Player:
* Optifine Installed: no, idk how
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0

* Additional Content Installed: none

please help im so confused

**Comment by Higuu** [comment]
like seriously im so darn confused

**Comment by Higuu** [comment]
ok no I didn't fix the problem I just made it a little better. I heard somewhere optifine helped but I don't know how to add it to a modpack? please help hh

**Comment by Streamcyper** [comment]
For support, go to the [Discord](https://discordapp.com/invite/darkosto)

**Comment by Higuu** [comment]
okidoki
