### ISSUE TITLE
Always zoomedin in betweenlands?

### ISSUE THREAD

**Issue by Giordyman** [DarkPacks/SevTech-Ages#3865]
## Bug Report
Playing on friend's server. This issue has happened to only me so far

## Expected Behaviour
Entering the world and playing normally

## Possible Solution
no idea

## Steps to Reproduce (for bugs)
<
1. Enter betweenlands

## Client Information
I made the betweenlands portal, however, once I get in, everything become zoomed in like in the picture, it's not a problem of FOV or Optifine, since I can still zoom with C

* Modpack Version: 3.0.8
* Java Version: Latest
* Launcher Used:TLauncher
* Memory Allocated: 6800M
* Server/LAN/Single Player: Server
* Optifine Installed: Yes
* Shaders Enabled: Yes

## World Information
<Perfectly normal world
* Modpack Version world created in: 3.0?8
* Additional Content Installed: Optifine

## Server Information
* Java Version: Latest
* Operating System: W10
* Hoster/Hosting Solution: None
* Sponge (Non-Vanilla Forge) Server:

**Comment by Giordyman** [comment]
http://it.tinypic.com/r/2nlw7zr/9
This being the image

**Comment by sk2048** [comment]
Please prove it's not Optifine or your shaders by removing it. I've not seen this issue before, and 3.0.8 has been out a long time.

**Comment by TheCyberBrick** [comment]
Probably same as https://github.com/Angry-Pixel/The-Betweenlands/issues/843, an incompatibility with Optifine which was fixed in BL v3.4.10.

**Comment by sk2048** [comment]
Thank you for the information TheCyberBrick, we'll include the updated version in the next release.
