### ISSUE TITLE
Achievement Progression

### ISSUE THREAD

**Issue by Krispeh** [DarkPacks/SevTech-Ages#3867]
So I appear to have encountered a progression issue and quests are no longer completing as I reach them (so far Tomahawk, farming, horse grindstone and strainer: note, I gave myself tomahawk achievement with server commands in the hopes it'd reset and fix the issue but to no avail).

Currently playing on a server I'm hosting for me and a couple of friends and their clients seem to be completing them fine. Any ideas?

Image below has strainer net in my hand, and a strainer setup bottom left.

![image](https://user-images.githubusercontent.com/9793903/62225552-05167880-b3fc-11e9-948c-e7f025e0691e.png)

v3.0.8

**Comment by sk2048** [comment]
This looks like a vanilla minecraft issue where sometimes and for unknown reasons the advancements screen stops updating. Rejoining the game is usually sufficient to resolve this.

These advancements' criteria are all correct.

**Comment by Krispeh** [comment]
Alrighty solved the issue by deleting all the config files for NEI and JEI just as a wild guess and it's solved. I had t ied restarting but that didn't work, seems to be all good now.

**Comment by sk2048** [comment]
Not much we can do based on this. JEI doesn't do anything with regards to advancements, NEI isn't in the current version of the pack but the issue is still present.
