### ISSUE TITLE
3.1.2 Structure generation issue

### ISSUE THREAD

**Issue by BattleFalcon** [DarkPacks/SevTech-Ages#3869]
## Bug Report
Just started (yet another) new world with SevTech with the 3.1.2 beta build. I immediately noticed a floating island (cobblestone shrine on dirt with a normal minecraft chest containing some flowers). I also found a sizeable logger's pile and a ruined building with a normal furnace and workbench.

## Expected Behaviour
In all builds since I started having fun with SevTech more than a year ago, there have been no structure generation beyond basic villages at all, and loot from chests have been nonexistent as well.

## Possible Solution
I'm thinking there's a config setting somewhere that hasn't been flipped correctly. Unfortunately, I am not familiar enough with individual mods to know which one generates these structures. However, the <Recurrent Complex> count lists 187 active structures, as opposed to 15 in the current release version (3.0.8).

## Steps to Reproduce (for bugs)
1. Generate a fresh world in 1.3.2 with the seed 1297936015485260886.
2. There is a dungeon in field of view on the right when spawning in (S-SW). Slightly further away (S-SE) is a log pile.

## Logs
I don't think this is an issue that requires a log, but here's a collection of screenshots (too big to embed): [https://www.dropbox.com/s/yc9ts169dujglu3/SevTech%20structures.zip?dl=0]

## Client Information

* Modpack Version: 1.3.2
* Java Version: 1.8.0_221
* Launcher Used: Twitch JAR
* Memory Allocated: 12288MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: None
* Shaders Enabled: No

## World Information
estimates are OK -->
* Modpack Version world created in: 1.3.2
* Additional Content Installed: None

**Comment by sk2048** [comment]
Recurrent Complex's `structures` folder was not included in the export from Twitch meaning a bunch of the built in structures have become reenabled.

To fix this, you can just copy and paste the structures folder in the root instance directory from a previous version into 3.1.2.

**Comment by justinrusso** [comment]
A hotfix has been released. https://www.curseforge.com/minecraft/modpacks/sevtech-ages/files/2752761

Thank you.
