### ISSUE TITLE
STARLIGHT CRAFTING ALTER TIER 2 RED BAR, even though structure is 100% proper

### ISSUE THREAD

**Issue by XannnyDevito** [DarkPacks/SevTech-Ages#3873]
The alter is 100% created properly in an area with high sun light though i still cannot get this to work. one thread said that the problem is with the modpack after the most recent update. I am on a server with 2 friends and cant progress any further due to this problem. we have tried everything the internet has to offer and are only left to report it [here.[](url)](url)
![2019-08-03_21 48 06](https://user-images.githubusercontent.com/53651196/62411598-b144a300-b638-11e9-9067-75002905cb89.png)
![2019-08-03_21 48 15](https://user-images.githubusercontent.com/53651196/62411599-b570c080-b638-11e9-8c93-8f5e81c96b9c.png)
![2019-08-03_21 48 19](https://user-images.githubusercontent.com/53651196/62411600-b73a8400-b638-11e9-80ed-caf323db1ec9.png)
![2019-08-03_21 48 28](https://user-images.githubusercontent.com/53651196/62411602-b99cde00-b638-11e9-8d3d-e67800a54a52.png)

**Comment by sk2048** [comment]
Were you the member of the server who crafted this and the previous tier of altar? Astral has a built in knowledge system that prevents you using an altar without you having crafted it and all preceding tiers. You can share knowledge using an astral sorcery item though I can’t remember the specifics right at this minute.

If you create issues in future please fill out the template.

**Comment by Yarik124421** [comment]
I have exactly the same problem. We play with a friend on the server. I was the one crafting the altar.
3.0.8
![image](https://user-images.githubusercontent.com/42224678/62415207-b56bc300-b62e-11e9-9e30-0435625c4324.png)
![image](https://user-images.githubusercontent.com/42224678/62415212-bd2b6780-b62e-11e9-9cc2-89078be6c98e.png)

**Comment by Yarik124421** [comment]
I found solution for me
![image](https://user-images.githubusercontent.com/42224678/62415384-97ec2880-b631-11e9-94d3-967e38e25acc.png)
![image](https://user-images.githubusercontent.com/42224678/62415386-9ae71900-b631-11e9-9b53-908f8fc11698.png)
i use not the one marble (chisel || astral sorcery) may be you have similar problem

**Comment by sk2048** [comment]
@Yarik124421 The structure in question involves no ordinary marble blocks, so this is unlikely to be the issue. Thank you for sharing your solution anyway, it is a fairly common mistake.

**Comment by sam-kirby** [comment]
Closing due to lack of updates.
