### ISSUE TITLE
Won't let me start a world

### ISSUE THREAD

**Issue by gdw1999** [DarkPacks/SevTech-Ages#3878]
When I create a single player world and launch it says "connection lost internal exception: java.nio.channels.ClosedChannelException" and puts me in the multiplayer server list.

I am playing 3.0.8 through the twitch app. idk what other information you need but just let me know.

**Comment by sk2048** [comment]
ClosedChannelException is sometimes related to the read timeout, check this:

https://github.com/DarkPacks/SevTech-Ages/wiki/Read-Timeout-Exception
