### ISSUE TITLE
Abyssalcraft Altar

### ISSUE THREAD

**Issue by XDeadImmortalX** [DarkPacks/SevTech-Ages#3879]
I cannot continue with the advancements because the abyssal craft altar isnt working to make my beneath portal. I have everything in place for the ritual, but it isnt doing it

**Comment by Zarvera** [comment]
So you've assembled the actual altar and recepticles themselves, put stuff in as shown, shift-right-clicked central altar with Necronomicon, right?
Does Necronomicon has enough PEnergy in itself to activate crafting?

**Comment by XDeadImmortalX** [comment]
Yes, my necronomicon have over 4000 PE, the only thing i can thing of is my demonic will doesnt have enough will in it, but I've even tried a stronger will with no success

**Comment by sk2048** [comment]
The amount of will is irrelevant.

Cannot reproduce and template not completed/deleted, despite prompting that we need more information, so this is being closed.

For gameplay help try the discord https://discord.gg/darkosto
