### ISSUE TITLE
Rice flour cannot be made using AA rice in an Industrial Mill.

### ISSUE THREAD

**Issue by tiger8255** [DarkPacks/SevTech-Ages#3880]
## Bug Report
Rice flour cannot be made from the rice from Actually Additions in an Industrial Mill. There is a recipe for rice flour, but it only accepts rice stalks from Better With Mods.

## Expected Behaviour
Rice flour should be able to be made in an Industrial Mill with Actually Additions rice.

## Possible Solution
Add a recipe to turn Actually Additions rice into rice flour.

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_201-b09
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: Unsure; whatever is default.

**Comment by sk2048** [comment]
Changed in future versions.
