### ISSUE TITLE
DeathCompass/Erebus Request

### ISSUE THREAD

**Issue by TeknoRapture** [DarkPacks/SevTech-Ages#3884]
Can you please please please PLEASE add an option to set a burn time for the Death Compass?  It would give them some use other than the intended one, and it's kinda a pain to go out of my way to get rid of the HUNDREDS of death compasses that keep piling up.  I'd say have a default burn time equivalence to paper.

This would be a quick fix that I'm sure plenty of people will love!

A burn time of 0 (not burnable) to any time would really help with the hundreds of death compasses we constantly keep piling up.

Thanks!

**Comment by sk2048** [comment]
They have a use in the late game and you’ll need a lot of them, and they have a recipe that removes their NBT to make them stackable for storage.
