### ISSUE TITLE
Sevtech 3.1.2 Server Crash

### ISSUE THREAD

**Issue by TheMaddog91** [DarkPacks/SevTech-Ages#3893]
Running the latest 3.1.2 Sevtech server on a CentOS7 operating system. 

6 players were online when this crash occurred.

Intel Xeon E3-1245v2
4c / 8t
3.4GHz
32GB DDR3 1333 MHz

https://pastebin.com/Z6qRty9G

**Comment by sk2048** [comment]
This crash report just says the server took more than 60 seconds to tick, and at the time it crashed it was trying  to generate a chunk. This does not mean it spent all of the 60 seconds on this. Without more context, or a method through which this can be reproduced, I can’t do much but put this down to chance.
