### ISSUE TITLE
Sevtech crashes in menus

### ISSUE THREAD

**Issue by DuckConsumer1734** [DarkPacks/SevTech-Ages#3894]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by DuckConsumer1734** [comment]
https://pastebin.com/dMgcbbwT <-- crash report

**Comment by sk2048** [comment]
Install the correct version of Optifine.
