### ISSUE TITLE
Obtaining vanilla iron ore,gold ore,redstone ore and coal ore in age 2 in the twilight forest generated cave-structure

### ISSUE THREAD

**Issue by Razvan5** [DarkPacks/SevTech-Ages#3896]
#Bug Report
This structure in Twilight Forest Generates Iron Ore, Gold Ore, Redstone Ore and Coal Ore
## Expected Behaviour
I believe that this ores would be restricted in some way, but it can compensate for the difficulty of obtaining starmetal ingots?
## Possible Solution
Let the structure generate,it might not be that OP, or replace the iron,gold ore,redstone ore with geolosys alternative.

## Steps to Reproduce (for bugs)
1. Generate a world. Enter Age 2.
2. Enter the Twilight Forest.
3. Search for the twilight Troll Caves or Forest Caves (i don't know which one it is).

## Logs
* Client/Server Log:https://gist.github.com/Razvan5/85c84a7991b95d701292abb1be12bfa2
* Crash Log:-

## Client Information
* Modpack Version:3.1.1
* Java Version:8 update 221
* Launcher Used: AtLauncher 
* Memory Allocated: 4GB
* Single Player.
* Optifine Installed:no
* Shaders Enabled:no

## World Information
*Seed:17813796291219128
*Twilight Cave Location: x:53 y:- z:551
* Modpack Version world created in:3.1.1

![2019-08-21_13 53 09](https://user-images.githubusercontent.com/48687252/63427602-2e845c00-c41e-11e9-9af2-bb32569eb089.png)

**Comment by sk2048** [comment]
This is not a bug, the Twilight Forest generates both vanilla ores and geolosys ores on purpose and if we wanted to stop this we could. This is a particularly good place to get iron ore without requiring silk touch to be used for starlight transmutation for more star metal.
