### ISSUE TITLE
Crash on Creating/Loading World ; java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by Schneiderism** [DarkPacks/SevTech-Ages#3901]
## Bug Report
Attempting to create/join a SevTech_V2 preset world with a fresh installation of SevTech: Ages causes the game to crash. Twitch shows the error as `java.lang.ExceptionInInitializerError`. It seems that the issue is potentially being caused by the Antique Atlas mod, as seen on line 29 of the crash report: (`at hunternif.mc.atlas.client.gui.ExportProgressOverlay.draw(ExportProgressOverlay.java:29)`)

## Expected Behaviour
Game shouldn't crash. Should join fine.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Install SevTech: Ages through the Twitch launcher
2. Launch game
3. Try and create new world
4. Game crashes

## Logs

* Client/Server Log: 
* Crash Log: https://pastebin.com/B8Shb12y

## Client Information

* Modpack Version: 3.0.8
* Java Version: v8u221 (build 1.8.0_221-b11)
* Launcher Used: Twitch
* Memory Allocated: 8192MB {16384MB installed}
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: None

## World Information

* Modpack Version world created in: N/A

* Additional Content Installed: N/A

**Comment by sk2048** [comment]
Closing as appears to be an edge case issue in the JVM itself: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8148342

Not much that can be done here.
