### ISSUE TITLE
Tracking Issue: Occasional infinitely recursive streams generation

### ISSUE THREAD

**Issue by sam-kirby** [DarkPacks/SevTech-Ages#3902]
delvr/Streams#74

**Comment by Vagor96** [comment]
The exact problem was unfortunately still not found. Could one of the developers of this modpack possibly join in the discussion in the Streams repo?
The current question is whether perhaps one of the mods used includes Sponge Mixins. And that goes far beyond my knowledge. But any other aolution approach would certainly also be welcome.
