### ISSUE TITLE
Please upgrade Galacticraft to fix space stations + spongeforge

### ISSUE THREAD

**Issue by bluelightning32** [DarkPacks/SevTech-Ages#3909]
Sevtech 3.1.2-hotfix.1 contains GalacticraftCore-1.12.2-4.0.2.211.jar. Please upgrade to GalacticraftCore-1.12.2-4.0.2.235.jar or newer to pick up the fix for this bug:
https://github.com/micdoodle8/Galacticraft/issues/3775

**Comment by sk2048** [comment]
That's not always true, and particularly with mods like Galacticraft which are not hosted on Curseforge it can be useful to know when there's a mod release that fixes an issue players are having.
