### ISSUE TITLE
Steel nuggets?

### ISSUE THREAD

**Issue by LexiTheTT** [DarkPacks/SevTech-Ages#3911]
## Bug Report

When you put a steel ingot in your crafting menu(Either table or inventory) it makes an object called "item.tcomplement.materials.name"

## Expected Behaviour

Nothing should be able to be made this way so I think that when you put a steel ingot here nothing should happen. But instead it makes "nuggets"?

## Possible Solution

Block the recipe.
Maybe make it so you'll need the press and alloy furnace then fix the item image.

## Steps to Reproduce (for bugs)

1. Get a steel ingot and put it in your crafting table/inventory.
2. Look at the horrifying pink block.

## Logs

* Client/Server Log: None
* Crash Log: None
I have an image though.
https://i.imgur.com/U2MFO23.png

## Client Information

* Modpack Version: 3.1.2 Hotfix
* Java Version: 8
* Launcher Used: Twitch
* Memory Allocated: Not relevant but 4gb
* Server/LAN/Single Player: Server
* Optifine Installed: Yeah
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: N/A

## Server Information
* Java Version: 8
* Operating System: Unknown
* Hoster/Hosting Solution: GGServers
* Sponge (Non-Vanilla Forge) Server: No?

**Comment by sk2048** [comment]
This is due to TComplement registering its nuggets -> ingot recipe despite its steel ingot being disabled. We have reported it to the mod author and I believe it has been fixed in the current release, though will need to confirm that.

**Comment by sk2048** [comment]
Please note, you can still convert nuggets to ingots in the normal way - by using the metal press.
