### ISSUE TITLE
Using sigil of green grove in purged lands makes it vanish

### ISSUE THREAD

**Issue by GearsOfClockwork** [DarkPacks/SevTech-Ages#3914]
## Bug Report

Attempting to bonemeal grass in a purged lands biome with a sigil of the green grove consumes the sigil.

## Expected Behaviour

The sigil should do nothing, but remain in inventory.

## Steps to Reproduce (for bugs)

1. Create a purged land using dread plague and appropriate ritual
2. Replace calcium blocks on surface with grass blocks
3. Attempt to grow tall grass with sigil.

## Client Information

* Modpack Version: 3.1.2 Hotfix 1
* Java Version: 1.8.0_211-b11
* Launcher Used: MultiMC
* Memory Allocated: 8G
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None

**Comment by sk2048** [comment]
Shinoow/Abyssalcraft#388
