### ISSUE TITLE
Constant crashes on load up.

### ISSUE THREAD

**Issue by badmanreviews** [DarkPacks/SevTech-Ages#3915]
My game keeps crashing when I try to load it, only started today and happens no matter how much ram I allocate to minecraft

[crash-2019-09-01_19.15.00-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/3564023/crash-2019-09-01_19.15.00-client.txt)

**Comment by sk2048** [comment]
The version of the LightWeight Java Game Library (LWJGL) shipped with Minecraft 1.12.2 does not support certain keybindings.

This cannot be resolved by us.

You should avoid using keybindings that are not present on a standard keyboard and 3 button mouse, else this crash will occur on startup.

You can get the game to start by manually editing the options.txt file to remove the bindings that are causing issue, or deleting it and allowing Minecraft to regenerate it.
