### ISSUE TITLE
missing mapping for part with RedStone Torch

### ISSUE THREAD

**Issue by Seeled008** [DarkPacks/SevTech-Ages#3919]
## Bug Report
3.0.8 Server crashes on load due to error related to missing mapping ID minecraft:redstone_torch

## Expected Behaviour
Server loads and is available for use

## Logs

* Client/Server Log: https://gist.github.com/Seeled008/a094602de826ba5d168a4a9d3e8c23e4
* Crash Log: https://gist.github.com/Seeled008/d9ae8b5c40c5add9a63924b048aa5ae3

## Client Information

* Modpack Version: 3.0.8
* Java Version:1.8.0_211-b11
* Launcher Used: Twitch
* Memory Allocated: Round 7gb
* Server/LAN/Single Player: Server
* Optifine Installed:no
* Shaders Enabled:no

## Server Information
* Java Version:1.12.2
* Operating System: Win10
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
Known issue, fixed in 3.1.0+

Restore a backup and avoid placing more than one Redstone component in a single block space until you update.
