### ISSUE TITLE
SevTech not even launching

### ISSUE THREAD

**Issue by Tapeman83** [DarkPacks/SevTech-Ages#3921]
## Bug Report
When I attempt to launch the pack, from the vanilla Minecraft launcher with the current version of SevTech selected, it crashes immediately and re-opens the launcher.

## Expected Behaviour
It crashes immediately instead of even starting to load the game.

## Steps to Reproduce (for bugs)

1. Use the 3.1.2 (Hotfix 1) release of the pack and attempt to launch while using the vanilla launcher.
2. Pack will not launch and will simply re-open the launcher with an error message.

## Logs

* Client/Server Log: https://pastebin.com/i9kQFLXe
* Crash Log: There does not appear to be a crash log generated for this issue.

## Client Information

* Modpack Version: 3.1.2 (Hotfix 1).
* Java Version: Java 8, Update 211, allegedly. Since I'm using the native launcher, I'm not entirely clear on what version is being used.
* Launcher Used: Vanilla launcher, through the Twitch desktop app.
* Memory Allocated: 8GB. 
* Server/LAN/Single Player: Single player.
* Optifine Installed: No.
* Shaders Enabled: No.

## World Information
 
* Modpack Version world created in: 3.0.8.

* Additional Content Installed: None that I know of.

**Comment by Tapeman83** [comment]
Alright....turns out I'm using Java 8, update 51, because of using the native launcher. I'll try to see if using the jar launcher will work again, but I had to switch from it in the first place because it stopped working upon the release of 1.14. I'll try it now and see.

**Comment by Tapeman83** [comment]
Ah...it won't even display any of the modpacks I have installed when I switch to the JAR launcher. For now, I'll edit my bug report to reflect this.

**Comment by sk2048** [comment]
You seem to be attempting to load multiple versions of BNBGamingCorePlugin 

Twitch may have messed up whilst updating the pack.

**Comment by Tapeman83** [comment]
Ah. Is there a way for me to fix this, or should I just back up my save and uninstall & reinstall the pack?

**Comment by sk2048** [comment]
That’s probably the simplest thing to do

**Comment by Tapeman83** [comment]
Ok. Thanks for the help.

**Comment by Tapeman83** [comment]
After uninstalling, reinstalling, and restoring my save, it's working fine. This issue can be closed, thanks.
