### ISSUE TITLE
Server Problems

### ISSUE THREAD

**Issue by 1artificial1** [DarkPacks/SevTech-Ages#3923]
Hey guys so I tried to update my server to the new Hotfix. I did everything the UPDATE.txt said to do. This error keeps popping up when I try to join.

Recurrent Complex: Failed mod's custom NetworkCheckHandler FMLMod:reccomplex{1.4.8.2}

Also, whenever I tried to do the installer to update forge it just immediately closes out.

**Comment by sk2048** [comment]
Did you update your client too?

**Comment by 1artificial1** [comment]
Yes I did, I think it's my server that won't update.

**Comment by sk2048** [comment]
Either your server or client is missing Recurrant Complex. But without more information I cannot really help. Seems we have a template for a reason after all.
