### ISSUE TITLE
Age advancement tabs are gone since update

### ISSUE THREAD

**Issue by vidal-adrien** [DarkPacks/SevTech-Ages#3924]
## Bug Report

The age tabs in the advancements menu are gone since I updated to 3.1.2_Hotfix_1 (on ATLauncher). 
The Twilight Forest and Betweenlands tabs are still available. New (previously hidden ?) tabs have appeared (vanilla, buildcraft, corail tombstone, astral sorcery). 
This is the case for both existing worlds or newly created ones. 
/reload doesn't fix it.

EDIT: [Screenshots](https://imgur.com/a/jZE8gnB)

## Expected Behaviour

Age advancement pages to be here. Other vanilla/mod advancement tabs to not be here.
## Steps to Reproduce (for bugs)

1. Load/Create a world.
2. Open the advancements menu.

## Logs

* Client/Server Log: https://gist.github.com/vidal-adrien/78094afadc415e1ebcfc18ab89deb0bd
* Crash Log:

## Client Information

* Modpack Version: 3.1.2_Hotfix_1
* Java Version: 1.8.0_192
* Launcher Used: ATLauncher
* Memory Allocated:  6 144 Mb
* Server/LAN/Single Player: Single Player
* Optifine Installed: false
* Shaders Enabled: false

## World Information

* Modpack Version world created in: 3.1.0 for the pre-existing world, 3.1.2_Hotfix_1 for new ones.

* Additional Content Installed: none

**Comment by sk2048** [comment]
You are missing mods, at least Triumph is not being loaded.

**Comment by vidal-adrien** [comment]
Can confirm that triumph is not loaded (in-game mod options). I was looking for mods such as Game Stages and Better Advancements which are loaded but I didn't know that there was another mod to look for.
Triumph is listed in the list of mods of my instance but is absent from the instance's mods folder.
The launcher's log file is full of issues concerning triumph all of which stem from the fact that it fails to download it.

The "reinstall" (3.1.2_Hotfix_1) functionality  also fails to download Triumph.

Currently attempting a fresh install of 3.1.1 (ATLauncher doesn't show 3.1.2_Hotfix_1 in the available versions for a fresh install) on a new instance. Will test new world and then pre-update backup of my world. Will then try to update this instance to 3.1.2_Hotfix_1.

**Comment by vidal-adrien** [comment]
New instance succesfully installed with no missing mods. 
The issue was apparently on the part of the ATLauncher.

Thanks for the help. Closing Issue.
