### ISSUE TITLE
New Server(3.1.2_Hotfix-1) not able to start on Linux

### ISSUE THREAD

**Issue by joshua-lehmann** [DarkPacks/SevTech-Ages#3925]
## Bug Report
I created a new server with version 3.1.2_Hotfix-1 without chaning any configs and tried to start it ony my Linux (ubuntu 18.04) server. Everytime after loading the dimensions I get the erorr: `"Can't keep up! Did the system time change, or is the server overloaded? Running 7396ms behind, skipping 147 tick(s)" ` and the server will not start. I Already tried installing a fresh server and same issue occured.

## Expected Behaviour
The server should start fine.

## Steps to Reproduce (for bugs)

1. Create a fresh SevTechAges server and accept eula etc.
2. Start the server on linux with  java -Xmx5G -jar forge-1.12.2-14.23.5.2838-universal.jar
3. Wait until spawn area is prepared
4. Server will output `[Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 7396ms behind, skipping 147 tick(s)
[39;0m> `

## Logs
ServerStartup Log: https://pastebin.com/embed_js/mHm3sHAa

## Client Information
* Modpack Version: 3.1.2_Hotfix-1
* Java Version: openjdk version "1.8.0_222" 
 OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
* Launcher Used: ATL Launcher (only used for creating Server Files)
* Memory Allocated: 5GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.1.2_Hotfix-1

## Server Information
* Java Version: openjdk version "1.8.0_222" 
* Operating System: ubuntu 18.04 on an Azure VM Standard D2s v3 (2 vcpus, 8 GiB memory)
* Hoster/Hosting Solution: Microsoft Azure
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
There is nothing in this log that suggests the server has failed to start. In fact, it looks entirely normal. A server often has to skip ticks after creating the spawn region.

**Comment by sk2048** [comment]
Why do you believe the server hasn’t started?

**Comment by joshua-lehmann** [comment]
Because I cannot connect to it! The server is not online after I started it, I tried to reboot it multiple times and it never starts (also the spawn area creation is not finished in the logs or?) And the ticks do not continue, after message about the ticks comes no more lines are written to the log.

**Comment by sk2048** [comment]
Java 8 is the only supported version.

The log should only continue if there are issues, such as the computer running too slowly (“Can’t keep up...”)

Once “Unloading Dimension...” appears try running the command `/forge tps` on the server console.

**Comment by sk2048** [comment]
Having taken a quick look at Azure (I typically use AWS), have you set your inbound port rules to allow port 25565? Without doing so your Minecraft server will be inaccessible from the internet, and will appear offline.

**Comment by jNullj** [comment]
not sure if related but i just started a server with this version on archlinux with java8, i have the same error but i can log-in, at login it says the tick takes 60.4s and it assumes it failed, then it shut itself down

**Comment by sk2048** [comment]
Not at all related @jNullj, please open a new issue with all relevant information or join the discord for support. (https://discord.gg/darkosto)

**Comment by joshua-lehmann** [comment]
@sk2048 Thanks a lot, after you said java 8 is only version, I uninstalled all java related things on the server and re installed java 8 specifically. Now the server runs! 

One last questions, sometimes I still get the message (“Can’t keep up...”) (but I server should be fine 6gb ram 2vcup and only 1 player online). I read [here ](https://forums.spongepowered.org/t/optimized-startup-flags-for-consistent-garbage-collection/13239) that this can be related to the java garbage collection and that you could use following paramters: `java -Xms6G -Xmx6G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AlwaysPreTouch -jar server.jar`
Is this a good idea?
Any recommendations for best performance, regarding the startup paramter for a server with the SevTechAges Modpack on Linux Server?

**Comment by sk2048** [comment]
Glad you got it going! There are a variety of reasons you might still see the "Can't keep up..." messages, the first is terrain generation - an incredibly intensive process that only utilises a single CPU core and causes even the most performant computers to struggle. A good way around this is pre-generating a region in each dimension and trying to stay within it. The command to do so is `/forge gen <pos_x> <pos_y> <pos_z> <num_chunks> <dimension>`

For example to generate a 5000 chunk area around yourself in the overworld, run `/forge gen ~ ~ ~ 5000 0`. This would give you a roughly 1000 block square region.

Another common issue is the garbage collector, which the arguments you've posted above seek to help with. It normally helps more with lag spikes than anything else, and we have our own set of JVM parameters that we recommend which aren't that dissimilar to those you've given above.

`java -Xms6G -Xmx6G -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -jar <server_jar> nogui`

These are used in our startup script provided in the server files from Curseforge.

Either should be an improvement over running without any customisation of the garbage collector.

Finally, an issue I ran into when using VPS was that, when they did not have local storage that my world was saved to, I would experience severely degraded performance vs. the same hardware with a local SSD.
