### ISSUE TITLE
crash after few minutes in beetweenlands

### ISSUE THREAD

**Issue by gmngms55** [DarkPacks/SevTech-Ages#3927]
my game crashed after few minutes in beetweenlands then i can't join the world again. i uploaded the map again from backups and samethings happened again. my game crashed in beetweenlands again and i can't connect to map anymore. it stucks on a loading screen.
 here is crash log 

> https://pastebin.com/7s1q4pAf

i just added worldedit 1-2 weeks ago. i didn't change anything

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
