### ISSUE TITLE
Axle stage 2 recipe 

### ISSUE THREAD

**Issue by itanne99** [DarkPacks/SevTech-Ages#3928]
I updated both my client and server to V 3.1.2 from V 3.0.8 and at first I had an issue with advancements but I was able to fix that by revoking and granting them back. _If someone has an easier fix for this please let me know_, but I am trying to make the axle from Better With Mods with the recipe from age 2, but the output isn't showing up. I thought this was an issue on the server end, but the same issue happens in single player. I haven't had any other "test subjects" to see if it's just something with my client, but if anyone else has had this issue and know how to fix it please let me know

<img width="308" alt="Annotation 2019-09-09 160658" src="https://user-images.githubusercontent.com/20746427/64562849-de613100-d31b-11e9-8ca5-897fdf5cbf34.png">

**Comment by Frozensun95** [comment]
Same issue here!

**Comment by sk2048** [comment]
JEI is displaying certain recipes incorrectly in this version of the pack, align the components vertically in a 3x3 crafting grid and it will work.

Caused by #3863, update recipestages to fix.
