### ISSUE TITLE
Food Recipe Outputs lack value

### ISSUE THREAD

**Issue by ArcticHowler** [DarkPacks/SevTech-Ages#3929]
## Context

I don't know anything about config changing and what have you, but the food recipes need tweaking... The output items for things like steak and potatoes, pork and other food combinations provide less refill than the meat, let alone anything combined with the meats... makes crafting food pointless beyond just cooking meats... Thus any food adding mods/recipes equally near pointless... Farming thus becomes pointless as well, other than for cotton and similar items.
![2019-09-09_14 51 46](https://user-images.githubusercontent.com/9349860/64569191-9210f380-d311-11e9-984d-361ba78cc9e9.png)
![2019-09-09_14 51 48](https://user-images.githubusercontent.com/9349860/64569192-9210f380-d311-11e9-8805-30c06159a044.png)
![2019-09-09_14 51 50](https://user-images.githubusercontent.com/9349860/64569194-92a98a00-d311-11e9-9de1-9bc47ced6091.png)
![2019-09-09_14 51 52](https://user-images.githubusercontent.com/9349860/64569195-92a98a00-d311-11e9-88d1-baf134d85af7.png)
![2019-09-09_14 51 56](https://user-images.githubusercontent.com/9349860/64569197-92a98a00-d311-11e9-8297-60ed954f2c83.png)
![2019-09-09_14 52 12](https://user-images.githubusercontent.com/9349860/64569198-92a98a00-d311-11e9-9538-d08a41b32b68.png)
![2019-09-09_14 52 13](https://user-images.githubusercontent.com/9349860/64569199-92a98a00-d311-11e9-9e02-fbd27599cd68.png)
![2019-09-09_14 51 41](https://user-images.githubusercontent.com/9349860/64569200-92a98a00-d311-11e9-9753-30bba8eb4838.png)
![2019-09-09_14 51 44](https://user-images.githubusercontent.com/9349860/64569201-93422080-d311-11e9-9eaa-9ef65827b9c8.png)

Screetshots are out of order, but that should show you what I mean... While my stage in these screenshots are still intro level, the results are the same in later stages(I've completed up to stage 3 before, but remade world for new version yesterday or so... This has bugged me for a while now...)

**Comment by sk2048** [comment]
There is more to food in this pack than simply filling up your hunger bar for the minimum possible number of items eaten. Making food which provides a balance of nutrition is far more important than filling up the hunger bar as quickly as possible.

With this in mind, crafted food becomes very useful.

**Comment by ArcticHowler** [comment]
Forgive me, but if that's the case, then why is the protein gain from ham and eggs less than porkchop on it's own...

**Comment by sk2048** [comment]
You put in 5.5% Protein and get 6% out, I'm afraid I don't see the issue. Besides, as mentioned above, going for a *balance* is more important.

**Comment by ArcticHowler** [comment]
The readout for Ham and Eggs for me is 3.0% protein vs the 5.5% of the individual items, I can't say every item is the same, but I noticed that one, in the case of the hunger bar I accept the explanation, just noticed the nutrition gain was off for what you are suggesting after you said that and went in-game for a bit(wasn't intending to continue this beyond if you don't wish, but spotting that made me bring it back up, sorry...) Here's a screenshot of output for Ham and Eggs output. As a precaution I'll state, I've not modified anything, purely updated my profile and made a new world since previous version i played on. 

![2019-09-10_11 36 34](https://user-images.githubusercontent.com/9349860/64640705-64828380-d3bf-11e9-903c-91f4f5bb8e63.png)

**Comment by vnvizitiu** [comment]
If I can chime in, if you just eat the egg you get 1.5% protein, if you just eat the pork chop you get 4% but if you eat 2 hams and eggs you get a total of 6%
