### ISSUE TITLE
Primal Core block textures mixed up brick and cobblestone 

### ISSUE THREAD

**Issue by azeiver** [DarkPacks/SevTech-Ages#3930]
Primal Core textures mixed up brick and cobblestone example green schist not droping cobblestone it droping bricks

**Comment by sk2048** [comment]
There is no texture that looks exactly like vanilla cobblestone. The cobblestone texture looks like small bricks, the bricks texture looks like larger bricks (c.f. stone brick).

The block called Greenschist Cobblestone is correctly dropped when you break the block.
