### ISSUE TITLE
Diamonds in stage 3 recipes

### ISSUE THREAD

**Issue by artopolis** [DarkPacks/SevTech-Ages#3931]
## Bug Report
There is a recipe for Storage Drawers Controller here in JEI, where diamon is required. But diamonds are available only on stage 5. Should it be somehow fixed?

## Expected Behaviour
JEI recipe.

## Possible Solution
Replacing conponent with starmetal ingot or by Aquamarine.
## Steps to Reproduce (for bugs)

1. Open JEI Drawer Controller #8584

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artopolis** [comment]
There is a recipe for Storage Drawers Controller in JEI, where diamond is required. But diamonds are available only on stage 5. Should it be fixed?

**Comment by sk2048** [comment]
<img width="380" alt="Screenshot 2019-09-10 at 19 27 36" src="https://user-images.githubusercontent.com/23245543/64640052-1bebba00-d401-11e9-9461-a5fe062a3a34.png">


Not the case in the most recently released version of the pack (3.1.2).

**Comment by sk2048** [comment]
@artopolis It seems likely you've either removed mods and broken the pack's scripting, or that the install/upgrade process failed to install all the mods in the pack.

It's also possible you're using an old version of the pack and this bug has now been fixed, though I don't have the time to go back through old versions to see if this is the case. It would have been nice if you'd completed the template.

If you continue having issues you might find it easier to get support on the discord.

**Comment by artopolis** [comment]
There is no ability to applay screenshots in discord. So there id no proof availible. And you guys just say 'its your faul'
But Stahe three is FULL of inpermissible recipes:
![2019-09-17_17 28 13](https://user-images.githubusercontent.com/6339092/65051473-da638d80-d971-11e9-972e-18a0a322490a.png)
![2019-09-17_17 38 22](https://user-images.githubusercontent.com/6339092/65052614-67f3ad00-d973-11e9-99a5-e4d1c2a21760.png)
![2019-09-17_17 39 12](https://user-images.githubusercontent.com/6339092/65052618-6924da00-d973-11e9-9098-90026641be8e.png)
![2019-09-17_17 47 26](https://user-images.githubusercontent.com/6339092/65052645-6fb35180-d973-11e9-8484-7cdb0fdcf23a.png)
![Drawers Controller 2019-09-12_12 07 08](https://user-images.githubusercontent.com/6339092/65052652-7215ab80-d973-11e9-90fd-4804851e1d74.png)

And so on and so on...
There is not only in JEI nor in books like a manual for aicraft...
Remeber? it's a stage 3! (version 3.1.2 with SevTech_Ages-3.1.2-hotfix)
