### ISSUE TITLE
Updating modpack causes parts of the world to disappear.

### ISSUE THREAD

**Issue by Dalenacio** [DarkPacks/SevTech-Ages#3937]
After updating the modpack to 3.1.2, parts of the world around my base simply vanished. No block that I place myself seems to have been targeted, but among those that were there is a variety  of blocks. This has created a huge sort of cave complex beneath my base that was not there before.

Furthermore, searching around the countryside reveals that there are many more holes like this. Grass and torches flot in midair as if attached to a black, and gravel remains suspended in midair. However, when I went far enough to enter previously non-rendered parts of the world, these holes stop happening.

Hole under base:
![image](https://user-images.githubusercontent.com/12587061/64921757-89b03100-d7c7-11e9-97c8-80304fa3c534.png)
![image](https://user-images.githubusercontent.com/12587061/64921809-d6940780-d7c7-11e9-9249-1f7a34acf4da.png)
![image](https://user-images.githubusercontent.com/12587061/64921873-68037980-d7c8-11e9-8102-a003f0466d7b.png)

More holes:
![image](https://user-images.githubusercontent.com/12587061/64921943-fe379f80-d7c8-11e9-86a0-92b8b9470eae.png)
![image](https://user-images.githubusercontent.com/12587061/64921956-160f2380-d7c9-11e9-8682-90741117068e.png)
![image](https://user-images.githubusercontent.com/12587061/64921962-29ba8a00-d7c9-11e9-8f78-103f05876133.png)
![image](https://user-images.githubusercontent.com/12587061/64921971-43f46800-d7c9-11e9-8d84-ea1c54921d67.png)
![image](https://user-images.githubusercontent.com/12587061/64921986-7900ba80-d7c9-11e9-8b52-3917dbdab3ed.png)
![image](https://user-images.githubusercontent.com/12587061/64922000-d98ff780-d7c9-11e9-872e-eed1c84a17a9.png)

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
Please follow the template. Logs from when you updated in particular are necessary to diagnose what is going on here.

**Comment by sk2048** [comment]
Suspect you're missing Primal. Launcher failed to update the pack properly, or you removed it. Either way, not reproducible.
