### ISSUE TITLE
Updated server from 3.0.8 to 3.1.2. Recipes broken

### ISSUE THREAD

**Issue by UnknownDev37** [DarkPacks/SevTech-Ages#3938]
**Fixed** - Files in server were missing

https://gist.github.com/UnknownDev37/8545588624ed60760b4b9dd171653c9c

I need to find out the log stuff but this is mostly a I hope im not alone can can get help.
As far as I tested, Primal recipes are hit. Kiln dont cook items but they do shot out xp like they did, i cant craft the stone mallet,  or the chopping block, I can even craft wood planks normally (in crafting grid)
Im probably going to edit this to follow more the guidelines but im confused what logs. Like just log in the server and then copy logs or try crafting or using kiln then copg logs.

Im in age 2
Creeperhost
Using latest server files from twitch app (Manual file install to server from old 3.0.8 creeperhost support files)
Im using 8ram

**Comment by sk2048** [comment]
For this issue the most useful log file will be crafttweaker.log from your server. So long as the server completed startup, all the information we need will be in the log.

**Comment by UnknownDev37** [comment]
https://pastebin.com/NuRJLcHk
I apologize for the late upload,  life stuff hitting hard.

**Comment by sk2048** [comment]
Unfortunately that's only the first ~250 lines of a file that usually runs to several thousand lines.

I suggest using https://gist.github.com as it supports very large text files, unlike pastebin.

**Comment by UnknownDev37** [comment]
https://gist.github.com/UnknownDev37/8545588624ed60760b4b9dd171653c9c

**Comment by sk2048** [comment]
It looks like the geolosys script is missing. It should be found at `./scripts/recipes/mods/geolosys.zs`.

Make sure all files were successfully uploaded.

**Comment by UnknownDev37** [comment]
Would that be in my server dictionary? 
I don't see recipes in scripts so i followed ./scripts/crafttweaker/recipes/mods but i dont see geolosys.zs 
Once I get home ill be able to reupload files, im just making im not missing an entire folder called recipes in the scripts folder.

**Comment by sk2048** [comment]
My mistake. You have identified the correct path, though I have updated the comment above.

**Comment by UnknownDev37** [comment]
I don't know how I messed up the first time but it worked. The file is in there and crafting seems to be working.
