### ISSUE TITLE
Wooden Axle age 2 recipe doesn't work.

### ISSUE THREAD

**Issue by Bloodhit** [DarkPacks/SevTech-Ages#3941]
I'm in age 3 right now and Age 2 Wooden Axle recipe( 1 hemp rope and 2 Planks Moulding) doesn't work. Age 1 recipe (2 sticks, 2hemp ropes, 1 Black Quartz) still works fine.

* Modpack Version:  SevTech: Ages 3.1.2_Hotfix_1 for Minecraft 1.12.2
* Java Version: Java 8 (1.8.0_191), Minecraft: Java 8 (1.8.0_191)
* Launcher Used: ATLauncher Version: 3.3.1.4
* Memory Allocated: 6gb
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled: No
* Modpack Version world created in: 3.1.0 (?)

Here my log dump If I missed anything https://paste.atlauncher.com/view/f56eda9d

**Comment by sk2048** [comment]
This is a JEI display issue, place the components in the crafting grid vertically and it will work.

To fix the issue, upgrade RecipeStages to version 1.1.3. Do not upgrade anything else or you will likely encounter issues with the included scripts.

**Comment by Bloodhit** [comment]
Thank you, it works fine that way. Is there way to update mods individually from AT Launcher, or do I need to drop it in mods in instances folder?

**Comment by sk2048** [comment]
I'm not overly familiar with ATLauncher I'm afraid, dropping it in the mods folder and removing the old version will definitely work however.

**Comment by Bloodhit** [comment]
Thank you.
