### ISSUE TITLE
Server world corrupted after single session, no updates

### ISSUE THREAD

**Issue by StefinitelyLethal** [DarkPacks/SevTech-Ages#3944]
## Bug Report

World corrupted after one 2 hour play session, server now crashes any time you attempt to join unless we generate a new world

## Expected Behaviour

Server staying up and being playable

## Possible Solution

Generating new world

## Steps to Reproduce (for bugs)

1. Joining server with any account

## Logs

* Crash Log: https://pastebin.com/XT03qtki

## Client Information

* Modpack Version: 3.1.2 Hotfix 1
* Java Version: Version 8 Update 211
* Launcher Used: Twitch
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Server
* Optifine Installed: Yes
* Shaders Enabled: Yes

## World Information

* Modpack Version world created in: 3.1.2

* Additional Content Installed: Only clientside Optifine (Disabling Optifine doesn't solve the issue)

## Server Information
* Java Version: Version 8 Update 211
* Operating System: Windows 10
* Hoster/Hosting Solution: Hosted on my own computer
* Sponge (Non-Vanilla Forge) Server: Unsure, I used the server download on the Twitch launcher

**Comment by sk2048** [comment]
Unfortunately this is an issue that can happen with any minecraft server, particularly if you're using older hard drives to store your world on which can be more prone to write errors. There are utilities that can help you determine your drive's health.

Always shut down your server properly using the `/stop` command.

Without numerous people experiencing similar issues, it is unlikely to be an issue with a mod storing invalid NBT data.

We do include a backup mod, you should try restoring your most recent backup before outright starting a new world.
