### ISSUE TITLE
Grass fiber mesh not working

### ISSUE THREAD

**Issue by itzDevy** [DarkPacks/SevTech-Ages#3945]
Help 
![image](https://user-images.githubusercontent.com/55580281/65313890-87d7da80-dbd8-11e9-8f69-b3ea7a5aed2e.png)

**Comment by vnvizitiu** [comment]
You need to combine the fibers into twine first, 3 for each, NEI can help with that.

**Comment by itzDevy** [comment]
thanks. my friend who i was showing the modpack to figured it out before me rip
