### ISSUE TITLE
Internal Exception: java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by zblueeeyx** [DarkPacks/SevTech-Ages#3950]
https://pastebin.com/BFK7vS1V Crash report
(Tlauncher) minecraft 1.12.2
22 mods
java version 8.161 (recomended versio from Tlauncher)
if someone can help me
https://pastebin.com/Kg8cAhdy Log

**Comment by artdude543** [comment]
Nothing to do with us. Also using a modded launcher, which even if you were using one of our packs. You'd not get support.
