### ISSUE TITLE
ulta laggy and corrupted worlds

### ISSUE THREAD

**Issue by ghostpanda0** [DarkPacks/SevTech-Ages#3951]
## Bug Report
Ive played this pack before on my system (given this was a few months ago as my system was down and I needed new power supply) loaded it up now and the lag was... shocking. It used to run just fine with 3gb out of my 12 set aside for it. even on lowest graphic settings it is unplayable. 
I tried tweaking some settings. lowering graphics, lighting, and messing with the betterFPS settings. When I tried loading into the world I just made moments ago. It started loaded and building terrain as if it was new world being generated. Then switched to shutting down internal server. and kicking me not to the single player select world, but the multiplayer select server screen. I tried looking for a crash log in the usual places but none was created since this it seems is not seen as a crash. if there is a file I could send to better help let me know. 

## Expected Behaviour
Laggy game and unable to play a world past session one

## Steps to Reproduce (for bugs)

1. create a fresh game
2. Exit game
3. try to load world a second time
[2019-09-24-1.log](https://github.com/DarkPacks/SevTech-Ages/files/3658443/2019-09-24-1.log)

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.1.2 Hotfix 1
* Java Version: latest
* Launcher Used: Twitch
* Memory Allocated: 3gb
* Server/LAN/Single Player: single
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: current

* Additional Content Installed: none

**Comment by sam-kirby** [comment]
3GB is below the minimum suggested RAM allocation, would it be possible for you to up this to 6GB and see if your issue persists?
