### ISSUE TITLE
Suggestion: Rebalance Flight

### ISSUE THREAD

**Issue by TheKedart** [DarkPacks/SevTech-Ages#3957]
Issue: Creative flight is too easy to obtain through both Mantle of Stars: Vicio (with Perk) and Creative Flight Modifier through Environmental Tech.

The current patch (3.1.2 hotfix1) implements an update for Astral Sorcery, which overhauls the perk system. This overhaul is fine, but it also includes a Vicio perk that allows the Vicio mantle of stars to grant creative flight. The actual mantle is fine without the perk (grants Elytra type gliding), but with the perk it's OP. To top it off, the mantle can be acquired as early as stage 2!

This Mantle with perk trivializes the adventure mods (Twilight Forest/Betweenlands), the Nether, the End, etc. It also completely invalidates mods like Viescraft and IronJetpacks (both of which are considered significant enough to have advancements). 

Even without this mantle, the Jetpacks are generally useless. They are complicated to assemble, which is fine, except for the fact that for a similar amount of work you can make the creative flight mod for EnvTech. Creative flight is not only easier to control than any of the jetpacks, it actually gives more speed!

Solution: Disable Vicio Mantle of Stars Perk via Astral Sorcery configs. Require at least one of the Jetpack tiers (Emerald? Creative?) in the assembly of the Creative Flight Mod.

**Comment by sam-kirby** [comment]
As far as I am aware, this perk cannot be disabled.

**Comment by TheKedart** [comment]
I'm not an expert, but I *think* they can be disabled.
https://github.com/HellFirePvP/AstralSorcery/blob/master/AS-Example.zs#L8

**Comment by sam-kirby** [comment]
Ah, I was unaware they could be modified through scripts. The line below may be relevant too however, we will have to investigate the effect of removing a perk on people who have already unlocked it before considering whether or not to follow through with this change. It should be noted that it is intentional that going deeper into the individual mods than required by the advancement is intended to give the player sometimes “OP” rewards. This perk was not a consideration of the original design however.

**Comment by TheKedart** [comment]
I fully understand, however I also know that you try to balance the investment:reward ratio. AS is one of the easiest mods to "max out" (time and resource-wise), and this update to the perk system adds a HUGE reward in the form of Creative Flight (arguably one of the most powerful abilities in the game). Being able to unlock it with very cheap materials and very low time investment as early as age 2 just seems out of theme with the rest of the pack.

If disabling the perk is out of the question, balancing can be done by increasing the cost for the Vicio Mantle of Stars. Perhaps including some Age 4 or even Age 5 gated materials could help balance it greatly.

**Comment by DatBoiSnowweh** [comment]
Youre a cocksucker.
Just wasted hours for creative flight as the ring of ascent basically gives it to you in age 2 for the cost of XP and i was tired of farming mobs to find out some fucking debbie downer ruined the fucking only thing i was looking forward to in AS.

**Comment by sam-kirby** [comment]
@DatBoiSnowweh Your behaviour here is completely unjustified. No action was ever taken as a result of this issue - we decided that going that deep into AS should be rewarding and so the Spectral Wings perk remains available along with the Vicio Mantle of the Stars.
