### ISSUE TITLE
nearly permanent invulnerabilty (no logs)

### ISSUE THREAD

**Issue by Devilinar** [DarkPacks/SevTech-Ages#3961]
## Bug Report

 Nearly permanent invulnerability

## Expected Behaviour

When you get the nutrition buffs for nourishment and resistance (90% nutrition on 2 food types) and then hop in and out of the hunting dimension you will take no damage at all from anything.

no fall damage, no drowning damage, lava damage or attack damage. status effects still happen, but you take no damage untill nutrition drops below 90% for all food types except for 1.

## Steps to Reproduce (for bugs)

1. get at least 2 food types above 90% nutrition to get the nourishment and resistance buffs
2. go to the hunting dimension
3. (immediatly) leave the the hunting dimension
4. permanent invulnerability if nutrition is maintained above 90%

## Logs

no logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.1.2 hotfix 1
* Java Version: 1.8.0_171-b11
* Launcher Used: twitch
* Memory Allocated: 8gb
* Server/LAN/Single Player: server
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in:3.1.2 hotfix 1

* Additional Content Installed:

## Server Information
* Java Version: same as above
* Operating System: win 10 x64
* Hoster/Hosting Solution: home dedicated
* Sponge (Non-Vanilla Forge) Server: unknown ( using all sevtech files)

**Comment by sam-kirby** [comment]
Duplicate of #3874
