### ISSUE TITLE
Quality of Life: Recipes to Add

### ISSUE THREAD

**Issue by TheKedart** [DarkPacks/SevTech-Ages#3963]
Requesting the following recipes to be added to various machines for QOL purposes:

Arc Furnace:
Red Sand -> Glass
immersiveEngineering.addArcFurn(<minecraft:glass:0>, <minecraft:sand:1>, null, 150, 256);

Mekanism Crusher:
Black Quartz (1) -> Crushed Black Quartz (1)
mekanism.addCrusher(<actuallyadditions:item_misc:5>, <actuallyadditions:item_dust:7>);

Starmetal Ingot (1) -> Stardust (1)
mekanism.addCrusher(<astralsorcery:itemcraftingcomponent:1>, <astralsorcery:itemcraftingcomponent:2>);

Mekanism Enrichment:
Black Quartz Ore (1) -> Black Quartz (2)
mekanism.addEnrichment(<actuallyadditions:block_misc:3>, <actuallyadditions:item_misc:5> * 2);

Reasoning:
Red Sand can't be smelted into glass using Arc Furnace for some reason, forcing you to use Tinkers. A bit obnoxious when trying to make singularities.

Black Quartz Ore/Quartz/Dust currently has to be manipulated using the slow actuallyadditions crusher/double crusher. In age 5, Mekanism machines should be able to handle this type of recipe.

Starmetal Ingots can be produced in abundance in age 5 with mystical ag, however you are forced to use the ActuallyAdditions or IE crusher to convert to dust. Just adding a recipe to Mekanism crusher for QOL.

These are all minor changes but help streamline things in age 5 a bit.

**Comment by sam-kirby** [comment]
I have added two of these recipes: starmetal to stardust and red sand to glass. Black Quartz to dust was already in the game, whilst enriching dust to black quartz creates a resource doubling loop.
