### ISSUE TITLE
Can not craft a wooden hopper

### ISSUE THREAD

**Issue by MNyan** [DarkPacks/SevTech-Ages#3966]
## Bug Report
 
I organize a chest and some wooden planks on a crafting stump as I should, then right click them with a crafting stone. instead of popping off as a wooden hopper, the stone keeps being used on the crafting stump. This continues indefinitely.

## Client Information

* Modpack Version: 3.1.2
* Java Version: 1.12.2
* Launcher Used: Official Minecraft 1.14.4 Launcher, modpack installed from twitch
* Memory Allocated: If by this it means RAM, 10GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: False

## World Information
 
* Modpack Version world created in: 3.1.2 

* Additional Content Installed: No additional content

**Comment by sam-kirby** [comment]
The work stump can only be used to craft very early recipes, stage tutorial, zero, and baykok. You need to make a crafting table to use the recipe for a wooden hopper that uses a minecraft chest.

This is intentional.
