### ISSUE TITLE
Gear Boxes Broken

### ISSUE THREAD

**Issue by Pakmai** [DarkPacks/SevTech-Ages#3970]
## Bug Report
The gear boxes no longer work on the water wheel

## Expected Behaviour
Nothing happens.  No matter what I do (new world/creative/free floating), I cannot get a waterwheel/windmill to power a gearbox.  This worked fine until I decided to move my waterwheel/gearbox on my first world.  Then it stopped.  I decided to start a new world in case that one was bugged.  Same result. Waterwheel/Axle animation is fine, until it hits the gearbox.  gearbox will not power additional axles.  Even right up against the waterwheel.

## Steps to Reproduce (for bugs)
I have no idea, as I have no idea why it's acting this way.

## Client Information
* Modpack Version: 3.1.2
* Java Version:
* Launcher Used: MC Launcher
* Memory Allocated: 6GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.1.2

**Comment by sam-kirby** [comment]
You haven't included any screenshots of your setup, and you don't mention some important things.

1. The wooden axles only transfer rotational energy 3 blocks before they need to go into a gearbox. Make sure your waterwheel has 3 blocks or less of axle between it and the gearbox.
2. The gearbox has a single input and all its other sides are outputs. The input is identified by the side with arrows pointing in towards the central spot where the axle comes in, when using the default textures at least. You can rotate the block by (iirc) shift right clicking it with an empty hand. Make sure the input is on the side the energy comes in from.

**Comment by Frikkle** [comment]
(the shift clicking with empty hand is indeed correct)

**Comment by sam-kirby** [comment]
Closing due to no response from original poster and lack of reproducibility.
