### ISSUE TITLE
Gear crafts not working right, bronze gear broken?

### ISSUE THREAD

**Issue by AdamChlupacek** [DarkPacks/SevTech-Ages#3974]
## Bug Report
All of this happens only when connecting to a server.

I granted myself stage0/root and stage1/root, and tried to craft a copper gear, which resulted in bronze gear (4 copper plates + 1 stone gear), also when I try to craft hopper using the 5 iron plates 1 bronze gear 1 chest recipe I can see in crafting bench that it is craftable but I can never take it out of the crating bench.

If I try to pour out bronze gear out of smeltery I get an unfamiliar item, which seems like signalum plate. I tried this only in my gameplay game, not on my debug server. 

## Expected Behaviour
The crafts work as JEI is suggesting.

## Steps to Reproduce (for bugs)
1. Get crafting bench
2. Get 5 iron plates, 1 chest 1 bronze gear
3. Try to craft normal hopper
4. Cannot get the hopper out of crafting window.

## Logs
I checked logs and there is nothing at the time of crafting. 

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.1.2 Hotfix 1
* Java Version: 1.8.0_181
* Launcher Used: Twitch app
* Memory Allocated: 8gb on client, default config on server
* Server/LAN/Single Player: Server
* Optifine Installed: N/A using the preinstalled provided client/server
* Shaders Enabled: N/A using the preinstalled provided client/server

## World Information

* Modpack Version world created in: 3.1.2 Hotfix 1

* Additional Content Installed:

## Server Information
* Java Version: 1.8.0_181
* Operating System: OSX 10.14.5, tested on hosted Red Hat server as well, same issue
* Hoster/Hosting Solution: local server (creeper host for the red hat)
* Sponge (Non-Vanilla Forge) Server: N/A

**Comment by sam-kirby** [comment]
Need to see the server logs. Both the main log and crafttweaker.log from the server would be useful.

**Comment by AdamChlupacek** [comment]
here you go: https://drive.google.com/drive/folders/1qqodatVH3QgBhxFBB-xdTsXkqbmg73RZ?usp=sharing  I included debug log as well so that there is as much info as possible, please let me know if you need anything more.

**Comment by AdamChlupacek** [comment]
@sam-kirby So, I have digged up my other pc (windows) and tried to login under the same character as before. Suddenly in my inventory I had copper gears instead of bronze gears and I can craft the hooper. I am pretty sure that I did reinstall my installation of sevtech before, I will try to do it again, update java to latest and such. If you have any idea where minecraft could be caching some additional data on OSX please tell me so that I can delete it.

**Comment by AdamChlupacek** [comment]
So yeah, I did reinstall it, updated java and everything gotten normal... Thank you for bearing up with me and for all the work on this great mod pack! I am closing this issue now.
