### ISSUE TITLE
Crashing with LAN play

### ISSUE THREAD

**Issue by TravGuy** [DarkPacks/SevTech-Ages#3976]
## Bug Report
 Whenever I try to save and quit after opening my game to LAN, the game stops responding. If I never open it to LAN, it works fine.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Avoid using open to LAN, there are numerous issues when using it in modded.
