### ISSUE TITLE
Crash on startup after updating to most recent version

### ISSUE THREAD

**Issue by EtenKillbeat** [DarkPacks/SevTech-Ages#3978]
## Bug Report
Every time I try to run the most recent version of the pack using the Twitch launcher (same as before), whenever the modpack starts to load, it instantly crashes.

## Expected Behaviour
Used to play it extensively a few months ago with no issues whatsoever, however after a long break and an update to the pack, the already described crash happens.

## Logs
* Client/Server Log: https://paste.feed-the-beast.com/view/b0009836
* Crash Log: https://paste.feed-the-beast.com/view/54ddd63a#L16

## Client Information
* Modpack Version: 3.1.2 Hotfix 1
* Java Version:
* Launcher Used: Twitch
* Memory Allocated: 7168 Mb
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in:
3.0.X   It wasn't as early as the pack was created but definitely before the 3.0.8 update. Though I believe I updated the pack to the 3.1.0 version and played for a bit (not certain)
* Additional Content Installed:
No

**Comment by sam-kirby** [comment]
Your crash report is from the 25th December 2018, and doesn't seem relevant as it shows a loaded world.

Your log indicates that there are multiple versions of at least one mod (BNBGamingCore). This likely indicates a broken upgrade, for which Twitch is responsible. An easy fix would be to install a fresh SevTech profile and copy your world over into that profile.
