### ISSUE TITLE
SevTech Ages won't start correctly

### ISSUE THREAD

**Issue by SwapesG** [DarkPacks/SevTech-Ages#3979]
Hello everyone!
I wanted to play the Minecraft Mod SevTech Ages but it isnt starting correctly
Pls help me 
Picture:
https://ibb.co/JRp2nch
pls help me. There is always the loading screen and it isnt starting
btw sry for my bad english skils

**Comment by SwapesG** [comment]
Updated picture:
https://ibb.co/3mKkkgj

**Comment by sam-kirby** [comment]
You likely need to assign more RAM (memory) to Java.

There are guides online for how to do this with Twitch Launcher if you want this in your own language or with pictures.

Go to Settings -> Minecraft -> Java Settings and adjust allocated memory to ideally 6GB if you have that much available.
