### ISSUE TITLE
SevTech: Ages - 3.1.2 Hotfix 1 - Crashes During Launch on ATLauncher

### ISSUE THREAD

**Issue by MorninBurchWood** [DarkPacks/SevTech-Ages#3981]
## Bug Report
 Crashes During Launch on ATLauncher

## Possible Solution
 Tried changing Memory Values

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log: 
* Crash Log: https://pastebin.com/VCdnK9vW

## Client Information

* Modpack Version: 3.1.2 Hotfix 1
* Java Version: Version 8 Update 221
* Launcher Used: ATLauncher
* Memory Allocated: Tried 6gb, 8gb, and 12gb
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
 Same as above
* Modpack Version world created in:
 None
* Additional Content Installed: None

**Comment by sam-kirby** [comment]
Your log indicates you are using Java 12. See line 4. Use Java 8.
