### ISSUE TITLE
Elixir of Starvation (The Betweenlands) can cause negative saturation

### ISSUE THREAD

**Issue by carter-g** [DarkPacks/SevTech-Ages#3982]
## Bug Report

Eating a yellow lollipop from Corail Tombstone's Halloween event rapidly decreases the player's hunger and disables the saturation mechanic while the effect is applied.

## Expected Behaviour

Saturation still disabled after the time is up which it shouldn't be.

## Possible Solution

Haven't tested dying yet. Might fix.

## Steps to Reproduce (for bugs)

1. Consume a yellow lollipop from Corail Tombstone's Halloween event to get "Curse of Starvation" effect.
2. Wait the 10 minutes.
3. During the 10 minutes and any time after, saturation from eating food will not be added to the hunger bar.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Angry-Pixel/The-Betweenlands#93

**Comment by sam-kirby** [comment]
Angry-Pixel/The-Betweenlands#903
