### ISSUE TITLE
Shift+RMB doesn't work

### ISSUE THREAD

**Issue by Sciti** [DarkPacks/SevTech-Ages#3984]
## Bug Report
Shift+RMB on samples doesn't create waypoint.
 
## Expected  Behaviour
In SevTech 3.0.8 when you shift + right click ore samples with something in hand, waypoint was automatically created on sample place. Maybe there's a way to enable it?

## Client Information
Modpack Version: 3.1.2
Java Version: 8 update 221
Launcher Used: MultiMC
Memory Allocated: 5120
Server/LAN/Single Player: Single
Optifine Installed: Yes
Shaders Enabled: No

**Comment by sam-kirby** [comment]
I don’t understand the issue. You expect nothing to happen so what is happening? Why are waypoints relevant? What are you actually doing?

**Comment by Sciti** [comment]
> I don’t understand the issue. You expect nothing to happen so what is happening? Why are waypoints relevant? What are you actually doing?

Sorry. In older versions of sevtech, you can create waypoint just by shift+rmb on samples.

**Comment by sam-kirby** [comment]
I didn't know you could do this, but I've just tried it in SevTech 3.1.2 and it creates a waypoint in JourneyMap. Seems to be a feature of Geolosys, and does not require, nor have, any configuration.
