### ISSUE TITLE
Unplayable Crashing

### ISSUE THREAD

**Issue by cn112371** [DarkPacks/SevTech-Ages#3986]
Hey All,

Not sure if anyone else has had this problem or not I couldn't find anything quite like it in the posts.

I have been able to progress a bit of the way through the beginning of the pack however, it seems that when I am trying to travel away from my spawn location (to find the darklands) then my game crashes completely. I unfortunately don't have a crash report.

When it crashes the following happens:

World stops loading (F3+a) does not reload chunks

Mobs stop moving and cannot be interacted with - including passive mobs they freeze in place and cannot be hit

I can still break blocks within the chunks that have already loaded however no items will drop. I have attempted to see if the game would resolve the issue itself however the game eventually crashes to desktop.

Fixes attempted:

Allocate RAM - A LOT MORE RAM. Like 8 GB+
Go a different direction - Same result
Uninstall - Reinstall Mod via Twitch - Nada, zilch, zero

This pack seems extremely fun and I would love to play it however every time I try to venture out and explore the game crashes. Any help would be greatly appreciated!

**Comment by cn112371** [comment]
Also game will crash every time I try to save and quite to menu.

**Comment by sam-kirby** [comment]
Please follow the issue template. In this particular case, your world seed would be useful as well.
