### ISSUE TITLE
Age 2: Flame Grilled Wopper crafting not working.

### ISSUE THREAD

**Issue by iosonoagenda** [DarkPacks/SevTech-Ages#3987]
## Bug Report

Simply trying to craft a Flame Grilled Wopper with an hopper and a lavawood in crafting station, will not work (in age 2).

## Expected Behaviour

- Place an hopper and lavawood in crafting station
- see as result a Flame Grilled Wopper

## Possible Solution

- trying to reload the server, but nothing changed.
- idk how, maybe re-apply recipes (?)

## Steps to Reproduce (for bugs)

1. Craft an hopper
2. Craft a lavawood
3. place those items in crafting station (shapless)
4. nothing appear as result

## Client Information

* Modpack Version: 3.1.2 Hotfix 1
* Java Version: OpenJDK 11.0.5-ea
* Launcher Used: MultiMC 5 for Ubuntu
* Memory Allocated: 4096 - 6144 MB
* Server/LAN/Single Player: server
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.1.2 Hotfix 1

* Additional Content Installed: nothing

## Server Information
* Java Version: Oracle Java 1.8.0_221
* Operating System: Ubuntu Server 19.10
* Hoster/Hosting Solution: server on local network
* Sponge (Non-Vanilla Forge) Server: forge-1.12.2-14.23.5.2838-universal

**Comment by Azrazal** [comment]
even though it says shapeless, i found that it works if the lavawood is above the mk2 wopper

**Comment by iosonoagenda** [comment]
You're right! Thanks a lot!
