### ISSUE TITLE
Rock Crystals not splitting

### ISSUE THREAD

**Issue by irondragon12** [DarkPacks/SevTech-Ages#3988]
## Expected Behaviour

so i put a rock crystal with 400 size 81 purity & 100 cutting and put it in liquid starlight and have repeated it about 20 or more times and it isnt splitting into two too up its purity.

* Modpack Version: 3.1.2 hotfix 1
* Java Version: idk but prob latest
* Launcher Used: AT Launcher
* Memory Allocated: MAX 8,192
* Server/LAN/Single Player: singleplayer
* Optifine Installed: no
* Shaders Enabled: no

## World Information

i really have no clue. so srry.

**Comment by sam-kirby** [comment]
There is only a 1/7 chance of a split. The chance of having 20 in a row not split is nearly 5%. This is unlucky, but probably just RNG.
