### ISSUE TITLE
Game crashes upon startup

### ISSUE THREAD

**Issue by DogeMaster03** [DarkPacks/SevTech-Ages#3993]
## Bug Report

The title says it all. If you are not convinced by the title, I wanted to play sevtech, I started the game and it crashed upon startup. please fix your game!

## Expected Behaviour

The game starts up without crashing
## Steps to Reproduce (for bugs)

1. Start the modpack in the launcher
2.

## Logs

* Client/Server Log: https://pastebin.com/Rf6FEnRH
* Crash Log: 

## Client Information

* Modpack Version: 3.1.2 Hotfix
* Java Version: 8
* Launcher Used: 
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed:

**Comment by sam-kirby** [comment]
Suggest you try installing a fresh profile instead of using Twitch's upgrade path as it keeps forgetting to remove mods. If that doesn't work please include a full log.

**Comment by DogeMaster03** [comment]
Thanks for the help! I used ATLauncher instead, and that worked
