### ISSUE TITLE
SevTech: Ages to Load. The modpack is taking literally an hour (or more) to load.

### ISSUE THREAD

**Issue by lucasrattz** [DarkPacks/SevTech-Ages#3994]
The modpack is taking too long to load, mostly stuck on 4/7 and when i join a server/world, most likely it will stop working and either takes another age to load or close the proccess at least 1 time.

* Modpack Version: 3.1.2 Hotfix 1
* Java Version: 8 (build 1.8.0_221-b11)
* Launcher Used: ATLauncher
* Memory Allocated: 7680MB
* Server/LAN/Single Player: Server/Single Player
* Optifine Installed: No
* Shaders Enabled: No
* CPU: Ryzen 5 1600
* Memory: 1x8 DDR4 2400MHZ
* GPU: GTX 1060 6GB

Is there any way to reduce the loading time?

**Comment by sam-kirby** [comment]
With only 8GB of available system memory you cannot use 7.7GB on a modpack.

Assuming you're using Windows, the OS needs approximately 2GB to itself or the RAM assigned to the modpack will end up in a page file (a special file on hard disk that acts like RAM but is much much slower). 

Try running with 5-6GB assigned to the pack, and make sure to use the arguments given on the wiki to optimise the garbage collector: https://github.com/DarkPacks/SevTech-Ages/wiki/Recommended-Java-Args

Run as few background programs as possible, avoid web browsers as they are generally very memory intensive.
