### ISSUE TITLE
Core sample icon is invisible

### ISSUE THREAD

**Issue by SvenVM** [DarkPacks/SevTech-Ages#3995]
My core samples resulting from my Core Sample Drill are invisible in my inventory. Remains invisible even with no resourcepacks.
I'm on V 3.1.2 hotfix1
![image](https://user-images.githubusercontent.com/32305149/69482889-3094f700-0e21-11ea-9517-9dabff1e7161.png)

**Comment by sam-kirby** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
