### ISSUE TITLE
Crash on play

### ISSUE THREAD

**Issue by Taje01taje** [DarkPacks/SevTech-Ages#3998]
# Bug Report

## Expected Behaviour
Every time I hit play on the launcher (Jar or native) the game immediately crashes, no special circumstances I can see

## Steps to Reproduce (for bugs)
No clue. Just ran the game and it immediately failed to launch.

## Logs
* Launcher Log: https://pastebin.com/eahNMZKy
* Crash Log:https://pastebin.com/bAgPAuZ9

## Client Information
* Modpack Version: 3.1.2 Hotfix 1
* Java Version: 1.8.0.181 64-bit
* Launcher Used: Either
* Memory Allocated: 9216 MB
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: N/A
* Additional Content Installed: None

**Comment by sam-kirby** [comment]
You have more than one of the same mod installed. Both astral sorcery 1.8.5 and 1.10.19 are trying to load, though the game is most likely crashing due to multiple BNB core mods being present.

Please make a clean profile and try again. Twitch may have failed to clean up properly when updating.
