### ISSUE TITLE
My Friend is getting a internal server error when they try to connect to my ser

### ISSUE THREAD

**Issue by TheDeadlyOctopus** [DarkPacks/SevTech-Ages#4000]
## Bug Report

Whenever they try to connect to my server they get the error "attempting connection with missing mods [antiqueatlasoverlay, betteradvancements, betterfoliage, clienttweaks, colouredtooltips, controlling, ctgui, ctm, custommainmenu, defaultoptions, enchdesc, fbp, jmapstages, justenoughpetroleum, moreoverlays, mousetweaks, neat, norecipebook, pdp, resourceloader, smoothfont, tips, tipthescales, toastcontrol, reauth] at **SERVER" but all of those are client side mods**

## Expected Behaviour

they would connect

## Possible Solution

unknown

## Steps to Reproduce (for bugs)

1.try to connect to my server on mac os with java 1.8
2. get booted and get a internal server error

## Logs

* Client/Server Log: for server it says "lost connection internal server error" for client it says "attempting connection with missing mods [antiqueatlasoverlay, betteradvancements, betterfoliage, clienttweaks, colouredtooltips, controlling, ctgui, ctm, custommainmenu, defaultoptions, enchdesc, fbp, jmapstages, justenoughpetroleum, moreoverlays, mousetweaks, neat, norecipebook, pdp, resourceloader, smoothfont, tips, tipthescales, toastcontrol, reauth] at SERVER"
* Crash Log:

## Client Information

* Modpack Version: 3.1.2 Hotfix 1
* Java Version: 1.8.0.231
* Launcher Used: twitch
* Memory Allocated: 10 GB
* Server/LAN/Single Player: server
* Optifine Installed: no
* Shaders Enabled: no

## World Information
 3.1.2 hotfix 1
* Modpack Version world created in: 3.1.2 hotfix 1

* Additional Content Installed: nope

## Server Information
* Java Version: 1.8.0.213
* Operating System: linux (ubuntu no graphics)
* Hoster/Hosting Solution: my old pc
* Sponge (Non-Vanilla Forge) Server: nope just the server files

**Comment by sam-kirby** [comment]
The only included line from the log is normal. The server hasn't loaded client only mods, for obvious reasons, so they are missing. Suggest you check an extended timeout is set on both the server and client, see [here](https://github.com/DarkPacks/SevTech-Ages/wiki/Read-Timeout-Exception).
