### ISSUE TITLE
Game won't load after updating modpack

### ISSUE THREAD

**Issue by Cifer98** [DarkPacks/SevTech-Ages#4002]
## Bug Report
After updating the Sevtech ages modpack from version 3.0.8 to 3.1.0 the client when launching gets hung up and never finishes loading the spawn area.
## Expected Behaviour
The client should be loading the spawn area fine.

## Possible Solution
My guess might be that it could be something in the world that isn't compatible with the new update , ie a block or structure that can't transfer over to the new version. 

## Steps to Reproduce (for bugs)

1.Create a world in version 3.0.8
2.Progress the world to Age 4
3.Update world to 3.1.0

## Logs
* Client/Server Log:https://gist.github.com/Cifer98/3db449fb5a0cb1f1ecde7be4b7abb3bb
* Crash Log: 

## Client Information

* Modpack Version:3.1.0
* Java Version:1.8.0_231
* Launcher Used: Multi MC
* Memory Allocated: 10 Gb
* Server/LAN/Single Player: Single Player
* Optifine Installed:no
* Shaders Enabled:no

## World Information

* Modpack Version world created in:3.0.8
* Additional Content Installed:

**Comment by sam-kirby** [comment]
Why is your log from v3.1.0?

**Comment by Cifer98** [comment]
Sorry that was a mistake on my part the version I updated it to should be 3.1.0 not 3.1.2
