### ISSUE TITLE
Sevtech Ages crashes after updating IE to 0.12-92

### ISSUE THREAD

**Issue by raggaeshark** [DarkPacks/SevTech-Ages#4007]
## Bug Report
SevTech Ages crashes while loading after I updated Immersive Engineering from 0.12-89 to 0.12-92

## Steps to Reproduce (for bugs)
1. Insert latest IE version into Sevteg Ages` modsfolder.
2. Launch SevTech Ages

## Logs
* Crash Log: https://pastebin.com/2HszE00w

## Client Information
* Modpack Version: 3.1.2_Hotfix_1
* Java Version: 8 Update 231
* Launcher Used: ATLauncher
* Memory Allocated: 14 GB
* Server/LAN/Single Player: Single Player
* Optifine Installed:
* Shaders Enabled: no

## World Information
* Modpack Version world created in: 3.1.2_Hotfix_1
* Additional Content Installed: none

**Comment by sam-kirby** [comment]
We do not support modifications to the pack; successfully launching the game will not be the end of issues here.
