### ISSUE TITLE
Advanced Storage Remote Glitching

### ISSUE THREAD

**Issue by irondragon12** [DarkPacks/SevTech-Ages#4012]
when using the advanced storage remote in other dimensions it glitches and show a blank screen even tho it says it work cross dimensions and it does work sometimes.

## Possible Solution
the only solution is killing myself or reloging every time i want to use it.

## Steps to Reproduce (for bugs)

1. setup simple storage network system
2.get advanced storage remote 
3. open in multiple dimensions to test

## Client Information
* Modpack Version: 3.1.2_Hotfix_1
* Java Version: window 10
* Launcher Used: atlauncher
* Memory Allocated: 8,192 ram
* Server/LAN/Single Player: singleplayer
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in: maybe 1 version under current or just current version

**Comment by sam-kirby** [comment]
By blank, do you mean it appears the same as in this issue: Lothrazar/Storage-Network#239?

**Comment by irondragon12** [comment]
ya pretty much the same i guess. i guess i didnt see that one.

**Comment by irondragon12** [comment]
so there isnt a fix on that page?

**Comment by sam-kirby** [comment]
Can you please provide the entirety of `latest.log`?

**Comment by sam-kirby** [comment]
Closing as nothing to go on.
