### ISSUE TITLE
Lead disapearing when returning from hunting dimension

### ISSUE THREAD

**Issue by MrWickedways** [DarkPacks/SevTech-Ages#4016]
If you have any type of animal tied up to a horse press, grinder or wood cutter, when returning from the hunting dimension the leads will be gone and your animals no more tied up to the machines, :q

**Comment by sam-kirby** [comment]
This is only true if the animal is in a different chunk from the thing the lead is tied to. If you avoid leads crossing chunk borders, this isn't an issue. Pressing F9 will show you where the chunk borders are.

This is an issue stemming from how leads are implemented in vanilla minecraft, and you can do much the same thing without mods using an animal tied to a fence post and a nether portal.
