### ISSUE TITLE
Blood Magic - Hellfire Forge Doesn't seem to work

### ISSUE THREAD

**Issue by Stone19298** [DarkPacks/SevTech-Ages#4017]
![Screenshot (17)](https://user-images.githubusercontent.com/59383078/71610669-a98e1980-2b58-11ea-82d5-0059aec3fce7.png)

I've tried a bunch of random things and been following recipes, please help!

**Comment by Frikkle** [comment]
I have successfully used the HellFire Forge yesterday in SevTech: Ages. Just note that the recipes are heavily modified and that the in-game books do not (always) reflect the changed recipes. So, for recipe consulation, use JEI.
