### ISSUE TITLE
Sevtech won't open

### ISSUE THREAD

**Issue by n00bslayer08** [DarkPacks/SevTech-Ages#4018]
## Bug Report
I just got a new computer and when I downloaded Sevtech and tried to play, and error pops up and I am unable to play.

## Expected Behaviour
That the game would open without an error.

## Possible Solution
That's why I'm here.
## Steps to Reproduce (for bugs)
No clue.

## Logs
I don't know how to find the logs but this is what the error tells me.
https://pastebin.com/38YGQ7Bb

## Client Information

* Modpack Version: 3.1.2 Hotfix 1
* Java Version: Java 1.8.0.51 (64 Bit)
* Launcher Used: Native Launcher
* Memory Allocated: 5888 MB
* Server/LAN/Single Player: Singleplayer/Server
* Optifine Installed: None
* Shaders Enabled: No

## World Information
No world created.

**Comment by sam-kirby** [comment]
See #4014
