### ISSUE TITLE
Game files "differ from what was expected", preventing load

### ISSUE THREAD

**Issue by plolil** [DarkPacks/SevTech-Ages#4019]
![image](https://user-images.githubusercontent.com/55294289/71640363-5ca56280-2c80-11ea-8d94-b9544120b55f.png)
This is the message I get when I try to load the game.
It was distributed on twitch, and I downloaded it and clicked play, and the above error repeatedly shows up whenever I press "play"

**Comment by plolil** [comment]
Never mind, is an issue with Twitch

**Comment by sam-kirby** [comment]
See #4014 for solutions if you haven't already.
