### ISSUE TITLE
Wooden Axle 2nd recipe broken

### ISSUE THREAD

**Issue by borg286** [DarkPacks/SevTech-Ages#4020]
# Bug Report
Recipe for Wooden axle involving Moulding rather than black quartz imports into the crafting grid, but the output (wooden axle) doesn't show up

## Expected Behaviour
Normally the wooden axle appears on the right of the crafting grid.

## Steps to Reproduce (for bugs)
Have oak moulding and Hemp rope in your inventory.
Click the + to pull the items into the crafting grid.
Sadly no wooden axle shows up

## Client Information
* Modpack Version: 3.1.2-hotfix.1
* Java Version: 11.04
* Launcher Used: MultiMC 5
* Memory Allocated: Plenty
* Server/LAN/Single Player: LAN
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in:3.1.2-hotfix.1
* Additional Content Installed: TestDummy Mod

**Comment by sam-kirby** [comment]
See here: https://github.com/DarkPacks/SevTech-Ages/issues/3991#issuecomment-552795779

**Comment by sam-kirby** [comment]
Note you can also fix this by updating recipe stages by one version.
