### ISSUE TITLE
viescraft airship does not trigger the age3 "Flight!" advancement

### ISSUE THREAD

**Issue by Dutchs** [DarkPacks/SevTech-Ages#4021]
## Bug Report
The crafted airship has a metadata value of 0, while the script checks for metadata 1-4, causing the advancement to not trigger.
(./config/triumph/script/triumph/stage3/viescraft.txt)

## Client Information
* Modpack Version: 3.1.2-hotfix.1

**Comment by abadger** [comment]
I saw this earlier today while looking for a different issue.  It could be fixed by allowing metadata of zero or by changing the description of the advancement to specify that a core upgrade needs to be installed (and the airship picked back up?)
