### ISSUE TITLE
Every time I now try to log into my sevtech world it crashes right away.

### ISSUE THREAD

**Issue by soulfoood** [DarkPacks/SevTech-Ages#4025]
The last thing I remember doing was exploring the world on my horse, then it crashed. I had to go to work so when I got on it today it was doing the same thing. I'm not super familiar with crash reports and how to troubleshoot when there is a ton of mods being loaded. Any feedback would be appreciated.

Here is crash report:

https://pastebin.com/Bej7wd8r

**Comment by FREDYFREDBOB** [comment]
I'm having the same problem in age 1. My friend went to an area I had just been to the day before to get some horses and now he cant log in without crashing the server so I tried to load the chunks and now it crashes when I join as well.
