### ISSUE TITLE
Automatic Crafter from Inductive Logistics is Broken

### ISSUE THREAD

**Issue by Bobmarlinjr** [DarkPacks/SevTech-Ages#4030]
## Bug Report

The Automatic Crafter from Inductive Logistics does not take melon blocks from an adjacent inventory and craft them into melons.

## Expected Behaviour

The crafter should automatically craft said items in the correct manner. 

## Steps to Reproduce (for bugs)

1. Place down a crafter
2.place a chest on the north side of the crafter
3. Set the top left slot in the crafter GUI to NORTH
4. Set the items to craft in the GUI to 1

## Logs

N/A
## Client Information

* Modpack Version: most recent
* Java Version:
* Launcher Used: AT launcher
* Memory Allocated: 4092 mb
* Server/LAN/Single Player: single player
* Optifine Installed: yes
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 

* Additional Content Installed: dynamic trees, newest versions on inductive logistics and respective library mod

**Comment by sam-kirby** [comment]
![Screenshot 2020-01-09 at 01 08 12](https://user-images.githubusercontent.com/23245543/72029036-85c78380-327c-11ea-9239-504acc7261db.png)

This is why we emphasise over and over that "latest" or "most recent" are not a substitute for version numbers. This bug has been fixed in 3.1.2.
