### ISSUE TITLE
Glitches

### ISSUE THREAD

**Issue by username1233213** [DarkPacks/SevTech-Ages#4031]
I'm at age 0, I can't break blocks from one direction, the mobs are having spasms/seizures, sometimes I start running too fast for some reason (sometimes I'm so fast that I teleport like 100 blocks away by lightly pressing w). Had none of these problems yesterday, no clue why it just started now. I don't have Optifine installed and I use the Taylors algorithm from betterfps.

**Comment by Espergium** [comment]
Use riven's half. Do not touch the algorithm please.
