### ISSUE TITLE
game crashes while finalizing Modpack Intialization

### ISSUE THREAD

**Issue by Th3Ma3lstrom** [DarkPacks/SevTech-Ages#4040]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by Th3Ma3lstrom** [comment]
[crash-2020-01-30_13.12.03-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/4136382/crash-2020-01-30_13.12.03-client.txt)

**Comment by sam-kirby** [comment]
Needs more RAM.
