### ISSUE TITLE
Moving near high mountain cause game no response , but haven't crash

### ISSUE THREAD

**Issue by SANagisa** [DarkPacks/SevTech-Ages#4041]
## Bug Report

Exploring near a chuck and the world stops response ( entity don't move , can't take on/off boat , can't using command, etc. ).
Trying to save and quit the world will cause the game (or program) stops reseponse (then windows will ask whether close it or not).

## Expected Behaviour

Expected the game would response normally.

## Possible Solution

No.

## Steps to Reproduce (for bugs)
1. Enter the world (I'm using world with seed 1638846215)
2. Come close to a chunk (In the seed it located in the south of spawnpoint) (And the log remind a chunk
3. No response
(If needed, I can provide a video as it's repeatable)

## Logs
* Client/Server Log: https://paste.ee/p/2vC7E#section1
MultiMC Log :https://paste.ee/p/2vC7E#section0
(The world stop generating log after I close to the chunk)
* Crash Log: No crash log

## Client Information
* Modpack Version: 3.1.2-hotfix.1
* Java Version: 1.8.0_211
* Launcher Used: MultiMC
* Memory Allocated: 16384MB
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.1.2-hotfix.1
* Additional Content Installed: No

**Comment by sam-kirby** [comment]
Could you please try updating the Streams mod to 0.4.8 to see if this resolves this hang?

https://www.curseforge.com/minecraft/mc-mods/streams/files/2861235

**Comment by SANagisa** [comment]
> Could you please try updating the Streams mod to 0.4.8 to see if this resolves this hang?
> 
> https://www.curseforge.com/minecraft/mc-mods/streams/files/2861235

Oh thanks, it works normal now
