### ISSUE TITLE
Opening Sigil of Holding

### ISSUE THREAD

**Issue by jackfrost0** [DarkPacks/SevTech-Ages#4042]
I just crafted the Sigil of Holding, but when I press H nothing happens. It says that I am the owner, and I confirmed the keybind, but it just doesn't respond when I press H.

**Comment by sam-kirby** [comment]
Make sure you unbind anything that might conflict.

**Comment by jackfrost0** [comment]
I did, I even put it on a mousebutton that I am more than positive has no conflicts.

**Comment by jackfrost0** [comment]
Oh, I see the bot reply. I'll try the discord.
