### ISSUE TITLE
SevTech Ages Golden Chest crash

### ISSUE THREAD

**Issue by Peckun** [DarkPacks/SevTech-Ages#4044]
## Bug Report

I was playing normally until i decided to chuck in optifine to boost my fps and possibly try out some shaders for the modpack and also removing smooth font and foliage to boost it even more, (I couldnt since i always crashed when i tried to). After that I continued playing normally until I attempted to open the golden chest that was near my smeltry and had all of my ores, which froze up my game and crashed it. I had two golden chests stacked on each other and both crashed me after test.

## Expected Behaviour

It just crashes you outright
## Possible Solution

I have no idea.
## Steps to Reproduce (for bugs)

1.Simply try to open the chest.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/LVX586UL

## Client Information

* Modpack Version: 3.1.2 Hotfix 1
* Java Version: Version 8 Update 201
* Launcher Used: Twitch
* Memory Allocated: 4769
* Server/LAN/Single Player: Server
* Optifine Installed: Yes
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.1.2 Hotfix 1

* Additional Content Installed: Optifine

**Comment by sam-kirby** [comment]
Can you attach a screenshot of the golden chest/blocks around it please?

**Comment by sam-kirby** [comment]
Things to note:
* The version of Optifine used is very old (C5 - released in 2017)
* You're not using the version of Java you expect, you are in fact using 1.8.0_51 - released in 2015

Could you please use updated versions of both of these?

**Comment by Peckun** [comment]
Update: Any chests from the IronChests mod crashes me

Okay i'll update the following, ill give a heads up later if anything changes

**Comment by Peckun** [comment]
Update: 
Ive updated both and it stopped the crash, But im going to make a big guess here that its the old optifine version. 

Thanks )/
