### ISSUE TITLE
Problem with ATLauncher and the Curse / Twitch app on the SevTech 3.1.2 package

### ISSUE THREAD

**Issue by Gabri404** [DarkPacks/SevTech-Ages#4045]
I read from your changelog that you have solved Sevtech Ages 3.1.2 problems

Unfortunately I have not seen any updates from the ATLauncher client and Curse / TwitchApp

I was wondering if you can get started, a zip (server side and client side of 3.1.3). My users are blocked from crafting the Scamulator blueprint, and have several problems with NEI recipes. I read the changelog and you tell them that these things are solved. Therefore I ask you this courtesy. Since the entities mentioned have not released an update, always admitting that there is.

I thank you for reading me.
I await your news

**Comment by sam-kirby** [comment]
First, the scamulator can be used without its blueprint.

Second, 3.1.3 is not yet ready for release. You can see the progress here: https://github.com/DarkPacks/SevTech-Ages/milestone/8

**Comment by Gabri404** [comment]
I understand, thank you for replying.
