### ISSUE TITLE
I cant find a swamp or jungle biome in sevtech ages i went in all directions more than 1000 blocks away this quest is from the man quests i cant  continue with out it

### ISSUE THREAD

**Issue by MahmoudTDS** [DarkPacks/SevTech-Ages#4047]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
It sounds like you've just gone in straight lines along the x and z axes. With the way the world is setup, it is entirely possible you'd miss the biomes you're looking for. See here for more information: https://sevtechages.gamepedia.com/Heatmap

Determine which humidity and temperature bands you are in, and move based on that.

Alternatively, if you're fed up of exploration you can just cheat using the command e.g. `/findbiome minecraft:swampland` which will teleport you there.

In the future, please use the discord for help requests.
