### ISSUE TITLE
Crashed on first start up

### ISSUE THREAD

**Issue by McDoodlee** [DarkPacks/SevTech-Ages#4048]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

This upon the first start up of SevTech

Can anyone help?

**Comment by sam-kirby** [comment]
Can you please upload the crash report generated as a result of this crash to pastebin or similar. Without it there isn't really a way to determine why the game is crashing.

## Twitch
1. Select the SevTech Pack to view the modpack page.
2. Click the `...` button on the top right just next to `Get More Content`.
3. Click `Open Folder`.
4. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it. 

## ATLauncher
1. Select the Instances tab, then scroll to the instance of SevTech.
2. Click the bottom right button named `Open Folder`
3. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it.

For any other launcher should be a similar process, if not consult with Google if you are not sure on how to find the folder. The information contained in these reports is critical for getting the crash fixed/looked into.

## Servers
For servers, the process is fairly simple. Go the folder containing all the server files/folder and you will see a folder called `crash-reports` follow the same process as above by getting the latest one and uploading it to a text store.
