### ISSUE TITLE
Multitypes pipes

### ISSUE THREAD

**Issue by 6elkir** [DarkPacks/SevTech-Ages#4055]
## Context
For the full automation of crafting, there is not enough of any object that can transfer several liquids and objects through itself. It is recommended to find such a mod)

**Comment by sam-kirby** [comment]
XNet is in the pack.

**Comment by 6elkir** [comment]
XNet does not allow to do this = \

**Comment by sam-kirby** [comment]
Then perhaps I am misunderstanding what you are trying to do, can you give an example of a mod that does what you want or a more detailed explanation of what you want to do?

**Comment by 6elkir** [comment]
For example, we have various multi-unit mechanisms that receive liquids and objects at the entrance (for example, a hydraulic press: grease + metal). Without crutches, the necessary items cannot be transferred to it through the crater from refined storage. EnderIO would solve this problem, but I know that it is not in your assembly and I saw your answer where you refused to use it. Now I have to pervert through hopper to collect experience%)
