### ISSUE TITLE
Diesel Generator is not accepting Diesel as fuel source (IE and IP)

### ISSUE THREAD

**Issue by sp00ne** [DarkPacks/SevTech-Ages#4056]
## Bug Report
When using the Diesel Generator, it doesn't accept Diesel as fuel source.

## Expected Behaviour
We expect that it can be fed Diesel (Immersive Petroleum) as well as Biodiesel (Immersive Engineering). 

## Possible Solution
Make it possible for the Diesel Generator to accept Diesel as a fuel source.

## Steps to Reproduce (for bugs)
1) Create Diesel Generator (Immersive Engineering)
2) Setup Fluid Pipes (Immersive Engineering)

Choose 1:
3a) Hook up Liquid Hopper (Pneumatic Craft: Repressurized) with Diesel inside its tank to the input of the Diesel Generator
3b) Hook up Refinery (Immersive Engineering) to the Diesel Generator through fluid pipes

4) Watch as the Diesel Generator is dead

## Logs
Not relevant

## Client Information

* Modpack Version: 3.1.2
* Java Version: Unknown
* Launcher Used: Twitch Launcher (Forge?)
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.1.2

**Comment by sam-kirby** [comment]
I am unable to recreate this issue. The Diesel Generator functions with both IP Diesel and IE Biodiesel.

![2020-02-28_01 10 10](https://user-images.githubusercontent.com/23245543/75501235-4c330f00-59c7-11ea-9886-b01c1f91fd73.png)

I'm not entirely sure what your specific issue is, maybe you could attach a screenshot? Additionally, you will receive generally faster support on the Discord. Use the #sevtech-gameplay channel.

https://discord.gg/darkosto

**Comment by sp00ne** [comment]
The setup above is not truly reproducing the issue though. I see you are using other tools to pipe the fuel? Is your modpack running 3.1.2? I will see if I can get a screenshot

**Comment by sam-kirby** [comment]
The setup above does not reproduce the issue at all, this is why I tagged the issue as "Cannot Reproduce".

Obviously, when trying to reproduce bugs I do use the same version of the pack as they were reported as being present in. For the avoidance of doubt, I am using a clean 3.1.2 install.

You stated that you could not use diesel or biodiesel to fuel the generator, seemingly irrespective of the mechanism used to pipe it in. You did not, for example, say that you could not insert diesel/biodiesel using fluid pipes from IE but other pipes worked, therefore I assumed it to be irrelevant and grabbed the first pipe I came across in JEI. Nevertheless, I note you did give two examples in your steps to reproduce, and so I gave both of these a try just now as well as just testing with an IE tank of diesel. All work, as demonstrated in the screenshots below.

![2020-02-29_23 46 54](https://user-images.githubusercontent.com/23245543/75616817-06ed1980-5b4e-11ea-98c5-0a20f5d03c1f.png)

![2020-02-29_23 54 17](https://user-images.githubusercontent.com/23245543/75616892-fab58c00-5b4e-11ea-8585-003df139939b.png)
