### ISSUE TITLE
Crash when loading save

### ISSUE THREAD

**Issue by Degenerecy** [DarkPacks/SevTech-Ages#4059]
Ver:  Sevtech Version 3.1.2 Hotfix 1

Desc:  Crash when loading world, happened randomly in game but now more consistent when loading world.  As well as more frequent in-game.

Happened only when I got to Age 5.

Crash Log:  Last 4 Attached.

[crash-2020-02-24_18.31.01-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/4247827/crash-2020-02-24_18.31.01-server.txt)
[crash-2020-02-24_15.14.54-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/4247829/crash-2020-02-24_15.14.54-server.txt)
[crash-2020-02-24_13.54.05-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/4247830/crash-2020-02-24_13.54.05-server.txt)
[crash-2020-02-24_00.57.53-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/4247831/crash-2020-02-24_00.57.53-server.txt)

Update:  Hasn't happened since.  Will keep playing to see if it happens again.

**Comment by sam-kirby** [comment]
Going to close this as update makes it sound as though this was resolved.
