### ISSUE TITLE
immersive engineering machines disappear , multiply

### ISSUE THREAD

**Issue by TheEvil014** [DarkPacks/SevTech-Ages#4061]
## Bug Report
Immersive engineering machine some of them disappear and some multiply in the same block  i sill can use them but it's annoying , 

## Expected Behaviour
it should look normal >,<  .-. 

## Possible Solution
i think the chunk corrupted cause i've built it using projector
i've tried to build the machines in other chunk without using projector it did work and didn't glitch
and i've tried to rebuild the machines in the same corrupted chunck without using projector it gave same result

## Steps to Reproduce (for bugs)

1. https://i.imgur.com/rtG4dde.jpg
2. https://i.imgur.com/5cZwjOO.png
2. https://i.imgur.com/RXwzEps.png

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.1.2 Hotfix 1
* Java Version: java 8 update 241 (64 bit)
* Launcher Used: twitch 
* Memory Allocated: 8gb
* Server/LAN/Single Player: single player
* Optifine Installed: yes
* Shaders Enabled: no

## World Information

* Modpack Version world created in: minecraft .-.

* Additional Content Installed: optifine

**Comment by sam-kirby** [comment]
What BetterFPS algorithm are you using?
