### ISSUE TITLE
EFLN still in the pack / not working

### ISSUE THREAD

**Issue by alexw-at** [DarkPacks/SevTech-Ages#4062]
## Bug Report
EFLN destroys ore and only drops Cobblestone despite being "safe for mining" in version 3.1.2 Hotfix 1

## Expected Behaviour
It should drop the ore

## Possible Solution
Make EFLN drop ore when thrown
or remove EFLN from the pack (suggested at https://github.com/DarkPacks/SevTech-Ages/issues/721)

## Steps to Reproduce (for bugs)

1. Throw EFLN at ore
2. Only get Cobblestone

**Comment by sam-kirby** [comment]
There's no way it will ever drop ores as it is not possible to determine who caused an explosion, and thus what age they are in.

It appears to have been hidden from JEI search but is still craftable; perhaps some players consider it useful for creating massive holes speedily? As previously noted, we can't easily alter the tooltip.

The current situation may well be the best balance.

**Comment by justinrusso** [comment]
It looks like the intent was to remove it based on #721 but appears like it never was.
