### ISSUE TITLE
incompatibility on AMD cards?

### ISSUE THREAD

**Issue by CleberPCB** [DarkPacks/SevTech-Ages#4063]
hello, im having some massive lag here on my RX 580 8GB, there's something that i can do?
![Screenshot_2867](https://user-images.githubusercontent.com/61630420/75612036-ad113300-5afe-11ea-8293-360237b7139c.png)

**Comment by sam-kirby** [comment]
I recommend you update the pack to version 3.1.2.

3.0.8 required a config change to run on AMD cards, and I don't remember what it was. You might be able to find it on the Discord.
