### ISSUE TITLE
would you know have to fix an issue with it? I've made it to age 3, Advancements tab has updated but the world has not regenerated to expose new ores and recipes any suggestions??

### ISSUE THREAD

**Issue by Elderwolf569** [DarkPacks/SevTech-Ages#4065]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by Elderwolf569** [comment]
would you know have to fix an issue with it? I've made it to age 3, Advancements tab has updated but the world has not regenerated to expose new ores and recipes any suggestions??

**Comment by sam-kirby** [comment]
Run each of the following commands:

`/gamestage add @p three`
`/gamestage add @p three_mob`
`/gamestage remove @p two_mob`

**Comment by Elderwolf569** [comment]
tried what you said, it's telling me I do not have the permission


Sent from Windows Mail

**Comment by Elderwolf569** [comment]
to prove that I unlocked the tab but it says I do not have the permission to run the commands you stated


Thanks
Chris Maynard
Sent from Windows Mail
