### ISSUE TITLE
Server Crash Report on Host

### ISSUE THREAD

**Issue by HomelessB** [DarkPacks/SevTech-Ages#4067]
I installed SevTech: Ages Server Files (pack), but nothing works when starting the server
[crash-2020-03-05_13.25.22-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/4292420/crash-2020-03-05_13.25.22-server.txt)
[latest.log](https://github.com/DarkPacks/SevTech-Ages/files/4292422/latest.log)
Please help me :)

**Comment by sam-kirby** [comment]
We do not support modified versions of the pack.

**Comment by sam-kirby** [comment]
More information; you're using a more recent version of Forge than the version included in SevTech Ages 3.1.2 (the latest version released at time of writing), yet you are also using a version of Immersive Engineering from 2018 that is incompatible with new versions of Forge.

This was resolved in 2018; more details here: BluSunrize/ImmersiveEngineering#3241

Please only use the server pack downloaded from Curseforge at the following link: https://www.curseforge.com/minecraft/modpacks/sevtech-ages/files/2752765
