### ISSUE TITLE
Can't update/install the modpack via twitch

### ISSUE THREAD

**Issue by Pe4enie** [DarkPacks/SevTech-Ages#4068]
Hey there,

couldn't find an open issue about that. Didn't play for a while and wanted to update the modpack, which resulted in a popup with a message
"This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 242638"

Removed the modpack completely to re-install it from scratch, but I get the same message even when trying to install a fresh one.

Best Regards

**Comment by sam-kirby** [comment]
That's a Twitch issue, it usually sorts itself so try again in a few hours.

Otherwise you can use MultiMC or ATLauncher to install the pack.

If you need any more help getting the pack setup please use the appropriate channel on Discord.
