### ISSUE TITLE
JEI Not Item Hiding

### ISSUE THREAD

**Issue by StealthM23** [DarkPacks/SevTech-Ages#4079]
## Bug Report
JEI is not hiding items from outside of my current age. Even completely reverting and revoking all stage advancements through:
/gamestage clear PlayerName
/advancement revoke playerName everything
/advancement grant playerName only triumph:stage0/root
It doesn't fix the item hiding issue.
Also, as all JEI items are unhidden, all rock samples have become samples from Ages that are not yet reached, for example I can see Kimberlite which gives diamonds in Age 0.
As this was on a server, I tried de-opping to see if that would help, it did not.
## Expected Behaviour
Items from Ages 3 and higher should be hidden as I was in Age 2, similarly all items above Age 0 should be hidden when completely reverting progress in the pack.

## Possible Solution
Possibly a file needs to be edited or deleted to force a change of the JEI item hiding back to normal? Restarting pack and launcher doesn't seem to fix it.

## Steps to Reproduce (for bugs)

1.Start game, open JEi with E button. 
2.Note that all recipes are unhidden.
3.Explore world, note that all supposed "unknown" items are known now.

## Logs

Client(https://gist.github.com/StealthM23/83124181e220d501c88003cda4e31af4)
Server(https://gist.github.com/StealthM23/95c0d0102a68b99a2802f199b66c1d96)
CraftTweaker(https://gist.github.com/StealthM23/37b7f993b53b08b089865854c2caa587)
CraftTweakerServer(https://gist.github.com/StealthM23/be2d98c826a4cb157865c3971b5e2f7d)
## Client Information

* Modpack Version: SevTech Ages 3.1.2 With a couple additional mods, while I know that those are not supposed to be hidden (as they are not originally in the pack) they always were shown but the remainder of the still original mods that should have been hidden were, until yesterday when this bug started to occur.
* Java Version:1.8.0.241(64 bit)
* Launcher Used:Twitch
* Memory Allocated:9216 MB
* Server/LAN/Single Player:Server and Singleplayer
* Optifine Installed:Yes
* Shaders Enabled:No

## World Information

* Modpack Version world created in:3.1.2

* Additional Content Installed: Apotheosis, ArchitectureCraft, Botania, CoFHCore,  DavincisVessels, ExtraUtilities, MalisisCore, MalisisDoors, MinecraftComesAlive, Movingworld, Optifine, Snad, Thaumcraft, Thaumic Energistics, ThaumicInventoryScanning, ThaumicJEI, ThaumicTinkerer

## Server Information
* Java Version: Unknown(don't know where to find that)
* Operating System: Windows
* Hoster/Hosting Solution: GGServers

**Comment by sam-kirby** [comment]
Would you please also upload the contents of crafttweaker.log from the client and server. It is in the root instance folder.

**Comment by StealthM23** [comment]
CraftTweaker Logs added.

**Comment by sam-kirby** [comment]
This issue is likely the result of your modifications to the pack.

Specifically, the scripts we use to set up the ages system are erroring due to a missing block. This results in most items not being assigned to ages, as well as custom recipes failing to load.

The missing block in question is Quark's Ender Watcher.
