### ISSUE TITLE
Server Advancements

### ISSUE THREAD

**Issue by Driiv** [DarkPacks/SevTech-Ages#4080]
Hi everybody.

I recently wanted to create a small Sevtech Ages server to play with 2 or 3 friends.
we pay a small host and use FileZilla for server files.

The server is working, but there are some problems: First, the chunks don't load, it is mandatory to break or place a block to initialize the chunk. Maybe not a modpack problem.

Then, it is not possible to break something if the hand is not empty or if you don't have the right tool. Maybe it's voluntary, but I haven't seen that in the videos I watched.

Finally, and this is the main problem, we haven't access to advancements at all. The default key is "L" and it opens the advancements of minecraft vanilla, not those of Sevtech as it is in solo.
Despite a lot of research I haven't found a solution to this, and its makes modpack unplayable.

We are using the latest version of modpack.

Thank you for your help, if necessary, I am available to provide more information.

**Comment by sam-kirby** [comment]
This sounds like an incomplete installation, in particular it sounds like you may not have uploaded the config directory.

Make sure you follow the readme included with the server files in its entirety.
