### ISSUE TITLE
I can't play on the server normaly

### ISSUE THREAD

**Issue by Dziugasss** [DarkPacks/SevTech-Ages#4081]
## Bug Report
 I can make planks from wood and don't get chopping block in the server with my friends

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version: 64 bit
* Launcher Used:  TLauncher
* Memory Allocated: 7GB
* Server/LAN/Single Player: server
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
This pack has not been released on TLauncher. As a result, I do not know what you have downloaded and we cannot support it.
