### ISSUE TITLE
Patch from issue #3851 won't work, needs either a recipe or different item

### ISSUE THREAD

**Issue by Ozzymud** [DarkPacks/SevTech-Ages#4087]
A bug report (https://github.com/DarkPacks/SevTech-Ages/issues/3851) was filed and then closed with a patch applied to the upcoming 3.1.3 update, but the patch will not be correct unless altered.

The patch (https://github.com/DarkPacks/SevTech-Ages/commit/864ceacacaf4d257948089c493eafc7c9d5485a9) changes line 83 of the json to be @2 which is the Normal Item Output. I made the change to my instance as such then on restart it was correct, but, the Normal Item Output has no recipe.

Suggest changing to use @1, the Small Item Output which is what the other machines already use.  

This was in 3.1.2-Hotfix1 version of the pack.

**Comment by sam-kirby** [comment]
This is already the case on master: https://github.com/DarkPacks/SevTech-Ages/blob/master/src/config/modularmachinery/machinery/auto-cauldron.json#L83
