### ISSUE TITLE
Tinker's Construct Armour Texture Bugged

### ISSUE THREAD

**Issue by ThePlagueDoctor** [DarkPacks/SevTech-Ages#4089]
![2020-04-15_16 42 03](https://user-images.githubusercontent.com/10220542/79386489-3312fd00-7f38-11ea-9c36-0de29ba22f1a.png)
I have a set of Tinker's Armor that I had put concealed on prior to Age 5, but for some reason once Age 5 was reached, it looked like this? No idea what could be causing the problem.

EDIT: We are on the latest version, this is on a privately hosted server.

**Comment by sam-kirby** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
