### ISSUE TITLE
Resplendent prism not working 

### ISSUE THREAD

**Issue by qrss** [DarkPacks/SevTech-Ages#4091]
Pack version: 3.1.2 Hotfix 1
Forge version: 14.23.5.2838
Current Age: 3
Single player

The Resplendent Prism from Astral Sorcery is a bauble, which, when equipped, is supposed to add new enchantments or improve the enchantments of worn/wielded items.

When the amulet is equipped, the displayed enchantments on your items change correctly. However gameplay wise, the displayed enchantments are not used. Instead, the enchantments you would have without the amulet are used.

This was tested with various vanilla enchantments and vanilla items.

I also tested this with the same version of Astral Sorcery alone on the same Forge version, and things seemed to work correctly there. Perhaps there is some mod conflict?

Note that the Resplendent Prism has a custom recipe in this pack, so presumably it worked in some earlier version of the pack (I have not tested this).

**Comment by sam-kirby** [comment]
DimensionalDevelopment/JustEnoughIDs#136

**Comment by sam-kirby** [comment]
DimensionalDevelopment/JustEnoughIDs#136
