### ISSUE TITLE
Sensor Display (@Cyclic) Requires GPS Marker, but that item does not exist.

### ISSUE THREAD

**Issue by MathiasSven** [DarkPacks/SevTech-Ages#4093]
## Bug Report
Sensor Display from Cyclic Requires GPS Marker to work, I saw that in Tutorials and also in the NEI Information TAB, but that item does not seem to exist. I checked in a Creative World where I gave myself all the Ages.

## Expected Behaviour
The item should exist.

## Steps to Reproduce (for bugs)

1. Look for GPS Marker in NEI
2. It is not there.

## Client Information

* Modpack Version: 3.1.2 Hotfix 1
* Java Version: 8 Update 241
* Launcher Used: MultiMC
* Memory Allocated: 5GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Hoster/Hosting Solution: Anvilnode

**Comment by sam-kirby** [comment]
The item is currently disabled. I assume this happened due to its association with Cyclic's wireless energy transfer, which is also disabled.

**Comment by MathiasSven** [comment]
Ah, I see... Any easy way (Delete a line entry, or turn something from False to True) for me to hotfix that? I went through some of the scripts looking for "GPS Marker" found nothing.

**Comment by sam-kirby** [comment]
See 1235e6ca724946f5b35dc8caa41a2e222921611b

Note, not tested. It's a very simple change so it should be fine, but mistakes do happen.
