### ISSUE TITLE
Install bat not working

### ISSUE THREAD

**Issue by largesoup** [DarkPacks/SevTech-Ages#4095]
Installed sevtech today and after extracting the server pack to my folder I tried running the Install.bat but my cmd prompt immediately closes and nothing happens. Has this happened to anyone else and do you have a fix?

Thank you in advance.

**Comment by sam-kirby** [comment]
Likely missing Java.

**Comment by largesoup** [comment]
> Likely missing Java.

I downloaded the most recent Java patch prior to installing the modpack

**Comment by sam-kirby** [comment]
Discord is a far better home for this.
