### ISSUE TITLE
Tinker's Construct bolt cores cannot be properly modified

### ISSUE THREAD

**Issue by CarlSR** [DarkPacks/SevTech-Ages#4098]
## Bug Report
When modifying a crossbow bolt by replacing the bolt core the head remains the same material as when it was crafted, regardless of any changes made. For example: if you used a wood shaft and an iron head to craft a bolt core and then later swapped the part out for a bolt core made with a bone shaft and a bronze head, the bolt would now have a bone shaft and an iron head. This is consistent across materials regardless of mod (tested with all materials available in Age 3).  

## Expected Behaviour
When modifying a bolt by replacing the core the whole bolt core should be replaced. This was possible in older versions of the pack and in other packs.  

## Steps to Reproduce (for bugs)
1. Craft a crossbow bolt with any materials.  
2. Craft a bolt core using different materials (bolt cores cannot be replaced if either material matches, this may also be a bug).  
3. Replace the bolt core with the new one using a Tool Forge or Tool Station.  

## Logs
* Client/Server Log: https://gist.github.com/CarlSR/7bce8bdcf85d82ba8aaf9ad8c42b26da

## Client Information
* Modpack Version: 3.12
* Java Version: 1.8.0_241
* Launcher Used: Twitch Launcher
* Memory Allocated: 10GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.12
* Additional Content Installed: None

## Server Information
* Java Version: 1.8.0_241
* Operating System: Windows 10
* Hoster/Hosting Solution: Private
* Sponge (Non-Vanilla Forge) Server: No

**Comment by sam-kirby** [comment]
I have been able to reproduce this in SevTech. The issue is only present on servers.

**Comment by sam-kirby** [comment]
I have now also replicated the issue on a server with just the following mods:
* Tinkers' Construct 2.13.0.183
* Mantle 1.3.3.55
* Forge 14.23.5.2854

All of which are the latest released versions at time of testing.

I am fairly confident this is an issue in Tinkers' Construct and not in this pack.

**Comment by sam-kirby** [comment]
Fix included in SevPatches as no clear indication another Tinkers' Construct release is coming for 1.12.2
