### ISSUE TITLE
Empty liquid canister recipe missing in JEI

### ISSUE THREAD

**Issue by komega13** [DarkPacks/SevTech-Ages#4104]
## Context

I'm not sure its a bug but I'm at age 4 and I cannot make galacticraft fuel cannister, when I click on "fuel cannister" on JEI nothing appear . I can just make "tin cannister" wich are not fillable . 
I know there should be an intermediary recipe called "empty liquid cannister" but nothng on JEI . Any help appreciated and thanks for your work

Sevtech ages version 3.1.2

**Comment by sam-kirby** [comment]
The empty canister is available in Age 5. I believe this was a deliberate design decision, and prior to this you can use buckets.

**Comment by komega13** [comment]
It's a bit confusing since the final goal of age 4 is going to the moon, using the galacticraft wiki that advise you to bring fuel canister on the pre flight check list .

**Comment by Pultex** [comment]
still is a problem maybe the pack is dead
