### ISSUE TITLE
Unable to use silicon and black quartz essence

### ISSUE THREAD

**Issue by michele-grifa** [DarkPacks/SevTech-Ages#4105]
## Bug Report
I know there are closed issues on this topic and I went to look at the commits that resolved it, to be precise, the commit [8a2ef58](https://github.com/DarkPacks/SevTech-Ages/commit/8a2ef589c09a41e7ec0ccd0966c3c01b8592098d). Looking at this commit I saw that 2 lines are added for the crafting of the essences so I added it to my script file both on the client side and on the server side, but the result I get is that with silicon essence, 64 diamonds are crafted or at worst In cases, all mystical agriculture craftings are not displayed in the JEI.

![mystical_agriculture script](https://user-images.githubusercontent.com/33720244/80909306-75ee1680-8d27-11ea-9225-95cc6205e932.png)

## Expected Behaviour
Raw Silicon and Black Quartz Ingot can be crafted using essence

## Client Information
* Modpack Version: 3.1.2 Hotfix-1
* Java Version: 1.8.0_241
* Launcher Used: ATLauncher
* Memory Allocated: 6144
* Server/LAN/Single Player: Server
* Optifine Installed: Yes
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.1.2 Hotfix-1
* Additional Content Installed: None

## Server Information
* Java Version: 1.8.0_241
* Operating System: Linux
* Hoster/Hosting Solution: GameHosting
* Sponge (Non-Vanilla Forge) Server: No

**Comment by sam-kirby** [comment]
See #3818 

You have accounted for missing recipes, but not the name mismatch between server and client.
