### ISSUE TITLE
Stage two wooden axle crafting recipe not working???

### ISSUE THREAD

**Issue by danknited** [DarkPacks/SevTech-Ages#4106]
## Bug Report

When trying to craft it appears as valid recipe but does not craft.(Doesn't consume items but won't give item. Item trying to be crafted isn't visible either.)

## Expected Behaviour

Item trying to be crafted doesn't appear

## Possible Solution

i got nothing have a smiley face. :)

## Steps to Reproduce (for bugs)

1.put 2 plank mouldings of any kind and one hemp rope in crafting table(2x2 crafting: 1 plank moulding top left and one bottom left and 1 hemp rope top right)
2. item to be crafted doesn't appear

## Logs

* Client/Server Log: no issue here
* Crash Log: no issue here

## Client Information

* Modpack Version: 3.1.2 Hotfix 1
* Java Version: 1.12.2
* Launcher Used: Twitch
* Memory Allocated:
* Server/LAN/Single Player: LAN
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.1.2 Hotfix 1

* Additional Content Installed: none

**Comment by sam-kirby** [comment]
The recipe is misidentified as shapeless in JEI, when it is in fact shaped. See here: https://github.com/DarkPacks/SevTech-Ages/issues/3991#issuecomment-552795779

**Comment by sam-kirby** [comment]
To resolve this display issue, for this and other recipes, update Recipe Stages to 1.1.3.
