### ISSUE TITLE
No black quartz recipe; mystical agriculture

### ISSUE THREAD

**Issue by voltz20** [DarkPacks/SevTech-Ages#4108]
Bug Report
There is no black quartz essence recipe.

## Expected Behaviour
a black quartz essence recipe exists

## Possible Solution
add a black quartz recipe

another solution is to add black iron essence (not sure if there is an addon for black iron or not.) and make a black iron recipe from that because that's more or less the only thing that black quartz is used for in age 5

## Steps to Reproduce (for bugs)
1) get to age 5
2) start mystical agriculture
3) plant black quartz seeds
4)try to use the essence

**Comment by sam-kirby** [comment]
Fixed at same time as #3913

**Comment by sam-kirby** [comment]
Duplicate of #3833
