### ISSUE TITLE
raw advanced processor recipe missing

### ISSUE THREAD

**Issue by komega13** [DarkPacks/SevTech-Ages#4110]
## Context
Trying to make the "processing pattern encoder" from refined storage mod, JEI show that it need "advanced processor" made by cooking into furnace a "raw advanced processor" but the item appear nowhere into JEI neither any recipe (I try in French translation and English).
Best regards and thanks for your work

**Comment by sam-kirby** [comment]
Do you mean the Pattern Grid? The recipe involving an advanced processor was included by mistake, you are able to craft it using the inscriber by combining an Engineering Processor, a Grid and a Pattern.

![image](https://user-images.githubusercontent.com/23245543/81309568-ffc91700-907a-11ea-84e6-c647f04019a5.png)

**Comment by komega13** [comment]
Sorry for tardive response; No the pattern grid need an advance processor wich is made with a raw advance processor wich the recipe is missing in JEI

**Comment by sam-kirby** [comment]
Duplicate of #4103
