### ISSUE TITLE
No raw advanced processor recipe

### ISSUE THREAD

**Issue by voltz20** [DarkPacks/SevTech-Ages#4114]
Bug Report
There is no recipe for the raw advanced processor, this is used to make the fluid grid with refined storage, without it there is no way to access stored fluids that are stored in your refined storage network
There should be a recipe so we can go further into refined storage

## Expected Behaviour
A recipe exists

## Possible Solution
Add a raw advanced processor recipe

## Steps to Reproduce (for bugs)
1. try to raw advanced processor
2. don't

**Comment by sam-kirby** [comment]
Raw advanced processors are purposefully disabled, there are alternative recipes to craft everything they are involved in so far as I am aware. The recipes involving advanced processors will be removed in the next update to avoid confusion.

https://github.com/DarkPacks/SevTech-Ages/issues/4110#issuecomment-625305383
