### ISSUE TITLE
Really bad with AMD graphics card

### ISSUE THREAD

**Issue by Azura0** [DarkPacks/SevTech-Ages#4119]
Im having some massive lag with my RX 580 8GB, i try everything to fix this, there's something that i can do?
![Sin título](https://user-images.githubusercontent.com/65145408/81522762-48016700-9311-11ea-9a51-f61faf3c8b63.png)

**Comment by sam-kirby** [comment]
This issue was resolved in 3.1.0. It is unclear what version you are running as you have not told us, and you have modified the version of Forge - which will cause crashes and issues if this install is based on 3.0.8.

**Comment by Azura0** [comment]
Version 3.1.2

**Comment by sam-kirby** [comment]
Okay - try this anyway:

```
certain RX and Vega cards seem to have a problem with a foamfix tweak (on 3.0.8) you can try this:
in: .\SevTech Ages\config\foamfix.cfg
under texures, set I:fasterAnimation=0
```

If that doesn't help, please try without Optifine and without modifying the pack.
