### ISSUE TITLE
CraftTweaker not applying in 3.1.2 Hotfix 1

### ISSUE THREAD

**Issue by SparksIsANerd** [DarkPacks/SevTech-Ages#4124]
Installed the game on MultiMC, with no additional mods except for Optifine and was using AdaptOpenJDK as my Java Runtime.

Tried multiple reinstallations but I can never seem to craft the Grass Fiber Mesh. Also some items which are supposed to be locked back in 3.0.8 are unlocked in the tutorial stage.

**Comment by sam-kirby** [comment]
I'm going to guess you're using the OpenJ9 VM. This is a known incompatibility, you can use OpenJDK but only the HotSpot VM is compatible.
