### ISSUE TITLE
Steppe Wolves are Eating River Fish and Reproducing in the Hundreds

### ISSUE THREAD

**Issue by iankellyUW** [DarkPacks/SevTech-Ages#4136]
## Bug Report
Steppe wolves have gotten into my river and are eating the river fish, and breeding unchecked.
A possible solution is to not have wolves reproduce eating fish, or prevent wolves from breeding when there are more than a certain amount in the area.

## Expected Behaviour
I would expect a pack of 4 - 8 steppe wolves eating fish in my river, not 400 of them.

## Possible Solution
Don't let wolves become breedable by eating fish in rivers.

## Steps to Reproduce (for bugs)

Imgur Photo: https://imgur.com/a/pMQWzCb
1. Put steppe wolves in river with fish.
2. Watch them multiply as more fish spawn.

## Logs
No Crash.

## Client Information

* Modpack Version: 3.1.2
* Java Version:
* Launcher Used: AT Launcher
* Memory Allocated: 24 Gb
* Server/LAN/Single Player: SSP
* Optifine Installed: Yes
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.1.2

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by justinrusso** [comment]
We have made changes in the next release already that should put a limit on the spawn rates of all these mobs to a much more reasonable amount.

I'm not sure if this will limit breeding though, so in either case, this should be looked into further.

**Comment by Darkosto** [comment]
Breeding is not limited by the changes we made. However, breeding beyond the mob limits will not allow those entities to naturally spawn any longer.

**Comment by sam-kirby** [comment]
Not resolved, reopening
