### ISSUE TITLE
RandomPatches Mod

### ISSUE THREAD

**Issue by Mike-Mad-Badger** [DarkPacks/SevTech-Ages#4137]
## Context
The error "internal exception java.nio.channels.closedchannelexception" when opening a local world and followed by being returned to the multiplayer screen seems quite well known and is often reported with SevTech. As far as I can tell it is mostly an issue with low to medium spec computers timing out when loading the world (this is supposition, I have no proof). If true then this error probably also applies to other very large packs that take a long time to load on low to mid-spec PC's.

Since adding RandomPatches to the mod folder I have not had an issue loading an existing world whereas previously the world failed to load >75% of the time. Even the creation of new worlds often failed with the same error.

The attraction of RandomPatches is the following feature :
- The read and login timeouts are hardcoded in vanilla Minecraft, and are often not long enough for slower computers.
- On Minecraft 1.9 and higher, RandomPatches allows you to configure the login timeout, and on - - - Minecraft 1.12 and higher, the read timeout is also configurable.
- By default, RandomPatches sets the read timeout to 90 seconds and the login timeout to 900 seconds.

I do not know if other RandomPatches features interfere with SevTech features / design.

In my case I have a laptop, i5-8250U 1.6GHz, 8GB RAM with 6GB allocated to SevTech.

## Mod Details
* Name: RandomPatches
* CurseForge Link: https://www.curseforge.com/minecraft/mc-mods/randompatches

Regards,
M

**Comment by sam-kirby** [comment]
Closed by c8e83a5
