### ISSUE TITLE
Void World Generation

### ISSUE THREAD

**Issue by LemonJamTart** [DarkPacks/SevTech-Ages#4144]
Hi! I am having an honestly rather funny, if infuriating, issue with the SevTech Ages modpack: No matter what world generation type I choose, every single time I create a new world there simply is... no land. Absolutely none. The only solid ground can be found on structures that will generate at random heights. And this is not exclusive to the Overworld! _Every single dimension will generate like this as well._ Makes it rather difficult to play the game, lol. Even when playing a previously-generated map, when entering new chunks that _weren't_ part of the original map, this same terrain generation glitch occurs. I've got no clue what could be causing it, especially since my log files don't actually... display any errors related to terrain generation. Please help! Images attached.
![overworld3](https://user-images.githubusercontent.com/20097471/84528623-a8375000-aca5-11ea-83a5-419ee050f342.png)
![beneath1](https://user-images.githubusercontent.com/20097471/84528624-a8cfe680-aca5-11ea-8758-add7ee165100.png)
![nether1](https://user-images.githubusercontent.com/20097471/84528626-a8cfe680-aca5-11ea-8a3d-9db9f4485101.png)
![nether2](https://user-images.githubusercontent.com/20097471/84528629-a9687d00-aca5-11ea-9502-aeb6f293f360.png)
![overworld1](https://user-images.githubusercontent.com/20097471/84528630-aa011380-aca5-11ea-8b1d-8c66dcee13fe.png)
![overworld2](https://user-images.githubusercontent.com/20097471/84528632-aa011380-aca5-11ea-962d-3222bc2311b3.png)
Please, I cannot properly play this pack until this issue is fixed. Any insight at all would be incredibly appreciated.

**Comment by sam-kirby** [comment]
You do not appear to be playing SevTech. Forestry is not a part of this pack, and you should receive no books on world creation.

We do not support other modpacks - there is not enough time in the day.

If you have an issue with SevTech, please submit a new issue and complete the template.
