### ISSUE TITLE
Server World Not Rendering Anything

### ISSUE THREAD

**Issue by Spudkin** [DarkPacks/SevTech-Ages#4157]
So when I log into a private server, none of the blocks render. Everything is invisible. Mobs and other entities load in fine, but blocks are just not appearing. This happens for everyone who logs in. We've tried multiple worlds and it continues to happen.

When blocks are altered (placed, blown up, etc.) sometimes it causes blocks around it to load, but doesn't solve the issue.

Since it doesn't cause a crash I don't have any logs, the server isn't throwing any errors either.

Anyone have any ideas as to what could be causing this?

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
There's a lot of information missing here that would help me work out what's going wrong. Server and client logs would have been great, as well as more details on the host. Please complete the template, which I have inserted into your post for your convenience.

Whilst doing this, could you clarify the following:
1) do you see the same issues when starting a single player world?
2) is there anything abnormal about the host, such as being part of a minecraft world "network"?

**Comment by sam-kirby** [comment]
Closing due to lack of information, please open a new issue with all the information requested if you still think this is an issue.
