### ISSUE TITLE
Recipes broken after updating game from 3.0.8 to 3.1.2

### ISSUE THREAD

**Issue by webik150** [DarkPacks/SevTech-Ages#4167]
## Bug Description

 So once more because I removed the steps to reproduce: Similar to #3938, except I'm playing singleplayer. A lot of vanilla recipes started working and a lot of SevTech recipes don't work. For example the recipes for the V1 Airship. I can see the SevTech extended crafting table recipes for it in JEI, but when I put in the items, I can't craft anything (nothing appears in output). Vanilla visecraft recipes work. Also happens with some immersive engineering recipes

### Did this behavior use to work in the previous version?

Everything worked fine in 3.0.8.

## Steps to Reproduce (for bugs)

1. open up game
2. try to craft
3. it not work

## Logs

* Client/Server Log
  * Here's a crafttweaker log. I'll gladly include anything else necessary:
  * https://gist.github.com/webik150/07087b394e5e951d11eb15366045c720

I noticed these lines, but I have no idea how to fix this:
`[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: mod_integrations\extended_crafting.zs}`
`[INITIALIZATION][CLIENT][ERROR] mod_integrations\extended_crafting.zs:13: Could not resolve <vc : airship_ignition>`
`[INITIALIZATION][CLIENT][ERROR] mod_integrations\extended_crafting.zs:14: Could not resolve <vc : airship_ignition>`

## Client Information
* Modpack Version: 3.1.2 Hotfix 1
* Java Version: The version included with Twitch
* Launcher Used: Twitch launcher
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed: None

**Comment by webik150** [comment]
I kinda omitted the steps to reproduce, but if You need proof that I can't craft or something, I can upload a video :D

**Comment by sam-kirby** [comment]
You are using scripts from 3.0.8. This is not going to work. I'm guessing Twitch failed to upgrade properly.

The best way around this is probably to install a fresh version of the pack, and copy your save across.
