### ISSUE TITLE
Modular Machinery

### ISSUE THREAD

**Issue by C14X** [DarkPacks/SevTech-Ages#4169]
## Context

 I wish that you could craft the higher tiers of modular machinery I/Os.

**Comment by sam-kirby** [comment]
Why? What's the point other than cluttering things up?

**Comment by C14X** [comment]
For me personally, I enjoy being able to upgrade things like that. It gives me a sense of satisfaction.

**Comment by sam-kirby** [comment]
These items don't really offer any gameplay advantage. They'd just be resource sinks with no purpose. The machines were designed around the input and output blocks included in their structures, and increasing the options serves only to increase clutter.
