### ISSUE TITLE
Bug with the limbs of all creatures

### ISSUE THREAD

**Issue by AlexRMU** [DarkPacks/SevTech-Ages#4172]
## Bug Description
All the limbs of all creatures spin madly or disappear. Sometimes after attack, sometimes on their own. I thought it was because of Mo'bends, but deleting it didn't change anything.
Video - https://dump.video/i/cvxZUq.mp4

### Did this behavior use to work in the previous version?
I don't know.

## Steps to Reproduce (for bugs)
See the video above.

## Logs
* Client/Server Log: https://gist.github.com/AlexRMU/15cd2a992018bcbf92570485145e0a66
* Crash Log: No crash

## Client Information
* Modpack Version: SevTech Ages  3.1.2 Hotfix 1
* Java Version:1.8.0_231
* Launcher Used: TLauncher
* Memory Allocated: 8192MB
* Server/LAN/Single Player: Single 
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in: 3.1.2 Hotfix 1
* Additional Content Installed: no

**Comment by sam-kirby** [comment]
Probably due to the BetterFPS algorithm being used, which you appear to have changed to Taylor's.

Try changing this back to Riven's Half, and if that does not help switch to Vanilla.

**Comment by sam-kirby** [comment]
Actually - you're using the TLauncher. We have never released this pack on the TLauncher. It was uploaded by someone else using this pack's name, and therefore may actually be anything.

I suggest you abandon it, and try installing the pack from either Curseforge via Twitch or MultiMC launcher or ATLauncher.
