### ISSUE TITLE
Betweenlands Dimension not initialise

### ISSUE THREAD

**Issue by skrilax91** [DarkPacks/SevTech-Ages#4177]
## Bug Description

I currently have an issue with The Betweenlands Mod, specialy with the dimension, it seems like the dimension are like otherworld.
Animals like pig and cow spawn and otherworld trees spawn. Also no one of mob spawn.

### Did this behavior use to work in the previous version?

i don't think

## Steps to Reproduce (for bugs)

1. go to the Betweenlands Dimension

## Logs

* Client/Server Log: [download](https://mega.nz/file/mBMkTYZL#N-4RcjCwC5moWWpJjMDQXjHI6MURKLinMS189i50xTk) (To big for Pastebin Sorry)

## Client Information
* Modpack Version: 3.1.2 Hotfix 1
* Java Version: build 1.8.0_241-b07
* Launcher Used: Twitch
* Memory Allocated: 10G
* Server/LAN/Single Player: Server
* Optifine Installed: OptiFine 1.12.2 HD U F6 pre1
* Shaders Enabled: Yes

## World Information
* Modpack Version world created in: 3.1.2 Hotfix 1
* Additional Content Installed: Some plugins

## Server Information
* Java Version: 8
* Operating System: Ubuntu
* Hoster/Hosting Solution: VPS using Pterodactyl for serveur docker management
* Sponge (Non-Vanilla Forge) Server: Yes

**Comment by skrilax91** [comment]
some pictures :
![2020-06-29_01 49 34](https://user-images.githubusercontent.com/6585219/85967542-feed9b00-b9c2-11ea-84c2-993ef5851cec.png)
![2020-06-29_01 49 46](https://user-images.githubusercontent.com/6585219/85967543-ff863180-b9c2-11ea-9be9-5ce75233f2aa.png)
![2020-06-29_01 50 08](https://user-images.githubusercontent.com/6585219/85967545-001ec800-b9c3-11ea-8e1c-04a72c4d515c.png)

**Comment by sam-kirby** [comment]
We do not support the use of Sponge, any issues encountered as a result of using it should be brought to the attention of the mod or plugin authors involved who may or may not attempt to fix it.

Sponge likes to have complete control over world gen, which may be an issue for a mod like betweenlands with huge amounts of custom generation.

**Comment by sam-kirby** [comment]
You may want to try this again on 3.1.3 however as both Forge and Betweenlands were updated and this issue may already be fixed.
