### ISSUE TITLE
Issues with Server not able to catch up:  Can't keep up! Did the system time change, or is the server overloaded? 

### ISSUE THREAD

**Issue by Visceralfulton** [DarkPacks/SevTech-Ages#4180]
🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟-->

## Bug Description
Hello everyone, for the last week or so I have been running a minecraft Sevtech server off of my rig with a group of about 5 people including myself. The reason why i am here today is because that whenever myself or my friends play in the server we tend to continuously experience TPS lag when mobs just keep teleporting around when they walk around or other plays appear to be teleporting around as well. I have been having alot of issues trying to fully optimize the server in terms of what i can do to try and elevate the TPS issues but I am at a loss. As we continuously progress through the ages the TPS lag does get worse and worse, at the current time we are on Age 3 nearing the end to head off to age 4 but with all the IE machines we have going for us it has become very difficult to progress with a stable playtime. 

### Did this behavior use to work in the previous version?
I have no Idea unfortunately, I never tried it in an older version.

## Steps to Reproduce (for bugs)
Just generally playing the game either by myself of with others. We usually have about 3-4 people in the server at a time so it tends to always have TPS lag whenever the server boots.

## Logs

* Client/Server Log:https://pastebin.com/D2R5MXNr
* Crash Log:https://pastebin.com/3Qx3CnAA - I havent had any server crashes in a bit so  i dont know if this is relevant

## Client Information
* Modpack Version:1.12.2
* Java Version: jre1.8.0_251
* Launcher Used: ATLauncher
* Memory Allocated: 12Gbs for server - 6000mbs:14000mbs for client
* Server/LAN/Single Player: Server
* Optifine Installed: Nope
* Shaders Enabled: Nada

## World Information
* Modpack Version world created in: 1.12.2
* Additional Content Installed: Dynamic Trees-1.12.2, BspkrsCore-1.12.2, TreeCapitator 1.12.2, Dynamic Lights 1.12.2, Waystones 1.12.2, RoguelikeDungeons 1.12.2, Thaumcraft 1.12.2, Millenaire Mod 1.12.2, Immersive Railroading 1.12.2

## Server Information
* Java Version : jre1.8.0_251
* Operating System: Windows 10 Home
* Hoster/Hosting Solution: Same rig i am playing the game off of
* Sponge (Non-Vanilla Forge) Server:

Please let me know if i need to add anything else to the list here. 
Thank you <3

**Comment by sam-kirby** [comment]
You appear to have removed optimisations we put in place to help with GC issues. You have also changed the pack significantly. This is not something we can offer support for.
