### ISSUE TITLE
[AbyssalCraft] Parrot Summoning Ritual Triggering Ritual of Downpour

### ISSUE THREAD

**Issue by DSinge** [DarkPacks/SevTech-Ages#4182]
## Bug Description
The Parrot Summoning Ritual seems to trigger the Ritual of Downpour (causes it to start raining) instead of summoning a parrot.

### Did this behavior use to work in the previous version?
Not sure

## Steps to Reproduce (for bugs)
https://youtu.be/zHvLwcJbjfw

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 3.1.3 Beta
* Java Version: 1.8.0_251
* Launcher Used: MultiMC
* Memory Allocated: 8092 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.1.2 Hotfix 1
* Additional Content Installed: None

**Comment by sam-kirby** [comment]
Resolved in 3beb38b85a3b145c3ca980a5b009f74bc22b3415
