### ISSUE TITLE
Crash on first time running 3.1.3 server on Ubuntu Server

### ISSUE THREAD

**Issue by McBainWRX** [DarkPacks/SevTech-Ages#4187]
**Bug Report**
Server crashes on start for missing mod actuallyadditions

**Steps to Reproduce (for bugs)**
Install Sevetech Ages 3.1.3 on Ubuntu Server. Run for the first time.
Logs
Client/Server Log: -
Crash Log: [crash-2020-07-04_04.08.47-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/4874392/crash-2020-07-04_04.08.47-server.txt)

**Client Information**
Modpack Version: SevTech: Ages 3.1.3
Java Version: openjdk  1.8.0_252
Memory Allocated: 4GB
Server/LAN/Single Player: Server
Optifine Installed: no
Shaders Enabled: no
World Information
Modpack Version world created in: SevTech: Ages 3.1.3
Additional Content Installed: None
**Server Information**
Java Version: OPEN JDK 8
Operating System: Ubuntu Server 20.04
Hoster/Hosting Solution: 
Sponge (Non-Vanilla Forge) Server: -
**OTHER**
Early in the startup of the server it generates a fatal error for a missing modpack, in this case actuallyadditions.  The jar file for this mod is present in the mods folder but apparently not found by forge.  It's very possible that this is some problem with my setup on Ubuntu server, I'm not a regular user of Linux, but I can successfully install and run SevTech Ages 3.1.2 Hotfix 1 and Vanilla servers on the same installation.

**Comment by sam-kirby** [comment]
Forge should log why it decides not to load any file in the mods folder. Please include a log.

**Comment by McBainWRX** [comment]
Server logs.
[debug.log](https://github.com/DarkPacks/SevTech-Ages/files/4875524/debug.log)
[latest.log](https://github.com/DarkPacks/SevTech-Ages/files/4875525/latest.log)

**Comment by sam-kirby** [comment]
Concerning Actually Additions, your log shows the following:

```
[04:08:40] [Server thread/ERROR] [FML]: There was a problem reading the entry de/ellpeck/actuallyadditions/api/ActuallyAdditionsAPI.class in the jar ./mods/ActuallyAdditions-1.12.2-r149.jar - probably a corrupt zip
net.minecraftforge.fml.common.LoaderException: java.util.zip.ZipException: invalid LOC header (bad signature)
```

As Forge indicates, this file has somehow become corrupted. This could have happened at any point from download of the pack zip to decompression to uploading to the server, or even whilst the file is at rest on the server's drive.

To eliminate all of these possibilities, please download the pack zip again and replace your existing setup.

**Comment by McBainWRX** [comment]
I downloaded a new copy of Actually Additions from curseforge and copied over the one in my mods folder and the server started.  Thanks for the help.  I was a bit nervous about working on it in linux but I'm over the hump.  Thanks for the hand holding.
