### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by bigkye** [DarkPacks/SevTech-Ages#4188]
## Bug Description

While loading the game it wont load past 6/7

### Did this behavior use to work in the previous version?

I have tried loading other versions and the same issue happens and I have tried on both my pcs

## Steps to Reproduce (for bugs)

There are no steps, it happens when the game is loading, might be not enough memory, it auto set to 2869 Mb memory used / total
1.
2.
3.

## Logs

* Client/Server Log:no idea how find any of this
* Crash Log:

## Client Information
* Modpack Version:no idea
* Java Version:no idea
* Launcher Used:Minecraft launcher
* Memory Allocated:no idea
* Server/LAN/Single Player:single player
* Optifine Installed:none
* Shaders Enabled:none

## World Information
* Modpack Version world created in:still no idea
* Additional Content Installed:

**Comment by bigkye** [comment]
I know I couldn't give a very descriptive explanation of the problem but I don't understand half the stuff asking me to get, just a normal player whos game wont run and cant understand how to resolve it

**Comment by sam-kirby** [comment]
What has Flash got to do with anything?

Could you please at least tell us what launcher you are using? i.e. how have you downloaded this modpack - through Twitch?

**Comment by bigkye** [comment]
I downloaded it through twitch

**Comment by sam-kirby** [comment]
How much RAM does your computer have? You can check in Task Manager under the Performance tab.

**Comment by bigkye** [comment]
I have 32 GB

**Comment by sam-kirby** [comment]
First, make sure Minecraft and its launcher are not running.

Then, in Twitch click the profile icon in the top right corner and go to Settings. In Settings, go to the Minecraft tab and scroll down until you see Java Settings.

Here you'll find a slider labelled Allocated Memory. Set that to approximately 8192MB. There is no benefit to going higher, even though you have the available RAM.

Now try starting the game.

**Comment by bigkye** [comment]
I put the memory up and reloading now

**Comment by bigkye** [comment]
Thank you for the help, finally loaded, tired playing this like a year ago and had same issue, but can finally play it, been a great help.
