### ISSUE TITLE
World Generates only Plains Biome

### ISSUE THREAD

**Issue by XenoStone1009** [DarkPacks/SevTech-Ages#4190]
## Bug Description

World generates nothing but Plains after having played it for a week.

### Did this behavior use to work in the previous version?

 Yes, Before we moved to spongeforge and first set up the pack on base vanilla hostings

## Steps to Reproduce (for bugs)

1. Run the server on vanilla minecraft.jar and forge.jar
2. Change over to Spongeforge

## Logs

* Client/Server Log: https://gist.github.com/XenoStone1009/66f973ac7e7093d3c8746ac5822426e3
* Crash Log:

## Client Information
* Modpack Version: 3.1.2-hotfix.1
* Java Version:1.8.0
* Launcher Used: MultiMC
* Memory Allocated: 5 GB
* Server/LAN/Single Player:Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in:3.1.2-hotfix.1
* Additional Content Installed: updated Farseek 2.5

## Server Information
* Java Version:1.8.0_252
* Operating System: Linux
* Hoster/Hosting Solution:MCProHosting
* Sponge (Non-Vanilla Forge) Server:Yes

**Comment by sam-kirby** [comment]
Try with 3.1.3.
