### ISSUE TITLE
Crashing my game when i use wawla

### ISSUE THREAD

**Issue by iiRedWolfii** [DarkPacks/SevTech-Ages#4193]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sam-kirby** [comment]
We have never released this pack on TLauncher, nor will we ever.

We therefore do not control the files you have downloaded, and cannot support them on that basis.
