### ISSUE TITLE
crashing my game when using wawla

### ISSUE THREAD

**Issue by iiRedWolfii** [DarkPacks/SevTech-Ages#4194]
<!🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟

Thank you for submitting an issue for the relevant topic. Please ensure that you fill in all the required information needed as specified by the template below. Enter text following any " i did but the problem still the same even i didn't click it

### Did this behavior use to work in the previous version?

* Client/Server Log:<1.12.2>
* Crash Log:<low quality mods or uncomfortable>

## Client Information
* Modpack Version:<Latest version>
* Java Version:<8>
* Launcher Used:<TLauncher>
* Memory Allocated:<4000/8000>
* Server/LAN/Single Player:<singlr player>
* Optifine Installed:<1.12.2>
* Shaders Enabled:<0>

## World Information
* Modpack Version world created in:<latest>
* Additional Content Installed:<foamfix-vannilafix-optifine:3>

**Comment by sam-kirby** [comment]
We have never released this pack on TLauncher, nor will we ever.

We therefore do not control the files you have downloaded, and cannot support them on that basis.
