### ISSUE TITLE
Issue with hosting server

### ISSUE THREAD

**Issue by ANTIBYT3** [DarkPacks/SevTech-Ages#4198]
## Bug Description

 Whenever I try to start a server with the provided server files for 3.1.2 hotfix 1, the first time I run the server, it seems to run smoothly, however whenever I try to run it again, it always gets stuck with the last line in the command prompt being "Unloading dimension XX". The dimension varies from 53 to 54 to 144 in the times I have tried. Task manager lists the server as suspended.

### Did this behavior use to work in the previous version?

I believe I was successfully able to run a server in the version prior to hotfix 1.

## Steps to Reproduce (for bugs)

1. Run Install.bat
2. Run ServerStart.bat
3. Agree to EULA
4. Run ServerStart.bat again
5. Server startup freezes, task manager lists it as Suspended.

## Logs

* Client/Server Log:
https://gist.github.com/ANTIBYT3/4c6ecf600eb13729f52b063c22d2aa22
* Crash Log:

## Client Information
* Modpack Version: 3.1.2 hotfix 1
* Java Version: 1.12.2
* Launcher Used: Twitch Launcher
* Memory Allocated: 8 GB to minecraft, 1-4 GB for server
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.1.2 hotfix 1
* Additional Content Installed:

## Server Information
* Java Version: 1.12.2
* Operating System: Windows 10
* Hoster/Hosting Solution: Personal hosting with included server pack
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
The server will always unload dimensions as the last action on startup - why do you believe there is an issue here?

**Comment by ANTIBYT3** [comment]
Hello,

Thanks for your reply. I do understand that the server will unload a
dimension as the last action, the problem is that it is supposed to unload
dimension 1 or -1 as the last dimension, but it gets stuck about halfway
through the unloading process and doesn't start the server. This is the
issue I have.

Thanks.
