### ISSUE TITLE
EFLN can be craft in Age 1, but can't be use to mine block

### ISSUE THREAD

**Issue by Solousia** [DarkPacks/SevTech-Ages#4202]
## Bug Description
EFLN from Tinker construct can be craft using flint and gunpowder or sulfer, but it does not appear in JEI. When use in mining ore, it does not drop the ore, but drop cobblestone instead.

### Did this behavior use to work in the previous version?
Probably, never play other version

## Steps to Reproduce (for bugs)
1. Make a EFLN from Tinker Construct, using gunpowder and flint
2. throw it into ore deposit
3. drop cobble instead of the ore

## Client Information
* Modpack Version: 3.1.2 (Release)
* Java Version: 1.8.0.51(64bit)
* Launcher Used: Twitch or Curse Launcher
* Memory Allocated: 6GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: None
* Shaders Enabled: None

## World Information
* Modpack Version world created in: 3.1.2 (Release)
* Additional Content Installed: None

**Comment by sam-kirby** [comment]
EFLN is disabled in 3.1.3+
