### ISSUE TITLE
I can't craft a Grass Fiber Mesh

### ISSUE THREAD

**Issue by Sharpy0077** [DarkPacks/SevTech-Ages#4205]
## Bug Description
 I start the world like any other and get the stuff to craft the Grass Fiber Mesh. When I put the Plant Twine and sticks into the crafting grid nothing pops up, and when I look up up and press move items nothing pops up still.

### Did this behavior use to work in the previous version?
I don't remember clearly but it was over a year ago

## Steps to Reproduce (for bugs)
None that I know of
Down
1. Go to a world and do the tutorial stage and go and try crafting it, if it does or doesn't work it might be a hardware issue on my end.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:3.1.1
* Java Version:
* Launcher Used:7/28/2020
* Memory Allocated:
* Server/LAN/Single Player:Yes
* Optifine Installed:No
* Shaders Enabled:No

## World Information
* Modpack Version world created in:3.1.1
* Additional Content Installed:None
Extra Note, if there's any info you need I really don't know any way to know as  I'm not any good at computer stuff as I'm young.

**Comment by sam-kirby** [comment]
If you aren't trying to continue playing in an old world, it's probably best you just forget about the version of the pack you have installed and start fresh with a new and up to date version.
