### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by ozoromo** [DarkPacks/SevTech-Ages#4209]
## Steps to Reproduce (for bugs)

1. Create server
2. Start it
3. Crash

## Logs

* Client/Server Log: [Server log](https://pastebin.com/e73E3Nwu)
* Crash Log: [Server crash log ](https://pastebin.com/X0zAmbsH)

## Client Information
This problem is serverside only

## World Information
The world doesn't get created

## Server Information
* Java Version: Java 8 OpenJDK headless
* Operating System: Ubuntu 18.04 LTS server
* Hoster/Hosting Solution: Dedicated server at home
* Sponge (Non-Vanilla Forge) Server: Just forge

**Comment by sam-kirby** [comment]
This is not an exact replica of your setup, but I am able to start the server running headless OpenJDK 1.8.0_262 on Linux without issue.

```
[13:27:34] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2838 for Minecraft 1.12.2 loading
[13:27:34] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_262, running on Linux:amd64:5.7.10-arch1-1, installed at /usr/lib/jvm/java-8-openjdk/jre
```

If you haven't already, could you redownload the server files and rerun the setup process on your server?

There are similar crash reports around but I have been unable to find a resolution:
mekanism/Mekanism#5858
Angry-Pixel/The-Betweenlands#478

**Comment by ozoromo** [comment]
Removing all clientside mods and the mcjty-lib.jar and then placing them back in after one restart seems to have fixed the errors, I'm highly confused about how that worked though.

**Comment by sam-kirby** [comment]
Closing as no way to further investigate this.
