### ISSUE TITLE
Bedrock gone, overworld is open to void

### ISSUE THREAD

**Issue by seals55** [DarkPacks/SevTech-Ages#4210]
## Bug Description

Upgraded from 3.1.3 to 3.1.5. Bedrock gone, overworld is open to void

### Did this behavior use to work in the previous version?

Yes, 3.1.3 had bedrock 

## Steps to Reproduce (for bugs)

1. Upgrade server from 3.1.3 to 3.1.5
2. Dig down (carefully)
3. See that there is no bedrock, only void

## Logs

* Client/Server Log:
* Crash Log:
I don't have this saved, but when I upgraded from 3.1.3 to 3.1.5 I had to /fml approve to allow minecraft:bedrock to be removed.

## Client Information
* Modpack Version: 3.1.5
* Java Version: AdoptOpenJDK/jdk-8.0.252.09
* Launcher Used: MultiMC 
* Memory Allocated: 21024 MB
* Server/LAN/Single Player: Client
* Optifine Installed: Yes
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.1.3
* Additional Content Installed: No additional mods

## Server Information
* Java Version: OpenJDK 1.8.0.252
* Operating System: Ubuntu 18.04
* Hoster/Hosting Solution: self hosted
* Sponge (Non-Vanilla Forge) Server: no

The Bedrock B Gone mod mentions there is a way to regenerate bedrock...but doesn't give the example??

**Comment by lmdpocus** [comment]
Same here, no bedrock in the world. Had to /FML approve for it as well.

**Comment by lmdpocus** [comment]
After some chatting it seems possible to regenerated the Bedrock. 
To do this, edit the BetterBedrock.cfg file in config folder.
Put Retrogen to true in both cases.

    # Enabled chunks to be regenerated. This will probability cause lag until chunks are done. [default: false]
    B:enabled=false

    # Enable this only to rebuild the Bedrock at y level 0. Retrogen must be enabled to work. [default: false]
    B:rebuild=false

**Comment by 24680FPIC** [comment]
It seems that Bedrock B Gone is strangely missing from 3.1.5. Placing it back into the mod folder fixes the problem.

**Comment by lmdpocus** [comment]
> It seems that Bedrock B Gone is strangely missing from 3.1.5. Placing it back into the mod folder fixes the problem (if the world wasn't loaded before).

Not the case here: BetterBedrock-1.12.2-5.1.11.jar

**Comment by gnowor** [comment]
I also had this issue, and fixed it with retrogen with same results as Imdpocus' post on 8/5 listed above.

**Comment by nimsarr** [comment]
I also went through the same experience and fix as described by @lmdpocus.

**Comment by justinrusso** [comment]
As mentioned by @lmdpocus BedrockBGone was renamed to Better Bedrock. Retrogen did not work in testing for me, so we've added [a mod](https://www.curseforge.com/minecraft/mc-mods/bring-back-bedrock) in for 3.1.6 which should resolve this issue entirely.

3.1.6 is now released - as always please make a backup before updating! https://www.curseforge.com/minecraft/modpacks/sevtech-ages/files/3038158

**Comment by sam-kirby** [comment]
Resolved in 3.1.6
