### ISSUE TITLE
Cant craft fiber mesh

### ISSUE THREAD

**Issue by ozoromo** [DarkPacks/SevTech-Ages#4212]
## Bug Description
Cant craft fiber mesh

### Did this behavior use to work in the previous version?
Guess so, haven't tried older versions

## Steps to Reproduce (for bugs)
1.Try to craft fiber mesh
2. Doesnt work
3. Yes I have tried reinstalling multiple times

## Logs

* Client/Server Log: [log](https://cdn.discordapp.com/attachments/604300795579465739/739958842263207966/latest.log)
* Crash Log: No crash

## Client Information
* Modpack Version: 3.1.2 Hotfix 1
* Java Version: java --version
* Launcher Used: new
* Memory Allocated: ~6gb
* Server/LAN/Single Player: server
* Optifine Installed: no
* Shaders Enabled: no 

## World Information
* Modpack Version world created in: 3.1.2 Hotfix 1
* Additional Content Installed: no

**Comment by sam-kirby** [comment]
Can you please upload your crafttweaker.log file? Use https://paste.ubuntu.com and share a link to it here please.

**Comment by ozoromo** [comment]
Im getting a bad gateway on paste.ubuntu, also I noticed that im able to craft fiber mesh in singeplayer, just not on the server

**Comment by sam-kirby** [comment]
It's probably an issue with the server setup, perhaps you haven't uploaded the scripts directory?

This definitely works on a properly configured server.

For support setting up a server, please use https://discord.gg/darkosto
