### ISSUE TITLE
Latest version of SevTech Ages makes using Optifine with the pack impossible.

### ISSUE THREAD

**Issue by JoeGribble** [DarkPacks/SevTech-Ages#4213]
###  Bug Description
Trying to run the latest version of SevTech Ages with Optifine crashes the game on world generation 100% of the time. Does not happen without Optifine. Crash log attached.

### Did this behavior use to work in the previous version?
Yes. Only experiencing this issue with the latest version.

## Steps to Reproduce (for bugs)
1. Download SevTech Ages via the Twitch Desktop App.
2. Boot the game for the first time.
3. Close game, install Optifine.
4. Reboot game, generate any world and you'll encounter a crash.

## Logs
https://pastebin.com/L0Z51qUj

## Client Information
* Modpack Version: Latest
* Java Version: Latest
* Launcher Used: Twitch
* Memory Allocated: Preallocated
* Server/LAN/Single Player: All 3.
* Optifine Installed: Yes.
* Shaders Enabled:Yes. Sildur's Shaders High Preset.

## World Information
* Modpack Version world created in: Latest
* Additional Content Installed: None

**Comment by sam-kirby** [comment]
I know the pack has been tested using Optifine 1.12.2 HD U F5 - please update to that version.

**Comment by JoeGribble** [comment]
Optifine 1.12.2 HD U F5 + Sildur's Shaders High Preset crashes instantly on main menu load - Not sure if this is directly related to SevTech Ages or a Sildur's Shaders compatibility issue, so feel free to close if this is deemed irrelevant.

Pastebin of error: https://pastebin.com/2qErCdWz

**Comment by Kangy1103** [comment]
> Optifine 1.12.2 HD U F5 + Sildur's Shaders High Preset crashes instantly on main menu load - Not sure if this is directly related to SevTech Ages or a Sildur's Shaders compatibility issue, so feel free to close if this is deemed irrelevant.
> 
> Pastebin of error: https://pastebin.com/2qErCdWz

I am running 3.1.6 Hotfix 1 with OptiFine 1.12.2 HD U F5 with no issues. Also works with BSL shaders

**Comment by sam-kirby** [comment]
Based on the limited information available, I don't think this is an issue on our side.

Please feel free to reopen this if there is something we can do that will resolve it.

**Comment by burgrr** [comment]
Was able to recreate it myself.  Crashes on startup with 1.12.2 on latest version on MultiMC. https://pastebin.com/XZuGLcZw

**Comment by sam-kirby** [comment]
> Was able to recreate it myself. Crashes on startup with 1.12.2 on latest version on MultiMC. https://pastebin.com/XZuGLcZw

You are not using the latest version of Optifine. Try with G5.
