### ISSUE TITLE
Rustic Mod - Cabinets item issue

### ISSUE THREAD

**Issue by lmdpocus** [DarkPacks/SevTech-Ages#4214]
## Bug Description

Placing Rustic Cabinets and then removing them gives back on other item then the Rustic Cabinets in the inventory.

Version 1, before placing: 
![image](https://user-images.githubusercontent.com/1772909/89454979-da26d900-d761-11ea-932d-78ec03212b88.png)

Version 2, after placing:
![image](https://user-images.githubusercontent.com/1772909/89455007-e743c800-d761-11ea-9295-112e01da764f.png)

### Did this behavior use to work in the previous version?

No, in version 3.1.2 Hotfix 1 there was no problem with this.

## Steps to Reproduce (for bugs)

1. Place Rustic Cabinet
2. Remove Rustic Cabinet with Iron Lumberaxe or Obisdian Pickaxe
3. Getting items back, but not stacking with Rustic Cabinet in inventory

## Logs

* Client/Server Log:
Server Log:
https://pastebin.com/C8TDbeYk
Client Log:
https://pastebin.com/0gaB9hpa
* Crash Log:

## Client Information
* Modpack Version: 3.1.5
* Java Version: 1.8.0_231 64bit
* Launcher Used: MultiMC5 (0.6.12)
* Memory Allocated: !-- ✍️-->
![image](https://user-images.githubusercontent.com/1772909/89455823-33dbd300-d763-11ea-82c6-0fe02b57ce2b.png)
* Server/LAN/Single Player:
* Optifine Installed: no
* Shaders Enabled:

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed: 3.1.5

## Server Information
* Java Version: 8 (openjdk 1.8.0_252)
* Operating System: Linux 4.19.107 -> MineOS docker a1e583a
* Hoster/Hosting Solution: Own server
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
The item placed in the world has gained a tag. This is commonplace to allow e.g. picking up containers with items.

Unfortunately, it is only possible to stack exactly matching items, including tag.
