### ISSUE TITLE
Totemic Ceremonies Unable to Activate

### ISSUE THREAD

**Issue by segriago** [DarkPacks/SevTech-Ages#4215]
## Bug Description

 During age 0, in both client and server side, holding sneak while using a totem instrument does not activate the ceremony process. You receive particle effects indicating it should be activating, yet no gui appears to indicate the ceremony is beginning.

### Did this behavior use to work in the previous version?

3.1.2_Hotfix

## Steps to Reproduce (for bugs)

1. Equip totemic instrument
2. Right click while sneaking

## Logs

* Client/Server Log:
* Crash Log: No crashes due to bug

## Client Information
* Modpack Version:3.1.5
* Java Version: 8 version 261
* Launcher Used: ATLauncher
* Memory Allocated: 7,000
* Server/LAN/Single Player: Single/Server
* Optifine Installed:no
* Shaders Enabled:no

## World Information
* Modpack Version world created in:3.1.5
* Additional Content Installed:no

**Comment by sam-kirby** [comment]
You must be near a totem base for this to work.
