### ISSUE TITLE
Twilight Forest Crashing

### ISSUE THREAD

**Issue by Mysticlxl** [DarkPacks/SevTech-Ages#4217]
## Bug Description

When I am traveling around the Twilight Forest, I am usually fine for a bit, but then my server decides to crash.

### Did this behavior use to work in the previous version?

 N/A

## Steps to Reproduce (for bugs)

1. Walk around the twilight
2. Continue walking
3. Wait for a crash

## Logs

* Client/Server Log:https://pastebin.com/7XL8eDEH
* Crash Log:

## Client Information
* Modpack Version: 3.1.2 Hotfix-1
* Java Version: 1.8.0.51
* Launcher Used: Twitch
* Memory Allocated: 7GB
* Server/LAN/Single Player: Server
* Optifine Installed: N/A
* Shaders Enabled: N/A

## World Information
* Modpack Version world created in: 3.1.2 Hotfix-1
* Additional Content Installed: N/A

## Server Information
* Java Version: 1.8.0_252
* Operating System: Linux (amd64) version 3.10.0-1127.el7.x86_64
* Hoster/Hosting Solution:  MC Pro Hosting 
* Sponge (Non-Vanilla Forge) Server: N/A

**Comment by 24680FPIC** [comment]
This is a performance issue. A ServerHangWatchdog crash is caused by a server skipping more than a certain amount of ticks (in this case, 60 seconds), due to it being overloaded. It's recommended to go to server.properties and set max-tick-time to -1 to disable the watchdog entirely.

**Comment by sam-kirby** [comment]
No, it is not recommended you disable the watchdog - do not do this.

**Comment by 24680FPIC** [comment]
What's wrong with disabling the watchdog?

**Comment by ROMVoid95** [comment]
If your able too. try adding `-Xss1M` before your `-Xmx` java arguments. 

I had a similar issue when using OpenJDK on my VM and it stopped occurring after adding this, From what i was able to gather after getting a HeapDump and following the stack-trace it stemmed from -> (**In case this might be helpful to someone**)
`"Chunk I/O Executor Thread-1" Id=<#id> WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@256b3495
	at sun.misc.Unsafe.park(Native Method)`
The thread is waiting on a ReadLock (as well as others) however the same thread held a WriteLock, Could only assume the thread was ignoring or swallowing its own SOE so the WriteLock is never released.
