### ISSUE TITLE
[Immersive Engineering] Metal press graphic glitch

### ISSUE THREAD

**Issue by slavaider** [DarkPacks/SevTech-Ages#4219]
![2020-08-17_16 02 31](https://user-images.githubusercontent.com/55443387/90389595-4fb87080-e0a3-11ea-87f5-6a97d82ddcf1.png)

**Comment by sam-kirby** [comment]
I have no idea why the bot thinks this matches the template, but it doesn't.

Without more details there isn't any realistic possibility of this being resolved, so I'm closing it. Please submit a new issue with the requested details.
