### ISSUE TITLE
[3.1.6 hotfix 1] the game crashes when launching the modpack

### ISSUE THREAD

**Issue by Krzysztof23** [DarkPacks/SevTech-Ages#4223]
## Bug Description

  the game unexpected  crashes when launching the modpack
                    [https://cdn.discordapp.com/attachments/546059901781278721/746641643867865088/crash.jpg](url)

### Did this behavior use to work in the previous version?

  I have never had a similar error when starting this modpack

## Steps to Reproduce (for bugs)

 
the error occurs every time you try to run the modpack
1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log: the game does not create a crash log, it only shows an error

## Client Information
* Modpack Version:3.1.6 hotfix 1
* Java Version:1.8.0_261
* Launcher Used: launcher in twitch app
* Memory Allocated: 12 GB
* Server/LAN/Single Player: single player
* Optifine Installed: yes OptiFine_1.12.2_HD_U_F4
* Shaders Enabled:yes

## World Information
* Modpack Version world created in: 3.1.5
* Additional Content Installed: none

**Comment by sam-kirby** [comment]
Please include a log or crash report. You can find one by right clicking the profile in the Twitch launcher, selecting go to folder and going to either the `crash-reports` folder or the `logs` folder. Please either upload the most recent crash report or `latest.log`.

**Comment by Krzysztof23** [comment]
sorry for problems and unnecessary report reinstalling modpack solved the problem
