### ISSUE TITLE
I just started and there are many bugs that make starting impossible.

### ISSUE THREAD

**Issue by thetntchicken** [DarkPacks/SevTech-Ages#4224]
## Bug Description

 
1. To get flint, you need to craft plant fiber mesh, but to make mesh, you need grass fiber which is crafted with grass. To get grass you need shears. This makes it impossible to get flint unless I stumble upon 2 iron for shears. 

2. I can craft planks in my inventory. When i click on the chopping block, it just places the log on top, but i can just use inventory to make planks, which isn't supposed to happen.

### Did this behavior use to work in the previous version?

 I have not played previous versions.

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 3.1,2 hotfix 1
* Java Version:1.12.2
* Launcher Used: Twitch launcher
* Memory Allocated: Full 12,000 mb or something
* Server/LAN/Single Player: singleplayer
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in: 1.12.2
* Additional Content Installed:

**Comment by sam-kirby** [comment]
Please share your crafttweaker.log file.

**Comment by sam-kirby** [comment]
I'm closing this as this sounds like you either attempted to modify the pack and broke the scripts, or Twitch failed to install it. Neither of these issues can be solved by us. I suggest reinstalling and playing a clean version.

If you need further support, try the Discord: https://discord.gg/darkosto
