### ISSUE TITLE
Bedrock regeneration message console spam

### ISSUE THREAD

**Issue by Kangy1103** [DarkPacks/SevTech-Ages#4225]
## Bug Description

 Hope you are well! My server is constantly outputting the following message: 
23.08 12:19:46 [Server] Server thread/INFO [bringbedrockback]: Regenerate bedrock chunk at:[-3, 15]
It's a brand new install that hasn't even had anyone log into it yet.

### Did this behavior use to work in the previous version?

N/A

## Steps to Reproduce (for bugs)

1. Install pack on server
2. Start server
3. Observe message

## Logs

* Client/Server Log: 23.08 12:19:46 [Server] Server thread/INFO [bringbedrockback]: Regenerate bedrock chunk at:[-3, 15]
* Crash Log: N/A

## Client Information
* Modpack Version: 3.1.6 Hotfix 1
* Java Version: 1.8.0.261
* Launcher Used:Twitch Launcher
* Memory Allocated: 6GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.1.6 Hotfix 1
* Additional Content Installed: Discord-integration

## Server Information
* Java Version: Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_211
* Operating System: Linux
* Hoster/Hosting Solution: Shockbyte
* Sponge (Non-Vanilla Forge) Server: No

![image](https://user-images.githubusercontent.com/42292756/90978277-8d564700-e544-11ea-8ac7-65bc790aed0f.png)

**Comment by sam-kirby** [comment]
Resolved in 3.1.7
