### ISSUE TITLE
ERROR when downloading

### ISSUE THREAD

**Issue by DieBemme** [DarkPacks/SevTech-Ages#4228]
## Bug Description

I want to download the modpack in the AT-Launcher, but after around 30 seconds an ERROR message keeps popping up, preventing me from downloading.

### Did this behavior use to work in the previous version?

 Didn't try a different version.

## Steps to Reproduce (for bugs)

1. Open AT-Launcher.
2. Select Version of the modpack.
3. Start the download.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sam-kirby** [comment]
We cannot fix issues in ATLauncher. Please report this to them at https://github.com/ATLauncher/ATLauncher
