### ISSUE TITLE
Changing tooltips for ST:AotS

### ISSUE THREAD

**Issue by 04Slash** [DarkPacks/SevTech-Ages#4241]
## Context
This is for Sevtech Ages of the Sky.
Yesterday on Darkosto's stream he mentioned wanting to change some tooltips but didn't know if this was possible. This is possible with crafttweaker (see example script below, using the items Darko wanted to change).

My goal will be to change any tooltips that are not easily readable (most likely all red tooltips) to a more readable color. I'm willing to go through and make all these changes myself. If there are any other changes you would like me to do while doing this let me know and I'll see what I can do. Before I start this I got a few questions:
1. Is this something that you want done?
2. Is there a better way to format the script? I'm familiar with the basics of CT but I'm not sure if it's possible to use the same method that is used to add tooltips, to remove tooltips. This isn't a huge deal for me, just asking so it doesn't look awful.
3. What tooltip color(s) are you looking to change? What color should I use for replaced tooltips? I will not change any colors that don't need to be changed and organize everything back into the same order, as shown in the script/example. If requested, I can also change all tooltips for said items to match the new/changed tooltip color.
4. Would you like me to add these changes into the existing tooltip.zs file or would a new file be acceptable?

## Config/Script Details
[Script](https://pastebin.com/dBiRTHc4) that removes existing tooltips and adds them with the suggested typo fix during stream, and changed the green tooltip to blue to match. The color is easily changeable. 
[Pictures of said changes](https://imgur.com/a/f7V49ha).
[Link to the CT page for removing tooltips](https://docs.blamejared.com/1.12/en/Vanilla/Items/Tooltips/). Probably not needed but adding for a quick reference.
[Stream link](https://www.twitch.tv/videos/734220655?t=4h44m18s) - When Darkosto mentions he doesn't know if he can change existing tooltips (cause why not).

**Comment by 04Slash** [comment]
Bad bot >:(
I'd imagine it's because I removed the "(if desired)" after Config/Script Details? If it is, whoops..

**Comment by sam-kirby** [comment]
That is the reason, yes.
