### ISSUE TITLE
The return portal from the Beneath will suffocate you in blocks.

### ISSUE THREAD

**Issue by snydej** [DarkPacks/SevTech-Ages#4242]
## Bug Description
The return portal from the Beneath does not check to see if there are blocks where it spawns you nor does it do the sane thing and put you on top of the portal. I even have 3x3 centered on the portal where it could have safely spawned me but, for reasons I cannot fathom, it spawned me 2 blocks away, inside the frame of my hunting dimension portal.

### Did this behavior use to work in the previous version?
I haven't tested other versions.

## Steps to Reproduce (for bugs)
Here's the setup:
![2020-09-10_10 01 54](https://user-images.githubusercontent.com/2817309/92768251-b2bcc080-f34c-11ea-8074-7e644a972774.png)

The the blocks chopped out of the portal are where it decided to spawn me.

## Logs
N/A

## Client Information
* Modpack Version: 3.1.7
* Java Version: 1.8.0_212
* Launcher Used: MultiMC
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.1.2 Hotfix 1
* Additional Content Installed: None

**Comment by snydej** [comment]
And to top it off the return portals are unbreakable. So now that I've moved the entrance portal, I'm stuck with two portals, one of which may try to kill me.

![2020-09-10_10 30 12](https://user-images.githubusercontent.com/2817309/92772799-e568b800-f350-11ea-8e12-e2b1ee94cbca.png)

**Comment by sam-kirby** [comment]
The beneath teleporters appear to be very simple; they will teleport you to the same block position in the overworld as you were in in the beneath when you right clicked it. This means if you stand two blocks to the north of the teleporter and right click it, you will appear in the overworld two blocks to the north of the corresponding teleporter.

If you want to make sure you come back in a predictable place, try activating the teleporter whilst standing on top of it.

You should be able to remove them using commands or creative mode.
