### ISSUE TITLE
SevTech: AoTS - Twilight Forest/Hunting Dimension generation issues

### ISSUE THREAD

**Issue by Alexithemia** [DarkPacks/SevTech-Ages#4246]
## Bug Description
Twilight Forest only generates landmarks, lich castle, mounds etc. If this is intentional, Volarkite does not get updrafts in this dimension for travel. Hunting dimension generates empty, you can build a spawn area for mobs, I don't know if this was intentional.

### Did this behavior use to work in the previous version?
N/a

## Steps to Reproduce (for bugs)
1. Create a Twilight Forest portal and enter
2. Try to travel with Volarkite
3. Create Hunting Dimension and enter

## Logs
Log of Twilight Forest Generation
https://gist.github.com/Alexithemia/5febca519e57439256e99228c926784d

## Client Information
* Modpack Version: 3.2.0 Alpha 2
* Java Version: 1.8.0_251
* Launcher Used: Twitch
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: No changes from pack defaults
* Additional Content Installed: None

**Comment by sam-kirby** [comment]
Leaving this open as I think that there being no warning that the Volarkite will not get updrafts in the TF is less than ideal.

**Comment by sam-kirby** [comment]
This is now resolved as of sam-kirby/drafty-kites@16a10a6
