### ISSUE TITLE
crashes with optifine

### ISSUE THREAD

**Issue by reyjkw** [DarkPacks/SevTech-Ages#4248]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:https://pastebin.com/12mXicQK

## Client Information
* Modpack Version:3.2.0
* Java Version:1.8.0_261
* Launcher Used:T-Launcher
* Memory Allocated:16gb
* Server/LAN/Single Player:Single Player
* Optifine Installed: i guess i do
* Shaders Enabled:tried with shaders and without and both crash

## World Information
* Modpack Version world created in:3.2.0
* Additional Content Installed:nothing

**Comment by sam-kirby** [comment]
Update Optifine.
