### ISSUE TITLE
SevTech: AoTS Liveroot does not generate (progression block)

### ISSUE THREAD

**Issue by Alexithemia** [DarkPacks/SevTech-Ages#4250]
## Bug Description
Liveroot does not spawn in Twilight Forest as there are no caves, only roots that exist are under trees in hedge mazes and they are all regular roots. Liveroot is required for progression, to make Astral Sorcery's Celestial Altar, which is required to make the coal engine to finish Age 2.

### Did this behavior use to work in the previous version?
N/a

## Steps to Reproduce (for bugs)
1. Enter Twilight Forest dimension
2. No caves upon searching/live root only spawns on cave walls.
3. Only roots that exist are under Hedge maze trees.

## Client Information
* Modpack Version: 3.2.0 Alpha 2
* Java Version: 1.8.0_251
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: Pack default
* Additional Content Installed: None

**Comment by Seegras** [comment]
Can confirm, same findings

**Comment by sam-kirby** [comment]
It spawns in hollow hills chests, so it's not impossible right now. We are looking to make this easier.

**Comment by Seegras** [comment]
.. and I guess torchberries the same?

**Comment by niet-dev** [comment]
Correct. I'll confirm that I was able to get all of the required materials for any twilight-related progression through chests.

**Comment by Drarthe** [comment]
They might spawn in chests, but it must be a low rate as I ended up hitting every chest that I could find with only 3 living roots and no torchberries to show for the hours of searching.  The Twilight wiki says they should spawn in hollow hills as well, but no luck there either.

**Comment by sam-kirby** [comment]
This was fixed in ee3a695dafdb2888a5d259a85735ae72576645d6 - can be found in lot more loot tables now.
