### ISSUE TITLE
Work Stump Mk2 Crafting

### ISSUE THREAD

**Issue by ChosenArchitect** [DarkPacks/SevTech-Ages#4252]
## Bug Description

There seems to be an inconsistency with crafting recipes pertaining to work stumps. The standard work stump can be crafting with any log. The work Stump Mk2 however requires Dark Oak, Eucalyptus, and Sakura Logs only.

### Did this behavior use to work in the previous version?

No other version to compare with.

## Steps to Reproduce (for bugs)

1. Craft a Work Stump Mk2

## Logs

* Client/Server Log:
N/A
* Crash Log:
N/A

## Client Information
* Modpack Version: 3.2.0-alpha.2-skyblock
* Java Version: 1.12.2
* Launcher Used: Twitch
* Memory Allocated: 8G
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: Yes

## World Information
* Modpack Version world created in: 3.2.0-alpha.2-skyblock
* Additional Content Installed: N/A

**Comment by sam-kirby** [comment]
This is deliberate - the wood required is harder to obtain.

**Comment by ChosenArchitect** [comment]
KK Thanks!
