### ISSUE TITLE
Game wont load and get Error.

### ISSUE THREAD

**Issue by Mirsche** [DarkPacks/SevTech-Ages#4257]
<!--Hello Guys 

im new here but played every Pack from darkosto :)

Now i have a Problem to Load the New Sevtechages Skyblock Modpack.
I get an Error Report:
net.minecraftforge.fml.common.LoaderExeption:thebetweenlands Failed to load new mod instance.
Exit Code: -1

I searched for any Issues Report but cant find one.
Can someone help me and explain how to fix these issus ?

Mirsche

**Comment by sam-kirby** [comment]
You should try the discord; https://discord.gg/darkosto
