### ISSUE TITLE
Age 3 Enter the Nether Advancement does not unlock SevTech: AotS

### ISSUE THREAD

**Issue by Alexithemia** [DarkPacks/SevTech-Ages#4264]
## Bug Description
Entering the nether does not unlock advancement in age 3.

### Did this behavior use to work in the previous version?
Works in SevTech: Ages, not Skyblock

## Steps to Reproduce (for bugs)
1. Get to Age 3.
2. Make portal, Enter nether.
3. No advancement.

## Logs
No log :(

## Client Information
* Modpack Version: 3.2.0-alpha.2
* Java Version: 1.8.0_251
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: Pack default
* Additional Content Installed: None

**Comment by justinrusso** [comment]
Fixed in 00b7a3e081f74df52bb49e4a47cd8fc155cb6088
