### ISSUE TITLE
Yew Sticks not recognized as sticks

### ISSUE THREAD

**Issue by Mechadomish** [DarkPacks/SevTech-Ages#4267]
## Bug Description

Yew Sticks are not being recongized as sticks for other crafting purposes

## Steps to Reproduce (for bugs)

1. Obtain Yew Sticks
2. Try to use them for crafting.
3. ???

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 3.0.Alpha2-Skyblock
* Java Version:8 64 bit
* Launcher Used:MultiMC
* Memory Allocated: 8MB
* Server/LAN/Single Player:Single
* Optifine Installed:No
* Shaders Enabled:No

## World Information
* Modpack Version world created in:Same as version
* Additional Content Installed:None

**Comment by calog3no** [comment]
I believe yew sticks have never been used as crafting sticks in regular SevTech

**Comment by Hillgrove** [comment]
^  correct. I'm in age 3 atm (original Sevtech) and they have zero uses so far.

**Comment by Darkosto** [comment]
Just added into dev. Will be out for Alpha 3 and regular Sevtech branches.

Thank you!
