### ISSUE TITLE
Age 2 Advancements

### ISSUE THREAD

**Issue by ChosenArchitect** [DarkPacks/SevTech-Ages#4274]
## Bug Description

After I completed the "Upgrade Your Prospects" advancement. "Roses are Red, Lapis is Blue" + "Iron Sights" also completed. If its like the others I would assume that you need the Items in order to complete it. I don't have the items no have I had the items as they were blocked in JEI. This might be a one off thing... needs more testing. 

### Did this behavior use to work in the previous version?

 NA

## Steps to Reproduce (for bugs)

1. Complete up to Age 2 "Glass Blowing" Advancement.
2. Craft Item **Tough Dowsing Rod**
3. Should see Lapis and Iron Advancement Complete. (Keep in mind I have also explored if it is based on Biomes explored. If that is the case it is not consistent with the other advancments)

## Logs

* Client/Server Log: NA
* Crash Log: 
![Imgur](https://i.imgur.com/CDMLSTi.png)

## Client Information
* Modpack Version: 3.2.0-alpha.2-skyblock
* Java Version: 1.12.2
* Launcher Used: Twitch
* Memory Allocated: 8G
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: Yes

## World Information
* Modpack Version world created in: 3.2.0-alpha.2-skyblock
* Additional Content Installed: NA

**Comment by sam-kirby** [comment]
Both of these advancements are granted when you break the ore block.

If you mined inside an island with these ores previously and broke the block whilst it was disguised this may have counted at that point; is this a possiblity?

**Comment by Darkosto** [comment]
This is working as intended, I'm okay with how the advancements are triggering. Thank you for the report! <3
