### ISSUE TITLE
hunting dimension is blank

### ISSUE THREAD

**Issue by alexHunter854** [DarkPacks/SevTech-Ages#4278]
### Did this behavior use to work in the previous version?

huntig  dimension is blank

## Steps to Reproduce (for bugs)

1. open huntig dimension portal
2. enter
3. and boom you have a blank hunting dimension

## Logs
there was no crash

## Client Information
* Modpack Version:3.2.0 alpha 2
* Java Version: 1.8.0_51
* Launcher Used: regular
* Memory Allocated: 7144mb
* Server/LAN/Single Player: single player
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in: 3.2.0 alpha 2
* Additional Content Installed: none

**Comment by Darkosto** [comment]
Is this bug reporting that SevTech Skyblock modpack has a skyblock hunting dimension?

**Comment by alexHunter854** [comment]
I just thought it would have islands like the beneath and the overworld, sorry for my stupidity

**Comment by Darkosto** [comment]
No problem. This dimension was edited custom for the pack since having it retain normal generation wouldn't be consistent with the aim of the pack.
