### ISSUE TITLE
Totemic: Unable to select ceremonies

### ISSUE THREAD

**Issue by purestone9** [DarkPacks/SevTech-Ages#4285]
## Bug Description

Unable to eslect Totemic Ceremonie

### Did this behavior use to work in the previous version?

Unknown

## Steps to Reproduce (for bugs)

https://youtu.be/tJeYOmWpzxQ

## Client Information
* Modpack Version:3.2.0 alpha 2
* Java Version: V8 U261
* Launcher Used: Twitch
* Memory Allocated: 12288 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.2.0 aplha 2
* Additional Content Installed: None

**Comment by sam-kirby** [comment]
Make sure you have a Totem base close to you - I'm not having issues starting ceremonies.
