### ISSUE TITLE
Stick recipe "Saw" is wrong - Sevtech Age of the Sky - SOLVED

### ISSUE THREAD

**Issue by AtPMonster** [DarkPacks/SevTech-Ages#4292]
## Bug Description

Hello there,

the Stick recipe in JEI with the SAW usage is bugged. It says you need to use Slabs of any kind, but it actually requires Thin Slabs, so the next one after normal Slabs.

### Did this behavior use to work in the previous version?

 I dont know. Didnt check in normal Sevtech.

## Steps to Reproduce (for bugs)

1. Go to ur Saw (Better with Mods)
2. Place planks on it
3. Get slabs
4. Try to use them on the Saw and get Thin Slabs and not sticks.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:3.2.0 Alpha 2
* Java Version:
* Launcher Used:Twitch
* Memory Allocated:10GB
* Server/LAN/Single Player:SP
* Optifine Installed:Yes
* Shaders Enabled:No

## World Information
* Modpack Version world created in:SevTech: Ages of the Sky 3.2.0 Alpha 2
* Additional Content Installed: Only Optifine

**Comment by Darkosto** [comment]
Just checked this out and JEI is showing the correct information. I think you might be assuming it's showing all slabs when it's only showing a handful of them. It's mostly Natura a few other random ones. I would double check JEI again to see which slabs it's cycling through and let me know if yours is any different.

**Comment by AtPMonster** [comment]
> Just checked this out and JEI is showing the correct information. I think you might be assuming it's showing all slabs when it's only showing a handful of them. It's mostly Natura a few other random ones. I would double check JEI again to see which slabs it's cycling through and let me know if yours is any different.

my bad. Its solved!
