### ISSUE TITLE
JourneyMap Unlocked age 1 - Alpha 3

### ISSUE THREAD

**Issue by willownezz** [DarkPacks/SevTech-Ages#4303]
## Bug Description

Just installed the new Alpha 3 from Sevtech Skys, and JourneyMap is now available. I am on age 1

**Edit: More items may be unlocked, now I have 83 pages on JEI on age 1 pretty sure that I can see many more recipes now.**

### Did this behavior use to work in the previous version?

Alpha 2 Journey map was locked in age 1

## Steps to Reproduce (for bugs)

1.Install Alpha 3
2.Start map
3.press B map opens

## Logs

* Client/Server Log:N/A
* Crash Log: N/A

## Client Information
* Modpack Version:SevTech-Ages-of-the-Sky_3.2.0-alpha.3-skyblock
* Java Version: 1.8.0.51
* Launcher Used:Twitch
* Memory Allocated: 12GB
* Server/LAN/Single Player: SP
* Optifine Installed: NO
* Shaders Enabled: NO

## World Information
* Modpack Version world created in: SevTech-Ages-of-the-Sky_3.2.0-alpha.2-skyblock
* Additional Content Installed: N/A

**Comment by sam-kirby** [comment]
Fixed by #4308, please update to alpha 4.
