### ISSUE TITLE
Geolosys Samples not Hidden / in JEI items are not hidden either

### ISSUE THREAD

**Issue by LittleFootNCera** [DarkPacks/SevTech-Ages#4304]
## Bug Description

Just Started up a new sevtech skyblock world for the new alpha (3) and found malachite samples literally right at spawn, no advancements achieved. JEI items are also searchable, right from the start as well.

### Did this behavior use to work in the previous version?

i believe so...

## Steps to Reproduce (for bugs)

1.Load sevtech ages of the sky, (alpha 3)
2.Create new world
3.Look for geolosys samples (only found malachite so far)
4.Load inventory, see all the JEI items

## Logs

* Client/Server Log:https://pastebin.pl/view/72dd7713
* Crash Log:

## Client Information
* Modpack Version:SevTech-Ages-of-the-Sky_3.2.0-alpha.3-skyblock
* Java Version:1.8.0_51
* Launcher Used:twitch/ native minecraft (my twitch doesnt like to load modpacks so i download from twitch and use the native minecraft launcher to load them.)
* Memory Allocated:8GB
* Server/LAN/Single Player:Single Player
* Optifine Installed:No

## World Information
* Modpack Version world created in:Same as above
* Additional Content Installed:No

**Comment by willownezz** [comment]
mine too, from what I have seen everything is unlocked, just found cinnabar samples on age 1

**Comment by LittleFootNCera** [comment]
And Lapis too.

**Comment by sam-kirby** [comment]
This is fixed by #4308, please update to alpha 4.
