### ISSUE TITLE
It crushes when i am traveling

### ISSUE THREAD

**Issue by Smokeboy-ya** [DarkPacks/SevTech-Ages#4306]
## Bug Description
Client crash

## Steps to Reproduce (for bugs)
1.i was traveling 
2.
3.

## Logs

* Client/Server Log:
* Crash Log:Exception in thread "Thread-267" Sep 26, 2020 7:40:19 AM net.gobbob.mobends.util.BendsLogger info
INFO: Registering Animated Entities...
Sep 26, 2020 7:40:19 AM net.gobbob.mobends.util.BendsLogger info
INFO: Registering Player
Sep 26, 2020 7:40:19 AM net.gobbob.mobends.util.BendsLogger info
INFO: Registering Zombie
Sep 26, 2020 7:40:19 AM net.gobbob.mobends.util.BendsLogger info
INFO: Registering Husk
Sep 26, 2020 7:40:19 AM net.gobbob.mobends.util.BendsLogger info
INFO: Registering Spider
Sep 26, 2020 7:40:19 AM net.gobbob.mobends.util.BendsLogger info
INFO: Registering Cave Spider
Sep 26, 2020 7:40:19 AM net.gobbob.mobends.util.BendsLogger info
INFO: Registering Skeleton
Sep 26, 2020 7:40:19 AM net.gobbob.mobends.util.BendsLogger info
INFO: Registering Wither Skeleton
Sep 26, 2020 7:40:19 AM net.gobbob.mobends.util.BendsLogger info
INFO: Registering Stray
Exception in thread "Client Shutdown Thread" AL lib: (EE) alc_cleanup: 1 device not closed
Picked up _JAVA_OPTIONS: -Xmx8192M

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:8gb
* Server/LAN/Single Player:single
* Optifine Installed:no
* Shaders Enabled:no

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by Smokeboy-ya** [comment]
Exception in thread "Thread-267" Sep 26, 2020 8:50:42 PM net.gobbob.mobends.util.BendsLogger info
INFO: Registering Animated Entities...
Sep 26, 2020 8:50:42 PM net.gobbob.mobends.util.BendsLogger info
INFO: Registering Player
Sep 26, 2020 8:50:42 PM net.gobbob.mobends.util.BendsLogger info
INFO: Registering Zombie
Sep 26, 2020 8:50:42 PM net.gobbob.mobends.util.BendsLogger info
INFO: Registering Husk
Sep 26, 2020 8:50:42 PM net.gobbob.mobends.util.BendsLogger info
INFO: Registering Spider
Sep 26, 2020 8:50:42 PM net.gobbob.mobends.util.BendsLogger info
INFO: Registering Cave Spider
Sep 26, 2020 8:50:42 PM net.gobbob.mobends.util.BendsLogger info
INFO: Registering Skeleton
Sep 26, 2020 8:50:42 PM net.gobbob.mobends.util.BendsLogger info
INFO: Registering Wither Skeleton
Sep 26, 2020 8:50:42 PM net.gobbob.mobends.util.BendsLogger info
INFO: Registering Stray
Exception in thread "Client Shutdown Thread" AL lib: (EE) alc_cleanup: 1 device not closed
Picked up _JAVA_OPTIONS: -Xmx8192M

Got same error at alpha 2

**Comment by sam-kirby** [comment]
Please update to alpha 4.
