### ISSUE TITLE
Different grass fiber mesh craft / messed up era progression 

### ISSUE THREAD

**Issue by MrPointlezz** [DarkPacks/SevTech-Ages#4307]
## Bug Description

Can't craft grass fiber mesh and looks like era progression is messed up

### Did this behavior use to work in the previous version?

Everything was normal in alpha 2

## Steps to Reproduce (for bugs)

1.Create a new world
2.Try to craft grass fiber mesh

## Client Information
* Modpack Version:Alpha 3
* Java Version:Java 8
* Launcher Used:MultiMC
* Memory Allocated:10gb
* Server/LAN/Single Player:LAN/Singleplayer
* Optifine Installed:Yes
* Shaders Enabled:Yes

## World Information
* Modpack Version world created in:Alpha 3
* Additional Content Installed:No

**Comment by sam-kirby** [comment]
Thank you for reporting this, I have uploaded a new alpha (alpha 4) to Curseforge which fixes this - it is currently pending approval.
