### ISSUE TITLE
not getting my advancement after going to nether.

### ISSUE THREAD

**Issue by otwtobi** [DarkPacks/SevTech-Ages#4309]
hey ive went to nether and ive not got my advancement for going to nether, how do i fix this?

## Bug Description

hey ive went to nether and ive not got my advancement for going to nether, how do i fix this?

### Did this behavior use to work in the previous version?

ive only played the sevtech ages of the sky, so im not sure.

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:
[2020-09-26-5.log1.txt](https://github.com/DarkPacks/SevTech-Ages/files/5287078/2020-09-26-5.log1.txt)

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sam-kirby** [comment]
Update to alpha 4.
