### ISSUE TITLE
Strange grave spawn locations

### ISSUE THREAD

**Issue by MrPointlezz** [DarkPacks/SevTech-Ages#4311]
## Bug Description

When you die in the void, grave sometimes spawns in void, or somewhere under island. It's very annoying, as you need to make a water canal to get your items back.

### Did this behavior use to work in the previous version?

All versions, i guess

## Steps to Reproduce (for bugs)

1.Fall in void
2.See that your grave is in void or on an island ledge.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:Alpha 2-4
* Java Version:Latest java 8
* Launcher Used:MultiMC
* Memory Allocated:10gb
* Server/LAN/Single Player:LAN/SP
* Optifine Installed:Yes
* Shaders Enabled:Yes

## World Information
* Modpack Version world created in:Alpha 2
* Additional Content Installed:No

**Comment by Darkosto** [comment]
This is just the nature of how grave mods will work. They attempt to find a 'safe' location that is attached to solid land. If they cannot, they will spawn in the void. This is a limitation with the graves mod in conjunction with a skyblock world. There is not much we can do about this to always make it scan and attach in more convenient place.
