### ISSUE TITLE
Nether advancement wouldn't complete

### ISSUE THREAD

**Issue by Permarin1** [DarkPacks/SevTech-Ages#4312]
## Bug Description

 When traveling to the nether the advancement would not complete, had to use / command for it to complete.

### Did this behavior use to work in the previous version?

 N/A?

## Steps to Reproduce (for bugs)

1. i dont know why it wouldn't complete, i lit the portal frame, and went in, even found a fortress but i had to manually complete it.
2.
3.

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information
* Modpack Version: 3.2.0-alpha.2-skyblock
* Java Version:version 8 update 261 (build 1.8.0_261-b12)
* Launcher Used: Twitch
* Memory Allocated: 7500 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in: 3.2.0-alpha.2-skyblock
* Additional Content Installed: no

**Comment by sam-kirby** [comment]
Update to alpha 4.
