### ISSUE TITLE
Skyblock Advancement Heat Map

### ISSUE THREAD

**Issue by ChosenArchitect** [DarkPacks/SevTech-Ages#4314]
## Bug Description

 The "Enter the Nether" advancement in Age 3 still mentions a logical heat map.

### Did this behavior use to work in the previous version?

 n/a

## Steps to Reproduce (for bugs)

n/a

## Logs

* Client/Server Log: n/a
* Crash Log: n/a

## Client Information
* Modpack Version: 3.2.0-alpha.4-skyblock
* Java Version: 1.8.0 Update 261
* Launcher Used: Twitch
* Memory Allocated: 8G
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: Yes

## World Information
* Modpack Version world created in: 3.2.0-alpha.2-skyblock
* Additional Content Installed: Replay Mod

**Comment by Darkosto** [comment]
Fixed up! Should be out for the next update. Thanks!
