### ISSUE TITLE
Crash upon placing Fire Pit

### ISSUE THREAD

**Issue by moon-st0ne** [DarkPacks/SevTech-Ages#4316]
Picked up an empty fire pit that had gone unused for ages intending to move it somewhere else. Placed it down and the game crashed to launcher instantly. Not sure what could've caused that. 

[crash-2020-09-30_01.46.57-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/5308496/crash-2020-09-30_01.46.57-client.txt)
[crash-2020-09-30_16.09.00-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/5308497/crash-2020-09-30_16.09.00-server.txt)

**Comment by moon-st0ne** [comment]
well it sure would be nice of you to include this template when i'm making a new post, but literally all you did was tell me to check if the issue already existed before posting.

**Comment by sam-kirby** [comment]
When clicking the "New Issue" button, you get a choice of templates to use. We do not accept issue reports that do not use one of our templates.

If you choose to open a blank issue, the help comment is provided by Github, not us. We cannot use it to warn you that your report will not be accepted as you've bypassed the templates we provide.

![image](https://user-images.githubusercontent.com/23245543/94746861-91f8f100-0375-11eb-8dad-089fc795a504.png)

We would appreciate it if you could resubmit your issue using the appropriate template.

https://github.com/DarkPacks/SevTech-Ages/issues/new/choose
