### ISSUE TITLE
Misleading advancement "Under Da Sea Lantern" - No Ocean Monuments (SevTech: Ages of the Sky)

### ISSUE THREAD

**Issue by Hamredahl** [DarkPacks/SevTech-Ages#4317]
## Bug Description

In Age 2, the advancement "Under Da Sea Lantern" states that one should locate Prismarine from an Ocean Monument or as drop from the Twilight Forest. Correct me if I'm wrong, but Sea Monuments don't seem to spawn at all in Skyblock Ocean Biomes, and that part should therefore be removed from the advancement, leaving only the Twilight Forest as a source of Sea Lanterns/Prismarine. 

### Did this behavior use to work in the previous version?

N/A

## Steps to Reproduce (for bugs)

N/A

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information
* Modpack Version: 3.2.0 Alpha 4
* Java Version: Java 8 Update 261
* Launcher Used: Twitch
* Memory Allocated:8 GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.2.0 Alpha 4
* Additional Content Installed: N/A

**Comment by Darkosto** [comment]
Changed the advancement text. Will be out in the next update.

**Comment by avicuz** [comment]
Hmm There're no Ocean Monuments which spawns guardian for RFtool peaceful module

**Comment by sam-kirby** [comment]
> Hmm There're no Ocean Monuments which spawns guardian for RFtool peaceful module

This needs to be its own issue please!
