### ISSUE TITLE
Age 4 Ore Procpector not detecting nether related ores other then quartz 

### ISSUE THREAD

**Issue by eitankushnir** [DarkPacks/SevTech-Ages#4318]
## Bug Description

 basically when i tried to locate amethyst and cobalt that were right below me the porcpector did not detect them

### Did this behavior use to work in the previous version?

i am not sure if it was in alpha 2 but i know it is in alpha 4

## Steps to Reproduce (for bugs)

1. get a age 4 ore procpector 
2. try to detect either amethyst ardite or cobalt ore 
3. it wont detect it 

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: Alpha 4
* Java Version:8
* Launcher Used:Twitch
* Memory Allocated:8 gigs
* Server/LAN/Single Player: Server
* Optifine Installed:no
* Shaders Enabled:no

## World Information
* Modpack Version world created in:Alpha 2 (prier version)
* Additional Content Installed:none

**Comment by Darkosto** [comment]
This has never been a feature in the prospectors mod to locate those specific ores. The reason was they were normal generation in comparison to the overworld ores and prospectors were meant to help the player out. I can add them to the prospectors for the next alpha update.

**Comment by sam-kirby** [comment]
Prospectors were previously able to detect ores from NetherEx, though this was broken when NetherEx changed their IDs.

**Comment by d-patyk** [comment]
Amethyst is currently available in age 3, but age 3 prospector can't detect it.
And also the "nex:quartz_ore"s (config has nex:ore_quartz)
