### ISSUE TITLE
Resplendent Prism Recipe - No Trollber (SevTech: Ages of the Sky)

### ISSUE THREAD

**Issue by Hamredahl** [DarkPacks/SevTech-Ages#4322]
## Bug Description

 Trollber do not spawn naturally in the Troll Caves, nor are they found in any chests in the Twilight Forest, but are needed when crafting a Resplendent Prism.

### Did this behavior use to work in the previous version?

 N/A

## Steps to Reproduce (for bugs)

 N/A

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information
* Modpack Version: 3.2.0 Alpha 4
* Java Version: Java 8 Update 261
* Launcher Used: Twitch
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.2.0 Alpha 4
* Additional Content Installed: N/A

**Comment by Darkosto** [comment]
Added into Twilight Forest chests for the next update.
