### ISSUE TITLE
[ST: AotS] Can't craft grass fiber mesh in 3.2.0-alpha.4 with Skyblock

### ISSUE THREAD

**Issue by mythmon** [DarkPacks/SevTech-Ages#4328]
## Bug Description
When starting on a new skyblock world on a multiplayer server, although the grass fiber mesh appears in JNEI and JNEI will copy the items into the crafting grid, the result box of the crafting operation is empty. I can't craft grass fiber mesh, even though JNEI things I should be able to.

### Did this behavior use to work in the previous version?
This is the first version of the mod I have played.

## Steps to Reproduce (for bugs)
1. Start a new game
2. Gather sticks and plant fiber
3. Make plant twine
4. Select the grass fiber mesh from JNEI

## Logs
* Client/Server Log: https://gist.githubusercontent.com/mythmon/a557a5ef8b51a7c8baf6e30a41d7687d/raw/ed4a10c4c4703fbd6ea9e994de513dc32825b6a1/gistfile1.txt
* Crash Log: N/A

## Client Information
* Modpack Version: 3.2.0-alpha.4
* Java Version: Version 8 update 261
* Launcher Used: MultiMC for the client
* Memory Allocated: 12GiB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.2.0-alpha.4
* Additional Content Installed: None

## Server Information
* Java Version: OpenJDK 8
* Operating System: Alpine Linux, Docker
* Hoster/Hosting Solution: Custom
* Sponge (Non-Vanilla Forge) Server: No?
* Forge Version: 14.23.5.2847

**Comment by sam-kirby** [comment]
The Forge build should be 2854. Please update and try again. If this continues to be an issue, please upload you crafttweaker log from the server - the file `crafttweaker.log` from the server's top directory.

**Comment by mythmon** [comment]
Forge build 2854 produces the same problem.

Here is the `crafttweaker.log`: https://gist.github.com/mythmon/b1d35514a2b3765aa9bf8c6df525177f

**Comment by sam-kirby** [comment]
The game is unable to resolve the items from Better Builders Wands. Is this mod missing from the server?

**Comment by mythmon** [comment]
The server did not have Better Builders Wands. tl;dr, That was enough to get me on the right track to fix this, and I think we can close this issue.

For some more detail, I'm trying to run this mod using Docker, and as I couldn't find any Dockerfiles that already had 3.2.0, I'm trying to make my own. I'm trying to process the released Sevtech zip file in the Dockerfile, and I'm using [ModPackDownloader](https://github.com/Nincraft/ModPackDownloader) to do that. Do you know of a better tool to download the mods in an automated way?

I see now in the logs of ModPackDownloader during my build process that it gives an error for Better Builder's Wands, and also for Inventory Tweaks. Looking more closely it is downloading those mods, but isn't able to find the downloaded JAR file. Those two mods are the only ones that have spaces in the JAR file name, but the file on disk has the space replaced with a plus sign, like it was URL encoded. The downloader gets confused by this. I've filed [an issue](https://github.com/Nincraft/ModPackDownloader/issues/102) with them about that.

I was able to put a work-around in place for my Dockerfile, and now the mods are being loading properly. The server seems to be working, and I can craft grass fiber mesh now.

I noticed that for previous releases, you've released a server zip file. I think that ultimately I'm trying to recreate that zip file. Would it be possible to release that for the alpha versions, or document how it is made? Or is this something that won't be coming until the full release?

**Comment by artdude543** [comment]
We'll have builds published to Curse once we hit the release stage. _(I'm the person who maintains the server-side of our modpacks)_

**Comment by xchoice** [comment]
If it helps, I'm using itzg/minecraft-server image for playing modpacks in docker (not this one in particular), maybe it'll save you some headaches on the setup.

**Comment by mythmon** [comment]
That looks really useful, @xchoice. I'm not going to mess with my set up right now, since it is working, but I'll keep that in mind in the future.

I think my problem is fixed here, and the mod downloader I was using has patched their issue too. I'm going to close this, since I don't think there is anything more for SevTech to do here.
