### ISSUE TITLE
Update ATLauncher version to 3.1.7

### ISSUE THREAD

**Issue by rrama** [DarkPacks/SevTech-Ages#4352]
## Context

Currently the ATLauncher version of the pack is 3.1.5, but I can see the release version on [CurseForge](https://www.curseforge.com/minecraft/modpacks/sevtech-ages) is 3.1.7. I spoke with a moderator of the ATLauncher Discord and they informed me I need to ask you to update it.
A link to the pack on the ATLauncher website can be found here: https://atlauncher.com/pack/sevtechages

FYI, the reason I am requesting this update is that I don't want to update to a version where Corail Tombstone has been replaced with Tombstone: Revived, which I assume will delete all the graves, when Corail Tombstone was added back in 3.1.6.

Thanks in advance!

## Config/Script Details (if desired)

N/A.

**Comment by nickavem** [comment]
Bump This! The twitch launcher doesn't work on Linux, and I know the AT launcher can improve performance for a lot of people regardless of OS.

**Comment by sam-kirby** [comment]
MultiMC is available for Linux and pulls from Curseforge.

The launcher used does not affect the performance of the game assuming you use the same arguments - you can close the launcher once the game is running to free up whatever resources it is using.

I doubt darkosto will upload 3.1.7 to ATLauncher at this point. Hopefully he will upload 3.2.0 when it leaves beta.

**Comment by rrama** [comment]
The versions have now been uploaded, including the beta versions, thanks whoever did it!
