### ISSUE TITLE
i cant find this modpack on twitch

### ISSUE THREAD

**Issue by Noahfrechette** [DarkPacks/SevTech-Ages#4368]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by blockgoblin31** [comment]
The modpack isn't on twitch yet. you need to download it from curse forge and import it into a profile.

**Comment by Noahfrechette** [comment]
i know i found the download button right after is said it on curse forge
