### ISSUE TITLE
your shit is broke fix it assholes!     cant make leather because it wont craft salted leather with the required items

### ISSUE THREAD

**Issue by shaddowfaux** [DarkPacks/SevTech-Ages#4387]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sam-kirby** [comment]
Thank you for your report @shaddowfaux - I was unable to reproduce the issue.

It's possible a modification you've made to the pack has caused this, or an error occurred during the installation. I suggest reinstalling a clean pack and retesting.

Should you continue experiencing an issue, please submit a new report with the requested information. It is not realistic to investigate issues missing these crucial facts.
