### ISSUE TITLE
totemic wont star

### ISSUE THREAD

**Issue by sagewakenight** [DarkPacks/SevTech-Ages#4391]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sagewakenight** [comment]
do it right and bar doesnt appear

**Comment by sam-kirby** [comment]
Are you near a totem base when trying to select the ritual? You need one.

**Comment by sagewakenight** [comment]
two of them and sorry to waste your time it started working after i sent the report

**Comment by sam-kirby** [comment]
If you can work out how to reproduce this predictably, let us know and we'll look into it. We've never seen a problem starting a ritual, though, so can't investigate based on this alone.
