### ISSUE TITLE
SevTech Ages of the Sky not downloadable?

### ISSUE THREAD

**Issue by XiNaru** [DarkPacks/SevTech-Ages#4392]
## Bug Description

Well I try to download it but nothing works. I went to curseforge and said Twitch should open, but it doesn't download anything in the launcher.

And unfortunately I can't find the modpack directly in Twitch.

### Did this behavior use to work in the previous version?

Irrelevant

## Steps to Reproduce (for bugs)

1. Try to Download the Modpack via Twitch.
2.
3.

## Logs

* Client/Server Log:
* Crash Log: No Logs for That

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sam-kirby** [comment]
Please see pinned issue #4245
