### ISSUE TITLE
Server launches, but stops on load, and doesen't crash just freezes

### ISSUE THREAD

**Issue by kispipin03** [DarkPacks/SevTech-Ages#4402]
## Bug Description
When I open the "ServerStart.bat" the server freezes at this: "[13:24:25] [BetterFps Update Checker/WARN] [BetterFps]: Could not check for updates: Server returned HTTP response code: 403 for URL: http://widget.mcf.li/mc-mods/minecraft/229876-betterfps.json" line of code (which I don't think is the problem). I'm thankful for every answers :)!

### Did this behavior use to work in the previous version?
I haven't played any previous versions so no

## Steps to Reproduce (for bugs)
1. I downloaded the server files + unzipped
2. I installed server forge, which is located in the folder
3. I changed my properties which I use
4. I open "ServerStart.bat" file then the problem occurs

## Logs
There is no log because it didn't crash
* Client/Server Log: -
* Crash Log: -

## Client Information
* Modpack Version: 3.1.7
* Java Version: 1.8.0_271
* Launcher Used: TLauncher
* Memory Allocated: Min: 1024MB, Max: 4096MB 
* Server/LAN/Single Player: Server w/ Hamachi
* Optifine Installed: -
* Shaders Enabled: -

## World Information
* Modpack Version world created in: 3.1.7
* Additional Content Installed: none

## Server Information
* Java Version: 1.8.0_271
* Operating System: Windows 10
* Hoster/Hosting Solution: Dedicated I guess
* Sponge (Non-Vanilla Forge) Server: -

**Comment by kispipin03** [comment]
Also I waited for more then a hour and it just stuck there.

**Comment by sam-kirby** [comment]
Please post a log as directed in the template.

**Comment by sam-kirby** [comment]
You can find the latest log in the logs directory, named latest.log

It does not matter that the server did not crash; there should still be a log.

**Comment by kispipin03** [comment]
I figured it out. It had to leave the server-ip empty.
