### ISSUE TITLE
Auto Jump

### ISSUE THREAD

**Issue by JumperXxXCables** [DarkPacks/SevTech-Ages#4404]
## Bug Description

Auto Jump is off in the option but it is still on 

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:3.2.1
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:no
* Shaders Enabled:no

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by JumperXxXCables** [comment]
sorry the mod version is 3.1.7 I was looking at something else

**Comment by YouLostTheGame** [comment]
That's literally part of the modpack. You need to craft an item in Age 1 to remove that if you wish.

**Comment by Machine-Maker** [comment]
Also, its technically **NOT** auto-jump. its more like auto-step since you don't overshoot the height of the thing you are trying to go up. In that sense its __**way**__ better than the default auto-jump.
