### ISSUE TITLE
Naseau at stage 3 permanant and regressed progress.

### ISSUE THREAD

**Issue by BreazyLantern** [DarkPacks/SevTech-Ages#4414]
## Bug Description

A bug appeared where when I got back in to sevtech I became permanantly naseaued and lost the knowledge of a lot of my items. I still had the progress in my achievements but it seems that I somehow "forgot" everything i've done and regressed back into age 1, still have all my stuff and such but cant use any of it.

### Did this behavior use to work in the previous version?

no

## Steps to Reproduce (for bugs)

1.get to stage 3 work up alot of things in astral sorcery and blood magic.
2.make a infinite lp source for the blood alter that is run in the background but it was turned off.
3.figure out some things like how to power it with the immersive tech sampler.
4. these were all the most recent things I did. I did not see any way these affected the stage progression nor how anything could give permanant naseau upon loading the game.

## Logs

* Client/Server Log:
* Crash Log:
-did not see it crash at any point but still have this report, this might not be related to the bug.
[crash-2020-11-24_03.30.15-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/5598645/crash-2020-11-24_03.30.15-client.txt)

## Client Information
* Modpack Version:3.2.0
* Java Version:most recent
* Launcher Used:curseforge launcher
* Memory Allocated:11008m
* Server/LAN/Single Player: single
* Optifine Installed:no
* Shaders Enabled:no

## World Information
* Modpack Version world created in:default
* Additional Content Installed:vinillafix

**Comment by sam-kirby** [comment]
Naseau is likely from Blood Magic - if you have rituals trying to drain LP and no source of LP then you will get naseua.

Lost ages is lkely the result of corruption, and happens fairly frequently when the game does not shutdown correctly (crash, end process through task manager, etc.). To fix this, you can either restore your playerdata from a backup, or use commands to unlock the stages you have lost.

Use `/gamestage add @p <stage_name>` to put yourself back in the correct stage.

You need to add the following stages: `zero`, `one`, `two`, `three`, `three_mob` and optionally `baykok` if you defeated the boss and `mapping` if you unlocked journeymap.

You need to run the command once per stage, e.g. `/gamestage add @p zero` then `/gamestage add @p one` etc.
