### ISSUE TITLE
Since new minecraft launcher update today I can no longer play sevtech ages of the sky. It just crashes and says Exit Code 0

### ISSUE THREAD

**Issue by Mondays3** [DarkPacks/SevTech-Ages#4422]
## Bug Description

 When Launching the game from the launcher with a fresh install, sevtech ages of the sky will crash with exit code 0. This is after todays minecraft launcher update.

### Did this behavior use to work in the previous version?

 I last played SevTech yesterday for streaming and nothing has gone wrong on it since I started playing 2 months ago

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/WtAQfSbH

## Client Information
* Modpack Version: Have only been playong Alpha 2 but have tried the beta1 version as well
* Java Version:
* Launcher Used: Curseforge
* Memory Allocated: 10GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: I have been using OptiFine_1.12.2_HD_U_F5 but have tried with fresh install
* Shaders Enabled: none

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sam-kirby** [comment]
The Curseforge launcher appears to have corrupted the vanilla Minecraft installation.

From your log: `your vanilla jar may be corrupt`.

If you delete the directory "E:\Twitch Minecrat\Install" then relaunch the pack from Curseforge, this will hopefully fix itself - though Curseforge may have installed Minecraft at another location. Please check your Curseforge settings to see where it is installing Minecraft.

**Comment by Mondays3** [comment]
I tried that and the problem was solved. However I tried opening other mod packs on earlier and later versions of minecraft and those packs worked. I had a problem purely on 1.12.2. When I reinstated my world of 2 months everything was still there and now I have also upgraded to beta 1 version!

**Comment by sam-kirby** [comment]
That makes sense as there are different vanilla installations for each version; it's likely only the 1.12.2 version was corrupted.
