### ISSUE TITLE
Server disconnects players and spams error message

### ISSUE THREAD

**Issue by Dan2724** [DarkPacks/SevTech-Ages#4426]
## Bug Description

I have recently started a server to play this modpack for myself and two friends. When we first began to play, this issue only occurred once every few hours. We are right about to reach the second age, but this issue has picked up in occurrence to the point we can only be on the server for 10-20 seconds before we lose connection. The error message is always the same, and the server must be restarted before it can be used again. the error only happens when someone (anyone) is on the server. The error does not seem to be related to a specific block or action, just happens randomly.

### Did this behavior use to work in the previous version?

I have only ran this server on the current version of the modpack, 3.1.7

## Steps to Reproduce (for bugs)

1. Start the server
2. Play for a while
3. Lose connection

## Logs

* Client/Server Log: [latest.log](https://github.com/DarkPacks/SevTech-Ages/files/5647426/latest.log)

* Crash Log:

## Client Information
* Modpack Version: 3.1.7
* Java Version: 1.8.0_241
* Launcher Used: Curseforge
* Memory Allocated: 6 Gb
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.1.7
* Additional Content Installed: None

## Server Information
* Java Version: 1.8.0_261
* Operating System: Windows 10 Home 64 Bit Version 1909
* Hoster/Hosting Solution: Personally ran server
* Sponge (Non-Vanilla Forge) Server: No

**Comment by sam-kirby** [comment]
This is a network issue and does not seem related to this modpack. Something is blocking all the server's outbound packets. This could be security software, any software you use to restrict uploads, or even something at the ISP level.

**Comment by Dan2724** [comment]
Alright seems as if my network adapter is having some issues and may need to be replaced. Thank you for your help sam.
