### ISSUE TITLE
Motion Sickness

### ISSUE THREAD

**Issue by zekenaulty** [DarkPacks/SevTech-Ages#4436]
AutoStep causes it, you locked it on, thanks. This is a common thing. Please go directly to hell, and unlock that.
 It is a dick move, there is no logical progression in being able to choose how I walk.

**Comment by sam-kirby** [comment]
Auto jump, the vanilla Minecraft "feature" toggled in controls, is locked *off*. This has clearly confused you.

Auto step is provided by a mod, and you are able to configure it as you please.

I would have happily given you detailed directions, but I'm too busy ~enjoying my Sunday evening~ burning in the fires of hell.

Hope you continue to enjoy the free mod pack that I have put days of work in to.
