### ISSUE TITLE
can not start server for sevtech ages of the sky

### ISSUE THREAD

**Issue by falizure** [DarkPacks/SevTech-Ages#4440]
while trying to launch a server running the server files for version 3.2.1 however im getting a error and this crash log which is something to do with the topography mod, this is preventing me from generating the world as a skyblock and defeating the whole point.
[crash-2020-12-19_17.48.41-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/5720015/crash-2020-12-19_17.48.41-server.txt)

**Comment by falizure** [comment]
## Bug Description
while trying to launch a server running the server files for version 3.2.1 of sevtech ages of the sky im getting a error and this crash log which is something to do with the topography mod, this is preventing me from generating the world as a skyblock and defeating the whole point.


### Did this behavior use to work in the previous version?
N/a

## Steps to Reproduce (for bugs)
install server files and try to launch the server


## Logs
https://github.com/DarkPacks/SevTech-Ages/files/5720015/crash-2020-12-19_17.48.41-server.txt


## Client Information
* Modpack Version: 3.2.1
* Java Version: 8
* Launcher Used: overwolf
* Memory Allocated:3 gb on the server
* Server/LAN/Single Player:server
* Optifine Installed:no
* Shaders Enabled:no


## World Information
* Modpack Version world created in:3.2.1
* Additional Content Installed:none

**Comment by sam-kirby** [comment]
Have you changed server.properties at all? The generator-settings are invalid, which is causing this crash.

**Comment by sam-kirby** [comment]
Please upload your server.properties file.

**Comment by falizure** [comment]
yes, several times but only in a attempt to actually make it work, first the generation type was blank, then i tried generator-settings={"Topography-Preset"\:"Sky Block"} as someone suggested, still no luck, and last i tried just doing topography, and none of those work, this is it how its currently set (sorry it wont accept the default format for uploading)

#Minecraft server properties
#Sat Dec 19 22:56:07 GMT 2020
spawn-protection=0
max-tick-time=-1
query.port=25656
generator-settings=topography
force-gamemode=false
allow-nether=true
gamemode=0
dc_preset=notSet
enable-query=true
player-idle-timeout=0
difficulty=1
spawn-monsters=true
op-permission-level=4
pvp=true
snooper-enabled=false
level-type=
hardcore=false
enable-command-block=false
max-players=30
network-compression-threshold=256
resource-pack-sha1=
max-world-size=29999984
server-port=25656
server-ip=sm72.serverminer.com
spawn-npcs=true
allow-flight=true
level-name=world
view-distance=10
resource-pack=
spawn-animals=true
white-list=false
generate-structures=true
max-build-height=256
online-mode=true
level-seed=
use-native-transport=true
prevent-proxy-connections=false
motd=A Minecraft Server
enable-rcon=false

**Comment by falizure** [comment]
frankly none of it should matter cause topography should be handling the generation but that seams to be whats causing the error

**Comment by sam-kirby** [comment]
Topography needs to know what preset to use; the generator settings must be valid json.

What you had originally should work, do you get a different crash report if you set it to `generator-settings={"Topography-Preset":"Sky Block"}`?

**Comment by falizure** [comment]
yes 
[crash-2020-12-20_10.03.06-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/5720761/crash-2020-12-20_10.03.06-server.txt)

**Comment by falizure** [comment]
no matter what i chance the world gen type to it always generates the same error

**Comment by sam-kirby** [comment]
Can you please upload your log? `logs/latest.log`

**Comment by falizure** [comment]
[latest.log](https://github.com/DarkPacks/SevTech-Ages/files/5720775/latest.log)

**Comment by sam-kirby** [comment]
```
{&#34;Topography-Preset&#34;:&#34;Sky Block&#34;}
```

Your generator-settings line has the `"` characters replaced with their HTML character code `&#34;`.

How are you editing this file?

**Comment by falizure** [comment]
ive tried 2 methods, ive tried using filezilla and editing the properties file with a text editor, and i have also tried editing it with the interface the server rental service provides, which has among other things the line for terrain generation and a blank box for entering it, it seams no matter what i do the moment i start the server it converts the characters to the 34, i didnt know if that was a intentional function but i did find it odd.

**Comment by sam-kirby** [comment]
This sounds like an issue on your host's end, where they convert characters that might have meaning in HTML to prevent attacks such as XSS. They should only be doing this when displaying the file, and not storing the escaped version.

Nothing on our end would convert these characters.

If you haven't already, try uploading the file using FTP and start the server without looking at the server properties in the browser.

**Comment by falizure** [comment]
not quite sure what you mean by that

**Comment by sam-kirby** [comment]
Which part?

**Comment by falizure** [comment]
im assuming you mean access it with my filezilla program again and reapply and upload it but im not quite sure whta you mean by without looking at the properties

**Comment by sam-kirby** [comment]
Don't go to any page on your server host's site that shows the contents of, or allows you to edit, the server properties.

Have the page with the button that you click to start the server open, upload the corrected server.properties file using filezilla, click start without refreshing, or going anywhere else on the host's website.

**Comment by falizure** [comment]
couldnt remember if i tried that or not so i did it again and still get the same crash

**Comment by falizure** [comment]
i have noticed something, when i edit the server property and upload it on filezilla if i go look at the settings from the server control panel it just shows up as this {    that single character is all that shows up in the generation box if i upload it.

**Comment by sam-kirby** [comment]
Can you please send the log from your attempt using the upload from filezilla?

**Comment by falizure** [comment]
thats what ive been using but ill upload the latest anyway
[latest.log](https://github.com/DarkPacks/SevTech-Ages/files/5720817/latest.log)

**Comment by sam-kirby** [comment]
Yep, same problem. This is unfortunately not an issue we can address, you will need to contact your server host as they are changing your server.properties file, breaking it.

**Comment by falizure** [comment]
ty for looking at it for me
