### ISSUE TITLE
Show ages on scoreboard

### ISSUE THREAD

**Issue by Diversion98** [DarkPacks/SevTech-Ages#4454]
## Context
I want to show the gamestage progression on the scoreboard for every player.

Minecraft has a built in scoreboard and i want to utilize that to show the age the player is in.
I found an existing issue for this and its closed but I cant find to set it up.
https://github.com/DarkPacks/SevTech-Ages/issues/1052

## My environment
Modpack: Sevtech: Ages of the Sky
Version: 3.2.1-beta.1-skyblock

**Comment by sam-kirby** [comment]
Two commands should be all that are needed to set this up:

Create the objective, and enable tracking in the scoreboard.
```
/sevtweaks gamestage init
```

Set it to display in the sidebar.
```
/scoreboard objectives setdisplay sidebar ST_Stage
```

![image](https://user-images.githubusercontent.com/23245543/103171264-cc720d00-4842-11eb-9524-f9344762522b.png)
