### ISSUE TITLE
Wild dog pelt boots + water = Very high speed

### ISSUE THREAD

**Issue by NotWhalea** [DarkPacks/SevTech-Ages#4465]
## Bug Description

Being on the bottom of the lake in "Wild dog pelt boots"  and sprinting makes the character to cross the lake WAY too fast and fly away from the island after that for about 50 blocks even in the medium size pool (if there is no wall outside the pool)

### Did this behaviour used to work in the previous version?

I don't know

## Steps to Reproduce (for bugs)

1.Put on "Wild dog pelt boots"
2.Climb in the pool
3.Reach the bottom of it
4.Start sprinting

## Logs

* Client/Server Log:
* Crash Log:
None

## Client Information
* Modpack Version:
SevTech-Ages-of-the-Sky_3.2.1-beta.1
* Java Version:
"1.8.0_221"
* Launcher Used:
Curseforge (Overwolf)
* Memory Allocated:
8 gb
* Server/LAN/Single Player:
Singleplayer
* Optifine Installed:
No
* Shaders Enabled:
Basic shaders

## World Information
* Modpack Version world created in:
SevTech-Ages-of-the-Sky_3.2.1-beta.1
* Additional Content Installed:
None

**Comment by tosk3** [comment]
+ doing it on ice -> breaking lightspeed

**Comment by Darkosto** [comment]
Yes, this is intended behavior
