### ISSUE TITLE
When moving, the view starts to rorate.

### ISSUE THREAD

**Issue by hexoctal-sur** [DarkPacks/SevTech-Ages#4469]
## Bug Description

When I try to move, the entire view start to rotate and I cant see anything. All mobs in game including player start "twitching".
Sorry for the poor English and you may check the video here: [https://youtu.be/VidKGgeGlT0](https://youtu.be/VidKGgeGlT0)

### Did this behavior use to work in the previous version?

Yes, at least two versions ago.

## Steps to Reproduce (for bugs)

Just start the game and walk.

## Logs

* Client/Server Log: [https://paste.ubuntu.com/p/5S8cYD9y5n/](https://paste.ubuntu.com/p/5S8cYD9y5n/) 
 [https://paste.ubuntu.com/p/PH47Zc6J5Y/](https://paste.ubuntu.com/p/PH47Zc6J5Y/)
* I can only paste a small part of log because it has tons of error caused by jei (about 16000 lines)
* Crash Log: The game won't crash so don't have a crash log.

## Client Information
* Modpack Version: 3.17
* Java Version: jre1.8.0_251
* Launcher Used: HMCL-3.3.172
* Memory Allocated: 8192 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: Modpack version 3.17
* Additional Content Installed: No

**Comment by sam-kirby** [comment]
If you have changed the BetterFPS algorithm, change it back to Rivens Half. It it is already set to Rivens Half, set it to vanilla.

**Comment by hexoctal-sur** [comment]
> If you have changed the BetterFPS algorithm, change it back to Rivens Half. It it is already set to Rivens Half, set it to vanilla.

Thanks, the problem solved.
