### ISSUE TITLE
Wierd behaviour with inductive logistics filter and imm. engin. ingots and grits

### ISSUE THREAD

**Issue by LoganDungeon** [DarkPacks/SevTech-Ages#4473]
## Bug Description

I want to use Inductive Logistics pipes to send grits and ingots to the two inputs of an Arc Furnace. However the item filter of the logistic pipes thinks that aluminium and copper grits and ingots are all the same.
So inspite me having grits and ingots filtered on different pipes, they get send kinda randomly.
(I did not change any of the settings of the filters, like metadata etc.)

Here is the minial (not) working setup with normal chests, extraction pipes with filters and injection pipes:

![](https://i.imgur.com/zvwLlWm.png)

Left side grits:

![](https://i.imgur.com/3uxbTNp.png)

Right side ingots:

![](https://i.imgur.com/A2yMDMC.png)

However after putting all the items in the middle chest, every item ends up in the left chest (sometimes it's random):

![](https://i.imgur.com/jXW0LIs.png)

So as it seems, the logistics filter sees aluminium and copper ingots and grits as the "same" item. I don't know if this is at the fault of immersive engineering, inductive logistics or some other unrelated configuration.

### Did this behavior use to work in the previous version?

Don't know.

## Steps to Reproduce (for bugs)

In the description.

## Logs

* Client/Server Log:
* Crash Log:
Does not apply

## Client Information
* Modpack Version: Sevtech Ages 3.2.1 Beta
* Java Version: 1.8.0_251-b08
* Launcher Used: CurseForge
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: I think 3.1.7 (?) not sure on that, but shouldn't matter
* Additional Content Installed: None

**Comment by sam-kirby** [comment]
> (I did not change any of the settings of the filters, like metadata etc.)

These items *are* technically the same item: `<immersiveengineering:metal>`. They are identified only by different metadata. For example aluminium dust has meta 10, the ingot meta 1. Copper has meta 9 for its dust and 0 for its ingot.

Turn on filtering by metadata and this should work.

**Comment by LoganDungeon** [comment]
Thank you very much, this indeed fixes it. I learned something new today.
I always kinda thought that these kind of items only care about oredict and metadata is more for entchantments etc., but guess i was wrong :D
