### ISSUE TITLE
My craft progress isn't working

### ISSUE THREAD

**Issue by DemonGamerLG** [DarkPacks/SevTech-Ages#4484]
I was playing yesterday and i badly turn off the computer, and now i have all the progress, but no the items, like i was in the age 2 i was capable of craft iron, but now i can't even have the iron in my hand, pls someone help me

**Comment by sam-kirby** [comment]
You can restore your progress using commands (`/gamestage add zero`, etc).

However, cutting the power could have corrupted more than just this. It would be best if you restored a backup from before this happened.

Go to https://discord.gg/darkosto if you need help with either of these.
