### ISSUE TITLE
Server Freezes whenever someone logs on after getting age 5

### ISSUE THREAD

**Issue by Mc-man165** [DarkPacks/SevTech-Ages#4488]
## Bug Description

 While I was offline my friend progressed to age 5, went to the moon then came back and got off. The server was still running all night with no issues but whenever me or my friend(only 2 of us) logs on it freezes. Tried it without my other mods installed and still does the same.

### Did this behavior use to work in the previous version?

 I dont know we have been in version 3.2.1 for a while and only just got to age 5

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:https://gist.github.com/Mc-man165/d6366fdb92d89f59ba0c47c9bd57f051.js
* Crash Log:https://gist.github.com/Mc-man165/5aa7202067174282174287913a23990e.js

## Client Information
* Modpack Version: 3.2.1
* Java Version:10.0.2.0(64bit)
* Launcher Used:Curse Forge
* Memory Allocated:9GiB
* Server/LAN/Single Player: Server
* Optifine Installed:no
* Shaders Enabled:None

## World Information
* Modpack Version world created in: 3.1.7 (i think)
* Additional Content Installed: FTBUtilities-5.4.1.130 & FTBLib-5.4.7.2

## Server Information
* Java Version:1.8.0_261
* Operating System:Windows
* Hoster/Hosting Solution:Hosting on my PC and using Hamachi to connect
* Sponge (Non-Vanilla Forge) Server:N/A

**Comment by Mc-man165** [comment]
So i managed to fix the problem by rolling back my world to before we hit age 5. I'm still interested in what caused the issue but ill close it now.

**Comment by sam-kirby** [comment]
Issue looks to be caused by an excessive number of item entities in the world; the server is spending so long calculating collisions between items that it crashes.

**Comment by Mc-man165** [comment]
> Issue looks to be caused by an excessive number of item entities in the world; the server is spending so long calculating collisions between items that it crashes.

Oh okay thanks I think I know what to was void upgrade on the drawer should fix that
