### ISSUE TITLE
Eagle Dance does not spawn Eagles upon completion (3.2.1)

### ISSUE THREAD

**Issue by TSoHardKnocks** [DarkPacks/SevTech-Ages#4508]
## Bug Description

The totemic Eagle Dance does not summon eagles. I have completed the dance 6 times with nothing spawning.

### Did this behavior use to work in the previous version?

N/A

## Steps to Reproduce (for bugs)

1.Set up totemic instruments and totem.
2.Perform the Eagle Dance(Ceremony) before the green bar fills.
3.No bird will spawn after completing it(for me).

## Logs

* Client/Server Log:N/A
* Crash Log:N/A

## Client Information
* Modpack Version:3.2.1
* Java Version:1.12.2
* Launcher Used:CurseForge > Minecraft Launcher
* Memory Allocated: 9G
* Server/LAN/Single Player:Singleplayer
* Optifine Installed:No
* Shaders Enabled:No

## World Information
* Modpack Version world created in:3.2.1
* Additional Content Installed:None

**Comment by sam-kirby** [comment]
The eagle dance transforms parrots into eagles.
