### ISSUE TITLE
i keep dropping my logs (help)

### ISSUE THREAD

**Issue by CobySwitch** [DarkPacks/SevTech-Ages#4511]
## Bug Description

i cant hover over any logs or plants

### Did this behavior use to work in the previous version?

im new so i dont know

## Steps to Reproduce (for bugs)

1. launch game
2. then i cant hover over any of the logs
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 3.1.7
* Java Version: newest
* Launcher Used: curseforge
* Memory Allocated:what
* Server/LAN/Single Player:single player
* Optifine Installed: no
* Shaders Enabled:no

## World Information
* Modpack Version world created in: 1.12.2
* Additional Content Installed:nothin

**Comment by CobySwitch** [comment]
also i cant open the map

**Comment by sam-kirby** [comment]
Please ask  gameplay questions on the gameplay channels on Discord. https://discord.gg/darkosto

This is not a bug.
