### ISSUE TITLE
Singleplayer World Gone

### ISSUE THREAD

**Issue by TheMiningGinger** [DarkPacks/SevTech-Ages#4514]
## Bug Description
     I was in my singleplayer world last night exploring a bunch in a mountainous area and it was starting to get laggy (This is in age 1). Lag isn't my concern though. Anyway, I was autopiloting and fell off a cliff after a lag spike and died. I went back to get my stuff and like 20 seconds after getting it, a lag spike crashed my game. The lag hasn't crashed my game ever before and hasn't even been that bad before that area. I came back to it today and my singleplayer file isn't in my singleplayer tab. I checked the "saves" file in the folder and it exists, but only in the folder, not the game. Oh, another thing to note is that my Curseforge had to relaunch before this I reloaded it today. It also removed my previous command reccomended by Darkosto in the Curseforge launcher to optimize gameplay and garbage collection after the crash. I don't know if that's important, but there that is.

Thanks for your time.

## Steps to Reproduce (for bugs)

1. Go near mountainous biome in Age 1 after exploring 1000s of blocks (most likely snowy darkstone?).
2. Experience heightened lag and crash.
3. Go to Singleplayer tab in game and see that the world isn't there.

## Logs
As far as I can see, no logs :(

## Client Information
* Modpack Version:1.12.2
* Java Version:Version 8/Update 261
* Launcher Used:Curseforge
* Memory Allocated:8GB
* Server/LAN/Single Player:Singleplayer
* Optifine Installed:No
* Shaders Enabled:No

## World Information
* Modpack Version world created in:1.12.2
* Additional Content Installed:No

**Comment by TheMiningGinger** [comment]
It has been 19 days since the opening of this issue, just wondering if it auto-closed or if there's no responses :p

**Comment by sam-kirby** [comment]
Restore your world from a backup. If you need help with this, please use the Discord. https://discord.gg/darkosto

Without logs or a reliable method to reproduce the crash, there is nothing we can do to fix the cause of the problem.

Crashes, force quitting and power loss always carry a risk of fatal world corruption, which is why we include an automatic backup mod.

**Comment by matimo21** [comment]
had the same problem in age 2 during exploration of betweenlands. world started lagging more then usual, screen froze and whole pc crashed. logged back in, and i suspect an advancement file corruption. all items appear as unfamiliar in my inventory. 10seconds after log in pc crashed and i cant find my world anymore. i tried to restore the backup but the world still wont appear in game
