### ISSUE TITLE
Please help the wood stump thing when i hit it with the rock used for it it did not work pls fix

### ISSUE THREAD

**Issue by aidenwalden12** [DarkPacks/SevTech-Ages#4515]
## Bug Description

 When i tried crafting with the wood stump it would not work yesterday it was working pls help

### Did this behavior use to work in the previous version?

i was using 1.16.5

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sam-kirby** [comment]
Make sure you have it the right way round. The bottom of the crafting grid is the side facing towards you when you place it down. The shelf on the bottom can help you orientate yourself.
