### ISSUE TITLE
leads not working right?

### ISSUE THREAD

**Issue by Vashta** [DarkPacks/SevTech-Ages#4542]
## Context

not sure if this is a bug or just a setting youve chosen but the leads are just despawning after a time as ill come back to find the horse just standing there with no lead and they arent keeping the horses close to the horse power stations so they will walk away breaking it as well

**Comment by sam-kirby** [comment]
Make sure leads don't cross a chunk boundary. If they do then it is possible for the horse entity to load before the block it is tethered too, thus breaking the lead. This is a vanilla Minecraft bug that can't be fixed in this version of Minecraft.

**Comment by Vashta** [comment]
> 
> 
> Make sure leads don't cross a chunk boundary. If they do then it is possible for the horse entity to load before the block it is tethered too, thus breaking the lead. This is a vanilla Minecraft bug that can't be fixed in this version of Minecraft.

the problem there is that itss happening while im in my base though ill be doing stuff in my base island and then walk over to find the leads broken does that bug happen even if all the chunks are loaded?
