### ISSUE TITLE
OMGSERV delete a plugin

### ISSUE THREAD

**Issue by TheoJeanney** [DarkPacks/SevTech-Ages#4545]
## Bug Description

OMGserv deleted the plugin "oeintegration-2.3.4.jar" because these files are not allowed on OMGSERV.

After this remove, some craft are available (for example, sticks with woods at age 2).

## Steps to Reproduce (for bugs)

1. Creating the portal for BetweenLands
2. Get in the portal
3. Wait 5 minutes and the serveur should crash

## Logs

* Client/Server Log: https://pastebin.com/ngaCV4B0
* Crash Log:

## Client Information
* Modpack Version: 3.2.1
* Java Version:
* Launcher Used: CurseForge
* Memory Allocated: 6Go
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.2.1
* Additional Content Installed: Nothing

## Server Information
* Java Version: 1.12.2

**Comment by sam-kirby** [comment]
Okay, why is that mod banned on their platform? I took a look through the source and it's a very small mod that does exactly what it says it does.

**Comment by sam-kirby** [comment]
What do your steps to reproduce have to do with this issue? They sound completely unrelated.

**Comment by TheoJeanney** [comment]
Thanks for your fast answer.

I have no idea why they banned it. That's why I came in this forum to find this answer. I hoped you got an idea of what going on, and if some other people could have the same problem.

This is my first issue on github to be honnest, and I put what happened when the server crashed.  We tried to restart the server from zero and we went again in the dimension "Between Lands", and the same thing happend.

I played many modpacks using OMGSERV as host, and I never had a problem like this. 

Have a nice day,

Elunyo.

**Comment by AnthonyCouthures** [comment]
Hello,

My server is also hosted on OMGServ. I have the same issue as you for example : no sticks with woods at age 2 and some others blocks are not craftable. 

I assume it's not related to the BetweenLands because no one have never been in the BetweenLands on my server. This happened today but it's the first day in Age 2 and the bug was not here before at Age 1 so maybe it's a OMGServ recent action or related to the Age 2 in general. 

Have a nice day,

AC

**Comment by sam-kirby** [comment]
After checking on the OMGSERV support Discord, it seems that this mod was being deleted accidentally by them. If you reupload it now hopefully they won't delete it anymore. Contact their support team if this is not the case.

This isn't really an issue we can help with further; it's expected that if you remove random components of the pack the pack will break. There isn't much we can do about that.
