### ISSUE TITLE
Blood magic pedestal bugg

### ISSUE THREAD

**Issue by funkydealer42** [DarkPacks/SevTech-Ages#4551]
## Bug Description

 my friend and i are playing on a server with just us 2, we are starting blood magic now and just crafted the beneath portal, for my friend everything works fine but i can't place blockt mine blockt open chests or pick berries close to the pedestals

### Did this behavior use to work in the previous version?

 i don't know, first time playing this

## Steps to Reproduce (for bugs)
 

1. Craft beneath portal with 2
2. Join beneath world
3. can't mine next to pedestal

## Logs

* Client/Server Log: no log since nothing special happens
* Crash Log:

## Client Information
* Modpack Version: 3.2.1
* Java Version:1.12.2
* Launcher Used:curseforge
* Memory Allocated:10gb
* Server/LAN/Single Player: server
* Optifine Installed:no
* Shaders Enabled:no

## World Information
* Modpack Version world created in:3.2.1
* Additional Content Installed:no

## Server Information
* Java Version: 1.12.2
* Operating System: don't know
* Hoster/Hosting Solution: apexminecrafthosting.com
* Sponge (Non-Vanilla Forge) Server: don't know what this means

**Comment by sam-kirby** [comment]
This sounds like it might be related to spawn protection; is your friend an op and are you? Is your blood magic altar near to the world spawn (the place you spawn if you have no bed/the first time you join the world)?

**Comment by funkydealer42** [comment]
oooh yessss thanks for this i think this might be it, we changed spawnpoint right before the pedestal stuff, because of that my friend is op because we wanted no cheats. im going to try this out and let you know if thats the problem. it was so weird cuz items dissapeared aswell

**Comment by sam-kirby** [comment]
Okay. You have a few options for dealing with it then;

1. While the server is offline, set `spawn-protection=0` in server.properties. This disables spawn protection and is probably the best option as you don't really need it
2. Make both of you ops so you both bypass the protection
3. Move the spawn to somewhere it won't interfere

**Comment by sam-kirby** [comment]
Closing as no further information given.
