### ISSUE TITLE
Starlight Crafting Altar cannot used

### ISSUE THREAD

**Issue by Milkyway2133** [DarkPacks/SevTech-Ages#4552]
## Bug Description
 So , i want to make portal to the twilight forest , it need Starlight Crafting Altar , But after i open the altar (the building already correct) it say something wrong , i watch on youtube it say make it high , i already try it high but it still not work

### Did this behavior use to work in the previous version?

 No 

## Steps to Reproduce (for bugs)

1.https://www.youtube.com/watch?v=vyypM8EJtzE&t=789s
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 3.1.7
* Java Version:1.12.2
* Launcher Used: Official Minecraft Launcher
* Memory Allocated: 6144 Mb
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes 
* Shaders Enabled: No 

## World Information
* Modpack Version world created in: 3.1.7
* Additional Content Installed: No
![2021-05-06_02 33 46](https://user-images.githubusercontent.com/83726390/117193371-55aed700-ae15-11eb-94bf-55b1f55ae1b9.png)
-->

**Comment by sam-kirby** [comment]
Red indicates the structure is incorrect. Make sure you are using marble from the Astral Sorcery mod. I can't really see anything from your screenshot.

**Comment by Milkyway2133** [comment]
> Red indicates the structure is incorrect. Make sure you are using marble from the Astral Sorcery mod. I can't really see anything from your screenshot.

oh yeah , omg my bad , the brick marble is wrong , its from the chisel mod , thank u bro
