### ISSUE TITLE
Server doesnt start

### ISSUE THREAD

**Issue by Albindigge** [DarkPacks/SevTech-Ages#4557]
## Bug Description

 I click the ServerStart.bat but then this shows up: Error: missing server' JVM at C:\Program Files(x86)\Java\jre1.8.0_291\bin\server\jvm.dll'. Please install or use the JRE or JDK that contains these missing components.

### Did this behavior use to work in the previous version?

Yes, this was also the case in other versions

## Steps to Reproduce (for bugs)

1. Click install.bat
2. Click serverstart.bat
3.

## Logs

* Client/Server Log:There is no logs
* Crash Log: No logs

## Client Information
* Modpack Version: 3.2.1
* Java Version: Dont know
* Launcher Used: Dont know
* Memory Allocated: Dont know
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: DOnt know
* Additional Content Installed: No

## Server Information
* Java Version: Dont know 
* Operating System: Dont know
* Hoster/Hosting Solution: Dont know
* Sponge (Non-Vanilla Forge) Server: Dont know

**Comment by sam-kirby** [comment]
Oracle no longer include the server component of the JRE in the standard Windows download. You can either install a JRE that includes the server component, or remove the flag that asks for it in the server start script.

For help with either of these, please use the support Discord server - https://discord.gg/darkosto
