### ISSUE TITLE
Astral sorcery attunement on player not working

### ISSUE THREAD

**Issue by xdken** [DarkPacks/SevTech-Ages#4561]
So I got the constellation set up in the attunement altar, the constellation is recognized and the alter raised.
But it didn't do attunement on me, though it's fine on the crystal
![2021-05-16_14 51 00](https://user-images.githubusercontent.com/62326910/118388324-4c640c80-b656-11eb-9d60-1831fef71c10.png)
![2021-05-16_14 51 05](https://user-images.githubusercontent.com/62326910/118388325-4e2dd000-b656-11eb-84cd-81d8dd932ba9.png)
![2021-05-16_14 51 09](https://user-images.githubusercontent.com/62326910/118388329-4ec66680-b656-11eb-81ba-69c09ff7e78a.png)

as you see I got armara set up

**Comment by sam-kirby** [comment]
You appear to already be attuned to another constellation. You can only be attuned to one at a time, but you can reset it using an item. I forget what it is, you can try asking on Discord - https://discord.gg/darkosto
