### ISSUE TITLE
INSANE COBBLE DUPE GLITCH

### ISSUE THREAD

**Issue by matro8** [DarkPacks/SevTech-Ages#4567]
## Steps to Reproduce (for bugs)

1.place a 3*3 cobble pattern
2.take a autosmelt and fortune 3 hammer
3.break the cobblestone with the hammer
4.u get triple stone

## Logs

* Client/Server Log:<!-- ✍️dont have access to>
* Crash Log:<!-- ✍️no crash>

## Client Information
* Modpack Version:<!-- ✍️3.2.1>
* Java Version:<!-- ✍️64>
* Launcher Used:<!-- ✍️curse forge>
* Memory Allocated:<!-- ✍️10624MB>
* Server/LAN/Single Player:<!-- ✍️server>
* Optifine Installed:<!-- ✍️false>
* Shaders Enabled:<!-- ✍️false>

## World Information
* Modpack Version world created in:<!-- ✍️1.12.2>
* Additional Content Installed:<!-- ✍️no>

**Comment by sam-kirby** [comment]
This doesn't seem particularly insane, but okay.

Tinkers Construct on 1.12 is now unmaintained so this is unlikely to ever be fixed.

**Comment by matro8** [comment]
k

**Comment by matro8** [comment]
should i close it ?

**Comment by matro8** [comment]
PS: i got 20 stone by 9 cobble
