### ISSUE TITLE
Request to add ender io to sevtech.

### ISSUE THREAD

**Issue by AGamer20** [DarkPacks/SevTech-Ages#4569]
## Context

 I would like to recommend Ender io.
Because it's machines are very useful, it's cables and pipes are compact and easy to manage, and using flux plugs and flux points to create an energy network to easily provide power to locations without having to place cables that go for long distances.

## Mod Details
* Name: Ender io
* CurseForge Link: https://www.curseforge.com/minecraft/mc-mods/ender-io

**Comment by sam-kirby** [comment]
This has been covered before; ender io will not be added to SevTech.
