### ISSUE TITLE
Unable to craft Mk2 wooden hopper - manually installed via curseforge server zip

### ISSUE THREAD

**Issue by markygnlg** [DarkPacks/SevTech-Ages#4572]
## Bug Description

In a single player game I am trying to craft a wooden hopper mk2 but it does not work. Everything else works fine but I've been stuck for over an hour & I keep re-trying whenever I get another achievement as I thought it may be locked to stop me building a fishing net (can't build the WaterStrainer base without the mk2 hopper).

### Did this behavior use to work in the previous version?

This is the first time playing this modpack.

## Steps to Reproduce (for bugs)

1. Download the server zip from https://www.curseforge.com/minecraft/modpacks/sevtech-ages/files/3125814
2. unzip & run install.bat
3. start the game
4.  I downloaded the smaller file but did not use it (from https://www.curseforge.com/minecraft/modpacks/sevtech-ages/files/3123514).

## Logs

* Client/Server Log: pastebin does not allow over 512 bytes , my latest.log is 2.5mb & debug.log is over 33mb
* Crash Log: does not crash

## Client Information
* Modpack Version: SevTech-Ages_Server_3.1.7
* Java Version: v8 update 291
* Launcher Used: none
* Memory Allocated: 10GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: OptiFine_1.12.2_HD_U_G5
* Shaders Enabled: none

## World Information
* Modpack Version world created in: 1.12.2
* Additional Content Installed:
* creeperconfetti-1.4.2.jar (mods)
* creeperheal-1.12-1.3.1.jar (mods)
* PureBDcraft  64x MC112.zip (resourcepacks)
* SphaxSevtech64x-v4.zip (resourcepacks)

![Sevtech 2of2](https://user-images.githubusercontent.com/62978705/120894690-f254d680-c658-11eb-8c28-74af4503ee07.png)
![Sevtech 1of2](https://user-images.githubusercontent.com/62978705/120894697-fc76d500-c658-11eb-8a4f-1f589d9a5a9a.png)

**Comment by sam-kirby** [comment]
Can you please upload your crafttweaker log to https://gist.github.com and link to it here?

**Comment by markygnlg** [comment]
Done.

(This file has been truncated...):
https://gist.github.com/markygnlg/c9ba0b9f636c7202b18536c84f34bde9

(... but you can view the full file):
https://gist.githubusercontent.com/markygnlg/c9ba0b9f636c7202b1853

It might help to mention that in the screenshot I have the Work Stump (basic) on the left & the Work Stump Mk2 on the right.


I'll also add that to install this mod I:

1. deleted all files & folders under ./minecraft
2. downloaded 1.12.2 using the default/vanilla mc launcher
3. unzipped the SevTech-Ages_Server_3.1.7.zip file
4. ran install.bat (I didn't run setup.bat when saw that it's 'called' from the install.bat)
5. when it failed to load I installed the forge client side version (I knew Sevtech Ages includes forge but I didn't realise it was the server version only)
6. ran the game & all was good except for the Wooden Hopper Mk2


I was planning to use either ATLauncher or MultiMC but I'm paranoid about 3rd party programs collecting my login info - which is why I tried a manual install first.

Thanks for help & for your very quick reply too.

**Comment by markygnlg** [comment]
SO Sorry!!

The PureBDcraft 64x MC112.zip resourcepack has a very white background in the crafting table so I could not see the cobweb required in the top centre position.

Thanks for your time!

**EDIT**: 
![mod thing](https://user-images.githubusercontent.com/62978705/120913024-2a98fb00-c6d3-11eb-97eb-1a4487810857.png)
