### ISSUE TITLE
Bloodmagic altar can't transfer more then 1k lp per operation

### ISSUE THREAD

**Issue by Flamebom** [DarkPacks/SevTech-Ages#4573]
## Bug Description
I have a blood altar with 37+ displacement runes. In theory it should be able to to transfer 17k lp per operation. However, in practice its only able to do 1k lp per operation max.

### Did this behavior use to work in the previous version?
Don't know

## Steps to Reproduce (for bugs)
Make a tier 4 blood altar.
Use only displacement runes.
Use any liquid transfer method to transfer lp out of the altar. 

## Logs
No applicable logs

## Client Information
* Modpack Version:3.2.0
* Java Version:1.8.0_222
* Launcher Used:Multi Mc, and twitch before it was removed
* Memory Allocated:5900MB
* Server/LAN/Single Player:Single Player
* Optifine Installed:No
* Shaders Enabled:No

## World Information
* Modpack Version world created in:3.0.4
* Additional Content Installed:No

**Comment by sam-kirby** [comment]
If memory serves correctly, you also need to increase the size of the blood altars internal tank using Capacity Runes or something like that.

Does adding these runes increase the rate you are able to transfer?

**Comment by sam-kirby** [comment]
From the FTB wiki page:

> Be aware: Without Rune of Augmented Capacity or Rune of Superior Capacity and without Rune of Acceleration the transfer rate is limited to max. 1000 LP/s(max multiplicative can be reach with 22 runes). 

https://ftbwiki.org/Rune_of_Dislocation

This seems to be functioning as intended?
