### ISSUE TITLE
All Advancements Showing

### ISSUE THREAD

**Issue by Zack095** [DarkPacks/SevTech-Ages#4574]
Hi there,

I'm enjoying the pack but it'd be much more satisfying if the later advancements didn't show until they were the next thing to be unlocked. Could you get it so that only the next thing is showing in the advancements and the rest is all hidden?

![image](https://user-images.githubusercontent.com/68552871/120938678-f3930b80-c70b-11eb-801d-5f168cff85cb.png)

For example in this image, the primal chest and wooden hopper mark 1 would show because they're the next advancement, but any after that would be hidden?

Thanks!

**Comment by sam-kirby** [comment]
We previously hid advancements as you describe (only available advancements visible), but players complained that left them unable to plan for the age - either in terms of buildings or not realising they'd need something they found while exploring.

We chose to change to the current system, whereby you can see all locked advancements in your current age only. There are many more advancements that you cannot yet see.
