### ISSUE TITLE
Chrash on launch

### ISSUE THREAD

**Issue by kostasn15** [DarkPacks/SevTech-Ages#4578]
## Bug Description
 📝 A clear and concise description of the problem... 
 Crashes on launch

### Did this behavior use to work in the previous version?
📝 Yes, the previous version in which this bug was not present was: 
 don't know first time playing it

## Steps to Reproduce (for bugs)
📝 A youtube video or a set of steps to reproduce... -->
1.
2.
3.

## Logs
 📝
Twitch logs can be found in the installation directory for the Twitch App.  Or click the ... button on SevTech and hit "Open Folder"
ATLauncher logs can be found in the installation directory. Or you can "Open Folder" from the launcher to view the instance.
Then upload the latest/crash logs to PasteBin or Gist. DON'T Upload them to GitHub 
* Client/Server Log:m https://pastebin.com/TuPYMetA
Pastebin 
* Crash Log: https://pastebin.com/TuPYMetA
Pastebin 

## Client Information
* Modpack Version: 3.2.1
* Java Version: 1.12.2
* Launcher Used: CurseForge 
* Memory Allocated: 8000MB
* Server/LAN/Single Player: single player
* Optifine Installed: no
* Shaders Enabled:  no

## World Information
* Modpack Version world created in: none made can't launch
* Additional Content Installed: none

**Comment by sam-kirby** [comment]
The important part of your log is:

```
java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.entity.passive.EntityOcelot, but received empty, your vanilla jar may be corrupt.
```

The vanilla Minecraft 1.12.2 jar file is corrupt, to fix this close Curseforge. Open the folder `I:\reeee\Install\` and delete it.

When you reopen Curseforge, it will tell you you need to reinstall Minecraft. Follow the steps and then try launching again.

If you have further issues with this, contact Curseforge support or post your issue in our support discord server: https://discord.gg/darkosto
