### ISSUE TITLE
Punching trees doesn't damage you

### ISSUE THREAD

**Issue by MasterSpeedPoke** [DarkPacks/SevTech-Ages#4590]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sam-kirby** [comment]
It's not supposed to.
