### ISSUE TITLE
No crafting recipe for most Modular Machinery inputs/outputs

### ISSUE THREAD

**Issue by eturner** [DarkPacks/SevTech-Ages#4598]
## Bug Description

It seems that everything above the smallest item in/outputs are unobtainable. With only four slots, there's no way to make certain recipes like hearty stew with the auto-cauldron. Only 2 out of 8 fluid in/outputs are craftable. Only 4/8 energy inputs, and 2/8 energy outputs are craftable.
I thought they may unlock in a later stage, but I'm at stage 5 now and it's the same. This has affected me on two installations of sevtech with two different launchers on both windows and linux. Although I did copy the same world over, so maybe it's just me somehow.

## Steps to Reproduce (for bugs)

1. Search "@modular machinery" in JEI
2. Try to obtain Normal Item Input (#10298/2)

## Logs

* Client/Server Log:
* Crash Log:
debug.log: https://gist.github.com/eturner/104cd0319f51d3412d3f8e7e499dd7d3

## Client Information
* Modpack Version:
3.2.1
* Java Version:
I compiled openjdk 8 with march/mtune=native
* Launcher Used:
Curseforge on windows and gdlauncher on linux
* Memory Allocated:
12GB
* Server/LAN/Single Player:
Singleplayer
* Optifine Installed:
With Optifine
* Shaders Enabled:
No shaders

## World Information
* Modpack Version world created in:
* Additional Content Installed:
I've only played sevtech 3.2.1, no idea if this is new
I updated a select few mods yesterday, but nothing really relevant and nothing changed

**Comment by sam-kirby** [comment]
The largest auto cauldron recipe wants two input items. Not all cauldron recipes have been copied to the auto-cauldron.

These blocks are not required for any recipe available in the game and so are purposefully disabled.
