### ISSUE TITLE
I have a problem with the dry leather ( SevTech Ages)

### ISSUE THREAD

**Issue by GamerTester** [DarkPacks/SevTech-Ages#4602]
I put salted leather in the drying rack and waited 2 minutes and it didn't happen after that I waited another half an hour and still nothing happened.

With best regards
Julian

**Comment by sam-kirby** [comment]
Are you absolutely certain you made a `Drying Rack` not an `Item Rack`.

They look the same, and have very similar crafting recipes (3 slabs or 2 slabs) but the Item Rack is a decorative item only.
