### ISSUE TITLE
Unable to Start Server on Ubuntu

### ISSUE THREAD

**Issue by t0shiii** [DarkPacks/SevTech-Ages#4603]
## Bug Description

Downloaded server files from curseforge site (https://www.curseforge.com/minecraft/modpacks/sevtech-ages/files/3125814) and moved zip file to server and unzipped and ran Install.sh and then ran ServerSetup.sh and it crashes.  Will attach full log file.

### Did this behavior use to work in the previous version?

Not Sure.  This is the first time running.

## Steps to Reproduce (for bugs)

1. Download server file.
2. Unzip in linux.
3. Run Install.sh
4. Run ServerSetup.sh
5. There will be a long set of warnings and a few errors and it says Killed at the end.

## Logs

* Client/Server Log: https://gist.github.com/t0shiii/33a21e496feeceecc287ad702fadc98b
* Crash Log: Same as above.

## Client Information
N/A as Client is not the issue

## World Information
* Modpack Version world created in:N/A
* Additional Content Installed:N/A

## Server Information
* Java Version:1.8.0
* Operating System:Ubuntu 18
* Hoster/Hosting Solution:Linode
* Sponge (Non-Vanilla Forge) Server:forge 1.12.2-14.23.5.2855 & 2854

**Comment by sam-kirby** [comment]
> it says Killed at the end

This is the most important part of your post. This means the process was sent a kill signal (`SIGKILL`) which means some part of your system has instructed it to close immediately. The usual candidate for why this happens on linux is the oom_reaper. The oom_reaper comes into play when the system is getting dangerously low on memory such that it is likely to become unstable, and kills the largest memory hogs. I can’t confirm this from your logs though, you will have to check your system or kernel logs to confirm (`dmesg -T | grep -i 'killed process'` - add `sudo` to the beginning if you get a permission error).

How much RAM are you assigning to the server and how much does your instance have in total?

**Comment by t0shiii** [comment]
Thanks for the quick response. I can adjust the RAM to ensure there's room.  You can close this out now.
