### ISSUE TITLE
Change JEI tooltip colour back to default

### ISSUE THREAD

**Issue by HueboWasTaken** [DarkPacks/SevTech-Ages#4606]
This isn't a bug or a feature request, but how do I change the tooltip background colour from red back to the default?

![image](https://user-images.githubusercontent.com/28763674/126440643-aa4069b2-47a6-427b-9a01-11b1915cb606.png)

**Comment by HueboWasTaken** [comment]
bruh are you kidding me

**Comment by sam-kirby** [comment]
> bruh are you kidding me

The bot responds the same no matter how many times you post the same thing. This kind of question would be better suited to the Discord server at https://discord.gg/darkosto

> how do I change the tooltip background colour from red back to the default?

Remove the Coloured Tool Tips mod or set a different background colour in its config here:
https://github.com/DarkPacks/SevTech-Ages/blob/master/original/src/config/colouredtooltips.cfg#L11

**Comment by HueboWasTaken** [comment]
> > bruh are you kidding me
> 
> The bot responds the same no matter how many times you post the same thing. This kind of question would be better suited to the Discord server at https://discord.gg/darkosto
> 
> > how do I change the tooltip background colour from red back to the default?
> 
> Remove the Coloured Tool Tips mod or set a different background colour in its config here:
> https://github.com/DarkPacks/SevTech-Ages/blob/master/original/src/config/colouredtooltips.cfg#L11

Bless you
