### ISSUE TITLE
Server error upon first entry to hunting dimension

### ISSUE THREAD

**Issue by peter-ahe** [DarkPacks/SevTech-Ages#4608]
## Bug Description

I entered the hunting dimension and saw an error in the server log. The dimension is empty, I'm not sure if that is intentional or not. As in a void world with only a portal.

### Did this behavior use to work in the previous version?
I don't know.

## Steps to Reproduce (for bugs)

1. Create a new (server) world in SevTech_Ages_of_the_Sky_3_2_1_Beta_1
2. Play until age 1.
3. Create a hunting dimension portal and enter it.
4. The below error show up in the server console.

## Logs

```
[23:00:28] [Server thread/INFO] [FML]: Loading dimension 28885 (world) (net.minecraft.server.dedicated.DedicatedServer@62bf0018)
[23:00:28] [Server thread/INFO] [topography]: Loading Dimension Definition for 28885
[23:00:28] [Server thread/ERROR] [bnbgaminglib]: Failed to load script file null.txt
[23:00:28] [Server thread/ERROR] [reccomplex]: Chunk finished generating without Forge population being triggered (dimension 28885). This is a bug with the dimension - please report this to the dimension's author. Recurrent Complex will proceed to generate in compatibility mode.
[23:00:29] [Server thread/INFO] [journeymap]: USERNAME_REDACTED joining dimension 28885
```

## Client Information
* Modpack Version: SevTech-Ages-of-the-Sky_3.2.1-beta.1-skyblock.zip
* Java Version:
```
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)
```
* Launcher Used: CurseForge
* Memory Allocated: 5291MB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: Unsure (default setting)

## World Information
* Modpack Version world created in: SevTech: Ages of  the Sky Server - v3.2.1 (Beta 1)
* Additional Content Installed: None

## Server Information
* Java Version:
```
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Zulu 8.56.0.21-CA-macosx) (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Zulu 8.56.0.21-CA-macosx) (build 25.302-b08, mixed mode)
```
* Operating System: macOS Big Sur Version 11.4
* Hoster/Hosting Solution: Running on my own Mac Mini (desktop computer)
* Sponge (Non-Vanilla Forge) Server: Don't know.

**Comment by eturner** [comment]
Something similar happened to me repeatedly upon first entering the betweenlands and one of the other dimensions, forget which one.

I just saved and quit while still in that dimension, and then re-logged in. Be careful if you try this and it works, because one of those times I would spawn a couple hundred blocks away from the portal and suffocating underground. This happened repeatedly. I eventually just left all my stuff in the overworld and then let myself die. Everything worked fine after that.

**Comment by peter-ahe** [comment]
The dimension is supposed to be empty. Verified by darkcosto and robertdroptable on stream today.
