### ISSUE TITLE
THERE IS NO SCROLL SENSITIVITY SETTINGS!

### ISSUE THREAD

**Issue by Soy-Boi** [DarkPacks/SevTech-Ages#4615]
## Bug Description

 There is no way to change the mouse scroll sensitivity in settings! I am on mac btw

### Did this behavior use to work in the previous version?

 I dont know I just got it.

## Steps to Reproduce (for bugs)

 
1. look in the control settings and there is nothing

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sam-kirby** [comment]
That’s really an issue for Mojang, not a random mod pack.
