### ISSUE TITLE
Stage restrictions 

### ISSUE THREAD

**Issue by HumanoidCreature1** [DarkPacks/SevTech-Ages#4617]
Normally I am at stage 2 but it doesn't let me use any of my stage restricted items, telling me to get to stage 0,1 and 2 to unlock these. I still have my achivements so I can't really do everything again.

This is the first time it happened.

I had to shutdown my computer while sevtech stages was open.
When I opened it back, everything I made was locked behind stage restrictions. 

## Client Information
* Modpack Version:the latest one
* Java Version:also the latest one?
* Launcher Used:Curseforge?
* Memory Allocated:4000
* Server/LAN/Single Player:Single Player

## World Information
* Modpack Version world created in: it was a few versions back, I don't really remember.
* Additional Content Installed:nope

**Comment by sam-kirby** [comment]
If you shutdown the computer whilst the game is running then you can expect incomplete or corrupted data.

We include a backup mod to aid in situations like this. Restore from a backup made before you shutdown.

If you need help doing so, you should ask on Discord - https://discord.gg/darkosto

**Comment by Arbifoxx** [comment]
which mod has the unfamiliar item feature?
