### ISSUE TITLE
World corruption afther agresive computer  shutdown

### ISSUE THREAD

**Issue by Elsinsejas** [DarkPacks/SevTech-Ages#4620]
## Bug Description

 My world was corrupted and the progression line was reseted and i can use my items because the are unfamiliar now

### Did this behavior use to work in the previous version?

 i dont know if this can hapen in older versions because i dont played before

## Steps to Reproduce (for bugs)

 the power went out and when i joined again in my world it was bugged

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 3.2.1
* Java Version: 
* Launcher Used: Curseforge
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single player
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in:
![image](https://user-images.githubusercontent.com/89112286/129818785-54227216-498d-4f7b-a6e2-073b22926bdf.png)

* Additional Content Installed:
![image](https://user-images.githubusercontent.com/89112286/129818803-420282da-669a-4837-89fd-2118672bc01d.png)
![image](https://user-images.githubusercontent.com/89112286/129818853-6636dfc3-1469-4c7b-9996-a4897885099c.png)

**Comment by Exacutionex** [comment]
Just logged into my world after the same situation with the power yesterday, and same result, I'm on stage two and most of the items in general have somehow unlearned themselves, If there is no fix for this then the hole run is ruined.

**Comment by sam-kirby** [comment]
You should report this to your electricity suppliers, there is nothing we can do about power cuts. Data corruption as a result of lost power or force quitting is pretty common, particularly in a game that modifies stuff on disk as often as Minecraft.

We include a backup mod in the pack for getting out of situations like this. Restore a backup of your world and you should be good. If you need help with this, use the Discord server: https://discord.gg/darkosto
