### ISSUE TITLE
Automatic lubricator unit bug (buckets/milibuckets)

### ISSUE THREAD

**Issue by RichardSabol** [DarkPacks/SevTech-Ages#4625]
FTB continuum, minecraft version 1.12.2. Immersive Engineering version 0.12-88. Immersive petroleum version 1.1.9
Automatic lubricator has set wrong input units. Instead of inserting buckets of lubricator, milibuckets are inserted.

**Comment by sam-kirby** [comment]
This is the issues page for SevTech Ages - FTB Continuum is a different pack from different people.

I tried to replicate your issue in our pack, but could not. Right clicking a bucket on the automatic lubricator inserts 1000mB as expected.
