### ISSUE TITLE
Cannot craft Nocturnal Powder, no way to obtain crushed lapis. Am I just blind?

### ISSUE THREAD

**Issue by Sprankledankle** [DarkPacks/SevTech-Ages#4628]
Am I unintentionally gated? 

Trying to keep this clear and concise. Trying to obtain a **Starmetal Ingot** to open TF portal for progression. Only way to get one is to cook a **Starmetal Ore**. Only way to get an Ore would be through either starlight transmute, which without iron ore wont work, or crafting. Ok, no biggie, I'll craft it. Now here is my issue...the **Nocturnal Powder**

You need **Crushed Lapis** for the recipe. The only way to obtain **Crushed Lapis** that I can find is by grinding the actual ore with the AS grindstone, everything else yields blue dye. Only way I see to get the ore itself since silk touch tinkers mod and enchantments are gated and the AS Stellar Refraction Table which I could use to get the silk touch mod needs 2 starmetal ingots, is the Abyssal Craft...Materializer? I forget the because the text is jumbled from lack of progression. But that in turn takes what looks to be Obsidian, which is gated until the next age. I've tried using blue dye, regular lapis, even tried the old recipes that were replaced, nothing works. Which don't get me wrong is fine, but I cannot get the **Crushed Lapis** to craft the Nocturnal Powder

Recently started play through this modpack and have really enjoyed it but this one part has me wondering if I am just blind to what has to be done or if there is an issue with recipe replacement through the pack. Any and all help is appreciated.

**Comment by sam-kirby** [comment]
Which step requires Crushed Lapis? The recipe for Nocturnal Powder requires plain old Lapis.

![image](https://user-images.githubusercontent.com/23245543/133242476-62e11776-cf53-4750-bc0a-2d90590c33a6.png)
