### ISSUE TITLE
World not rendering properly when playing on servers (3.2.3 -BETA)

### ISSUE THREAD

**Issue by lele92007** [DarkPacks/SevTech-Ages#4654]
## Bug Description
The world do not render properly when playing on a server.
It dosen't seem to be the case when playing in singleplayer.
When you update the chunk it does even werider things

### Did this behavior use to work in the previous version?
Not tested

## Steps to Reproduce (for bugs)
1. Create a server running SevTech : Ages 3.2.3
2. Connect to this server using the same sevtech version
3. You should be able to experience the bug

## Logs
https://gist.github.com/lele92007/9227805894a71fd1bd68e96f994bb8cd

## Client Information
* Modpack Version: 3.2.3
* Java Version: 8u311
* Launcher Used: MultiMC and CurseForge
* Memory Allocated: tested with 4gb and 8+gb
* Server/LAN/Single Player: Server (the bug is clientside)
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.2.3
* Additional Content Installed: Nothing

## Server Information
* Java Version: 16
* Operating System: ubuntu headless (pterodactyl)
* Hoster/Hosting Solution: own server

**Comment by lele92007** [comment]
I'm currently testing with 3.2.1

**Comment by sam-kirby** [comment]
This is the behaviour you would expect to see if connecting to a vanilla server.

As you claim to be using Java 16 on your server, which is incompatible with Forge for 1.12.2, I suspect this is what you've done - if you upload your server logs I can tell you for sure.

**Comment by lele92007** [comment]
Same thing happens when the server is running java 8

**Comment by lele92007** [comment]
Still happens in 3.2.1

**Comment by sam-kirby** [comment]
How are you launching the server?

**Comment by lele92007** [comment]
java -Xms128M -Xmx30000M -jar minecraft_server.1.12.2.jar

**Comment by lele92007** [comment]
![bug3](https://user-images.githubusercontent.com/77411734/146904701-6add7e9e-00a3-498d-9f4d-60a69247b1a5.png)
![bug2](https://user-images.githubusercontent.com/77411734/146904705-09fb990d-bf48-4064-a0a5-57dbc421bfd7.png)
![bug1](https://user-images.githubusercontent.com/77411734/146904706-74a99c20-4094-4d87-8668-14df813b613a.png)
![bug4](https://user-images.githubusercontent.com/77411734/146904707-f3e7d288-bd23-4eee-b1a0-6e6ba22a839e.png)
A few sreens of what it looks like

**Comment by sam-kirby** [comment]
> `minecraft_server.1.12.2.jar`

This is the vanilla Minecraft server. Forge needs it to be present to patch it.

You need to launch the forge jar. See the start script for an example.

**Comment by lele92007** [comment]
This was the cause of the bug, closing the issue.
