### ISSUE TITLE
Sevtech Ages Crashes on Launch

### ISSUE THREAD

**Issue by Deez-lab-lab** [DarkPacks/SevTech-Ages#4657]
## Bug Description

<Pack Crashes on Launch>

### Did this behavior use to work in the previous version?

<I never had this problem until recently, and no version seems to work>

## Steps to Reproduce (for bugs)

<I just start it>
1.Launch the modpack from the UltiMC main page
2.
3.

## Logs

* Client/Server Log:<https://paste.ee/p/V8JlQ (Can't upload it on PasteBin>
* Crash Log:<Can't find it>

## Client Information
* Modpack Version:<3.2.2>
* Java Version:<1.8.0_292>
* Launcher Used:<Ultimc>
* Memory Allocated:<7GB>
* Server/LAN/Single Player:<N/A>
* Optifine Installed:<No>
* Shaders Enabled:<No>

## World Information
* Modpack Version world created in:<N/A>
* Additional Content Installed:<N/A>
This modpack used to work just fine, but after a crash it stopped working, and I tried re-installing it without any success.  I really LOVED this modpack, so any help is appreciated. If any other information is needed I can provide it. It's on Linux Arch, and it used to run just fine.

**Comment by sam-kirby** [comment]
We do not support cracked launchers.
