### ISSUE TITLE
Green world border keeps appearing and stops from the horizon to down

### ISSUE THREAD

**Issue by Hymandois** [DarkPacks/SevTech-Ages#4663]
## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sam-kirby** [comment]
I've not seen anything like this before - have you played other packs on 1.12.2 without seeing this?

**Comment by Hymandois** [comment]
Yes, it is only Sevtech that is having this issue
