### ISSUE TITLE
No death key

### ISSUE THREAD

**Issue by KingCreeper262** [DarkPacks/SevTech-Ages#4667]
## Bug Description

 Whenever I die in 3.2.3 I never get the key and my stuff is locked the grave

### Did this behavior use to work in the previous version?

 3.1.7

## Steps to Reproduce (for bugs)

1. Start sevtech ages 3.2.3
2. create a singleplayer world
3. die in any way possible

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 3.2.3
* Java Version: No idea
* Launcher Used: AtLauncher
* Memory Allocated: roughly 4000 mb
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.2.3
* Additional Content Installed: None

**Comment by sam-kirby** [comment]
Pressing shift whilst standing on the grave should give you your items back.

**Comment by KingCreeper262** [comment]
thx
