### ISSUE TITLE
Softlocked, by unable to craft a Grass Fiber Mesh in Version 3.2.1 on CurseForge

### ISSUE THREAD

**Issue by Tiki103** [DarkPacks/SevTech-Ages#4669]
## Bug Description
 Softlocked by unable to craft Grass Fiber Mesh

1. Hi, my friend hosted a Sevtech Server on 3.2.1 Version on Curseforge - he is currently soft-locked as he can't craft a Grass Fiber Mesh in his own inventory 4x4 crafting. 
2. My friend could also craft planks from logs in the tutorial stage as well as if he was playing normal minecraft. This suggests that the crafting recipes from mods are not in the proper format or are not being processed.

I am still updating this issue ticket so please be mindful.

Also, we could not play on the latest server because the ScalaCube servers have not been updated on the modpack options.

Is there a possible solution for this? This is my first post "issue" on Github, and being a liaison for someone else, I don't have all the details. 

## Steps to Reproduce (for bugs)

1. Launch server and play grab the fibers and sticks.
2. Following the crafting recipe of the Grass Fiber Mesh, which does not show the item for the crafted result.
3. 

## Logs

* Client/Server Log:

## Client Information
* Modpack Version:
* Server/LAN/Single Player:
* Hoster/Hosting Solution:

**Comment by sam-kirby** [comment]
We've had several reports in the past of issues with ScalaCube's implementation of a SevTech server.

The server files we ship on CurseForge are perfectly functional; ScalaCube have broken something when setting up their automated installer.

To have a hope of figuring out what they've broken, please provide logs. In particular, the `crafttweaker.log` file.

**Comment by Tiki103** [comment]
> We've had several reports in the past of issues with ScalaCube's implementation of a SevTech server.
> 
> The server files we ship on CurseForge are perfectly functional; ScalaCube have broken something when setting up their automated installer.
> 
> To have a hope of figuring out what they've broken, please provide logs. In particular, the `crafttweaker.log` file.

Thank you for the information.

I am also updating now that there are also other bugs in the servers that are on ScalaCube servers, I will reply to this post so you can view them.

Can you direct me to where I can find the crafttweaker.log file? This is to help my friend to navigate the files more easily rather than the hustle in the Default Computer search.

Once again, Thank you very much.
Regards, TIKI103

**Comment by Reallyaceman** [comment]
Hello! I am one of TIKI's friends and I'm here to provide the crafttweaker log:
[crafttweaker.log](https://github.com/DarkPacks/SevTech-Ages/files/7965282/crafttweaker.log)

Hope this helps!
-Reallyaceman

**Comment by sam-kirby** [comment]
You appear to be missing two mods on the server; ModTweaker version 4.0.17 and JourneyMapStages version 2.0.9.

ModTweaker allows us to write custom recipes for a wide range of different mods including Tinker's Construct, Blood Magic and Better With Mods. It is an essential part of the pack.

JourneyMapStages allows us to control when you unlock the ability to use JourneyMap. It is important to the feel of the pack in the early game, where you are intended to use an Antique Atlas as your map.

Both of these mods are required for the pack to load the custom recipes correctly.

It is possible there are other problems that will become apparent once this is resolved; if that is the case please again provide the CraftTweaker log. You could also inform ScalaCube of the problem with their installer.

**Comment by Tiki103** [comment]
Thank you very much on my and my friends' behalf. I will continue to update or inform whether such changes are prevalent.
Sincere Regards,
Tiki103, Reallyaceman, and behalf of another.
