### ISSUE TITLE
Many recipes broken in 3.2.3

### ISSUE THREAD

**Issue by hideyyo** [DarkPacks/SevTech-Ages#4670]
## Bug Description

White dye powder from bonemeal, porcelain, and transmutation gem, among other recipes, no longer work properly.

### Did this behavior use to work in the previous version?

Worked properly in version 3.2.1

## Steps to Reproduce (for bugs)

1. Create a 3.2.1 server
2. Upgrade to 3.2.3
3. Attempt to craft certain recipes, and the game fails to craft them.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 3.2.3
* Java Version: 1.12.2
* Launcher Used: CurseForge
* Memory Allocated:16 GB
* Server/LAN/Single Player: Server
* Optifine Installed: N/A
* Shaders Enabled: N/A

## World Information
* Modpack Version world created in:
* Additional Content Installed:

## Server Information
* Java Version: 1.12.2
* Operating System: Linux
* Hoster/Hosting Solution: Shockbyte
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Could you please provide the CraftTweaker log from your server?

**Comment by hideyyo** [comment]
I could provide the logs but the directory tree of the server is still foreign to me and I'll have to try to navigate this tree to find the proper logs

**Comment by sam-kirby** [comment]
It's the file called `crafttweaker.log` in the server's root directory.

**Comment by hideyyo** [comment]
[crafttweaker.log](https://github.com/DarkPacks/SevTech-Ages/files/7967187/crafttweaker.log)

**Comment by sam-kirby** [comment]
Something seems to have gone wrong when you upgraded, you don't seem to have Ferdinhand's Flowers and there's some issue with Pneumaticcraft too. Perhaps one of the pneumaticcraft scripts is missing?

I checked the modpack as its available on CurseForge and I don't see these errors. When searching this log there should only be 5 errors (lines with `[ERROR]`) at the bottom; you have 433 errors.

As it's late here I won't respond to this anymore tonight, you could try the Discord server if you need further help. https://discord.gg/darkosto

As this doesn't appear to be an issue with the pack, I'm closing this. Please reopen if you can demonstrate I'm wrong.
