### ISSUE TITLE
Totemic Mod & Horses Issue

### ISSUE THREAD

**Issue by MBTNK** [DarkPacks/SevTech-Ages#4675]
## Bug Description
I have played through the stone age twice now, first a few months back and again just recently today. I have run into the same problems as last time and I don't know whether this is intended or maybe it's a bug of some sort. I spent about 10 hours on my current default world and for the entirety of the session I haven't spotted a single horse in any biome whatsoever, so I can't progress through "Pressing your luck". I found Lamas, Brown Bears, Black Bears, temples, rabbits, villagers, everything but horses. 

After I gave up looking, I decided to do another quest. Then for the past four hours, I have been trying to complete a ritual and neither Rite of Spring or Buffalo Dance works. Rite of spring has done nothing, I've littered the ground with every food type for breeding but animals won't breed. I have actually lost my mind smacking these drums and hoping that my chimes will activate altogether to finish the buffalo dance ritual - the bar always gets so close to filling up but the timer always runs out. I've been repeating the same thing over and over again, moving the chimes around, had 8 at one point, then noticed you have to use 2 or 3 - this still didn't work.

I tried being patient and thought that maybe it was intended to be hard. However, don't you think repeating the same two rituals for four hours is a little too excessive? I've looked up You Tube tutorials and read online for solutions but to no avail. I feel so annoyed that I've grinded for so long and nothing will let me progress past those three quests.

### Did this behavior use to work in the previous version?
I haven't played for a few months so, I have no idea what version I used last.

## Steps to Reproduce (for bugs)
1. Grind to quests: "Pressing Your Luck", "Ancient Animals", "Rite of Spring".
2. Follow the instructions (Finding a horse for Pressing your Luck and performing the rituals with the totemic mod).
3. Realize that you can't find a single horse or complete any of the rituals.

## Client Information
* Modpack Version: 3.2.3
* Java Version: 1.8.0_51 64Bit
* Launcher Used: Minecraft Launcher
* Memory Allocated: 12GB RAM
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.2.3
* Additional Content Installed: No

**Comment by sam-kirby** [comment]
1) The mod may be called "Horse Powered", but you do not need to use horses. You can use practically anything, and tamed wolves in the sitting position are particularly hilarious. Horses should be found in the plains, though.
2) I cannot reproduce your issues with the Rite of Spring or Buffalo Dance. With the Rite of Spring, the food needs to be on the ground nearby to the totem base and the animals need to be fairly close too. When it comes to the Buffalo Dance it sounds like you need more instruments; you can make the pipe flute, the rattle and the jingle skirt in addition to the drums and chimes at this stage in the game. Each instrument has a maximum it can contribute to rituals and so switching between them is essential.
