### ISSUE TITLE
SevTech Ages öffnet nicht

### ISSUE THREAD

**Issue by LadyHerbstwald** [DarkPacks/SevTech-Ages#4676]
## Bug Description

 Das Spiel läd nicht nach dem minecraft Luncher da steht dann nur  Fehler  Spielabsturz Ein unerwartetes Problem ist aufgetreten und das Spiel ist abgestürzt. Wir entschuldigen uns für die Unannehmlichkeiten Exit-Code:0

### Did this behavior use to work in the previous version?

 ich habe es noch nie gespielt egal welche version ich nehme 

## Steps to Reproduce (for bugs)

1. öffnen sevTech ages auf Curse Forge
2. Luncher Spielstarten und dann kommt der fehler
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:3.2.3
* Java Version: Ja
* Launcher Used: Minecraft launcher
* Memory Allocated:
* Server/LAN/Single Player: Singel Player
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in: nein
* Additional Content Installed: nein

**Comment by sam-kirby** [comment]
Without a crash report or log I cannot offer any advice as I have no idea what the problem is.
