### ISSUE TITLE
Sky not rendering part way down?

### ISSUE THREAD

**Issue by HeavyDeception** [DarkPacks/SevTech-Ages#4679]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sam-kirby** [comment]
This might be caused by Overwolf injecting buggy code to make its overlay work. Try playing with Overwolf completely stopped.

**Comment by HeavyDeception** [comment]
the overlay for Minecraft is off.

**Comment by HeavyDeception** [comment]
@sam-kirby go it part of it was a recording software that was picking up java. Doing the same as Overwolf thanks for adding that comment as it help me a tone in finding out what was happening.
