### ISSUE TITLE
Server not starting on arm

### ISSUE THREAD

**Issue by JensDeLeersnyder** [DarkPacks/SevTech-Ages#4681]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
This has nothing to do with the processor architecture; Forge for Minecraft 1.12.2 requires that you use Java 8. Java 17 is unsupported and crashes with this error on any architecture.

**Comment by sam-kirby** [comment]
I recently wrote a reply to another user trying to start an SF4 server on an RPi (aarch64) which may be of interest to you:

https://github.com/DarkPacks/SkyFactory-4/issues/2051#issuecomment-1021143152
