### ISSUE TITLE
Finite Water

### ISSUE THREAD

**Issue by ItzPixql** [DarkPacks/SevTech-Ages#4682]
## Bug Description

Water is never infinite in river or ocean biomes etc. even though it says its infinite in river and ocean biomes.

## Steps to Reproduce (for bugs)

1.Picking up water with fluid bladders in a river
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:Latest
* Java Version:Latest
* Launcher Used:Curseforge
* Memory Allocated:5GB
* Server/LAN/Single Player:Singleplayer
* Optifine Installed:No
* Shaders Enabled:No

## World Information
* Modpack Version world created in:Latest
* Additional Content Installed:None

**Comment by sam-kirby** [comment]
https://user-images.githubusercontent.com/23245543/155118043-1a0f7147-44b9-4ac0-b930-4a22f6a02229.mp4

I cannot reproduce this.

Make sure you're not trying to take from a block right on the edge of the river/ocean as these may not officially be in the correct biome.
