### ISSUE TITLE
i can't walk in linux with TLaucher

### ISSUE THREAD

**Issue by ama-coder** [DarkPacks/SevTech-Ages#4683]
## Bug Description
i can't walk in linux with TLaucher.
i use server version to private gaming. (solo)

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
This pack has not, and will never be, released on TLauncher.
