### ISSUE TITLE
Unfamiliar item glitch

### ISSUE THREAD

**Issue by DewinOrSkill** [DarkPacks/SevTech-Ages#4684]
## Bug Description
I had played a little bit and was nearly able to make a fluid bladder. When i logged back in the game a few days later it said my picaxe, shovel and some other things were unfamiliar items and threw them out when just a few days before i could hold them. i haven't changed anything since last i played.

### Did this behavior use to work in the previous version?
This have only happened just now.

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:latest
* Java Version:don't know
* Launcher Used:not the new one
* Memory Allocated:4000
* Server/LAN/Single Player:singleplayer
* Optifine Installed:no
* Shaders Enabled:no

## World Information
* Modpack Version world created in:Created in latest version
* Additional Content Installed:no additional content

**Comment by sam-kirby** [comment]
This is usually caused by the game stages data file for your player becoming corrupted. You can restore it using commands or from a backup. For more support please use the Discord: https://discord.gg/darkosto
