### ISSUE TITLE
Lost advancement progress

### ISSUE THREAD

**Issue by DewinOrSkill** [DarkPacks/SevTech-Ages#4686]
## Bug Description
I logged in my world after a few days and the pprogress is still there but i cant hold certain items that is further in the advancement progress

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by dilanmaravilha** [comment]
eu tabem estou com esse ploblema

**Comment by sam-kirby** [comment]
Restore a backup; for further support please ask on Discord https://discord.gg/darkosto
