### ISSUE TITLE
problem with geolosys mod

### ISSUE THREAD

**Issue by mati294** [DarkPacks/SevTech-Ages#4687]
I have reached stage 1 and have reached prospecting but the stones have not turned into ore samples. even those stones that do not break down right away, that is, they should turn into samples.
Version 3.2.3 default world mode.
restarting the launcher did not help

**Comment by sam-kirby** [comment]
You won't be able to see every ore in age one; a large proportion remain hidden.

**Comment by mati294** [comment]
> You won't be able to see every ore in age one; a large proportion remain hidden.

How do I do a task where I have to find an ore sample since the any ore is not visible? Copper coal etc.

**Comment by sam-kirby** [comment]
Both copper and coal will be visible, however there are many other ores that won't be until much later e.g. Iron, Gold, Redstone, Lapis, Quartz, Silicon, Diamond, etc.

**Comment by mati294** [comment]
> Both copper and coal will be visible, however there are many other ores that won't be until much later e.g. Iron, Gold, Redstone, Lapis, Quartz, Silicon, Diamond, etc.

I spent about 1.5 hours searching in different biomes (in wtm those indicated in the task) and I did not come across a single sample ...

**Comment by sam-kirby** [comment]
As you mention biomes corresponding to ores, are you playing "SevTech Ages of the Sky"?

If you've set it to Default world generation instead of Topography, you've turned off ore generation. This version of the pack is only intended to be played on the Sky Islands world type.

**Comment by mati294** [comment]
Are you sure it doesn't work?
Because some stones behave as if they were samples, they are not yet visible as samples

**Comment by sam-kirby** [comment]
Most ore generation is turned off as it would interfere with island generation.

A very small number of ores are still allowed to generate - astral's crystals, silicon and maybe quartz.

If you wish to continue playing on this world then you'll probably have to cheat in ores.

I would however recommend starting again - either on SevTech Ages if you want to play on a regular overworld or using the Topography sky islands world type on SevTech Ages of the Sky.
