### ISSUE TITLE
Chunks not loading

### ISSUE THREAD

**Issue by Zeek-AZ** [DarkPacks/SevTech-Ages#4689]
## Bug Description
When I load into a newly created server none of my chuncks are loading correctly. Everything is invisible until I destroy or sometimes place a block, then part of the chunk will load.

### Did this behavior use to work in the previous version?
No other previous version used.

## Steps to Reproduce (for bugs)
1.start server 
2.logged into server
3.No textures in the chuncks load

## Logs

* Client Log:https://pastebin.pl/view/eeb23ecd
* Server Log: https://pastebin.pl/view/64a8697f
* Crash Log: 

## Client Information
* Modpack Version:3.1.7
* Java Version:Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51
* Launcher Used:Minecraft Launcher with Forge 14.23.5.2860
* Memory Allocated:6GB
* Server/LAN/Single Player:Server
* Optifine Installed:No
* Shaders Enabled:tried with and without shades on, made no difference

**Comment by sam-kirby** [comment]
I gave the following reply on your previous issue report; please stop spamming.

> There are significant issues with your client setup evident from your logs. You indicate you only included the mods folder, but this is useless on its own - you will also need the configuration, resources and scripts.
> 
> Your client also indicates it is connecting to a vanilla server:
> 
> ```
> [09:51:42] [Netty Client IO #0/INFO] [FML]: [Netty Client IO #0] Client side vanilla connection established
> ```
> 
> And this is exactly the behaviour we would expect to see when connecting to a vanilla server as the client is expecting a modified protocol.
> 
> I suggest you use a launcher such as multimc to setup the client and follow the guide for setting up a server. If you need assistance, it would be best to ask on Discord at https://discord.gg/darkosto rather than opening issues here.

**Comment by sam-kirby** [comment]
Your server log makes clear you are starting a vanilla server. A modded server produces thousands of lines of output before loading the world.
