### ISSUE TITLE
Grass Fiber Mesh does not show correct recipe in JEI

### ISSUE THREAD

**Issue by restics** [DarkPacks/SevTech-Ages#4691]
## Bug Description

 Looking up the recipe for plant fiber mesh reveals a 3x3 recipe in JEI, however, you can still craft the 2x2 recipe.

### Did this behavior use to work in the previous version?

 Yes, I remember playing in 3.2.1 and this bug wasn't present.

## Steps to Reproduce (for bugs)

1. Go into JEI
2. Look up "mesh"
3. Left click on Grass Fiber Mesh from Pickle Tweaks

## Logs

* Client/Server Log:https://paste.ee/p/8CZ2D
* Crash Log:

## Client Information
* Modpack Version:3.2.3
* Java Version:1.8
* Launcher Used:multimc
* Memory Allocated:8gb
* Server/LAN/Single Player:Singleplayer & Server
* Optifine Installed:No
* Shaders Enabled:No

## World Information
* Modpack Version world created in:3.2.3
* Additional Content Installed:none

**Comment by sam-kirby** [comment]
I cannot reproduce this with a fresh install of 3.2.3. Usually this indicates an issue with your installation. Could you please attach your client's crafttweaker log (`crafttweaker.log`)?

**Comment by sam-kirby** [comment]
Closed as no response
