### ISSUE TITLE
its broken for me

### ISSUE THREAD

**Issue by zacharyhenry** [DarkPacks/SevTech-Ages#4703]
## Bug Description

https://photos.app.goo.gl/3Gnrh94dDcANyDXy8

i cant get pass this on tech age tutorial its broken for me

## Client Information
* Modpack Version:3.2.3
* Java Version:
* Launcher Used:gdlauncher
* Memory Allocated:8gb

**Comment by sam-kirby** [comment]
Use a different launcher, GDLauncher is broken and doesn't install the pack properly.
