### ISSUE TITLE
Server Stalling in Initialization

### ISSUE THREAD

**Issue by SaintBeef** [DarkPacks/SevTech-Ages#4704]
## Bug Description

The server stalls in the initialization process upon
`Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper`

### Did this behavior use to work in the previous version?

First time running server, don't know

## Steps to Reproduce (for bugs)

https://youtu.be/UF4LpZyaxQw

## Logs

*Client/Server Log: [latest.log](https://pastebin.com/EvYGRWYH) + [debug.log](https://pastebin.com/zCxbGr4p)

## Client Information
* Modpack Version: N/A
* Java Version: N/A
* Launcher Used: N/A
* Memory Allocated: N/A
* Server/LAN/Single Player: N/A
* Optifine Installed: N/A
* Shaders Enabled: N/A

## World Information
* Modpack Version world created in: 3.2.3
* Additional Content Installed: N/A

## Server Information
* Java Version: 1.8.0_332-b04
* Operating System: Arch Linux (5.15.32-1-lts)
* Hoster/Hosting Solution: Seperate Server Computer
* Sponge (Non-Vanilla Forge) Server: None

**Comment by sam-kirby** [comment]
I cannot reproduce this on OpenJDK 1.8.0_332-b04 and 5.17.2-zen2-1-zen - server prompts for eula acceptance as expected following the steps from your video. Accepting the eula results in a successful startup.

**Comment by SaintBeef** [comment]
Problem ended up being with the environment
