### ISSUE TITLE
Sevtech ages server having major stutter issues and lag

### ISSUE THREAD

**Issue by Babdser** [DarkPacks/SevTech-Ages#4714]
Me and friends have tried multiple times to start a server we get it running but the second anyone trys to play the lag is so unbearable it isnt playable. Everything stutters very hard and I dont want to pay for a server. Does anyone know the causes of these major lag issues??

**Comment by sam-kirby** [comment]
Do you have a window like in the screenshot attached on screen when you launch the server?

![image](https://user-images.githubusercontent.com/23245543/169646060-191bff10-e6bb-4e8d-a82c-98939ed7272d.png)
