### ISSUE TITLE
Crash Ages of Sky play on Feed The Beast

### ISSUE THREAD

**Issue by LaChoucrouteDu14** [DarkPacks/SevTech-Ages#4725]
1.  The Bug Description

I play Ages of Sky 3.2.0-alpha-2 on Feed The Beast And when I trying to launch my world the serveur Crash The log crash Said .
" _Client Shutdown Thread Warn Unable To register log4j shutdown hook because HVM is Shutting Down_."

2.  Did this behavior use to work in the previous version?

- Nop

3. Steps to Reproduce 

Launch the modpack/Load in my World/Crash

4. Logs And Crash Reports

- [crash-2022-08-01_12.50.34-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/9233405/crash-2022-08-01_12.50.34-server.txt)

- ![Screenshot 2022-08-01 130435](https://user-images.githubusercontent.com/110392162/182136674-255ec17d-0b25-4e78-a10c-68b3efaa7ab6.png)

5. Client Information

- Modpack Version: 3.2.0
- Java Version: 8 update 333
- Launcher Used: overwolf
- Memory Allocated:7 gb on the server
- Play in SinglePlayer
- Optifine Installed:no
- Shaders Enabled:no

6. World Informations

- ModPack version 3.2.0
- Additional Content Installed:none

**Comment by sam-kirby** [comment]
1) what does "on Feed The Beast" mean? We are not affliated with FTB, and you list your launcher as Overwolf.
2) does this issue still occur if you update to the latest version?

**Comment by LaChoucrouteDu14** [comment]
1. My launcher is Overwolf You're right and i gonna tried to update to the latest version

**Comment by LaChoucrouteDu14** [comment]
It works very well thanks you :)
