### ISSUE TITLE
[1.18.2] Addon Recipes missing Enigmatica 8

### ISSUE THREAD

**Issue by balloonhead** [DarkPacks/SevTech-Ages#4726]
## Bug Description
The recipes for the Addons like the Range Addon are missing.

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: Enigmatica 8
* Java Version: OpenJDK 17.0.1
* Launcher Used: GDLauncher
* Memory Allocated: 16GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 1.18.2
* Additional Content Installed: no.

**Comment by balloonhead** [comment]
wrong place. Ment to go into Industrial Foregoing error

**Comment by sam-kirby** [comment]
This seems entirely unrelated to us, so closing.
