### ISSUE TITLE
the leather is not working i try to make it but recipe stopped working

### ISSUE THREAD

**Issue by iaintgotnoclue34** [DarkPacks/SevTech-Ages#4729]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sam-kirby** [comment]
Ensure you're using a drying rack and not an item rack; the item rack is decorative only.

Without more information I can't help you further.
