### ISSUE TITLE
Restore inventory

### ISSUE THREAD

**Issue by Repoman1099** [DarkPacks/SevTech-Ages#4730]
I was going through the teleport in the end to one of the end city gateways and it teleported me into the void. This was a bogus death caused by a glitch. This was not the first time through this particular gateway. The first time I went through without any issues. This time sent me straight into the void. How can I retrieve my grave as it is at y=0 in the end? Is there a way to restore my inventory? Please let me know. Thanks.

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sam-kirby** [comment]
You can take your player data from a backup or you can retrieve your grave - it should have searched for land above to place the grave on so if you were below an end island it should have put the grave on the island.

You have neglected to mention which version of the pack you are playing, so I'm assuming you're playing 3.2.3 - the latest. In this version there is unfortunately no command that restores your inventory from a grave.
