### ISSUE TITLE
Advancements - Farmer: Necrofarmer not achievable. Plant Tonic not available for crafting. v2

### ISSUE THREAD

**Issue by TimpAofc** [DarkPacks/SevTech-Ages#4738]
## Bug Description

 Unable to craft "Plant Tonic" for Advancements - Farmer: Necrofarmer.

According to wiki, recipe requires a "Weedwood/Syrmorite Bucket" filled with "Swamp Water" + a "Ball of Sap".

Recipe does not appear in JEI, but the recipe can be seen if checking the uses of "Ball of Sap". However, that recipe in-game shows only an empty "Weedwood/Syrmorite Bucket" + a "Ball of Sap".

Have tried picking up "Swamp Water" with the "Weedwood/Syrmorite Bucket" but it won't go into said bucket. Can be picked up using an ordinary bucket.

![necrofarmer](https://user-images.githubusercontent.com/55051941/190653352-ec624581-dfec-445b-a765-c9da09fcb4a6.png)
![tonic](https://user-images.githubusercontent.com/55051941/190653357-5340ed2e-622d-433c-bbbc-3c60dcfe741c.png)
![tonic2](https://user-images.githubusercontent.com/55051941/190653358-175c575d-6875-4bb3-9167-a9fcb8fbae60.png)
![tonic3](https://user-images.githubusercontent.com/55051941/190653362-01d0f964-a2cd-43a7-8351-2a87d5bf5ec4.png)

### Did this behavior use to work in the previous version?

Have only played this version.

## Steps to Reproduce (for bugs)

1.Have required reagents for recipe.
2.Unable to craft.

## Logs

* Client/Server Log:No crashes.
* Crash Log:No crashes.

## Client Information
* Modpack Version: Sevtech Ages 3.2.3
* Java Version: 1.8.0_311
* Launcher Used: MultiMC
* Memory Allocated: 8192MiB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: Sevtech Ages 3.2.3
* Additional Content Installed: None

## Server Information
* Java Version: Assuming 1.8.0
* Operating System: No idea
* Hoster/Hosting Solution: ZAP-Hosting
* Sponge (Non-Vanilla Forge) Server: No idea. "1.12.2/fml,forge" or "Forge 14.23.5.2860" if that helps.

**Comment by sam-kirby** [comment]
I don't seem to have any issue picking up swamp water with either the syrmorite or the weedwood bucket. Could you expand on this aspect of your issue? The recipe works when using a bucket filled with swamp water. The recipe *is* incorrect in JEI, but I assume this is why it is hidden.
![image](https://user-images.githubusercontent.com/23245543/193428225-e4ffd7d9-0f5b-4f67-b357-8a91836dae1a.png)

**Comment by TimpAofc** [comment]
Don't know how the issue got resolved, but I was able to craft the Plant Tonic two weeks later.
Maybe an issue with the bucket or something changed after a server reset.
