### ISSUE TITLE
unfamiliar item

### ISSUE THREAD

**Issue by mistyboi** [DarkPacks/SevTech-Ages#4741]
## Bug Description

 This is my first time opening a sevtech modpack on the compact skies world variant, as soon as I spawn in. In chat it says: dropped unfamiliar item. this item is the personal shrinking device. This causes a problem, as you need that to start in the world type

### Did this behavior use to work in the previous version?

i dont know

## Steps to Reproduce (for bugs)

 i dont know
1.
2.
3.

## Logs

* Client/Server Log:.
* Crash Log:.

## Client Information
* Modpack Version: 1.12.2
* Java Version: 1.12.2
* Launcher Used: curseforge
* Memory Allocated:3800
* Server/LAN/Single Player:single player
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in: 3.2.3
* Additional Content Installed: none

**Comment by sam-kirby** [comment]
Compact sky is not a supported world type; `topography` sky islands is the only supported world type.

It would be impossible to get any resources on compact sky and it would require a major reworking to make it viable. This would probably have to be a separate pack.
