### ISSUE TITLE
SevTech Ages failing launch sequence

### ISSUE THREAD

**Issue by BlorglyShnorf** [DarkPacks/SevTech-Ages#4742]
Link for log:
[](https://paste.ee/p/QIbbq)

Every time I try to launch the game, it fails on exit code -1. I have Java 17 on my computer, and I'm using MultiMC to launch.

Any fixes? Please let me know.

**Comment by sam-kirby** [comment]
You must use Java 8 with forge for 1.12.2, as used in this pack. Java 9 and newer made significant changes to reflection and Forge has not been updated in 1.12.2 to support this.
