### ISSUE TITLE
World will not load 

### ISSUE THREAD

**Issue by Cbuff94** [DarkPacks/SevTech-Ages#4745]
## Bug Description
Power Surged Computer restarted mod pack loaded loading world game crashes multiple times I've tried loading the world I have 50 hours into this world. Avg 100 fps and 70% Ram usage at 8 chunks rendered

## Steps to Reproduce (for bugs)
1.Power goes out
2.Computer Restarts
3.Load modpack
4.Loads world CRASH

## Logs
<!-- 📝
* Client/Server Log:
* Crash Log:
https://paste.atlauncher.com/view/7706a4d9-08c3-4d00-8e09-0669dc128f54

## Client Information
* Modpack Version: 3.2.3
* Java Version: Provided By launcher and/or Modpack
* Launcher Used: At Launcher
* Memory Allocated: 5400 MB
* Server/LAN/Single Player: Single player
* Optifine Installed: N
* Shaders Enabled: N

## World Information
* Modpack Version world created in: 3.2.3
* Additional Content Installed: N

**Comment by Cbuff94** [comment]
WTF I followed the template to a T

**Comment by sam-kirby** [comment]
```
<!-- 📝
```
indicates the start of a "comment", a hidden block of text. As you never end it with `-->`, the rest of your post is not displayed, and so it looks to the bot like you didn't follow the template.

Regardless, world corruption as a result of power loss is not a bug with the pack and not something we can resolve.

The modpack includes a backup mod, which by default creates backups every 30 minutes of playtime. You should be able to restore one of these backups. If you need help on how to do this, please ask on Discord (https://discord.gg/darkosto).

**Comment by Cbuff94** [comment]
That’s what don’t make sense though none of the back ups load either I do
believe your correct in the route of world corruption but why won’t the
backups work I’m more then willing to just start a new world but I’d much
rather keep the 50 hours in the one I have. So I just want an explanation
as to why the world backups aren’t working that’s why I put it in as a bug.
