### ISSUE TITLE
Can't unlock stage0 normally in server without op permission

### ISSUE THREAD

**Issue by Kzybd** [DarkPacks/SevTech-Ages#4751]
## Bug Description

Player in my server who have op permission can unlock stage0 normally, but others can't unlock stage0 when they get the same advencement. (The advencement unlock normallly, but their gamestage info have only tutorial) When I revoke their advencement and give them op permission, they can unlock the stage.

### Did this behavior use to work in the previous version?

Not tried yet

## Steps to Reproduce (for bugs)

1.Enter the server, follow the advencement
2.Bulid the Work Stump, advencement unlock
3.stage didn't unlock, Stone Pickaxe can't used. /gamestage info shows only tutorial 

## Logs

* Client/Server Log:
[latest.log](https://github.com/DarkPacks/SevTech-Ages/files/9892047/latest.log)
* Crash Log:

## Client Information
* Modpack Version:3.2.3
* Java Version:Java 8
* Launcher Used:HMCL
* Memory Allocated:15G
* Server/LAN/Single Player:Server
* Optifine Installed:None
* Shaders Enabled:Disabled

## World Information
* Modpack Version world created in:
* Additional Content Installed:

## Server Information
* Java Version:java 8
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Your plugins seem to be messing up the permissions system; completing the advancement runs a function that would require OP if run manually.

Without plugins, these are run by Triumph on behalf of the player successfully. If you can allow Triumph to run these commands then it should work.

As this is a result of your modification to the pack, not an issue with the pack, and it is outside my area of expertise, I am closing this issue. If there is a change we can make to the pack that will fix this, please open a separate issue stating clearly what change we would need to make.

**Comment by sam-kirby** [comment]
For your reference, the function names take the form of e.g. `triumph:stage-0_trigger` and are stored [here](https://github.com/DarkPacks/SevTech-Ages/blob/master/original/src/config/triumph/functions/stage-0_trigger.txt).

**Comment by Kzybd** [comment]
> Your plugins seem to be messing up the permissions system; completing the advancement runs a function that would require OP if run manually.
> 
> Without plugins, these are run by Triumph on behalf of the player successfully. If you can allow Triumph to run these commands then it should work.
> 
> As this is a result of your modification to the pack, not an issue with the pack, and it is outside my area of expertise, I am closing this issue. If there is a change we can make to the pack that will fix this, please open a separate issue stating clearly what change we would need to make.

The save issue happened without Groupmanager plugin, I add this means to give the permisson of the command, but faild. Thanks for your help.
