### ISSUE TITLE
Tin/Bronze is broken on the Stone anvil

### ISSUE THREAD

**Issue by Yusufk033** [DarkPacks/SevTech-Ages#4754]
## Steps to Reproduce (for bugs)

1. Slap a tin/bronze plate on an anvil and use the stone mallet. 
2 .Don't get the plates that u are meant to get.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: Latest
* Java Version:Latest
* Launcher Used:Curseforge
* Memory Allocated:5600MB
* Server/LAN/Single Player:Server
* Optifine Installed:x
* Shaders Enabled:x

## World Information
* Modpack Version world created in:X
* Additional Content Installed:X

## Server Information
* Java Version:X
* Operating System:X
* Hoster/Hosting Solution:X
* Sponge (Non-Vanilla Forge) Server:X

**Comment by sam-kirby** [comment]
Numerous players have noticed issues recently stemming from an issue with the Curseforge launcher that results in a desync between the contenttweaker item IDs on server and clients. Could you try installing a new instance of the modpack on Curseforge and seeing if the issue persists on that clean install?

**Comment by Yusufk033** [comment]
Redownloading it fixed it, and im now getting the intended plates, Thanks! This also fixed it for my server.
