### ISSUE TITLE
Aquamarine Ore Replaced with Platinum Blocks in the Beneath Dimension

### ISSUE THREAD

**Issue by eruhkzor** [DarkPacks/SevTech-Ages#4756]
## Bug Description
I've been to the Beneath Dimension twice in total. The first time, I had no issues collecting Aquamarine from Aquamarine Ore. A couple weeks later, I went back to collect more Aquamarine. Now, it appears that Aquamarine Ore has been completely replaced with Platinum Blocks. Additionally, the icon for the Age 1 advancement for collecting Aquamarine, which I completed previously when it worked properly, has also been replaced with a Platinum Block. This is a serious issue for Astral Sorcery progression.

Note: After my first time to the Beneath, I broke the portal and then placed it into a chest. Today, I took it out of the chest and put it in a different location, then used it.

[Platinum blocks in the Beneath](https://prnt.sc/s10iNa2J6Qpq)
[Age 1 Aquamarine advancement](https://prnt.sc/cNgsWI0l4jRa)

### Did this behavior use to work in the previous version?
While there was a timespan of a couple weeks between the times I visited the Beneath, I don't think there were any modpack updates or changes.

## Steps to Reproduce (for bugs)
1. Go to the top of the Beneath and find Platinum Blocks where Aquamarine Ore should be

## Logs
* [Client Log](https://pastebin.com/NkKqUBni)
* Crash Log: No crashes occurred

## Client Information
* Modpack Version: 3.2.3
* Java Version: 8.0.51.16
* Launcher Used: CurseForge
* Memory Allocated: 6048 MB
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.2.3
* Additional Content Installed: No

**Comment by sam-kirby** [comment]
The Curseforge launcher recently suffered from an issue that caused the contenttweaker configuration to be overwritten. This means the mapping between IDs of the blocks we add have become confused.

Try repairing the modpack. If that doesn't work, create a new copy of the modpack and copy your save across.

As this is not an issue with the modpack I am closing this issue.
