### ISSUE TITLE
Keeping charm makes inventory dissapear if totem of undying gets triggered

### ISSUE THREAD

**Issue by antoine-courant** [DarkPacks/SevTech-Ages#4761]
Minecraft Version: 1.18.2

Forge Version: 40.1.60

Mod Version: 4.1.1184

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Hello ! I was hanging around the end with my keeping charm III in a curios slot, then I died, but I had a totem of undying in one of my other slots, so it got used, and I didn't died, but my inventory/armors dissapeared, and was not anywhere around
After making some researches, I found out it was because of the keeping charm, where you must click "respawn" to make it work properly, but because I didn't die, everything dissapeared :/

Maybe you should check it a totem or something else make us not dying before the keeping charm enables itself ?
To be more previse, it was the soulstone from Cyclic mode that got enabled, but it has the same effect as a totem of undying

Thanks in advance ! :)

**Comment by sam-kirby** [comment]
This is an interesting issue, but it's unclear what pack you're playing - SevTech has only been released for Minecraft 1.12.2 using Forge 14.23.5.2860 latest.

**Comment by antoine-courant** [comment]
To be clear, I'm playing a modified version of Better Minecraft plus, which I added few mods, including Cyclic and Twilight Forest
But the totem of undying is a vanilla item

**Comment by sam-kirby** [comment]
This is the issue page for SevTech Ages, a mod pack for 1.12.2. We don't make Better Minecraft, Cyclic or Twilight Forest, and the issue does not seem to occur in our pack. Please open an issue with someone relevant to the problem.

**Comment by antoine-courant** [comment]
Oh god, did I do a mistake ? My baad :/
The ticket is closed anyway because it wasn't with the good template
Thanks and sorry again
