### ISSUE TITLE
Suddenly unlocked all stages upon loading world.

### ISSUE THREAD

**Issue by gradientogames** [DarkPacks/SevTech-Ages#4766]
## Bug Description

I changed config to add a recipe for the primal core common stone. Now everything from every stage is suddenly unlocked upon entering game (besides achievements).

### Did this behavior use to work in the previous version?

No, when I updated the version, the config was reset so I had to add the recipe again but then upon loading in again the bug occurs.

## Steps to Reproduce (for bugs)

1.Add new recipe in SevtechAges/scripts/crafttweaker/recipes/mods/primal/core.zs
2.Reload sevtech via curseforge
3.Bug occurs

## Logs

* Client/Server Log: [log](https://gist.github.com/gradientogames/7bbe843b8989780775cfe159581c0544)
* Crash Log: none

## Client Information
* Modpack Version:3.2.3
* Java Version:1.8.0.351 64x
* Launcher Used:Curseforge
* Memory Allocated:7G
* Server/LAN/Single Player:Single Player
* Optifine Installed:Yes
* Shaders Enabled:No

## World Information
* Modpack Version world created in:3.1.3
* Additional Content Installed:none

**Comment by sam-kirby** [comment]
This doesn't sound like you've actually unlocked the stages, but instead you have introduced an error into the scripts causing the stages not to be setup and therefore everything is unlocked as nothing now requires a stage.

Please give details of the change you have made and attach the crafttweaker log (`./crafttweaker.log`).

**Comment by gradientogames** [comment]
Thx for replying. 
All I changed/added was in:
\scripts\crafttweaker\recipes\mods\primal\core.zs which in line 32 (under the Shaped Recipes section) I added:

	<primal:common_stone> * 4 : [
		[
			[<minecraft:stone>, <minecraft:cobblestone>, <minecraft:stone>]
			[<minecraft:cobblestone>, <minecraft:stone>, <minecraft:cobblestone>]
			[<minecraft:stone>, <minecraft:cobblestone>, <minecraft:stone>]
		]
	],

I did this in a previous version, so I don't know why it does this now. Also, the code seems pretty fragile if the code doesn't work with just an extra recipe (correct me if the new code is wrong.)

[crafttweaker.log](https://github.com/DarkPacks/SevTech-Ages/files/10339799/crafttweaker.log)

**Comment by sam-kirby** [comment]
From your log, an error has been introduced into the file you've edited, and it points to line 35.
```
[INITIALIZATION][CLIENT][ERROR] [crafttweaker | SIDE_CLIENT]: Error parsing crafttweaker\recipes\mods\primal\core.zs:35 -- ] expected
```

It is, however, a little misleading - the `]` is present, but you're missing the commas separating each array of ingredients. It should be:
```js
<primal:common_stone> * 4 : [
	[
		[<minecraft:stone>, <minecraft:cobblestone>, <minecraft:stone>],
		[<minecraft:cobblestone>, <minecraft:stone>, <minecraft:cobblestone>],
		[<minecraft:stone>, <minecraft:cobblestone>, <minecraft:stone>]
	]
],
```
