### ISSUE TITLE
CaftTeaker crash in loading screen

### ISSUE THREAD

**Issue by KiltCross** [DarkPacks/SevTech-Ages#4779]
## Bug Description
I tried to load the game, but when it finish the loading it crash

### Did this behavior use to work in the previous version?
This is the first installation and I haven't even enter the main menu.

## Steps to Reproduce (for bugs)
1.  Start the game
2. It loads the game
3. It crashes before showing the main menu

## Logs

* Client/Server Log: [client_crash_log](https://pastebin.com/uXPVcDm0)
* Crash Log: [crash_log](https://pastebin.com/sNFBdR0y)

## Client Information
* Modpack Version: 3.2.2
* Java Version: openjdk 8
* Launcher Used: LauncherFenix-Minecraft-v7
* Memory Allocated: 6GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: No world has been created.
* Additional Content Installed: None

**Comment by sam-kirby** [comment]
The installed mod versions do not match any version of the pack we've released. We are unable to support modified packs.
