### ISSUE TITLE
Stuck looking up

### ISSUE THREAD

**Issue by cn-ofc** [DarkPacks/SevTech-Ages#4782]
chronological order of my actions:
- I just got the mod
- created a single player world
- constantly was slowly looking up
- waited a couple of weeks
- tried again
- created a new world
- same problem occurred
- played for a while trying to ignore the problem
- tried crafting but with significant difficulty
- opened menu
- researched for a long time noticing there is no information about this bug
- restarted forge
- came back
- still not working
- noticed the report bugs button
- created a bug report

## Client Information
* Modpack Version: 3.2.1
* Java Version:idk
* Launcher Used: Minecraft Forge
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: recent

- if you need more detail, feel free to ask.

**Comment by cn-ofc** [comment]
oh well...

**Comment by sam-kirby** [comment]
Did you change the BetterFPS algorithm?

If it's not currently set to Riven's Half change it back to that. If it is already, change it to vanilla.
