### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by mpangburn34** [DarkPacks/SevTech-Ages#4788]
"The advancements are really just a general concept of how to get somewhere. The rest is on you to figure out. We are not looking to provide a hand-holding experience."

The original problem is at large : Nowhere in the book does it tell you how to make a block of metal. Making an ingot? Locked in age 1. Love getting stuck at a certain spot due to poor documentation combined with zero help from the stubborn maintainers.

_Originally posted by @justinrusso in https://github.com/DarkPacks/SevTech-Ages/issues/1952#issuecomment-383143971_

**Comment by sam-kirby** [comment]
With respect to recipes such as the crafting of ingots and blocks, the game is largely self documenting. JEI shows you that you can cast blocks in a casting basin, or ingots on a casting table. The advancements guide you through creating a melter, which you can use to do this. It doesn't seem unreasonable for us to expect that the player can put two and two together at this point, particularly considering this is intended as an advanced pack for experienced modded players.

> zero help from the stubborn maintainers

You've not asked for help, you've come here with nothing but complaints. Regardless, despite you not giving any specifics hopefully my comment will have pointed you in the right direction. And if not, there are plenty of resources that may help you get further, from the [wiki](https://sevtechages.fandom.com/wiki/SevTech:_Ages_Wiki), to the numerous third party video tutorials, to the gameplay support channel on the Discord server (https://discord.gg/darkosto).

This issue page is not the avenue for gameplay questions however, as we try to keep it clear for tracking bugs in the pack.
