### ISSUE TITLE
Piston

### ISSUE THREAD

**Issue by TatsuyaBR** [DarkPacks/SevTech-Ages#4792]
## Bug Description

try crafting piston using jei. On crafting table/station or RS
[18:52:20] [Netty Local Client IO #2/ERROR] [FML]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes

## Steps to Reproduce (for bugs)

1. search piston in jei
2.click + button
3.done

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sam-kirby** [comment]
This is due to a long standing bug in Refined Storage; it has been resolved for later versions of Minecraft but the fix was not backported to 1.12.2 as far as I can tell, and so this issue is unlikely to be resolved in this pack.

Duplicate #2498, see there for further details.
