### ISSUE TITLE
java 1.8.0_51 in-game

### ISSUE THREAD

**Issue by USER1233466** [DarkPacks/SevTech-Ages#4794]
## Bug Description
<ive been told to update my java,Which i can see from the game by pressing f3,and in the top left i saw "java 1.8.0_58" which is from 2015,so how can i change it>

### Did this behavior use to work in the previous version?
<i dont know>

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:sevtech_ages_3.2.3
* Java Version:1.8.0_58
* Launcher Used:curseforage
* Memory Allocated:8G
* Server/LAN/Single Player:Single player
* Optifine Installed:yes
* Shaders Enabled:No

## World Information
* Modpack Version world created in:
* Additional Content Installed:no additional content installed

**Comment by sam-kirby** [comment]
We do not control which version of Java is used to launch the game, this is determined by your launcher and the available versions on your system.

Curseforge packages an extremely outdated version of Java 8 with their launcher and uses this by default, and it is this version that you seem to be using. Installing a more recent version on your system and selecting it for use in Curseforge can be beneficial, but is not necessary.

To do this, you would need to download and install a recent version of Java 8 (64-bit), and then select that version in Curseforge's Minecraft settings page.

I have not used Curseforge for many years as they do not have a version available for the OS I use, and therefore I am not in a position to be able to help you further with this.

As this issue does not describe a bug in the pack, I am closing it. Please use the Discord for support at https://discord.gg/darkosto

**Comment by USER1233466** [comment]
thank you very much
