### ISSUE TITLE
When trying to select shaders, the game crash

### ISSUE THREAD

**Issue by cold-viking** [DarkPacks/SevTech-Ages#4811]
## Bug Description

When trying to select any pack with shaders in the graphics settings, the game freezes and crashes after

### Did this behavior use to work in the previous version?
Don't try

## Client Information
* Modpack Version: 1.12.2
* Launcher Used: main mod packs

 
## Hellp
if you now? how i can select a shaders, tell me. And also tell me which shaders are better to use

**Comment by sam-kirby** [comment]
This is normal; the game has to reload all its resources.

You can change the shaders manually by editing `shaders.txt` whilst the game is closed.

If you need more detailed advice please ask on the Discord: https://discord.gg/darkosto
