### ISSUE TITLE
my power went out while playing and now my progress is reset even though the unlocked advancments are still there

### ISSUE THREAD

**Issue by kacpeG** [DarkPacks/SevTech-Ages#4814]
## Bug Description

power went out and now game thinks that i havent reached any age even though all the advancments are saved and crafting a work stump or other progress items doesnt fix it

### Did this behavior use to work in the previous version?

i dont know

## Steps to Reproduce (for bugs)

1.i was just playing
2.power went out
3.the end

## Logs

* Client/Server Log:there are no crash logs saved from this
* Crash Log:there are no crash logs saved from this

## Client Information
* Modpack Version:3.2.3
* Java Version:8 update 371
* Launcher Used:crystal launcher
* Memory Allocated:8gb
* Server/LAN/Single Player:single player
* Optifine Installed:yes
* Shaders Enabled:no

## World Information
* Modpack Version world created in:3.2.3
* Additional Content Installed:optifine

**Comment by kacpeG** [comment]
Is there really no way to fix this? am i supposed to just go fuck myself and no one will even try to help me?

**Comment by sam-kirby** [comment]
You should contact the author of the pack you are playing; it is not our pack as we have never released on Crystal Launcher.

**Comment by kacpeG** [comment]
> You should contact the author of the pack you are playing; it is not our pack as we have never released on Crystal Launcher.

but its literally your pack downloaded from curse forge, its not created by this launcher.
 Also i guess i fixed this issue by finding the advancements folder and deleting it and now im giving my self the items with creative in order to be able to use my stuff
