### ISSUE TITLE
Game crashes on the 4th step of initialization, seamingly due to Galacticraft Core

### ISSUE THREAD

**Issue by DanijelMerli** [DarkPacks/SevTech-Ages#4823]
## Bug Description

After a clean installation of minecraft and the mod, on first (and every other) launch during the 4th step of initialization the game crashes. I've updated Java 8 to the latest version, updated my graphics drivers to latest version, tried running minecraft as Administrator just in case, tried reinstalling minecraft multiple times, reinstalling the modpack in multiple ways (curseforge, other launchers, manually) and multiple versions (3.2.3, 3.2.2, 3.2.1, and 3.2.0). In all of these cases I get the same reason for crash.
Same error appears on my friends PC, so the issue probably lays somewhere in the installation steps. Maybe there's something we need to install before trying to install the mod? None of the tutorials I've seen had anything extra, but it's all I can think of.

### Did this behavior use to work in the previous version?
Nope, this is my first time installing this modpack.

## Steps to Reproduce (for bugs)
1. Install modpack trough Curseforge, TLauncher, MultiMMC, or manually
2. Try to launch the game
3. ???
4. Profit

## Logs
* Client/Server Log:
* Crash Log: https://pastebin.com/rX3n2Fts

## Client Information
* Modpack Version: 3.2.3
* Java Version: java version "1.8.0_381"  Java(TM) SE Runtime Environment (build 1.8.0_381-b09)
* Launcher Used: TLauncher (in this specific case), tried in other launchers also as I've mentioned
* Memory Allocated: 5GB
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: Probably not, not sure what those are

## World Information
* Modpack Version world created in: No worlds yet
* Additional Content Installed: Nothing additional

**Comment by sam-kirby** [comment]
Could you please attach your debug log (`logs/debug.log`) via https://gist.github.com or similar.

**Comment by DanijelMerli** [comment]
> Could you please attach your debug log (`logs/debug.log`) via https://gist.github.com or similar.

I don't have a debug.log file, but I do have a latest.log one, I hope that's what you need. Here's the [gist link](https://gist.github.com/DanijelMerli/fc9f45ff48ebf4c719917392dd779a7d).

**Comment by Sciti** [comment]
Any updates on this?

**Comment by sam-kirby** [comment]
Yes; changes introduced to bypass Minecraft's account requirements have caused this issue. We do not support piracy and so this issue is being closed.
