### ISSUE TITLE
Server Wont Reboot After a Temporary Shutdown

### ISSUE THREAD

**Issue by Jcyber15** [DarkPacks/SevTech-Ages#4830]
## Bug Description

So I briefly stopped the server instance so I could update my physical server and now the server instance and its backups wont reboot.

### Did this behavior use to work in the previous version?

This is the first version I've used for a server

## Steps to Reproduce (for bugs)

1. Create a server instance using the provided template on curseforge
2. Place a MohistMC and custom batch run script with java variable arguments
3. Start up the server
4. Join the server for any amount of time
5. Stop the server
6. Restart the server and wait for the crash on boot
https://youtu.be/uNb-Coi_mIM

## Logs

* Client/Server Log: [latest.log](https://github.com/DarkPacks/SevTech-Ages/files/13061134/latest.log)
* Crash Log: [crash-2023-10-21_16.42.10-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/13061135/crash-2023-10-21_16.42.10-server.txt)

## Client Information
* Modpack Version: 3.2.3
* Java Version: JDK 21
* Launcher Used: Modified Default Launcher
* Memory Allocated: 120GB (only uses 60GB max on client side)
* Server/LAN/Single Player: Server
* Optifine Installed: Yes
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.2.3
* Additional Content Installed: No

## Server Information
* Java Version: SE Binary 8 (for the instance, the server natively run JDK 21)
* Operating System: Windows 10 Home (Modded for server use)
* Hoster/Hosting Solution: My personal servers
* Sponge (Non-Vanilla Forge) Server: MohistMC

**Comment by sam-kirby** [comment]
Mohist is unsupported; see my more detailed response here: https://github.com/DarkPacks/SevTech-Ages/issues/4497#issuecomment-770167126
