### ISSUE TITLE
world generating as superflat bedrock on default settings

### ISSUE THREAD

**Issue by TTVOmegaGaming119** [DarkPacks/SevTech-Ages#4838]
![2023-12-09_03 21 40](https://github.com/DarkPacks/SevTech-Ages/assets/93915931/3dec7b1b-6e65-4d32-bc06-f9ef0a639e43)
not entirely sure what is causing my world to generate like this even does it when i generate it using a server

**Comment by sam-kirby** [comment]
What mod are those crystals from?

**Comment by TTVOmegaGaming119** [comment]
thaumcraft i removed them even removed anything that could affect world gen still didnt change im currently trying on a fresh install seeing if that fixed anything. I was scrolling through the logs and there was no kind of error thrown during generation and it didnt matter what type i chose even on custom itd still be the same
