### ISSUE TITLE
No footstep sounds

### ISSUE THREAD

**Issue by RohanSlazar** [DarkPacks/SevTech-Ages#4843]
## Bug Description

No sound of footsteps. This is persistant and world specific. When creating a different world the bug is not present, even if said world has the same seed. Reloading sounds with F3 + T or relaunching the game does not fix it.

### Did this behavior use to work in the previous version?

 Never played a previous version.

## Steps to Reproduce (for bugs)

 I really don't know (sorry...)

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: v3.2.3
* Java Version: 8
* Launcher Used: Prism v8.0
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: 1.12.2_HD_U_G5_MOD
* Shaders Enabled: No

## World Information
* Modpack Version world created in: v3.2.3
* Additional Content Installed: None

**Comment by sam-kirby** [comment]
Do you mean player footsteps, mob footsteps or both?

If player footsteps, could you be wearing some piece of armour that negates the sound?

**Comment by RohanSlazar** [comment]
Nevermind, I found the issue. It was the Wolf Pelt Boots who were muffling the footstep sounds :P
