### ISSUE TITLE
Corrupt NBT data

### ISSUE THREAD

**Issue by UtkuOzkutucu** [DarkPacks/SevTech-Ages#4845]
## Bug Description
We were playing with my friends, we played just one day. After closing the server we couldn't get it going, we didn't change any file or didn't do anything so I'm clueless. We are getting "the state engine was in incorrect state server_starting and forced into state server_stopped" Error

### Did this behavior use to work in the previous version?
We just started playing so we didn't know any previous versions

## Steps to Reproduce (for bugs)
Really Don't have Any idea

## Logs

* Client/Server Log: https://pastebin.com/0rKQWUxp
* Crash Log: https://pastebin.com/GffWg8FR

## Client Information
* Modpack Version: 3.2.3
* Java Version:
* Launcher Used:CurseForge
* Memory Allocated:8GB
* Server/LAN/Single Player: Server
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in: 3.2.3
* Additional Content Installed:None

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by Craigehton** [comment]
What is your Java version?

**Comment by sam-kirby** [comment]
This was solved on [Discord](https://discord.gg/darkosto) at https://discord.com/channels/329440410839678986/427521856413630474/1203796909089620069

The issue in this case was that the world was corrupt and needed to be restored from a backup. I have updated the title of this issue as the state engine error is a red herring that appears when the server crashes for almost any reason during startup.
