### ISSUE TITLE
Issue when attempting to play Totemic Cerimonies.

### ISSUE THREAD

**Issue by Cailisto** [DarkPacks/SevTech-Ages#4859]
## Bug Description

 Totemic ceremony Flute not playing as secondary instrument when attempting to play, Zaphkiel Waltz.

### Did this behavior use to work in the previous version?
3.2.1
It worked fine when I was playing then.

## Steps to Reproduce (for bugs)

 Am able to reproduce results multiple times.
1. Sneak select wind chimes to start ceremony
2. Sneak select flute as secondary instrument
3. Flute takes over as primary instrument instead of secondary

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:3.2.3
* Java Version:1.12.2
* Launcher Used:Curse Forge/Minecraft Launcher
* Memory Allocated:16G
* Server/LAN/Single Player:Single Player
* Optifine Installed:No
* Shaders Enabled:No

## World Information
* Modpack Version world created in:3.2.3
* Additional Content Installed:No

**Comment by Cailisto** [comment]
Well I feel dumb started a creative test world, results were not the same. Ceremony played properly, issue might be only with my the world I made. More tests and comments to come if issue resolves itself.

**Comment by Cailisto** [comment]
Results: Issue may arise because location of ceremony blocks(10 blocks next to spawn), or placement of ceremony blocks. Tested 100 blocks away from spawn location of my world and the issue did not pop up, Zaphkiel waltz, worked properly. Also placed all blocks in ceremony next to spawn in a different layout, issue did not repeat. The issue was probably just user error, lmao.

**Comment by sam-kirby** [comment]
I've seen this before when there's more than one totem base in range - could that have been your issue?
