### ISSUE TITLE
optifine crashing when entering world

### ISSUE THREAD

**Issue by SageOD** [DarkPacks/SevTech-Ages#4860]
hi i have the laters version of the modpack installed, and using at launcher with my actual account, no cracked accounts, the game worked fine, but i tried installing optifine, now it opens the game and everything is fine but i cant load the world it just crashes instantly, as soon as i try launching a new world same thing happens, is there a fix?

the potifine version im using is(OptiFine_1.12.2_HD_U_E3)

the crash report link is(https://mclo.gs/bOyl4Mh)

**Comment by sam-kirby** [comment]
You don't list the version of the modpack you're playing, but it sounds like you're using an old version of Optifine; here are the versions we have tested for each version of the pack:

> For SevTech v3.1.3 and up, use Optifine G6 pre if you want to use shaders or Optifine G5 if not.
> For SevTech v3.1.0-3.1.2, use Optifine F4 or F5.
> For SevTech v3.0.8, you must use Optifine D3 or earlier.
