### ISSUE TITLE
Textures missing from items while in Tinkers crafting station.

### ISSUE THREAD

**Issue by Cailisto** [DarkPacks/SevTech-Ages#4865]
## Bug Description

A few items do not have any textures while in the tinkers crafting station, and while I am not sure if this is something that can be resolved from yall's side, I just wanted to let you know. 
Base Minecraft: Chest, Trapped Chest, Shulker(all colors), Ender Chest
Ender Storage:  Ender Chest, Ender Tank
The Betweenlands: Weedwood Chest, Compost Bin, Purifier, Infuser, Censur, Animator, Alembic, Gecko Cage, Mortar, Menhir, Repeller, Dark Druid Altar, Tar Pot of Chance, Monster Spawner
The Twilight Forest: Every Shader Bag, Every Trophy, Moonworm, Cicada, Firefly
Astral Sorcery: Floating Crystals, Rock Crystal Sample
RFTools: Screen
Mod grinding Utils: Mob Masher
![image](https://github.com/DarkPacks/SevTech-Ages/assets/168575856/3c67bbd3-073a-48bb-be0b-a8834cf4999e)
While I understand some Items are not Obtainable in survival mode, I feel that these items should have textures. There might also be more items that I missed, tried to get all I could find.

### Did this behavior use to work in the previous version?

Not sure, I only found them when I was trying to make hoppers, so I scanned the creative inventory for more.

## Steps to Reproduce (for bugs)

Place items into Crafting Station and there are no textures present.
1. Unfortunate
2. Big
3. Sadge

## Logs

* Client/Server Log: No log
* Crash Log: No log

## Client Information
* Modpack Version:3.2.3
* Java Version:1.12.2
* Launcher Used:Curse Forge
* Memory Allocated:16g/1024m
* Server/LAN/Single Player:Single player
* Optifine Installed:No
* Shaders Enabled:No

## World Information
* Modpack Version world created in:3.2.3
* Additional Content Installed:No

**Comment by Cailisto** [comment]
I also found more Items that simply do not appear (ie...The Betweenlands Shields) while in the crafting station, but I focused on the ones that showed the missing texture (texture)

**Comment by sam-kirby** [comment]
Unfortunately this can't be resolved; this applies to basically anything that uses a Tile Enitity Special Renderer or the equivalent for displaying on the player (I can't recall the name off the top of my head). These renderers could rely on a tile entity or player being present, which it can't be if the block hasn't been placed in the world or equipped by a player, and so rendering these items must be blanket disabled to prevent crashes.

**Comment by Cailisto** [comment]
Ah, well that's to bad, but reasonable.
