### ISSUE TITLE
Firepit cooks faster than Kiln

### ISSUE THREAD

**Issue by rtandbk** [DarkPacks/SevTech-Ages#4868]
## Bug Description
Firepit using oak logs cooks wolf meat faster than clay kiln using low grade charcoal.

### Did this behavior use to work in the previous version?
This is a fresh install with no previous version used/played

## Steps to Reproduce (for bugs)
1. Create low grade charcoal in kiln with oak logs
2. Put any raw meat in kiln
3. Meat is not cooked at expected.

## Client Information
Version: 3.2.3
Java 8
Curseforge
20gb Allocated
Singleplayer
No Optifine
No shaders

## World Information
Modpack Version world created in: 3.2.3
Sphax Resourcepack

https://github.com/DarkPacks/SevTech-Ages/assets/19803636/fa38ca7b-bf83-4d57-b809-9a6c47a0926c

**Comment by sam-kirby** [comment]
The kiln does not act as a generic furnace and only the recipes listed in JEI will work. It is not capable of cooking meats. Most recipes are focussed on firing clay, as you might expect for a kiln.
