### ISSUE TITLE
I can't craft coal generator using asral sorcery

### ISSUE THREAD

**Issue by rallyguard** [DarkPacks/SevTech-Ages#4872]
![image](https://github.com/user-attachments/assets/d141e571-151f-43cb-b3af-47fc322a4cd2)
![image](https://github.com/user-attachments/assets/f569f4fd-abe8-4cb7-a64c-59c481250d3d)

**Comment by sam-kirby** [comment]
I think you might need more power? Try raising the altar up. If that doesn't work, please open a new issue providing as much of the requested information as you are able to.
