### ISSUE TITLE
Celestial Altar does not work

### ISSUE THREAD

**Issue by Caxapok975** [DarkPacks/SevTech-Ages#4876]
Bug description
My friend and I reached the 2nd era and in order to finish it, we need to make a coal engine, but our celestial altar refuses to work and burns red without receiving energy. I've watched a lot of videos on how to build it correctly, but everything is built correctly.

Did this behavior use to work in the previous version?
I don't know, I haven't checked.

Steps to Reproduce (for bugs)
The construction of the altar and the relay to it.

**Comment by sam-kirby** [comment]
I suggest joining https://discord.gg/darkosto and asking for help in #sevtech-gameplay

**Comment by Caxapok975** [comment]
![image](https://github.com/user-attachments/assets/7bd2ff4e-88ee-4edc-9e89-49d7195fc3c7)
