### ISSUE TITLE
cant play

### ISSUE THREAD

**Issue by only1karmajust1** [DarkPacks/SevTech-Ages#4879]
## Bug Description

when i walk the world flips and flips wntil i stop i cant play like this

### Did this behavior use to work in the previous version?

idk i am new to sevtech ages

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:latest 
* Java Version:latest 
* Launcher Used:tluncher
* Memory Allocated:14 gb usable
* Server/LAN/Single Player:singleplayer
* Optifine Installed:yes
* Shaders Enabled:idk

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sam-kirby** [comment]
> Usually this happens when people change the BetterFPS algorithm to one that is incompatible with their hardware. Reset the BetterFPS algorithm to Riven's Half. If it is already set to Riven's Half, set it to vanilla.

I left this response on the last issue created; did it help?

**Comment by only1karmajust1** [comment]
thx

**Comment by only1karmajust1** [comment]
it worked
