### ISSUE TITLE
Disappearing Wooden Hopper

### ISSUE THREAD

**Issue by AdherentTea4921** [DarkPacks/SevTech-Ages#4880]
Bug Description
It's a simple but annoying bug. When I try to place a hopper under me, jump and place it doen in the last frames of the jump, the wooden hopper disappears. I am not sure if the issue relates only to the wooden version or to all types of hoppers

Did this behavior use to work in the previous version?
I don't know, I have been playing this modpack for a few days and have only played on the current version

Steps to Reproduce (for bugs)
1. Get a wooden hopper
2. Look down under you and jump
3. As you start falling during the jump, try placing the wooden hopper under you
PS (I did this in a 1x2x1 space, I am not sure if it works with bigger spaces around the player)

Client Information
* Modpack Version: 3.2.3
* Java Version: 1.12.2
* Launcher Used: Minecraft Launcher opened through Forge, Chrome
* Memory Allocated: Mem: 85% Allocated: 100%
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

World Information
* Modpack Version world created in: 3.2.3
* Additional Content Installed: No

**Comment by sam-kirby** [comment]
https://github.com/user-attachments/assets/f4f2a96c-d6da-49b8-b007-d0f7f9ddd719

I was unable to reproduce this.
