### ISSUE TITLE
salted hide doesn`t become dried hide after i hang it

### ISSUE THREAD

**Issue by CrowXen** [DarkPacks/SevTech-Ages#4883]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sam-kirby** [comment]
You haven't given me much to work with here.. It's possible you're using "Item Racks" (for displaying items) and not "Drying Racks" (for drying items). They are visually very similar.
