### ISSUE TITLE
Crash while loading world

### ISSUE THREAD

**Issue by aura123lol** [DarkPacks/SevTech-Ages#4888]
## Bug Description
my whole ui is purple and black in main menu and when i try to load a world it crahses

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:![latestlog.txt](https://github.com/user-attachments/files/18147158/latestlog.txt)

## Client Information
* Modpack Version:3.23
* Java Version:1.12.2
* Launcher Used:pojav 
* Memory Allocated: 2480
* Server/LAN/Single Player:single player
* Optifine Installed:yes
* Shaders Enabled:no

## World Information
* Modpack Version world created in:
* Additional Content Installed:

**Comment by sam-kirby** [comment]
Looks like there's some issue with the arm64 build of LWJGL you're using; not our issue.
