### ISSUE TITLE
All Vanilla Dye Recipes Need to be converted to giving Pickle Tweaks Dye

### ISSUE THREAD

**Issue by Darkosto** [DarkPacks/SevTech-Ages#593]
![image](https://user-images.githubusercontent.com/10309699/37172059-c5a7f558-22dd-11e8-974f-f45ae8d89f07.png)

**Comment by justinrusso** [comment]
Ah.. of course theres those sneaky recipes.

**Comment by justinrusso** [comment]
After discussion we are going to leave the ones left as they will be handled when clearing out those machines in a later state
