### ISSUE TITLE
With fast horses, the Astikoor cart disconnects

### ISSUE THREAD

**Issue by MrHrulgin** [DarkPacks/SevTech-Ages#698]
Beta 3:

The cart from Astikoor regularly disconnects from the horse towing it, even across flat ground. Maybe a horse speed issue?

**Comment by Nightcaste** [comment]
I am having this issue in release version 3.0.6.

My carts also simply vanish before I can return to reconnect to them.

**Comment by justinrusso** [comment]
https://minecraft.curseforge.com/projects/astikoor/issues/13

**Comment by justinrusso** [comment]
This will be fixed when a mod update is released for it. Unfortunately due to the rate at which the mod is updated I would rather not have this sit on our tracker until a time where the mod is updated.
