### ISSUE TITLE
Making Slabs with Stairs Recipe

### ISSUE THREAD

**Issue by TwilightPSN** [DarkPacks/SevTech-Ages#705]
Playing on the most recent downloadable version from discord, ive come across the issue when trying to make cobble stairs. If you make the bottom row (i.e. slab recipe) before any of the other stairs pieces it will attempt to make slabs even with the stairs recipe in the crafting table.

Edit - Tested to make sure wasnt a ui glitch and isnt it takes all the cobble and gives yu 3 slabs thus loosing 3 cobble per craft

![2018-03-18_10 14 50](https://user-images.githubusercontent.com/37508557/37566957-6fda3472-2a96-11e8-990d-643ad0e0efab.png)

**Comment by artdude543** [comment]
Okay, this is still an issue in 3.0.3 it seems if you start the craft from the top slot and use the click and hold feature to fill you'll get the stair recipe. But removing the top slot will change it to the slab recipe. This needs more testing and work out what could be causing this.

**Comment by hresad** [comment]
This is an ongoing issue in 3.0.6. If you use the normal stair recipe you get slabs, if you invert the stair recipe you get stairs. JEI shows the classic vanilla layout.

![2018-04-14_00 48 13](https://user-images.githubusercontent.com/16922222/38781043-dc59464c-40df-11e8-9552-5c7f44d9201d.png)

**Comment by Butterlegz** [comment]
I found that if I started filling the crafting table from the bottom I got slabs, but if I filled the crafting table from the top I got stairs.

**Comment by tahg** [comment]
This is not limited to stairs/slabs.  If you remove the right most stack, that shape will get you a crafting table.

**Comment by tahg** [comment]
I've now limited it to CraftTweaker specifically, with no other mods installed and have filed an issue here: https://github.com/CraftTweaker/CraftTweaker/issues/534.

**Comment by artdude543** [comment]
Will be fixed when 3.1.0 lands 😄
