### ISSUE TITLE
Using Lit-Fibre Torches to Make Torches?

### ISSUE THREAD

**Issue by Vyraal1** [DarkPacks/SevTech-Ages#797]
### Issue / bug
 - Right now to make Torches from Primal Tech Torches, they need to be unlit, which is the minority of torches you make (since you usually light them up immediately after crafting), would it be possible to add in another recipe using the lit torches to make upgraded toches?

**Comment by vadis365** [comment]
sigh

**Comment by Vyraal1** [comment]
Sorry, I'm a bit confused about the sigh, was this intentional then that Lit Torches cannot be upgraded, and only unlit? 

1) Is there a way to put out torches automatically or convert lit torches? I only causally checked through JEI,
2) If it was intentional, I think I missed the design point, but I didn't think it was intentional since I saw the the pack had custom crafttweaker scripts designed for torch upgrades in the first place for only the unlit torches, so I thought it was an oversight.

**Comment by monodemono** [comment]
Fixed #3229
