### ISSUE TITLE
Server Difficulty Bug

### ISSUE THREAD

**Issue by Speedy8g** [DarkPacks/SevTech-Ages#804]
Okay, so first off AMAZING pack. 
Version 3.0.1
I had the server on Hard difficulty for several hours, no mobs at all were spawning, or EXTREMELY rarely. I switched to Normal and its 'Normal'. Never seen anything like it before. It was recurring, as I switched multiple times between difficulties to make sure. Happy to send any server side info you may need. Thanks again!

**Comment by Speedy8g** [comment]
We couldnt get the shadow gems, and after 3 hours of looking and wondering I just by chance checked a different difficulty and it worked fine.

**Comment by Kurtok** [comment]
I am having the same issue. On both normal and hard mobs are rarely spawning. Its very annoying. The only thing I have done to the modpack is install Optifine.

**Comment by artdude543** [comment]
Going to close this as it's an older issue on an older version of the pack. If you still have this issue on the latest pack can make another issue, thanks!

**Comment by Flow86** [comment]
Hi,
ran into the same bug in 3.0.6 again? only non hostile mobs spawn (sheep, etc) :-1: no zombies, no monsters at all?

I tried switching the difficulty with /difficulty command, no change.

I'm running the game via a forge server

**Comment by justinrusso** [comment]
This does not appear to be related to SevTech_V2 profile as this issue was created before that existed.

**Comment by MrSmallish** [comment]
**I've found a solution!**
I've had this same problem and it drove me mad. I tried re-installing the pack, adding and removing mods and all sorts of nonsense just to try and make it work. Because I really really like this pack.

Anyway, here's how I got my mobs spawning again: **Open to LAN**.
It worked for me, so I hope it works for everyone else.
