### ISSUE TITLE
Memory Usage Analysis of SevTech Ages 3.0.1

### ISSUE THREAD

**Issue by asiekierka** [DarkPacks/SevTech-Ages#805]
I've done one for [Modern Skyblock 3](https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/8) before, here we go again.

**Memory usage:** 2400MB of Java heap on main menu post-forced-GC. That's high by 1.12.2 standards, but not the worst I've seen. You'll probably need a machine with 6GB of RAM and -Xmx4G as it is now.

**Key issues:**

* SmoothFont. The mod pre-loads all of the glyphs it plans to render smoothly in memory as 32-bit (8-bit RGB + alpha) images! This takes up a whooping **475 megabytes**, or 20% of the pack's main menu memory usage. The easy fix is for the mod developer to make it use grayscale bitmaps instead, shaving off 3/4ths of that (32-bit RGBA -> 8-bit grayscale, 475MB -> ~120MB) - the long-term fix is to make the mod generate BufferedImages dynamically as needed rather than preload. As this is a client-side-only mod, removing it is a sufficient workaround for low-RAM users.

**Notes:**

* Due to the high amount of items and blocks in the pack, JEI's lookup cache takes up 250 megabytes. This is 10% of the pack's memory usage. This is also a bit high, but unfortunately, there is nothing that can be done about it. FoamFix helps with this by removing the then-redundant vanilla search lookup cache (usually takes up about 60-70% of what JEI does, but JEI's is more featureful and easier to hook into vanilla than vanilla's is into JEI.)
* An early look implies that a few mods have blocks which generate a surprisingly high amount of baked models. Those should probably be moved to use dynamically generated baked models with caching where applicable, as I do in Charset. [Debugging information](http://paste.asie.pl/Eo2x). However, the total post-FoamFix usage of memory by baked models is ~600MB, which isn't an overly high result at all.

**Solutions:**

* Remove or make optional SmoothFont, as well as [report the issue to the mod author](https://minecraft.curseforge.com/projects/smooth-font/issues/1). This should save 350-500MB of RAM.
* Potentially work with mods implicated in the debug information for baked models. This will not save much, however - I expect 150MB in the best case.

The first solution alone should drop SevTech's main menu JVM heap memory usage under 2GB, which is fairly respectable for a 1.12.2 modpack of this mod count.

**Comment by jaredlll08** [comment]
@asiekierka smooth font is actually required on both the client and the server, you can't remove it from the client and then connect to the the server, they don't have a client only flag.

**Comment by asiekierka** [comment]
A new version of SmoothFont is available, as per [the issue](https://minecraft.curseforge.com/projects/smooth-font/issues/1).

Setting saveMemory to 2 should be a default; I would recommend checking if saveMemory=3 doesn't impact FPS; if it doesn't, set it to 3 by default.
