### ISSUE TITLE
Venus Fly Trap eats Astikoor Carts

### ISSUE THREAD

**Issue by Turmfalke2** [DarkPacks/SevTech-Ages#809]
hi,
So the world it littered with venus fly traps and wile the fly traps eating stray horses is a bit of a stretch, them instantly destroying your cart seems a bit odd.  
I would imagine a  horse drawn vehicle should destroy a venus fly trap, not the other way around.

**Comment by justinrusso** [comment]
Since the cart is an entity... maybe the hp of the cart can be increased with CraftTweaker?

**Comment by artdude543** [comment]
After reviewing this and going over the options we have. It's not something that easy to "patch". The plant is doing the job it was coded to do, to attack any entities which passed over it. I left a note with the dev of the cart mod in regards.

We could patch this elsewhere via our tweaker mod. But it's not something which high on the list of things we need to fix. So, for now, be careful where your riding and watch out for the traps! But if this becomes a bigger issue we shall look into it more one day.

_On a side note: The mod changed somewhat for the carts so it could even be fixed but has not tested._
