### ISSUE TITLE
Export Map Doesn't Work

### ISSUE THREAD

**Issue by stronkbad** [DarkPacks/SevTech-Ages#906]
![atlas](https://user-images.githubusercontent.com/37816659/37934186-710b33b0-311b-11e8-89ad-c341dbd3dd31.png)
 
 ### Issue / bug
 - Doesn't export map, just the markers.

**Comment by Darkosto** [comment]
Will check this out, I might need to get the Antique Atlas devs on this one.

**Comment by justinrusso** [comment]
Seems quite similar to https://github.com/AntiqueAtlasTeam/AntiqueAtlas/issues/173. Either way.. this is a mod bug and nothing we can really do about it.
