### ISSUE TITLE
Field Manual Opens for LAN Host When Other Connected Players Open The Manual

### ISSUE THREAD

**Issue by MaxFirestorm** [DarkPacks/SevTech-Ages#907]
Bug details - Whilst playing on a LAN as host, the connected player opened the Field Manual from the mod Prospectors, the manual was opened on my screen as host at the same time. While attempting this the other way around (host opening manual), the connected player did not have this happen and could play as normal.

MC version - 1.12.2
Forge version - forge-14.23.2.2634
Java version - 1.8.0_161 (64 bit)
Modpack version - 3.0.1

How to recreate - Host server as LAN and while hosting, have a connected player open the Field Manual

GIF - https://www.dropbox.com/s/pu2yticy9t2dtex/2018-03-26_22-35-00.gif (might need to be downloaded to actually move)

**Comment by Darkosto** [comment]
Tagging @oitsjustjose to remind him to check it out :)

**Comment by ScaCoyote** [comment]
Also had this issue with renaming the Improved Backpacks. Made sure it only happened when player connected to the host opens the book or renames the backpack and not the other way. Double checked all the books I had available to me and only had it happen with renaming the backpack and opening the field manual. 

Mod Version 3.0.4 
Java version 1.8.0_161

**Comment by oitsjustjose** [comment]
Fixed in https://github.com/oitsjustjose/Geolosys/commit/6bb8cbe79dab8d9e5672a282b72ba139b9b615cb
